import type { CuratedGame } from "./types";

export const CURATED_GAMES: CuratedGame[] = [
  {
    appId: 2988580,
    slug: "yakuza-0",
    arc: "kiryu",
    year: 1988,
    title: { ko: "용과 같이 0 Director's Cut", en: "Yakuza 0 Director's Cut" },
    summary: {
      ko: "시리즈 입문과 공략 동선을 동시에 잡기 가장 좋은 프리퀄.",
      en: "The cleanest starting point in the series and the easiest place to learn its completion rhythm.",
    },
    lead: { ko: "키류 / 마지마", en: "Kiryu / Majima" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "60h+",
      completion: "140-180h",
      note: {
        ko: "기존 단일 추정치가 너무 낮아 보였던 대표 작품입니다. 메인만 천천히 밀어도 60시간 이상을 잡는 편이 안전합니다.",
        en: "The old single estimate was especially misleading here. Even a relaxed main-story run can easily pass 60 hours.",
      },
    },
    difficulty: 3,
    missableCount: 7,
    engine: "Magical V Engine (PS3 carryover)",
  },
  {
    appId: 3717330,
    slug: "yakuza-kiwami",
    arc: "kiryu",
    year: 1995,
    title: { ko: "용과 같이 극", en: "Yakuza Kiwami" },
    summary: {
      ko: "0편에서 쌓인 관계를 원작 1편 리메이크로 바로 이어받는 핵심 축.",
      en: "The direct continuation of 0 and the modernized version of the original Yakuza 1.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "20-30h",
      completion: "80-100h",
      note: {
        ko: "Majima Everywhere와 컴플리션 리스트 때문에 100%는 메인보다 훨씬 깁니다.",
        en: "Majima Everywhere and the Completion List make 100% much longer than the main route.",
      },
    },
    difficulty: 3,
    missableCount: 4,
    engine: "Magical V Engine (PS3 carryover)",
  },
  {
    appId: 3717340,
    slug: "yakuza-kiwami-2",
    arc: "kiryu",
    year: 2006,
    title: { ko: "용과 같이 극2", en: "Yakuza Kiwami 2" },
    summary: {
      ko: "드래곤 엔진 초반부의 감각과 시리즈 대표 인기 에피소드를 함께 보여줍니다.",
      en: "A fan-favorite sequel and one of the strongest showcases of the early Dragon Engine era.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "25-35h",
      completion: "80-110h",
      note: {
        ko: "영구 Missable은 적지만 서브 콘텐츠와 클랜/캬바쿠라 정리가 시간을 크게 늘립니다.",
        en: "Few permanent traps, but substories, Clan Creator, and cabaret cleanup stretch the run.",
      },
    },
    difficulty: 3,
    missableCount: 6,
    engine: "Dragon Engine",
  },
  {
    appId: 3937550,
    slug: "yakuza-kiwami-3",
    arc: "kiryu",
    year: 2009,
    title: { ko: "용과 같이 극3", en: "Yakuza Kiwami 3 & Dark Ties" },
    summary: {
      ko: "오키나와·도쿄를 무대로 한 키류 사가 3편을 드래곤 엔진으로 리메이크. 신규 외전 「Dark Ties」가 동봉되어 보너스 시나리오 트로피가 함께 풀립니다.",
      en: "A Dragon Engine remake of Kiryu's Okinawa-and-Tokyo chapter, bundled with the new Dark Ties side scenario and its dedicated trophy line.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "35-45h",
      completion: "90-120h",
      note: {
        ko: "신규 리메이크/외전 구성이라 추정치는 보수적으로 표시합니다.",
        en: "Shown conservatively because the remake and Dark Ties package changes the route.",
      },
    },
    difficulty: 3,
    missableCount: 0,
    engine: "Dragon Engine",
  },
  {
    appId: 1088710,
    slug: "yakuza-3",
    arc: "kiryu",
    year: 2009,
    title: { ko: "용과 같이 3", en: "Yakuza 3 Remastered" },
    summary: {
      ko: "구식 감각이 남아 있지만 키류 사가 서사에는 빠질 수 없는 전환점입니다.",
      en: "Older and rougher, but essential for understanding where Kiryu's later arc is headed.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "20-30h",
      completion: "90-120h",
      note: {
        ko: "구작 미니게임과 장별 체크가 100% 시간을 크게 끌어올립니다.",
        en: "Older minigames and chapter checks make the 100% route much heavier than the story.",
      },
    },
    difficulty: 4,
    missableCount: 9,
    engine: "Magical V Engine (PS3 remaster)",
  },
  {
    appId: 1105500,
    slug: "yakuza-4",
    arc: "kiryu",
    year: 2010,
    title: { ko: "용과 같이 4", en: "Yakuza 4 Remastered" },
    summary: {
      ko: "4인 주인공 구조가 본격적으로 시작되는 구간.",
      en: "The point where RGG's multi-protagonist structure fully takes over.",
    },
    lead: { ko: "키류 외 3명", en: "Kiryu + 3" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "25-35h",
      completion: "80-110h",
      note: {
        ko: "4인 주인공 구조라 장 전환 전에 사이드 진행을 점검하는 시간이 필요합니다.",
        en: "The four-lead structure rewards extra checking before each protagonist handoff.",
      },
    },
    difficulty: 4,
    missableCount: 12,
    engine: "Magical V Engine (PS3 remaster)",
  },
  {
    appId: 1105510,
    slug: "yakuza-5",
    arc: "kiryu",
    year: 2012,
    title: { ko: "용과 같이 5", en: "Yakuza 5 Remastered" },
    summary: {
      ko: "분량과 사이드 콘텐츠 모두 시리즈 최고 수준인 장기전.",
      en: "A maximalist entry with one of the largest completion footprints in the series.",
    },
    lead: { ko: "키류 외 4명", en: "Kiryu + 4" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "45-60h",
      completion: "150-200h",
      note: {
        ko: "시리즈에서 가장 긴 축입니다. 하루카/어나더 드라마/컴플리션을 따로 예산 잡는 편이 좋습니다.",
        en: "One of the biggest runs in the series. Budget separately for Haruka, Another Drama, and full completion.",
      },
    },
    difficulty: 5,
    missableCount: 14,
    engine: "Magical V Engine (PS3 remaster)",
  },
  {
    appId: 1388590,
    slug: "yakuza-6",
    arc: "kiryu",
    year: 2016,
    title: { ko: "용과 같이 6", en: "Yakuza 6: The Song of Life" },
    summary: {
      ko: "키류 사가의 마지막 장을 정리하는 작품.",
      en: "The closing chapter of Kiryu's mainline story.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "18-25h",
      completion: "50-70h",
      note: {
        ko: "메인은 짧은 편이지만 클랜, 야구, 스낵, 서브스토리 정리가 남습니다.",
        en: "The story is compact, but clan, baseball, snack, and substory cleanup still add up.",
      },
    },
    difficulty: 3,
    missableCount: 5,
    engine: "Dragon Engine",
  },
  {
    appId: 2375550,
    slug: "like-a-dragon-gaiden",
    arc: "spinoff",
    year: 2023,
    title: { ko: "용과 같이 7 외전: 이름을 지운 자", en: "Like a Dragon Gaiden: The Man Who Erased His Name" },
    summary: {
      ko: "키류의 공백기를 직접 메우며 6편 이후와 8편 직전까지 연결하는 외전.",
      en: "Kiryu's missing-years side story that bridges Yakuza 6 to the lead-in for Infinite Wealth.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "12-18h",
      completion: "30-45h",
      note: {
        ko: "현대 작품 중 가장 짧은 축이지만 아카메/콜로세움/호스티스 정리는 별도 루프입니다.",
        en: "One of the shortest modern entries, with Akame, Coliseum, and hostess cleanup as the main extra loop.",
      },
    },
    difficulty: 3,
    missableCount: 5,
    engine: "Dragon Engine (Enhanced)",
  },
  {
    appId: 1805480,
    slug: "like-a-dragon-ishin",
    arc: "spinoff",
    year: 1867,
    title: { ko: "용과 같이 유신! 극", en: "Like a Dragon: Ishin!" },
    summary: {
      ko: "막부 말기를 배경으로 한 역사 외전. 본편과 다른 분위기에서 완주 분량이 크게 나오는 장기전입니다.",
      en: "A Bakumatsu-era historical spinoff with a very different tone and a large completion footprint.",
    },
    lead: { ko: "사카모토 료마", en: "Ryoma Sakamoto" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "30-40h",
      completion: "120-160h",
      note: {
        ko: "어나더 라이프, 대원 카드, 제작/파밍 때문에 플래티넘은 장기전입니다.",
        en: "Another Life, Trooper Cards, crafting, and farming turn the platinum route into a long haul.",
      },
    },
    difficulty: 4,
    missableCount: 0,
    engine: "Unreal Engine 4",
  },
  {
    appId: 1235140,
    slug: "yakuza-like-a-dragon",
    arc: "ichiban",
    year: 2019,
    title: { ko: "용과 같이 7", en: "Yakuza: Like a Dragon" },
    summary: {
      ko: "턴제 RPG로 완전히 넘어가며 새 주인공 체제를 여는 작품.",
      en: "The hard pivot to turn-based combat and Ichiban's true starting point.",
    },
    lead: { ko: "이치반", en: "Ichiban" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "45-60h",
      completion: "90-120h",
      note: {
        ko: "RPG 육성, 회사 경영, True Final Millennium Tower 준비 시간을 따로 봐야 합니다.",
        en: "Account for RPG leveling, business management, and True Final Millennium Tower prep.",
      },
    },
    difficulty: 3,
    missableCount: 8,
    engine: "Dragon Engine",
  },
  {
    appId: 2072450,
    slug: "like-a-dragon-infinite-wealth",
    arc: "ichiban",
    year: 2024,
    title: { ko: "용과 같이 8", en: "Like a Dragon: Infinite Wealth" },
    summary: {
      ko: "이치반과 키류가 함께 움직이는 대형 후속작. 하와이와 일본을 오가며 분량과 콘텐츠 규모가 크게 확장됩니다.",
      en: "The large-scale follow-up where Ichiban and Kiryu share the spotlight across Hawaii and Japan.",
    },
    lead: { ko: "이치반 / 키류", en: "Ichiban / Kiryu" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "60-80h",
      completion: "120-160h",
      note: {
        ko: "하와이/일본 양쪽의 링크, 던전, 도감형 콘텐츠가 100% 시간을 늘립니다.",
        en: "Links, dungeons, and checklist-heavy systems across Hawaii and Japan stretch the 100% route.",
      },
    },
    difficulty: 4,
    missableCount: 0,
    engine: "Dragon Engine",
  },
  {
    appId: 3061810,
    slug: "like-a-dragon-pirate-yakuza-in-hawaii",
    arc: "spinoff",
    year: 2025,
    title: { ko: "용과 같이 8 외전: Pirates in Hawaii", en: "Like a Dragon: Pirate Yakuza in Hawaii" },
    summary: {
      ko: "마지마 중심의 해적 외전. 하와이 이후의 분위기를 이어가면서 육상과 해상 액션 루프가 강조됩니다.",
      en: "A Majima-led pirate spinoff that extends the Hawaii setting with land-and-sea action routing.",
    },
    lead: { ko: "마지마", en: "Majima" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "25-35h",
      completion: "60-80h",
      note: {
        ko: "해상/콜로세움/미나토 걸 라인이 메인 이후 정리 분량을 만듭니다.",
        en: "Naval, Coliseum, and Minato Girl lines make up most of the post-story cleanup.",
      },
    },
    difficulty: 3,
    missableCount: 0,
    engine: "Dragon Engine",
  },
  {
    appId: 2058180,
    slug: "judgment",
    arc: "judgment",
    year: 2018,
    title: { ko: "저지먼트", en: "Judgment" },
    summary: {
      ko: "탐정 구조와 도시 탐사가 전면으로 나오는 스핀오프 축의 시작.",
      en: "The detective-side spinoff where investigation and city activity routing become central.",
    },
    lead: { ko: "야가미", en: "Yagami" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "25-35h",
      completion: "90-120h",
      note: {
        ko: "탐정 사이드케이스, 친구 이벤트, 미니게임이 플래티넘 시간을 크게 늘립니다.",
        en: "Side cases, friends, and minigames push the platinum route far beyond the story.",
      },
    },
    difficulty: 3,
    missableCount: 4,
    engine: "Dragon Engine",
  },
  {
    appId: 2058190,
    slug: "lost-judgment",
    arc: "judgment",
    year: 2021,
    title: { ko: "로스트 저지먼트", en: "Lost Judgment" },
    summary: {
      ko: "청춘 드라마, 타운고, 카이토 파일까지 완주 루트가 크게 확장된 후속작.",
      en: "A denser sequel with School Stories, TownGo, and a much wider cleanup route.",
    },
    lead: { ko: "야가미", en: "Yagami" },
    platforms: ["PC", "Steam"],
    timeEstimate: {
      story: "35-50h",
      completion: "100-140h",
      note: {
        ko: "청춘 드라마와 TownGo 정리가 핵심 병목입니다.",
        en: "School Stories and TownGo cleanup are the major bottlenecks.",
      },
    },
    difficulty: 4,
    missableCount: 7,
    engine: "Dragon Engine",
  },
];


export const RGG_APP_IDS = CURATED_GAMES.map((game) => game.appId);

export function getCuratedGameBySlug(slug: string) {
  return CURATED_GAMES.find((game) => game.slug === slug || String(game.appId) === slug) ?? null;
}
