import type { CuratedGame } from "./types";

export const CURATED_GAMES: CuratedGame[] = [
  {
    appId: 2988580,
    slug: "yakuza-0",
    arc: "kiryu",
    year: 1988,
    title: { ko: "용과 같이 0 Director's Cut", en: "Yakuza 0 Director's Cut" },
    summary: {
      ko: "시리즈 입문과 공략 동선을 동시에 잡기 가장 좋은 프리퀄.",
      en: "The cleanest starting point in the series and the easiest place to learn its completion rhythm.",
    },
    lead: { ko: "키류 / 마지마", en: "Kiryu / Majima" },
    platforms: ["PC", "Steam"],
    estimatedHours: "35h",
    difficulty: 3,
    missableCount: 7,
    engine: "Magical V Engine (PS3 carryover)",
  },
  {
    appId: 3717330,
    slug: "yakuza-kiwami",
    arc: "kiryu",
    year: 1995,
    title: { ko: "용과 같이 극", en: "Yakuza Kiwami" },
    summary: {
      ko: "0편에서 쌓인 관계를 원작 1편 리메이크로 바로 이어받는 핵심 축.",
      en: "The direct continuation of 0 and the modernized version of the original Yakuza 1.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    estimatedHours: "30h",
    difficulty: 3,
    missableCount: 4,
    engine: "Magical V Engine (PS3 carryover)",
  },
  {
    appId: 3717340,
    slug: "yakuza-kiwami-2",
    arc: "kiryu",
    year: 2006,
    title: { ko: "용과 같이 극2", en: "Yakuza Kiwami 2" },
    summary: {
      ko: "드래곤 엔진 초반부의 감각과 시리즈 대표 인기 에피소드를 함께 보여줍니다.",
      en: "A fan-favorite sequel and one of the strongest showcases of the early Dragon Engine era.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    estimatedHours: "40h",
    difficulty: 3,
    missableCount: 6,
    engine: "Dragon Engine",
  },
  {
    appId: 1088710,
    slug: "yakuza-3",
    arc: "kiryu",
    year: 2009,
    title: { ko: "용과 같이 3", en: "Yakuza 3 Remastered" },
    summary: {
      ko: "구식 감각이 남아 있지만 키류 사가 서사에는 빠질 수 없는 전환점입니다.",
      en: "Older and rougher, but essential for understanding where Kiryu's later arc is headed.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    estimatedHours: "45h",
    difficulty: 4,
    missableCount: 9,
    engine: "Magical V Engine (PS3 remaster)",
  },
  {
    appId: 1105500,
    slug: "yakuza-4",
    arc: "kiryu",
    year: 2010,
    title: { ko: "용과 같이 4", en: "Yakuza 4 Remastered" },
    summary: {
      ko: "4인 주인공 구조가 본격적으로 시작되는 구간.",
      en: "The point where RGG's multi-protagonist structure fully takes over.",
    },
    lead: { ko: "키류 외 3명", en: "Kiryu + 3" },
    platforms: ["PC", "Steam"],
    estimatedHours: "40h",
    difficulty: 4,
    missableCount: 12,
    engine: "Magical V Engine (PS3 remaster)",
  },
  {
    appId: 1105510,
    slug: "yakuza-5",
    arc: "kiryu",
    year: 2012,
    title: { ko: "용과 같이 5", en: "Yakuza 5 Remastered" },
    summary: {
      ko: "분량과 사이드 콘텐츠 모두 시리즈 최고 수준인 장기전.",
      en: "A maximalist entry with one of the largest completion footprints in the series.",
    },
    lead: { ko: "키류 외 4명", en: "Kiryu + 4" },
    platforms: ["PC", "Steam"],
    estimatedHours: "70h",
    difficulty: 5,
    missableCount: 14,
    engine: "Magical V Engine (PS3 remaster)",
  },
  {
    appId: 1388590,
    slug: "yakuza-6",
    arc: "kiryu",
    year: 2016,
    title: { ko: "용과 같이 6", en: "Yakuza 6: The Song of Life" },
    summary: {
      ko: "키류 사가의 마지막 장을 정리하는 작품.",
      en: "The closing chapter of Kiryu's mainline story.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    estimatedHours: "35h",
    difficulty: 3,
    missableCount: 5,
    engine: "Dragon Engine",
  },
  {
    appId: 2375550,
    slug: "like-a-dragon-gaiden",
    arc: "spinoff",
    year: 2023,
    title: { ko: "용과 같이 7 외전: 이름을 지운 자", en: "Like a Dragon Gaiden: The Man Who Erased His Name" },
    summary: {
      ko: "키류의 공백기를 직접 메우며 6편 이후와 8편 직전까지 연결하는 외전.",
      en: "Kiryu's missing-years side story that bridges Yakuza 6 to the lead-in for Infinite Wealth.",
    },
    lead: { ko: "키류", en: "Kiryu" },
    platforms: ["PC", "Steam"],
    estimatedHours: "30h",
    difficulty: 3,
    missableCount: 5,
    engine: "Dragon Engine (Enhanced)",
  },
  {
    appId: 1805480,
    slug: "like-a-dragon-ishin",
    arc: "spinoff",
    year: 1867,
    title: { ko: "용과 같이 유신! 극", en: "Like a Dragon: Ishin!" },
    summary: {
      ko: "막부 말기를 배경으로 한 역사 외전. 본편과 다른 분위기에서 완주 분량이 크게 나오는 장기전입니다.",
      en: "A Bakumatsu-era historical spinoff with a very different tone and a large completion footprint.",
    },
    lead: { ko: "사카모토 료마", en: "Ryoma Sakamoto" },
    platforms: ["PC", "Steam"],
    estimatedHours: "60h",
    difficulty: 4,
    missableCount: 0,
    engine: "Unreal Engine 4",
  },
  {
    appId: 1235140,
    slug: "yakuza-like-a-dragon",
    arc: "ichiban",
    year: 2019,
    title: { ko: "용과 같이 7", en: "Yakuza: Like a Dragon" },
    summary: {
      ko: "턴제 RPG로 완전히 넘어가며 새 주인공 체제를 여는 작품.",
      en: "The hard pivot to turn-based combat and Ichiban's true starting point.",
    },
    lead: { ko: "이치반", en: "Ichiban" },
    platforms: ["PC", "Steam"],
    estimatedHours: "55h",
    difficulty: 3,
    missableCount: 8,
    engine: "Dragon Engine",
  },
  {
    appId: 2072450,
    slug: "like-a-dragon-infinite-wealth",
    arc: "ichiban",
    year: 2024,
    title: { ko: "용과 같이 8", en: "Like a Dragon: Infinite Wealth" },
    summary: {
      ko: "이치반과 키류가 함께 움직이는 대형 후속작. 하와이와 일본을 오가며 분량과 콘텐츠 규모가 크게 확장됩니다.",
      en: "The large-scale follow-up where Ichiban and Kiryu share the spotlight across Hawaii and Japan.",
    },
    lead: { ko: "이치반 / 키류", en: "Ichiban / Kiryu" },
    platforms: ["PC", "Steam"],
    estimatedHours: "75h",
    difficulty: 4,
    missableCount: 0,
    engine: "Dragon Engine",
  },
  {
    appId: 3061810,
    slug: "like-a-dragon-pirate-yakuza-in-hawaii",
    arc: "spinoff",
    year: 2025,
    title: { ko: "용과 같이 8 외전: Pirates in Hawaii", en: "Like a Dragon: Pirate Yakuza in Hawaii" },
    summary: {
      ko: "마지마 중심의 해적 외전. 하와이 이후의 분위기를 이어가면서 육상과 해상 액션 루프가 강조됩니다.",
      en: "A Majima-led pirate spinoff that extends the Hawaii setting with land-and-sea action routing.",
    },
    lead: { ko: "마지마", en: "Majima" },
    platforms: ["PC", "Steam"],
    estimatedHours: "40h",
    difficulty: 3,
    missableCount: 0,
    engine: "Dragon Engine",
  },
  {
    appId: 2058180,
    slug: "judgment",
    arc: "judgment",
    year: 2018,
    title: { ko: "저지먼트", en: "Judgment" },
    summary: {
      ko: "탐정 구조와 도시 탐사가 전면으로 나오는 스핀오프 축의 시작.",
      en: "The detective-side spinoff where investigation and city activity routing become central.",
    },
    lead: { ko: "야가미", en: "Yagami" },
    platforms: ["PC", "Steam"],
    estimatedHours: "40h",
    difficulty: 3,
    missableCount: 4,
    engine: "Dragon Engine",
  },
  {
    appId: 2058190,
    slug: "lost-judgment",
    arc: "judgment",
    year: 2021,
    title: { ko: "로스트 저지먼트", en: "Lost Judgment" },
    summary: {
      ko: "청춘 드라마, 타운고, 카이토 파일까지 완주 루트가 크게 확장된 후속작.",
      en: "A denser sequel with School Stories, TownGo, and a much wider cleanup route.",
    },
    lead: { ko: "야가미", en: "Yagami" },
    platforms: ["PC", "Steam"],
    estimatedHours: "55h",
    difficulty: 4,
    missableCount: 7,
    engine: "Dragon Engine",
  },
];


export const RGG_APP_IDS = CURATED_GAMES.map((game) => game.appId);

export function getCuratedGameBySlug(slug: string) {
  return CURATED_GAMES.find((game) => game.slug === slug || String(game.appId) === slug) ?? null;
}
