import type { MinigamesData } from "./types";

const YT = (id: string) => `https://www.youtube.com/watch?v=${id}`;

// Minigame guides for Like a Dragon: Pirate Yakuza in Hawaii. Locations,
// unlock conditions, 偉業チャレンジ (Feat) targets and rank tables come from
// ゲーム攻略マン's per-play-spot pages, with ゲームエイト / 神ゲー攻略 for the
// pirate battle content that site does not cover. Every entry cites its page.
export const likeADragonPirateMinigames: MinigamesData = {
  appId: 3061810,
  intro: {
    ko: "마지마 고로가 해적이 되어 하와이와 마들랜티스를 누비는 외전. 뼈대는 고로마루를 몰고 벌이는 해적 배틀과 파이러츠 콜로세움이고, 그 바깥으로 시리즈 단골 플레이 스폿이 하와이·마들랜티스 양쪽에 흩어져 있습니다. 각 종목에는 「위업 챌린지」라는 단계별 목표가 붙어 있어 아래 항목마다 그 수치를 적어 두었습니다. 서로 다른 미니게임 10종을 플레이하면 트로피 「Party Pirate」.",
    en: "The spin-off where Goro Majima turns pirate across Hawaii and Madlantis. Its backbone is ship-to-ship pirate battle aboard the Goromaru and the Pirates' Coliseum, with the series' usual play spots scattered across both maps. Each spot carries tiered Feat Challenges, and their targets are listed per entry below. Playing ten different minigames gives the Party Pirate trophy.",
  },
  minigames: [
    {
      slug: "nautical-combat",
      name: { ko: "해적 배틀 (포격전·선상 결전)", en: "Pirate battle (cannon duel & boarding)" },
      category: { ko: "배틀", en: "Battle" },
      difficulty: 4,
      location: { ko: "각 해역 — 고로마루 승선 중", en: "The open sea aboard the Goromaru" },
      summary: {
        ko: "고로마루를 몰고 적선과 싸우는 본작의 골격. 대포로 적선을 항행 불능으로 만드는 「포격전」과, 멈춘 배에 올라타 마지마를 직접 조작하는 「선상 결전」 2단 구성입니다.",
        en: "The game's spine: sail the Goromaru against enemy ships, first shelling them into a dead stop, then boarding for a hands-on fight as Majima.",
      },
      howTo: [
        { ko: "적선도 포격을 되쏘므로, 미리 선체 장갑을 강화해 피해를 줄이거나 탄이 닿지 않는 위치로 돌아들어 가는 기동이 필요합니다. 강화를 미룬 채로는 상위 해역에서 버티기 어렵습니다.", en: "The enemy shoots back, so either armour the hull to absorb it or circle to where their guns don't reach — going into the higher sea areas unupgraded doesn't work." },
        { ko: "선상 결전은 마지마 조작의 액션 배틀이고 동료를 몇 명 데려갑니다. 배는 강화, 사람은 육성 — 둘 다 밀어야 전력이 오릅니다.", en: "Boarding is a normal action fight with a few crew alongside. The ship is upgraded and the crew is levelled — you need both lines pushed." },
        { ko: "2장에서 해적·배목수 클라크가 합류하고 줄리가 고로마루를 정비하면 선장실과 담화실이 열립니다. 선장실에서는 연회·회식과 가라오케를, 지하 담화실에서는 고로고로 키친·선원 교류·코디네이트·절 챗 회상을 할 수 있습니다.", en: "In Chapter 2, once shipwright Clark joins and Julie refits the Goromaru, the captain's cabin and lounge open — banquets, dinners and karaoke above, and the Goro Goro Kitchen, crew interaction, outfits and bond-chat replays below." },
        { ko: "연회(맥주 아이콘)는 고른 선원 전원의 사기를 크게 올리고 「해적 연회 냄비(5인분)」 또는 「공포! 해적 연회 지옥냄비(10인분)」가 필요합니다. 회식(와인 아이콘)은 사기가 조금 오르는 대신 경험치가 크게 오르고, 「해적 회식 세트」 5인분 1,250 / 10인분 2,000의 경험치가 들어옵니다. 요리는 미리 만들어 두세요.", en: "The banquet (beer icon) sharply raises morale for the chosen crew and needs the 5- or 10-serving pirate hotpot; the dinner (wine icon) nudges morale but pours in experience — 1,250 from the 5-serving set, 2,000 from the 10 — and both need the dishes cooked in advance." },
        { ko: "선원의 사기는 시간이 지나면 떨어지고, 떨어지면 능력도 같이 떨어집니다. 「호조」 이상을 유지하는 것이 기본 관리입니다. 급할 때는 선원에게 선물 아이템을 건네는 것만으로도 경험치와 사기를 올릴 수 있습니다(예: 호놀룰루 「레이와 꽃의 가게 메리아」의 팬지 꽃다발 = 경험치 500 + 사기 상승).", en: "Crew morale decays over time and their stats fall with it, so keep everyone at good or better. In a pinch, handing a crew member a gift raises both — the pansy bouquet from Melia's flower shop in Honolulu is worth 500 experience plus a morale bump." },
      ],
      videos: [
        { title: { ko: "노티컬 컴뱃 공식 개요 (PlayStation)", en: "Naval Combat Overview (official PlayStation)" }, url: YT("rGhbqRwvni0") },
      ],
      source: [
        { label: "神ゲー攻略 — 海賊バトルの特徴と流れ", url: "https://kamigame.jp/ryugagotoku8-gaiden/page/351260193897602932.html" },
        { label: "ゲーム攻略マン — ゴロー丸の機能", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/ship-goro-pirates/ship-goro-sistem.html" },
      ],
      achievementSlug: "goro_ship",
    },
    {
      slug: "pirates-coliseum",
      name: { ko: "파이러츠 콜로세움", en: "Pirates' Coliseum" },
      category: { ko: "배틀", en: "Battle" },
      difficulty: 5,
      location: { ko: "마들랜티스 — 콜로세움 접수처 (2장에서 노아를 구하면 해금)", en: "The Coliseum reception in Madlantis — unlocks when you save Noah in Chapter 2" },
      summary: {
        ko: "「해적 싱글 매치」·「선상 배틀 러시」·「파이러츠 챔피언십」·「해적 결투 쇼다운」 4개 모드로 구성된 투기장. 서로 다른 매치를 10승·20승·30승 하면 각각 트로피가 나오고, 전 모드를 제패하면 시리즈 전통의 아몬이 열립니다.",
        en: "Four modes — Pirate Single Match, Shipboard Battle Rush, Pirates' Championship and Pirate Duel Showdown. Winning 10, 20 and 30 different matches gives three trophies, and clearing every mode unlocks Amon.",
      },
      howTo: [
        { ko: "싱글 매치와 선상 배틀 러시에는 스테이지가 여러 개 있고, 해적 랭크를 올려야 상위 스테이지가 열립니다. 막히면 랭크를 먼저 올리세요.", en: "Single Match and Battle Rush have multiple stages gated behind your Pirate Rank — if you're stuck, go raise the rank first." },
        { ko: "S랭크를 노린다면 고로마루 강화가 가장 직접적입니다. 공략이 막힐 때 가장 먼저 손봐야 할 곳입니다.", en: "Upgrading the Goromaru is the most direct route to S rank, and the first thing to fix when you stall." },
        { ko: "마지마 조작 배틀도 있으므로 능력 강화를 미루지 마세요. 선상 배틀에서는 아이템을 쓸 수 없으니 기초 능력부터 집중적으로 올려 두는 편이 좋습니다.", en: "Some matches are played as Majima, and items are banned in the shipboard fights — so put ability points into raw stats early." },
        { ko: "선원과 지원 부대를 편성해 싸우므로 레어도 높은 선원을 모으고 레벨을 올려 두세요. 벽에 부딪히면 낮은 난이도를 돌아 선원 레벨을 올리는 편이 결국 빠릅니다.", en: "You field crew and a support unit, so collect high-rarity crew and level them; grinding a lower difficulty to raise crew levels is usually faster than banging on the wall." },
      ],
      source: { label: "ゲームエイト — パイレーツコロシアムの攻略と解放条件", url: "https://game8.jp/ryu-ga-gotoku8-gaiden/669352" },
      achievementSlug: "arena_c",
    },
    {
      slug: "dragon-kart",
      name: { ko: "드래곤 카트", en: "Dragon Kart" },
      category: { ko: "레이스", en: "Racing" },
      difficulty: 4,
      location: { ko: "호놀룰루 시티 하버파크 구역, 아나콘다 하버파크 (2장 서브스토리 No.7)", en: "Anaconda Harbor Park, Honolulu — via substory No.7 in Chapter 2" },
      summary: {
        ko: "거리를 카트로 달리며 아이템으로 라이벌을 격추하는 배틀 레이스. 2장의 서브스토리 No.7 「드래곤 카트 in 하와이」를 클리어하면 각 모드와 카트 세팅이 열립니다.",
        en: "A battle kart race through the streets, weapons and all. Substory No.7 in Chapter 2 unlocks the modes and kart setup.",
      },
      howTo: [
        { ko: "위업 챌린지는 리조트 컵·어반 컵·페스티벌 컵 우승, 카트 3종 입수, 카트 전 종류 입수, 그리고 3명이 주최하는 버서스 룰에서 각각 승리입니다.", en: "The Feats are winning the Resort, Urban and Festival cups, obtaining three karts, obtaining every kart, and beating each of the three hosts' Versus rules." },
        { ko: "코스의 아이템 박스에서 무기를 최대 2종까지 보유합니다. 카트의 내구력이 0이 되면 크래시로 시간을 크게 잃으므로, 공격만큼 회피도 중요합니다.", en: "Item boxes hold up to two weapons at a time. Losing all kart durability crashes you and costs serious time, so dodging matters as much as shooting." },
        { ko: "코스 위의 드래곤 링을 주우면 내구력이 회복되고, 모은 링은 경품과도 교환됩니다. 순위를 못 딸 판이라도 링을 주우며 도는 주회는 낭비가 아닙니다.", en: "Dragon Rings on the course repair durability and also buy prizes, so a lap spent collecting them isn't wasted even if the placing is lost." },
        { ko: "그랑프리 외에 타임 어택이 있고, 카트 세팅에서 성능을 업그레이드할 수 있습니다. 컵이 안 넘어가면 세팅부터 손보세요.", en: "Besides the Grand Prix there's a time attack, and kart setup upgrades performance — tune before retrying a cup you can't clear." },
      ],
      videos: [
        { title: { ko: "전 드래곤 카트 레이스 & 듀얼", en: "All Dragon Kart races & battles" }, url: YT("p2YFoBP7Fgs") },
        { title: { ko: "드래곤 카트 전 서브스토리 & 듀얼", en: "All Dragon Kart substories & duels" }, url: YT("OBDgy3k6Fo0") },
      ],
      source: { label: "ゲーム攻略マン — ドラゴンカート攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/dragon-kart/" },
      achievementSlug: "dragon_cart",
    },
    {
      slug: "crazy-delivery",
      name: { ko: "크레이지 딜리버리", en: "Crazy Delivery" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 4,
      location: { ko: "호놀룰루 시티 다운타운 구역, 선셋 파크", en: "Sunset Park, Downtown Honolulu" },
      summary: {
        ko: "자전거로 거리를 달리며 햄버거·피자·스시를 모아 손님에게 배달하는 종목. 스코어로 배달원 랭크를 올리고, 딜리버리 포인트를 경품과 교환합니다.",
        en: "Cycle the streets scooping burgers, pizza and sushi to customers. Score raises your courier rank and Delivery Points buy prizes.",
      },
      howTo: [
        { ko: "위업 챌린지는 누적 10만·30만·50만 달러 획득, 퍼포먼스 100·300·500회 성공, 배달원 랭크 최고 달성, 그리고 아나콘다 거리 코스를 전 난이도 A랭크 이상 클리어입니다.", en: "The Feats are $100k, $300k and $500k of cumulative earnings, 100/300/500 successful tricks, maxing the courier rank, and clearing every difficulty of the Anaconda Street course at A or better." },
        { ko: "조작은 8편과 같습니다. R2 전진, L2 브레이크(길게 누르면 후진), ○ 드리프트, × 점프, □ 크레이지 모드이고, 트릭은 좌스틱 방향 + ○입니다.", en: "The controls match Infinite Wealth's: R2 accelerate, L2 brake (hold to reverse), circle drift, cross jump, square Crazy Mode, and tricks are a stick direction plus circle." },
        { ko: "트릭으로 평가를 올린 뒤 배달하면 배달료가 올라갑니다. 8편과 마찬가지로 넘어지면 음식을 잃고 평가가 초기화되니, 코너는 드리프트로 감속 없이 돌면서 평가를 유지하세요.", en: "Deliver at a raised trick rating for more money, and — as in Infinite Wealth — crashing drops food and resets the rating, so drift the corners to keep speed and rating together." },
      ],
      videos: [
        { title: { ko: "슈퍼 크레이지 딜리버리 전 레벨 S랭크", en: "Super Crazy Delivery, all levels S Rank" }, url: YT("86mu5lmXQws") },
        { title: { ko: "크레이지 딜리버리 S랭크", en: "Crazy Delivery S Rank" }, url: YT("S8nZ8LeztYU") },
      ],
      source: { label: "ゲーム攻略マン — クレイジーデリバリー攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/crazy-delivery.html" },
      achievementSlug: "delivery_clear",
    },
    {
      slug: "goro-goro-kitchen",
      name: { ko: "고로고로 키친 (요리)", en: "Goro Goro Kitchen" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 2,
      location: { ko: "거리 곳곳의 요리 스폿(드럼통 스토브), 고로마루 담화실", en: "The drum-can stoves dotted around town, plus the Goromaru's lounge" },
      summary: {
        ko: "식재를 써서 요리를 만드는 시스템. 1장에서 감자 요리 튜토리얼로 해금되고, 요리는 전 14종입니다. 전부 만들면 트로피 「가정적인 일면」.",
        en: "Cook dishes from gathered ingredients — unlocked by the potato tutorial in Chapter 1, with fourteen recipes in all. Cooking every one gives the Domestic Pirate trophy.",
      },
      howTo: [
        { ko: "위업 챌린지는 누적 10·20·30회 조리와 5·10·14종 제작입니다. 14종은 2장 후반에 리치 섬의 고로 왕국에 접근하면 전부 갖춰집니다.", en: "The Feats are 10/20/30 cooks and 5/10/14 distinct dishes; the full fourteen become available late in Chapter 2 when you approach Goro Kingdom on Rich Island." },
        { ko: "식재는 고기·벌레·생선·청과·축산 5계통이고 레어도(★)가 있습니다. 레어도가 높은 식재일수록 필요한 개수가 줄어드니, 좋은 식재를 아끼기보다 쓰는 편이 총량으로는 이득입니다.", en: "Ingredients come in five lines — meat, bugs, fish, produce and livestock — with rarity stars; higher-rarity ingredients need fewer units, so spending the good ones actually costs less material overall." },
        { ko: "완성 요리에는 ★1~3 품질이 있고, 쓴 식재의 레어도와 조리 미니게임의 성공도로 결정됩니다. 품질이 높을수록 효과가 큽니다.", en: "Dishes finish at one to three stars, decided by ingredient rarity and how well the cooking minigame went; higher quality means a stronger effect." },
        { ko: "한 번에 만드는 개수를 늘리면 난이도가 「간단 → 보통 → 어려움 → 매우 어려움 → 극악」으로 올라갑니다. 확실히 하고 싶다면 1개씩 만드세요.", en: "Batching raises the difficulty step by step from easy up to brutal, so cook one at a time when quality matters." },
        { ko: "2장부터는 「애니멀 간식의 극」을 만들 수 있습니다. 고로 왕국의 여러 동물의 친밀도를 한 번에 올리고 답례 식재도 한꺼번에 받을 수 있어, 왕국 진행의 핵심 아이템입니다.", en: "From Chapter 2 you can cook the Ultimate Animal Treat, which raises several Goro Kingdom animals' affection at once and returns their gift ingredients in one go — the key item for that side of the game." },
      ],
      videos: [
        { title: { ko: "고로고로 키친 첫 4가지 요리", en: "Goro Goro Kitchen: first 4 dishes" }, url: YT("yeSXMFls-Lw") },
      ],
      source: { label: "ゲーム攻略マン — ゴロゴロキッチン", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/walkthrough-data/gorogoro-kitchen.html" },
      achievementSlug: "cooking",
    },
    {
      slug: "goro-kingdom",
      name: { ko: "고로 왕국 (동물 사육)", en: "Goro Kingdom" },
      category: { ko: "경영·시뮬레이션", en: "Management / sim" },
      difficulty: 3,
      location: { ko: "리치 섬 주민가", en: "The residential district of Rich Island" },
      summary: {
        ko: "각지에서 보호한 동물을 기르는 시설. 1장에서 스텔라에게 닭 「피닉스」를 받아 공터로 데려가면 해금됩니다. 먹이를 주면 답례로 식재를 받고, 친밀도가 최대가 된 동물은 고로 해적단의 선원으로 합류합니다.",
        en: "A menagerie for the animals you rescue. Chapter 1 hands you the chicken Phoenix from Stella; taking her to the empty lot opens it. Feeding animals returns ingredients, and one whose affection maxes joins the crew.",
      },
      howTo: [
        { ko: "위업 챌린지는 동물 3·4·6종 수집, 먹이 5·15·30회, 「애니멀 간식의 극」 1회·5회 대접입니다.", en: "The Feats are collecting 3, 4 and 6 species, feeding 5, 15 and 30 times, and serving the Ultimate Animal Treat once and five times." },
        { ko: "2장에서 서브스토리 No.4 「제5지구의 새끼 고양이」가 강제 발생하고, 클리어하면 「동물 보호」 시스템이 열립니다. 이후 맵에 육구(발바닥) 아이콘이 표시된 곳에서 동물을 보호해 왕국으로 보낼 수 있습니다.", en: "Substory No.4 fires automatically in Chapter 2 and clearing it opens the Animal Rescue system — paw-print icons then appear on the map wherever an animal can be sent to the Kingdom." },
        { ko: "좋은 먹이일수록 받는 식재가 많아집니다. 한 번 먹이를 주면 10분 뒤에야 다시 줄 수 있으니, 돌아다니다 시간이 지나면 들르는 식으로 운용하세요.", en: "Better feed returns more ingredients. Each animal only accepts feed again after ten minutes, so treat it as something you drop in on between other errands." },
        { ko: "「애니멀 간식의 극」은 여러 동물의 친밀도를 한꺼번에 올리고 답례도 한 번에 받습니다. 이쪽도 준 뒤 10분 쿨타임입니다.", en: "The Ultimate Animal Treat raises several animals at once and collects all their gifts together — also on a ten-minute cooldown." },
      ],
      videos: [
        { title: { ko: "고로 킹덤 소개", en: "The Goro Kingdom" }, url: YT("P7Z2AVKY2xc") },
      ],
      source: { label: "ゲーム攻略マン — ゴロー王国", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/walkthrough-data/goro-kingdom.html" },
      achievementSlug: "goro_kingdom",
    },
    {
      slug: "sega-arcade",
      name: { ko: "세가 아케이드 (오션 헌터 등)", en: "SEGA arcade cabinets (incl. The Ocean Hunter)" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "호놀룰루 시티 아나콘다 게임센터", en: "Anaconda Game Center, Honolulu" },
      summary: {
        ko: "게임센터에 실제 세가 아케이드 6종이 수록돼 있습니다. 그중 「오션 헌터」는 지금까지 어떤 가정용 하드에도 이식된 적 없던 MODEL3 기판 타이틀로, 이번 작품의 최대 화제였습니다.",
        en: "Six real SEGA arcade cabinets sit in the game center. One of them, The Ocean Hunter, is a Model 3 title that had never been ported to any home hardware before — the headline inclusion of this game.",
      },
      howTo: [
        { ko: "수록 타이틀은 「버추어 파이터 3tb」, 「파이팅 바이퍼즈 2」, 「스파이크아웃」, 「오션 헌터」, 「SEGA RACING CLASSIC 2 POWER EDITION」, 「SEGA RACING CLASSIC 2 BATTLE ON THE EDGE」입니다.", en: "The line-up is Virtua Fighter 3tb, Fighting Vipers 2, Spikeout, The Ocean Hunter, SEGA RACING CLASSIC 2 POWER EDITION and SEGA RACING CLASSIC 2 BATTLE ON THE EDGE." },
        { ko: "「오션 헌터」는 바다 괴물을 총으로 사냥하며 보물을 찾는 수중 건 슈팅입니다. 해적을 다루는 본편 테마와 맞물려 신규 수록된 타이틀입니다.", en: "The Ocean Hunter is an underwater light-gun shooter about hunting sea monsters while searching for treasure — chosen to sit with the game's pirate theme." },
        { ko: "같은 게임센터에는 UFO 캐처도 있고, 이쪽은 별도의 위업 챌린지가 걸려 있습니다.", en: "The same arcade holds the UFO catcher, which has its own separate Feat Challenges." },
      ],
      source: { label: "GAZEMARU — 龍が如くシリーズ 各作品でプレイ可能なレトロゲーム一覧", url: "https://gazemaru.hateblo.jp/entry/2026/03/21/213000" },
    },
    {
      slug: "master-system",
      name: { ko: "세가 마스터 시스템", en: "SEGA Master System" },
      category: { ko: "레트로 게임", en: "Retro games" },
      difficulty: 1,
      location: { ko: "각 맵의 거점 — 하와이 섬(호놀룰루), 마들랜티스 동굴 구역, 리치 섬 (2장부터)", en: "The hideout on each map: Honolulu, Madlantis' cave area and Rich Island — from Chapter 2" },
      summary: {
        ko: "1987년 세가의 8비트 가정용 기기. 전 15종 중 5종은 처음부터 있고, 나머지는 각지 전당포에서 사서 늘립니다.",
        en: "SEGA's 1987 8-bit console. Five of the fifteen titles are there from the start; the rest are bought from pawn shops around the map.",
      },
      howTo: [
        { ko: "초기 수록 5종은 「포세이돈 워즈 3D」, 「알렉스 키드의 미라클 월드」, 「에일리언 신드롬」, 「두근두근 펭귄랜드 우주 대모험」, 「판타지 존」입니다.", en: "The five built-in titles are Poseidon Wars 3D, Alex Kidd in Miracle World, Alien Syndrome, Doki Doki Penguin Land and Fantasy Zone." },
        { ko: "구입처: 「판타지 존 II」·「갤럭시 포스」·「엔듀로 레이서」는 전당포 트레저 셀렉트 훌라 애비뉴점, 「아수라」·「SDI」는 차이나타운점, 「메이즈 워커」·「더블 타깃」·「스타 재커」는 아나콘다점, 「스페이스 해리어 3D」·「플리키」는 리버 스트리트점입니다.", en: "Where to buy: Fantasy Zone II, Galaxy Force and Enduro Racer at the Treasure Select pawn shop on Hula Avenue; Ashura and SDI in Chinatown; Maze Walker, Double Target and Star Jacker at the Anaconda branch; Space Harrier 3D and Flicky on River Street." },
        { ko: "위업 챌린지를 채우려면 상점에서 임의의 7종을 사서 합계 12종을 플레이해야 합니다. 클리어까지 갈 필요는 없습니다.", en: "The Feat needs seven purchased titles on top of the five, for twelve played in total — playing them is enough, clearing them isn't required." },
      ],
      source: { label: "ゲームエイト — マスターシステムの場所とゲーム一覧", url: "https://game8.jp/ryu-ga-gotoku8-gaiden/670987" },
    },
    {
      slug: "ufo-catcher",
      name: { ko: "UFO 캐처", en: "UFO catcher" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "호놀룰루 시티 아나콘다 게임센터 / 마들랜티스 유기장 (3플레이 5달러)", en: "Anaconda Game Center, Honolulu, and the Madlantis amusement floor (three plays for $5)" },
      summary: {
        ko: "크레인으로 경품을 집는 종목. 경품 종류가 아나콘다와 마들랜티스로 갈려 있어, 시리즈 컴플리트를 노린다면 양쪽을 다 돌아야 합니다.",
        en: "Crane game. The prize pools differ between Anaconda and Madlantis, so completing the series means working both.",
      },
      howTo: [
        { ko: "위업 챌린지는 경품 2·5·10개 획득과 경품 2·4·7시리즈 획득입니다.", en: "The Feats are winning 2, 5 and 10 prizes and completing 2, 4 and 7 prize series." },
        { ko: "조작은 × 두 번뿐입니다. 처음 × 길게 누르기로 가로 라인, 두 번째로 안쪽 라인을 정하면 팔이 내려갑니다.", en: "Two presses of cross is all there is: hold once to set the horizontal line and again for the depth, then the arm drops." },
        { ko: "플레이 횟수가 남아 있어도 ○로 중단할 수 있지만, 팔이 움직이는 중에는 중단되지 않습니다.", en: "Circle quits with plays remaining, but not while the arm is moving." },
      ],
      source: { label: "ゲーム攻略マン — UFOキャッチャー攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/ufo-catcher.html" },
    },
    {
      slug: "sicko-snap",
      name: { ko: "시코 스냅 (불심자 스냅)", en: "Sicko Snap" },
      category: { ko: "촬영", en: "Photography" },
      difficulty: 3,
      location: { ko: "호놀룰루 시티 와이키키 타운 동 구역, 알로하 비치 정류장 (2장 서브스토리 No.10)", en: "The Aloha Beach trolley stop, east Waikiki — via substory No.10 in Chapter 2" },
      summary: {
        ko: "트롤리 버스 차창에서 「파피용 보이」를 촬영하는 종목. 2장의 서브스토리 No.10 「불심자 스냅 어게인」을 시작하면 열리고, 이후 정류장의 쿠로키에게 말을 걸면 플레이할 수 있습니다.",
        en: "Photograph the Papillon Boys from the trolley window. Substory No.10 in Chapter 2 opens it, after which Kuroki at the stop runs it on demand.",
      },
      howTo: [
        { ko: "위업 챌린지는 파피용 보이즈 누적 50·100·200명 촬영, 코스 누적 1·3·5회 클리어, 크리스탈 파피용 촬영·포획, 그리고 트롤리 1·5·10회 승차입니다.", en: "The Feats are photographing 50, 100 and 200 Papillon Boys, clearing courses 1, 3 and 5 times, photographing and capturing the Crystal Papillon, and riding the trolley 1, 5 and 10 times." },
        { ko: "화면 중앙에 잡으면 프레임이 주황으로 바뀝니다. 그때 ×로 찍으면 성공이고, 한 명당 점수는 1회뿐입니다.", en: "Centre a target and the frame turns orange — shoot then. Each sicko only scores once." },
        { ko: "필름 잔량이 0이 되면 그 시점에 종료됩니다. 종료 시 클리어 스코어를 넘겼는지로 성공·실패가 갈립니다.", en: "Running out of film ends the run on the spot; clearing depends on whether you were over the target score when it ended." },
      ],
      source: { label: "ゲーム攻略マン — 不審者スナップ攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/snap-that-sickos.html" },
    },
    {
      slug: "karaoke",
      name: { ko: "가라오케", en: "Karaoke" },
      category: { ko: "음악·리듬", en: "Music / rhythm" },
      difficulty: 2,
      location: { ko: "호놀룰루 시티 리틀 재팬 구역 「리볼버」 / 고로마루 선장실", en: "Revolver in Little Japan, Honolulu, and the Goromaru's captain's cabin" },
      summary: {
        ko: "실존하는 JOYPad 쿄쿠나비와 콜라보한 터치패널 UI의 리듬 게임입니다. 플레이하는 장소에 따라 고를 수 있는 곡이 다르고, 고로마루에서 부르면 트로피 「염원의 선상 가라오케」를 받습니다.",
        en: "A rhythm game with a touch-panel interface built in collaboration with the real JOYPad Kyokunavi. The song list depends on where you sing, and singing on the Goromaru gives the Sea Shanties trophy.",
      },
      howTo: [
        { ko: "위업 챌린지는 2곡·4곡·7곡에서 85점 이상 내기입니다. DLC 악곡은 카운트에 포함되지 않습니다.", en: "The Feats are scoring 85 or better on 2, 4 and 7 songs — DLC tracks don't count toward it." },
        { ko: "곡 진행에 맞춰 흘러오는 아이콘이 라인에 겹칠 때 같은 버튼을 누릅니다. 길게 누르기와 연타 구간이 일부 섞여 있습니다.", en: "Press the matching button as each icon crosses the line, with a few held and mashed sections mixed in." },
        { ko: "고로 해적단의 테마송과 마지마 고로의 아이돌송 같은 신규 악곡이 추가돼 있습니다. 리듬 조작 없이 보기만 하는 회상 모드와 재생수 랭킹·하이스코어·이력도 볼 수 있습니다.", en: "New tracks include the Goro Pirates' theme song and a Majima idol number, and there's a Reminisce mode with no inputs plus play counts, high scores and history." },
      ],
      source: { label: "ゲーム攻略マン — カラオケ攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/karaoke.html" },
      achievementSlug: "karaoke_sea",
    },
    {
      slug: "darts",
      name: { ko: "다트 (DARTSLIVE3)", en: "Darts (DARTSLIVE3)" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "호놀룰루 시티 와이키키 타운 남 구역, 크리스탈 알로하 리조트", en: "Crystal Aloha Resort, south Waikiki" },
      summary: {
        ko: "다트라이브사의 DARTSLIVE3 콜라보 기체로 01 GAMES / STANDARD CRICKET / CENTER COUNT-UP / COUNT-UP 4종을 즐길 수 있습니다.",
        en: "A DARTSLIVE3 collaboration cabinet running 01 Games, Standard Cricket, Center Count-Up and Count-Up.",
      },
      howTo: [
        { ko: "위업 챌린지는 4종 룰 전부 플레이, 누적 2승, 누적 5승입니다.", en: "The Feats are playing all four rule sets, winning twice and winning five times." },
        { ko: "싱글은 숫자 그대로, 더블은 외주의 가는 영역으로 2배, 트리플은 3배입니다. 8외전에서는 어디를 노려야 하는지가 색으로 하이라이트되고 화면 상단에 텍스트로도 표시돼 이전작보다 훨씬 알기 쉽습니다.", en: "Singles score face value, the thin outer ring doubles and the triple ring triples. This game highlights the area you should be aiming at in colour and spells it out in text at the top of the screen, which makes it far more readable than earlier entries." },
      ],
      source: { label: "ゲーム攻略マン — ダーツ攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/darts.html" },
    },
    {
      slug: "shogi",
      name: { ko: "노상 장기", en: "Street shogi" },
      category: { ko: "보드게임", en: "Board game" },
      difficulty: 3,
      location: { ko: "호놀룰루 시티 리틀 재팬 구역, 사쿠라 스트리트", en: "Sakura Street, Little Japan, Honolulu" },
      summary: {
        ko: "순위전·시련 답파·쓰메쇼기 3종이 준비돼 있고, 이기면 장기 포인트를 받아 경품과 교환합니다.",
        en: "Ranking matches, Trial Run and tsume-shogi problems, paying Shogi Points for prizes.",
      },
      howTo: [
        { ko: "상대의 왕을 궁지에 몰면 승리, 이기기 한 수 전에 「왕수」를 선언합니다. 잡은 말은 자기 말로 쓸 수 있고 투료하면 패배입니다.", en: "Corner the enemy king to win, declaring check one move before; captured pieces come into your hand and resigning loses." },
        { ko: "적진 3열에 말이 들어가면 「왕」과 「금」을 제외한 말을 성(강화)시킬 수 있고, 성하면 움직임 자체가 바뀝니다.", en: "Pieces entering the opponent's back three ranks promote — everything except the king and gold — and promotion changes how they move." },
        { ko: "□가 무르기, L1이 슈퍼 무르기, △가 아이템 사용입니다. 불리해지면 아끼지 말고 쓰세요.", en: "Square takes a move back, L1 takes back further and triangle uses items — don't hoard them when the position turns." },
      ],
      source: { label: "ゲーム攻略マン — 将棋攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/syogi.html" },
    },
    {
      slug: "mahjong",
      name: { ko: "마작", en: "Mahjong" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "호놀룰루 시티 차이나타운 구역, 지하 마작 판타지아", en: "Underground Parlour Fantasia, Chinatown, Honolulu" },
      summary: {
        ko: "표준 4인 마작입니다. 난이도는 약탁·중탁·강탁과 레인보우 컵이 있습니다.",
        en: "Standard four-player mahjong, with weak, medium and strong tables plus the Rainbow Cup.",
      },
      howTo: [
        { ko: "위업 챌린지는 5회·10회 화료, 그리고 약탁·중탁·강탁에서 각각 1위입니다.", en: "The Feats are winning 5 and 10 hands, and taking first place at the weak, medium and strong tables." },
        { ko: "8외전에서는 조작이 간소화됐습니다. 이전에는 □로 리치를 선언했지만, 이번에는 역이 갖춰졌을 때 ×로 리치를 걸 수 있고 론·쯔모도 ×로 처리됩니다.", en: "The controls are simplified here: where the series used square to declare riichi, this game lets you riichi with cross when the hand is ready, and ron and tsumo are also cross." },
        { ko: "시작 전에 룰을 바꿀 수 있고 순위 우마는 착순에 따라 붙습니다. L1으로 버림패 확인, △로 룰 설명입니다.", en: "Rules are adjustable before you sit down and placement bonuses apply by finishing order; L1 reviews discards and triangle opens the rules." },
      ],
      source: { label: "ゲーム攻略マン — 麻雀攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/majan.html" },
    },
    {
      slug: "koi-koi",
      name: { ko: "코이코이 (화투)", en: "Koi-koi" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "호놀룰루 시티 리틀 재팬 구역, 도박장", en: "The gambling den in Little Japan, Honolulu" },
      summary: {
        ko: "화투 1대1 대전. 위업 챌린지는 목찰 1,500매·3,000매·7,500매 획득입니다.",
        en: "One-on-one hanafuda. The Feats are winning 1,500, 3,000 and 7,500 wooden tokens.",
      },
      howTo: [
        { ko: "8외전에서는 역이 성립할 것 같으면 화면 하단에 텍스트로 알려 주고, 성립하는 순간 장의 해당 화투가 반짝입니다. 역을 외우지 않아도 시각적으로 따라갈 수 있습니다.", en: "This entry tells you in text at the bottom of the screen when a yaku is close, and the relevant field cards sparkle as it completes — you can follow it without memorising the hands." },
        { ko: "선은 고른 패의 달이 빠른 쪽이고 이후로는 승자가 선을 잡습니다. 손패와 장에 같은 달의 패가 있으면 가져올 수 있고(가능하면 색 테두리가 붙습니다), 없으면 손패를 장에 놓은 뒤 산에서 1장 뽑습니다.", en: "The earlier month deals first and the winner deals after that. Match a month between hand and field to take the pair (the field card gets a coloured border), otherwise place a card and draw one from the stock." },
        { ko: "역이 완성되면 「코이코이한다」로 더 강한 역을 노릴지, 그 자리에서 승부를 낼지 고릅니다. 약한 역으로 도망칠지 강한 역을 노릴지가 승부처입니다.", en: "With a hand made, you either call koi-koi for something bigger or bank it — taking the small win or reaching for the big one is the whole decision." },
      ],
      source: { label: "ゲーム攻略マン — こいこい攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/koikoi.html" },
    },
    {
      slug: "oicho-kabu",
      name: { ko: "오이초카부", en: "Oicho-kabu" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "호놀룰루 시티 리틀 재팬 구역, 도박장", en: "The gambling den in Little Japan, Honolulu" },
      summary: {
        ko: "11·12월을 뺀 40장으로 하는 카드 도박. 위업 챌린지는 목찰 2,000매·5,000매·15,000매 획득입니다.",
        en: "Card gambling with the 40 cards from months one to ten. The Feats are winning 2,000, 5,000 and 15,000 tokens.",
      },
      howTo: [
        { ko: "친(딜러) 1명과 자(플레이어) 3명이 앉고, 승부는 친과 자 사이에서만 벌어집니다. 자끼리는 겨루지 않고, 친은 진행에 따라 교대합니다.", en: "One dealer and three players sit down, and only dealer-versus-player matters; players never compete with each other and the dealer role rotates." },
        { ko: "1월 패는 1, 5월 패는 5, 10월 패는 0으로 세고, 받은 2~3장 합계의 끝자리를 9에 가깝게 만드는 것이 목표입니다. 친보다 9에 가까우면 승리입니다.", en: "January counts as 1, May as 5, October as 0; get the last digit of your two or three cards closest to 9 and beat the dealer's." },
        { ko: "자는 처음에 어느 패로 갈지 고를 수 있습니다. 이 선택권이 유일하게 실력이 개입하는 지점입니다.", en: "As a player you choose which card to take first — that pick is the one place skill enters the game." },
      ],
      source: { label: "ゲーム攻略マン — おいちょかぶ攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/oichokabu.html" },
    },
    {
      slug: "casino",
      name: { ko: "카지노 (블랙잭·포커)", en: "Casino (blackjack & poker)" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "마들랜티스 술집 구역(저/고 레이트) / 마들랜티스 로열 카지노(VIP 레이트)", en: "The Madlantis tavern floor (low and high rates) and the Royal Casino (VIP rate)" },
      summary: {
        ko: "블랙잭과 텍사스 홀덤 포커. 위업 챌린지는 블랙잭 칩 10,000·50,000·150,000매, 포커 칩 5,000·25,000·75,000매 획득입니다.",
        en: "Blackjack and Texas Hold'em. The Feats are 10,000/50,000/150,000 chips at blackjack and 5,000/25,000/75,000 at poker.",
      },
      howTo: [
        { ko: "블랙잭은 딜러 1명에 플레이어 5명이 앉지만 기본적으로 딜러와의 1대1 승부입니다. 21에 가깝게 만들되 넘으면 버스트로 패배, 딜러가 22 이상이면 승리, 동점은 드로우입니다.", en: "Blackjack seats one dealer and five players but is fundamentally you against the dealer: get near 21 without busting, win if the dealer goes to 22 or more, and a tie is a draw." },
        { ko: "L2가 최소 BET, R2가 최대 BET이라 베팅이 빠릅니다. △로 아이템도 쓸 수 있습니다.", en: "L2 sets the minimum bet and R2 the maximum, and triangle uses items." },
        { ko: "포커는 4인 텍사스 홀덤입니다. 손패 2장 + 공유패 5장 중 가장 강한 5장으로 겨루고, 공유패는 3장 → 4장 → 5장 순으로 열리며 라운드마다 걸거나 내려갑니다.", en: "Poker is four-handed Texas Hold'em: your two hole cards plus five community cards, the board opening three, then four, then five, with a bet-or-fold decision each round." },
      ],
      source: [
        { label: "ゲーム攻略マン — ブラックジャック攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/blackjack.html" },
        { label: "ゲーム攻略マン — ポーカー攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/poker.html" },
      ],
    },
    {
      slug: "billiards",
      name: { ko: "당구", en: "Billiards" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 4,
      location: { ko: "호놀룰루 시티 제5지구 구역, 다이아몬드 헤드", en: "Diamond Head, District 5, Honolulu" },
      summary: {
        ko: "나인볼·로테이션·에이트볼·요쓰다마에 시리즈 특별 룰인 1샷 챌린지까지 5종입니다.",
        en: "Nine-ball, rotation, eight-ball and four-ball carom, plus the series' own One-Shot Challenge — five rule sets in all.",
      },
      howTo: [
        { ko: "위업 챌린지는 2승·4승·8승, 5종 룰 전부 플레이, 그리고 누적 1,000·3,000·6,000포인트 획득입니다.", en: "The Feats are 2, 4 and 8 wins, playing all five rule sets, and 1,000, 3,000 and 6,000 cumulative points." },
        { ko: "조준은 좌스틱 또는 방향키, 샷 세기는 우스틱을 기울인 정도로 정합니다. 적구를 넣으면 연속 샷이고, 수구가 적구에 맞지 않거나 수구를 넣으면 파울로 상대가 수구를 원하는 위치에 놓습니다.", en: "Aim with the stick or d-pad and set power by how far you push the right stick. Potting continues your turn; missing the object ball entirely or scratching hands ball-in-hand to the opponent." },
        { ko: "각도가 붙은 샷은 미세한 오차로 빗나가니 특수 샷을 익혀 두세요. 캐논 샷(수구를 튕겨 다른 적구), 키스 샷(맞은 적구가 다른 적구를 밀어 넣기), 콤비네이션 샷, 뱅크 샷(쿠션 반사)이 준비돼 있습니다.", en: "Angled shots miss on tiny errors, so learn the trick shots: cannon (deflect the cue ball onto another object ball), kiss (the struck ball drives a third), combination and bank (off the cushion)." },
      ],
      source: { label: "ゲーム攻略マン — ビリヤード攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/billiards.html" },
    },
    {
      slug: "golf",
      name: { ko: "골프 (타격 연습장)", en: "Golf (driving range)" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 3,
      location: { ko: "마들랜티스 유기장", en: "The Madlantis amusement floor" },
      summary: {
        ko: "니어핀 챌린지와 빙고 챌린지 2종. 획득 포인트는 경품과 교환합니다.",
        en: "The Near Pin and Bingo challenges, with points traded for prizes.",
      },
      howTo: [
        { ko: "위업 챌린지는 3회·10회 플레이, 니어핀 초급·중급·상급에서 각각 스코어 600 이상, 그리고 빙고 챌린지 누적 3라인·10라인입니다.", en: "The Feats are playing 3 and 10 times, scoring 600 or more on the beginner, intermediate and advanced Near Pin courses, and 3 and 10 cumulative bingo lines." },
        { ko: "먼저 R1으로 부감 모드로 바꿔 위에서 내려다보며 위치를 정하세요. 그 뒤 × 2회로 파워와 방향을 정합니다. 똑바로 보내려면 파란 아이콘 위치에 맞추고 빨간 게이지의 저스트 임팩트를 노립니다.", en: "Switch to the overhead view with R1 and pick the spot from above, then set power and direction with two presses of cross. For a straight ball, line up on the blue icon and stop the red gauge on Just Impact." },
        { ko: "저스트 임팩트 양옆의 노란 존은 훅과 슬라이스입니다. 왼쪽으로 치우치면 오른쪽으로, 오른쪽으로 치우치면 왼쪽으로 나가므로 미세 조정에 쓰세요.", en: "The yellow zones either side of Just Impact are the hook and slice: stopping left sends the ball right and stopping right sends it left, which is how you fine-tune." },
        { ko: "화면의 화살표가 바람의 방향과 세기입니다. 저스트 임팩트로 쳐도 바람이 있으면 휘므로 조준 자체를 미리 옮겨 두세요.", en: "The arrow shows wind direction and strength — even a Just Impact curves in wind, so offset the aim before the shot rather than after." },
      ],
      source: { label: "ゲーム攻略マン — ゴルフ攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/golf.html" },
    },
    {
      slug: "bang-bang-batting",
      name: { ko: "방방 배팅 센터", en: "Bang Bang Batting Center" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 4,
      location: { ko: "마들랜티스 술집 구역 (빅방방 코스 1회 100달러)", en: "The Madlantis tavern floor ($100 a run on the Big Bang Bang course)" },
      summary: {
        ko: "8외전에서 새로 추가된 종목입니다. 대포에서 날아오는 포탄을 배트로 받아쳐 폭약이 든 빨간 통에 맞히고, 폭발로 더 많은 통을 부수는 스코어 어택입니다. 「빅방방 코스」와 「엔들리스 방방 코스」 2종이 있습니다.",
        en: "New to this game: bat the incoming cannon shells into red powder barrels and chain the explosions for score. Two modes — the Big Bang Bang course and the endless one.",
      },
      howTo: [
        { ko: "위업 챌린지는 빅방방 코스 초급·중급·상급·초인급을 각각 A랭크 이상으로 클리어, 엔들리스 코스에서 10,000점 이상, 그리고 통 누적 200·500·1,000·2,000개 파괴입니다.", en: "The Feats are clearing the beginner, intermediate, advanced and superhuman Big Bang Bang courses at A or better, scoring 10,000 on the endless course, and destroying 200, 500, 1,000 and 2,000 barrels in total." },
        { ko: "핵심은 통을 전부 부수는 것이 아닙니다. 통을 어느 정도 부수면 거대한 보물상자가 나타나고, 그 자물쇠를 부수면 대량 득점과 함께 다음 스테이지로 넘어갑니다. 「어디를 부숴야 최단으로 상자가 나오는가」를 푸는 퍼즐에 가깝습니다.", en: "The goal isn't clearing every barrel: break enough and a giant chest appears, and smashing its lock scores big and advances the stage. It plays as a puzzle about which barrels expose the chest fastest." },
        { ko: "포탄은 5발 소지하고 스테이지가 넘어가면 4발까지 회복됩니다. 리절트에서는 남은 탄약이 많을수록, 그리고 필살기를 쓰지 않을수록 보너스가 붙으니 스코어를 노린다면 필살기(R2 자세)는 쓰지 마세요.", en: "You carry five shells and refill to four between stages. The results screen bonuses unspent ammunition and not using the special, so for score, leave the R2 special alone." },
        { ko: "배트는 시작 전에 고릅니다. 「보통 배트」가 균형이 좋아 무난하고, 하이스코어를 노리면 「달인 배트」, 초보자는 「안심 배트」(1,000pts 경품 교환, 맞히기 쉬운 대신 획득 포인트 0.8배)입니다.", en: "Pick a bat before you start: the normal bat is the balanced default, the master bat is for high scores, and the easy bat — 1,000 points at the prize counter — is easier to connect with but pays 0.8x." },
        { ko: "초급의 랭크 기준은 S 4,000 / A 2,000 / B 1,500 / C 1,000점(3스테이지, 클리어 보상 1.2배), 중급은 S 6,000 / A 4,000 / B 3,000 / C 2,000점(4스테이지)입니다. A랭크 이상으로 클리어해야 다음 계급이 열립니다.", en: "Beginner grades at 4,000 for S, 2,000 A, 1,500 B and 1,000 C across three stages with a 1.2x clear multiplier; intermediate is 6,000/4,000/3,000/2,000 across four. A rank or better unlocks the next class." },
      ],
      source: { label: "ゲーム攻略マン — バンバン・バッティングセンター攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/play-spots/bang-bang-batting.html" },
      achievementSlug: "banban_batting",
    },
    {
      slug: "license-school",
      name: { ko: "오우나바라 라이선스 스쿨", en: "Ounabara Vocational School" },
      category: { ko: "퀴즈", en: "Quiz" },
      difficulty: 2,
      location: { ko: "호놀룰루 시티 — 오우나바라 라이선스 스쿨", en: "The Ounabara Vocational School, Honolulu" },
      summary: {
        ko: "수험료를 내고 퀴즈를 풀어 자격을 따는 학교입니다. 자격마다 명성 포인트가 붙어 있어 해적 랭크를 올리는 수단이기도 합니다. 5종을 따면 트로피 「Erudite Pirate」입니다.",
        en: "Pay a fee, answer the quiz, collect certificates — each worth Fame, which feeds your Pirate Rank. Five certificates give the Erudite Pirate trophy.",
      },
      howTo: [
        { ko: "초기부터 볼 수 있는 시험 예: 「바다의 세계 검정」(명성 1,000, 수험료 무료), 「바다의 생물 박사」(명성 2,000, 500달러), 「근육 박사」(명성 1,000, 300달러), 「패션 리더」(명성 1,000, 300달러).", en: "Available from the start: the Sea World exam (1,000 Fame, free), Marine Life Doctor (2,000 Fame, $500), Muscle Doctor (1,000 Fame, $300) and Fashion Leader (1,000 Fame, $300)." },
        { ko: "무료인 「바다의 세계 검정」부터 보는 것이 손해가 없습니다. 명성이 1,000 붙으므로 초반 해적 랭크 올리기에 그대로 보탬이 됩니다.", en: "Start with the free Sea World exam — 1,000 Fame at no cost feeds straight into your early Pirate Rank." },
        { ko: "출처 페이지에는 각 자격의 수험 자격·시험 내용과 함께 퀴즈의 해답까지 정리돼 있습니다. 수험료를 반복해서 날리기 싫다면 미리 보고 들어가세요.", en: "The linked guide lists each exam's prerequisites and content along with the answers, which is worth reading first rather than paying the fee twice." },
      ],
      source: { label: "ゲーム攻略マン — 大海原ライセンススクール攻略", url: "https://dswiipspwikips3.jp/yakuza8-gaiden/ounabara-vocational-school/" },
      achievementSlug: "qualification",
    },
    {
      slug: "minato-girls",
      name: { ko: "미나토구계 여자 (실사 합동 미팅)", en: "Minato Girls (live-action group date)" },
      category: { ko: "연애·대화", en: "Dating / dialogue" },
      difficulty: 2,
      location: { ko: "3장 중반 — 선원 마사루의 상담에서 시작", en: "Mid-Chapter 3, from crew member Masaru's request" },
      summary: {
        ko: "합동 미팅을 하고 싶다는 선원 마사루의 소원을 들어주는 실사 영상 이벤트 계열입니다. 서브스토리 「동경의 미나토구계 여자」에서 시작해, 클리어하면 각 여성 캐릭터가 선원으로 합류합니다.",
        en: "A live-action strand built around crew member Masaru's wish to go on a group date. It starts with the substory \"The Minato Girls I Admire\", and clearing it recruits the women as crew.",
      },
      howTo: [
        { ko: "3장 중반에 마사루가 기운이 없는 이유를 물으면 시작됩니다. 진행하면 실사 영상으로 된 합동 미팅 장면을 볼 수 있습니다.", en: "It begins when you ask why Masaru is down, mid-Chapter 3, and plays out as live-action video of the group date." },
        { ko: "「동경의 미나토구계 여자」를 클리어하면 개별 서브스토리가 열립니다. 에나의 「#My new friend」, 미소시의 「Hello,world!」, 카호의 「Can You Keep A Secret?」 등입니다.", en: "Clearing the opening substory unlocks one per girl — \"#My new friend\" for Ena, \"Hello,world!\" for Misoshi, \"Can You Keep A Secret?\" for Kaho and so on." },
        { ko: "보상으로 합류하는 선원들은 레벨 상한이 높고 스킬을 가지고 있어 편성하기 좋습니다. 실사 파트가 취향이 아니더라도 전력 면에서 진행할 가치가 있습니다.", en: "The crew you get from it have high level caps and skills, so it's worth doing for the roster even if the live-action segments aren't your thing." },
      ],
      source: { label: "神ゲー攻略 — ミナト区系女子一覧", url: "https://kamigame.jp/ryugagotoku8-gaiden/page/351370832657792155.html" },
      achievementSlug: "minatoku",
    },
  ],
};
