import type { MinigamesData } from "./types";

const YT = (id: string) => `https://www.youtube.com/watch?v=${id}`;

// Minigame guides for Like a Dragon: Ishin! Locations, unlock conditions,
// completion thresholds and technique come from 神ゲー攻略's per-minigame and
// per-district pages, cited on each entry.
export const likeADragonIshinMinigames: MinigamesData = {
  appId: 1805480,
  intro: {
    ko: "막부 말기 교토가 무대인 외전. 미니게임 컴플리트를 전부 달성하면 방어구 「천룡인(天龍印)」을 받고, 모든 플레이 스폿을 한 번씩 플레이하면 트로피 「The Man Who Does It All」이 나옵니다. 도박 종목은 목찰 누적 점수(치리린·코이코이·오이초카부 7,500점, 포커·초한 15,000점)가 컴플리트 조건이라 승패보다 총량이 중요합니다. 경계(競鶏)는 이 게임에서 돈과 덕을 가장 빠르게 버는 수단입니다.",
    en: "A Bakumatsu-era spin-off set in Kyo. Completing every minigame gives the Tenryu Crest headgear, and playing every play spot once earns \"The Man Who Does It All\". The gambling entries complete on cumulative wooden-token points — 7,500 for cee-lo, koi-koi and oicho-kabu, 15,000 for poker and cho-han — so total volume matters more than any single win. Chicken racing is the fastest money and Virtue in the game.",
  },
  minigames: [
    {
      slug: "another-life",
      name: { ko: "어나더 라이프 (별택)", en: "Another Life (second home)" },
      category: { ko: "경영·시뮬레이션", en: "Management / sim" },
      difficulty: 4,
      location: { ko: "별택 (본편 진행으로 해금)", en: "Your second home, unlocked through the main story" },
      summary: {
        ko: "농사·낚시·요리·행상·펫으로 이루어진 생활 파트. 최종 목표는 행상 주문을 받아 납품하고 하루카의 빚을 전부 갚는 것으로, 완납하면 트로피 「World's Greatest Uncle」입니다.",
        en: "The life sim — farming, fishing, cooking, trading and pets. The end goal is filling trade orders until Haruka's debt is cleared, which gives the World's Greatest Uncle trophy.",
      },
      howTo: [
        { ko: "흐름은 ① 행상 주문 확인 → ② 요구 농작물·생선·요리 조달 → ③ 납품 → ④ 병행해서 펫을 늘리고 덕을 벌어 별택을 확충 → 반복입니다. 빚을 갚으려면 행상을 소화해 독촉장을 받아야 합니다.", en: "The loop is: check the trade orders, gather the crops, fish and dishes they ask for, deliver, and in parallel add pets and spend Virtue on expanding the house. Paying down the debt requires filling those orders to earn the demand notes." },
        { ko: "주문 품목은 사서 채울 수도 있지만, 트로피·컴플리트·정진목록을 함께 노린다면 직접 농사와 낚시로 조달하는 편이 낫습니다.", en: "You can buy what the orders want, but growing and catching it yourself also feeds the trophies, the completion list and the Diligence Records." },
        { ko: "개와 고양이는 각각의 서브스토리를 클리어하고 절을 최대로 올리면 펫이 됩니다. 해당 서브스토리는 「짖어대는 개」, 「마네키네코」, 「배고픈 고양이」, 「상처 입은 개」, 「기다리는 개」, 「더러워진 고양이」입니다. 닭과 시설 확충은 덕 교환으로 가능합니다.", en: "Dogs and cats become pets by clearing their substories and maxing the bond — the barking dog, the lucky cat, the hungry cat, the injured dog, the waiting dog and the dirty cat. Chickens and facility upgrades come from the Virtue exchange." },
      ],
      videos: [
        { title: { ko: "어나더 라이프 농사 가이드", en: "Another Life farming guide" }, url: YT("5BCSwtPpgHQ") },
      ],
      source: { label: "神ゲー攻略 — アナザーライフ(別宅)の攻略", url: "https://kamigame.jp/ryugagotoku-ishin/page/250359629643560204.html" },
      achievementSlug: "pay_back_all",
    },
    {
      slug: "buyo-dancing",
      name: { ko: "일본 무용 (니치부자)", en: "Japanese dance (Nichibuza)" },
      category: { ko: "음악·리듬", en: "Music / rhythm" },
      difficulty: 3,
      location: { ko: "라쿠나이 「니치부자」 (1회 1량 2,000문)", en: "Nichibuza, Rakunai (1 ryo 2,000 mon a play)" },
      summary: {
        ko: "노트를 맞춰 누르는 리듬 게임. 전 악곡을 아무 난이도로든 클리어하면 트로피 「Lord of the Dance」이고, 전 난이도를 「일류」 이상으로 클리어해야 컴플리트가 오릅니다.",
        en: "A note-matching rhythm game. Clearing every song on any difficulty gives Lord of the Dance; the completion list wants every difficulty cleared at first-class rank or better.",
      },
      howTo: [
        { ko: "화면 우상단 게이지가 차면 R1으로 「클라이맥스 연무」를 발동합니다. 발동 중에는 노트를 무시하면서 스코어가 쌓이므로, 합격점이 모자랄 때 확실한 보험이 됩니다.", en: "Filling the gauge in the top right lets R1 trigger the Climax Performance, which racks up score while ignoring notes — the reliable way to make a passing score." },
        { ko: "합격점 자체가 상당히 낮게 잡혀 있어 실수를 여러 번 해도 일류 평가는 나옵니다. 확실히 하고 싶을 때만 클라이맥스를 쓰면 됩니다.", en: "The pass line is set low enough that plenty of mistakes still leave you at first class, so the Climax is insurance rather than a requirement." },
        { ko: "몇 번 반복하면 「오히로메(선보임)」 이벤트가 발생합니다. 「후부키 코우타」의 최고 난이도를 플레이해야 하지만, 클리어하면 「양질의 나뭇조각」과 덕 +1,500을 받습니다.", en: "After a few plays the Ohirome event triggers: it puts you on Fubuki Kouta at its highest difficulty, but clearing it pays a fine wood scrap and 1,500 Virtue." },
        { ko: "출처 페이지에는 「후부키 코우타」, 「고동」, 「사무라이 연무」의 게이샤 난이도 보면(노트 배열)이 전부 텍스트로 적혀 있습니다. 외워서 치고 싶다면 그대로 참고하세요.", en: "The linked guide writes out the full Geisha-difficulty note charts for Fubuki Kouta, Kodou and Samurai Enbu as text, if you want to learn them by rote." },
      ],
      videos: [
        { title: { ko: "부채춤 플레이 가이드", en: "Buyo Dancing gameplay guide" }, url: YT("EBlH8xF75oE") },
        { title: { ko: "부채춤 미니게임 영상", en: "Buyo Dancing mini-game" }, url: YT("piJMr8shFoU") },
        { title: { ko: "전 곡 100% 퍼펙트 (게이샤 난이도)", en: "100% Perfect on every song (Geisha difficulty)" }, url: YT("Fl0bmzOTUvU") },
      ],
      source: [
        { label: "神ゲー攻略 — 日本舞踊", url: "https://kamigame.jp/ryugagotoku-ishin/page/252983667930974713.html" },
        { label: "神ゲー攻略 — 洛内のマップと施設一覧", url: "https://kamigame.jp/ryugagotoku-ishin/page/250940026324554324.html" },
      ],
      achievementSlug: "play_all_nihon_buyou",
    },
    {
      slug: "singing",
      name: { ko: "노래 주점 (우타마루야)", en: "Singing bar (Utamaruya)" },
      category: { ko: "음악·리듬", en: "Music / rhythm" },
      difficulty: 3,
      location: { ko: "후시미 「우타마루야」 (1곡 500문)", en: "Utamaruya, Fushimi (500 mon a song)" },
      summary: {
        ko: "화면의 아이콘에 맞춰 같은 버튼을 누르는 리듬 게임. 전 악곡을 부르면 트로피 「Sing Your Heart Out」이고, 컴플리트 항목 「당점의 간판 남자」와 최고 랭크 「분위기 신」이 따로 걸려 있습니다.",
        en: "Match the on-screen icon with the same button. Singing every song gives Sing Your Heart Out, with the completion entry and the top \"crowd god\" rank as separate goals.",
      },
      howTo: [
        { ko: "환경에 따라 입력 지연이 생기므로, 눈에 보이는 선보다 음악에 맞춰 누른다는 감각으로 치면 「우(優)」가 잘 나옵니다.", en: "Input lag varies by setup, so aim at the music rather than the visual line — that's what makes the top grade land." },
        { ko: "특수 노트 요령: 길게 누르기는 시작점을 정확히 누르고 버튼 표시보다 조금 늦게 떼고, 연타는 1초에 6회 이상을 목표로 하면 「우」가 나옵니다.", en: "For the special notes: on holds, start on time and release slightly after the marker ends; on mashes, aim for six-plus presses a second." },
        { ko: "추임새 곡은 「무난하게」와 「정열적으로」 중 고르는데, 무난하게는 최고 90점까지만 평가됩니다. 컴플리트와 최고 랭크를 노린다면 무난하게로 곡을 익힌 뒤 반드시 정열적으로 다시 치세요.", en: "Call-and-response songs offer a safe and a passionate option; the safe one caps at 90 points. Learn the song on safe, then take the passionate option for the completion entry and top rank." },
        { ko: "동반자 해금 조건이 각각 다릅니다. 하루카(「배고픈 날씨」)는 별택 빚을 전부 갚아야 하고 주인에게 500문을 먼저 내야 하며, 이쿠마쓰(「아수라 코마치」)는 10장 개시 이후입니다. 하루카를 뺀 나머지는 말을 걸면 해당 곡과 「의지 사쿠라」 2곡을 무료로 부를 수 있습니다.", en: "Duet partners unlock separately: Haruka (Harapeko Biyori) needs Haruka's debt fully repaid and a 500-mon fee to the owner, Ikumatsu (Ashura Komachi) needs Chapter 10 to have started. Apart from Haruka, talking to a partner gives their song plus Ijizakura free." },
      ],
      source: [
        { label: "神ゲー攻略 — 歌声酒場", url: "https://kamigame.jp/ryugagotoku-ishin/page/255738582411539699.html" },
        { label: "神ゲー攻略 — 伏見のマップと施設一覧", url: "https://kamigame.jp/ryugagotoku-ishin/page/253409800040228729.html" },
      ],
      achievementSlug: "play_all_utagoe_sakaba",
    },
    {
      slug: "udon-shop",
      name: { ko: "우동집 돕기", en: "Udon shop helper" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 3,
      location: { ko: "후시미 「우마이야」", en: "Umaiya, Fushimi" },
      summary: {
        ko: "손님 주문대로 정해진 버튼을 순서대로 누르는 암기 게임. 3초의 암기 시간이 지나면 버튼 표시가 사라집니다. 컴플리트 조건은 최고 랭크 「신」이고, 트로피는 매출 누적 10량입니다.",
        en: "Memorise each customer's order and press the buttons back in sequence — the prompts vanish after a three-second memorisation window. The completion condition is the top \"god\" rank, and the trophy wants 10 ryo of cumulative sales.",
      },
      howTo: [
        { ko: "가장 확실한 방법은 스마트폰으로 화면을 찍어 두는 것입니다. 암기 시간이 끝나 버튼이 가려져도 사진을 보고 그대로 누르면 됩니다.", en: "The reliable trick is photographing the screen with your phone — once the prompts hide, just read them off the photo." },
        { ko: "미니게임 중 OPTIONS로 중단할 수 있습니다. 중단하면 암기할 시간을 벌 수 있어 컴플리트까지 훨씬 편합니다.", en: "OPTIONS pauses mid-game, which buys you all the memorisation time you want and makes the completion run much easier." },
        { ko: "L1의 「추천」은 모든 주문을 하나로 통일해 줍니다. 입력 수용 시간이 짧은 단체 손님에게 쓰세요. 단체 손님은 획득 금액도 큽니다.", en: "L1's \"recommend\" unifies every order in a group. Save it for group customers, who have the tightest input window and the biggest payout." },
        { ko: "연속으로 성공할수록 입력 수용 시간이 짧아지고, 3회 실패하면 종료됩니다. 계급이 오르면 매출에 보정이 붙고 「사범」이 되면 단체 손님이 등장합니다. 초반부터 「신우치급」에 도전해 매출 5량 이상을 노리면 랭크 「신」이 빠릅니다.", en: "Each success tightens the input window and three failures end the run. Higher ranks apply a sales multiplier, and at Shihan rank group customers start appearing — going straight for Shin'uchi class and 5-plus ryo of sales is the quickest route to the god rank." },
        { ko: "랭크 「신」을 딴 뒤에는 절 올리기로 넘어갑니다. 절 상승량은 일정하고 실패해도 오르므로, 버튼을 최속으로 연타해 일부러 실패를 반복하면 됩니다. 8회 플레이 + 점장과 대화로 절이 최대가 됩니다.", en: "Once you have the god rank, switch to the bond: it rises a fixed amount whether you succeed or fail, so mash to fail instantly. Eight plays plus talking to the owner maxes it." },
      ],
      source: [
        { label: "神ゲー攻略 — うどん屋手伝いの攻略", url: "https://kamigame.jp/ryugagotoku-ishin/page/255742803307443966.html" },
        { label: "神ゲー攻略 — 伏見のマップと施設一覧", url: "https://kamigame.jp/ryugagotoku-ishin/page/253409800040228729.html" },
      ],
      achievementSlug: "udon_earn_total_10000",
    },
    {
      slug: "ageya",
      name: { ko: "유곽 오자시키 놀이 (술 대결·가위바위보·간호)", en: "Courtesan house games (drinking, janken, nursing)" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 5,
      location: { ko: "기온 「야마부키」 (1회 1량)", en: "Yamabuki, Gion (1 ryo a play)" },
      summary: {
        ko: "유곽에서 안나(杏南)를 상대로 「술 대결」·「가위바위보」·「간호」 3종을 플레이합니다. 세 종목을 각각 아수라급까지 클리어하는 것이 목표이고, 전부 클리어하면 트로피 「Like a Dragon in Heaven」입니다.",
        en: "Three games against Anna at the courtesan house: a drinking contest, janken and \"nursing\". The goal is clearing all three up to Ashura class, which gives Like a Dragon in Heaven.",
      },
      howTo: [
        { ko: "1회에 1량이 들고 컴플리트 보상까지 10회쯤 도전해야 하니 미리 10량을 준비하세요. 처음에는 「술 대결 → 가위바위보 → 간호」를 연달아 이겨야 단골이 되어, 이후 종목과 난이도를 자유롭게 고를 수 있습니다.", en: "Each attempt costs 1 ryo and you'll need roughly ten runs, so bring 10 ryo. You must first win drinking, janken and nursing back to back to become a regular — only then can you pick individual games and difficulties." },
        { ko: "안나와의 절이 최대가 되면 세이브해 두고, 클리어하면 세이브·실패하면 로드를 반복하면 쓸데없는 돈이 나가지 않습니다.", en: "Once Anna's bond is maxed, save — then save on a clear and reload on a failure so you stop burning money." },
        { ko: "술 대결 아수라급은 4잔째까지 승부를 내는 것이 전부입니다. 마시는 도쿠리 수가 1~2잔째 3개, 3~4잔째 4개, 5잔째 이후 5개로 늘어나기 때문입니다.", en: "Ashura-class drinking is about finishing inside four rounds: you drink three flasks in rounds one and two, four in rounds three and four, and five from round five on." },
        { ko: "술 대결에서 잔 게이지는 항상 절반 이상으로 유지하세요. 절반 아래로 떨어지면 마시는 데 시간이 걸려 안나의 취기가 깨버립니다. 반대로 「휴(休)」까지 내릴 필요는 없습니다 — 내리면 상대의 취기도 함께 깨서 승부가 영원히 안 납니다.", en: "Keep the cup gauge above half at all times: below half you drink too slowly and Anna sobers up. But never drop it all the way to \"rest\" — that sobers her too, and the contest never ends." },
        { ko: "가위바위보 아수라급은 다른 난이도와 크게 다르지 않고 심안을 쓰면 편합니다. 비겼을 때는 「내가 바위였으면 가위」, 「가위였으면 보」, 「보였으면 바위」를 내면 높은 확률로 이깁니다.", en: "Ashura janken plays like the lower tiers if you use the insight ability. After a draw, follow up with the hand that beats what you just threw — rock then scissors, scissors then paper, paper then rock — and you win most of the time." },
        { ko: "간호는 하트 모양의 핵을 쏘는 슈팅입니다. ○ 또는 □로 발사, 길게 누르면 차지 샷, △ 또는 ×로 봄. 3스테이지에서 핵을 부수면 클리어이고 글자에 4번 맞으면 패배입니다.", en: "Nursing is a shooter against a heart-shaped core: circle or square fires, holding charges, triangle or cross drops a bomb. Break the core across three stages to win; four hits from the falling characters loses." },
        { ko: "간호의 판정은 료마의 「머리」에만 있습니다. 몸은 신경 쓰지 말고 머리만 피하세요. 적 공격은 역八자와 ✕자 4줄 기준이라, 항상 ✕ 아래쪽 틈에 들어가 있으면 안전지대가 됩니다.", en: "Only Ryoma's head has a hitbox — ignore the body and keep the head clear. The attacks are built on an inverted-V and an X of four lines, so the gap under the X is a safe pocket." },
        { ko: "간호의 패턴은 「우좌우로 회피 → 공격 → 좌우좌로 회피 → 공격」의 반복으로 고정입니다. 봄은 큰 글자가 차지 샷을 방해하는 스테이지 3에서 쓰고, 플레이어가 다가가면 핵이 반대로 도망가는 성질을 이용해 좌우로 계속 움직이며 맞히세요.", en: "The nursing pattern is fixed: dodge right-left-right, attack, dodge left-right-left, attack. Save the bomb for stage 3 where big characters block the charge shot, and keep moving side to side — the core flees from you, which is what lets you time the shot." },
      ],
      source: [
        { label: "神ゲー攻略 — 遊郭（お座敷遊び）", url: "https://kamigame.jp/ryugagotoku-ishin/page/254730430241084220.html" },
        { label: "神ゲー攻略 — 飲み比べ（阿修羅級）の攻略", url: "https://kamigame.jp/ryugagotoku-ishin/page/255418620232900915.html" },
        { label: "神ゲー攻略 — 介抱（阿修羅級）の攻略", url: "https://kamigame.jp/ryugagotoku-ishin/page/255444201259435410.html" },
      ],
      achievementSlug: "play_all_ozashiki",
    },
    {
      slug: "woodcutting",
      name: { ko: "장작 패기", en: "Wood chopping" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 2,
      location: { ko: "서브스토리 「장작 패는 영감」에서 개시", en: "Starts from the wood-chopping old man's substory" },
      summary: {
        ko: "도끼가 빛나는 타이밍에 버튼을 누르는 단순 리듬 종목. 누적 300개를 패면 대부분의 요소가 끝나고, 이벤트 후 영감과의 절이 최대가 됩니다.",
        en: "Press the button as the axe flashes. Chopping 300 logs in total finishes most of what it's attached to and maxes the old man's bond after an event.",
      },
      howTo: [
        { ko: "1연째부터 7연째쯤까지는 누르는 타이밍이 느리고 리듬이 서서히 빨라집니다. 이 구간은 도끼가 빛나는 것을 눈으로 보고 누르는 편이 확실합니다.", en: "Through roughly the seventh log the timing is slow and the rhythm gradually speeds up — watch for the flash and press on sight." },
        { ko: "10연째 이후로는 패자마자 곧바로 빛나기 때문에 눈으로는 대응이 어렵습니다. 대신 빛나는 간격은 일정하므로 소리와 진동에 맞춰 누르세요.", en: "From the tenth on it flashes almost immediately after each chop, too fast to react to visually — but the interval is constant, so go by sound and vibration." },
        { ko: "누적 100개와 300개에서 무기 소재를 받고 정진목록도 달성됩니다. 정진목록에는 누적 500개 항목까지 있으므로 목록 완주를 노린다면 300개 이후로도 계속 패야 합니다.", en: "Weapon materials drop at 100 and 300 logs and Diligence Records entries clear along the way; the records go up to 500, so keep chopping past 300 if you want them all." },
      ],
      source: { label: "神ゲー攻略 — 薪割り", url: "https://kamigame.jp/ryugagotoku-ishin/page/251294702391818864.html" },
    },
    {
      slug: "lottery",
      name: { ko: "후쿠비키 (복권 추첨)", en: "Fukubiki lottery" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 1,
      location: { ko: "후시미 이치반가이 북동쪽", en: "North-east of Fushimi Ichiban Street" },
      summary: {
        ko: "후쿠비키 권을 써서 경품을 뽑는 추첨. 꽝 이외의 각 상은 1회씩만 나오고, 전부 뽑으면 다음 경품 세트로 갱신됩니다. 5회 갱신하면 첫 세트로 돌아오므로, 권만 있으면 못 얻는 아이템은 없습니다.",
        en: "Spend lottery tickets for prizes. Each non-blank prize only appears once, and clearing the set rotates it; after five rotations the first set comes back, so no item is permanently missable as long as you have tickets.",
      },
      howTo: [
        { ko: "소지품이 가득 차 있으면 뽑을 때마다 창고로 보낼 아이템을 골라야 합니다. 바로 근처의 지장보살에서 아이템을 먼저 맡기고 오세요.", en: "With a full inventory you have to pick something to warehouse on every draw — dump your items at the nearby jizo statue first." },
        { ko: "권은 길에서 빛나는 아이템을 조사해도 나오지만 1장씩이고 시간이 걸립니다. 실제로는 가게에서 2,000문마다 1장(1회 구매당 최대 100장)이 붙으므로, 음식점 컴플리트·행상용 식재·대장간 레벨업 같은 다른 목적의 지출로 자연히 모입니다.", en: "Tickets drop from glowing pickups one at a time, slowly. In practice they come from shopping — one per 2,000 mon, up to 100 per purchase — so they accumulate while you're spending on restaurant completion, trade goods and blacksmith levels anyway." },
        { ko: "여러 번 돌리면 상위 추첨이 해금됩니다. 후쿠비키 1장, 개운 후쿠비키 3장(3등 이상이 잘 나옴), 키비키 5장(경품이 조금 더 좋음), 개운 키비키 10장 순입니다. 꽝을 노리는 게 아니라면 「개운」 쪽이 소모 매수 대비 효율이 좋습니다.", en: "Drawing repeatedly unlocks better machines: the basic draw at one ticket, the lucky draw at three (better odds of third prize or higher), the rare draw at five (better prizes) and the lucky rare draw at ten. Unless you're farming blanks, the lucky versions burn fewer tickets per hit." },
      ],
      source: { label: "神ゲー攻略 — 福引き", url: "https://kamigame.jp/ryugagotoku-ishin/page/252945471042011560.html" },
    },
    {
      slug: "arena",
      name: { ko: "투기장", en: "Arena" },
      category: { ko: "배틀", en: "Battle" },
      difficulty: 5,
      location: { ko: "무쿠로가이(骸街) 투기장", en: "The arena in Mukuro Town" },
      summary: {
        ko: "「승발전(勝ち抜き戦)」과 「백인 베기」를 치르는 실력 시험장. 컴플리트 보상은 대통(大筒) 「봉황」이고, 10승으로 트로피 「This is MY Ring!」, 궁극 투기를 전부 클리어하면 「Ultimate Champion」입니다.",
        en: "Gauntlet fights and the Hundred-Man Slash. Completing it awards the Houou cannon, ten wins give This is MY Ring!, and clearing every Ultimate Challenge gives Ultimate Champion.",
      },
      howTo: [
        { ko: "무쿠로가이로 가는 길부터 준비입니다. 후시미 신마치의 뱃사공에게 편도 500문을 내거나, 3장 저녁 이후 라쿠가이 문 앞의 남자에게 술(값싼 「도부로쿠」면 충분)을 건네면 이후 자유롭게 왕래할 수 있습니다.", en: "Getting there is step one: pay the Shinmachi boatman 500 mon each way, or from evening in Chapter 3 hand the man at the Rakugai gate any sake — cheap doburoku does — for permanent free passage." },
        { ko: "투기장은 도전 직전의 레벨·장비·체력·히트 게이지·식사 효과를 그대로 이어받습니다. 들어가기 전에 반드시 체력과 게이지를 채워 두세요.", en: "The arena inherits your level, gear, health, heat gauge and food buffs exactly as they are when you enter — top everything up first." },
        { ko: "투기장 안에서는 아이템을 쓸 수 없고 대사(隊士) 능력도 못 씁니다. 그래서 체력·게이지가 자동 회복되는 인(印)을 무구에 박아 두는 것이 사실상 필수이고, 장기전이 되는 백인 베기에서는 특히 그렇습니다.", en: "Items are banned inside and trooper abilities don't work, so seals that auto-regenerate health and gauge are effectively mandatory — above all for the long Hundred-Man Slash." },
        { ko: "혼구(魂球)로 능력을 미리 강화해 체력·히트 게이지 상한을 올려 두고, 백인 베기 전에는 다수를 한 번에 치는 기술을 배워 두세요. 추천 기술은 격투의 형 「고마키류 다루마 피하기」·「말려들기 강화」·「강체의 마음가짐」, 일도의 형 「검속 강화」·「무검술 공중 회전 베기」, 단총의 형 「연사 속도 상승」·「염룡 활공」·「염룡 포효」, 난무의 형 「회피 연영」·「천룡 쇄아」·「난격무도 1~3」입니다.", en: "Spend Soul Orbs on health and heat caps beforehand, and learn multi-target moves before the Hundred-Man Slash. The guide's picks are Komaki-style Dharma Dodge, Sweep Enhancement and Iron Body in Brawler; Blade Speed and Aerial Spin Slash in Swordsman; Rapid Fire, Flame Dragon Glide and Flame Dragon Roar in Gunman; and Evasive Afterimage, Heavenly Dragon Fang Crusher and Wild Dance 1–3 in Wild Dancer." },
        { ko: "진행하다 보면 스토리 종반 수준의 적이 나옵니다. 벽에 부딪히면 무기·방어구를 새로 만들고 인으로 강화하고 오세요.", en: "The later rounds throw endgame-level enemies at you; if you stall, go craft better weapons and armour and upgrade them with seals." },
      ],
      source: { label: "神ゲー攻略 — 闘技場の立ち回りと準備", url: "https://kamigame.jp/ryugagotoku-ishin/page/254731080542745622.html" },
      achievementSlug: "win_tougijyo_10",
    },
    {
      slug: "cannonball",
      name: { ko: "대포알 다루기 (신베에 박사의 수행)", en: "Cannonball juggling (Dr. Shinbei's training)" },
      category: { ko: "수행", en: "Training" },
      difficulty: 3,
      location: { ko: "무쿠로가이 동쪽 강가 — 신베에 박사 앞을 지나면 발생", en: "The riverside on the east side of Mukuro Town — triggers by walking past Dr. Shinbei" },
      summary: {
        ko: "날아오는 대포알을 타이밍에 맞춰 □로 쳐 내는 수행. 스틱 조작은 필요 없고 오로지 타이밍입니다. 「일도의 형」과 「단총의 형」 두 계통이 있고 각각 초급·중급·상급·오마케 4단계입니다.",
        en: "Bat away incoming cannonballs with square on timing alone — no stick input at all. It runs in two lines, Swordsman and Gunman, each with beginner, intermediate, advanced and bonus tiers.",
      },
      howTo: [
        { ko: "통상 대포알은 200점, 황금 장식 대포알은 400점입니다. 스치듯 맞히면 점수가 절반이 되므로, 확실히 중심에 맞히는 편이 결과적으로 유리합니다.", en: "A normal ball scores 200 and the gilded one 400 — but a glancing hit halves the score, so a clean centre hit beats a rushed one." },
        { ko: "평가는 동·은·금 3단계입니다. 은 이상이면 보상을 받고, 금을 받아야 다음 난이도가 열립니다.", en: "Runs grade bronze, silver or gold: silver and above pays out, but only gold unlocks the next difficulty." },
        { ko: "무쿠로가이 자체가 3장 저녁 이후 라쿠가이 문지기에게 술을 건네야 열립니다. 값싼 도부로쿠 한 병을 미리 사 두세요.", en: "Mukuro Town itself opens by handing the Rakugai gatekeeper any sake from evening in Chapter 3 — pick up cheap doburoku first." },
      ],
      source: [
        { label: "神ゲー攻略 — 新兵衛博士の修行「大砲玉捌き」", url: "https://kamigame.jp/ryugagotoku-ishin/page/252828401792982037.html" },
        { label: "神ゲー攻略 — 骸街のマップと施設一覧", url: "https://kamigame.jp/ryugagotoku-ishin/page/251692014599433416.html" },
      ],
    },
    {
      slug: "chicken-racing",
      name: { ko: "경계 (닭 경주)", en: "Chicken racing" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "라쿠가이 경계장 (목찰 구입도 가능)", en: "The chicken-racing grounds in Rakugai (wooden tokens sold on site)" },
      summary: {
        ko: "이 게임에서 돈과 덕을 가장 효율적으로 버는 콘텐츠입니다. 5회 걸면 트로피가 나오고, 10,000점 이상을 획득하면 컴플리트가 달성됩니다.",
        en: "The most efficient money and Virtue in the game. Betting five times gives the trophy, and 10,000 points clears the completion entry.",
      },
      howTo: [
        { ko: "볼 것은 「조자(調子)」, 「예상 표시」, 「레이스 거리」 세 가지입니다. 조자가 좋으면 스피드 업이 잘 나오고 나쁘면 스피드 다운이 잘 납니다. 실력이 있어도 조자가 나쁘면 지는 일이 많으니, 익숙해지기 전에는 조자를 최우선으로 보세요.", en: "Three things to read: condition, the tipster's mark and the race distance. Good condition means speed-ups, bad means speed-downs — and a strong bird in poor condition loses often, so weight condition heaviest until you know the field." },
        { ko: "거리는 길수록 조자의 영향이 크고 짧을수록 실력 승부가 됩니다. 예상 표시는 실력자일수록 좋게 나오니 참고 정도로만 보세요.", en: "Longer races amplify condition; shorter ones come down to raw ability. The tipster's mark just tracks ability, so treat it as a hint rather than a call." },
        { ko: "목찰은 최대까지 걸어 두세요. 조권(鳥券)에는 구매 제한 시간이 있어서, 5연단과 3연단을 함께 살 때는 걸 점수를 세세하게 조정할 시간이 없습니다. 예상이 정해지면 곧장 MAX 베팅으로 가세요.", en: "Always bet the maximum. Ticket sales are on a timer, and buying a five-horse and a three-horse exacta together leaves no time to fiddle with the stake — decide, then MAX bet." },
        { ko: "효율을 노린다면 경계장 앞에서 세이브해 두고 결과에 따라 로드하는 방식이 정석입니다. 딴 목찰의 「접시(皿)」 경품을 환금하면 덕도 함께 들어옵니다.", en: "The efficient loop is saving in front of the grounds and reloading on a loss. Cashing the plate prizes your tokens buy also pays Virtue." },
      ],
      videos: [
        { title: { ko: "치킨 레이싱 가이드", en: "Chicken Racing guide" }, url: YT("04DO5If8D-w") },
      ],
      source: [
        { label: "神ゲー攻略 — 競鶏の攻略とお金稼ぎのやり方", url: "https://kamigame.jp/ryugagotoku-ishin/page/249651282615253221.html" },
        { label: "神ゲー攻略 — 洛外のマップと施設一覧", url: "https://kamigame.jp/ryugagotoku-ishin/page/251363316356649383.html" },
      ],
      achievementSlug: "kyokei_earn_total_5",
    },
    {
      slug: "cee-lo",
      name: { ko: "친치로린 (주사위)", en: "Cee-lo" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "도박장 (라쿠가이 등)", en: "The gambling dens, including Rakugai's" },
      summary: {
        ko: "그릇에 주사위를 던져 눈을 겨루는 도박. 컴플리트 조건은 목찰 누적 7,500점입니다.",
        en: "Throw dice into a bowl and compare the results. The completion condition is 7,500 cumulative token points.",
      },
      howTo: [
        { ko: "먼저 1점씩 걸어 상한을 푸는 것이 정석입니다. 초기 200점, 10회 승부로 500점, 15회 승부로 1,000점까지 열립니다. 상한을 연 뒤에 본격적으로 벌면 훨씬 빠릅니다.", en: "Open the stake cap first by betting one point at a time: it starts at 200, rises to 500 after ten rounds and to 1,000 after fifteen. Farm seriously only after that." },
        { ko: "친(親)이 한 바퀴 돌면 1승부입니다. 도중에 누군가의 소지 점수가 0이 되어도 그 시점에 승부가 끝납니다.", en: "A round runs until the dealer role has gone all the way around — or ends early the moment anyone's points hit zero." },
        { ko: "자기가 자(子)이고 친의 눈이 2나 3처럼 낮아 이기기 쉬울 때는 「한 번 던지기 3배」를 발동하세요. 주사위를 한 번만 던지는 대신 이겼을 때 배당이 3배가 되고, 졌을 때 잃는 점수는 그대로입니다.", en: "As a player against a weak dealer roll — a 2 or 3 — call the single-throw triple: you only get one throw, but a win pays triple while a loss costs the same as normal." },
      ],
      source: { label: "神ゲー攻略 — チンチロリン", url: "https://kamigame.jp/ryugagotoku-ishin/page/255856568552166502.html" },
      achievementSlug: "play_all_toba",
    },
    {
      slug: "cho-han",
      name: { ko: "초한 도박", en: "Cho-han" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "도박장 (라쿠가이 등)", en: "The gambling dens, including Rakugai's" },
      summary: {
        ko: "주사위 두 개의 합이 짝수(초)인지 홀수(한)인지를 맞히는 가장 단순한 도박. 컴플리트 조건은 누적 15,000점입니다.",
        en: "Call whether two dice total even (cho) or odd (han) — the simplest table in the game. Completion wants 15,000 cumulative points.",
      },
      howTo: [
        { ko: "여기도 걸 수 있는 점수의 상한 해방이 먼저입니다. 초기 200점, 10전에 500점, 20전에 800점, 30전에 1,000점입니다. 「1회 걸고 그만두기」를 반복하면 빠르게 풀립니다.", en: "Unlock the stake cap first: 200 at the start, 500 after ten rounds, 800 after twenty and 1,000 after thirty. Bet once and leave, repeatedly, to clock them up fast." },
        { ko: "상한을 1,000점까지 연 뒤에는 1,000점을 사서 세이브하고, 초한 걸기로 1,000점을 걸어 사시(1대1) 승부를 하는 흐름이 가장 빠릅니다. 누적 15,000점이면 완료입니다.", en: "With the cap at 1,000, buy 1,000 points, save, and take 1,000-point head-to-head bets — 15,000 cumulative finishes it." },
        { ko: "다른 손님들의 조자를 보면서 거는 것도 출처가 권하는 방법입니다.", en: "The guide also suggests reading the other players' streaks before committing." },
      ],
      source: { label: "神ゲー攻略 — 丁半博打", url: "https://kamigame.jp/ryugagotoku-ishin/page/254710882100077061.html" },
    },
    {
      slug: "koi-koi",
      name: { ko: "코이코이 (화투)", en: "Koi-koi" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "도박장 (라쿠가이 등)", en: "The gambling dens, including Rakugai's" },
      summary: {
        ko: "화투 1대1 대전. 컴플리트 조건은 누적 7,500점입니다.",
        en: "One-on-one hanafuda. Completion wants 7,500 cumulative points.",
      },
      howTo: [
        { ko: "득점 높은 역에 필요한 패부터 가져가세요. 내 점수가 커지는 동시에 상대의 고득점을 방해할 수 있습니다. 특히 2장으로 고득점이 되는 「달맞이 술」·「꽃놀이 술」에 필요한 「국화에 잔」은 최우선 확보 대상입니다.", en: "Take the cards the big yaku need first — it builds your score and blocks theirs at once. The chrysanthemum sake cup, which makes the two-card moon-viewing and flower-viewing hands, is the single highest priority." },
        { ko: "같은 달의 패는 총 4장입니다. 장에 1장·내 손에 3장인 달은 상대가 절대 가져갈 수 없으니 후순위로 미루고, 장과 내 손에 1장씩(=산이나 상대에 2장)처럼 상대가 가져갈 여지가 큰 달부터 처리하세요.", en: "There are four cards per month. A month where you hold three and one is on the field can never be taken, so leave it — clear the months where the opponent still has two in reach first." },
        { ko: "상대의 역이 완성될 것 같으면 「코이」하지 마세요. 욕심을 부리다 역전당하는 것이 이 게임에서 점수를 잃는 가장 흔한 방식입니다.", en: "Don't call koi when the opponent's hand looks close — greed after a made hand is the most common way to lose points here." },
      ],
      source: { label: "神ゲー攻略 — こいこい", url: "https://kamigame.jp/ryugagotoku-ishin/page/255856228981310645.html" },
    },
    {
      slug: "oicho-kabu",
      name: { ko: "오이초카부", en: "Oicho-kabu" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "도박장 (라쿠가이 등)", en: "The gambling dens, including Rakugai's" },
      summary: {
        ko: "합계의 끝자리를 9에 가깝게 만드는 카드 도박. 블랙잭과 비슷하지만 버스트가 없어 9를 넘겨도 문제없습니다. 컴플리트 조건은 누적 7,500점입니다.",
        en: "Get the last digit of your total as close to 9 as possible. It resembles blackjack but has no bust, so going past 9 costs you nothing. Completion wants 7,500 cumulative points.",
      },
      howTo: [
        { ko: "자(子)일 때는 첫 패를 고를 수 있습니다. 1·4·9가 있으면 우선해서 잡으세요. 특히 1은 특수역에 잘 얽히므로 최우선입니다.", en: "As a player you pick your first card — grab a 1, 4 or 9 if it's there, and the 1 above all, since it feeds the special hands." },
        { ko: "합계가 6 이상이면 3장째를 뽑지 말고 그대로 승부하세요. 더 뽑으면 숫자가 작아질 확률이 높습니다.", en: "At six or higher, stand rather than take a third card — drawing is more likely to shrink the total than grow it." },
        { ko: "특수역: 싯핀(자 전용, 2장째에 1과 4 → 걸린 점수 2배), 쿳핀(친 전용, 1과 9 → 2배), 아라시(친·자 공통, 3장이 모두 같은 달 → 3배), 도싯핀(친·자 공통, 10 2장 + 1 1장 → 20배), 시로쿠의 도주(친·자 공통, 2장째에 4와 6).", en: "Special hands: Shippin (player only, 1 and 4 on the second card, double stake), Kuppin (dealer only, 1 and 9, double), Arashi (either side, three cards of the same month, triple), Doshippin (either side, two 10s and a 1, twenty times) and Shiroku-no-nige (either side, 4 and 6 on the second card)." },
        { ko: "특수역은 9에 가까운 통상역보다 강하고, 상위 특수역이 나오지 않는 한 무조건 승리입니다. 그래서 「9에 붙이기」보다 특수역이 성립할 조합을 노리는 편이 기대값이 높을 때가 많습니다.", en: "A special hand beats any ordinary total and wins outright unless a higher special appears — so chasing a special is often worth more than nudging toward nine." },
      ],
      source: { label: "神ゲー攻略 — おいちょかぶ", url: "https://kamigame.jp/ryugagotoku-ishin/page/255862055456786372.html" },
    },
    {
      slug: "poker",
      name: { ko: "포커", en: "Poker" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "도박장 (라쿠가이 등)", en: "The gambling dens, including Rakugai's" },
      summary: {
        ko: "룰이 3종 있지만, 방침을 세우기 쉬운 텍사스 홀덤을 높은 배율로 도는 것이 가장 빠릅니다. 컴플리트 조건은 누적 15,000점입니다.",
        en: "Three rule sets are offered, but the fast route is Texas Hold'em at the high stake, where the decisions are clearest. Completion wants 15,000 cumulative points.",
      },
      howTo: [
        { ko: "텍사스 홀덤은 강한 역이 잘 나오지 않는 룰이라, 초반에 역이 서면 높은 확률로 이깁니다. 그래서 높은 배율에서 도는 편이 효율적입니다.", en: "Hold'em rarely produces big hands here, so an early made hand usually wins — which is why the high stake is the efficient table." },
        { ko: "판단은 공유패가 3장 열리는 2라운드에서 내립니다. 원페어·스트레이트·플러시가 보이면 CALL이나 RAISE로 갑니다.", en: "Make the decision on round two when three community cards are out: if a pair, straight or flush is live, call or raise." },
        { ko: "2라운드 시점에 원페어조차 안 보이거나 2·3 같은 약한 페어뿐이라면 일찍 FOLD하세요. 빨리 접는 만큼 칩이 안 줄어듭니다.", en: "If round two shows no pair at all, or only a weak one like twos or threes, fold early — folding cheap is how the stack survives." },
        { ko: "강한 원페어 이상이면 강하게 갑니다. 다만 원페어뿐인데 상대가 강하게 나오면 무리하지 말고 CALL로 상황을 보세요.", en: "Push with a strong pair or better, but with only a pair against an aggressive opponent, flat-call and watch rather than escalate." },
      ],
      source: { label: "神ゲー攻略 — ポーカー", url: "https://kamigame.jp/ryugagotoku-ishin/page/255457255074300965.html" },
    },
    {
      slug: "mahjong",
      name: { ko: "마작", en: "Mahjong" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "무쿠로가이 마작집", en: "The mahjong parlour in Mukuro Town" },
      summary: {
        ko: "표준 마작입니다. 룰을 모른다면 아래 최소한만 지켜도 화료까지는 갑니다.",
        en: "Standard mahjong. If you don't know the game, the minimum below is enough to reach a win.",
      },
      howTo: [
        { ko: "기본형은 「4멘츠 + 1작두」입니다. 연속한 숫자 3개 또는 같은 패 3개의 덩어리를 4개, 같은 패 2개의 머리를 1개 만드세요. 멘츠와 작두는 각각 같은 종류의 패로만 구성됩니다.", en: "The shape is four sets plus one pair: four groups of three consecutive numbers or three identical tiles, and one pair. Each group must be a single suit." },
        { ko: "같은 패 3개보다 3연속 숫자 쪽이 만들기 쉽습니다. 같은 숫자·자패는 최대 4장뿐이라 잘 모이지 않습니다.", en: "Runs are easier than triplets — there are only four of any given tile, so triplets stall." },
        { ko: "역을 모른다면 폰·치를 하지 마세요. 한 번이라도 울면 오를 수 있는 역이 크게 줄어듭니다. 반대로 론은 그 시점에 오르는 것이므로 무조건 하세요.", en: "Don't call pon or chi if you don't know the yaku — melding cuts most of them off. Ron, by contrast, wins on the spot, so always take it." },
        { ko: "리치 자체가 역 하나입니다. 울지 않고 텐파이까지 가면 리치만으로 화료할 수 있으니, 초심자는 「울지 않고 리치」를 기본 방침으로 삼으세요.", en: "Riichi is itself a yaku, so staying closed and declaring it is enough to win a hand — make \"no melds, then riichi\" your default." },
      ],
      source: [
        { label: "神ゲー攻略 — 麻雀", url: "https://kamigame.jp/ryugagotoku-ishin/page/255708739082929181.html" },
        { label: "神ゲー攻略 — 骸街のマップと施設一覧", url: "https://kamigame.jp/ryugagotoku-ishin/page/251692014599433416.html" },
      ],
    },
    {
      slug: "shogi",
      name: { ko: "장기 (이코마야)", en: "Shogi (Ikomaya)" },
      category: { ko: "보드게임", en: "Board game" },
      difficulty: 3,
      location: { ko: "라쿠나이 장기집 「이코마야」 (1회 500문)", en: "Ikomaya, Rakunai (500 mon a play)" },
      summary: {
        ko: "장기점을 두어 「장기점(将棋点)」을 모으고 상처약이나 환금 아이템과 교환합니다. 컴플리트 조건은 「시련 답파 1」을 3회 이기는 것입니다.",
        en: "Play for Shogi Points, traded for salves and cash items. The completion condition is winning Trial Run 1 three times.",
      },
      howTo: [
        { ko: "정석은 각(角)이 지나갈 길을 여는 것입니다. 초기 배치에서는 보(歩) 때문에 각이 못 움직이니 보를 밀어 길을 트고, 그러면 각 뒤의 계마도 함께 움직일 수 있게 됩니다.", en: "Open the bishop's diagonal first: it's blocked by a pawn at the start, and pushing that pawn also frees the knight behind it." },
        { ko: "비차(飛車) 앞의 보도 밀어 길을 엽니다. 다만 비차가 움직이기 쉬워질수록 상대도 비차를 잡기 쉬워지니, 배치할 때 상대 진형을 확인하고 절대 잡히지 않을 자리로 옮기세요.", en: "Push the rook's pawn too — but a mobile rook is also an exposed rook, so check the opponent's setup and only move it where it can't be taken." },
        { ko: "컴플리트는 「시련 답파 1」 3회 승리로 끝납니다. 순위전보다 시간이 짧아 이쪽이 효율적입니다.", en: "The completion entry finishes at three wins in Trial Run 1, which is much quicker than the ranking matches." },
        { ko: "절 올리기는 4전 뒤 발생하는 「장기집 주인」과의 대국에서 이기면 최대가 됩니다. 주인은 강하지 않지만 시간을 아끼고 싶다면, 무료 장기 소프트에 상대 수를 입력하고 최강 설정 CPU에게 두게 하면 쉽게 이깁니다.", en: "Four games in, an event match against the shop's owner appears — beating him maxes the bond. He isn't strong, but if you want it over fast, feed his moves into a free shogi engine set to maximum strength and play its replies." },
      ],
      source: [
        { label: "神ゲー攻略 — 将棋", url: "https://kamigame.jp/ryugagotoku-ishin/page/255732050554795674.html" },
        { label: "神ゲー攻略 — 洛内のマップと施設一覧", url: "https://kamigame.jp/ryugagotoku-ishin/page/250940026324554324.html" },
      ],
    },
    {
      slug: "fishing",
      name: { ko: "낚시", en: "Fishing" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 2,
      location: { ko: "후시미 데라다야 앞 강 / 데라다야 앞 뱃사공(바다낚시: 어초의 갯바위·히가시오키) / 무쿠로가이 강", en: "The river in front of Teradaya in Fushimi, the boatman there for sea fishing (reef or east offshore), and the river in Mukuro Town" },
      summary: {
        ko: "찌의 빨간 부분이 물에 잠기면 버튼을 누르는 단순한 액션입니다. 잡은 물고기는 요리와 서브스토리, 어나더 라이프의 행상 납품에 쓰입니다. 누적 10마리로 트로피.",
        en: "Watch the float and press when its red section sinks. Fish feed cooking, substories and Another Life's trade orders; ten fish total gives the trophy.",
      },
      howTo: [
        { ko: "성능 좋은 낚싯대를 먼저 구하세요. 히트까지의 시간이 짧아져 효율이 크게 오르고, 멀리까지 던질 수 있어 원거리에만 있는 물고기도 잡힙니다. 덕 교환으로 구합니다.", en: "Get a better rod first — bites come faster and it casts far enough to reach fish that only appear at distance. Buy it from the Virtue exchange." },
        { ko: "레어 물고기를 노린다면 라쿠나이의 봇테후리(행상)에서 밑밥을 사 두세요. 일시적으로 출현율이 올라가지만 효과가 3분 정도라 고성능 낚싯대와 병용이 사실상 필수입니다.", en: "For rare fish, buy chum from the Rakunai peddler. It raises spawn rates but only lasts about three minutes, so it really needs the good rod alongside it." },
        { ko: "물고기는 어영(魚影)과 헤엄치는 위치, 움직이는지 멈춰 있는지로 대체로 구별됩니다. 노리는 물고기가 있으면 던지기 전에 먼저 어디 있는지 찾으세요.", en: "Species are identifiable from the shadow, where it swims and whether it's moving or holding still — spot your target before you cast, not after." },
      ],
      source: [
        { label: "神ゲー攻略 — 釣りの攻略と釣れる魚一覧", url: "https://kamigame.jp/ryugagotoku-ishin/page/250675545946241347.html" },
        { label: "神ゲー攻略 — 伏見のマップと施設一覧", url: "https://kamigame.jp/ryugagotoku-ishin/page/253409800040228729.html" },
      ],
      achievementSlug: "fishing_10",
    },
  ],
};
