import type { MinigamesData } from "./types";

const YT = (id: string) => `https://www.youtube.com/watch?v=${id}`;

// Minigame guides for Like a Dragon Gaiden. Locations, unlock chapters, rules
// and prize tables come from ゲーム攻略マン's per-play-spot pages, with 神ゲー攻略
// for the arcade line-up. Every entry cites the page its numbers came from.
export const likeADragonGaidenMinigames: MinigamesData = {
  appId: 2375550,
  intro: {
    ko: "용과 같이 7 외전의 플레이 스폿은 소텐보리·이진초·「캐슬」 세 곳에 걸쳐 있고, 대부분 메인 스토리 2장 진행으로 열립니다. 콜로세움(ZIGOKU ARENA)·실사 캬바쿠라·포켓 서킷이 컴플리션의 축이고, 3장에서 다이도지 아지트에 놓인 SEGA 마스터 시스템으로 레트로 게임도 즐길 수 있습니다. 미니게임 10종을 플레이하면 트로피 「취미가 너무 많았던 남자」.",
    en: "Gaiden's play spots are split across Sotenbori, Ijincho and the Castle, and most open once the main story reaches Chapter 2. The Coliseum (ZIGOKU ARENA), the live-action cabaret clubs and Pocket Circuit anchor completion, and from Chapter 3 the Daidoji hideout's SEGA Master System adds retro games. Playing ten minigames gives \"The Man Who Had Too Many Hobbies\".",
  },
  minigames: [
    {
      slug: "coliseum",
      name: { ko: "콜로세움 (ZIGOKU ARENA)", en: "Coliseum (ZIGOKU ARENA)" },
      category: { ko: "배틀", en: "Battle" },
      difficulty: 5,
      location: { ko: "캐슬 — 2장 진행으로 해금", en: "The Castle — unlocks in Chapter 2" },
      summary: {
        ko: "캐슬의 간판 콘텐츠인 과격 격투 쇼. 1대1 토너먼트부터 다수전, 팀 대 팀 대난투까지 4종 대회가 열립니다. 기류뿐 아니라 조류회 동료를 리더로 세워 직접 조작할 수도 있어, 동료 수집과 편성이 그 자체로 공략입니다. 전 매치를 실버/골드/플래티넘 랭크로 클리어하는 것이 트로피 조건입니다.",
        en: "The Castle's headline attraction: a brutal fighting show running four formats, from one-on-one tournaments up to team-versus-team brawls. You can put a Joryu Clan member in as leader and play them instead of Kiryu, so recruiting and arranging the roster is itself the strategy. Clearing every match at Silver, Gold and Platinum rank are the three trophies.",
      },
      howTo: [
        { ko: "대회는 4종입니다. TOURNAMENT는 1대1 타이맨, ZIGOKU RUMBLE은 1대 다수 난투, SPECIAL EVENT MATCH는 실적을 쌓은 선수만 참가권을 얻는 부정기 특별 룰, ZIGOKU TEAM RUMBLE은 팀을 짜서 도전하는 다수 대 다수 대난투입니다.", en: "Four formats: Tournament (one on one), Zigoku Rumble (one against many), Special Event Match (irregular special rules, entry earned by track record) and Zigoku Team Rumble (team versus team)." },
        { ko: "팀 럼블에서만 화면 좌하단에 Order 게이지가 있습니다. 가득 찼을 때 방향키 ←로 호령을 내리면 일시적으로 아군이 강화되고, 그동안 아군도 히트 스킬을 쓰기 쉬워집니다.", en: "Only Team Rumble has the Order gauge, bottom left. Filling it and pressing left on the d-pad issues an order that temporarily buffs your allies and makes them use heat skills more freely." },
        { ko: "편성은 전열에 방어력 높은 동료, 후열에 서포트·회복역을 두는 식으로 짭니다. 싸울수록 동료 레벨이 올라 강화되고, 지친 동료는 파이터 라운지에서 회복시킵니다.", en: "Put high-defence members in the front row and support or healing roles behind. Members level up by fighting, and the Fighter Lounge restores the tired ones." },
        { ko: "동료는 서브스토리 공략과 파이터 라운지에서 모읍니다. 스테이지는 상부(배틀 에리어가 좁음)와 하부로 나뉘니 편성 전에 어느 쪽인지 확인하세요.", en: "Recruit members through substories and the Fighter Lounge. Stages split into an upper area (a tighter fighting space) and a lower one — check which before setting your team." },
        { ko: "승리 보상에는 기본 보상 외에 타임 보너스와 랭크 보너스가 붙습니다. 빠르게, 높은 랭크로 끝낼수록 보상금이 커집니다.", en: "Wins pay a base reward plus Time and Rank bonuses, so finishing fast and cleanly is worth real money." },
        { ko: "구매 특전·유료 DLC 「레전더리 파이터 팩」에는 도지마 다이고·마지마 고로·사에지마 타이가 3명이 플레이어블로 참전하며, 콜로세움 해금과 동시에 자동으로 동료가 됩니다.", en: "The Legendary Fighter Pack (pre-order bonus / paid DLC) adds Daigo Dojima, Goro Majima and Taiga Saejima as playable fighters, automatically joining the moment the Coliseum unlocks." },
      ],
      videos: [
        { title: { ko: "콜로세움 플래티넘 랭크 + 4대 천왕 가이드", en: "Coliseum: reaching Platinum Rank & the Four Kings" }, url: YT("fPj_pyIz5Zg") },
        { title: { ko: "4대 천왕 4연전 공략", en: "Four Kings — all four fights" }, url: YT("I_zzBl35Cpc") },
      ],
      source: { label: "ゲーム攻略マン — 闘技場の攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/walkthrough-data/coliseum.html" },
      achievementSlug: "arena_c",
    },
    {
      slug: "cabaret-heavenly",
      name: { ko: "캬바쿠라 — Club Heavenly (실사)", en: "Cabaret Club — Club Heavenly (live action)" },
      category: { ko: "술집·바", en: "Bar / hostess" },
      difficulty: 3,
      location: { ko: "소텐보리 Club Heavenly — 2장 진행으로 개점", en: "Club Heavenly, Sotenbori — opens in Chapter 2" },
      summary: {
        ko: "7 외전의 캬바쿠라는 3DCG가 아니라 실사 영상입니다. 「용과 같이 생캬바조 오디션」으로 뽑힌 5명 중 kson과 아유가 Club Heavenly 소속입니다. 대화·주문·선물로 호감도를 올려 연애 레벨 Lv.3까지 올리면 클리어입니다.",
        en: "Gaiden's hostesses are live-action video, not 3D models — five women cast through the Yakuza Studio hostess audition, of whom kson and Ayu work at Club Heavenly. Talk, order and give gifts to raise affection to Romance Level 3 to finish a hostess.",
      },
      howTo: [
        { ko: "기본 요금은 입점 1만 엔이고, 주문한 만큼 추가로 듭니다. 호감도 올리기에 돈이 꽤 드니 어느 정도 자금을 모은 뒤에 공략하는 편이 낫습니다.", en: "Entry is a flat ¥10,000 and orders cost more on top. Raising affection is expensive, so build up some money before committing to a hostess." },
        { ko: "한 번 방문에 대화는 2회까지입니다. 대화 내용은 하트 레벨(연애 레벨)에 따라 정해져 있고, 마지막에 선물을 건네고 퇴점하는 흐름입니다.", en: "You get two conversations per visit; which ones come up is fixed by the current Romance Level, and each visit ends with a gift." },
        { ko: "호감도 게이지가 8할쯤 차면 연애 레벨 랭크업 대화가 나옵니다. 적절한 선택지를 고르면 레벨이 오르고, 한 번 오른 뒤에는 호감도가 내려가는 선택지를 골라도 랭크 다운은 없습니다.", en: "At roughly 80% of the gauge a rank-up conversation triggers; pick the right option and the level rises. Once raised, it never drops again even if you answer badly later." },
        { ko: "연애 레벨은 Lv.3이 상한이고, 올릴 때마다 프로필이 단계적으로 공개됩니다. Lv.3에서 애프터에 초대받지만 특별 영상을 보는 것뿐이고, 시리즈 종래의 데이트 파트는 없습니다.", en: "Romance Level caps at 3, unlocking more of her profile at each step. Level 3 ends in an after-hours invitation, but that is a video only — there's no date sequence like the older games." },
        { ko: "클리어 후에는 연애 레벨 0~2를 지정해 다시 플레이할 수 있습니다. 회상에서 아직 듣지 않은 대화를 확인할 수 있으니 회상 컴플리트용으로 쓰세요.", en: "After clearing her you can replay at Romance Level 0–2 to pick up dialogue you missed; the Reminisce list shows which conversations you still haven't seen." },
      ],
      videos: [
        { title: { ko: "클럽 헤븐리 호스티스 아유 공략 (해피엔딩)", en: "Club Heavenly hostess Ayu guide (happy ending)" }, url: YT("7iHrZVEWqCA") },
        { title: { ko: "클럽 헤븐리 호스티스 아유 공략", en: "Club Heavenly hostess Ayu guide" }, url: YT("SgFEV-hUGdc") },
      ],
      source: { label: "ゲーム攻略マン — キャバクラ（キャバ嬢）攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/cabaret-club/" },
      achievementSlug: "caba_a",
    },
    {
      slug: "cabaret-castle",
      name: { ko: "캬바쿠라 — Club Castle (실사)", en: "Cabaret Club — Club Castle (live action)" },
      category: { ko: "술집·바", en: "Bar / hostess" },
      difficulty: 3,
      location: { ko: "캐슬 Club Castle — 2장에 캐슬 도달 후", en: "Club Castle, the Castle — once Chapter 2 opens the Castle" },
      summary: {
        ko: "캐슬 쪽 캬바쿠라로 카나메·나카야마 코코로·사야마 아이 3명이 소속돼 있습니다. Club Heavenly와 규칙은 같고, 2장 시점에 캬바쿠라 전체를 컴플리트할 수 있습니다.",
        en: "The Castle's club, with Kaname, Kokoro Nakayama and Ai Sayama. The rules match Club Heavenly, and every hostess in the game can be completed as soon as Chapter 2 opens.",
      },
      howTo: [
        { ko: "진행은 헤븐리와 동일합니다. 입점 1만 엔 + 주문, 대화 2회, 선물 후 퇴점, 게이지 8할에서 랭크업 대화.", en: "The loop is identical to Heavenly: ¥10,000 entry plus orders, two conversations, a gift on the way out, and a rank-up conversation at about 80% of the gauge." },
        { ko: "캬바조는 전 5명 중 3명이 이곳 소속입니다. 두 가게 모두 2장에 열리므로 한 챕터 안에서 5명 전원을 끝낼 수 있습니다.", en: "Three of the five hostesses work here and both clubs open in Chapter 2, so all five can be finished inside that chapter." },
        { ko: "실사 캬바쿠라는 용량을 크게 잡아먹어, 무비 용량의 77%를 차지했다고 개발진이 밝혔습니다. 게임 진행과는 무관한 사실이지만 이 모드가 왜 이 규모인지를 설명합니다.", en: "The developers noted the live-action club ate 77% of the game's movie data — no gameplay bearing, but it explains the scale of the mode." },
      ],
      videos: [
        { title: { ko: "캐슬 캐바레 호스티스 카나메 공략 (해피엔딩)", en: "Castle Cabaret hostess Kaname guide (happy ending)" }, url: YT("w6Ek9DDELKk") },
        { title: { ko: "카나메 로맨스 완전판 + 정답 + 최종 데이트", en: "Complete Kaname romance, best answers & final date" }, url: YT("IHYdmAd_h6s") },
      ],
      source: { label: "ゲーム攻略マン — キャバクラ（キャバ嬢）攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/cabaret-club/" },
      achievementSlug: "caba_b",
    },
    {
      slug: "pocket-circuit",
      name: { ko: "포켓 서킷 (포케사)", en: "Pocket Circuit" },
      category: { ko: "레이스", en: "Racing" },
      difficulty: 4,
      location: { ko: "소텐보리 CourStar — 2장 진행으로 해금", en: "CourStar, Sotenbori — unlocks in Chapter 2" },
      summary: {
        ko: "미니 4WD를 코스에 달리게 해 순위를 다투는 종목. 용과 같이 0의 포케사와 같은 계보로, 외전에서는 신규 대회·코스·바디·파츠가 추가됐습니다. 2장 전에는 가게가 준비 중이라 들어갈 수 없습니다.",
        en: "Race mini four-wheel-drive cars around a track, in the same lineage as Yakuza 0's Pocket Circuit but with new tournaments, courses, bodies and parts. The shop is closed until Chapter 2.",
      },
      howTo: [
        { ko: "머신 스탯은 스피드·밸런스·가속력·다운포스·그립·코너·무게·코스트입니다. 속도를 올리는 방향이 기본이지만, 너무 빠르면 굽은 코스에서 코스아웃하고 점프대에서 뒤집혀 집니다. 주행 불능이 되면 그 시점에 패배이므로 균형이 정답입니다.", en: "Machine stats are speed, balance, acceleration, downforce, grip, cornering, weight and cost. Faster is the default direction, but too fast flies off the bends and flips on the jump sections — and a stalled machine loses on the spot, so balance wins." },
        { ko: "파츠 커스터마이즈는 코스트 안에 들어가야 대회 출전이 가능합니다. 파츠는 숍에서 포케사 포인트(PP)로 사거나 적에게서 드롭으로 얻습니다.", en: "Your build must fit inside the cost cap or you can't enter. Parts come from the shop for Pocket Circuit Points (PP) or as enemy drops." },
        { ko: "레이스 중 조작은 △ 부스트 주행과 ○ 연타(기합 주입)뿐입니다. 코스아웃할 것 같을 때 ○를 연타하면 복귀하기 쉬워집니다.", en: "In-race you only have triangle to boost and mashing circle to psych the car on; mashing circle as it wobbles makes a recovery much more likely." },
        { ko: "대회는 입문(엔트리 코스, 코스트 20, 88.2m, 8랩)부터 단계적으로 열리고, 앞 대회를 클리어해야 다음이 해금됩니다. 초기 3개는 난도 ★1·코스트 20이고, 스탠다드부터 코스트 25, 베테랑 대회부터 30으로 올라갑니다.", en: "Tournaments unlock in a chain from the Entry Course (cost 20, 88.2 m, 8 laps); the first three are one-star at cost 20, the Standard tier raises the cap to 25 and the Veteran tier to 30." },
        { ko: "출처 페이지는 대회별로 우승 가능한 파츠 구성(타이어/핀/모터/기어/배터리)과 부스트·기합 주입 없이 낸 클리어 타임까지 적어 두었습니다. 막히면 그 조합을 그대로 따라가는 것이 가장 빠릅니다.", en: "The linked guide lists, per tournament, a parts set (tyre / fin / motor / gear / battery) that wins it plus the clear time achieved without using boost or the circle-mash — copying the listed build is the fastest way past a wall." },
        { ko: "특수 존(점프 섹션, 다이나믹 커브, 잔디 섹션, 루프 체인지, 쇼트 슬로프, 울트라 슬로프)은 코스마다 다릅니다. 대회 정보에서 어떤 존이 있는지 보고 그에 맞춰 세팅을 바꾸세요.", en: "Special zones differ per course — jump sections, dynamic curves, grass, loop changes, short and ultra slopes. Read which ones a tournament has and tune for them." },
      ],
      videos: [
        { title: { ko: "포켓 서킷 완전 공략 (전 레이스)", en: "Pocket Circuit complete guide (all races)" }, url: YT("Sk3iPRprsiE") },
        { title: { ko: "전 부품 위치 가이드", en: "All parts locations guide" }, url: YT("jfIzMPUsrjQ") },
      ],
      source: { label: "ゲーム攻略マン — ポケサー攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/pocket-circuit.html" },
      achievementSlug: "pokecir_a",
    },
    {
      slug: "master-system",
      name: { ko: "SEGA 마스터 시스템", en: "SEGA Master System" },
      category: { ko: "레트로 게임", en: "Retro games" },
      difficulty: 1,
      location: { ko: "소텐보리 — 다이도지 아지트 (3장 개막부터)", en: "The Daidoji hideout, Sotenbori — from the start of Chapter 3" },
      summary: {
        ko: "아지트에 놓인 세가의 8비트 가정용 게임기. 1986년 북미판 세가 마크 III로, 해외판·일본판 전환과 2인 플레이까지 지원합니다. 5종 이상 플레이하면 트로피 「레트로 게이머」입니다.",
        en: "SEGA's 8-bit console sitting in the hideout — the 1986 North American Mark III — with region switching and two-player support. Playing five different titles earns the Retro Gamer trophy.",
      },
      howTo: [
        { ko: "트로피는 클리어가 아니라 플레이만 세므로, 5종을 켰다가 바로 중단하는 것만으로 획득할 수 있습니다.", en: "The trophy counts playing, not clearing — booting five different titles and quitting straight away is enough." },
        { ko: "초기 수록은 「아수라」, 「메이즈 워커」, 「두근두근 펭귄랜드 우주 대모험」, 「판타지 존」입니다. 이것만으로 4종이라 한 개만 더 구하면 됩니다.", en: "Four titles are built in — Ashura, Maze Walker, Doki Doki Penguin Land and Fantasy Zone — so you only need to find one more." },
        { ko: "추가 소프트 입수처: 「판타지 존 II」 코인 로커 F4, 「갤럭시 포스」 에비스야 소텐보리 판매, 「플리키」 소텐보리 입수 No.24, 「알렉스 키드의 미라클 월드」 캐슬 입수 No.7, 「에일리언 신드롬」 코인 로커 F1, 「엔듀로 레이서」 코인 로커 I4, 「더블 타깃」 캐슬 카지노 교환소 경품, 「SDI」 캐슬 도박장 경품.", en: "Where the rest come from: Fantasy Zone II in coin locker F4, Galaxy Force sold at Ebisuya Sotenbori, Flicky as Sotenbori pickup No.24, Alex Kidd in Miracle World as Castle pickup No.7, Alien Syndrome in locker F1, Enduro Racer in locker I4, Double Target from the Castle casino exchange and SDI from the Castle gambling den." },
      ],
      videos: [
        { title: { ko: "마스터 시스템 전 게임 위치 (레트로 게이머)", en: "All Master System game locations (Retro Gamer)" }, url: YT("ggeLlkWSW-4") },
      ],
      source: { label: "ゲーム攻略マン — SEGAマスターシステム攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/sega-master-system.html" },
      achievementSlug: "retro_games",
    },
    {
      slug: "arcade",
      name: { ko: "게임센터 (아케이드 기체)", en: "Arcade cabinets" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 1,
      location: { ko: "소텐보리 CLUB SEGA (소텐보리도리 북쪽) / 이진초 게임센터 사사키 (쓰루카메 가도 서쪽 부근)", en: "CLUB SEGA on north Sotenbori Street; Game Center Sasaki near west Tsurukame Road, Ijincho" },
      summary: {
        ko: "두 게임센터의 라인업은 동일합니다. UFO 캐처를 포함해 6종을 플레이하면 트로피 「Arcade Dweller」입니다.",
        en: "Both arcades have the same line-up, and playing six different machines — the UFO catcher counts — gives the Arcade Dweller trophy.",
      },
      howTo: [
        { ko: "수록 기체는 「소닉 더 파이터즈」(1996), 「파이팅 바이퍼즈 2」(1998), 「버추어 파이터 2.1」(1995년 가동의 밸런스 조정판), 「모터 레이드」(1997), 「SEGA RACING CLASSIC 2」, 그리고 UFO 캐처입니다.", en: "The machines are Sonic the Fighters (1996), Fighting Vipers 2 (1998), Virtua Fighter 2.1 (the 1995 rebalanced revision), Motor Raid (1997), SEGA RACING CLASSIC 2 and the UFO catcher." },
        { ko: "SEGA RACING CLASSIC 2는 「데이토나 USA(PE판)」의 이식으로, 라이선스 문제로 「데이토나」 이름을 쓸 수 없어 개명된 것입니다.", en: "SEGA RACING CLASSIC 2 is the Daytona USA (PE) port, renamed because the Daytona licence couldn't be used." },
        { ko: "소닉 더 파이터즈는 게임성이 버추어 파이터 2.1과 거의 같고, 파이팅 바이퍼즈 2는 HP 게이지 외에 상반신·하반신 「아머」가 따로 있는 것이 특징입니다.", en: "Sonic the Fighters plays close to Virtua Fighter 2.1, while Fighting Vipers 2 adds separate upper- and lower-body armour on top of the health bar." },
      ],
      source: { label: "神ゲー攻略 — ゲームセンターの場所と遊べるゲーム", url: "https://kamigame.jp/ryugagotoku7-gaiden/page/289480559393004007.html" },
      achievementSlug: "arcade_games",
    },
    {
      slug: "ufo-catcher",
      name: { ko: "UFO 캐처", en: "UFO catcher" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "소텐보리 클럽 세가 소텐보리점 / 이진초 게임센터 사사키 (3플레이 500엔)", en: "Club SEGA Sotenbori and Game Center Sasaki, Ijincho (three plays for ¥500)" },
      summary: {
        ko: "크레인으로 경품을 집는 종목. 조작은 × 두 번뿐이라 단순하지만, 경품이 두 점포에 걸쳐 있어 컴플리트하려면 양쪽을 다 돌아야 합니다.",
        en: "Crane game. The controls are just two presses of cross, but the prize pool is spread across the two arcades, so completing it means visiting both.",
      },
      howTo: [
        { ko: "× 버튼을 누른 채로 가로 라인을 정하고, 두 번째 × 누름으로 안쪽 라인을 정합니다. 그 뒤엔 암이 경품을 잡아 반출구까지 옮기면 획득입니다.", en: "Hold cross to set the horizontal line, then hold it again to set the depth. After that the arm grabs and, if it holds, carries the prize to the chute." },
        { ko: "경품 대부분은 무게 중심이 가운데에 있으니 크레인을 경품 중심에 맞춰 균형이 무너지지 않게 집는 것이 요령입니다.", en: "Most prizes are weighted at the centre, so line the claw up on the middle of the item and lift without tipping it." },
        { ko: "점원에게 말을 걸면 경품을 교체할 수 있고, 이때 배치가 초기 상태로 돌아갑니다. 조작 실수로 경품이 집기 어려운 위치로 밀려났다면 점원에게 말을 걸어 리셋하세요.", en: "Talking to the attendant swaps the prize out — and resets the layout, so if a bad grab has shoved a prize somewhere unreachable, reset it that way." },
        { ko: "플레이 횟수가 남아 있어도 ○로 중단할 수 있지만, 암이 움직이는 중에는 중단되지 않습니다.", en: "Circle quits even with plays left, though not while the arm is in motion." },
      ],
      source: [
        { label: "ゲーム攻略マン — UFOキャッチャー攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/ufo-catcher.html" },
        { label: "神ゲー攻略 — ゲームセンターの場所と遊べるゲーム", url: "https://kamigame.jp/ryugagotoku7-gaiden/page/289480559393004007.html" },
      ],
    },
    {
      slug: "golf",
      name: { ko: "골프 (요코보리 골프 센터)", en: "Golf (Yokobori Golf Center)" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 3,
      location: { ko: "소텐보리 요코보리 골프 센터 (1플레이 1,000엔)", en: "Yokobori Golf Center, Sotenbori (¥1,000 a play)" },
      summary: {
        ko: "타격 연습장에서 니어핀 챌린지와 빙고 챌린지를 즐깁니다. 외전에서는 경품이 전부 gp(골프 포인트)로 통일돼, 조건을 달성해 모은 gp를 접수처에서 교환합니다.",
        en: "A driving range running the Near Pin and Bingo challenges. Gaiden unifies every prize under golf points (gp), which you earn by meeting the conditions and spend at the counter.",
      },
      howTo: [
        { ko: "샷은 ×로 시작 → 샷 게이지 커서에서 ×로 파워 결정 → 임팩트 게이지 범위에 커서가 오면 ×로 결정, 순입니다. 임팩트 게이지에서 ×를 누르지 않으면 헛스윙 처리됩니다.", en: "Cross starts the shot, cross again on the power gauge, and cross a third time inside the impact window. Missing that last press counts as a whiff." },
        { ko: "임팩트 게이지 한가운데 빨간 존(저스트 임팩트)에서 멈추면 똑바로 날아갑니다. 양옆 노란 존은 훅과 슬라이스로, 왼쪽으로 치우치면 좌측, 오른쪽이면 우측으로 휘어집니다. 파워 결정 후에도 ×로 샷을 취소할 수 있습니다.", en: "Stopping in the red Just Impact zone at the centre sends the ball straight; the yellow zones either side hook it left or slice it right. Even after locking the power you can cancel the shot with cross." },
        { ko: "니어핀 챌린지는 전 10샷의 합계 포인트가 최종 스코어입니다. 초급만 열려 있고 최종 스코어 100을 넘기면 다음 난이도가 해금됩니다. 중급 이상은 장애물이 배치돼 붙이기가 어려워집니다.", en: "Near Pin scores the total of ten shots. Only the beginner course is open at first; breaking 100 unlocks the next tier, and from intermediate up obstacles start blocking the line." },
        { ko: "핀이나 깃발에 공이 맞는 위치로 치면 컵인 연출이 나오며 최고점 200pt를 받습니다. 연속으로 핀에 붙이면 콤보가 발생해 pt 보너스가 붙습니다.", en: "Hitting the pin or flag triggers the cup-in animation and the maximum 200 points, and stringing near misses together builds a combo bonus." },
        { ko: "니어핀 보상은 코스별로 다릅니다. 초급은 C 100 / B 200 / A 300 / S 500gp, 중급은 100 / 300 / 600 / 1,000gp, 상급은 100 / 500 / 1,000 / 2,000gp입니다(S는 1,000점 이상).", en: "Near Pin payouts scale with the course: beginner gives 100/200/300/500 gp for C/B/A/S, intermediate 100/300/600/1,000 and advanced 100/500/1,000/2,000, with S needing 1,000 points." },
        { ko: "빙고 챌린지는 9장의 패널을 쳐서 종횡을 맞추는 방식으로, 1 BINGO 100gp부터 6 BINGO 1,000gp, 8 BINGO는 단번에 2,000gp입니다. gp 벌이는 여기가 압도적으로 효율적입니다.", en: "Bingo has you punch through nine panels for lines: 100 gp for one bingo up to 1,000 for six, and 2,000 for eight — far and away the best gp per minute." },
      ],
      source: { label: "ゲーム攻略マン — ゴルフ攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/golf-center.html" },
    },
    {
      slug: "billiards",
      name: { ko: "당구", en: "Billiards" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 4,
      location: { ko: "소텐보리 Kiss Shot Billiards & Bar", en: "Kiss Shot Billiards & Bar, Sotenbori" },
      summary: {
        ko: "통상 모드에 나인볼·로테이션·에이트볼·요쓰다마 4종, 그리고 별도로 1샷 챌린지가 있습니다. 트로피는 1샷 챌린지 NORMAL 클리어입니다.",
        en: "Four standard modes — nine-ball, rotation, eight-ball and four-ball carom — plus the separate One-Shot Challenge, which is what the trophy asks for on normal difficulty.",
      },
      howTo: [
        { ko: "직선 샷은 화면에 자 같은 곧은 물건을 대보면 들어갈지 판단할 수 있지만, 각도가 붙은 샷은 미세한 오차로 빗나가므로 경험과 감에 의존해야 합니다. 그래서 특수 샷을 알아 두는 편이 낫습니다.", en: "For a straight shot you can literally hold something straight against the screen to check the line; angled shots miss on tiny errors, so it's worth knowing the trick shots." },
        { ko: "캐논 샷은 수구를 적구에 맞혀 방향을 바꿔 다른 적구를 넣는 것, 키스 샷은 맞은 적구가 다시 다른 적구를 맞혀 넣는 것, 콤비네이션 샷은 적구1이 적구2를 밀어 넣는 것(수구는 적구2에 닿지 않음), 뱅크 샷은 적구를 쿠션에 튕겨 넣는 것입니다. 뱅크 샷은 쿠션에서 속도가 죽으니 파워를 강하게 잡으세요.", en: "A cannon deflects the cue ball off one object ball into another; a kiss sends the struck ball into a third; a combination has ball one drive ball two in without the cue ball touching it; and a bank rebounds the object ball off a cushion — which kills its speed, so hit it harder." },
        { ko: "나인볼은 1~9번을 쓰고 9번을 먼저 넣으면 승리입니다. 테이블에 남은 가장 작은 숫자부터 맞혀야 하며, 그 뒤 다른 공이 들어가도 유효합니다. 작은 숫자를 맞히지 않거나 목표구에 닿지 않으면 파울로 상대가 수구를 원하는 곳에 놓습니다.", en: "Nine-ball uses balls 1–9 and ends when the 9 drops. You must contact the lowest ball on the table first, though anything that falls after counts. Missing that contact is a foul and hands ball-in-hand to the opponent." },
        { ko: "에이트볼은 브레이크 후 처음 넣은 공으로 로우(1~7)·하이(9~15) 그룹이 정해집니다. 자기 그룹을 전부 넣기 전에 8번을 넣으면 패배이고, 마지막 8번은 포켓 위치를 지정해 그곳에 넣어야 합니다.", en: "In eight-ball the first ball you pot after the break assigns you low (1–7) or high (9–15). Potting the 8 before clearing your group loses, and the final 8 must be called into a nominated pocket." },
        { ko: "요쓰다마는 포켓이 없는 대에서 흰공·노란공 각 1개와 빨간공 2개로 합니다. 수구가 2개 이상의 공에 맞으면 1점이고 먼저 15점이면 승리입니다. 처음 적구에 맞은 뒤의 궤도를 표시할 수 있으니 켜 두고 파워만 조절하면 일방적으로 이길 수 있습니다.", en: "Four-ball is played on a pocketless table with one white, one yellow and two reds; hitting two or more balls scores a point, and 15 points wins. Turn on the post-contact trajectory line and it becomes pure power control — a one-sided win." },
        { ko: "1샷 챌린지는 한 번의 샷으로 빨간 공을 지정된 포켓에 넣는 룰입니다. 검은 공에 부딪히면 실패입니다. 난이도마다 스테이지 3개씩(EASY/NORMAL/HARD/ExHARD), 실패는 9회까지이며 그 안에 스테이지 3까지 못 가면 스테이지 1부터 다시입니다.", en: "One-Shot Challenge asks you to sink the red ball into a named pocket in a single stroke; touching a black ball fails. Each difficulty (Easy, Normal, Hard, ExHard) has three stages, you get nine failures, and running out restarts from stage 1." },
        { ko: "1샷 챌린지 보상은 초회와 2회차 이후가 다릅니다. EASY는 스테이지별 50/75/100pts에 전 클리어 보너스 450pts이고, 재클리어는 10/15/20pts로 줄어듭니다. NORMAL은 125/150pts~로 올라갑니다.", en: "One-Shot payouts drop on repeats: Easy pays 50/75/100 points per stage plus a 450-point completion bonus, falling to 10/15/20 on replays, and Normal starts at 125/150." },
      ],
      source: { label: "ゲーム攻略マン — ビリヤード攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/billiards.html" },
      achievementSlug: "billiards",
    },
    {
      slug: "darts",
      name: { ko: "다트 (DARTSLIVE3)", en: "Darts (DARTSLIVE3)" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "소텐보리 BAR 스테일 / 캐슬 투기장 접수처 앞", en: "Bar Steil, Sotenbori; in front of the Coliseum reception in the Castle" },
      summary: {
        ko: "외전의 다트 기체도 DARTSLIVE3라 「CENTER COUNT-UP」이 추가돼 01 / CRICKET / CENTER COUNT-UP / COUNT UP 4종을 즐길 수 있고, 특수 다트도 추가됐습니다.",
        en: "Gaiden also uses the DARTSLIVE3 cabinet, so Center Count-Up joins 01, Cricket and Count-Up, and special darts are available.",
      },
      howTo: [
        { ko: "싱글은 그 숫자, 더블은 2배, 트리플은 3배, BULL·더블 BULL은 모두 50점입니다. 던질 때 왼쪽의 파워 게이지가 상하로 움직이므로 베스트 존에서 눌러야 하고, 아무리 정확히 노려도 사용 중인 화살에 따라 흔들림이 남습니다.", en: "Singles score face value, doubles double, triples triple, and both bulls count 50. A power gauge slides up and down as you throw — press in the best zone — and the dart you're using still adds wobble." },
        { ko: "화살 스펙이 높을수록 손 흔들림이 줄어 던지기 쉬워집니다. 초기 「비기너 다트」는 C등급이고, 에비스야 소텐보리에서 3,000엔에 「노멀 다트」(B), 캐슬 카지노 교환소 경품 100매로 「로즈」(B), 소텐보리 분자에몬스지 서점 지붕 위(가젯 「거미」로 회수)에서 「펜슬」(A)을 얻을 수 있습니다.", en: "Higher-spec darts wobble less. You start with the C-rank Beginner Darts; Normal Darts (B) cost ¥3,000 at Ebisuya Sotenbori, Rose (B) is 100 chips at the Castle casino exchange, and Pencil (A) sits on the bookshop roof on Bunzaemon Street — grab it with the Spider gadget." },
        { ko: "달성 목록의 「해트트릭 5회」(1라운드에 3발 모두 BULL)는 혼자서도 달성할 수 있습니다.", en: "The five-hat-trick completion entry — all three darts in the bull in one round — is doable in single player." },
      ],
      source: { label: "ゲーム攻略マン — ダーツ攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/darts.html" },
      achievementSlug: "darts",
    },
    {
      slug: "karaoke",
      name: { ko: "가라오케", en: "Karaoke" },
      category: { ko: "음악·리듬", en: "Music / rhythm" },
      difficulty: 2,
      location: { ko: "소텐보리 스낵 뉴 모모코", en: "Snack New Momoko, Sotenbori" },
      summary: {
        ko: "라인을 흘러오는 □△○×를 맞춰 누르는 리듬 게임. 수록곡은 「바카미타이」, 「hands」, 「TONIGHT」, 「사요나라 Silent Night」, 「신·이·치·즈·사무라이」, 「Like A Butterfly」입니다.",
        en: "The standard rhythm game. The song list is Baka Mitai, hands, TONIGHT, Sayonara Silent Night, Shin Ichizu Samurai and Like A Butterfly.",
      },
      howTo: [
        { ko: "판정은 GREAT / GOOD / MISS이고, GREAT과 GOOD이 이어지면 콤보가 쌓입니다. 한 번이라도 실패하면 콤보는 처음부터입니다.", en: "Inputs grade GREAT, GOOD or MISS; GREAT and GOOD both extend the combo and any miss resets it." },
        { ko: "콤보 20회 이상에서 「초정열 모드」에 들어가 점수가 크게 붙습니다. 콤보를 끊지 않는 것이 사실상 유일한 공략법입니다.", en: "Twenty combo puts you in Super Passion Mode and the score jumps — keeping the combo is effectively the whole technique." },
        { ko: "외전에서는 「정열적으로 추임새」를 넣을 수 있는 곡이 일부로 제한됩니다. 수록곡 중에서는 「Like A Butterfly」만 해당합니다.", en: "Gaiden restricts the passionate call-and-response option to a few songs — of the six, only Like A Butterfly has it." },
        { ko: "아카메 드라마를 진행하면 아카메를 가라오케에 불러 듀엣을 부를 수 있고, 이것이 트로피 「Rising Superstar」 조건입니다.", en: "Advancing Akame's drama lets you invite him to karaoke for a duet — that's the Rising Superstar trophy." },
      ],
      source: { label: "ゲーム攻略マン — カラオケ攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/karaoke.html" },
      achievementSlug: "karaoke_akame",
    },
    {
      slug: "mahjong",
      name: { ko: "마작", en: "Mahjong" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "이진초 마작 시토론 (약/중/강/소주배) / 소텐보리 마작 리치로 (약/중/강/로열탁/소텐배)", en: "Mahjong Citron, Ijincho (weak/medium/strong/Shochu Cup); Mahjong Reichirou, Sotenbori (weak/medium/strong/royal/Soten Cup)" },
      summary: {
        ko: "표준 4인 마작입니다. 두 점포에서 열리는 탁의 종류가 다르고, 각각 소주배와 소텐배라는 대회가 붙어 있습니다.",
        en: "Standard four-player mahjong. The two parlours offer different table tiers and each hosts its own cup — the Shochu Cup and the Soten Cup.",
      },
      howTo: [
        { ko: "순위 우마는 약탁·중탁이 1위 +10,000 / 2위 +5,000 / 3위 −5,000 / 4위 −10,000이고, 강탁은 그 두 배(+20,000 / +10,000 / −10,000 / −20,000)입니다.", en: "Placement bonuses are +10,000 / +5,000 / −5,000 / −10,000 on the weak and medium tables, and double that on the strong table." },
        { ko: "시작 전 설정에서 대국 형식(반장전·동풍전)과 쿠이탄, 이판묶음 채용 여부를 바꿀 수 있습니다.", en: "Before starting you can switch between hanchan and tonpuusen and toggle kuitan and the two-han minimum." },
        { ko: "□로 리치, L1으로 버림패 확인, △로 룰 설명입니다.", en: "Square declares riichi, L1 reviews discards, triangle opens the rules." },
      ],
      source: { label: "ゲーム攻略マン — 麻雀攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/majan.html" },
    },
    {
      slug: "shogi",
      name: { ko: "노상 장기", en: "Street shogi" },
      category: { ko: "보드게임", en: "Board game" },
      difficulty: 3,
      location: { ko: "이진초 노상 장기 / 소텐보리 노상 장기", en: "Street shogi in Ijincho and in Sotenbori" },
      summary: {
        ko: "순위전·시련 돌파·쓰메쇼기 세 모드를 플레이할 수 있고, 이기면 장기 포인트를 받아 경품과 교환합니다. 포인트에는 별도의 숍 미션도 걸려 있습니다.",
        en: "Ranking matches, Trial Run and tsume-shogi problems, all paying Shogi Points for prizes, with a separate set of shop missions attached to them.",
      },
      howTo: [
        { ko: "상대 왕을 먼저 잡으면 승리, 잡은 말은 자기 말로 쓸 수 있고, 투료하면 패배입니다. 말이 성(成)하면 움직임이 바뀝니다.", en: "Take the enemy king to win, captured pieces come back into your hand, and resigning loses. Promoted pieces move differently." },
        { ko: "□로 「무르기」(한 수 되돌리기), L1으로 「슈퍼 무르기」를 쓸 수 있고 △로 아이템을 씁니다. 불리해졌을 때 무르기를 아끼지 마세요.", en: "Square takes back a move, L1 takes back further, and triangle uses items — don't hoard the takebacks when a position goes bad." },
      ],
      source: { label: "ゲーム攻略マン — 将棋攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/syogi.html" },
    },
    {
      slug: "koi-koi",
      name: { ko: "코이코이 (화투)", en: "Koi-koi" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "이진초 도박장(초급) / 소텐보리 도박장 요쓰데라 회관(초급) / 캐슬 도박장(초급~최상급)", en: "The Ijincho den (beginner), the Yotsudera Hall den in Sotenbori (beginner) and the Castle den (beginner through top class)" },
      summary: {
        ko: "화투 1대1 대전. 역을 완성해도 「코이코이한다」로 더 강한 역을 노릴 수 있어, 어디서 멈출지가 승부입니다. 상급 이상 탁은 캐슬 도박장에만 있습니다.",
        en: "One-on-one hanafuda. Completing a yaku lets you call koi-koi to push for a bigger one, so knowing when to stop is the game. Only the Castle den runs the higher classes.",
      },
      howTo: [
        { ko: "선은 고른 패의 달이 빠른 쪽이고 이후로는 승자가 선을 잡습니다. 지불은 득점 차 × 걸린 점수입니다.", en: "The earlier month deals first and thereafter the winner deals; payment is the score difference times the stake." },
        { ko: "손패와 장에 같은 달의 패가 있으면 가져올 수 있고(가능하면 장의 패에 색 테두리가 붙습니다), 없으면 손패를 장에 놓습니다. 그 뒤 산에서 1장을 뽑아 같은 달이면 가져옵니다.", en: "Match a month between your hand and the field to take the pair — the field card gets a coloured border when you can — otherwise you place a card. Then you draw one from the stock and take that pair if it matches." },
        { ko: "플레이에는 목찰 최소 200점이 필요합니다. 시작 전 「설정 변경」에서 급수를 고르고, 걸린 점수는 초급 10/30, 중급 40/60, 상급 70/90, 최상급 100/200점입니다.", en: "You need at least 200 points in wooden tokens to sit down. Pick a class in the settings first; stakes are 10/30 (beginner), 40/60 (intermediate), 70/90 (advanced) and 100/200 (top)." },
      ],
      source: { label: "ゲーム攻略マン — こいこい攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/koikoi.html" },
      achievementSlug: "gambling",
    },
    {
      slug: "oicho-kabu",
      name: { ko: "오이초카부", en: "Oicho-kabu" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "이진초 도박장(초급) / 소텐보리 도박장 요쓰데라 회관(초급) / 캐슬 도박장(초급~최상급)", en: "The Ijincho den (beginner), the Yotsudera Hall den in Sotenbori (beginner) and the Castle den (beginner through top class)" },
      summary: {
        ko: "11·12월을 뺀 1~10월 40장을 써서, 받은 2~3장 합계의 끝자리를 9에 가깝게 만드는 게임. 운 요소가 강해 짧게 끊어 치는 편이 낫습니다.",
        en: "Played with the 40 cards from months one to ten; get the last digit of your two or three cards as close to 9 as you can. It's largely luck, so short sessions are the sane way to play it.",
      },
      howTo: [
        { ko: "1월 패는 1, 5월 패는 5, 10월 패는 0으로 셉니다. 합계는 0에 가까울수록 약하고 9에 가까울수록 강합니다.", en: "January counts as 1, May as 5, October as 0. Totals nearer zero are weak and nearer nine are strong." },
        { ko: "승부는 선과 자 사이에서만 벌어지며 자끼리는 겨루지 않습니다. 같은 숫자면 선이 이깁니다.", en: "Only dealer versus player matters — players never compete with each other — and a tie goes to the dealer." },
        { ko: "난이도별 자의 걸린 점수는 초급 100점, 중급 500점, 상급 1,000점입니다.", en: "Player stakes are 100 points on beginner, 500 on intermediate and 1,000 on advanced." },
      ],
      source: { label: "ゲーム攻略マン — おいちょかぶ攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/oichokabu.html" },
    },
    {
      slug: "casino",
      name: { ko: "카지노 (블랙잭·포커)", en: "Casino (blackjack & poker)" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "캐슬 — 저/고/VIP 레이트", en: "The Castle — low, high and VIP rates" },
      summary: {
        ko: "캐슬 카지노에서 블랙잭과 텍사스 홀덤 포커를 즐깁니다. 칩은 교환소에서 아이템으로 바꿀 수 있고, 마스터 시스템 소프트 「더블 타깃」과 다트 「로즈」도 여기 경품입니다.",
        en: "Blackjack and Texas Hold'em at the Castle. Chips trade at the exchange — the Double Target Master System cartridge and the Rose darts both come from here.",
      },
      howTo: [
        { ko: "블랙잭: 숫자는 그대로, J·Q·K는 10, A는 1이지만 합계가 11을 넘지 않으면 11로 셉니다. 21 초과는 버스트로 즉시 패배이고, 승리 시 배당은 이긴 방식에 따라 배율이 다릅니다.", en: "Blackjack: number cards face value, J/Q/K count ten, and an ace is 1 or 11 while the total stays at or under 11. Over 21 busts, and the payout multiplier depends on how you won." },
        { ko: "커맨드는 HIT / STAND / SPLIT(처음 2장이 같은 숫자일 때) / DOUBLE DOWN이고, L2가 최소 BET, R2가 최대 BET입니다.", en: "Hit, Stand, Split (only on a matching opening pair) and Double Down; L2 is the minimum bet and R2 the maximum." },
        { ko: "포커는 텍사스 홀덤입니다. 손패 2장에 공유패가 3장 → 4장 → 5장으로 열리며 라운드마다 칩을 걸거나 내려갑니다. 역이 가장 강한 사람이 칩을 전부 가져갑니다.", en: "Poker is Texas Hold'em: two hole cards with the board opening three, four then five, betting or folding each round, winner takes the pot." },
        { ko: "동점이면 역을 만든 카드가 강한 쪽, 다음으로 역과 무관한 최강 카드(키커) 순으로 가리고, 전부 같으면 판돈을 나눕니다.", en: "Ties break on the hand's own cards, then the best unrelated card, and split the pot if everything matches." },
        { ko: "트로피 「Royal Gambler」는 캐슬의 카지노와 도박장 양쪽을 플레이해야 나옵니다.", en: "The Royal Gambler trophy needs you to play both the Castle's casino and its gambling den." },
      ],
      source: [
        { label: "ゲーム攻略マン — ブラックジャック攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/blackjack.html" },
        { label: "ゲーム攻略マン — ポーカー攻略", url: "https://dswiipspwikips3.jp/yakuza7-gaiden/play-spots/poker.html" },
      ],
    },
  ],
};
