import type { MinigamesData } from "./types";

const YT = (id: string) => `https://www.youtube.com/watch?v=${id}`;

// Minigame guides for Like a Dragon: Infinite Wealth (Yakuza 8). Locations,
// unlock conditions, rules and prize/threshold numbers come from ゲーム攻略マン's
// per-play-spot pages, PINION's 15-play-spot survey and (for the Yokohama-side
// spots ゲーム攻略マン does not cover) 神ゲー攻略 / ゲームエイト. Every entry cites
// the page its numbers came from.
export const likeADragonInfiniteWealthMinigames: MinigamesData = {
  appId: 2072450,
  intro: {
    ko: "용과 같이 8은 플레이 스폿이 하와이·요코하마·카무로초 세 곳에 흩어져 있고, PINION 기준 전 15종입니다. 서로 다른 플레이 스폿 10종을 플레이하면 트로피 'Having Fun Yet?'를 받습니다. 돈도코 섬·크레이지 딜리버리·스지몬 배틀·시코 스냅처럼 챕터나 서브스토리로 열리는 대형 종목이 컴플리션의 축이고, 마작·다트·장기·도박장·카지노 같은 단골은 하와이와 요코하마 양쪽에 있습니다. 배팅 센터·골프·캔 줍기는 8장 이후 기류 쪽 콘텐츠(엔딩 노트 미련 미션)와 엮여 있습니다.",
    en: "Infinite Wealth spreads its play spots across Honolulu, Yokohama and Kamurocho — fifteen in all by PINION's count — and playing ten different ones unlocks the \"Having Fun Yet?\" trophy. The big chapter- or substory-gated modes (Dondoko Island, Crazy Delivery, Sujimon battles, Sicko Snap) anchor completion, while the staples — mahjong, darts, shogi, the gambling den and the casino — appear on both sides of the Pacific. The batting centre, golf and can collecting are tied to Kiryu's Bucket List missions from Chapter 8.",
  },
  minigames: [
    {
      slug: "dondoko-island",
      name: { ko: "돈도코 섬", en: "Dondoko Island" },
      category: { ko: "경영·시뮬레이션", en: "Management / sim" },
      difficulty: 5,
      location: { ko: "돈도코 섬 — 서브스토리 No.33 「열려라! 밑바닥 섬」 클리어 후", en: "Dondoko Island — after clearing substory No.33" },
      summary: {
        ko: "이치반이 쓰레기 섬을 리조트로 되살리는 섬 경영 미니게임. 정지(整地)·DIY 가구·숙박객 접대로 충실도와 인기도를 올려 리조트 랭크 ★5를 목표로 합니다. 최종 조건은 충실도 43,000 / 인기도 13,000 + 치안 정비 + 클린 파이럿츠 격파이고, 달성하면 트로피 「해피 리조트 돈도코 섬」과 함께 이치반이 100만 제니·30만 달러·「돈도코 레이저의 극」을 받습니다.",
        en: "Ichiban rebuilds a trashed island into a resort: clear land, craft DIY furniture and host guests to raise Satisfaction and Popularity toward Resort Rank 5. The final bar is 43,000 Satisfaction and 13,000 Popularity plus the security cleanup and beating the Clean Pirates; clearing it pays 1,000,000 zeni, $300,000 and the Dondoko Laser move alongside the trophy.",
      },
      howTo: [
        { ko: "★1 조건은 충실도 1,000 / 인기도 700 + 입구 구역(개발력 Lv.5, 30,000제니)과 대수 구역(개발력 Lv.10, 50,000제니) 정지입니다. 개발력은 DIY로만 오르니, 자원이 남으면 무조건 가구를 만들며 굴리세요.", en: "Rank 1 needs 1,000 Satisfaction / 700 Popularity plus clearing the Entrance area (Development Lv.5, 30,000 zeni) and the Great Tree area (Development Lv.10, 50,000 zeni). Development Level only rises by crafting, so build whenever you have spare materials." },
        { ko: "섬 충실도 효율 1위는 빌딩·캬바쿠라(충실도 9,121 / 인기도 50), 그다음이 「일본 전통 건물」(6,999 / 40)입니다. 다이아몬드·플래티넘 원석은 이 두 건물에 쓰이니 절대 팔지 마세요.", en: "The most Satisfaction-dense builds are the Cabaret Club building (9,121 Satisfaction / 50 Popularity) and the Traditional Japanese Building (6,999 / 40). Diamond and platinum ore go into these, so never sell them." },
        { ko: "마지마 건설 헬멧(1칸)은 흔히 오해받는데, 집 안에 두면 올라가는 것은 섬 충실도가 아니라 '집 충실도'입니다. 상한 5,000이라 헬멧 250개로 채울 수 있고, 집 충실도가 높을수록 다음 날 이치반의 컨디션이 좋아져 자원 채집량이 늘어납니다(절호조 시 나무·돌 +3, 철·유리·반도체 등 +4). 야외에 두면 인기도 +5.", en: "The Majima Construction Helmet (1 tile) is widely misread: indoors it raises House Fullness, not island Satisfaction. The cap is 5,000, so 250 helmets max it, and higher House Fullness makes a good next-day condition more likely — in 絶好調 you gather +3 wood/stone and +4 iron, glass and semiconductors per node. Placed outdoors it is worth +5 Popularity." },
        { ko: "설계도는 개발력 상승 시 자동 습득, 해변의 유리병 줍기, 하와이 본토의 특정 인물과의 대화 세 경로로 늘어납니다. 해변 병 줍기는 매일 도는 게 좋습니다.", en: "Blueprints come from three places: development-level ups, bottles washed up on the beach, and specific NPCs back in Hawaii. Walk the shoreline every day." },
        { ko: "★2를 찍으면 무크 비치에 뗏목이 놓여 돈도코 팜이 열립니다. 작업소 「초대작 코스」는 60분에 300,000제니로 자금줄이 됩니다. 배치할 때는 스지몬 레벨보다 신뢰도, 그리고 코스 속성 일치가 대성공률을 좌우합니다.", en: "Reaching 2 stars opens Dondoko Farm via the raft at Muck Beach. The workshop's longest course pays 300,000 zeni per 60 minutes and becomes your money engine; when assigning Sujimon, trust level and matching the course's element matter more than level." },
        { ko: "★3에서 스바루의 CM과 캠프파이어가 열립니다. 로컬 방송국 CM은 100,000제니에 인기도 +200, ★4에서 열리는 전국 네트워크 CM은 200,000제니에 인기도 +500이며 각각 정해진 숙박 희망자가 추가됩니다. 캠프파이어는 100,000제니로 전 숙박객 만족도를 올리지만 숙박객 4명 이상이어야 하고 3일 투어당 1회입니다.", en: "Three stars unlocks Subaru's TV ads and the campfire. A local-station ad costs 100,000 zeni for +200 Popularity; the national-network ad unlocked at 4 stars costs 200,000 for +500, and each brings a fixed roster of new guests. The campfire costs 100,000 zeni to raise every guest's satisfaction, but needs four guests and can only be held once per three-day tour." },
        { ko: "★1부터 스바루에게서 오미야게(기념품) 개발·제작이 가능합니다. 숙박객은 3일 머무르며 하루 1개씩 받을 수 있고, 명산품보다 오미야게가 만족도가 훨씬 크며 원하는 품목을 주면 크게 오릅니다.", en: "From 1 star Subaru lets you develop and craft souvenirs. Guests stay three days and accept one gift a day; souvenirs beat raw specialties for satisfaction, and giving a guest the one they asked for is worth much more again." },
        { ko: "★5 최종전은 후크 사장 포함 파이럿츠 사원 12명과의 배틀입니다. 출발 전 사야가 「악마의 지옥냄비」×3을 주니 체력이 깎이면 쓰세요. 클리어 후에는 해방주(海坊主)·돈도코 선인 이벤트가 밤에 추가됩니다.", en: "The 5-star finale is a fight against President Hook and twelve Pirates staff. Saya hands you three Ichiban's Hell Stew items on the way — use them when your health dips. Clearing it adds the night-time Umibozu and Dondoko Hermit events." },
      ],
      videos: [
        { title: { ko: "돈도코 섬 5스타 리조트 단계별 가이드", en: "Dondoko Island 5-star resort step-by-step guide" }, url: YT("bcK_HfHrIoI") },
        { title: { ko: "돈도코 섬 5스타 달성 방법", en: "How to get 5 stars on Dondoko Island" }, url: YT("u9C4fFeTvBw") },
      ],
      source: [
        { label: "ゲーム攻略マン — ドンドコ島攻略", url: "https://dswiipspwikips3.jp/yakuza8/dondoko/" },
        { label: "ゲームエイト — 家具の一覧と設計図の入手方法", url: "https://game8.jp/ryu-ga-gotoku8/590717" },
        { label: "ゲームエイト — 家充実度の上げ方と絶好調の効果", url: "https://game8.jp/ryu-ga-gotoku8/590150" },
      ],
      achievementSlug: "resort_diy",
    },
    {
      slug: "crazy-delivery",
      name: { ko: "크레이지 딜리버리", en: "Crazy Delivery" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 4,
      location: { ko: "호놀룰루 시티 — 알로하 스트리트의 찰리 (3장, 서브스토리 No.3 이후)", en: "Aloha Street, Honolulu — Charlie, after substory No.3 in Chapter 3" },
      summary: {
        ko: "자전거로 거리를 달리며 떨어진 햄버거·피자·스시를 주워 손님에게 배달하는 크레이지 택시형 종목. 3장에서 서브스토리 No.3 「크레이지 딜리버리」를 강제로 플레이한 뒤 찰리에게 말을 걸면 상시 플레이됩니다. 실적은 딜리버리 포인트가 되고 찰리에게서 아이템으로 교환합니다. 전 난이도 클리어로 트로피 「미스터 크레이지」.",
        en: "A Crazy Taxi-style courier run: pedal around town, scoop up burgers, pizza and sushi and drop them at waiting customers. Substory No.3 in Chapter 3 forces one run, after which Charlie runs it on demand. Earnings become Delivery Points to trade with Charlie, and clearing every difficulty gives the Mr. Crazy trophy.",
      },
      howTo: [
        { ko: "트릭(앞/뒤 회전, 횡회전)을 성공시키면 평가가 Cool → Genius → Extreme으로 올라가고, 그 상태로 배달하면 배달료가 오릅니다. 넘어지면 음식을 조금 잃고 평가가 초기화되며, 일정 시간이 지나도 리셋되니 Extreme 중에 다시 트릭을 넣어 유지하세요.", en: "Landing tricks (front/back flips, side spins) walks the rating up Cool → Genius → Extreme, and delivering at a higher rating pays more. Crashing costs you some food and resets the rating, and it also decays on a timer — trick again while still in Extreme to hold it." },
        { ko: "횡회전은 착지 전도가 없는 대신 직선에서 옆으로 밀리고, 종회전은 흔들림이 적지만 착지 실패로 넘어지기 쉽습니다. 초반에는 좌스틱 상하로 기울기를 맞추는 착지 연습부터 하세요.", en: "Side spins never botch the landing but drift you off the line; flips track straighter but wipe out if you land badly. Practise balancing the landing with the left stick before chasing score." },
        { ko: "윌리(트릭 후 뒷바퀴 착지, 또는 전진 중 좌스틱↓ 길게)는 속도가 오르고 차를 날려버립니다. 드리프트(전진 중 좌스틱+×)는 감속 없이 코너를 돌면서 음식을 빨아들이고 유지 시 평가도 오릅니다. 이 둘이 시간 단축의 핵심입니다.", en: "A wheelie — land on the back wheel after a trick, or hold left stick down while riding — adds speed and knocks cars aside. A drift (left stick + cross while riding) corners without losing speed, vacuums food and raises the rating while held. These two are where the time is." },
        { ko: "크레이지 게이지가 차면 불꽃 아이콘이 최대 3개까지 쌓이고 □로 크레이지 모드 발동. 속도·회수 범위 증가, 차 격파, 평가 Extreme 고정에 무적 시간까지 붙습니다. 직선 구간에서 터뜨리고, 효과가 끝난 직후 Extreme이 남아 있을 때 트릭으로 이어받으세요.", en: "A filled Crazy gauge stocks up to three flame icons; square triggers Crazy Mode for extra speed, a wider pickup radius, car-smashing, a locked Extreme rating and invincibility. Pop it on straights, and trick immediately as it ends to keep the Extreme rating alive." },
        { ko: "필드 아이템: 코인(스코어), 크레이지 드링크(게이지 1개), 보너스 티켓(일정 시간 배달료 1.5배), 메탈릭 가방(30초간 전도해도 음식 손실 방지), 파티 박스(버거·피자·스시 5개씩). 지면의 빨간 서클 안 점프대는 스페셜 점프로 ○연타 QTE 보너스가 붙습니다.", en: "Pickups: coins (score), Crazy Drink (one gauge charge), Bonus Ticket (1.5x delivery fees for a while), Metallic Bag (30 seconds of no food loss on crashes) and Party Box (five each of burgers, pizza and sushi). Red circles on the ground hold Special Jump ramps with a circle-mash QTE bonus." },
        { ko: "손님은 미니맵에 색으로 표시됩니다. 노랑=햄버거, 주황=피자, 파랑=스시. 한 손님당 배달은 1회뿐이니 평가를 올린 뒤 넘기세요. 브레이크(L2)로 서클 안에 정차하면 배달됩니다.", en: "Customers are colour-coded on the minimap: yellow wants a burger, orange pizza, blue sushi. Each takes one delivery only, so raise the rating before handing over; brake (L2) inside their circle to deliver." },
        { ko: "난이도별 S랭크 기준은 EASY $18,000 / NORMAL $27,000 / HARD $45,000 / PROFESSIONAL $55,000입니다. HARD는 NORMAL을 C랭크 이상, PROFESSIONAL은 HARD를 C랭크 이상으로 클리어해야 열립니다.", en: "S-rank thresholds are $18,000 (Easy), $27,000 (Normal), $45,000 (Hard) and $55,000 (Professional). Hard unlocks by clearing Normal at C or better, Professional by clearing Hard at C or better." },
        { ko: "최종 배당은 평가 보너스(D~C 1.0배 / B 1.3배 / A 1.5배 / S 2.0배)와 딜리버리 랭크 보너스(GREEN 1.0 / GOLD 1.1 / PLATINUM 1.2 / DIAMOND 1.5)의 곱입니다. 포인트를 노린다면 랭크를 올려두고 도세요.", en: "Payout multiplies the grade bonus (1.0x for D–C, 1.3x B, 1.5x A, 2.0x S) by the Delivery Rank bonus (Green 1.0, Gold 1.1, Platinum 1.2, Diamond 1.5), so push your rank up before farming points." },
        { ko: "코스는 난이도가 올라도 배치가 크게 바뀌지 않고 차량 통행만 늘어납니다. 배달 후에는 방향이 반대로 돌아가는 일이 잦으니 미니맵으로 방향을 확인하고, 익숙해지면 L2+×로 브레이크 드리프트를 걸어 원하는 방향을 향한 채 배달하세요.", en: "The course layout barely changes between difficulties — mostly just more traffic. Deliveries often spin you to face back the way you came, so check the minimap after each one; once comfortable, brake-drift (L2 + cross) so you finish the delivery already pointing where you want to go." },
      ],
      videos: [
        { title: { ko: "크레이지 딜리버리 전 코스 S랭크", en: "Crazy Delivery all courses (S Rank)" }, url: YT("Yte99_EPEWY") },
        { title: { ko: "크레이지 딜리버리 100% 가이드", en: "Crazy Delivery 100% guide" }, url: YT("hNb3yKjHkTk") },
      ],
      source: [
        { label: "ゲーム攻略マン — クレイジーデリバリー攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/crazy-delivery.html" },
        { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
      ],
      achievementSlug: "delivery_clear",
    },
    {
      slug: "sujimon-battle",
      name: { ko: "스지몬 배틀 / 근신 콜로세움", en: "Sujimon Battle / Sujigami Colosseum" },
      category: { ko: "수집·배틀", en: "Collect / battle" },
      difficulty: 4,
      location: { ko: "호놀룰루 시티 전역의 스지 스폿, 아나콘다 쇼핑센터 2F 「PC숍 스지가미」", en: "Suji Spots across Honolulu; PC Shop Sujigami, 2F of the Anaconda Shopping Center" },
      summary: {
        ko: "거리의 기인들을 스지몬으로 모아 6명(선발 3·후보 3) 팀으로 싸우는 커맨드 배틀. 스지 스폿에서 강화·각성·진화·스파링·상점을 이용하고, 서브스토리 No.38 「근신 사천왕 등장」을 클리어하면 근신 콜로세움의 3개 리그가 열립니다.",
        en: "Collect the city's oddballs as Sujimon and fight six-a-side (three starters, three reserves) command battles. Suji Spots handle strengthening, awakening, evolution, sparring and the shop; clearing substory No.38 opens the Sujigami Colosseum and its three leagues.",
      },
      howTo: [
        { ko: "SP(스지몬 파워)는 장에 나온 스지몬의 민첩 합계로, 10칸을 먼저 채운 팀부터 지시합니다. 기술마다 SP 소모가 달라 SP10 기술은 강하지만 다음 턴이 느려집니다. 소모 7~8 기술이 균형이 좋고, 한 방에 못 죽일 상대라면 위력을 낮춰 손 수를 버세요.", en: "SP (Sujimon Power) is the combined speed of your on-field trio; the team that fills ten pips first acts. Each move costs different SP — a 10-cost move hits hard but delays your next turn. Moves costing 7–8 are the sweet spot, and when a big move won't finish the target, take the weaker one and win on tempo." },
        { ko: "민첩 수치는 레벨업·강화·각성으로도 오르지 않고 초기값 그대로입니다. 그래서 팀은 처음부터 민첩이 높은 스지몬으로 짜는 편이 낫습니다.", en: "Speed never rises — not from levels, strengthening or awakening; it stays at the base value. Build the team around naturally fast Sujimon from the start." },
        { ko: "속성은 핫/쿨/내추럴/포지티브/네거티브 5종. 약점을 찌르면 대미지와 MP 축적이 모두 늘어나므로, 자기 턴에 1회 가능한 교대로 상성을 맞춰 가며 싸우는 것이 기본입니다.", en: "Five elements — Hot, Cool, Natural, Positive, Negative. Hitting a weakness raises both damage and MP gain, so the core loop is using your one swap per turn to keep a favourable matchup on the field." },
        { ko: "위치도 위력에 영향을 줍니다. 화살표가 빨강이면 유리, 흰색은 보통, 보라는 불리. 정면 공격이 가장 세고 대각은 감소하며, 대각으로 너무 먼 적(좌단 → 우단)에게는 반드시 빗나갑니다.", en: "Position matters too: a red arrow means advantage, white neutral, purple disadvantage. Straight-ahead attacks hit hardest, diagonals do less, and a diagonal that is too far — left end to right end — always misses." },
        { ko: "MP는 약점 공격과 다수 타격, 그리고 파이터의 신뢰도가 높을수록 잘 찹니다. △로 필살기를 쓰면 SP는 반드시 10 소모되고, 이어서 「필살 룰렛」 목押し가 들어갑니다. 적이 필살기를 쓴 직후에 전체 회복 필살기를 맞받아치는 운용이 유효합니다.", en: "MP builds from weakness hits, multi-target attacks and high fighter trust. Triangle fires a special, always spending 10 SP and triggering the Special Roulette stop-timing. A strong pattern is holding your full-heal special until right after the enemy fires theirs." },
        { ko: "스지 스폿은 접근만 해도 랜덤 아이템을 주고, 조사하면 강화(스지테인 소모)·각성(동종 또는 근신 각성위원 배합)·진화(각성 한계까지 올린 개체)·스파링·PC숍 스지가미를 이용할 수 있습니다.", en: "Just walking up to a Suji Spot drops a random item; examining it opens strengthening (spend Sujitein), awakening (fuse same-species Sujimon or Awakening Committee members), evolution (for a fully awakened Sujimon), sparring and the PC Shop Sujigami." },
        { ko: "콜로세움 3리그: 챌린지 리그는 30마리 격파, 서바이벌 리그는 회복 없이 연전(전체 회복 필살기 보유 개체가 중요), 그랜드 리그는 1경기마다 회복이 들어가는 엘리트 연전입니다. 보상 CP는 접수처 교환소에서 아이템으로 바꿉니다.", en: "Three leagues: Challenge is a 30-Sujimon gauntlet, Survival is back-to-back fights with no healing between (a full-heal special is essential), and Grand is an elite run that does heal between matches. Colosseum Points from them trade at the reception desk." },
      ],
      videos: [
        { title: { ko: "디스크릿 포 Jack 공략 (스지몬 리그)", en: "Discreet Four: Jack walkthrough (Sujimon League)" }, url: YT("Q58IzDmujDU") },
      ],
      source: [
        { label: "ゲーム攻略マン — スジモンバトルの基本攻略", url: "https://dswiipspwikips3.jp/yakuza8/sujimo-battles/sujimo-battles-basic-knowledge.html" },
        { label: "ゲーム攻略マン — 筋神コロシアム", url: "https://dswiipspwikips3.jp/yakuza8/sujimo-battles/sujigami-colosseum.html" },
        { label: "ゲーム攻略マン — スジスポットとスジモンガチャ", url: "https://dswiipspwikips3.jp/yakuza8/sujimo-battles/suji-spots-gacha-system.html" },
      ],
      achievementSlug: "sujimon_a",
    },
    {
      slug: "sicko-snap",
      name: { ko: "시코 스냅 (불심자 스냅)", en: "Sicko Snap" },
      category: { ko: "촬영", en: "Photography" },
      difficulty: 3,
      location: { ko: "초급: 알로하 스트리트(와이키키 타운 동) / 중급: 아나콘다 거리 / 상급: 하버 스트리트", en: "Easy: Aloha Street (east Waikiki) / Normal: Anaconda Street / Hard: Harbor Street" },
      summary: {
        ko: "트롤리 버스 차창에서 거리의 변태(불심자)를 찍는 촬영 미니게임. 서브스토리 No.8로 시작합니다. 필름 잔량이 0이 되면 그 자리에서 종료되고, 종료 시 클리어 스코어를 넘기면 성공입니다. 스냅 포인트는 버스 운전사와 아이템으로 교환합니다.",
        en: "Shoot the perverts loitering along the trolley-bus route, starting from substory No.8. Running the film to zero ends the run on the spot; beating the clear score at the end is the win condition. Snap Points trade with the bus driver.",
      },
      howTo: [
        { ko: "프레임 중앙에 불심자를 잡으면 프레임이 주황으로 바뀝니다. 그때 ×로 찍으면 성공이고, 한 명당 점수는 1회뿐입니다. 그냥 찍으면 GOOD, R2 줌 상태로 찍으면 EXCELLENT입니다.", en: "Centre a sicko and the frame turns orange — press cross then. Each sicko scores once. A plain shot is GOOD; shooting while zoomed with R2 is EXCELLENT." },
        { ko: "황금색 불심자는 포즈를 취한 순간에 찍으면 TIMING BONUS가 붙습니다. 보이자마자 찍지 말고 포즈까지 한 박자 기다리세요.", en: "Golden sickos give a Timing Bonus if photographed mid-pose — don't fire the instant you see one, wait a beat for the pose." },
        { ko: "흰색 → 파랑 → 빨강 순으로 노출도가 높을수록 포인트가 크지만 그만큼 찍기 어렵게 설정돼 있습니다. 결국 반복 플레이로 출현 위치를 외우는 것이 공략의 핵심입니다.", en: "The more exposed the outfit (white, then blue, then red), the more points — and the harder the shot. Learning spawn positions by repetition is the real technique." },
        { ko: "코스별 수치 — 초급 「처음 뵙겠습니다 파피용」: 클리어 4,000 / 필름 50 / 불심자 30명 / S랭크 최고 11,375. 중급 「거리에 숨은 파피용」: 6,000 / 75 / 40명 / 15,750. 상급 「파피용 피버」: 9,000 / 99 / 50명 / 19,125.", en: "Course numbers — Easy: clear 4,000, 50 film, 30 sickos, S-rank best 11,375. Normal: 6,000 / 75 film / 40 sickos / 15,750. Hard: 9,000 / 99 film / 50 sickos / 19,125." },
      ],
      videos: [
        { title: { ko: "시코 스냅 전 코스 S랭크", en: "Sicko Snap all courses (S Rank)" }, url: YT("VsbuhUSovcA") },
        { title: { ko: "시코 스냅 전 30마리 S랭크 (이지)", en: "Sicko Snap all 30 sickos, S rank (Easy)" }, url: YT("B1Lq4w6n_eQ") },
      ],
      source: { label: "ゲーム攻略マン — 不審者スナップ攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/snap-that-sickos.html" },
      achievementSlug: "snap_claer",
    },
    {
      slug: "miss-match",
      name: { ko: "미스 매치 (매칭 앱)", en: "Miss Match" },
      category: { ko: "연애·대화", en: "Dating / dialogue" },
      difficulty: 3,
      location: { ko: "와이키키 타운 서 구역 — 팬케이크 하우스 크림&베리 와이키키점 (3장, 서브스토리 「마치코 씨」)", en: "Pancake House Cream & Berry, west Waikiki — via the substory in Chapter 3" },
      summary: {
        ko: "이치반의 프로필과 아이콘을 편집해 여성과 매칭하고, 채팅으로 「기분 게이지」를 올려 대면 데이트까지 가는 미니게임. 상대는 노멀/골드/프리미엄 회원 등급으로 나뉘며 전 10명입니다. 5명과 만나면 트로피.",
        en: "Edit Ichiban's profile and icon, match with women, then raise the mood gauge over chat until she agrees to meet. Partners are split across Normal, Gold and Premium membership tiers — ten in all — and meeting five earns a trophy.",
      },
      howTo: [
        { ko: "프로필 문장은 위에서부터 「직업 / 성격 / 취미 / 취미 / 마지막 한마디」 키워드에 L1·R1로 문체(보통·정중·하이텐션·의식 높음·오라오라·전문가풍 6종)를 조합해 만듭니다. 아이콘을 바꾸면 매칭되는 상대 자체가 달라집니다.", en: "The profile is built from five keyword slots — job, personality, hobby, hobby, closing line — plus one of six tones set with L1/R1 (plain, polite, high-energy, aspirational, tough-guy, connoisseur). Changing the icon changes who you match with at all." },
        { ko: "게임에이트에 따르면 프로필에서 가장 중요한 항목은 직업입니다. 상대가 선호하는 직업을 설정하지 않으면 게이지가 크게 늘지 않습니다.", en: "Per Game8, the decisive profile field is the job: if it isn't one the target likes, the gauge simply won't move far." },
        { ko: "회원 플랜은 노멀 1,000pt / 골드 3,000pt / 프리미엄 5,000pt가 1매칭당 소모이고, pt는 1,000pt=10달러로 현금 구매합니다. 플랜 변경 자체에는 pt가 들지 않습니다.", en: "A match costs 1,000 points on Normal, 3,000 on Gold and 5,000 on Premium; points are bought with cash at 1,000 per $10. Switching plans itself is free." },
        { ko: "선택지 답장은 고른 뒤 ○×△□ 커맨드를 제한 시간 안에 순서대로 입력해야 합니다. 문장이 길수록 커맨드가 길지만 게이지 상승폭이 큽니다. EXCELLENT +15~25, GREAT +10~12, NORMAL +8, BAD ±0, MISS −8~10 — 정답을 골라도 입력을 놓치면 깎이니 입력 성공이 최우선입니다.", en: "After picking a reply you must enter its circle/cross/triangle/square string in order against a timer. Longer replies mean longer strings but bigger gains: EXCELLENT +15–25, GREAT +10–12, NORMAL +8, BAD 0, MISS −8 to −10. A correct choice you fumble still costs you, so landing the input comes first." },
        { ko: "스탬프 답장은 옆으로 흐르는 스탬프를 ×로 멈추는 방식으로, 빨리 보낼수록 배율이 큽니다(×1.25 → ×1.10 → ×1.00 → ×0.80). 게이지를 깎는 스탬프도 섞여 있으니 내용도 보세요.", en: "Stamp replies slide past and are locked with cross; sending early pays more (x1.25, x1.10, x1.00, x0.80). Some stamps lower the gauge, so read them, don't just mash." },
        { ko: "게이지가 카메라 아이콘을 지나면 사진을, 하트 아이콘을 지나면 대면 데이트를 얻습니다. 메모리즈에서는 pt 소모 없이 지난 채팅과 사진을 다시 볼 수 있습니다.", en: "Passing the camera icon on the gauge earns a photo, passing the heart unlocks the in-person date. Memories replays past chats and photos at no point cost." },
        { ko: "상대별 성향(공략 페이지 기준): 카나포요=텐션 높고 위험한 사람, 카오루=아웃로 느낌, 카노=게임·소년만화, 사호리=운동부·열혈, ETSU=마작·파친코와 밴드맨 같은 열정, 소피=품격·로맨틱(음악 취미, 운동 못함), 나오미=진지한 교제·독서(도박 싫어함), 마리=의식 높은 라이프·카페 순례(도박 싫어함), 린샨=모델 동업자·요리(음담 싫어함), 키나코=코스프레·술·밝은 성격·RPG(음악 못함).", en: "Partner preferences per the guide: Kanapoyo likes high-energy and dangerous types; Kaworu wants an outlaw edge; Kano likes games and shonen manga; Sahori is a sports type who hates complicated talk; ETSU is into mahjong and pachinko and admires band-guy passion; Sophie wants dignity and romance (music, no sports); Naomi wants serious intent and reading (no gambling); Marie wants an aspirational lifestyle and cafes (no gambling); Linshan is a model who welcomes fellow models and cooking (no crude jokes); Kinako is a cosplayer into drink, bright personalities and RPGs (no music)." },
      ],
      videos: [
        { title: { ko: "미스 매치 100% 가이드", en: "Miss Match 100% guide" }, url: YT("umiHBD0bRvo") },
      ],
      source: [
        { label: "ゲーム攻略マン — マッチングアプリ攻略", url: "https://dswiipspwikips3.jp/yakuza8/miss-match/" },
        { label: "ゲームエイト — マッチングアプリの攻略とプロフィールの書き方", url: "https://game8.jp/ryu-ga-gotoku8/589714" },
      ],
      achievementSlug: "matchingapp_a",
    },
    {
      slug: "alo-happy-tours",
      name: { ko: "알로 해피 투어 (액티비티·직업 해금)", en: "Alo-Happy Tours (activities / job unlocks)" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 2,
      location: { ko: "호놀룰루 시티 — 알로 해피 투어즈", en: "Alo-Happy Tours, Honolulu" },
      summary: {
        ko: "여행사 알로 해피 투어즈의 액티비티를 돈과 인간력으로 구매하면 그에 대응하는 직업이 해금되는 구조입니다. 액티비티 8종을 체험하면 트로피 「Alo-Happy as Can Be」. 같은 직업이라도 캐릭터마다 필요한 절(絆) 레벨이 달라서, 원하는 멤버 기준으로 절을 먼저 올려둬야 합니다.",
        en: "Buying an activity from the Alo-Happy Tours travel agency — each gated by money and a personality stat — unlocks the matching job, and experiencing eight of them gives the Alo-Happy as Can Be trophy. The bond level required differs per party member for the same job, so raise bonds with the member you actually want first.",
      },
      howTo: [
        { ko: "마린 마스터 — 「마린 액티비티 팩」, 상냥함 Lv.1, 0달러. 나바·한 준기는 초기 해금, 아다치·조천우는 절 Lv.30 이상.", en: "Marine Master — Marine Activity Pack, Kindness Lv.1, $0. Nanba and Han Jun-gi start unlocked; Adachi and Zhao need bond 30." },
        { ko: "웨스턴맨 — 「워터건 배틀」, 세련 Lv.5, 1,600달러. 한 준기 초기 해금, 아다치·나바·조천우는 절 Lv.10 이상.", en: "Desperado — Water Gun Battle, Style Lv.5, $1,600. Han starts unlocked; Adachi, Nanba and Zhao need bond 10." },
        { ko: "와일드 댄서 — 「파이어 댄스 쇼」, 정열 Lv.3, 200달러. 나바 초기 해금, 아다치 절 Lv.20, 조천우·한 준기 절 Lv.40.", en: "Wild Dancer — Fire Dance Show, Passion Lv.3, $200. Nanba starts unlocked; Adachi bond 20, Zhao and Han bond 40." },
        { ko: "액션 스타 — 「파라세일링」, 쾌활 Lv.4, 200달러. 조천우 초기 해금, 한 준기 절 Lv.10, 나바 절 Lv.40.", en: "Action Star — Parasailing, Charisma Lv.4, $200. Zhao starts unlocked; Han bond 10, Nanba bond 40." },
        { ko: "사무라이 — 「트롤리 투어」, 멘탈 Lv.5, 1,600달러. 조천우 절 Lv.20, 나바 절 Lv.50, 한 준기 절 Lv.50.", en: "Samurai — Trolley Tour, Confidence Lv.5, $1,600. Zhao bond 20, Nanba bond 50, Han bond 50." },
        { ko: "쿠노이치 — 「비치 요가」, 지성 Lv.5, 1,600달러. 손희 초기 해금, 무코다 사에코 절 Lv.10.", en: "Kunoichi — Beach Yoga, Intellect Lv.5, $1,600. Seonhee starts unlocked; Saeko needs bond 10." },
        { ko: "하우스키퍼 — 「면세 쇼핑」, 상냥함 Lv.4, 200달러. 사에코 초기 해금, 손희 절 Lv.10.", en: "Housekeeper — Duty-Free Shopping, Kindness Lv.4, $200. Saeko starts unlocked; Seonhee needs bond 10." },
        { ko: "트로피컬 댄서 — 「훌라 댄스 쇼」, 정열 Lv.1, 200달러. 손희·사에코 모두 절 Lv.30.", en: "Tropical Dancer — Hula Dance Show, Passion Lv.1, $200. Both Seonhee and Saeko need bond 30." },
        { ko: "테니스 플레이어(리조트 에스테, 쾌활 Lv.5, 1,600달러)와 풋볼러(코코넛 만끽 투어, 멘탈 Lv.5, 1,600달러)는 DLC 「스페셜 잡 세트」에 포함된 직업입니다.", en: "Tennis Player (Resort Spa, Charisma Lv.5, $1,600) and Footballer (Coconut Tour, Confidence Lv.5, $1,600) come with the Special Job Set DLC." },
        { ko: "이치반의 전용 직업 「소환사」는 액티비티가 아니라 서브스토리 No.38 「근신 사천왕 등장」 클리어로 열립니다.", en: "Ichiban's exclusive Sujimancer job doesn't come from an activity — it unlocks by clearing substory No.38." },
      ],
      videos: [
        { title: { ko: "알로 해피 투어 전 직업 해금 (4K)", en: "All Alo-Happy Tours / job revelations (4K)" }, url: YT("F7-51Ni7s1k") },
      ],
      source: { label: "ゲーム攻略マン — ジョブ入手条件一覧", url: "https://dswiipspwikips3.jp/yakuza8/jobs/" },
      achievementSlug: "activity_clear",
    },
    {
      slug: "license-school",
      name: { ko: "오우나바라 라이선스 스쿨 (자격 검정)", en: "Ounabara Vocational School" },
      category: { ko: "퀴즈", en: "Quiz" },
      difficulty: 2,
      location: { ko: "호놀룰루 시티 — 하버 스트리트 (4장, 서브스토리 No.21 「대해원에 렛츠 다이브!」)", en: "Harbor Street, Honolulu — Chapter 4, substory No.21" },
      summary: {
        ko: "수험료를 내고 4지선다 퀴즈를 푸는 자격 학교. 합격하면 대응하는 인간력이 크게 오릅니다(첫 합격 시). 자격 10종 취득으로 트로피 「License to Skill」, 20종 전부 합격하면 최종 「대해원 검정」이 열립니다.",
        en: "Pay an entry fee and answer multiple-choice questions; passing raises the matching personality stat (on the first pass). Ten certificates give the License to Skill trophy, and passing all twenty opens the final Ounabara Exam.",
      },
      howTo: [
        { ko: "각 검정은 10문제 중 5문제가 랜덤 출제됩니다. 떨어지면 수험료를 다시 내야 하니 도전 전에 세이브를 만들어 두세요. 한 번 합격한 자격은 이후 무료로 몇 번이든 재플레이할 수 있습니다.", en: "Each exam draws five questions at random from a pool of ten. Failing means paying again, so save before attempting one; a certificate you have already passed can be replayed free." },
        { ko: "접수처 옆의 이가리에게서 보조 기술 두 가지를 살 수 있습니다. 「초집중」 1,000달러 = △로 제한 시간 30초 연장, 「신에게 비는 연필」 5,000달러 = □로 오답 3개 중 2개를 확실히 지움. 각각 1회 시험에 1번만 쓸 수 있지만, 한 번 사면 영구적으로 사용 가능합니다.", en: "Igari beside the reception sells two aids: Hyperfocus ($1,000, triangle, +30 seconds) and the Pencil of Providence ($5,000, square, removes two of the three wrong answers). Each is once per exam, but buying them is a one-time cost." },
        { ko: "수험료는 대체로 300~500달러이고, 최종 「대해원 검정」은 1,000달러입니다. 검정은 전 20자격 합격 후에만 볼 수 있고 랜덤 5문제 전부를 맞혀야 합격이며, 보상으로 정열·멘탈·세련이 각 +100 오릅니다.", en: "Fees run $300–500 for the regular exams and $1,000 for the Ounabara Exam, which only unlocks after all twenty certificates and requires all five random questions correct — worth +100 Passion, Confidence and Style." },
        { ko: "접수처의 마에다 로라에게 지성이 필요한 선물을 3번 건네면 서브스토리 No.47 「로라로 상처투성이」가 발생합니다.", en: "Giving receptionist Laura Maeda three gifts (which need Intellect) triggers substory No.47." },
      ],
      source: [
        { label: "ゲーム攻略マン — 大海原ライセンススクール", url: "https://dswiipspwikips3.jp/yakuza8/ounabara-vocational-school/" },
        { label: "ゲームエイト — ライセンススクールの答え", url: "https://game8.jp/ryu-ga-gotoku8/589695" },
      ],
      achievementSlug: "qualification",
    },
    {
      slug: "casino",
      name: { ko: "카지노 (블랙잭·포커)", en: "Casino (blackjack & poker)" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "하와이 「흑부용(黒芙蓉)」(6장) / 요코하마 이세자키 이진초 중화가 남 공중화장실 안쪽 칸 벽, m HOLD'EM 진나이", en: "Black Orchid, Hawaii (Chapter 6); the back stall of the public toilet south of Chinatown in Ijincho, and m HOLD'EM Jinnai" },
      summary: {
        ko: "블랙잭과 텍사스 홀덤 포커를 칩으로 즐깁니다. 하와이는 1달러/칩, 이세자키 이진초는 1엔/칩, m HOLD'EM 진나이는 100엔/포인트. 인간력 「세련」과 기류의 각성도가 오르고, 「동료와 플레이」를 고르면 절 레벨도 오릅니다.",
        en: "Blackjack and Texas Hold'em for chips — $1 a chip in Hawaii, ¥1 in Ijincho, ¥100 per point at m HOLD'EM Jinnai. Playing raises Style and Kiryu's Awakening, and the \"play with a friend\" option raises bond levels.",
      },
      howTo: [
        { ko: "블랙잭 기본: 숫자 카드는 그대로, J·Q·K는 10, A는 1이지만 합계가 11을 넘지 않으면 11로 셉니다. 21 초과는 버스트로 즉시 패배입니다.", en: "Blackjack basics: number cards face value, J/Q/K count 10, and an ace is 1 — or 11 while the total stays at or under 11. Going over 21 busts you immediately." },
        { ko: "커맨드는 HIT(1장 추가) / STAND(현재 합계로 승부) / SPLIT(처음 2장이 같은 숫자일 때 손패를 둘로 나눔) / DOUBLE DOWN. L2가 최소 BET, R2가 최대 BET이라 베팅 조작이 빠릅니다.", en: "Commands are Hit, Stand, Split (only when the opening two cards match) and Double Down. L2 sets the minimum bet and R2 the maximum, which speeds the betting up a lot." },
        { ko: "포커는 텍사스 홀덤입니다. 자기 패 2장 + 중앙 공유패로 역을 만들고, 라운드마다 BET / CHECK / CALL / 폴드를 고릅니다. 공유패는 3장 → 4장 → 5장 순으로 열립니다.", en: "Poker is Texas Hold'em: two hole cards plus community cards, with a bet/check/call/fold decision each round as the board opens to three, then four, then five cards." },
        { ko: "동점 판정은 역을 만든 카드가 강한 쪽, 그다음 역과 무관한 카드 중 최강 카드(키커), 전부 같으면 무승부로 판돈을 나눕니다. 카드 강약은 2 < … < 10 < J < Q < K < A.", en: "Ties break on the stronger cards making the hand, then the best unrelated card (the kicker); if everything matches, the pot is split. Card order is 2 up to 10, then J, Q, K, A." },
        { ko: "하와이 카지노는 6장에서 카지노에 쳐들어가는 스토리를 진행해야 열립니다. 획득한 칩은 아이템으로 교환합니다.", en: "The Hawaii casino only opens once Chapter 6's storming-the-casino sequence is done. Chips trade for items." },
      ],
      source: [
        { label: "ゲーム攻略マン — カジノ『ブラックジャック』攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/blackjack.html" },
        { label: "ゲーム攻略マン — カジノ『ポーカー』攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/poker.html" },
        { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
      ],
    },
    {
      slug: "gambling-hall",
      name: { ko: "도박장 (코이코이·오이초카부)", en: "Gambling den (koi-koi & oicho-kabu)" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "하와이 츠바키 스트리트 동쪽 뒷골목 (멘탈 Lv.3 이상) / 요코하마 대로의 사다리를 내려가 하수도", en: "The back alley east of Tsubaki Street, Hawaii (needs Confidence Lv.3); down the ladder on Yokohama Boulevard into the sewers" },
      summary: {
        ko: "화투로 코이코이와 오이초카부를 하는 지하 도박장. 입구의 교환역에게서 1점=1달러(100엔)로 목찰을 사서 시작하며, 목찰은 하와이·요코하마 공통이라 어느 쪽에서든 교환할 수 있습니다. 「동료와 플레이」로 절 레벨도 오릅니다.",
        en: "An underground den running koi-koi and oicho-kabu on hanafuda. Buy wooden tokens from the changer at the entrance at one point per dollar (¥100), and note the tokens are shared between Hawaii and Yokohama, so either den can cash them. The \"play with a friend\" option raises bonds.",
      },
      howTo: [
        { ko: "코이코이는 1대1로, 손패와 장의 같은 달 패를 맞춰 역을 만드는 게임입니다. 역이 완성되면 「코이코이한다」로 더 강한 역을 노리거나, 「하지 않는다」로 그 자리에서 승부를 마칠 수 있습니다. 이 판단이 승부처입니다.", en: "Koi-koi is one on one: pair cards of the same month from your hand and the field to build yaku. When one completes you either call koi-koi to keep pushing for a bigger hand or stop and bank it — that call is the whole game." },
        { ko: "선(親)은 고른 패의 달이 빠른 쪽이고, 이후로는 승자가 선을 가져갑니다. 지불은 득점 차 × 걸린 점수로 계산됩니다.", en: "The dealer is whoever picks the earlier month, and thereafter the winner deals. Payment is the score difference times the stake." },
        { ko: "코이코이 플레이에는 목찰 최소 200점이 필요합니다. 시작 전 「설정 변경」에서 급수를 고르며 걸린 점수는 초급 10/30점, 중급 40/60점, 상급 70/90점, 최상급 100/200점입니다.", en: "Koi-koi needs at least 200 points in tokens. Pick a class in the settings first; stakes are 10/30 (beginner), 40/60 (intermediate), 70/90 (advanced) and 100/200 (expert)." },
        { ko: "오이초카부는 11·12월을 뺀 1~10월 40장으로, 배분된 2~3장 합계의 끝자리를 9에 가깝게 만드는 게임입니다. 승부는 선과 자(子) 사이에서만 벌어지고, 같은 숫자면 선이 이깁니다. 난이도별 자의 걸린 점수는 초급 100점, 중급 500점, 상급 1,000점.", en: "Oicho-kabu uses the 40 cards from months one to ten; you want the last digit of your two- or three-card total as close to 9 as possible. Only dealer versus player matters, ties go to the dealer, and the player stake is 100 (beginner), 500 (intermediate) or 1,000 (advanced) points." },
        { ko: "오이초카부는 시작 전 설정에서 「돗시핀」과 「시로쿠의 도주」 채용 여부, 그리고 패 디자인을 주찰/화투 중에서 고를 수 있습니다.", en: "Oicho-kabu's settings toggle the Dosshipin and Shiroku-no-nige house rules and let you switch the deck art between kabufuda and hanafuda." },
      ],
      source: [
        { label: "ゲーム攻略マン — 賭場『こいこい』攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/koikoi.html" },
        { label: "ゲーム攻略マン — 賭場『おいちょかぶ』攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/oichokabu.html" },
        { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
      ],
    },
    {
      slug: "karaoke",
      name: { ko: "가라오케", en: "Karaoke" },
      category: { ko: "음악·리듬", en: "Music / rhythm" },
      difficulty: 2,
      location: { ko: "호놀룰루 시티 리틀 재팬 구역 — 리볼버 (1곡 5달러)", en: "Revolver, Little Japan, Honolulu ($5 a song)" },
      summary: {
        ko: "라인을 타고 흘러오는 □△○×를 타이밍에 맞춰 입력하는 리듬 게임. 길게 누르기·연타 구간이 섞여 있습니다. 함께 부른 동료의 절 랭크가 오르고, 90점 이상이면 리볼버 마스터의 호감도가 오릅니다.",
        en: "The series rhythm game — square, triangle, circle and cross scroll down a line, with held and mashed sections mixed in. Singing raises the bond rank of whoever joined you, and scoring 90+ raises the Revolver master's affection." },
      howTo: [
        { ko: "판정은 GREAT / GOOD / MISS입니다. GREAT과 GOOD이 연속되면 콤보가 쌓이고 한 번이라도 실패하면 처음부터 리셋됩니다.", en: "Inputs grade as GREAT, GOOD or MISS. GREAT and GOOD both extend the combo; a single miss resets it to zero." },
        { ko: "콤보 20회 이상에서 「초정열 모드」에 들어가 점수가 급격히 오릅니다. 결국 콤보를 끊지 않는 것이 최대 공략 포인트입니다.", en: "Past twenty combo you enter Super Passion Mode and the score climbs fast — keeping the combo alive is the whole technique." },
        { ko: "추임새(合いの手)를 넣을 수 있는 곡에서는 「무난하게」와 「정열적으로」 중 고르는데, 무난하게는 쉬운 대신 90점을 넘길 수 없습니다. 100점을 노린다면 반드시 「정열적으로」를 고르세요.", en: "On duet songs with call-and-response you choose between a safe and a passionate backing. The safe one is easier but caps you below 90 points — for a 100 you must take the passionate option." },
        { ko: "리듬 조작 없이 노래 장면만 보는 「회상」 모드와, 곡별 재생수 랭킹·하이스코어·최근 부른 곡 이력도 볼 수 있습니다.", en: "There is also a Reminisce mode that just plays the performance with no inputs, plus per-song play counts, high scores and a recently-sung list." },
      ],
      source: { label: "ゲーム攻略マン — カラオケ攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/karaoke.html" },
    },
    {
      slug: "darts",
      name: { ko: "다트 (DARTSLIVE3)", en: "Darts (DARTSLIVE3)" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "하와이 크리스탈 알로하 리조트 1층 / 요코하마 이진초 베이사이드 거리 (1플레이 2달러)", en: "Crystal Aloha Resort 1F, Hawaii; Bayside Street, Ijincho ($2 a play)" },
      summary: {
        ko: "8편의 다트 기체는 최신 DARTSLIVE3라 신 종목 「CENTER COUNT-UP」이 추가됐습니다. 01 / CRICKET / CENTER COUNT-UP / COUNT UP 4종을 즐길 수 있고, 동료를 불러 대전하면 절이 오릅니다.",
        en: "Infinite Wealth uses a DARTSLIVE3 cabinet, which adds Center Count-Up to the usual 01, Cricket and Count-Up. Bringing a party member along raises bonds.",
      },
      howTo: [
        { ko: "던질 때 왼쪽에 파워 게이지가 상하로 움직입니다. 베스트 존에서 버튼을 눌러야 하고, 아무리 정확히 노려도 사용 중인 화살에 따라 흔들림이 남습니다. 싱글 = 그 숫자, 더블 = 2배, 트리플 = 3배, BULL·더블 BULL은 모두 50점입니다.", en: "A power gauge slides up and down on the left as you throw; hit the best zone. Even a perfect aim wobbles depending on the dart you're using. Singles score face value, doubles double, triples triple, and both the bull and double bull count 50." },
        { ko: "다트 옆에 다트 가게가 있어 돈으로 화살을 살 수 있습니다. 스펙이 높을수록 손 흔들림이 줄어 훨씬 던지기 쉬워지니, 성적이 안 나오면 먼저 화살부터 바꾸세요.", en: "There's a dart shop beside the cabinet; higher-spec darts reduce the wobble noticeably, so upgrade the arrows before blaming your aim." },
        { ko: "01은 설정 점수를 정확히 0으로 만드는 종목입니다. 301/501/701/901 중 301이 가장 빠릅니다. 301이면 BULL·더블 BULL ×3을 두 라운드 맞히고 마지막에 1을 맞히면 끝나며, 중급까지는 이 방법으로 충분합니다.", en: "01 is about reducing your score to exactly zero — of 301/501/701/901, 301 is quickest. On 301, two rounds of three bulls plus a final 1 finishes it, which carries you through the intermediate opponents." },
        { ko: "크리켓은 15~20과 BULL만 유효한 진지 뺏기입니다. 싱글 1마크·더블 2마크·트리플 3마크로 합계 3마크면 클로즈. 기본은 20 트리플만 노리고, 던지기에 익숙하지 않으면 BULL만 노려도 중급까지는 이깁니다. 클로즈한 뒤에는 그 트리플만 계속 노려 점수를 쌓는 편이 낫습니다.", en: "Cricket only counts 15 through 20 and the bull: singles are one mark, doubles two, triples three, and three marks closes a number. Aim triple 20 by default; if your throw isn't steady, bull-only will still beat the intermediate opponents. Once a number is closed, keep hammering that same triple for points." },
        { ko: "CENTER COUNT-UP은 3라운드 합계로 겨루며 중심에 가까울수록 고득점입니다. 정중앙 600점에서 바깥으로 500 → 480 → 400 → 350 → 200 → 100 → 80 → 70 → 60 → 50으로 떨어집니다.", en: "Center Count-Up scores three rounds by proximity to the middle: 600 dead centre, then 500, 480, 400, 350, 200, 100, 80, 70, 60 and 50 outward." },
        { ko: "달성 목록의 「해트트릭 5회」(1라운드에 3발 모두 BULL)는 혼자서도 달성할 수 있습니다.", en: "The completion-list entry for five hat-tricks — all three darts in the bull in one round — can be done in single player." },
      ],
      source: { label: "ゲーム攻略マン — ダーツ攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/darts.html" },
    },
    {
      slug: "mahjong",
      name: { ko: "마작", en: "Mahjong" },
      category: { ko: "도박", en: "Gambling" },
      difficulty: 3,
      location: { ko: "하와이 차이나타운 지하 작장 판타지아 / 이진초 마작 시토론 / 중화가 화조풍월 / 카무로초 마작 라라바이", en: "Underground Parlour Fantasia (Chinatown, Hawaii); Mahjong Citron and Kachofugetsu in Ijincho; Mahjong Lullaby in Kamurocho" },
      summary: {
        ko: "표준 4인 마작. 8편에서는 교환 아이템이나 트로피가 걸려 있지 않아, 인간력 「멘탈」과 동료 절 올리기, 그리고 레인보우 컵·소주배 우승 상금이 목적이 됩니다.",
        en: "Standard four-player mahjong. There are no exchange items or trophies attached in Infinite Wealth, so the reasons to play are Confidence, party bonds and the Rainbow Cup / Shochu Cup prize money.",
      },
      howTo: [
        { ko: "난이도(탁)는 약탁·중탁·강탁·로열탁이 있고, 순위 우마는 약탁·중탁이 1위 +10,000 / 2위 +5,000 / 3위 −5,000 / 4위 −10,000, 강탁은 그 2배(+20,000 / +10,000 / −10,000 / −20,000)입니다.", en: "Tables run weak, medium, strong and royal. Placement bonuses on the weak and medium tables are +10,000 / +5,000 / −5,000 / −10,000, and double that on the strong table." },
        { ko: "대국 형식은 반장전(4명이 2번씩 친을 하면 종료)과 동풍전(1번씩) 중 고르고, 쿠이탄과 이판묶음(친이 5연속 화료 중일 때 2판 이상 필요) 채용 여부도 시작 전 설정에서 바꿉니다.", en: "Choose hanchan (each player deals twice) or tonpuusen (once each), and toggle kuitan and the two-han minimum rule (which applies while the dealer is on a five-hand streak) before starting." },
        { ko: "요금은 약함 125달러/5,000엔, 보통 250달러/25,000엔, 동료와 플레이 250달러/25,000엔(동료 3명 필요)입니다. 전 탁에서 플레이한 경험이 있으면 레인보우 컵(1,000달러)과 소주배(5만 엔)가 열리고, 우승 상금은 5,000달러/20만 엔에 경품 아이템이 붙습니다.", en: "Entry is $125 / ¥5,000 on easy, $250 / ¥25,000 on normal, and the same to play with three party members. Playing every table type unlocks the Rainbow Cup ($1,000) and Shochu Cup (¥50,000), which pay $5,000 / ¥200,000 plus a prize item for the win." },
        { ko: "리치는 □ 버튼, L1으로 버림패 확인, △로 룰 설명입니다. 역 일람이 화면에 표시되니 확인하며 두면 됩니다.", en: "Square declares riichi, L1 reviews discards and triangle brings up the rules; the yaku list is on screen while you play." },
      ],
      source: [
        { label: "ゲーム攻略マン — 麻雀攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/majan.html" },
        { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
      ],
    },
    {
      slug: "shogi",
      name: { ko: "노상 장기", en: "Street shogi" },
      category: { ko: "보드게임", en: "Board game" },
      difficulty: 3,
      location: { ko: "하와이 사쿠라 스트리트 공원 안 / 요코하마 이세자키 이진초 사쿠라가와도리 남", en: "Sakura Street park, Hawaii; south Sakuragawa Street, Isezaki Ijincho" },
      summary: {
        ko: "공원의 아저씨에게 말을 걸어 시작합니다. 순위전·시련 돌파·쓰메쇼기 세 모드가 있고, 이기면 장기 포인트를 받아 경품과 교환합니다. 인간력 「지성」이 오릅니다.",
        en: "Talk to the old man in the park to start. Three modes — ranking matches, Trial Run and tsume-shogi problems — pay Shogi Points for prizes and raise Intellect.",
      },
      howTo: [
        { ko: "규칙은 표준 장기입니다. 상대 왕을 먼저 잡으면 승리, 잡은 말은 자기 말로 쓸 수 있고, 「투료」하면 패배입니다. □가 무르기, L1이 슈퍼 무르기, △가 아이템 사용입니다.", en: "Standard shogi: take the opposing king to win, captured pieces return to your hand, and resigning loses. Square takes a move back, L1 takes back further and triangle uses an item." },
        { ko: "순위전과 시련 돌파는 자력으로 이기기 상당히 어렵습니다. 공략 페이지도 bonanza 같은 장기 프리 소프트에 국면을 넣고 다음 수를 받아 두는 방식을 권합니다.", en: "The ranking matches and Trial Run are genuinely hard to win unaided — the guide itself recommends feeding the position into a free shogi engine such as Bonanza and playing its suggestion." },
        { ko: "쓰메쇼기는 특수 초기 국면에서 정해진 수 안에 상대 옥을 잡는 문제로, 매 수 왕수가 아니면 그 시점에 실패입니다. 전 10문제이며 1~2수로 끝나는 난이도라 포인트 벌이로 편합니다.", en: "Tsume-shogi sets a fixed position you must mate within a set number of moves, failing the instant a move isn't check. There are ten problems, all one or two moves deep, which makes them the easy point source." },
        { ko: "경품 중 최상위는 21,000pt의 「웨스턴맨의 리볼버」(★5, 공격력 +107 / 마력 +100)이고, 무기 강화 소재 「강화철강·하」 850pt, 「·중」 1,700pt도 여기서 삽니다.", en: "The top prize is the Desperado's Revolver at 21,000 points (5 star, +107 attack, +100 magic); the shop also sells weapon-upgrade steel at 850 and 1,700 points." },
      ],
      source: [
        { label: "ゲーム攻略マン — 将棋攻略", url: "https://dswiipspwikips3.jp/yakuza8/play-spots/syogi.html" },
        { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
      ],
    },
    {
      slug: "arcade",
      name: { ko: "게임센터 (아케이드·UFO 캐처)", en: "Arcade (cabinets & UFO catcher)" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "하와이 아나콘다 쇼핑센터 / 이진초 GiGO 중화가점·게임센터 사사키 / 카무로초 극장 앞 광장점", en: "Anaconda Shopping Center, Hawaii; GiGO Chinatown and Game Center Sasaki in Ijincho; the Theater Square branch in Kamurocho" },
      summary: {
        ko: "실제 세가 아케이드 3종과 UFO 캐처, 스지몬 가챠가 놓여 있습니다. 인간력 「쾌활」이 오르고, 하와이에서는 UFO 캐처 경품을 특정 인물에게 건네 친구가 될 수 있어 알로하 링크스와 직결됩니다.",
        en: "Three real SEGA cabinets plus the UFO catcher and a Sujimon gacha. Playing raises Charisma, and in Hawaii the UFO catcher prizes can be handed to specific people to befriend them — which feeds straight into Aloha Links.",
      },
      howTo: [
        { ko: "수록 아케이드는 「스파이크아웃」(1998년 3D 액션, 이지/노멀 각 1달러), 「겟 배스」(1997년 배스 낚시, 1달러), 「버추어 파이터 3tb」(1997년 3on3 팀 배틀, 이지/노멀 각 1달러) 3종입니다.", en: "The line-up is Spikeout (1998 3D action, $1 on Easy or Normal), Get Bass (1997 bass fishing, $1) and Virtua Fighter 3tb (1997, 3-on-3 team battles, $1 on Easy or Normal)." },
        { ko: "스파이크아웃은 에리어 안의 적을 전멸시키면 게이트가 열리고, 마지막에 스테이지 보스를 쓰러뜨리면 클리어입니다. 게이트 선택으로 루트가 갈립니다.", en: "In Spikeout, wiping out an area's enemies opens the gate, and the run ends when you beat the stage boss; gate choices branch the route." },
        { ko: "겟 배스는 지정된 무게만큼 낚아 올리면 클리어입니다. 통상 3스테이지 + 최종 스테이지 구성입니다.", en: "Get Bass clears when you land the specified total weight, across three stages plus a final one." },
        { ko: "UFO 캐처는 5달러에 3게임이며, 점원에게 말을 걸면 안에 든 경품을 교체할 수 있습니다. 경품은 점포마다 다릅니다.", en: "The UFO catcher is three plays for $5, and talking to the attendant swaps out what's inside; the prize pool differs per branch." },
      ],
      source: [
        { label: "神ゲー攻略 — アーケードゲームの攻略", url: "https://kamigame.jp/ryugagotoku8/page/296329505570601763.html" },
        { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
      ],
    },
    {
      slug: "nightclub-cabaret",
      name: { ko: "나이트클럽·캬바쿠라", en: "Nightclub & cabaret club" },
      category: { ko: "술집·바", en: "Bar / hostess" },
      difficulty: 1,
      location: { ko: "하와이 돌스&데빌스 / 이진초 ROSE BLOSSOM·린린", en: "Dolls & Devils, Hawaii; ROSE BLOSSOM and Rinrin in Ijincho" },
      summary: {
        ko: "캐스트를 지명하고 술과 음식을 주문하는 접대 스폿. 돈은 들지만 동료와의 절 레벨을 단시간에 크게 올릴 수 있어, 액티비티 직업 해금에 필요한 절 수치를 맞출 때 가장 빠른 수단입니다.",
        en: "Pick a cast member and order drinks and food. It costs money, but it raises party bonds faster than anything else — which makes it the quickest way to hit the bond thresholds the Alo-Happy job unlocks demand.",
      },
      howTo: [
        { ko: "비싼 술을 2병 주문하면 특기 발동률이 최대가 됩니다. 하와이는 4,400달러, 일본은 44만 엔입니다.", en: "Ordering two of the expensive bottles maxes the special-move trigger rate — $4,400 in Hawaii, ¥440,000 in Japan." },
        { ko: "캬바쿠라보다 나이트클럽 쪽 캐스트의 능력이 높으니 나이트클럽을 우선하고, 캐스트는 좌측 상단 3명부터 고르는 것이 좋습니다.", en: "Nightclub cast members have better stats than the cabaret ones, so prefer the nightclub, and pick from the top-left three." },
        { ko: "출근 상황은 타이밍에 따라 다릅니다. 하와이에서는 「앨리스」를 고르면 전원의 절 랭크가 크게 오르고, 일본에서는 여성 캐릭터의 절을 올리려면 「아이리」, 남성 캐릭터라면 「린린」이 크게 오릅니다.", en: "Who is working varies by visit. In Hawaii, Alice raises everyone's bond rank sharply; in Japan, Airi is the pick for raising female party members and Rinrin for the men." },
      ],
      source: { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
    },
    {
      slug: "batting-center",
      name: { ko: "배팅 센터", en: "Batting center" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 2,
      location: { ko: "요코하마 이세자키 이진초 / 카무로초 요시다 배팅 센터 (8장 이후)", en: "Isezaki Ijincho; Yoshida Batting Center, Kamurocho — from Chapter 8" },
      summary: {
        ko: "8장에서 기류 쪽 콘텐츠로 열립니다. 챌린지 코스와 홈런 코스가 각각 초급·중급·상급·초인급으로 나뉘고, 모두 A랭크 이상으로 클리어하면 「홈런 경쟁」이 추가됩니다. 획득 포인트는 경품과 교환합니다.",
        en: "Opens with Kiryu's side of the story in Chapter 8. The Challenge and Home Run courses each run beginner, intermediate, advanced and superhuman; clearing them all at A rank or better adds the Home Run Contest. Points trade for prizes.",
      },
      howTo: [
        { ko: "날아오는 코스와 구종은 전부 고정입니다. 미리 커서를 그 자리에 놓고 마크와 중심을 겹친 채 타이밍만 맞춰 휘두르면 홈런이 비교적 쉽게 나옵니다.", en: "Both the pitch type and its location are fixed per throw. Park the cursor there in advance with the mark centred, and the swing becomes pure timing." },
        { ko: "홈런이 안 나오면 경품 교환에서 50pt로 「안심 배트」를 받으세요. 획득 포인트가 줄어드는 대신 배트 판정이 넓어집니다.", en: "If home runs won't come, trade 50 points for the Easy Bat: it earns fewer points but widens the bat's hitbox." },
        { ko: "포인트 벌이는 「홈런 경쟁」이 가장 낫습니다. 챌린지 코스 초급1~초인급3과 같은 코스라 익숙하고, 도중에 실패해도 클리어한 세트 수만큼 포인트를 줍니다.", en: "For farming points, the Home Run Contest is best: it reuses the Challenge courses you already know, and pays out per set cleared even if you fail partway." },
        { ko: "요금은 초급 300엔, 중급 400엔, 상급 500엔, 초인급 1,000엔입니다.", en: "Fees are ¥300 beginner, ¥400 intermediate, ¥500 advanced and ¥1,000 superhuman." },
      ],
      source: [
        { label: "神ゲー攻略 — バッティングセンターの攻略のコツと景品一覧", url: "https://kamigame.jp/ryugagotoku8/page/303430467896508979.html" },
        { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
      ],
    },
    {
      slug: "golf",
      name: { ko: "골프 (타격 연습장)", en: "Golf (driving range)" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 2,
      location: { ko: "이진초 HEAVENS GOLF (택시 승강장 「HEAVENS GOLF 앞」)", en: "HEAVENS GOLF, Ijincho — there's a taxi stop right outside" },
      summary: {
        ko: "니어핀 챌린지와 빙고 챌린지 두 종목(각 1,000엔)입니다. 엔딩 노트의 미련 미션을 달성할 수 있고, 획득 포인트는 경품과 교환합니다.",
        en: "Two modes at ¥1,000 a go — the Near Pin Challenge and the Bingo Challenge. Both complete Bucket List missions, and points trade for prizes.",
      },
      howTo: [
        { ko: "샷 위치를 정할 때 R1으로 부감 모드를 켜면 궤도와 낙하 지점이 훨씬 잘 보입니다. 기본적으로 부감 모드로 치세요.", en: "R1 switches to the overhead view, which makes the ball's arc and landing point far easier to read — use it by default." },
        { ko: "화면 오른쪽 위에 바람의 방향과 세기가 m 단위 화살표로 표시됩니다. 궤도가 바람에 휘니 샷 위치를 그만큼 보정하세요.", en: "Wind direction and strength sit in the top right in metres; the ball curves with it, so offset your aim accordingly." },
        { ko: "포인트는 빙고 챌린지가 압도적으로 효율이 좋습니다. 8BINGO를 달성하면 2,000pt이고, 니어핀과 달리 장애물이 없어 타이밍만 외우면 안정적으로 나오며 9구면 끝나 시간 효율도 좋습니다.", en: "The Bingo Challenge is the efficient one: 8 BINGO pays 2,000 points, there are no obstacles unlike Near Pin, so it's consistent once the timing is learned, and nine shots finishes it." },
        { ko: "경품 최상위는 10,000pt의 「대열광 앵클릿」이고, 그 밖에 레벨·어태커·스피드 어퍼(각 3,200pt), 각종 직업 「극め방」(2,400pt), 비전서 「기」(2,000pt) 등을 교환할 수 있습니다.", en: "The top prize is the Wild Excitement Anklet at 10,000 points, alongside Level/Attack/Speed Uppers at 3,200 each, various job mastery books at 2,400 and the Tech secret manual at 2,000." },
      ],
      source: [
        { label: "神ゲー攻略 — ゴルフのコツと遊べる場所", url: "https://kamigame.jp/ryugagotoku8/page/304411144573989821.html" },
        { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
      ],
    },
    {
      slug: "can-collecting",
      name: { ko: "서바이벌 캔 줍기", en: "Survival can collecting" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 3,
      location: { ko: "이세자키 이진초 사쿠라가와도리 남 — 노숙자 마을의 「칸 씨」", en: "South Sakuragawa Street, Isezaki Ijincho — Kan-san in the homeless village" },
      summary: {
        ko: "7편에서 돌아온 자전거 캔 줍기. 8편에서는 기류의 엔딩 노트 「미련 미션」 항목이기도 해서, 초회 클리어나 캔 수집 수 같은 달성 항목을 채우면 심·기·체와 각 내성이 오릅니다. 초급·중급·상급 3단계입니다.",
        en: "The bicycle can hunt returns from Yakuza 7. In Infinite Wealth it doubles as one of Kiryu's Bucket List missions, so the first clear and the can-count milestones raise his Soul/Tech/Body and their resistances. Three difficulties." },
      howTo: [
        { ko: "라이벌에게 부스트로 몸통박치기를 하면 캔 20개 이상이 쏟아지고, 쓰러진 라이벌은 멀리 리스폰됩니다. 라이벌은 보이는 대로 적극적으로 들이받으세요.", en: "Boost-ramming a rival spills twenty-plus cans and respawns them far away, so hit every rival you can reach." },
        { ko: "가끔 나오는 쓰레기 버리는 소녀는 캔을 대량으로 뿌리며 스테이지를 돌아다닙니다. 뒤를 따라붙기만 해도 대량 회수가 됩니다.", en: "The rubbish-bag girl who periodically appears scatters cans as she runs the stage — just tail her and collect." },
        { ko: "바닥의 쓰레기 더미는 한 번에 캔 30개입니다. 회수 효율이 가장 높으니 우선적으로 주우세요.", en: "A pile of rubbish on the ground is worth thirty cans in one grab — the single best pickup, so prioritise them." },
        { ko: "쓰레기 수거차와 빨간 드럼통 같은 장애물은 피하고, 영양 드링크를 주워 부스트에 쓰세요.", en: "Dodge the obstacles — the refuse truck and the red drums — and pick up the energy drinks to fuel the boost." },
      ],
      source: [
        { label: "神ゲー攻略 — サバイバル缶拾いのコツと遊べる場所", url: "https://kamigame.jp/ryugagotoku8/page/304434311342354319.html" },
        { label: "PINION — プレイスポットの場所・遊びかた一覧", url: "https://pinion.jp/%E3%82%AC%E3%82%A4%E3%83%89/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F8-%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88%E3%81%AE%E5%A0%B4%E6%89%80%E3%81%A8%E9%81%8A%E3%81%B3%E3%81%8B%E3%81%9F/" },
      ],
    },
  ],
};
