import type { MinigamesData } from "./types";

const YT = (id: string) => `https://www.youtube.com/watch?v=${id}`;

// Minigame guides for Yakuza: Like a Dragon. Unlock chapters, rules and prize
// bands come from ゲーム攻略マン's per-play-spot pages, cited on each entry.
export const yakuzaLikeADragonMinigames: MinigamesData = {
  appId: 1235140,
  intro: {
    ko: "Y7의 미니게임은 챕터로 해금이 갈립니다. 캔 줍기는 3장, 드래곤 카트는 4장(서브스토리 No.40)부터 열리고, 비즈니스 매니지먼트와 스지몬 도감은 본편과 병행해야 하는 대형 콘텐츠입니다. 각 항목의 해금 조건과 규칙은 출처 페이지에서 확인한 것입니다.",
    en: "Like a Dragon gates its minigames by chapter: can collecting opens in Chapter 3, Dragon Kart in Chapter 4 via substory No.40, and Business Management and the Sujidex are long-running content you push alongside the story. Unlock conditions and rules below come from the linked pages.",
  },
  minigames: [
    {
      slug: "dragon-kart",
      name: { ko: "드래곤 카트", en: "Dragon Kart" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 4,
      location: { ko: "이진초 — 하마키타 공원 구역 (4장부터)", en: "Hamakita Park, Isezaki Ijincho — from Chapter 4" },
      summary: {
        ko: "거리를 카트로 달리는 레이스입니다. 4장에서 서브스토리 No.40으로 시작되고, 이후 후지사와(포케사 파이터)에게 말을 걸어 그랑프리 코스를 고릅니다. 한 컵에 3코스씩이며 코스는 총 12개입니다.",
        en: "A kart race through the streets. It starts as substory No.40 in Chapter 4, after which Fujisawa — the Pocket Circuit Fighter — runs the Grand Prix. Three courses per cup, twelve in all.",
      },
      howTo: [
        { ko: "코스의 아이템 박스(어태셔 케이스)에서 최대 2종까지 무기를 얻고 ○로 사용합니다. 라이벌이 먼저 가져가는 경우도 있으니 라인을 뺏기지 않는 것도 중요합니다.", en: "Item boxes — the attaché cases — give up to two weapons at a time, fired with circle. Rivals grab them too, so the racing line matters as much as the item." },
        { ko: "링을 모으면 가속 성능이 오르고 카트 내구도 게이지가 회복됩니다. 공격받아 내구도가 0이 되면 크래시로 조작 불능이 되므로, 링을 지나치지 말고 주워 가며 달리는 편이 결과적으로 빠릅니다.", en: "Rings raise acceleration and repair the kart's durability gauge. Losing all durability crashes you into a helpless animation, so collecting rings on the way round is faster than ignoring them." },
        { ko: "모은 링은 경품과 교환합니다. 레이스에서 이기는 것 자체보다 링 수급이 목적인 주회도 유효합니다.", en: "Rings also buy prizes, so a lap run purely for ring collection is a legitimate use of the mode." },
      ],
      videos: [
        { title: { ko: "드래곤 카트 전 라이벌 레이스", en: "Dragon Kart — all rival races" }, url: YT("HtdWqioCrko") },
        { title: { ko: "드래곤 컵 공략", en: "Dragon Cup walkthrough" }, url: YT("XbDKr_NOXsc") },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 ドラゴンカート", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/dragon-kart.html" },
    },
    {
      slug: "can-quest",
      name: { ko: "서바이벌 캔 줍기", en: "Survival Can Quest" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 3,
      location: { ko: "이진초 — 직업안정소 거리 (3장부터)", en: "The job-centre district, Isezaki Ijincho — from Chapter 3" },
      summary: {
        ko: "리어카 자전거로 빈 캔을 모아 출발 지점으로 돌아오는 돈벌이 미니게임입니다. 3장 진행 후 칸 씨에게 말을 걸면 플레이할 수 있고, 모은 pts로 재료·아이템 구입과 환금이 가능합니다.",
        en: "Collect cans on a cart bike and bring them back to the start. It opens in Chapter 3 by talking to Kan-san, and the points buy materials and convert to cash at his shop.",
      },
      howTo: [
        { ko: "캔이 무더기로 쌓인 지점이 있습니다. 맵에서 위치를 보고 무더기를 지나가는 경로를 짜면 효율이 크게 달라집니다.", en: "Some spots hold whole piles of cans — read the map and route through the piles rather than picking singles." },
        { ko: "벽이나 가스통에 부딪히면 모은 캔을 떨어뜨립니다. 파란 쓰레기 수거차와 충돌하면 대량으로 회수당하므로, 난이도마다 다른 수거차의 순회 경로를 맵으로 확인하며 피하세요.", en: "Hitting a wall or a gas cylinder drops cans, and colliding with the blue collection truck takes a large batch — its route differs by difficulty, so watch it on the map." },
        { ko: "영양 드링크를 주우면 △로 부스트를 씁니다. 부스트 중에 라이벌 노숙자에게 부딪히면 반대로 상대의 캔을 빼앗을 수 있습니다.", en: "The energy drink lets you boost with triangle, and ramming a rival while boosting takes their cans instead of losing yours." },
        { ko: "가끔 쓰레기봉투를 진 소녀가 나타나 이동하며 캔을 대량으로 흘립니다. 맵의 ☆ 아이콘이 그 위치이므로 보이면 쫓아가세요.", en: "A girl carrying a rubbish bag occasionally appears and scatters cans as she walks — the star icon on the map is her, and she is worth chasing." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 サバイバル缶拾い", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/survival-picked-up-empty-cans.html" },
    },
    {
      slug: "vintage-film-theater",
      name: { ko: "명화 극장 (졸음 참기)", en: "Vintage Film Theater" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 3,
      location: { ko: "이진초 — 한텐코지 구역 영화관 「우미네코자」", en: "Umineko-za cinema, Hantenkoji, Isezaki Ijincho" },
      summary: {
        ko: "옛 영화 10편을 상영하는 극장입니다. 티켓은 1인 1,000엔이고 동료와 함께 보면 인연도 깊어집니다. 상영 중 나타나는 「수마(睡魔)」를 버튼 입력으로 쫓아내는 반사신경 게임입니다.",
        en: "Ten old films, ¥1,000 a ticket, and watching with a party member deepens bonds. During the film you fend off the sheep-faced Sleep Demons with button inputs.",
      },
      howTo: [
        { ko: "화면 좌우에 수마가 나타나면 표시된 방향키나 버튼을 빠르게 누릅니다. 수마가 없는 쪽 버튼을 누르면 오히려 체력 게이지가 줄어드니 화면을 보고 반응해야 합니다.", en: "Press the button shown as each demon appears on the left or right — pressing a button where there is no demon costs you gauge instead." },
        { ko: "「연타」로 표시된 수마는 5회 이상 눌러야 쓰러집니다. 한 번만 눌러서는 넘어가지 않습니다.", en: "A demon marked for rapid input needs five or more presses; one will not do it." },
        { ko: "닭 머리 캐릭터는 그냥 두면 체력 게이지를 회복해 줍니다. 반사적으로 버튼을 누르면 쫓아내 버리므로 손을 대지 마세요.", en: "The chicken-headed character restores your gauge if you leave it alone — reflexively hitting the button shoos it away." },
        { ko: "「러시」 상태에서는 평소보다 졸음을 많이 날리는 금색 수마가 등장합니다. 이때는 금색을 우선 처리하세요.", en: "During a Rush the gold demons appear and hit much harder — deal with those first." },
      ],
      videos: [
        { title: { ko: "명화 극장 「Life of Sheep」 S랭크", en: "Vintage Film Theater — Life of Sheep (S rank)" }, url: YT("xvdshCazprk") },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 名画座", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/movie-theater.html" },
    },
    {
      slug: "business-management",
      name: { ko: "비즈니스 매니지먼트 (이치반 흥업)", en: "Business Management" },
      category: { ko: "경영 시뮬레이션", en: "Management sim" },
      difficulty: 4,
      location: { ko: "이진초 — 이치반 흥업", en: "Ichiban Holdings, Isezaki Ijincho" },
      summary: {
        ko: "회사를 경영해 주주총회를 이겨 나가는 대형 사이드 모드입니다. 사원 배치와 사업 확장, 주주총회 전투가 축입니다.",
        en: "A full management mode: run the company, expand, and win the shareholder meetings.",
      },
      howTo: [
        { ko: "사원은 능력치뿐 아니라 상성이 있습니다. 매장에 맞는 인재를 배치하는 것이 매출에 직접 반영되므로, 능력치가 높다고 아무 데나 넣으면 손해입니다.", en: "Staff have affinities as well as stats, and matching them to the right store is what actually moves revenue — high stats in the wrong place are wasted." },
        { ko: "주주총회는 별도의 전투입니다. 지지율을 미리 올려 두고 유리한 주주를 배치해야 하므로, 경영 페이즈에서 준비를 끝내 놓고 들어가야 합니다.", en: "The shareholder meeting is its own battle: you go in with approval already raised and the right shareholders placed, so the prep happens in the management phase." },
        { ko: "랭크가 오를수록 요구 매출이 급격히 커집니다. 사업 확장은 자금 여유를 두고 단계적으로 하세요.", en: "Required revenue climbs steeply with each rank, so expand in steps with cash in reserve." },
      ],
      videos: [
        { title: { ko: "비즈니스 매니지먼트 랭킹 1위 공략", en: "Business Management rank 1 guide" }, url: YT("FjyNRDHqsOA") },
        { title: { ko: "이치반 과자점 종합 가이드", en: "Ultimate Ichiban Confections guide" }, url: YT("FtGm2-YjliU") },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 事業を始める", url: "https://dswiipspwikips3.jp/yakuza7/company-management/start-business.html" },
    },
    {
      slug: "sujimon",
      name: { ko: "스지몬 (스지 도감)", en: "Sujimon (the Sujidex)" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 3,
      location: { ko: "이진초·소텐보리·카무로초 전역", en: "All three cities" },
      summary: {
        ko: "거리의 적을 스지몬으로 등록해 도감을 채우는 수집 요소입니다. 도감을 채우면 스지 배틀과 보상이 열립니다.",
        en: "Register street enemies into the Sujidex. Filling it opens Suji battles and rewards.",
      },
      howTo: [
        { ko: "등록은 그 적과 싸워 이기면 자동으로 됩니다. 특정 조건에서만 나오는 개체가 있으므로 시간대·구역·챕터를 바꿔 가며 돌아야 합니다.", en: "Beating an enemy registers it automatically, but some only spawn under particular conditions, so sweep by time of day, district and chapter." },
        { ko: "레어 개체는 챕터가 지나면 나오지 않는 경우가 있습니다. 도감을 노린다면 각 챕터에서 그 지역의 적을 한 번씩 훑고 넘어가세요.", en: "Some rare entries stop appearing once a chapter passes, so clear each district's roster before moving the story on." },
        { ko: "스지몬 정보는 도감에서 약점과 출현 지역을 확인할 수 있습니다. 남은 항목을 찾을 때는 도감의 미등록 슬롯을 먼저 보세요.", en: "The dex itself lists weaknesses and spawn areas — check the empty slots first when hunting the last few." },
      ],
      videos: [
        { title: { ko: "전 스지몬 위치 가이드", en: "All Sujimon locations" }, url: YT("HbH7z66aldM") },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 スジモン図鑑", url: "https://dswiipspwikips3.jp/yakuza7/cheats-data/sujimon.html" },
    },
    {
      slug: "niginigi",
      name: { ko: "주물주물 (니기니기)", en: "Can-Squeeze (Niginigi)" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 2,
      location: { ko: "이진초 — 유흥가", en: "The nightlife district, Isezaki Ijincho" },
      summary: {
        ko: "버튼 입력으로 진행하는 짧은 성인 취향 미니게임입니다. 인연 이벤트와 연결되어 있습니다.",
        en: "A short adult-humour minigame driven by button inputs, tied into the bond events.",
      },
      howTo: [
        { ko: "화면에 표시되는 버튼과 리듬에 맞춰 입력하는 방식입니다. 정확도보다 지시대로 끝까지 따라가는 것이 조건입니다.", en: "Follow the prompts in rhythm — the requirement is finishing as instructed rather than any accuracy target." },
        { ko: "플레이 자체가 컴플리트 항목이므로 한 번 돌리면 됩니다. 반복 보상은 없습니다.", en: "The completion row counts the play itself, so one run is enough — there is no repeat reward." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 にぎにぎ", url: "https://dswiipspwikips3.jp/yakuza7/cheats-data/niginig-daughter.html" },
    },
    {
      slug: "golf",
      name: { ko: "골프 센터", en: "Golf Center" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 3,
      location: { ko: "이진초 — HEAVEN'S GOLF / 소텐보리 — 요코보리 골프 센터 (1플레이 1,000엔)", en: "HEAVEN'S GOLF in Ijincho and Yokobori Golf Center in Sotenbori — ¥1,000 a round" },
      summary: {
        ko: "니어핀 챌린지와 빙고 챌린지가 있습니다. 두 시설의 코스와 경품 교환 내용은 같으므로 어느 쪽에서 해도 상관없습니다.",
        en: "Nearest-the-Pin and Bingo. Both venues run the same courses and prize list, so either works.",
      },
      howTo: [
        { ko: "니어핀 경품은 코스와 포인트 구간으로 갈립니다. 초급 100~199pt는 이에몬 특차, 중급 같은 구간은 터프니스 라이트, 상급은 마쿠노우치 도시락처럼 코스가 올라갈수록 보상이 좋아집니다.", en: "Nearest-the-Pin prizes are banded by course and points: 100-199 gives Iyemon Tokucha on Beginner, Toughness Light on Intermediate and a Makunouchi Bento on Advanced." },
        { ko: "빙고 챌린지는 9장의 패널을 쳐서 가로세로를 맞추는 방식입니다. 니어핀처럼 컵을 노리는 것이 아니라 패널 위치에 맞춰 파워를 조절하는 종목입니다.", en: "Bingo is a 3x3 panel grid rather than a cup — you are matching power to a panel position." },
        { ko: "바람의 방향과 세기가 낙하 지점을 크게 바꿉니다. 화면의 바람 표시를 먼저 보고 파워와 방향을 정하세요.", en: "Wind direction and strength move the landing point a long way, so read the indicator before setting power and aim." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 ゴルフセンター", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/golf-center.html" },
    },
    {
      slug: "pachislot",
      name: { ko: "파치슬로", en: "Pachislot" },
      category: { ko: "도박·보드", en: "Gambling / board" },
      difficulty: 3,
      location: { ko: "이진초 — PIA / 카무로초 — 에스파스 니타쿠·마루한", en: "PIA in Ijincho, Espace Nittaku and Maruhan in Kamurocho" },
      summary: {
        ko: "실제 기종 4대를 그대로 이식했습니다. 파치슬로 창천의 권 붕우, 어나더 갓 하데스, 미리언 갓, 파치슬로 맹수왕이며 뒤 두 대는 무료 DLC로 배포됩니다.",
        en: "Four real machines ported whole: Sōten no Ken Hōyū, Another God Hades, Million God and Mōjūō — the last two arriving as free DLC.",
      },
      howTo: [
        { ko: "이 작품의 파치슬로 대는 가게마다 설정이 다르고, 가게를 나가도 설정이 초기화되지 않습니다. 시간대가 바뀌는 특정 타이밍에만 설정이 바뀌므로 좋은 대를 찾으면 계속 앉아 있어도 됩니다.", en: "Each parlour sets its machines differently, and unlike earlier games the setting does not reset when you leave — it only changes at certain times of day, so a good machine stays good." },
        { ko: "아이템을 써서 대의 설정을 직접 바꿀 수도 있습니다. 메달을 대량으로 벌어야 한다면 설정을 올려 두고 돌리는 편이 확실합니다.", en: "Items can raise a machine's setting outright, which is the reliable way to farm medals." },
        { ko: "메달은 경품과 교환합니다. 비싼 경품일수록 요구 매수가 크므로, 목표 경품의 매수를 먼저 확인하고 필요한 만큼만 돌리세요.", en: "Medals buy prizes, and the expensive ones want a lot — check the price before deciding how long to sit there." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 パチスロ", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/pachislot.html" },
    },
    {
      slug: "batting-center",
      name: { ko: "배팅 센터", en: "Batting Center" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 3,
      location: { ko: "이진초·카무로초 — 배팅 센터", en: "Batting centers in Ijincho and Kamurocho" },
      summary: {
        ko: "패널을 맞혀 점수를 내는 방식이며 코스마다 구질이 고정입니다.",
        en: "Panel-hitting for points, with a fixed pitch script per course.",
      },
      howTo: [
        { ko: "커서를 코스에 맞춘 뒤, 투구와 함께 줄어드는 커서가 공 크기와 겹치는 순간에 휘두르는 것이 정타입니다.", en: "Line the cursor up, then swing as the shrinking cursor matches the ball's size." },
        { ko: "구질별 구속대가 다릅니다. 느린 커브에서 타이밍을 당기지 않는 것이 점수를 지키는 핵심입니다.", en: "Speeds differ by pitch type, and not rushing the slow curves is what protects the score." },
      ],
      source: [
        { label: "ゲーム攻略マン — 龍が如く7 バッティングセンター", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/batting-center.html" },
        { label: "kamigame.jp — 龍が如く7 バッティングセンター", url: "https://kamigame.jp/龍が如く7/プレイスポット/バッティングセンター.html" },
      ],
      courses: [
        {
          title: { ko: "챌린지 코스 — 초인급 1", en: "Challenge Course — Superhuman 1" },
          note: { ko: "가장 어려운 티어 — 초급·중급·상급 순서표는 추가 예정", en: "Hardest tier — Beginner/Intermediate/Advanced tables are pending" },
          pitches: [
            { pos: 1, type: "One-seam", speed: "140" }, { pos: 6, type: "Cutball", speed: "130" }, { pos: 2, type: "Changeup", speed: "90" }, { pos: 3, type: "Sinker", speed: "120" }, { pos: 9, type: "Two-seam", speed: "140" },
            { pos: 1, type: "Curve", speed: "110" }, { pos: 2, type: "Split", speed: "145" }, { pos: 7, type: "Straight", speed: "155" }, { pos: 9, type: "Slider", speed: "125" }, { pos: 6, type: "Shoot", speed: "125" },
          ],
        },
        {
          title: { ko: "챌린지 코스 — 초인급 2", en: "Challenge Course — Superhuman 2" },
          pitches: [
            { pos: 3, type: "Curve", speed: "110" }, { pos: 2, type: "One-seam", speed: "140" }, { pos: 6, type: "Slider", speed: "125" }, { pos: 1, type: "Shoot", speed: "125" }, { pos: 7, type: "Straight", speed: "155" },
            { pos: 1, type: "Sinker", speed: "120" }, { pos: 9, type: "Cutball", speed: "140" }, { pos: 2, type: "Two-seam", speed: "140" }, { pos: 3, type: "Changeup", speed: "90" }, { pos: 1, type: "Fork", speed: "125" },
          ],
        },
        {
          title: { ko: "챌린지 코스 — 초인급 3", en: "Challenge Course — Superhuman 3" },
          pitches: [
            { pos: 2, type: "Power slider", speed: "145" }, { pos: 8, type: "Straight", speed: "155" }, { pos: 6, type: "Cutball", speed: "130" }, { pos: 1, type: "Sinker", speed: "110" }, { pos: 3, type: "Curve", speed: "110" },
            { pos: 2, type: "Changeup", speed: "90" }, { pos: 4, type: "Two-seam", speed: "140" }, { pos: 9, type: "Shoot", speed: "125" }, { pos: 1, type: "One-seam", speed: "140" }, { pos: 3, type: "Power slider", speed: "145" },
          ],
        },
      ],
    },
    {
      slug: "darts",
      name: { ko: "다트", en: "Darts" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "이진초·카무로초 — 바", en: "Bars in Ijincho and Kamurocho" },
      summary: {
        ko: "01·크리켓·카운트업 세 종목입니다.",
        en: "The usual three modes: 01, Cricket and Count-Up.",
      },
      howTo: [
        { ko: "싱글은 그 구역 점수, 더블 2배, 트리플 3배이고 BULL은 50점입니다. 01에서는 트리플 20보다 BULL이 안정적입니다.", en: "Singles score the sector, doubles double, triples treble, bull is 50 — in 01 the bull is steadier than treble 20." },
        { ko: "크리켓은 한 구역을 세 번 맞혀 점유합니다. 더블은 2회, 트리플은 3회로 계산되므로 트리플 한 방이면 즉시 점유됩니다.", en: "Cricket claims a number on three hits, with doubles worth two and triples three — one triple claims it outright." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 ダーツ", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/darts.html" },
    },
    {
      slug: "karaoke",
      name: { ko: "가라오케", en: "Karaoke" },
      category: { ko: "음악·리듬", en: "Music / rhythm" },
      difficulty: 2,
      location: { ko: "이진초·카무로초 — 가라오케", en: "Karaoke in Ijincho and Kamurocho" },
      summary: {
        ko: "버튼 타이밍 리듬 게임입니다. 동료와 함께 부르면 인연도가 오릅니다.",
        en: "A button-timing rhythm game, and singing with a party member raises bonds.",
      },
      howTo: [
        { ko: "노트가 라인에 닿는 순간이 아니라 커서에 겹치는 순간이 판정 기준입니다. 「Hold」는 끝까지 누르고 「Rapid」는 연타입니다.", en: "Judge on the note overlapping the cursor, not reaching the lane. Hold means hold to the end; Rapid means mash." },
        { ko: "인연도를 올릴 목적이라면 점수보다 동행이 중요합니다. 아직 인연이 낮은 동료를 데려가세요.", en: "If bonds are the point, who you bring matters more than the score — take whoever is furthest behind." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 カラオケ", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/karaoke.html" },
    },
    {
      slug: "mahjong",
      name: { ko: "마작", en: "Mahjong" },
      category: { ko: "도박·보드", en: "Gambling / board" },
      difficulty: 4,
      location: { ko: "이진초·카무로초 — 마작장", en: "Mahjong parlours in Ijincho and Kamurocho" },
      summary: {
        ko: "컴플리트 항목은 화료와 누적 점수입니다. 규칙을 모르면 이 작품에서도 가장 오래 걸립니다.",
        en: "Wins and a points total, and still the longest entry if the rules are new to you.",
      },
      howTo: [
        { ko: "점수를 크게 만들기보다 싸고 빠르게 화료하는 편이 조건을 빨리 채웁니다. 리치·탕야오 수준으로 계속 돌리세요.", en: "Cheap fast hands fill the rows faster than big ones — stick to riichi and tanyao." },
        { ko: "누적 점수는 고레이트 탁에서 도는 편이 빠르고, 화료 횟수 조건과 동시에 진행됩니다.", en: "The points row goes faster at a high-rate table and advances alongside the win-count row." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 麻雀", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/majan.html" },
    },
    {
      slug: "shogi",
      name: { ko: "쇼기 (장기)", en: "Shogi" },
      category: { ko: "도박·보드", en: "Gambling / board" },
      difficulty: 3,
      location: { ko: "이진초 — 직업안정소 거리(쇼쿠안가이) 북동쪽, 쓰루카메 다리 앞 / 소텐보리 — 쇼후쿠초 남쪽", en: "North-east Shokuan-gai by the Tsurukame Bridge, Isezaki Ijincho; south Shofukucho, Sotenbori" },
      summary: {
        ko: "길가의 노숙자에게 말을 걸어 두는 노상 장기입니다. 순위전·시련 돌파·쓰메쇼기 세 모드가 있고, 이기면 받는 장기 포인트로 경품을 교환합니다. 컴플리트 항목은 「10승(쓰메쇼기 포함)」과 「쓰메쇼기 10문제 클리어」 두 줄입니다.",
        en: "Street shogi with the homeless regulars. Ranked matches, Challenge (trial) matches and Puzzle Shogi all pay Shogi Points for prizes. The completion rows are ten wins (puzzles count) and clearing all ten puzzles.",
      },
      howTo: [
        { ko: "쓰메쇼기가 가장 빠른 길입니다. 문제 하나를 풀 때마다 1승으로 세므로 10문제를 다 풀면 두 컴플리트 항목이 한꺼번에 끝납니다. 1~5번은 1수, 6~10번은 3수 외통이고 정답은 아래에 있습니다.", en: "Puzzle Shogi is the shortcut: each solved puzzle counts as a win, so clearing all ten finishes both completion rows at once. Puzzles 1–5 are mate in one, 6–10 mate in three; answers are below." },
        { ko: "쓰메쇼기 포인트는 첫 클리어 때만 들어옵니다. 其の一 500점부터 한 문제마다 500점씩 올라 其の十은 5,000점이고, 무르기를 쓰지 않으면 +150점이 붙습니다. 다시 풀면 무르기 보너스만 받습니다.", en: "Puzzle points pay on the first clear only: 500 for No. 1 rising by 500 each to 5,000 for No. 10, plus 150 if you never take a move back. Repeat clears pay only that take-back bonus." },
        { ko: "□가 무르기(한 수 전으로), L1이 슈퍼 무르기(되돌릴 수를 직접 지정)입니다. 어느 쪽이든 쓰면 이겼을 때 받는 포인트가 줄어듭니다.", en: "Square takes back one move and L1 is the super take-back to a move of your choice; either one cuts the points a win pays." },
        { ko: "시련 돌파는 불리한 배치(其の一은 왼쪽 향차가 빠진 채)에서 시작하는 실전이라 혼자 이기기 어렵습니다. 공략 페이지도 bonanza 같은 무료 장기 엔진에 국면을 넣어 수를 받는 방법을 권합니다. 其の一 클리어는 1,000점입니다.", en: "Challenge matches are full games from a handicapped start (No. 1 drops your left lance) and are hard to win unaided; the guide recommends feeding the position into a free engine such as Bonanza. No. 1 pays 1,000 points." },
      ],
      videos: [
        { title: { ko: "쓰메쇼기 전 10문제 공략", en: "All ten Puzzle Shogi solutions" }, url: YT("zDAwTJsoqSE") },
      ],
      source: [
        { label: "ゲーム攻略マン — 龍が如く7 将棋", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/syogi.html" },
        { label: "神ゲー攻略 — 龍が如く7 将棋の攻略と詰将棋の答え", url: "https://kamigame.jp/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F7/%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9%E3%83%9D%E3%83%83%E3%83%88/%E5%B0%86%E6%A3%8B.html" },
        { label: "ゲームウィズ — 龍が如く7 将棋(詰将棋)の答え", url: "https://gamewith.jp/ryu-ga-gotoku7/article/show/183972" },
        { label: "ゴリラ攻略wiki — 龍が如く7 将棋攻略と詰将棋の答え", url: "https://ryugagotoku7.gorillawiki.jp/entry/shougi" },
        { label: "電ファミ攻略wiki — 龍が如く7 将棋 (Wayback 2023-10 사본, 원 사이트 폐쇄)", url: "https://web.archive.org/web/20231002065641/https://wiki.denfaminicogamer.jp/ryugagotoku7/%E5%B0%86%E6%A3%8B" },
        { label: "GameFAQs (CyricZ) — Yakuza: Like a Dragon Shogi", url: "https://gamefaqs.gamespot.com/ps4/272324-yakuza-like-a-dragon/faqs/78735/shogi" },
        { label: "たっくんブラザーズ — 龍が如く7 将棋 試練踏破 (YouTube)", url: "https://www.youtube.com/@TakuBro" },
      ],
      puzzleSets: [
        {
          title: { ko: "쓰메쇼기 정답 — 10문제", en: "Puzzle Shogi answers — all 10" },
          note: { ko: "1~5번은 1수, 6~10번은 3수 외통입니다. 공격 수는 神ゲー攻略·ゲームウィズ·アルテマ(고릴라위키)·電ファミ·GameFAQs가 8번을 빼고 모두 같습니다. 상대 응수(同桂·同玉)는 ゲームウィズ, 打 표기와 그림은 神ゲー攻略 캡처입니다. 7번 3수째는 神ゲー攻略 본문에 숫자가 빠져 있어 ゲームウィズ의 2一角成을 따랐습니다.", en: "Problems 1–5 are mate in one, 6–10 mate in three. Kamigame, GameWith, Altema (via Gorillawiki), Denfaminico and GameFAQs agree on every attacking move except No. 8. Defender replies (同桂/同玉) are GameWith's; the 打 notation and the diagrams are Kamigame's captures. No. 7's third move is missing its file number in Kamigame's text, so it follows GameWith's 2一角成." },
          puzzles: [
            { title: { ko: "1번 (1수 외통)", en: "No. 1 (mate in 1)" }, moves: ["▲2四飛"], image: "https://lh3.googleusercontent.com/nWL7rIHCqCjIvcRT3Dudm9zfwJWZFLfG653FVeFIpkmOjXzd6yzgYXzIcmVkFpJAVogOsMiORx7lBkQhQz4D49U_7hAUraD33sYA_1TWEVIq=s0" },
            { title: { ko: "2번 (1수 외통)", en: "No. 2 (mate in 1)" }, moves: ["▲2一角成"], image: "https://lh3.googleusercontent.com/tSd_xu8uJCyfxoQIt4xkBpZEqjDaCE92cQeKxv3x26Sp1EsrV2_ob3-p-Lncm4dgyvNazFcWYoHCdSaeksQDbvOnCfcIPdyPYJRWeVL1jEpeRQ=s0" },
            { title: { ko: "3번 (1수 외통)", en: "No. 3 (mate in 1)" }, moves: ["▲3二飛成"], image: "https://lh3.googleusercontent.com/ypzVppsHGHf3NkHHL3eGbJgWywNhUQ6a0vE-YEVmg5B6AIFRsygwfSnCTNJ1Etj9weahDXTHxGK23JqNVvlD4j4BcA7QbBjLkQM0Ij8NysR5iQ=s0" },
            { title: { ko: "4번 (1수 외통)", en: "No. 4 (mate in 1)" }, moves: ["▲3一金"], image: "https://lh3.googleusercontent.com/AZs-D1u7WWyytT01da1a9pKii8MmmTBSdLs3TI74FDpcgp5an52xxffKQK23RxtJcpOT5t8eG_EA29-MtT2Dwbxmp-TPhK_BaT_IGfDCOI-R=s0" },
            { title: { ko: "5번 (1수 외통)", en: "No. 5 (mate in 1)" }, moves: ["▲2一馬"], image: "https://lh3.googleusercontent.com/F5x0Rg0dmIoB6uEfP568i9mAH1z_phGFLYoNXizb7IENsdbOnEa2Fc5404Ur5x4zpz6aWDi7AYdF3wpuapb1l40-6N6UtWELnpjthsbn2Nck=s0" },
            { title: { ko: "6번 (3수 외통)", en: "No. 6 (mate in 3)" }, moves: ["▲1三銀打", "△同桂", "▲2一銀打"], image: "https://lh3.googleusercontent.com/QHesJ2mVZUp-8M4JYPGcWtt3gs5nd4g3TfHkEdZQvjTt6NByqpRNebOtSvuCTC_usYAR6OKgCyfaHb3PKM2lNde0eQh06CnJlxLcY2AOFPyJkQ=s0", images: ["https://lh3.googleusercontent.com/x5hRNIabOFheJjeQ6Z2s5l8GHOU9oRin57GyohJCUtJ7M8II9yk91D9ZDAiDMihFS8-RmxlyEXjPtEnvMxpdBd8nlIXO2N8hxL9F0b92X_uh=s0"] },
            { title: { ko: "7번 (3수 외통)", en: "No. 7 (mate in 3)" }, moves: ["▲1一飛成", "△同玉", "▲2一角成"], image: "https://lh3.googleusercontent.com/xQeEjnQRJS4wH_1aouZKhWaVB3m_DO0CD7QtY1TwKGpcKiqxqTZogZOAggxpDE4OcbvAsGOlbGaMoQja-iqSUCdgcGq7G1ROllXkFdlZQ6Rw=s0", images: ["https://lh3.googleusercontent.com/aYQUJtbX71vLUSBlXZo22MBSif86iV9MBhyEfefvN3Vxkb2Vh0kwyIcI3FdWE-rhs_DFqNsBH0zpRW2dU0rqIDHWigF8OkRgP_4fDA68PLNc=s0"] },
            { title: { ko: "8번 (3수 외통)", en: "No. 8 (mate in 3)" }, image: "https://lh3.googleusercontent.com/Uw5gztXfck_qCeFURZrUqFB6vLz9VdYYWY6JCVTDBwZfAf7wEgEnTzYrqU_oEjuigI-LWRM_YJpCFqX8ka8roXB-w_X3tCGxMnz6DrwzFhsu=s0", images: ["https://img.altema.jp/ryugagotoku7/uploads/2020/02/2020y02m06d_2002518239.jpg"], note: { ko: "출처끼리 첫 수가 갈립니다. 神ゲー攻略·電ファミ·GameFAQs는 ▲3四角(각을 왼쪽 위로 1칸) → △同玉 → ▲2三銀打, ゲームウィズ·アルテマ(고릴라위키 게재)는 ▲1四角(오른쪽 위로 1칸) → △同玉 → ▲2三銀입니다. 첫 그림은 神ゲー攻略 캡처(3四), 둘째 그림은 アルテマ 캡처(1四)입니다. 3수째 ▲2三銀은 모든 출처가 같습니다.", en: "Sources disagree on the first move. Kamigame, Denfaminico and GameFAQs give ▲3四角 (bishop one square up-left) → △同玉 → ▲2三銀打; GameWith and Altema (via Gorillawiki) give ▲1四角 (up-right) → △同玉 → ▲2三銀. The first diagram is Kamigame's capture (3四), the second Altema's (1四). Every source agrees on the closing ▲2三銀." } },
            { title: { ko: "9번 (3수 외통)", en: "No. 9 (mate in 3)" }, moves: ["▲1三飛打", "△同玉", "▲2三馬"], image: "https://lh3.googleusercontent.com/U0j4uu5OwviWcDAUarsdR6hIdLGB8Na21a2dCJfafjcF_YLUGVgXdL7V7CMyLi-pH3cwdIScBgRW3FnaPxY0YkWvdixbgQGTgmrFO7-W7dsx=s0", images: ["https://lh3.googleusercontent.com/wgO2qWkxxPfFp9SeaGTqe-Ok4tiJh4_ycdpLbQt-clTtBdr21CGaQICpjQ0M69_iG3y3F9jl2KrQZc7h-EL7I3e717z6ImIy66cedwxsomWq=s0"] },
            { title: { ko: "10번 (3수 외통)", en: "No. 10 (mate in 3)" }, moves: ["▲3一飛成", "△同玉", "▲4二金打"], image: "https://lh3.googleusercontent.com/mx0l6QPPwshkAhHLWqwzpoVU4GzXw_qCNScxkIdXWePcM_cJ-ZYsmZ4cVfo0tR0EQLoZFDbDiYDSyyKCUNM6LdblNt5VjZVyWtcCFQWieLI=s0", images: ["https://lh3.googleusercontent.com/0v8Y9CVr8IfMhoEV1yXZsD5ZcnXIug9LpaKyhRus--Dkp3h2nXbnCJuh9hyE755AARHUF8tohkqJxZZhVF57n9nJRLJHgtekbwGS6-nsbfPb=s0"] },
          ],
        },
        {
          title: { ko: "시련 돌파 — 其の一~최종 (11판)", en: "Challenge matches — No. 1 to Final (11)" },
          note: { ko: "시련 돌파는 CPU와 두는 실전이라 수순표나 정답 그림이 없고 영상만 있습니다(たっくんブラザーズ). 대체로 영상대로 두면 CPU도 같은 수로 받지만, 다르게 두면 무르기로 몇 번 되돌려 다시 시도하세요.", en: "Challenge matches are full games against the CPU, so no move list or answer diagrams exist — only videos (TakuBro). The CPU usually answers as in the video; if it deviates, take back and retry a few times." },
          puzzles: [
            { title: { ko: "1번", en: "No. 1" }, video: YT("anR4b419Lsg") },
            { title: { ko: "2번", en: "No. 2" }, video: YT("dVC9NTw3E9M") },
            { title: { ko: "3번", en: "No. 3" }, video: YT("nh4TXMsQFiY") },
            { title: { ko: "4번", en: "No. 4" }, video: YT("52HQms6n5OY") },
            { title: { ko: "5번", en: "No. 5" }, video: YT("YuLVn9uK3DY") },
            { title: { ko: "6번", en: "No. 6" }, video: YT("Zm1aG7GoTyc") },
            { title: { ko: "7번", en: "No. 7" }, video: YT("3rK-wrtmfpE") },
            { title: { ko: "8번", en: "No. 8" }, video: YT("hZ_He_l8zoA") },
            { title: { ko: "9번", en: "No. 9" }, video: YT("Tup-ez0gwHo") },
            { title: { ko: "10번", en: "No. 10" }, video: YT("k7T3pJkQwmM") },
            { title: { ko: "최종 시련", en: "Final trial" }, video: YT("3LHIWvkt9I4") },
          ],
        },
      ],
    },
    {
      slug: "koi-koi",
      name: { ko: "도박장 (코이코이·오이초카부)", en: "Gambling Hall (koi-koi, oicho-kabu)" },
      category: { ko: "도박·보드", en: "Gambling / board" },
      difficulty: 2,
      location: { ko: "이진초·카무로초 — 도박장", en: "Gambling dens in Ijincho and Kamurocho" },
      summary: {
        ko: "코이코이와 오이초카부가 있으며 누적 획득량이 조건입니다.",
        en: "Koi-koi and oicho-kabu, counted by cumulative winnings.",
      },
      howTo: [
        { ko: "코이코이는 역을 알면 「고이코이」 선언 타이밍이 전부입니다. 작은 역이라도 확정 점수를 챙기는 편이 누적에 유리합니다.", en: "In koi-koi the whole game is when to call — banking a small hand beats gambling it away when totals count." },
        { ko: "누적이 조건이므로 잃어도 진행이 되돌아가지 않습니다. 중간 판돈으로 꾸준히 도는 편이 결과적으로 빠릅니다.", en: "Losses do not undo a cumulative row, so steady mid-size bets finish faster than swinging for it." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 こいこい", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/koikoi.html" },
    },
    {
      slug: "casino",
      name: { ko: "카지노 (블랙잭·포커 등)", en: "Casino (blackjack, poker and more)" },
      category: { ko: "도박·보드", en: "Gambling / board" },
      difficulty: 2,
      location: { ko: "이진초·카무로초 — 카지노", en: "Casinos in Ijincho and Kamurocho" },
      summary: {
        ko: "칩을 벌어 경품과 교환합니다. 블랙잭이 회전과 기대값 양쪽에서 가장 안정적입니다.",
        en: "Earn chips and trade them for prizes; blackjack is the steadiest for both pace and expectation.",
      },
      howTo: [
        { ko: "블랙잭은 연승으로 베팅 상한이 오르고 한 번 지면 초기화됩니다. 상한을 먼저 올린 뒤 큰 판을 거는 순서가 효율적입니다.", en: "Blackjack raises its cap on a streak and resets it on a loss, so climb first and bet big afterwards." },
        { ko: "칩을 다 써도 조건이 「획득량」이면 진행은 남습니다. 경품 교환을 미룰 필요는 없습니다.", en: "Where a row counts winnings rather than balance, spending the chips does not undo it — no need to hoard." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く7 ブラックジャック", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/blackjack.html" },
    },
    {
      slug: "club-sega-arcade",
      name: { ko: "클럽 세가 (판타지 존·아웃런·스페이스 해리어·슈퍼 행온·UFO 캐처)", en: "Club SEGA (Fantasy Zone, Out Run, Space Harrier, Super Hang-On, UFO Catcher)" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 3,
      location: { ko: "이진초·카무로초 — 클럽 세가", en: "Club SEGA in Ijincho and Kamurocho" },
      summary: {
        ko: "아케이드 기판 4종과 UFO 캐처가 있습니다. 기판은 원작 난도 그대로입니다.",
        en: "Four arcade boards and the UFO Catcher, the boards at their original difficulty.",
      },
      howTo: [
        { ko: "판타지 존은 스테이지를 빠르게 깨는 것보다 적을 계속 잡아 돈을 모으고 강화 아이템을 사서 오래 살아남는 쪽이 점수가 큽니다.", en: "Fantasy Zone scores better by farming enemies for money and buying upgrades to survive longer than by rushing stages." },
        { ko: "아웃런과 슈퍼 행온은 타임 보너스가 점수의 대부분입니다. 코스를 외워 감속을 줄이는 것이 그대로 점수가 됩니다.", en: "Out Run and Super Hang-On pay mostly in time bonus, so learning the course to avoid braking is the score." },
        { ko: "UFO 캐처는 서로 다른 경품을 모으는 방식이라 같은 인형을 반복해 뽑아도 진행되지 않습니다.", en: "The UFO Catcher counts distinct prizes, so duplicates do nothing." },
      ],
      source: [
        { label: "ゲーム攻略マン — 龍が如く7 ファンタジーゾーン", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/fantasy-zone.html" },
        { label: "ゲーム攻略マン — 龍が如く7 UFOキャッチャー", url: "https://dswiipspwikips3.jp/yakuza7/play-spots/ufo-catcher.html" },
      ],
    },
    {
      slug: "vocational-school",
      name: { ko: "대해원 자격학교 (자격 검정)", en: "Ounabara Vocational School" },
      category: { ko: "퀴즈", en: "Quiz" },
      difficulty: 2,
      location: { ko: "이진초 — 진나이역 오른쪽 위, 다이코쿠텐 거리 (4장부터)", en: "Daikokuten Street, up and right of Jinnai Station, Isezaki Ijincho — from Chapter 4" },
      summary: {
        ko: "수험료를 내고 4지선다 퀴즈를 푸는 자격학교입니다. 처음 방문하면 서브스토리 No.10 「대해원에 뛰어들어라!」로 스포츠 2급을 보게 되고, 합격한 자격마다 대응하는 인간력이 첫 합격 때 크게 오릅니다. 20개 자격을 모두 따면 최종 「대해원 검정」이 열립니다.",
        en: "Pay a fee and answer multiple-choice questions. Your first visit triggers substory No.10 with the Sports Tier 2 exam, and each certificate raises its personality stats on the first pass. Passing all twenty opens the final Ounabara Proficiency exam.",
      },
      howTo: [
        { ko: "검정마다 약 10문제 중 5문제가 무작위로 나오고 5문제 중 3문제를 맞히면 합격입니다. 떨어져도 마지막에 틀린 문제의 정답을 보여 주니 외워서 다시 보세요. 정답은 아래 시험별 목록에 있습니다.", en: "Each exam draws five random questions from a pool of about ten, and three right is a pass. A failed attempt still shows the correct answers at the end, so you can learn them and retry. All answers are listed below by exam." },
        { ko: "최종 「대해원 검정」(수험료 10만 엔)은 앞의 모든 검정에서 5문제가 나오고 5문제 전부를 맞혀야 합격이며, 정열·멘탈·세련이 각 +100 오릅니다.", en: "The final Ounabara Proficiency (¥100,000) draws five questions from every earlier exam and needs all five right; it is worth +100 Passion, Confidence and Style." },
        { ko: "정문으로 들어가 접수처를 바라보고 오른쪽에 있는 이가리에게서 보조 기술을 살 수 있습니다. 「초집중」 10만 엔 = 제한 시간이 1분으로 늘어남, 「신에게 비는 연필」 50만 엔 = 4지선다가 2지선다로 줄어듦. 각각 시험 한 번에 1회씩만 쓸 수 있습니다.", en: "Igari, to the right of the reception desk as you walk in, sells two aids: Hyperfocus (¥100,000, the time limit becomes one minute) and the Pencil of Providence (¥500,000, cuts a question down to two choices). Each is usable once per exam." },
        { ko: "자격 10개를 따면 서브스토리 No.11 「쓰레기 사회의 패배자」(보상 「平常心の手ぬぐい」 = 경험치 증가)가, 전 자격 합격 후 접수원 미야코시(宮腰愛恵)와 3번 대화하면 서브스토리 No.49 「건네고 싶은 것」이 발생합니다. No.49를 깨면 회사 경영에 서비스 특화 인재로 미야코시를 고용할 수 있습니다.", en: "Ten certificates trigger substory No.11 (reward: 平常心の手ぬぐい, which raises EXP gain); passing everything and talking to receptionist Miyakoshi (宮腰愛恵) three times triggers substory No.49, after which she can be hired in Business Management as a service specialist." },
        { ko: "4장부터 갈 수 있지만 진나이역 주변 적이 강하니, 레벨이 오른 7장(지하 던전 이후) 무렵에 가는 편이 편합니다.", en: "It opens in Chapter 4, but the enemies around Jinnai Station are tough that early — Chapter 7, after the underground dungeon, is a more comfortable time." },
      ],
      source: [
        { label: "神ゲー攻略 — 龍が如く7 資格学校の答えと上昇する人間力一覧", url: "https://kamigame.jp/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F7/%E6%94%BB%E7%95%A5%E3%82%AC%E3%82%A4%E3%83%89/%E8%B3%87%E6%A0%BC%E5%AD%A6%E6%A0%A1.html" },
        { label: "ゲームウィズ — 龍が如く7 資格学校の答え一覧", url: "https://gamewith.jp/ryu-ga-gotoku7/article/show/183956" },
        { label: "ゴリラ攻略wiki — 龍が如く7 資格学校の答え", url: "https://ryugagotoku7.gorillawiki.jp/entry/shikakugakkou" },
        { label: "もいもちゃん — 龍が如く7 資格試験の答え", url: "https://moimochan.com/games/ryugoto7/321/" },
        { label: "GameFAQs (CyricZ) — Yakuza: Like a Dragon Vocational School", url: "https://gamefaqs.gamespot.com/ps4/272324-yakuza-like-a-dragon/faqs/78735/vocational-school" },
      ],
      puzzleSets: [
        {
          title: { ko: "スポーツ2級 — 정답 10문제", en: "Sports Tier 2 — all 10 answers" },
          note: { ko: "수험료 무료(첫 응시는 서브스토리 No.10 안에서) · 첫 합격 보상 정열 +30 · 쾌활 +30. 모든 시험 공통: 가이드들이 문제 문장을 요약해서만 싣기 때문에, 문제 문구는 여러 가이드의 요약을 합친 것이고 게임 원문과 다를 수 있습니다. 정답은 神ゲー攻略·ゴリラwiki·ゲームウィズ·もいもちゃん이 맞춰 본 것입니다.", en: "Fee free (first sitting is inside substory No.10); first pass gives Passion +30, Charisma +30. For every exam: guides only print the questions in shortened form, so the question wording is merged from several guides and may differ from the in-game text. Answers are cross-checked across Kamigame, Gorillawiki, GameWith and moimochan." },
          puzzles: [
            { title: { ko: "1. スポーツの「ボウリング」に関する問題", en: "1. スポーツの「ボウリング」に関する問題" }, note: { ko: "정답: ピン", en: "Answer: ピン" } },
            { title: { ko: "2. スポーツの「陸上」に関する問題（金属球を投げる競技）", en: "2. スポーツの「陸上」に関する問題（金属球を投げる競技）" }, note: { ko: "정답: 砲丸投げ", en: "Answer: 砲丸投げ" } },
            { title: { ko: "3. スポーツの「スキー」に関する問題", en: "3. スポーツの「スキー」に関する問題" }, note: { ko: "정답: ストック", en: "Answer: ストック" } },
            { title: { ko: "4. スポーツの「バスケットボール」に関する問題", en: "4. スポーツの「バスケットボール」に関する問題" }, note: { ko: "정답: 3点", en: "Answer: 3点" } },
            { title: { ko: "5. スポーツの「ゴルフ」に関する問題", en: "5. スポーツの「ゴルフ」に関する問題" }, note: { ko: "정답: アルバトロス", en: "Answer: アルバトロス" } },
            { title: { ko: "6. スポーツの「マラソン」に関する問題（名前の由来）", en: "6. スポーツの「マラソン」に関する問題（名前の由来）" }, note: { ko: "정답: マラトンの戦い", en: "Answer: マラトンの戦い" } },
            { title: { ko: "7. スポーツの「トライアスロン」に関する問題", en: "7. スポーツの「トライアスロン」に関する問題" }, note: { ko: "정답: クロスカントリー", en: "Answer: クロスカントリー" } },
            { title: { ko: "8. スポーツの「カーレース」に関する問題", en: "8. スポーツの「カーレース」に関する問題" }, note: { ko: "정답: ドリフト走行", en: "Answer: ドリフト走行" } },
            { title: { ko: "9. スポーツの「野球」に関する問題", en: "9. スポーツの「野球」に関する問題" }, note: { ko: "정답: ボレー", en: "Answer: ボレー" } },
            { title: { ko: "10. スポーツの「サッカー」に関する問題", en: "10. スポーツの「サッカー」に関する問題" }, note: { ko: "정답: ハンドリング", en: "Answer: ハンドリング" } },
          ],
        },
        {
          title: { ko: "スポーツ1級 — 정답 10문제", en: "Sports Tier 1 — all 10 answers" },
          note: { ko: "수험료 50,000엔 · スポーツ2級 합격 후 · 첫 합격 보상 정열 +50 · 쾌활 +50.", en: "Fee ¥50,000; needs Sports Tier 2 first; first pass gives Passion +50, Charisma +50." },
          puzzles: [
            { title: { ko: "1. スポーツの「卓球」に関する問題", en: "1. スポーツの「卓球」に関する問題" }, note: { ko: "정답: ペンホルダー", en: "Answer: ペンホルダー" } },
            { title: { ko: "2. スポーツの「ダーツ」に関する問題", en: "2. スポーツの「ダーツ」に関する問題" }, note: { ko: "정답: ブル", en: "Answer: ブル" } },
            { title: { ko: "3. バドミントンのシャトルが最速で時速いくらほどか", en: "3. バドミントンのシャトルが最速で時速いくらほどか" }, note: { ko: "정답: 500キロメートル", en: "Answer: 500キロメートル" } },
            { title: { ko: "4. フィギュアスケートで片足の外側エッジから踏み切り反対の足で着氷するジャンプ", en: "4. フィギュアスケートで片足の外側エッジから踏み切り反対の足で着氷するジャンプ" }, note: { ko: "정답: ルッツ", en: "Answer: ルッツ" } },
            { title: { ko: "5. スキー板の先端を接近させ後端を離した状態で滑る滑走法", en: "5. スキー板の先端を接近させ後端を離した状態で滑る滑走法" }, note: { ko: "정답: プルークボーゲン", en: "Answer: プルークボーゲン" } },
            { title: { ko: "6. 野球で単打・二塁打・三塁打・本塁打の全てを1試合で打つ事", en: "6. 野球で単打・二塁打・三塁打・本塁打の全てを1試合で打つ事" }, note: { ko: "정답: サイクルヒット", en: "Answer: サイクルヒット" } },
            { title: { ko: "7. ボクシングのフェザー級よりも体重の軽い階級", en: "7. ボクシングのフェザー級よりも体重の軽い階級" }, note: { ko: "정답: バンタム級", en: "Answer: バンタム級" } },
            { title: { ko: "8. Xスポーツの正式名称", en: "8. Xスポーツの正式名称" }, note: { ko: "정답: エクストリームスポーツ", en: "Answer: エクストリームスポーツ" } },
            { title: { ko: "9. フェンシングで斬る攻撃ができる種目", en: "9. フェンシングで斬る攻撃ができる種目" }, note: { ko: "정답: サーブル", en: "Answer: サーブル" } },
            { title: { ko: "10. アメリカンフットボールで同時にフィールド内に入れる人数", en: "10. アメリカンフットボールで同時にフィールド内に入れる人数" }, note: { ko: "정답: 11人", en: "Answer: 11人" } },
          ],
        },
        {
          title: { ko: "裏社会学 — 정답 10문제", en: "Underworld Studies — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 첫 합격 보상 멘탈 +100.", en: "Fee ¥50,000; first pass gives Confidence +100." },
          puzzles: [
            { title: { ko: "1. 東城会、近江連合以外の極道組織として不適切なもの", en: "1. 東城会、近江連合以外の極道組織として不適切なもの" }, note: { ko: "정답: 泰平一家", en: "Answer: 泰平一家" } },
            { title: { ko: "2. 「嶋野の狂犬」の異名で恐れられた男の正しい名前", en: "2. 「嶋野の狂犬」の異名で恐れられた男の正しい名前" }, note: { ko: "정답: 真島吾朗", en: "Answer: 真島吾朗" } },
            { title: { ko: "3. 神室劇場地下に事務所を構えていた組織（柴田和夫が組長を務めていた組織）", en: "3. 神室劇場地下に事務所を構えていた組織（柴田和夫が組長を務めていた組織）" }, note: { ko: "정답: 初芝会", en: "Answer: 初芝会" } },
            { title: { ko: "4. 錦山組の三代目組長", en: "4. 錦山組の三代目組長" }, note: { ko: "정답: 神田強", en: "Answer: 神田強" } },
            { title: { ko: "5. 東城会の「直系」ではない組", en: "5. 東城会の「直系」ではない組" }, note: { ko: "정답: 玉城組", en: "Answer: 玉城組" } },
            { title: { ko: "6. 東城会の三代目会長", en: "6. 東城会の三代目会長" }, note: { ko: "정답: 世良勝", en: "Answer: 世良勝" } },
            { title: { ko: "7. アンドレ・リチャードソンが首領を務めた組織", en: "7. アンドレ・リチャードソンが首領を務めた組織" }, note: { ko: "정답: ブラックマンデー", en: "Answer: ブラックマンデー" } },
            { title: { ko: "8. 「関西の龍」郷田仁は近江連合の何代目会長か", en: "8. 「関西の龍」郷田仁は近江連合の何代目会長か" }, note: { ko: "정답: 五代目", en: "Answer: 五代目" } },
            { title: { ko: "9. 近江連合「千石組」組長の名前", en: "9. 近江連合「千石組」組長の名前" }, note: { ko: "정답: 千石虎之介", en: "Answer: 千石虎之介" } },
            { title: { ko: "10. 2010年代の近江連合の組で不適切なもの", en: "10. 2010年代の近江連合の組で不適切なもの" }, note: { ko: "정답: 笹井組", en: "Answer: 笹井組" } },
          ],
        },
        {
          title: { ko: "伊勢佐木異人町検定 — 정답 10문제", en: "Isezaki Ijincho Proficiency — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 첫 합격 보상 지성 +100.", en: "Fee ¥50,000; first pass gives Intellect +100." },
          puzzles: [
            { title: { ko: "1. 伊勢佐木ロード北の大人気ファストフード店", en: "1. 伊勢佐木ロード北の大人気ファストフード店" }, note: { ko: "정답: ヴェッテキッチン", en: "Answer: ヴェッテキッチン" } },
            { title: { ko: "2. 伊勢佐木異人町の中心部にある鉄道駅", en: "2. 伊勢佐木異人町の中心部にある鉄道駅" }, note: { ko: "정답: 神内駅", en: "Answer: 神内駅" } },
            { title: { ko: "3. 伊勢佐木異人町を縦断する川の名前", en: "3. 伊勢佐木異人町を縦断する川の名前" }, note: { ko: "정답: 櫻川", en: "Answer: 櫻川" } },
            { title: { ko: "4. 昔の映画作品が上映されている映画館の名前", en: "4. 昔の映画作品が上映されている映画館の名前" }, note: { ko: "정답: うみねこ坐", en: "Answer: うみねこ坐" } },
            { title: { ko: "5. 中華街の「クラブセガ」にあるゲーム", en: "5. 中華街の「クラブセガ」にあるゲーム" }, note: { ko: "정답: スペースハリアー", en: "Answer: スペースハリアー" } },
            { title: { ko: "6. スナック街に存在する店", en: "6. スナック街に存在する店" }, note: { ko: "정답: Bar Rodriguez", en: "Answer: Bar Rodriguez" } },
            { title: { ko: "7. 浜北公園の乗り物競技の名前", en: "7. 浜北公園の乗り物競技の名前" }, note: { ko: "정답: ドラゴンカート", en: "Answer: ドラゴンカート" } },
            { title: { ko: "8. 中華街（さん橋通り）の門の名前", en: "8. 中華街（さん橋通り）の門の名前" }, note: { ko: "정답: 太陽門", en: "Answer: 太陽門" } },
            { title: { ko: "9. 大海原資格学校の前を走る大通りの名前", en: "9. 大海原資格学校の前を走る大通りの名前" }, note: { ko: "정답: 大黒天通り", en: "Answer: 大黒天通り" } },
            { title: { ko: "10. 湾岸沿いの公園の名前", en: "10. 湾岸沿いの公園の名前" }, note: { ko: "정답: 浜北公園", en: "Answer: 浜北公園" } },
          ],
        },
        {
          title: { ko: "動物博士 — 정답 10문제", en: "Animal Science — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 첫 합격 보상 상냥함 +100.", en: "Fee ¥50,000; first pass gives Kindness +100." },
          puzzles: [
            { title: { ko: "1. 餌取りのために巣を作らない蜘蛛", en: "1. 餌取りのために巣を作らない蜘蛛" }, note: { ko: "정답: ハエトリグモ", en: "Answer: ハエトリグモ" } },
            { title: { ko: "2. 草食動物", en: "2. 草食動物" }, note: { ko: "정답: ビーバー", en: "Answer: ビーバー" } },
            { title: { ko: "3. 魚類に属する動物", en: "3. 魚類に属する動物" }, note: { ko: "정답: ホオジロザメ", en: "Answer: ホオジロザメ" } },
            { title: { ko: "4. 両生類の動物", en: "4. 両生類の動物" }, note: { ko: "정답: イモリ", en: "Answer: イモリ" } },
            { title: { ko: "5. 最も体長が長い爬虫類", en: "5. 最も体長が長い爬虫類" }, note: { ko: "정답: イリエワニ", en: "Answer: イリエワニ" } },
            { title: { ko: "6. かつてペンギンと呼ばれていた絶滅動物", en: "6. かつてペンギンと呼ばれていた絶滅動物" }, note: { ko: "정답: オオウミガラス", en: "Answer: オオウミガラス" } },
            { title: { ko: "7. 空を飛べない鳥", en: "7. 空を飛べない鳥" }, note: { ko: "정답: ダチョウ", en: "Answer: ダチョウ" } },
            { title: { ko: "8. 実はサメではない魚", en: "8. 実はサメではない魚" }, note: { ko: "정답: チョウザメ", en: "Answer: チョウザメ" } },
            { title: { ko: "9. 類人猿に分類されない動物", en: "9. 類人猿に分類されない動物" }, note: { ko: "정답: ニホンザル", en: "Answer: ニホンザル" } },
            { title: { ko: "10. 学術的に「昆虫」に含まれる虫", en: "10. 学術的に「昆虫」に含まれる虫" }, note: { ko: "정답: テントウムシ", en: "Answer: テントウムシ" } },
          ],
        },
        {
          title: { ko: "SEGA検定2級 — 정답 10문제", en: "SEGA Proficiency Tier 2 — all 10 answers" },
          note: { ko: "수험료 30,000엔 · 첫 합격 보상 정열 +30 · 세련 +30.", en: "Fee ¥30,000; first pass gives Passion +30, Style +30." },
          puzzles: [
            { title: { ko: "1. 魔人デス=アダーを倒すために戦う戦士が主人公の名作アクションゲーム", en: "1. 魔人デス=アダーを倒すために戦う戦士が主人公の名作アクションゲーム" }, note: { ko: "정답: ゴールデンアックス", en: "Answer: ゴールデンアックス" } },
            { title: { ko: "2. ジェットセットラジオで主人公達が街の中に描いていたもの", en: "2. ジェットセットラジオで主人公達が街の中に描いていたもの" }, note: { ko: "정답: グラフィティ", en: "Answer: グラフィティ" } },
            { title: { ko: "3. セガが発売した人気格闘ゲームシリーズ", en: "3. セガが発売した人気格闘ゲームシリーズ" }, note: { ko: "정답: バーチャファイター", en: "Answer: バーチャファイター" } },
            { title: { ko: "4. 柔らかい色彩が印象的なシューティングゲームシリーズ", en: "4. 柔らかい色彩が印象的なシューティングゲームシリーズ" }, note: { ko: "정답: ファンタジーゾーン", en: "Answer: ファンタジーゾーン" } },
            { title: { ko: "5. セガのゲーム機のうち発売日が2番目に古いもの", en: "5. セガのゲーム機のうち発売日が2番目に古いもの" }, note: { ko: "정답: メガドライブ", en: "Answer: メガドライブ" } },
            { title: { ko: "6. ソニック・ザ・ヘッジホッグが最初に発売された家庭用ゲーム機", en: "6. ソニック・ザ・ヘッジホッグが最初に発売された家庭用ゲーム機" }, note: { ko: "정답: メガドライブ", en: "Answer: メガドライブ" } },
            { title: { ko: "7. サクラ大戦シリーズ4作目までの主人公", en: "7. サクラ大戦シリーズ4作目までの主人公" }, note: { ko: "정답: 大神一郎", en: "Answer: 大神一郎" } },
            { title: { ko: "8. 日本で発売されていないセガサターンの色", en: "8. 日本で発売されていないセガサターンの色" }, note: { ko: "정답: 黒", en: "Answer: 黒" } },
            { title: { ko: "9. サクラ大戦で真宮寺さくらが所属している部隊", en: "9. サクラ大戦で真宮寺さくらが所属している部隊" }, note: { ko: "정답: 花組", en: "Answer: 花組" } },
            { title: { ko: "10. セガが販売していないゲーム機", en: "10. セガが販売していないゲーム機" }, note: { ko: "정답: セガ　プルート", en: "Answer: セガ　プルート" } },
          ],
        },
        {
          title: { ko: "SEGA検定1級 — 정답 10문제", en: "SEGA Proficiency Tier 1 — all 10 answers" },
          note: { ko: "수험료 50,000엔 · SEGA検定2級 합격 후 · 첫 합격 보상 정열 +50 · 세련 +50.", en: "Fee ¥50,000; needs SEGA Proficiency Tier 2 first; first pass gives Passion +50, Style +50." },
          puzzles: [
            { title: { ko: "1. きみのためなら死ねるで主人公が参加したスーパーパフォーマンス集団の名前", en: "1. きみのためなら死ねるで主人公が参加したスーパーパフォーマンス集団の名前" }, note: { ko: "정답: ラブラビッツ", en: "Answer: ラブラビッツ" } },
            { title: { ko: "2. ソニック・ザ・ヘッジホッグ（ソニック）の年齢", en: "2. ソニック・ザ・ヘッジホッグ（ソニック）の年齢" }, note: { ko: "정답: 15歳", en: "Answer: 15歳" } },
            { title: { ko: "3. セガが実際に販売したマシンの正式名称", en: "3. セガが実際に販売したマシンの正式名称" }, note: { ko: "정답: テラドライブ", en: "Answer: テラドライブ" } },
            { title: { ko: "4. 戦場のヴァルキュリア1作目で主人公が属する国", en: "4. 戦場のヴァルキュリア1作目で主人公が属する国" }, note: { ko: "정답: ガリア公国", en: "Answer: ガリア公国" } },
            { title: { ko: "5. バーチャファイターの主人公", en: "5. バーチャファイターの主人公" }, note: { ko: "정답: アキラ", en: "Answer: アキラ" } },
            { title: { ko: "6. スペースチャンネル5でウララ達が口にする言葉", en: "6. スペースチャンネル5でウララ達が口にする言葉" }, note: { ko: "정답: チュー！", en: "Answer: チュー！" } },
            { title: { ko: "7. メガドライブの周辺機器で公式に発売されていないもの", en: "7. メガドライブの周辺機器で公式に発売されていないもの" }, note: { ko: "정답: セガキーボード", en: "Answer: セガキーボード" } },
            { title: { ko: "8. パンツァードラグーン ツヴァイで主人公の相方となったドラゴンの名前", en: "8. パンツァードラグーン ツヴァイで主人公の相方となったドラゴンの名前" }, note: { ko: "정답: ラギ", en: "Answer: ラギ" } },
            { title: { ko: "9. メガドライブの標準コントローラーにないボタン", en: "9. メガドライブの標準コントローラーにないボタン" }, note: { ko: "정답: セレクトボタン", en: "Answer: セレクトボタン" } },
            { title: { ko: "10. サクラ大戦のナンバリングに使われた事のないサブタイトル", en: "10. サクラ大戦のナンバリングに使われた事のないサブタイトル" }, note: { ko: "정답: さらば故郷", en: "Answer: さらば故郷" } },
          ],
        },
        {
          title: { ko: "数学2級 — 정답 10문제", en: "Mathematics Tier 2 — all 10 answers" },
          note: { ko: "수험료 30,000엔 · 첫 합격 보상 지성 +60.", en: "Fee ¥30,000; first pass gives Intellect +60." },
          puzzles: [
            { title: { ko: "1. 向かい合う2つの内角同士が同じで、内角がひとつも90度ではない四角形", en: "1. 向かい合う2つの内角同士が同じで、内角がひとつも90度ではない四角形" }, note: { ko: "정답: 平行四辺形", en: "Answer: 平行四辺形" } },
            { title: { ko: "2. 120×2=", en: "2. 120×2=" }, note: { ko: "정답: 240", en: "Answer: 240" } },
            { title: { ko: "3. 同じ長さの5本の辺で構成される正五角形の内角", en: "3. 同じ長さの5本の辺で構成される正五角形の内角" }, note: { ko: "정답: 108度", en: "Answer: 108度" } },
            { title: { ko: "4. 三角形の内角のうち1つは65度、1つは35度の時、残りひとつの内角", en: "4. 三角形の内角のうち1つは65度、1つは35度の時、残りひとつの内角" }, note: { ko: "정답: 80度", en: "Answer: 80度" } },
            { title: { ko: "5. 200÷25=", en: "5. 200÷25=" }, note: { ko: "정답: 8", en: "Answer: 8" } },
            { title: { ko: "6. 72-3-17=", en: "6. 72-3-17=" }, note: { ko: "정답: 52", en: "Answer: 52" } },
            { title: { ko: "7. 6+16=", en: "7. 6+16=" }, note: { ko: "정답: 22", en: "Answer: 22" } },
            { title: { ko: "8. 121÷11=", en: "8. 121÷11=" }, note: { ko: "정답: 11", en: "Answer: 11" } },
            { title: { ko: "9. 三角形の内角のうち1つは40度、1つは50度の時、残りひとつの内角", en: "9. 三角形の内角のうち1つは40度、1つは50度の時、残りひとつの内角" }, note: { ko: "정답: 90度", en: "Answer: 90度" } },
            { title: { ko: "10. 14+37=", en: "10. 14+37=" }, note: { ko: "정답: 51", en: "Answer: 51" } },
          ],
        },
        {
          title: { ko: "数学1級 — 정답 10문제", en: "Mathematics Tier 1 — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 数学2級 합격 후 · 첫 합격 보상 지성 +100.", en: "Fee ¥50,000; needs Mathematics Tier 2 first; first pass gives Intellect +100." },
          puzzles: [
            { title: { ko: "1. 6、○、496、8128、33550336 の○に入る数字", en: "1. 6、○、496、8128、33550336 の○に入る数字" }, note: { ko: "정답: 28", en: "Answer: 28" } },
            { title: { ko: "2. 1、2、4、7、○、16、22 の○に入る数字", en: "2. 1、2、4、7、○、16、22 の○に入る数字" }, note: { ko: "정답: 11", en: "Answer: 11" } },
            { title: { ko: "3. 1、3、6、○、15、21、28、36 の○に入る数字", en: "3. 1、3、6、○、15、21、28、36 の○に入る数字" }, note: { ko: "정답: 10", en: "Answer: 10" } },
            { title: { ko: "4. 2、3、5、7、11、13、17、19、○、29、31、37 の○に入る数字", en: "4. 2、3、5、7、11、13、17、19、○、29、31、37 の○に入る数字" }, note: { ko: "정답: 23", en: "Answer: 23" } },
            { title: { ko: "5. 1、4、9、16、○、36、49 の○に入る数字", en: "5. 1、4、9、16、○、36、49 の○に入る数字" }, note: { ko: "정답: 25", en: "Answer: 25" } },
            { title: { ko: "6. 1つだけ違うものを選びなさい（16.8÷4-0.2 / 11-1.2×5 / 96÷24 / -1-2-3+10）", en: "6. 1つだけ違うものを選びなさい（16.8÷4-0.2 / 11-1.2×5 / 96÷24 / -1-2-3+10）" }, note: { ko: "정답: 11-1.2×5", en: "Answer: 11-1.2×5" } },
            { title: { ko: "7. 1つだけ違うものを選びなさい（1+2+3+4+5 / 30÷5+9 / 125÷5 / 3×5）", en: "7. 1つだけ違うものを選びなさい（1+2+3+4+5 / 30÷5+9 / 125÷5 / 3×5）" }, note: { ko: "정답: 125÷5", en: "Answer: 125÷5" } },
            { title: { ko: "8. 1つだけ違うものを選びなさい（1×3×5×7 / 8×15 / (9+3)×10 / 5!）", en: "8. 1つだけ違うものを選びなさい（1×3×5×7 / 8×15 / (9+3)×10 / 5!）" }, note: { ko: "정답: 1×3×5×7", en: "Answer: 1×3×5×7" } },
            { title: { ko: "9. 1つだけ違うものを選びなさい（20% / 0.2 / 2÷1 / 1÷5）", en: "9. 1つだけ違うものを選びなさい（20% / 0.2 / 2÷1 / 1÷5）" }, note: { ko: "정답: 2÷1", en: "Answer: 2÷1" } },
            { title: { ko: "10. 1つだけ違うものを選びなさい（108÷12 / 10÷2+3 / 64×2÷16 / 4×2）", en: "10. 1つだけ違うものを選びなさい（108÷12 / 10÷2+3 / 64×2÷16 / 4×2）" }, note: { ko: "정답: 108÷12", en: "Answer: 108÷12" } },
          ],
        },
        {
          title: { ko: "ファッションリーダー — 정답 10문제", en: "Fashionista — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 첫 합격 보상 세련 +100.", en: "Fee ¥50,000; first pass gives Style +100." },
          puzzles: [
            { title: { ko: "1. 動物繊維でも植物繊維でもない化学繊維", en: "1. 動物繊維でも植物繊維でもない化学繊維" }, note: { ko: "정답: ナイロン", en: "Answer: ナイロン" } },
            { title: { ko: "2. スコットランドの民族衣装", en: "2. スコットランドの民族衣装" }, note: { ko: "정답: キルト", en: "Answer: キルト" } },
            { title: { ko: "3. 古代ギリシャにおいて男性が着ていた一枚布の上着", en: "3. 古代ギリシャにおいて男性が着ていた一枚布の上着" }, note: { ko: "정답: トーガ", en: "Answer: トーガ" } },
            { title: { ko: "4. 服の柄として使われる以下4種類の模様のうち、菱形が使われているもの", en: "4. 服の柄として使われる以下4種類の模様のうち、菱形が使われているもの" }, note: { ko: "정답: アーガイル柄", en: "Answer: アーガイル柄" } },
            { title: { ko: "5. アクリル繊維の肌触りと最も近い繊維", en: "5. アクリル繊維の肌触りと最も近い繊維" }, note: { ko: "정답: ウール", en: "Answer: ウール" } },
            { title: { ko: "6. 狩猟の際に着用された事から名前がついた帽子", en: "6. 狩猟の際に着用された事から名前がついた帽子" }, note: { ko: "정답: ハンチング帽", en: "Answer: ハンチング帽" } },
            { title: { ko: "7. ベトナムの民族衣装", en: "7. ベトナムの民族衣装" }, note: { ko: "정답: アオザイ", en: "Answer: アオザイ" } },
            { title: { ko: "8. 絹糸の説明として間違っているもの", en: "8. 絹糸の説明として間違っているもの" }, note: { ko: "정답: 植物から作られる繊維である", en: "Answer: 植物から作られる繊維である" } },
            { title: { ko: "9. ポロシャツの「ポロ」とは何の事か", en: "9. ポロシャツの「ポロ」とは何の事か" }, note: { ko: "정답: ポロという競技", en: "Answer: ポロという競技" } },
            { title: { ko: "10. 高級な衣装を取り扱う店を表すフランス語「オート○○」に入る言葉", en: "10. 高級な衣装を取り扱う店を表すフランス語「オート○○」に入る言葉" }, note: { ko: "정답: クチュール", en: "Answer: クチュール" } },
          ],
        },
        {
          title: { ko: "音楽検定2級 — 정답 10문제", en: "Music Proficiency Tier 2 — all 10 answers" },
          note: { ko: "수험료 30,000엔 · 첫 합격 보상 상냥함 +30 · 세련 +30.", en: "Fee ¥30,000; first pass gives Kindness +30, Style +30." },
          puzzles: [
            { title: { ko: "1. 流れてくる曲のタイトル（春 / 夏 / 秋 / 冬）", en: "1. 流れてくる曲のタイトル（春 / 夏 / 秋 / 冬）" }, note: { ko: "정답: 春", en: "Answer: 春" } },
            { title: { ko: "2. 「月光」「歓喜の歌」「運命」などを作曲した音楽家", en: "2. 「月光」「歓喜の歌」「運命」などを作曲した音楽家" }, note: { ko: "정답: ベートーヴェン", en: "Answer: ベートーヴェン" } },
            { title: { ko: "3. 流れてくる曲のタイトル（エニグマ変奏曲 / 運命 / 威風堂々 / ヴァイオリン協奏曲）", en: "3. 流れてくる曲のタイトル（エニグマ変奏曲 / 運命 / 威風堂々 / ヴァイオリン協奏曲）" }, note: { ko: "정답: 威風堂々", en: "Answer: 威風堂々" } },
            { title: { ko: "4. 曲のリズムを一定の速さに調整するための道具", en: "4. 曲のリズムを一定の速さに調整するための道具" }, note: { ko: "정답: メトロノーム", en: "Answer: メトロノーム" } },
            { title: { ko: "5. 音楽の父「ヨハン・ゼバスティアン・○○」", en: "5. 音楽の父「ヨハン・ゼバスティアン・○○」" }, note: { ko: "정답: バッハ", en: "Answer: バッハ" } },
            { title: { ko: "6. 世界3大ヴァイオリンとして名高いヴァイオリンの名前", en: "6. 世界3大ヴァイオリンとして名高いヴァイオリンの名前" }, note: { ko: "정답: ストラディヴァリウス", en: "Answer: ストラディヴァリウス" } },
            { title: { ko: "7. 打楽器に分類される楽器", en: "7. 打楽器に分類される楽器" }, note: { ko: "정답: 木琴", en: "Answer: 木琴" } },
            { title: { ko: "8. 流れてくる曲のタイトル（愛しのソナタ / ボレロ / カンパネラ / エリーゼのために）", en: "8. 流れてくる曲のタイトル（愛しのソナタ / ボレロ / カンパネラ / エリーゼのために）" }, note: { ko: "정답: エリーゼのために", en: "Answer: エリーゼのために" } },
            { title: { ko: "9. ピョートル・チャイコフスキーが作曲したバレエ作品のタイトル", en: "9. ピョートル・チャイコフスキーが作曲したバレエ作品のタイトル" }, note: { ko: "정답: 白鳥の湖", en: "Answer: 白鳥の湖" } },
            { title: { ko: "10. フレデリック・ショパンの作曲した曲", en: "10. フレデリック・ショパンの作曲した曲" }, note: { ko: "정답: 子犬のワルツ", en: "Answer: 子犬のワルツ" } },
          ],
        },
        {
          title: { ko: "音楽検定1級 — 정답 10문제", en: "Music Proficiency Tier 1 — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 音楽検定2級 합격 후 · 첫 합격 보상 상냥함 +50 · 세련 +50.", en: "Fee ¥50,000; needs Music Proficiency Tier 2 first; first pass gives Kindness +50, Style +50." },
          puzzles: [
            { title: { ko: "1. 「ツィゴイネルワイゼン」で知られるパブロ・デ・サラサーテの出身国", en: "1. 「ツィゴイネルワイゼン」で知られるパブロ・デ・サラサーテの出身国" }, note: { ko: "정답: スペイン", en: "Answer: スペイン" } },
            { title: { ko: "2. イタリアの作曲家ジュゼッペ・ヴェルディが作曲した歌劇", en: "2. イタリアの作曲家ジュゼッペ・ヴェルディが作曲した歌劇" }, note: { ko: "정답: マクベス", en: "Answer: マクベス" } },
            { title: { ko: "3. ジャン・シベリウスの作った交響詩", en: "3. ジャン・シベリウスの作った交響詩" }, note: { ko: "정답: フィンランディア", en: "Answer: フィンランディア" } },
            { title: { ko: "4. 流れてくる曲のタイトル（第1楽章アダージョ / 第2楽章ラルゴ / 第3楽章スケルツォ / 第4楽章アレグロ・コン・フォーコ）", en: "4. 流れてくる曲のタイトル（第1楽章アダージョ / 第2楽章ラルゴ / 第3楽章スケルツォ / 第4楽章アレグロ・コン・フォーコ）" }, note: { ko: "정답: 第2楽章ラルゴ", en: "Answer: 第2楽章ラルゴ" } },
            { title: { ko: "5. 流れてくる曲のタイトル（ワルプルギスの夜 / 銀河鉄道の夜 / 魔笛　夜の女王 / 真夏の夜の夢）", en: "5. 流れてくる曲のタイトル（ワルプルギスの夜 / 銀河鉄道の夜 / 魔笛　夜の女王 / 真夏の夜の夢）" }, note: { ko: "정답: 真夏の夜の夢", en: "Answer: 真夏の夜の夢" } },
            { title: { ko: "6. 1台のピアノを複数人で同時に演奏する演奏技法", en: "6. 1台のピアノを複数人で同時に演奏する演奏技法" }, note: { ko: "정답: 連弾", en: "Answer: 連弾" } },
            { title: { ko: "7. 「最も強く演奏するように」を指示する音楽用語", en: "7. 「最も強く演奏するように」を指示する音楽用語" }, note: { ko: "정답: フォルテッシシモ", en: "Answer: フォルテッシシモ" } },
            { title: { ko: "8. 流れてくる曲のタイトル（魔法使いの弟子 / クシコス・ポスト / ギャロップ / 天国と地獄）", en: "8. 流れてくる曲のタイトル（魔法使いの弟子 / クシコス・ポスト / ギャロップ / 天国と地獄）" }, note: { ko: "정답: クシコス・ポスト", en: "Answer: クシコス・ポスト" } },
            { title: { ko: "9. 音楽を演奏する速度を徐々に遅くする事を指示する音楽用語", en: "9. 音楽を演奏する速度を徐々に遅くする事を指示する音楽用語" }, note: { ko: "정답: リタルダンド", en: "Answer: リタルダンド" } },
            { title: { ko: "10. 「魔笛」「フィガロの結婚」「ドン・ジョバンニ」等の作曲家として知られる音楽家の名前", en: "10. 「魔笛」「フィガロの結婚」「ドン・ジョバンニ」等の作曲家として知られる音楽家の名前" }, note: { ko: "정답: モーツァルト", en: "Answer: モーツァルト" } },
          ],
        },
        {
          title: { ko: "医療調剤学 — 정답 10문제", en: "Pharmacology — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 첫 합격 보상 지성 +100.", en: "Fee ¥50,000; first pass gives Intellect +100." },
          puzzles: [
            { title: { ko: "1. 医薬品は投与手段に応じて内服薬・外用薬と、残る1つは", en: "1. 医薬品は投与手段に応じて内服薬・外用薬と、残る1つは" }, note: { ko: "정답: 注射薬", en: "Answer: 注射薬" } },
            { title: { ko: "2. 皮膚の保湿に有効な精製成分", en: "2. 皮膚の保湿に有効な精製成分" }, note: { ko: "정답: 白色ワセリン", en: "Answer: 白色ワセリン" } },
            { title: { ko: "3. 痛みを和らげるために使われる薬物", en: "3. 痛みを和らげるために使われる薬物" }, note: { ko: "정답: モルヒネ", en: "Answer: モルヒネ" } },
            { title: { ko: "4. 頭痛や炎症の鎮痛に有効な成分", en: "4. 頭痛や炎症の鎮痛に有効な成分" }, note: { ko: "정답: アセチルサリチル酸", en: "Answer: アセチルサリチル酸" } },
            { title: { ko: "5. 湿疹などの改善に使われる軟膏剤に含まれる化合物", en: "5. 湿疹などの改善に使われる軟膏剤に含まれる化合物" }, note: { ko: "정답: ステロイド", en: "Answer: ステロイド" } },
            { title: { ko: "6. 医師の診察と指示を基に調剤される薬", en: "6. 医師の診察と指示を基に調剤される薬" }, note: { ko: "정답: 処方箋医薬品", en: "Answer: 処方箋医薬品" } },
            { title: { ko: "7. 消毒薬として使われる化学成分", en: "7. 消毒薬として使われる化学成分" }, note: { ko: "정답: エタノール", en: "Answer: エタノール" } },
            { title: { ko: "8. オリジナルの薬の特許が切れ、他社が同じ有効成分で製造する薬品", en: "8. オリジナルの薬の特許が切れ、他社が同じ有効成分で製造する薬品" }, note: { ko: "정답: ジェネリック医薬品", en: "Answer: ジェネリック医薬品" } },
            { title: { ko: "9. 塗る「外用薬」に含まれる薬剤", en: "9. 塗る「外用薬」に含まれる薬剤" }, note: { ko: "정답: トローチ", en: "Answer: トローチ" } },
            { title: { ko: "10. 飲む「内服薬」に含まれる薬剤", en: "10. 飲む「内服薬」に含まれる薬剤" }, note: { ko: "정답: 粉薬", en: "Answer: 粉薬" } },
          ],
        },
        {
          title: { ko: "フードコーディネーター — 정답 10문제", en: "Nutritionist — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 첫 합격 보상 상냥함 +50 · 쾌활 +50.", en: "Fee ¥50,000; first pass gives Kindness +50, Charisma +50." },
          puzzles: [
            { title: { ko: "1. 野菜のトマトに含まれない栄養素", en: "1. 野菜のトマトに含まれない栄養素" }, note: { ko: "정답: ビタミンD", en: "Answer: ビタミンD" } },
            { title: { ko: "2. スペイン料理", en: "2. スペイン料理" }, note: { ko: "정답: タパス", en: "Answer: タパス" } },
            { title: { ko: "3. 青魚等に含まれる不飽和脂肪酸の名前", en: "3. 青魚等に含まれる不飽和脂肪酸の名前" }, note: { ko: "정답: ドコサヘキサエン酸", en: "Answer: ドコサヘキサエン酸" } },
            { title: { ko: "4. 茹でたパスタ・黒コショウ・チーズの3種類の素材で作れる料理", en: "4. 茹でたパスタ・黒コショウ・チーズの3種類の素材で作れる料理" }, note: { ko: "정답: カチョ・エ・ペペ", en: "Answer: カチョ・エ・ペペ" } },
            { title: { ko: "5. 「水に溶ける」特徴をもつ水溶性食物繊維", en: "5. 「水に溶ける」特徴をもつ水溶性食物繊維" }, note: { ko: "정답: ペクチン", en: "Answer: ペクチン" } },
            { title: { ko: "6. スカンジナビアで作られる、珍しい動物（の乳）から作られるチーズ", en: "6. スカンジナビアで作られる、珍しい動物（の乳）から作られるチーズ" }, note: { ko: "정답: トナカイ", en: "Answer: トナカイ" } },
            { title: { ko: "7. 魚を使う料理として一般的に知られている料理名", en: "7. 魚を使う料理として一般的に知られている料理名" }, note: { ko: "정답: アクアパッツァ", en: "Answer: アクアパッツァ" } },
            { title: { ko: "8. トウガラシ等辛味の強い食材に多く含まれ、食欲増進や脂肪燃焼効果がある成分", en: "8. トウガラシ等辛味の強い食材に多く含まれ、食欲増進や脂肪燃焼効果がある成分" }, note: { ko: "정답: カプサイシン", en: "Answer: カプサイシン" } },
            { title: { ko: "9. ポテトを潰して生クリームやブイヨンと合わせて裏ごしして冷やしたスープ", en: "9. ポテトを潰して生クリームやブイヨンと合わせて裏ごしして冷やしたスープ" }, note: { ko: "정답: ヴィシソワーズ", en: "Answer: ヴィシソワーズ" } },
            { title: { ko: "10. トルコ料理", en: "10. トルコ料理" }, note: { ko: "정답: ケバブ", en: "Answer: ケバブ" } },
          ],
        },
        {
          title: { ko: "危険物取扱管理 — 정답 10문제", en: "Hazardous Materials — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 첫 합격 보상 멘탈 +100.", en: "Fee ¥50,000; first pass gives Confidence +100." },
          puzzles: [
            { title: { ko: "1. 危険物取扱者の資格保有者が監督しなければならない作業", en: "1. 危険物取扱者の資格保有者が監督しなければならない作業" }, note: { ko: "정답: ガソリンスタンドを営業する", en: "Answer: ガソリンスタンドを営業する" } },
            { title: { ko: "2. 「重金属」に含まれるもの", en: "2. 「重金属」に含まれるもの" }, note: { ko: "정답: 亜鉛", en: "Answer: 亜鉛" } },
            { title: { ko: "3. 危険物を管理する時、定められた広さの空地を確保する理由", en: "3. 危険物を管理する時、定められた広さの空地を確保する理由" }, note: { ko: "정답: 不測の事態において被害を抑える為", en: "Answer: 不測の事態において被害を抑える為" } },
            { title: { ko: "4. アルコールやガソリンはどの状態に分類されるか", en: "4. アルコールやガソリンはどの状態に分類されるか" }, note: { ko: "정답: 液体", en: "Answer: 液体" } },
            { title: { ko: "5. 危険物取扱者乙種第4類の性質として正しいもの", en: "5. 危険物取扱者乙種第4類の性質として正しいもの" }, note: { ko: "정답: 引火性の液体", en: "Answer: 引火性の液体" } },
            { title: { ko: "6. 粉塵爆発が起こる際に必ず必要になる条件", en: "6. 粉塵爆発が起こる際に必ず必要になる条件" }, note: { ko: "정답: 酸素", en: "Answer: 酸素" } },
            { title: { ko: "7. 危険物と危険物取扱者が関与すべき状況を定めている法律の名前", en: "7. 危険物と危険物取扱者が関与すべき状況を定めている法律の名前" }, note: { ko: "정답: 消防法", en: "Answer: 消防法" } },
            { title: { ko: "8. 静電気を起こしにくくする為の対策", en: "8. 静電気を起こしにくくする為の対策" }, note: { ko: "정답: 湿度を上げる", en: "Answer: 湿度を上げる" } },
            { title: { ko: "9. 物質が固体から気体に変化する事", en: "9. 物質が固体から気体に変化する事" }, note: { ko: "정답: 昇華", en: "Answer: 昇華" } },
            { title: { ko: "10. 「危険物取扱者」が扱える危険物は最大で何種類に分類されるか", en: "10. 「危険物取扱者」が扱える危険物は最大で何種類に分類されるか" }, note: { ko: "정답: 6種類", en: "Answer: 6種類" } },
          ],
        },
        {
          title: { ko: "国旗マスター — 정답 10문제", en: "Flag Master — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 첫 합격 보상 쾌활 +100.", en: "Fee ¥50,000; first pass gives Charisma +100." },
          puzzles: [
            { title: { ko: "1. 国旗に黄色が含まれている国", en: "1. 国旗に黄色が含まれている国" }, note: { ko: "정답: スペイン王国", en: "Answer: スペイン王国" } },
            { title: { ko: "2. 国旗が赤・白・青の3色で構成されている国", en: "2. 国旗が赤・白・青の3色で構成されている国" }, note: { ko: "정답: ロシア", en: "Answer: ロシア" } },
            { title: { ko: "3. 国旗に月が描かれている国", en: "3. 国旗に月が描かれている国" }, note: { ko: "정답: シンガポール共和国", en: "Answer: シンガポール共和国" } },
            { title: { ko: "4. 国旗が4色で構成されている国", en: "4. 国旗が4色で構成されている国" }, note: { ko: "정답: マレーシア", en: "Answer: マレーシア" } },
            { title: { ko: "5. 国旗に緑色が含まれている国", en: "5. 国旗に緑色が含まれている国" }, note: { ko: "정답: カメルーン共和国", en: "Answer: カメルーン共和国" } },
            { title: { ko: "6. 国旗に「龍」が描かれている国", en: "6. 国旗に「龍」が描かれている国" }, note: { ko: "정답: ブータン王国", en: "Answer: ブータン王国" } },
            { title: { ko: "7. 国旗に「植物」が描かれている国", en: "7. 国旗に「植物」が描かれている国" }, note: { ko: "정답: カナダ", en: "Answer: カナダ" } },
            { title: { ko: "8. 国旗が赤と白の2色で構成されている国", en: "8. 国旗が赤と白の2色で構成されている国" }, note: { ko: "정답: オーストリア共和国", en: "Answer: オーストリア共和国" } },
            { title: { ko: "9. 国旗に太陽と星が両方描かれている国", en: "9. 国旗に太陽と星が両方描かれている国" }, note: { ko: "정답: フィリピン共和国", en: "Answer: フィリピン共和国" } },
            { title: { ko: "10. 国旗に青色が含まれている国", en: "10. 国旗に青色が含まれている国" }, note: { ko: "정답: エストニア共和国", en: "Answer: エストニア共和国" } },
          ],
        },
        {
          title: { ko: "歴史学 — 정답 10문제", en: "World History — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 첫 합격 보상 지성 +100.", en: "Fee ¥50,000; first pass gives Intellect +100." },
          puzzles: [
            { title: { ko: "1. 19世紀にアメリカ大陸において奴隷の人権を求めて分裂した内戦の名前", en: "1. 19世紀にアメリカ大陸において奴隷の人権を求めて分裂した内戦の名前" }, note: { ko: "정답: 南北戦争", en: "Answer: 南北戦争" } },
            { title: { ko: "2. 18世紀に活躍したフランスの軍人ナポレオンが最期を迎えた場所", en: "2. 18世紀に活躍したフランスの軍人ナポレオンが最期を迎えた場所" }, note: { ko: "정답: セントヘレナ島", en: "Answer: セントヘレナ島" } },
            { title: { ko: "3. 紀元前3世紀、カルタゴの兵士を率いてローマに攻め入った将軍", en: "3. 紀元前3世紀、カルタゴの兵士を率いてローマに攻め入った将軍" }, note: { ko: "정답: ハンニバル・バルカ", en: "Answer: ハンニバル・バルカ" } },
            { title: { ko: "4. フランス最後の王妃マリー・アントワネットの母親の名前", en: "4. フランス最後の王妃マリー・アントワネットの母親の名前" }, note: { ko: "정답: マリア・テレジア", en: "Answer: マリア・テレジア" } },
            { title: { ko: "5. 西アジアに流れるチグリス川・ユーフラテス川の恩恵を受けて栄えた古代文明", en: "5. 西アジアに流れるチグリス川・ユーフラテス川の恩恵を受けて栄えた古代文明" }, note: { ko: "정답: メソポタミア文明", en: "Answer: メソポタミア文明" } },
            { title: { ko: "6. 16世紀の日本において本能寺の変を起こした人物", en: "6. 16世紀の日本において本能寺の変を起こした人物" }, note: { ko: "정답: 明智光秀", en: "Answer: 明智光秀" } },
            { title: { ko: "7. 古代エジプトにおいて神権を大義に国を治めた君主の称号", en: "7. 古代エジプトにおいて神権を大義に国を治めた君主の称号" }, note: { ko: "정답: ファラオ", en: "Answer: ファラオ" } },
            { title: { ko: "8. ロシア帝国の最後の皇帝", en: "8. ロシア帝国の最後の皇帝" }, note: { ko: "정답: ニコライ2世", en: "Answer: ニコライ2世" } },
            { title: { ko: "9. ローマの政治家ガイウス・ユリウス・カエサルがルビコン川横断の際に発した言葉", en: "9. ローマの政治家ガイウス・ユリウス・カエサルがルビコン川横断の際に発した言葉" }, note: { ko: "정답: 賽は投げられた", en: "Answer: 賽は投げられた" } },
            { title: { ko: "10. アジアの中国一帯において最終的に国を統一した王朝の名前", en: "10. アジアの中国一帯において最終的に国を統一した王朝の名前" }, note: { ko: "정답: 隋", en: "Answer: 隋" } },
          ],
        },
        {
          title: { ko: "雑学王2級 — 정답 10문제", en: "Trivia King Tier 2 — all 10 answers" },
          note: { ko: "수험료 30,000엔 · 첫 합격 보상 상냥함 +20 · 쾌활 +20 · 지성 +20.", en: "Fee ¥30,000; first pass gives Kindness +20, Charisma +20, Intellect +20." },
          puzzles: [
            { title: { ko: "1. GMT（グリニッジ標準時）の基準になったイギリスの天文台", en: "1. GMT（グリニッジ標準時）の基準になったイギリスの天文台" }, note: { ko: "정답: グリニッジ天文台", en: "Answer: グリニッジ天文台" } },
            { title: { ko: "2. 地球のコアと地殻の間にある岩盤層", en: "2. 地球のコアと地殻の間にある岩盤層" }, note: { ko: "정답: マントル", en: "Answer: マントル" } },
            { title: { ko: "3. 日本では一般的な娯楽「カラオケ」の意味", en: "3. 日本では一般的な娯楽「カラオケ」の意味" }, note: { ko: "정답: 演奏者がおらず空である為", en: "Answer: 演奏者がおらず空である為" } },
            { title: { ko: "4. クラシックバレエでバレエ団のトップダンサー", en: "4. クラシックバレエでバレエ団のトップダンサー" }, note: { ko: "정답: プリンシパル", en: "Answer: プリンシパル" } },
            { title: { ko: "5. ポーカーで同じマークのカードが5枚揃う組み合わせ", en: "5. ポーカーで同じマークのカードが5枚揃う組み合わせ" }, note: { ko: "정답: フラッシュ", en: "Answer: フラッシュ" } },
            { title: { ko: "6. トランプカード1セットからジョーカーと予備を除いた枚数", en: "6. トランプカード1セットからジョーカーと予備を除いた枚数" }, note: { ko: "정답: 52枚", en: "Answer: 52枚" } },
            { title: { ko: "7. 近年主に宇宙研究分野においてミクロな物質の原理を紐解く学問の総称", en: "7. 近年主に宇宙研究分野においてミクロな物質の原理を紐解く学問の総称" }, note: { ko: "정답: 量子力学", en: "Answer: 量子力学" } },
            { title: { ko: "8. 地球を含めた太陽系で太陽から最も近い距離にある惑星", en: "8. 地球を含めた太陽系で太陽から最も近い距離にある惑星" }, note: { ko: "정답: 水星", en: "Answer: 水星" } },
            { title: { ko: "9. 絵画「叫び」が有名なノルウェー出身の画家", en: "9. 絵画「叫び」が有名なノルウェー出身の画家" }, note: { ko: "정답: エドヴァルド・ムンク", en: "Answer: エドヴァルド・ムンク" } },
            { title: { ko: "10. 太陽極意・エベレスト・月面着陸・とんぼ返り等の技がある遊び", en: "10. 太陽極意・エベレスト・月面着陸・とんぼ返り等の技がある遊び" }, note: { ko: "정답: けんだま", en: "Answer: けんだま" } },
          ],
        },
        {
          title: { ko: "雑学王1級 — 정답 10문제", en: "Trivia King Tier 1 — all 10 answers" },
          note: { ko: "수험료 50,000엔 · 雑学王2級 합격 후 · 첫 합격 보상 상냥함 +40 · 쾌활 +40 · 지성 +40.", en: "Fee ¥50,000; needs Trivia King Tier 2 first; first pass gives Kindness +40, Charisma +40, Intellect +40." },
          puzzles: [
            { title: { ko: "1. 日本における長さの単位「1尺」の長さ", en: "1. 日本における長さの単位「1尺」の長さ" }, note: { ko: "정답: 30.303センチメートル", en: "Answer: 30.303センチメートル" } },
            { title: { ko: "2. アメリカのバンジージャンプで有名なロイヤル・ゴージ・ブリッジの高さ", en: "2. アメリカのバンジージャンプで有名なロイヤル・ゴージ・ブリッジの高さ" }, note: { ko: "정답: 321m", en: "Answer: 321m" } },
            { title: { ko: "3. 海底から測量して最も高い山（がある島）", en: "3. 海底から測量して最も高い山（がある島）" }, note: { ko: "정답: ハワイ島", en: "Answer: ハワイ島" } },
            { title: { ko: "4. 日本列島の太平洋側で黒潮とぶつかり北アメリカ海流につながる海流", en: "4. 日本列島の太平洋側で黒潮とぶつかり北アメリカ海流につながる海流" }, note: { ko: "정답: 親潮", en: "Answer: 親潮" } },
            { title: { ko: "5. 1基のチェス盤のマス目は何個あるか", en: "5. 1基のチェス盤のマス目は何個あるか" }, note: { ko: "정답: 64個", en: "Answer: 64個" } },
            { title: { ko: "6. 古代ギリシャの哲学者ソクラテスの弟子でイデア論を構築した哲学者", en: "6. 古代ギリシャの哲学者ソクラテスの弟子でイデア論を構築した哲学者" }, note: { ko: "정답: プラトン", en: "Answer: プラトン" } },
            { title: { ko: "7. ドイツの文学者兄弟によるグリム童話に含まれない物語", en: "7. ドイツの文学者兄弟によるグリム童話に含まれない物語" }, note: { ko: "정답: 人魚姫", en: "Answer: 人魚姫" } },
            { title: { ko: "8. チェスでキング以外の他の駒に変化できる駒", en: "8. チェスでキング以外の他の駒に変化できる駒" }, note: { ko: "정답: ポーン", en: "Answer: ポーン" } },
            { title: { ko: "9. 日本列島近郊で隣接し合う4枚のプレートに含まれるもの", en: "9. 日本列島近郊で隣接し合う4枚のプレートに含まれるもの" }, note: { ko: "정답: ユーラシアプレート", en: "Answer: ユーラシアプレート" } },
            { title: { ko: "10. 重さをはかる単位「1ポンド」は何を基に決められたか", en: "10. 重さをはかる単位「1ポンド」は何を基に決められたか" }, note: { ko: "정답: 1人が1日に消費する小麦粉の重さ", en: "Answer: 1人が1日に消費する小麦粉の重さ" } },
          ],
        },
        {
          title: { ko: "雑学王特級 — 정답 10문제", en: "Trivia King Special Tier — all 10 answers" },
          note: { ko: "수험료 100,000엔 · 雑学王1級 합격 후 · 첫 합격 보상 상냥함 +50 · 쾌활 +50 · 지성 +50.", en: "Fee ¥100,000; needs Trivia King Tier 1 first; first pass gives Kindness +50, Charisma +50, Intellect +50." },
          puzzles: [
            { title: { ko: "1. 21世紀において北極星と呼ばれている2等星の名前", en: "1. 21世紀において北極星と呼ばれている2等星の名前" }, note: { ko: "정답: ポラリス", en: "Answer: ポラリス" } },
            { title: { ko: "2. 以下のうち大海原資格学校で取得できる資格", en: "2. 以下のうち大海原資格学校で取得できる資格" }, note: { ko: "정답: 音楽検定2級", en: "Answer: 音楽検定2級" } },
            { title: { ko: "3. 将棋やチェスの起源とされる古代インドのボードゲーム", en: "3. 将棋やチェスの起源とされる古代インドのボードゲーム" }, note: { ko: "정답: チャトランガ", en: "Answer: チャトランガ" } },
            { title: { ko: "4. 星座「こと座」を形成し、織姫の星として知られる1等星の名前", en: "4. 星座「こと座」を形成し、織姫の星として知られる1等星の名前" }, note: { ko: "정답: ベガ", en: "Answer: ベガ" } },
            { title: { ko: "5. 日本で紙幣（貨幣）を印刷・製造している機関", en: "5. 日本で紙幣（貨幣）を印刷・製造している機関" }, note: { ko: "정답: 国立印刷局", en: "Answer: 国立印刷局" } },
            { title: { ko: "6. 大海原資格学校の校章に描かれている組み合わせ", en: "6. 大海原資格学校の校章に描かれている組み合わせ" }, note: { ko: "정답: 大海原とペン", en: "Answer: 大海原とペン" } },
            { title: { ko: "7. 地球で1番高い山はエベレスト、2番目に高い山の名前", en: "7. 地球で1番高い山はエベレスト、2番目に高い山の名前" }, note: { ko: "정답: K2", en: "Answer: K2" } },
            { title: { ko: "8. 「世界最古のボードゲーム」のひとつとされ、膨大な種類のルールで遊ばれているボードゲーム", en: "8. 「世界最古のボードゲーム」のひとつとされ、膨大な種類のルールで遊ばれているボードゲーム" }, note: { ko: "정답: マンカラ", en: "Answer: マンカラ" } },
            { title: { ko: "9. 日本の昔話「竹取物語」において、かぐや姫が貴族に要求した宝に含まれないもの", en: "9. 日本の昔話「竹取物語」において、かぐや姫が貴族に要求した宝に含まれないもの" }, note: { ko: "정답: 鳳凰の尾羽", en: "Answer: 鳳凰の尾羽" } },
            { title: { ko: "10. 日本で1回の会計で使っても問題ない1円玉の最大枚数", en: "10. 日本で1回の会計で使っても問題ない1円玉の最大枚数" }, note: { ko: "정답: 20枚", en: "Answer: 20枚" } },
          ],
        },
      ],
    },
  ],
};

