import type { MinigamesData } from "./types";

const YT = (id: string) => `https://www.youtube.com/watch?v=${id}`;

// Minigame guides for Yakuza Kiwami. Completion-list rows, thresholds and the
// cheat-item locker numbers are taken from CyricZ's GameFAQs guide, cited on
// each entry, rather than written from memory.
export const yakuzaKiwamiMinigames: MinigamesData = {
  appId: 3717330,
  intro: {
    ko: "Yakuza Kiwami는 카무로초 한 곳에 미니게임이 몰려 있어 컴플리션이 비교적 집약적입니다. 「놀이를 제패한 남자」 트로피는 아래 종목을 모두 건드려야 하고, 포켓 서킷·메스킹은 전용 트로피가 따로 있습니다. 도박 계열은 코인로커에서 나오는 이카사마 아이템을 먼저 챙기면 난이도가 통째로 사라집니다.",
    en: "Yakuza Kiwami keeps every minigame inside one Kamurocho, so the grind is concentrated. 'What a Player' wants a go at all of them, and Pocket Circuit and MesuKing carry their own trophies. The gambling rows stop being gambling once you have collected the cheat items out of the coin lockers.",
  },
  minigames: [
    {
      slug: "mahjong",
      name: { ko: "마작", en: "Mahjong" },
      category: { ko: "도박·보드", en: "Gambling / board" },
      difficulty: 5,
      location: { ko: "카무로초 — 마작 라라바이", en: "Mahjong Jansou, Kamurocho" },
      summary: {
        ko: "컴플리션 조건이 여섯 줄로 가장 깁니다. 10회 화료, 만관 5회, 하네만 1회, 리치 일발 1회, 잇쓰(일기통관) 1회, 그리고 누적 100,000점봉.",
        en: "Six completion rows, the longest set here: go out 10 times, five mangan, one haneman, one riichi ippatsu, one full straight, and 100,000 sticks banked.",
      },
      howTo: [
        { ko: "이카사마 「행운의 패」는 코인로커 I2에 있습니다. 국사무쌍이 통째로 배패되므로 하네만과 점수 조건을 한 번에 해결할 수 있습니다.", en: "The Lucky Tile cheat sits in Locker I2. It deals you Thirteen Orphans outright, which clears the haneman row and a big chunk of the points at once." },
        { ko: "다만 「행운의 패」로는 리치 일발을 못 만듭니다. 국사무쌍 같은 역만은 일발을 비롯한 다른 판정을 덮어쓰기 때문에, 리치 일발 줄은 평범한 손으로 따로 노려야 합니다.", en: "It cannot do riichi ippatsu, though — a yakuman like Thirteen Orphans overrides ippatsu and other minor yaku, so that row needs an ordinary hand." },
        { ko: "잇쓰는 한 색으로 123·456·789를 모으는 역입니다. 배패에 같은 색 숫자가 다섯 종류 이상 있을 때만 노리고, 치는 세 뭉치 중 하나를 완성할 때만 쓰세요. 다른 조합을 치면 역이 사라집니다.", en: "Full straight wants 123, 456 and 789 in one suit. Only chase it when the deal already has five or more numbers of a suit, and only chi to complete one of those three runs — any other chi kills the yaku." },
        { ko: "장비까지 노린다면 랭킹 매치가 있습니다. 참가비 50,000엔은 최초 1회뿐이고 이후 무료이며, 1위는 2랭크·2위는 1랭크 상승, 4위는 1랭크 하락입니다. 판이 나쁘면 중단해도 벌점이 없습니다.", en: "For the gear, Ranking Match costs a one-off ¥50,000 buy-in and is free afterwards: first place moves you up two ranks, second one, fourth drops you one — and quitting a bad game costs nothing." },
        { ko: "랭킹 보상은 25위 터프니스 인피니티, 20위 스태미난 스파크, 15위 사롱, 10위 쌍절 중국도, 5위 두목의 목도리, 3위 연꽃회 청룡도, 1위 드래곤 드라이버입니다.", en: "Rank rewards: 25 Toughness Infinity, 20 Staminan Spark, 15 Sarong, 10 Double Chinese Broadswords, 5 Head Honcho Scarf, 3 Lotus Clan Broadsword, 1 Dragon Driver." },
      ],
      videos: [
        { title: { ko: "마작 입문 가이드 (Yakuza)", en: "An amateur's guide to mahjong (Yakuza)" }, url: YT("UrYyaBMiIcw") },
        { title: { ko: "리치 일발 등 100% 마작 공략", en: "Mahjong 100% guide (Riichi Ippatsu, etc.)" }, url: YT("nhFoL6ZSI7k") },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Mahjong (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/mahjong" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "shogi",
      name: { ko: "쇼기 (장기)", en: "Shogi" },
      category: { ko: "도박·보드", en: "Gambling / board" },
      difficulty: 3,
      location: { ko: "카무로초 센료 거리 — 장기 도장 「쇼텐(将天)」, 1판 500엔", en: "Shoten shogi parlour, Senryo Avenue, Kamurocho — ¥500 a game" },
      summary: {
        ko: "컴플리션은 「무르기 없이 승리」 1회·3회·5회 세 줄뿐입니다. 규칙을 몰라도 코인로커 J3의 아이템 하나로 전부 끝낼 수 있습니다.",
        en: "Three rows: win without a take-back once, three times, five times. You do not need to know shogi — one item from Locker J3 covers all three.",
      },
      howTo: [
        { ko: "코인로커 J3의 「투료의 말(参った駒)」을 대국 중 아무 때나 쓰면 상대가 즉시 투료합니다. 무르기를 안 쓴 승리로 잡히므로 세 줄을 이걸로 채울 수 있습니다.", en: "The Give-Up Piece (参った駒) in Locker J3 makes the opponent resign instantly whenever you use it, and it counts as a win with no take-back — so it clears all three rows." },
        { ko: "모드는 순위전과 「시련 답파(試練踏破, 영문판 Shogi Challenge)」 1~10·최종 11판입니다. 시련 답파는 특수한 초기 배치에서 CPU와 끝까지 두는 대국이고, 정해진 수로 끝나는 쓰메쇼기(詰将棋) 모드는 이 작품에 없습니다.", en: "The modes are ranked games and the Shogi Challenges (試練踏破) — eleven of them, 1–10 plus a final. Each is a full game against the CPU from a special starting position; this game has no tsume-shogi (fixed mate puzzle) mode." },
        { ko: "승리 포인트는 대전 포인트 + 待った 남은 횟수×50(최대 150) + 超待った 미사용 시 100입니다. 시련 답파의 대전 포인트는 1번 100에서 10번 1,000까지 100씩 오르고 최종이 2,000이라, 무르기 없이 이기면 9번이 한 판 1,150pt(900+250)입니다.", en: "A win pays the match points + 50 per unused take-back (up to 150) + 100 if you never used the super take-back. Challenge match points run 100 for No. 1 up to 1,000 for No. 10 and 2,000 for the final, so a clean win on No. 9 pays 1,150 (900 + 250)." },
        { ko: "경품은 동 접시 100pt, 은 접시 1,200pt, 금 접시 8,500pt, 플래티넘 접시 12,000pt, 무기 「드래곤 슬레이어(龍殺し)」 100,000pt입니다. 드래곤 슬레이어는 10장 이후에 교환 목록에 추가되고, 100% 컴플리션에는 필요 없습니다.", en: "Prizes: copper plate 100, silver plate 1,200, gold plate 8,500, platinum plate 12,000, and the Dragon Slayer at 100,000 points. The Dragon Slayer joins the list from Chapter 10 and is not needed for 100% completion." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Shogi (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/shogi" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
        { label: "ダラゲ！ — 龍が如く 極 将棋（試練踏破の棋譜）", url: "https://darage.com/guide/ryukiwami1/mini07.html" },
        { label: "龍が如く極 攻略通信Wiki — 将棋", url: "https://kouryakutsushin.com/ryu-kiwami/%E5%B0%86%E6%A3%8B" },
        { label: "神ゲー攻略 — 龍が如く極 将棋", url: "https://kamigame.jp/ryugagotokukiwami/page/339675020651407753.html" },
      ],
      puzzleSets: [
        {
          title: { ko: "시련 답파(試練踏破) 수순 — 11판", en: "Shogi Challenge lines — all 11" },
          note: { ko: "시련 답파는 CPU와 끝까지 두는 대국이라, 아래 수순은 출처가 그대로 따라 두었을 때의 기록입니다. CPU가 다른 수를 두면 待った로 되돌리거나 다시 시작하세요(같은 수를 두면 대체로 같은 응수가 옵니다). ▲가 플레이어, △가 CPU입니다. 1~10번은 ダラゲ!(K-Shogi로 둔 결과) 단일 출처, 최종은 攻略通信Wiki 단일 출처라 서로 대조할 수 있는 판은 없습니다. 그림은 ダラゲ!의 것으로 3·5~10번은 초기 배치도, 4번은 단계별 그림이고, 1·2번은 글 설명밖에 없어 영상을 함께 붙였습니다. 판 제목의 포인트는 대전 포인트이고, 무르기 없이 이기면 +250이 붙습니다.", en: "Challenges are full games against the CPU, so these are the lines the sources actually played. If the CPU deviates, take back (待った) or restart — the same moves usually draw the same replies. ▲ is you, △ the CPU. Nos. 1–10 come from Darage (played out with K-Shogi) and the final from Kouryaku Tsushin Wiki — each single-source, so there is nothing to cross-check them against. Diagrams are Darage's: starting positions for Nos. 3 and 5–10, step-by-step for No. 4; Nos. 1 and 2 only have prose, so a video is attached. Points in each title are match points; a win without take-backs adds 250." },
          puzzles: [
            { title: { ko: "1번 (대전 100pt)", en: "No. 1 (100 pt)" }, note: { ko: "해설은 글 순서만 있고 기보는 없습니다. 비차를 오른쪽 끝으로 → 상대 보 줄까지 올려 용왕으로 승격 → 상대 보 뒤로 → 보를 잡고 → 왼쪽 끝으로 가서 장군 → 한 칸 오른쪽으로 장군 → 한 칸 위로 올리면 외통. 같은 순서로 두면 CPU도 매번 같은 수로 응수합니다.", en: "Prose only, no kifu: rook to the far right → up to the enemy pawn row and promote → behind the enemy pawns → take a pawn → far left for check → one square right, check → one square up for mate. Play the same moves and the CPU answers the same way every time." }, video: YT("-_CKsJgSxes") },
            { title: { ko: "2번 (대전 200pt)", en: "No. 2 (200 pt)" }, note: { ko: "해설은 글 순서만 있고 기보는 없습니다. 비차를 오른쪽으로 2칸 → 위로 올려 상대 보를 잡고 → 맨 위까지 올라가 용왕으로 승격 → 왼쪽 아래 대각으로 장군 → 왼쪽으로 3칸 → 상대 옥의 오른쪽 아래 칸에 보를 놓고 → 그 보를 올려 と금으로 승격하면 외통.", en: "Prose only, no kifu: rook two squares right → up to take the enemy pawn → to the top row and promote → diagonally down-left for check → three squares left → drop a pawn diagonally below-right of the enemy king → push it and promote for mate." }, video: YT("oqFnA9eQuXc") },
            { title: { ko: "3번 (대전 300pt)", en: "No. 3 (300 pt)" }, image: "/yakuza-kiwami-shogi/trial-3.webp", moves: ["▲４八玉", "△６一玉", "▲３七玉", "△７一玉", "▲３六玉", "△８二玉", "▲３五玉", "△３三桂", "▲３四玉", "△２五桂", "▲同　玉", "△７三桂", "▲８七金", "△６五桂", "▲７六金", "△５七桂成", "▲３四玉", "△９七香成", "▲４三玉", "△４七歩打", "▲８五金", "△４八歩成", "▲８四金", "△３八と", "▲２七銀", "△１七香成", "▲３八銀", "△２八成香", "▲３七銀", "△２七成香", "▲４六銀", "△５六成桂", "▲４五銀", "△５五成桂", "▲４四銀", "△８三歩打", "▲９四桂打", "△７二玉", "▲７四金", "△４五成桂", "▲５三銀成", "△２六成香", "▲７三歩打", "△７一玉", "▲８三金", "△６一玉", "▲５二成銀", "△７一玉", "▲８二桂成"] },
            { title: { ko: "4번 (대전 400pt)", en: "No. 4 (400 pt)" }, image: "/yakuza-kiwami-shogi/trial-4-step-1.webp", images: ["/yakuza-kiwami-shogi/trial-4-step-2.webp", "/yakuza-kiwami-shogi/trial-4-step-3.webp"], note: { ko: "그림 순서대로 둡니다. 비차를 그림 위치에 놓아 장군 → 한 칸 아래로 내려 용왕으로 승격 → 용왕을 대각으로 몰아가고 → 마지막에 상대 옥의 대각 아래에 금을 놓으면 외통. 한 판 650pt로 포인트 벌이에 좋습니다.", en: "Follow the diagrams: drop the rook where shown for check → down one square and promote → walk the dragon diagonally → finish by dropping a gold diagonally below the enemy king. 650 points a run, a good farming option." } },
            { title: { ko: "5번 (대전 500pt)", en: "No. 5 (500 pt)" }, image: "/yakuza-kiwami-shogi/trial-5.webp", moves: ["▲７八飛", "△５二金", "▲４八玉", "△７二銀", "▲７六飛", "△４二玉", "▲３八玉", "△３二玉", "▲１六飛", "△２二玉", "▲３六飛", "△９四歩", "▲１六歩", "△９五歩", "▲１五歩", "△９六歩", "▲１四歩", "△９七歩成", "▲１三歩成", "△２一玉", "▲１二と"] },
            { title: { ko: "6번 (대전 600pt)", en: "No. 6 (600 pt)" }, image: "/yakuza-kiwami-shogi/trial-6.webp", moves: ["▲６八玉", "△６一玉", "▲５七玉", "△４一金", "▲４五歩", "△７二金", "▲４四歩", "△５二金", "▲５四銀", "△７一玉", "▲４三歩成", "△６二金左", "▲４六玉", "△８二玉", "▲５五玉", "△６一金", "▲６五歩", "△９一玉", "▲６四歩", "△６二金上", "▲５三と", "△６一金", "▲６三歩成", "△７一金引", "▲５二と直", "△同　金", "▲同　と", "△５七歩打", "▲６三銀", "△５八歩成", "▲６二と", "△８二金", "▲７二と", "△９二金", "▲８一金打"] },
            { title: { ko: "7번 (대전 700pt)", en: "No. 7 (700 pt)" }, image: "/yakuza-kiwami-shogi/trial-7.webp", moves: ["▲７四歩", "△２七歩成", "▲７六玉", "△９八角打", "▲７五玉", "△１八歩成", "▲７三歩成", "△３六歩", "▲８三歩成", "△３七歩成", "▲６五歩", "△４八と", "▲６二と", "△８九角成", "▲７六金", "△５八と", "▲７七銀", "△７九馬", "▲６四歩", "△５七馬", "▲７四玉", "△３八歩打", "▲同　歩", "△３七歩打", "▲同　歩", "△４七馬", "▲８四玉", "△７二歩", "▲６三歩成", "△４八馬", "▲６六銀", "△３七と", "▲９二歩成", "△５四歩", "▲９四歩打", "△９六歩打", "▲９三歩成", "△９七歩成", "▲５三と", "△５五歩", "▲７四歩打", "△５六歩", "▲７二と寄", "△５七歩成", "▲７三歩成", "△５六と", "▲７五銀", "△１七と", "▲６四歩打", "△１六と", "▲６三歩成", "△３六と", "▲７四と", "△３七馬", "▲８六銀", "△８七と", "▲８五銀", "△１五と", "▲７五と", "△５七と引", "▲９六銀", "△９七と", "▲９五銀", "△９六と", "▲９四銀", "△４七と寄", "▲８五玉", "△８七と", "▲７四玉", "△５五馬", "▲６四と引", "△７七と", "▲６五と寄", "△７六と", "▲５五と", "△同　と", "▲５一角打", "△２二玉", "▲１五角成", "△３五と", "▲２四馬", "△３四金打", "▲２三歩打", "△１二玉", "▲１三歩打", "△１一玉", "▲３四馬", "△７三歩打", "▲同　玉", "△３四と", "▲２二金打"] },
            { title: { ko: "8번 (대전 800pt)", en: "No. 8 (800 pt)" }, image: "/yakuza-kiwami-shogi/trial-8.webp", moves: ["▲１一飛成", "△５一銀", "▲４二歩打", "△８五金", "▲４一歩成", "△５二銀", "▲５一と", "△同　金", "▲同　龍", "△４三銀", "▲６一金打", "△２八歩打", "▲６五角", "△２九歩成", "▲同　玉", "△３四銀", "▲７一金", "△同　金", "▲同　龍", "△９七香成", "▲７二金打", "△１八金打", "▲同　玉", "△９六成香", "▲８一龍"] },
            { title: { ko: "9번 (대전 900pt)", en: "No. 9 (900 pt)" }, image: "/yakuza-kiwami-shogi/trial-9.webp", moves: ["△７七角成", "▲６八歩打", "△３二金", "▲２三角成", "△同　金", "▲同　飛成", "△１二角打", "▲２七龍", "△３三馬", "▲２二歩打", "△１五馬", "▲４八歩打", "△３三桂", "▲２一歩成", "△４五角", "▲２二龍", "△１二香", "▲４二龍", "△同　玉", "▲３一銀打", "△４一玉", "▲４二金打"], note: { ko: "이 판은 CPU(△)가 먼저 둡니다. CPU가 7수째에 각을 놓지 않고 계마를 움직이면 아래 「9번 — 7수째 계마 패턴」으로 넘어가세요. 한 판 1,150pt로 포인트 벌이 최적입니다.", en: "The CPU (△) moves first here. If it moves a knight instead of dropping the bishop on move 7, switch to the 'No. 9 — knight on move 7' line below. 1,150 points a run, the best farming option." } },
            { title: { ko: "9번 — 7수째 계마 패턴", en: "No. 9 — knight on move 7" }, moves: ["△７七角成", "▲６八歩打", "△３二金", "▲２三角成", "△同　金", "▲同　飛成", "△３三桂", "▲３二金打", "△３七角打", "▲５八玉", "△７六馬", "▲４七玉", "△５五角成", "▲２一龍", "△３一銀", "▲同　龍", "△５二玉", "▲４二金"], note: { ko: "드물게 CPU가 9수째에도 계마를 연달아 움직이면, 중간 수를 건너뛰고 용왕을 ２一로 옮기면 됩니다.", en: "Rarely the CPU moves a knight again on move 9; if so, skip ahead and move the dragon to 2-1." } },
            { title: { ko: "10번 (대전 1,000pt)", en: "No. 10 (1,000 pt)" }, image: "/yakuza-kiwami-shogi/trial-10.webp", moves: ["▲３一銀打", "△３三銀", "▲２五歩", "△同　歩", "▲４二銀成", "△同　玉", "▲６八玉", "△２四銀", "▲６九角", "△１五歩", "▲同　歩", "△同　香", "▲４七飛", "△１八香成", "▲４五歩", "△１六歩打", "▲４四歩", "△５二金", "▲４三金打", "△４一玉", "▲５三金打", "△５一金", "▲４二金直", "△同　金", "▲４三歩成", "△３一玉", "▲４二と", "△２一玉", "▲１三歩打", "△５三飛", "▲３一金打", "△１一玉", "▲３二と", "△１三銀", "▲２一金", "△１二玉", "▲１一金", "△同　玉", "▲４一飛成", "△３一銀打", "▲同　龍", "△１二玉", "▲２一龍"], note: { ko: "CPU 사고 시간이 길어서 포인트 벌이에는 맞지 않습니다.", en: "The CPU thinks for a long time here, so it is a poor farming choice." } },
            { title: { ko: "최종 (대전 2,000pt)", en: "Final (2,000 pt)" }, moves: ["▲4八玉", "△8四と(9三のもの)", "▲5九香打", "△2四と(1三のもの)", "▲3七玉", "△1七香成", "▲2六玉", "△2八成香", "▲3七玉", "△3九成香", "▲4八玉", "△9三桂", "▲3九玉", "△8五桂", "▲8六銀打", "△9七香成", "▲5八香打", "△8七成香", "▲8五銀", "△8五(同じく)と", "▲6五桂打", "△5四と(4三のもの)", "▲5三桂成", "△5三(同じく)と(6三のもの)", "▲5四香", "△4三と", "▲5三香成", "△5三(同じく)と", "▲5三香成", "△6六馬", "▲2八玉", "△7五馬", "▲4三桂打"], note: { ko: "이 수순만 攻略通信Wiki에서 가져왔고 그림은 없습니다. 출처는 재현성을 확인했다고 적었지만, CPU가 다른 수를 두면 待った나 재도전으로 다시 맞추세요. 괄호 안 메모(9三のもの 등)는 어느 말을 움직이는지 원문이 덧붙인 것입니다.", en: "This line comes from Kouryaku Tsushin Wiki and has no diagram. The source says it reproduces reliably, but if the CPU deviates, take back (待った) or retry. The bracketed notes (9三のもの etc.) are the source's own markers for which piece moves." } },
          ],
        },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "gambling-hall",
      name: { ko: "도박장 (초한·주사위·코이코이·오이초카부)", en: "Gambling Hall (cho-han, cee-lo, koi-koi, oicho-kabu)" },
      category: { ko: "도박·보드", en: "Gambling / board" },
      difficulty: 2,
      location: { ko: "카무로초 — 지하 연옥 도박장", en: "The gambling den in Underground Purgatory" },
      summary: {
        ko: "네 종목 각각 누적 10,000점 획득이 조건입니다. 이카사마 아이템을 먼저 챙기면 도박이 아니라 작업이 됩니다.",
        en: "Each of the four wants 10,000 banked. Pick the cheat items up first and it stops being gambling.",
      },
      howTo: [
        { ko: "초한 이카사마는 코인로커 E4의 「짝수 고로의 염주」와 F3의 「기울어진 담배」입니다. 염주는 다음 한 판만 반드시 짝수로 만들고, 담배는 다른 손님들의 베팅을 한쪽으로 몰아 줍니다.", en: "Cho-han uses Even Goro's Beads (Locker E4) and the Lopsided Cigarette (Locker F3). The beads force the very next roll even; the cigarette skews the other punters' bets to one side." },
        { ko: "초한은 처음에 최대 100장까지만 걸 수 있고, 이기면 상한이 단계적으로 1,000장까지 오릅니다. 다만 상한이 오르려면 한 번 나갔다 들어와야 반영되니, 5연승쯤 하면 자리를 뜼다 돌아오세요.", en: "Cho-han starts capped at 100 tags and the ceiling climbs to 1,000 as you win — but it only updates when you leave and come back, so step out every five wins or so." },
        { ko: "염주는 딜러와 직접 붙는 판(친 승부)에서 베팅 상한이 올라간 뒤에 쓰는 게 가장 이득입니다. 상한 100장에서 쓰면 아깝습니다.", en: "Save the beads for a direct bet against the house after the ceiling has risen — spending one at a 100-tag cap wastes it." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Cho-han (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/cho-han" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "casino",
      name: { ko: "카지노 (블랙잭·포커·바카라·룰렛)", en: "Casino (blackjack, poker, baccarat, roulette)" },
      category: { ko: "도박·보드", en: "Gambling / board" },
      difficulty: 2,
      location: { ko: "카무로초 — 지하 연옥 카지노", en: "The casino in Underground Purgatory" },
      summary: {
        ko: "컴플리션 조건은 포커 누적 20,000, 블랙잭 50,000, 바카라 20,000, 룰렛 50,000입니다. 블랙잭 이카사마 두 개면 나머지 자금까지 한 번에 벌립니다.",
        en: "Rows are 20,000 in poker, 50,000 in blackjack, 20,000 in baccarat and 50,000 in roulette. Two blackjack cheats bankroll the rest of them.",
      },
      howTo: [
        { ko: "블랙잭 이카사마는 코인로커 G3의 「블랙잭의 부적」과 G4의 「버스트의 부적」입니다. 고레이트 탁에 칩 1,000장 이상을 들고 앉아 먼저 버스트의 부적을 쓰면 딜러가 5판 연속 버스트합니다.", en: "The Blackjack Amulet is in Locker G3 and the Bust Amulet in G4. Sit at high stakes with 1,000+ chips and use the Bust Amulet first: the dealer busts five hands in a row." },
        { ko: "버스트의 부적은 딜러가 두 장으로 17 이상이면 더 뽑지 않아 무효가 됩니다. 그래도 5판이면 베팅 상한이 10,000까지 올라가므로, 그때 블랙잭의 부적을 써서 5연속 블랙잭을 받으면 칩이 넘칩니다.", en: "It fizzles when the dealer stands on 17 from two cards, but five wins still pushes the bet ceiling to 10,000 — then the Blackjack Amulet gives five blackjacks in a row and the chips pile up." },
        { ko: "블랙잭 베팅 상한은 연승에 따라 오릅니다. 1승이면 저레이트 300·고레이트 3,000, 2연승이면 500·5,000, 3연승부터 1,000·10,000이며 한 번 지면 초기화됩니다.", en: "Blackjack raises your cap on a streak: one win allows 300 low or 3,000 high, two wins 500 or 5,000, three or more 1,000 or 10,000 — and one loss resets it." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Blackjack (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/blackjack" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "pool",
      name: { ko: "당구", en: "Pool" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "카무로초 — 클럽 세가 등 당구장", en: "The pool hall in Kamurocho" },
      summary: {
        ko: "컴플리션은 콤비네이션 샷 3회와 캐롬 샷 3회뿐입니다. 경기에서 이길 필요도, 퍼즐 풀을 건드릴 필요도 없습니다.",
        en: "Completion is three combination shots and three carom shots. You never have to win a game, and Puzzle Pool is not required at all.",
      },
      howTo: [
        { ko: "캐롬은 큐볼이 목적구를 맞힌 뒤 다시 다른 공을 맞혀 그 공이 들어가는 샷이고, 콤비네이션은 목적구가 다른 공을 맞혀 그 공이 들어가는 샷입니다. 이 둘을 각각 3회씩입니다.", en: "A carom is cue -> object ball -> another ball, and that other ball drops. A combination is cue -> object ball -> another ball, where the object ball did the hitting. Three of each." },
        { ko: "실전에서 우연히 나오길 기다리지 말고 「혼자 플레이」로 나인볼을 고르세요. 공을 마음대로 밀어 배치를 만들고, 큐볼을 일부러 포켓에 넣어 스크래치를 내면 원하는 자리에 큐볼을 놓을 수 있습니다.", en: "Do not wait for these in a match: choose Play Alone and Nine-ball, nudge the balls into the shape you want, then scratch on purpose to place the cue ball wherever you like." },
        { ko: "퍼즐 풀은 검은 공을 맞히면 실패이고 노란 공은 도움용입니다. 컴플리션과 무관하니 시간이 없다면 건너뛰어도 됩니다.", en: "In Puzzle Pool touching a black ball fails the puzzle and the yellow balls are optional help — none of it counts for completion, so skip it if you are short on time." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Pool (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/pool" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "darts",
      name: { ko: "다트", en: "Darts" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "카무로초 — 클럽 세가", en: "Club SEGA, Kamurocho" },
      summary: {
        ko: "컴플리션은 해트트릭 10회 하나뿐입니다. 해트트릭은 한 라운드에 세 발을 모두 BULL에 넣는 것입니다.",
        en: "One row: ten hat-tricks. A hat-trick is all three darts in the bull in a single round.",
      },
      howTo: [
        { ko: "901 게임을 혼자 골라 두면 시간 제한 없이 20라운드를 BULL만 노릴 수 있습니다. 대전을 기다리는 것보다 훨씬 빠릅니다.", en: "Start a 901 game alone: that is twenty rounds of aiming at nothing but the bull, at your own pace." },
        { ko: "던지기는 왼쪽 스틱으로 조준 → 오른쪽 스틱을 아래로 당김 → 놓기입니다. 가장자리까지가 아니라 절반쯤까지만 천천히 당겼다가 빠르게 놓는 것이 정확합니다.", en: "Aim with the left stick, pull the right stick down, release to throw. Pull slowly to about halfway rather than to the edge, then release quickly — that lands on target." },
        { ko: "조준을 끝내기 전에 당기지 마세요. 왼쪽 스틱을 가만히 둬도 손이 미세하게 흔들리므로, 조준이 맞은 순간에 당겨야 합니다.", en: "Do not pull back before you are on target: the hand wavers even with the stick still, so commit at the moment the aim is right." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Darts (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/darts" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "bowling",
      name: { ko: "볼링", en: "Bowling" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "카무로초 — 마하볼", en: "Mach Bowl, Kamurocho" },
      summary: {
        ko: "컴플리션은 스트라이크 10회와 스플릿 게임 누적 5프레임입니다. 일반 게임보다 스플릿 게임 쪽이 조건이 까다롭습니다.",
        en: "Two rows: ten strikes, and five frames cleared across Split Games. The split side is the harder half.",
      },
      howTo: [
        { ko: "스트라이크는 1번 핀 바로 옆의 「포켓」을 노려야 합니다. 공을 세게 넣으면서 약간의 스핀을 주면 확률이 크게 올라갑니다.", en: "Strikes come from the pocket — just beside the head pin. Hit it hard with a little spin and the odds jump." },
        { ko: "조작은 방향키 위아래로 공 선택(가벼운 공은 제어가 쉽고 무거운 공은 힘이 셉니다), 좌우로 서는 위치 선택, ×로 방향 결정, ×로 파워 결정, 마지막에 던지는 동안 왼쪽 스틱을 살짝 기울여 스핀을 겁니다. 스핀은 매우 민감하니 조금만 움직이세요.", en: "Up/down picks the ball (light is controllable, heavy has power), left/right your stance, cross sets direction then power, and a gentle left-stick nudge during the approach adds spin — it is very sensitive, so barely move it." },
        { ko: "스플릿 게임은 열 가지 핀 조합 중에서 골라 한 번의 투구로 그 조합을 모두 쓰러뜨리는 방식입니다. 공은 3개뿐이고 실패할 때마다 하나씩 줄어듭니다.", en: "Split Game gives ten pin combinations; each must go down in a single throw. You have a stock of three balls and every miss costs one." },
        { ko: "스플릿 게임 보상은 전부 포켓 서킷 부품입니다. 3프레임에서 선샤인 데칼, 5프레임에서 엑스트라 스피드 프레임, 7프레임에서 울트라 소프트 타이어가 나옵니다.", en: "Split Game prizes are all Pocket Circuit parts: three frames gives the Sunshine Decal, five the Extra Speed Frame, seven the Ultra Soft Tires." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Bowling (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/bowling" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "batting-center",
      name: { ko: "배팅 센터", en: "Batting Center" },
      category: { ko: "스포츠", en: "Sports" },
      difficulty: 3,
      location: { ko: "카무로초 — 요시다 배팅 센터", en: "Yoshida Batting Center, Kamurocho" },
      summary: {
        ko: "컴플리션은 다섯 줄입니다. 투 패널 녹아웃 10회, 그리고 이지·노멀·하드·엑스트라 하드 각 코스에서 1,600점 이상.",
        en: "Five rows: ten Two-Panel Knock-outs, and 1,600 points on each of Easy, Normal, Hard and Extra Hard.",
      },
      howTo: [
        { ko: "1,600점은 A랭크 라인입니다. 각 난이도의 랭크 보상은 B(1,200점)·A(1,600점)·S(1,800점)로 나뉘고, 엑스트라 하드 S에서 터프니스 인피니티가 나옵니다.", en: "1,600 is the A-rank line. Each course pays out at B (1,200), A (1,600) and S (1,800) — Extra Hard at S gives Toughness Infinity." },
        { ko: "구질과 구속은 코스별로 완전히 고정입니다. 하드와 엑스트라 하드는 20구 배열이 사실상 같으므로, 하드에서 익힌 타이밍이 그대로 통합니다.", en: "Pitch types and speeds are fixed per course, and Hard and Extra Hard use effectively the same twenty-pitch script — the timing you learn on Hard carries straight over." },
        { ko: "스트레이트는 110~130km/h, 커브는 60~100km/h, 싱커는 70~110km/h대로 갈립니다. 느린 커브에서 타이밍을 당기지 않는 것이 점수를 지키는 핵심입니다.", en: "Straights sit at 110-130 km/h, curves at 60-100 and sinkers at 70-110 — not rushing the slow curves is what protects the score." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Batting Center (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/batting-center" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
        { label: "ゲーム攻略マン — 龍が如く極 バッティングセンター", url: "https://dswiipspwikips3.jp/yakuza-kiwami/playspot/batting-center.html" },
      ],
      achievementSlug: "23_what_a_player",
      courses: [
        {
          title: { ko: "이지", en: "Easy" },
          note: { ko: "위치는 자유 조준 — 구질·구속만 고정", en: "Free-aim — pitch type/speed fixed, landing spot is your choice" },
          pitches: [
            { type: "Straight", speed: "80" }, { type: "Curve", speed: "78" }, { type: "Sinker", speed: "73" }, { type: "Curve", speed: "68" }, { type: "Straight", speed: "115" },
            { type: "Curve", speed: "78" }, { type: "Curve", speed: "65" }, { type: "Straight", speed: "116" }, { type: "Straight", speed: "108" }, { type: "Sinker", speed: "72" },
            { type: "Curve", speed: "77" }, { type: "Straight", speed: "117" }, { type: "Curve", speed: "67" }, { type: "Straight", speed: "113" }, { type: "Straight", speed: "88" },
            { type: "Straight", speed: "114" }, { type: "Curve", speed: "76" }, { type: "Straight", speed: "101" }, { type: "Straight", speed: "113" }, { type: "Curve", speed: "74" },
          ],
        },
        {
          title: { ko: "노멀", en: "Normal" },
          note: { ko: "위치는 자유 조준 — 구질·구속만 고정", en: "Free-aim — pitch type/speed fixed, landing spot is your choice" },
          pitches: [
            { type: "Straight", speed: "128" }, { type: "Sinker", speed: "84" }, { type: "Curve", speed: "74" }, { type: "Straight", speed: "128" }, { type: "Straight", speed: "81" },
            { type: "Sinker", speed: "87" }, { type: "Straight", speed: "128" }, { type: "Curve", speed: "61" }, { type: "Straight", speed: "125" }, { type: "Sinker", speed: "105" },
            { type: "Curve", speed: "81" }, { type: "Straight", speed: "122" }, { type: "Curve", speed: "61" }, { type: "Sinker", speed: "82" }, { type: "Straight", speed: "120" },
            { type: "Curve", speed: "68" }, { type: "Straight", speed: "127" }, { type: "Straight", speed: "107" }, { type: "Sinker", speed: "100" }, { type: "Straight", speed: "142" },
          ],
        },
        {
          title: { ko: "하드", en: "Hard" },
          note: { ko: "위치는 자유 조준 — 구질·구속만 고정. 엑스트라 하드와 사실상 같은 20구 배열", en: "Free-aim — same 20-pitch script as Extra Hard in practice" },
          pitches: [
            { type: "Straight", speed: "121" }, { type: "Sinker", speed: "88" }, { type: "Straight", speed: "88" }, { type: "Curve", speed: "85" }, { type: "Straight", speed: "122" },
            { type: "Sinker", speed: "106" }, { type: "Straight", speed: "124" }, { type: "Straight", speed: "83" }, { type: "Straight", speed: "126" }, { type: "Sinker", speed: "83" },
            { type: "Sinker", speed: "77" }, { type: "Straight", speed: "112" }, { type: "Straight", speed: "105" }, { type: "Curve", speed: "84" }, { type: "Straight", speed: "117" },
            { type: "Sinker", speed: "87" }, { type: "Straight", speed: "108" }, { type: "Straight", speed: "122" }, { type: "Curve", speed: "88" }, { type: "Straight", speed: "128" },
          ],
        },
        {
          title: { ko: "엑스트라 하드", en: "Extra Hard" },
          note: { ko: "위치는 자유 조준(하드보다 타겟이 작음, 2연타 불가)", en: "Free-aim — smaller targets than Hard, no two-panel hits" },
          pitches: [
            { type: "Straight", speed: "128" }, { type: "Sinker", speed: "84" }, { type: "Straight", speed: "102" }, { type: "Curve", speed: "88" }, { type: "Straight", speed: "124" },
            { type: "Sinker", speed: "105" }, { type: "Straight", speed: "120" }, { type: "Straight", speed: "104" }, { type: "Straight", speed: "128" }, { type: "Sinker", speed: "81" },
            { type: "Sinker", speed: "73" }, { type: "Straight", speed: "118" }, { type: "Straight", speed: "106" }, { type: "Curve", speed: "86" }, { type: "Straight", speed: "125" },
            { type: "Sinker", speed: "74" }, { type: "Straight", speed: "108" }, { type: "Straight", speed: "128" }, { type: "Curve", speed: "81" }, { type: "Straight", speed: "118" },
          ],
        },
      ],
    },
    {
      slug: "karaoke",
      name: { ko: "가라오케", en: "Karaoke" },
      category: { ko: "음악·리듬", en: "Music / rhythm" },
      difficulty: 3,
      location: { ko: "카무로초 — 가라오케관", en: "Karaoke bar, Kamurocho" },
      summary: {
        ko: "여섯 곡 각각 900점 이상이 조건입니다. 세 곡은 직접 부르고 세 곡은 추임새(인터젝션)로 참여합니다.",
        en: "Six songs, 900 or more on each. Three you sing yourself; three you back up with interjections.",
      },
      howTo: [
        { ko: "추임새 곡에서는 「간단」과 「신나게」 중에서 고르는데, 900점을 넘기려면 반드시 「신나게」를 골라야 합니다. 간단으로는 점수 상한이 모자랍니다.", en: "Interjection songs offer Simple or Lively — you have to take Lively, because Simple cannot reach 900." },
        { ko: "부르는 곡은 TONIGHT, 이지 사쿠라 2000, 바보 같지 -Sorrow-이고, 추임새 곡은 오토메탈 MY LIFE(하루카), Moment de la Petite Sirene(유이), EURO de x3 SHINE(리나)입니다.", en: "The three you sing are TONIGHT, Iji Sakura 2000 and Bakamitai -Sorrow-; the three you interject on are Otometal MY LIFE (Haruka), Moment de la Petite Sirene (Yui) and EURO de x3 SHINE (Rina)." },
        { ko: "오토메탈 MY LIFE는 하루카가 동행해야만 선택할 수 있습니다. 나머지 두 곡도 각각 유이·리나를 데려가야 하므로, 캬바쿠라 쪽을 어느 정도 진행해 두어야 합니다.", en: "Otometal MY LIFE only appears with Haruka along, and the other two need Yui and Rina — so the cabaret side has to be underway first." },
        { ko: "부르는 곡은 가사에, 추임새는 박자에 맞춰 옵니다. 「Hold」는 끝까지 누르고 「Rapid」는 연타입니다.", en: "Sung parts follow the lyrics, interjections follow the beat. Hold means hold to the end of the marker; Rapid means mash." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Karaoke (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/karaoke" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "ufo-catcher",
      name: { ko: "UFO 캐처 (인형 뽑기)", en: "UFO Catcher" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 2,
      location: { ko: "카무로초 — 클럽 세가 (1플레이 300엔)", en: "Club SEGA, Kamurocho (¥300 a play)" },
      summary: {
        ko: "컴플리션은 서로 다른 경품 5종과 15종 획득입니다. 인형은 전부 16종이며 어느 지점에서도 전부 뽑을 수 있습니다.",
        en: "Two rows: five and fifteen different prizes. There are sixteen plushes in total and every one can turn up at any location.",
      },
      howTo: [
        { ko: "원하는 인형이 안 보이면 카운터 직원에게 말을 걸어 기기를 다시 채워 달라고 하세요. 진열은 무작위로 바뀌므로 반복하면 결국 나옵니다.", en: "If the plush you need is not in the machine, ask the attendant to restock — the line-up is randomised, so it eventually turns up." },
        { ko: "잡는 방식은 인형 모양에 따라 다릅니다. 발이나 귀처럼 가는 부분에 걸거나, 가장 넓은 부분을 통째로 감싸거나, 가장 높은 부분을 잡아 넘어지지 않게 하는 세 가지를 상황에 맞게 씁니다.", en: "How you grab depends on the shape: hook a thin part like a foot or ear, wrap the widest part for a solid hold, or take it at its tallest point so it does not tip out." },
        { ko: "가장 찾기 어려운 건 「점보 밤톨이」와 「점보 분짱」입니다. 다른 인형보다 눈에 띄게 크므로 진열대에서 크기를 비교해 찾으세요.", en: "The hardest to find are the Jumbo Chestnut and Jumbo Bunchan — they are visibly larger than the rest, so compare sizes in the cabinet." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: UFO Catcher (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/ufo-catcher" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "photo-booth",
      name: { ko: "스티커 사진 (포토 부스)", en: "Photo Booth" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 2,
      location: { ko: "카무로초 — 클럽 세가 어디든", en: "Any Club SEGA in Kamurocho" },
      summary: {
        ko: "컴플리션은 「퍼펙트 샷 10회」 한 줄입니다. 단순해 보이지만 타이밍이 꽤 빡빡합니다.",
        en: "One row: ten perfect shots. It looks trivial and the timing is not.",
      },
      howTo: [
        { ko: "요금을 넣고 배경 세 장을 고른 뒤(배경은 컴플리션과 무관), 카운트다운 중 사진 아래에 표시되는 타이밍에 맞춰 버튼을 눌러 포즈를 잡습니다. 정확히 맞으면 사진에 반짝임이 붙고 그게 퍼펙트 샷입니다.", en: "Pay, pick three backgrounds (which do not matter), then hit a button on the timing marker under the picture as the countdown runs. Nail it and the shot fills with sparkles — that is a perfect shot." },
        { ko: "한 번 방문에 세 장을 찍으므로 잘하면 1회 방문에 3카운트가 오릅니다. 사진을 저장하지 않아도 카운트는 인정됩니다.", en: "A visit is three photos, so a good run banks three at once — and you do not have to save the photo for it to count." },
        { ko: "혼자 가도 되고, 캬바쿠라 데이트나 프리미엄 어드벤처의 하루카와 함께 가도 됩니다. 동행이 있어도 조건은 같습니다.", en: "You can go alone, on a cabaret date, or with Haruka in Premium Adventure — the requirement is the same either way." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Photo Booth (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/photo-booth" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "23_what_a_player",
    },
    {
      slug: "pocket-circuit",
      name: { ko: "포켓 서킷", en: "Pocket Circuit" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 4,
      location: { ko: "카무로초 — 포켓 서킷 스타디움", en: "Pocket Circuit Stadium, Kamurocho" },
      summary: {
        ko: "컴플리션은 부품 수집(타이어 5·10·20, 모터 5·10·15, 기어 5·10·20, 프레임 5·10·20)과 10회 출전, 그리고 14개 대회 전 우승입니다.",
        en: "Collect parts (5/10/20 tires, 5/10/15 motors, 5/10/20 gears, 5/10/20 frames), race ten times, and win all fourteen events.",
      },
      howTo: [
        { ko: "부품은 첫 번째·세 번째·네 번째·여섯 번째·마지막 레이스를 마칠 때마다 상점 재고가 갱신됩니다. 뒤로 갈수록 값이 크게 오르니 필요 없는 부품을 미리 사 두지 마세요.", en: "New parts appear in the shop after the first, third, fourth, sixth and final races, and get sharply more expensive each time — do not stock up on parts you will not use." },
        { ko: "스타디움에서 못 사는 부품이 있습니다. 일부는 거리의 상점에, 일부는 다른 미니게임 보상으로 나옵니다 — 볼링 스플릿 게임의 선샤인 데칼·엑스트라 스피드 프레임·울트라 소프트 타이어가 대표적입니다.", en: "Some parts are not sold at the Stadium: a few come from shops around town, others from other minigames — the Sunshine Decal, Extra Speed Frame and Ultra Soft Tires all come out of Split Bowling." },
        { ko: "대회별 추천 세팅은 kouryakutsushin.com이 정리한 것을 CyricZ 가이드가 표로 옮겨 두었습니다. 예를 들어 첫 도전 레이스는 슬림 타이어·스피드 프레임·스피드 모터·밸런스 기어·고속 배터리 조합입니다.", en: "Per-race builds were worked out by kouryakutsushin.com and tabulated in CyricZ's guide — the Introductory Race, for instance, is Slim tires, Speed frame, Speed motor, Balanced gears and a High Speed battery." },
        { ko: "챔피언 컵만은 부스트 타이밍이 중요합니다. 시계가 37초에 닿기 직전에 부스트를 써야 합니다.", en: "The Champion Cup is the one that needs a timed boost — use it just before the clock hits 37 seconds." },
      ],
      videos: [
        { title: { ko: "포켓 서킷 비기너·아마추어 컵 가이드", en: "Pocket Circuit: Beginner & Amateur Cup guide" }, url: YT("UaVsn4YPCwI") },
        { title: { ko: "포켓 서킷 마스터 컵 가이드", en: "Pocket Circuit: Master Cup guide" }, url: YT("hQWruCJ9wpg") },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Pocket Circuit (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/pocket-circuit" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "21_the_dragon_of_pocket_circuit_reborn",
    },
    {
      slug: "mesuking",
      name: { ko: "메스킹 (곤충 카드 배틀)", en: "MesuKing" },
      category: { ko: "아케이드", en: "Arcade" },
      difficulty: 3,
      location: { ko: "카무로초 — 클럽 세가 나카미치 거리점", en: "Club SEGA Nakamichi St., Kamurocho" },
      summary: {
        ko: "컴플리션은 카드 5장·20장·45장 수집입니다. 카드는 상점 구매, 거리에서 줍기, 서브스토리 보상 세 경로로 모입니다.",
        en: "Rows at 5, 20 and 45 cards. They come from shops, from the ground around town, and from substories.",
      },
      howTo: [
        { ko: "시작은 클럽 세가 나카미치 거리점의 흰 가운을 입은 소년(교수)에게 말을 거는 것입니다. 옴니 초크와 보디 슬램 두 장을 여기서 받습니다.", en: "Start by talking to the boy in the lab coat at Club SEGA Nakamichi St. — he hands you Omni Choke and Body Slam to begin." },
        { ko: "에비스 전당포와 연옥 무기점에서 10,000엔짜리 카드를 팝니다. 슈퍼 엘보 드롭·슈퍼 레그 스플리터는 전당포, 슈퍼 파일드라이버·카운터 힐·슈퍼 더블 드롭·미스틱 힐은 연옥 쪽입니다.", en: "Ebisu Pawn and the Purgatory weapon shop each sell cards at ¥10,000 — Super Elbow Drop and Super Leg Splitter at the pawn shop; Super Piledriver, Counter Heal, Super Double Drop and Mystic Heal in Purgatory." },
        { ko: "서브스토리 보상 카드가 여섯 장입니다. No.71 자이언트 스윙, No.72 피니시 타임, No.73 슈퍼 로메로 스페셜, No.75 라스트 리조트, No.77 타이 브레이커가 여기 해당합니다.", en: "Six cards come from substories — No.71 Giant Swing, No.72 Finish Time, No.73 Super Romero Special, No.75 Last Resort and No.77 Tie Breaker among them." },
        { ko: "나머지는 거리에 떨어져 있습니다. 호텔가 세이브 포인트 북서쪽 자판기 앞, 킷사 알프스 안쪽 테이블 뒤, 마하볼 입구의 볼링핀 뒤, 타이헤이 거리 서쪽 끝, 텐카이치 거리 POPPO 북쪽 트럭 앞 등이 대표적입니다.", en: "The rest lie around town: in front of the vending machines northwest of the Hotel District save point, behind the front tables in Cafe Alps, behind the pin at the Mach Bowl entrance, the far west end of Taihei Blvd., and by the flatbed truck north of the Tenkaichi St. POPPO." },
      ],
      videos: [
        { title: { ko: "메스킹 100% 트로피 공략", en: "Throne of the MesuKing 100% guide" }, url: YT("L49pavvEl4g") },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: MesuKing (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/mesuking" },
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
      ],
      achievementSlug: "22_throne_of_the_mesuking",
    },
    {
      slug: "cabaret-club",
      name: { ko: "캬바쿠라 (유이·리나)", en: "Cabaret Clubs (Yui & Rina)" },
      category: { ko: "기타", en: "Misc" },
      difficulty: 2,
      location: { ko: "카무로초 — 캬바쿠라", en: "The cabaret clubs of Kamurocho" },
      summary: {
        ko: "컴플리션은 유이의 서브스토리와 리나의 서브스토리를 각각 끝내는 두 줄입니다. 대화 선택지로 호감도를 올려 진행합니다.",
        en: "Two rows: finish Yui's substory and Rina's substory. You raise each hostess by picking the right conversation options.",
      },
      howTo: [
        { ko: "두 사람은 가라오케 컴플리션과도 엮여 있습니다. Moment de la Petite Sirene은 유이, EURO de x3 SHINE은 리나를 동반해야 부를 수 있으므로 캬바쿠라를 먼저 진행해 두는 편이 효율적입니다.", en: "They also gate two karaoke rows — Moment de la Petite Sirene needs Yui along and EURO de x3 SHINE needs Rina — so it pays to push the club side first." },
        { ko: "서브스토리는 지명 → 대화 → 애프터(데이트) 순으로 진행됩니다. 데이트 장소에서 포토 부스에 들르면 퍼펙트 샷 카운트도 같이 올릴 수 있습니다.", en: "Each substory runs request, conversation, then an after-hours date — and taking that date to the photo booth banks perfect shots at the same time." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami: Completion List (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/181171-yakuza-kiwami/faqs/75194/completion-list" },
        { label: "ダラゲ！ — 龍が如く 極 キャバクラ（会話の選択肢）", url: "https://darage.com/guide/ryukiwami1/mini17.html" },
        { label: "ゲーム攻略マン — キャバ嬢『ゆい』", url: "https://dswiipspwikips3.jp/yakuza-kiwami/cabaret-club/yui.html" },
        { label: "ゲーム攻略マン — キャバ嬢『リナ』", url: "https://dswiipspwikips3.jp/yakuza-kiwami/cabaret-club/rina.html" },
      ],
      puzzleSets: [
        {
          title: { ko: "유이(JeweL) 대화 정답 — 22종", en: "Yui (JeweL) conversation answers — all 22" },
          note: { ko: "대화는 정해진 순서대로 나오고, 22종을 한 바퀴 돈 뒤에는 (반복) 표시된 대화만 순서대로 다시 나옵니다. 아래는 호감도가 오르는 선택지만 적었고(나머지는 변화 없음 또는 하락), 오르는 선택지는 ダラゲ!와 ゲーム攻略マン 두 곳에서 22문항 모두 같고, ゲーム攻略マン이 「한 번 내렸다가 오른다」고 적은 선택지는 해당 문항에 따로 표시했습니다. 선택지 원문은 일본어판 표기이고 한국어·영어는 뜻풀이라 실제 게임 문구와 다를 수 있습니다. 음료는 1,000엔짜리로 충분하고, 「私ももらっていい？」에는 「いいぞ」를 고르면 조금 더 오릅니다.", en: "Conversations come in a fixed order; once all 22 have played, only the ones marked (repeats) cycle again. Only the choices that raise affection are listed (the rest do nothing or lower it); Darage and ゲーム攻略マン agree on the rising choices for all 22; where ゲーム攻略マン says a choice dips before rising, that question says so. Choice text is the Japanese release; the English is a gloss and will not match the localised wording exactly. A ¥1,000 drink is enough, and answering 「私ももらっていい？」 (can I have one too?) with 「いいぞ」 (sure) adds a little more." },
          puzzles: [
            { title: { ko: "1. 「お仕事、辞めちゃったの？」 — 일 그만둔 거야?", en: "1. 「お仕事、辞めちゃったの？」 — You quit your job?" }, note: { ko: "정답: 「刑務所に入ってたんだ」(교도소에 있었어) 또는 「任期満了ってところだ」(임기 만료라고 해 두지).", en: "Pick: 「刑務所に入ってたんだ」 (I was in prison) or 「任期満了ってところだ」 (Let's say my term was up)." } },
            { title: { ko: "2. 「\"いくら貢いでもお客さんには絶対惚れません\"って言うことにしてるの。」 — 「아무리 갖다 바쳐도 손님한텐 절대 안 반해요」라고 말하기로 했어", en: "2. 「\"いくら貢いでもお客さんには絶対惚れません\"って言うことにしてるの。」 — I always say 'however much you spend, I never fall for customers'" }, note: { ko: "정답: 「正直なんだな」(솔직하구나).", en: "Pick: 「正直なんだな」 (You're honest)." } },
            { title: { ko: "3. 「何かオススメあったら教えて♪」 — 뭔가 추천할 거 있으면 알려 줘♪ (반복)", en: "3. 「何かオススメあったら教えて♪」 — Recommend me something♪ (repeats)" }, note: { ko: "정답: 「ダンススクール」(댄스 스쿨) 또는 「料理教室」(요리 교실).", en: "Pick: 「ダンススクール」 (Dance school) or 「料理教室」 (Cooking class)." } },
            { title: { ko: "4. 「私まで巻き込まれちゃって・・・」 — 나까지 휘말려 버려서…… (반복)", en: "4. 「私まで巻き込まれちゃって・・・」 — Now I'm dragged into it too… (repeats)" }, note: { ko: "정답: 「妹の自由だ」(동생 마음이지) 또는 「お前もすればいい」(너도 하면 되지).", en: "Pick: 「妹の自由だ」 (It's your sister's call) or 「お前もすればいい」 (You do it too, then)." } },
            { title: { ko: "5. 「あんまりいないと思うんだよねぇ・・・」 — 별로 없을 것 같거든……", en: "5. 「あんまりいないと思うんだよねぇ・・・」 — I don't think there are many…" }, note: { ko: "정답: 「女の気持ちも考えないとな」(여자 마음도 생각해야지).", en: "Pick: 「女の気持ちも考えないとな」 (You have to think about how women feel)." } },
            { title: { ko: "6. 「キャバで出会いましたって言うわけ？」 — 캬바에서 만났다고 말하는 거야?", en: "6. 「キャバで出会いましたって言うわけ？」 — So you say you met at a cabaret?" }, note: { ko: "정답: 「適当にぼかせばいい」(적당히 얼버무리면 돼) 또는 「正直に言えばいい」(솔직하게 말하면 돼).", en: "Pick: 「適当にぼかせばいい」 (Just keep it vague) or 「正直に言えばいい」 (Just be honest)." } },
            { title: { ko: "7. 「同窓会に参加しない人って、どう思う？」 — 동창회에 안 나오는 사람, 어떻게 생각해? (반복)", en: "7. 「同窓会に参加しない人って、どう思う？」 — What do you think of people who skip reunions? (repeats)" }, note: { ko: "정답: 「楽しくないんだろう」(재미없는 거겠지).", en: "Pick: 「楽しくないんだろう」 (They probably don't enjoy it)." } },
            { title: { ko: "8. 「って誘って、本人に選ばせるとかあるじゃない？」 — ……하고 꾀어서 본인한테 고르게 하는 거 있잖아? (반복)", en: "8. 「って誘って、本人に選ばせるとかあるじゃない？」 — You know, invite them and let them choose? (repeats)" }, note: { ko: "정답: 「常套手段だな」(흔한 수법이군).", en: "Pick: 「常套手段だな」 (The usual trick)." } },
            { title: { ko: "9. 「それなのに全然めげないんだもん。」 — 그런데도 전혀 기죽지 않는다니까.", en: "9. 「それなのに全然めげないんだもん。」 — And he just won't give up." }, note: { ko: "정답: 「その言い方はダメだ」(그렇게 말하면 안 되지) 또는 「しつけぇ男だな……」(끈질긴 놈이군……).", en: "Pick: 「その言い方はダメだ」 (Don't put it like that) or 「しつけぇ男だな……」 (Persistent guy…)." } },
            { title: { ko: "10. 「お客さん相手に\"好き\"なんて絶対言えない！」 — 손님한테 '좋아해'라고는 절대 못 해!", en: "10. 「お客さん相手に\"好き\"なんて絶対言えない！」 — I could never say 'I like you' to a customer!" }, note: { ko: "정답: 「\"愛してる\"ならどうだ」('사랑해'라면 어때).", en: "Pick: 「\"愛してる\"ならどうだ」 (How about 'I love you'?)." } },
            { title: { ko: "11. 「どうしたらいいかな～？」 — 어떻게 하면 좋을까~? (반복)", en: "11. 「どうしたらいいかな～？」 — What should I do~? (repeats)" }, note: { ko: "정답: 「飼うなら早くした方がいい」(키울 거면 빨리 하는 게 좋아) 또는 「半端な気持ちならやめとけ」(어중간한 마음이면 그만둬).", en: "Pick: 「飼うなら早くした方がいい」 (If you'll keep one, do it soon) or 「半端な気持ちならやめとけ」 (Don't if you're half-hearted)." } },
            { title: { ko: "12. 「いいから！ちょっと考えてみてよ。」 — 됐으니까! 좀 생각해 봐. (반복)", en: "12. 「いいから！ちょっと考えてみてよ。」 — Come on! Just think about it. (repeats)" }, note: { ko: "정답: 「面白くない」(재미없어, ゲーム攻略マン: 한 번 내렸다가 오름) 또는 「可愛くない」(안 귀여워, ゲーム攻略マン: 한 번 내렸다가 오름).", en: "Pick: 「面白くない」 (Not funny; ゲーム攻略マン: dips, then rises) or 「可愛くない」 (Not cute; ゲーム攻略マン: dips, then rises)." } },
            { title: { ko: "13. 「相手の男が、絶対に外で会おうとしないのよ！そんなのってありえる？」 — 상대 남자가 절대 밖에서 만나려고 안 해! 그런 게 말이 돼?", en: "13. 「相手の男が、絶対に外で会おうとしないのよ！そんなのってありえる？」 — The guy will never meet her outside! Is that even possible?" }, note: { ko: "정답: 「変なのはお前だ」(이상한 건 너야).", en: "Pick: 「変なのはお前だ」 (You're the weird one)." } },
            { title: { ko: "14. 「さっさと別れた方がいいと思うのよね。」 — 빨리 헤어지는 게 좋을 것 같거든.", en: "14. 「さっさと別れた方がいいと思うのよね。」 — I think she should break up already." }, note: { ko: "정답: 「外野が騒ぐことじゃない」(남이 떠들 일이 아니야, ゲーム攻略マン: 한 번 내렸다가 오름) 또는 「そうした方がいい」(그러는 게 좋겠지).", en: "Pick: 「外野が騒ぐことじゃない」 (Not for outsiders to fuss over; ゲーム攻略マン: dips, then rises) or 「そうした方がいい」 (She should)." } },
            { title: { ko: "15. 「今から憂鬱なのよね……」 — 벌써부터 우울해…… (반복)", en: "15. 「今から憂鬱なのよね……」 — I'm already dreading it… (repeats)" }, note: { ko: "정답: 「笑顔をやめたらどうだ？」(웃는 걸 그만두면 어때?) 또는 「友達に撮ってもらえ」(친구한테 찍어 달라고 해).", en: "Pick: 「笑顔をやめたらどうだ？」 (Why not stop smiling?) or 「友達に撮ってもらえ」 (Have a friend take it)." } },
            { title: { ko: "16. 「中身はただのソフトドリンクにするとか。」 — 내용물은 그냥 소프트드링크로 한다든가. (반복)", en: "16. 「中身はただのソフトドリンクにするとか。」 — Like, it's just a soft drink inside. (repeats)" }, note: { ko: "정답: 「お前もそうなのか？」(너도 그래?) 또는 「健康に良さそうだな」(건강에 좋겠네). 「お前もそうなのか？」 뒤에 나오는 「やめておく」「いいだろう」는 어느 쪽이든 오릅니다.", en: "Pick: 「お前もそうなのか？」 (You too?) or 「健康に良さそうだな」 (Sounds healthy). After 「お前もそうなのか？」 both follow-ups (「やめておく」/「いいだろう」) raise it." } },
            { title: { ko: "17. 「行っちゃったりするのかなって思って……」 — 가 버리는 건 아닐까 싶어서……", en: "17. 「行っちゃったりするのかなって思って……」 — I wondered if you might go…" }, note: { ko: "정답: 「その可能性はある」(그럴 가능성은 있지).", en: "Pick: 「その可能性はある」 (That's possible)." } },
            { title: { ko: "18. 「惚れないようにしなきゃ……！」 — 반하지 않도록 해야지……!", en: "18. 「惚れないようにしなきゃ……！」 — I mustn't fall for you…!" }, note: { ko: "정답: 「仕事を辞めた方がいい」(일을 그만두는 게 좋아) 또는 「多分それはもう惚れている」(아마 이미 반한 거야) — 크게 오름.", en: "Pick: 「仕事を辞めた方がいい」 (You should quit the job) or 「多分それはもう惚れている」 (You probably already have) — big boost." } },
            { title: { ko: "19. 「桐生さん、どう思う！？」 — 키류 씨, 어떻게 생각해!? (반복)", en: "19. 「桐生さん、どう思う！？」 — Kiryu, what do you think!? (repeats)" }, note: { ko: "정답: 「映画によるだろ」(영화에 따라 다르지) 또는 「歳は関係あるな」(나이는 상관있지).", en: "Pick: 「映画によるだろ」 (Depends on the film) or 「歳は関係あるな」 (Age does matter)." } },
            { title: { ko: "20. 「予約したのに待たされるとか超サイアク……」 — 예약했는데 기다리게 하다니 완전 최악…… (반복)", en: "20. 「予約したのに待たされるとか超サイアク……」 — Booked and still kept waiting — the worst… (repeats)" }, note: { ko: "정답: 「災難だったな」(운이 나빴네).", en: "Pick: 「災難だったな」 (Rough luck)." } },
            { title: { ko: "21. 「罰金払わされちゃうの……」 — 벌금 내야 한단 말이야……", en: "21. 「罰金払わされちゃうの……」 — I'll get fined…" }, note: { ko: "정답: 「客には惚れないんだろ？」(손님한텐 안 반한다며?) 또는 「俺で良ければ構わないぜ」(나라도 괜찮다면 상관없어).", en: "Pick: 「客には惚れないんだろ？」 (You don't fall for customers, right?) or 「俺で良ければ構わないぜ」 (Fine by me, if I'll do)." } },
            { title: { ko: "22. 「だから私に任せて！」 — 그러니까 나한테 맡겨!", en: "22. 「だから私に任せて！」 — So leave it to me!" }, note: { ko: "정답: 「楽しみにしておくよ」(기대하고 있을게).", en: "Pick: 「楽しみにしておくよ」 (I'll look forward to it)." } },
          ],
        },
        {
          title: { ko: "리나(SHINE) 대화 정답 — 22종", en: "Rina (SHINE) conversation answers — all 22" },
          note: { ko: "대화는 정해진 순서대로 나오고, 22종을 한 바퀴 돈 뒤에는 (반복) 표시된 대화만 순서대로 다시 나옵니다. 아래는 호감도가 오르는 선택지만 적었고(나머지는 변화 없음 또는 하락), 오르는 선택지는 ダラゲ!와 ゲーム攻略マン 두 곳에서 22문항 모두 같고, ゲーム攻略マン이 「한 번 내렸다가 오른다」고 적은 선택지는 해당 문항에 따로 표시했습니다. 선택지 원문은 일본어판 표기이고 한국어·영어는 뜻풀이라 실제 게임 문구와 다를 수 있습니다. 음료는 1,000엔짜리로 충분하고, 「私ももらっていい？」에는 「いいぞ」를 고르면 조금 더 오릅니다.", en: "Conversations come in a fixed order; once all 22 have played, only the ones marked (repeats) cycle again. Only the choices that raise affection are listed (the rest do nothing or lower it); Darage and ゲーム攻略マン agree on the rising choices for all 22; where ゲーム攻略マン says a choice dips before rising, that question says so. Choice text is the Japanese release; the English is a gloss and will not match the localised wording exactly. A ¥1,000 drink is enough, and answering 「私ももらっていい？」 (can I have one too?) with 「いいぞ」 (sure) adds a little more." },
          puzzles: [
            { title: { ko: "1. 「えへへ…… それも全然♪」 — 에헤헤…… 그것도 전혀♪", en: "1. 「えへへ…… それも全然♪」 — Hehe… that too, not at all♪" }, note: { ko: "정답: 「お前、新人か？」(너 신입이야?) 또는 「俺も最近の事情は全然だな」(나도 요즘 사정은 전혀 몰라).", en: "Pick: 「お前、新人か？」 (Are you new?) or 「俺も最近の事情は全然だな」 (I'm out of touch too)." } },
            { title: { ko: "2. 「まさにここは天国です♪」 — 그야말로 여긴 천국이에요♪", en: "2. 「まさにここは天国です♪」 — This place is heaven♪" }, note: { ko: "정답: 「ほどほどにな」(적당히 해) 또는 「幸せそうだな」(행복해 보이네) — 크게 오름.", en: "Pick: 「ほどほどにな」 (Don't overdo it) or 「幸せそうだな」 (You look happy) — big boost." } },
            { title: { ko: "3. 「カメラ買えないよぉ……！」 — 카메라를 못 사겠어요……! (반복)", en: "3. 「カメラ買えないよぉ……！」 — I can't afford the camera…! (repeats)" }, note: { ko: "정답: 「そこまで欲しくないんだろ」(그렇게까지 갖고 싶진 않은 거지) 또는 「金は使ってこそだ」(돈은 써야 맛이지).", en: "Pick: 「そこまで欲しくないんだろ」 (You don't want it that badly) or 「金は使ってこそだ」 (Money's for spending)." } },
            { title: { ko: "4. 「どういうところがいいのかなぁ？」 — 어떤 곳이 좋을까요? (반복)", en: "4. 「どういうところがいいのかなぁ？」 — What kind of place would be good? (repeats)" }, note: { ko: "정답: 「ラーメンなんてどうだ？」(라멘은 어때?) 또는 「食べ放題なんてどうだ？」(무한리필은 어때?).", en: "Pick: 「ラーメンなんてどうだ？」 (How about ramen?) or 「食べ放題なんてどうだ？」 (How about all-you-can-eat?)." } },
            { title: { ko: "5. 「別れて欲しいって言われて……」 — 헤어지자는 말을 들어서……", en: "5. 「別れて欲しいって言われて……」 — She was asked to break up…" }, note: { ko: "정답: 「それは浮気じゃないだろ」(그건 바람이 아니잖아).", en: "Pick: 「それは浮気じゃないだろ」 (That's not cheating)." } },
            { title: { ko: "6. 「もちろん女の子ですよぉ」 — 물론 여자예요", en: "6. 「もちろん女の子ですよぉ」 — A woman, of course" }, note: { ko: "정답: 「式には行くのか？」(결혼식엔 가?) 또는 「海外は進んでいるな」(해외는 앞서 있네).", en: "Pick: 「式には行くのか？」 (Are you going to the wedding?) or 「海外は進んでいるな」 (They're progressive abroad)." } },
            { title: { ko: "7. 「あんなに辛いカラオケは初めて……」 — 그렇게 괴로운 노래방은 처음…… (반복)", en: "7. 「あんなに辛いカラオケは初めて……」 — Never had karaoke that painful… (repeats)" }, note: { ko: "정답: 「お前が合わせろよ」(네가 맞춰, ゲーム攻略マン: 한 번 내렸다가 오름) 또는 「流行りの曲を歌うべきだな」(유행하는 곡을 불러야지).", en: "Pick: 「お前が合わせろよ」 (You match them; ゲーム攻略マン: dips, then rises) or 「流行りの曲を歌うべきだな」 (Sing the hits)." } },
            { title: { ko: "8. 「手も超スベスベだし、本当に可愛かった♪」 — 손도 엄청 매끈하고, 정말 귀여웠어♪ (반복)", en: "8. 「手も超スベスベだし、本当に可愛かった♪」 — Her hands were so smooth, she was so cute♪ (repeats)" }, note: { ko: "정답: 「大変なことも多そうだ」(힘든 일도 많겠어, ゲーム攻略マン: 한 번 내렸다가 오름) 또는 「距離が近くていいな」(거리가 가까워서 좋네) — 크게 오름.", en: "Pick: 「大変なことも多そうだ」 (Must be hard work too; ゲーム攻略マン: dips, then rises) or 「距離が近くていいな」 (Nice to be that close) — big boost." } },
            { title: { ko: "9. 「俺がもし女だったら、か。そうだなぁ……」 — 내가 만약 여자라면, 이라. 글쎄……", en: "9. 「俺がもし女だったら、か。そうだなぁ……」 — If I were a woman, huh. Let's see…" }, note: { ko: "정답: 「男と付き合ってみたい」(남자랑 사귀어 보고 싶어) 또는 「服装にこだわってみたい」(옷차림에 신경 써 보고 싶어).", en: "Pick: 「男と付き合ってみたい」 (I'd date a man) or 「服装にこだわってみたい」 (I'd get into fashion)." } },
            { title: { ko: "10. 「逞しい男性に憧れてるかも……？」 — 늠름한 남자를 동경하는 걸지도……?", en: "10. 「逞しい男性に憧れてるかも……？」 — Maybe I admire strong men…?" }, note: { ko: "정답: 「自分が嫌いなのか？」(자기가 싫은 거야?).", en: "Pick: 「自分が嫌いなのか？」 (Do you dislike yourself?)." } },
            { title: { ko: "11. 「ホント嫌になります……」 — 정말 싫어져요…… (반복)", en: "11. 「ホント嫌になります……」 — It really gets to me… (repeats)" }, note: { ko: "정답: 「転勤したらどうだ？」(전근하면 어때?) 또는 「俺も人混みは苦手だ」(나도 인파는 질색이야) — 크게 오름.", en: "Pick: 「転勤したらどうだ？」 (Why not transfer?) or 「俺も人混みは苦手だ」 (I hate crowds too) — big boost." } },
            { title: { ko: "12. 「なんで気にしないんだろ？」 — 왜 신경을 안 쓰는 걸까? (반복)", en: "12. 「なんで気にしないんだろ？」 — Why don't they care? (repeats)" }, note: { ko: "정답: 「大事なのは気持ちだ」(중요한 건 마음이야) 또는 「忘れちゃダメだよな」(잊으면 안 되지).", en: "Pick: 「大事なのは気持ちだ」 (It's the feeling that counts) or 「忘れちゃダメだよな」 (You shouldn't forget)." } },
            { title: { ko: "13. 「似合う女になりたいです～。」 — 어울리는 여자가 되고 싶어요~.", en: "13. 「似合う女になりたいです～。」 — I want to become a woman who suits it~." }, note: { ko: "정답: 「やめておけ」(그만둬) 또는 「なれるさ」(될 수 있어).", en: "Pick: 「やめておけ」 (Don't) or 「なれるさ」 (You can)." } },
            { title: { ko: "14. 「もし桐生さんが、自分のこと可愛いって言われたらどう思います？」 — 만약 키류 씨가 자기더러 귀엽다는 말을 들으면 어떨 것 같아요?", en: "14. 「もし桐生さんが、自分のこと可愛いって言われたらどう思います？」 — If someone called you cute, Kiryu, how would you feel?" }, note: { ko: "정답: 「何も思わない」(아무렇지도 않아) 또는 「俺、可愛い？」(나, 귀여워?) — 크게 오름.", en: "Pick: 「何も思わない」 (Nothing) or 「俺、可愛い？」 (Am I cute?) — big boost." } },
            { title: { ko: "15. 「ところが気持ち悪いんです……」 — 그런 데가 징그러워요…… (반복)", en: "15. 「ところが気持ち悪いんです……」 — That part's creepy… (repeats)" }, note: { ko: "정답: 「お前もやり返せ」(너도 되갚아 줘).", en: "Pick: 「お前もやり返せ」 (Give it back to him)." } },
            { title: { ko: "16. 「起きたらすぐ出かける時間でそんな余裕ないし……」 — 일어나면 바로 나갈 시간이라 그럴 여유가 없고…… (반복)", en: "16. 「起きたらすぐ出かける時間でそんな余裕ないし……」 — By the time I wake up I have to leave, no time… (repeats)" }, note: { ko: "정답: 「自分でなんとかしろ」(스스로 어떻게든 해) 또는 「俺が手伝おうか」(내가 도와줄까).", en: "Pick: 「自分でなんとかしろ」 (Sort it out yourself) or 「俺が手伝おうか」 (Shall I help?)." } },
            { title: { ko: "17. 「協力してくれる？」 — 협력해 줄래요?", en: "17. 「協力してくれる？」 — Will you help me?" }, note: { ko: "정답: 「馬鹿言うな」(바보 같은 소리 마).", en: "Pick: 「馬鹿言うな」 (Don't be stupid)." } },
            { title: { ko: "18. 「やっぱり難しいですよねぇ……」 — 역시 어렵겠죠……", en: "18. 「やっぱり難しいですよねぇ……」 — It's hard after all, isn't it…" }, note: { ko: "정답: 「養子はどうだ？」(입양은 어때?) 또는 「見つかるといいな」(찾으면 좋겠네).", en: "Pick: 「養子はどうだ？」 (How about adoption?) or 「見つかるといいな」 (Hope you find one)." } },
            { title: { ko: "19. 「男が化粧なんかするなぁって感じ！」 — 남자가 화장 같은 걸 하냐는 느낌! (반복)", en: "19. 「男が化粧なんかするなぁって感じ！」 — Like, men shouldn't wear makeup! (repeats)" }, note: { ko: "정답: 「女装バーはどうだ？」(여장 바는 어때?) 또는 「男らしい男はどうだ？」(남자다운 남자는 어때?). PS4판은 「オカマバーはどうだ？」로 표기됩니다.", en: "Pick: 「女装バーはどうだ？」 (How about a crossdressing bar?) or 「男らしい男はどうだ？」 (How about a manly man?). The PS4 version words it 「オカマバーはどうだ？」." } },
            { title: { ko: "20. 「私、運動はダメなんですよぉ！」 — 저, 운동은 젬병이에요! (반복)", en: "20. 「私、運動はダメなんですよぉ！」 — I'm hopeless at exercise! (repeats)" }, note: { ko: "정답: 「太ってる方がいい」(통통한 게 좋아).", en: "Pick: 「太ってる方がいい」 (I like a bit of weight)." } },
            { title: { ko: "21. 「自分から声をかけますか？」 — 먼저 말을 거나요?", en: "21. 「自分から声をかけますか？」 — Do you speak to them first?" }, note: { ko: "정답: 「もちろんだ」(물론이지).", en: "Pick: 「もちろんだ」 (Of course)." } },
            { title: { ko: "22. 「はぁ、どうしたらいいのかなぁ……？」 — 하아, 어떻게 하면 좋을까요……?", en: "22. 「はぁ、どうしたらいいのかなぁ……？」 — Sigh, what should I do…?" }, note: { ko: "정답: 「損な性格だな」(손해 보는 성격이네) 또는 「気になる相手がいるのか？」(신경 쓰이는 상대가 있어?).", en: "Pick: 「損な性格だな」 (You lose out with that personality) or 「気になる相手がいるのか？」 (Is there someone you like?)." } },
          ],
        },
      ],
      achievementSlug: "23_what_a_player",
    },
  ],
};

