import type { SubstoriesData } from "./types";

export const judgmentSubstories: SubstoriesData = {
  appId: 2058180,
  summary: {
    ko: "주인공 야가미 타카유미의 탐정 사이드 케이스 총 50건. 챕터 2에서 야가미 탐정 사무소의 게시판이 해금되면서 본격 시작되고, 술집 텐더·겐다 법률사무소·길거리 의뢰가 추가됩니다. 49건 클리어 + 거리 평판 Lv.50 달성 시 최종 「최후의 의뢰」(아몬 신 전) 해금. 친구 이벤트(카이토, 히라누마 등) 진행이 일부 케이스 전제 조건입니다.",
    en: "50 detective Side Cases for Yagami Takayuki. The bulletin board at the Yagami Detective Agency unlocks in Chapter 2; later bar-tender, law-office, and street requests stack on top. Clearing 49 cases plus reaching Street Reputation Lv.50 opens the finale 'The Final Request' (Shin Amon fight). Several cases gate on friend events (Kaito, Hiranuma, etc.).",
  },
  source: { label: "gamewith.jp — ジャッジアイズ サイドケース攻略一覧", url: "https://gamewith.jp/judgeeyes/article/show/134172" },
  groups: [
    {
      title: { ko: "야가미 탐정 사무소 — 게시판 의뢰", en: "Yagami Detective Agency — Bulletin Board" },
      items: [
        {
          number: 1,
          title: { ko: "변태 삼총사: 팬티 교수", en: "The Perv Trinity: Professor Panty" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "야가미 탐정 사무소 게시판", en: "Yagami Detective Agency — bulletin board" },
          trigger: { ko: "챕터 2 사이드 케이스 해금 후 게시판에서 의뢰 수락 (애인 이벤트 1건 이상 진행 필요)", en: "Accept from the bulletin board after Chapter 2 unlocks side cases. Requires at least one girlfriend event in progress." },
          body: {
            ko: "여대생들의 팬티를 훔쳐가는 「팬티 교수」를 잡아달라는 의뢰. 잠복하면서 의심스러운 인물 한 명을 골라야 하며, 야가미의 추리 모드(미행/사진)로 결정적 증거를 잡습니다. 변태 삼총사 1편으로, 클리어해야 2편 「엉덩이 마이스터」가 풀립니다.",
            en: "Track down 'Professor Panty', a serial underwear thief targeting female students. Stake out the campus, tail the suspect with Yagami's detective tools, then snap the decisive photo. Clearing this opens Part 2 ('Butt Meister').",
          },
          choices: [
            { prompt: { ko: "「수상한 사람은 누구지?」", en: "'Who's the suspect?'" }, correct: { ko: "안경을 낀 강사풍 남자", en: "The lecturer-looking man with glasses" }, note: { ko: "다른 후보를 고르면 미행 실패 → 처음부터 다시", en: "Wrong pick fails the tail — restart the sequence." } },
          ],
          reward: { ko: "30,000엔 + 80 SP", en: "¥30,000 + 80 SP" },
        },
        {
          number: 2,
          title: { ko: "변태 삼총사: 엉덩이 마이스터", en: "The Perv Trinity: Butt Meister" },
          chapter: { ko: "챕터 2~", en: "Chapter 2+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "「팬티 교수」 클리어 + 거리 평판 Lv.5 이상", en: "Clear Case 1, reach Street Reputation Lv.5." },
          body: {
            ko: "이번엔 길거리에서 여성 엉덩이만 노리는 변태를 추적. 카무로쵸 거리 곳곳을 미행하다가 결정적 순간을 카메라로 포착해야 합니다. 부주의하게 가까이 다가가면 들켜서 처음부터.",
            en: "Tail a butt-obsessed pervert through Kamurocho. Keep distance during the stalk and time the photo right or you'll be made and restart.",
          },
          choices: [
            { prompt: { ko: "「어디서부터 미행할까?」", en: "'Where to start the tail?'" }, correct: { ko: "타이헤이 거리 쪽 카페 앞", en: "The café on Taihei Blvd." } },
          ],
          reward: { ko: "40,000엔 + 100 SP", en: "¥40,000 + 100 SP" },
        },
        {
          number: 3,
          title: { ko: "변태 삼총사: 도촬 판사", en: "The Perv Trinity: Peeping Judge" },
          chapter: { ko: "챕터 2~", en: "Chapter 2+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "「엉덩이 마이스터」 + 「다이아몬드의 눈을 가진 고양이」 클리어 + 평판 Lv.15", en: "Clear Cases 2 and 19, reach Lv.15 reputation." },
          body: {
            ko: "변태 시리즈 마지막. 도촬 판사를 잡기 위해 야간 잠복 + 미행을 반복하며, 마지막 추리 파트에서 진범 후보 세 명 중 한 명을 지목해야 합니다.",
            en: "Final pervert case. Night stake-outs and tails, then a deduction prompt with three suspects — pick the real Peeping Judge.",
          },
          choices: [
            { prompt: { ko: "「진범은 누구인가?」", en: "'Who's the real culprit?'" }, correct: { ko: "정장 차림 중년 남자", en: "The middle-aged man in a suit" } },
          ],
          reward: { ko: "60,000엔 + 150 SP + 「변태왕」 칭호 트로피 진행", en: "¥60,000 + 150 SP + progress toward the 'Pervert King' trophy chain" },
        },
        {
          number: 4,
          title: { ko: "스카쟌의 행방", en: "Where's the Sukajan?" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "챕터 2에서 게시판 해금 직후 수락", en: "Accept right after the bulletin board unlocks in Chapter 2." },
          body: {
            ko: "잃어버린 스카쟌(자수 점퍼)의 행방을 추적. 와일드 잭슨, 어린이 공원, 배팅 센터, 챔피언 거리에서 단서를 수집. 노숙자에게 도시락 2개 + 방한복 합계 6,150엔 어치를 사 주면 정보가 풀립니다. 모로보시 고로 친구 이벤트를 끝냈다면 도시락 구매는 생략 가능.",
            en: "Track down a missing sukajan jacket. Gather clues at Wild Jackson, the kids' park, the batting cage, and Champion St. Buying two bentos + winter clothing (¥6,150 total) for a homeless informant unlocks the next lead — skippable if you've finished Goro Moroboshi's friend event.",
          },
          reward: { ko: "50,000엔 + 100 SP", en: "¥50,000 + 100 SP" },
        },
        {
          number: 5,
          title: { ko: "미스터리 작가로부터의 도전장", en: "The Mystery Writer's Challenge" },
          chapter: { ko: "챕터 2~", en: "Chapter 2+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "챕터 2 이후 + 거리 평판 Lv.10", en: "Chapter 2+, Street Reputation Lv.10." },
          body: {
            ko: "유명 미스터리 작가가 야가미의 추리력을 시험하기 위해 카무로쵸에 암호를 숨겨놨습니다. 게시판 사진 단서를 보고 정확한 장소로 이동, 다음 단서를 찾는 식. 추리 파트에서 작가의 진의를 묻는 선택지가 등장합니다.",
            en: "A famous mystery author drops coded clues across Kamurocho. Decode the bulletin-board photo, travel to each spot, and finish a deduction prompt about the writer's true motive.",
          },
          choices: [
            { prompt: { ko: "「작가가 진짜 시험하려는 것은?」", en: "'What is the writer really testing?'" }, correct: { ko: "탐정의 관찰력", en: "The detective's powers of observation" } },
          ],
          reward: { ko: "60,000엔 + 120 SP", en: "¥60,000 + 120 SP" },
        },
        {
          number: 6,
          title: { ko: "속・미스터리 작가로부터의 도전장", en: "The Mystery Writer's Challenge II" },
          chapter: { ko: "챕터 3~", en: "Chapter 3+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "5번 클리어 + 평판 Lv.20 + 일정 시간 경과", en: "Clear Case 5, reach Lv.20 reputation, wait in-game." },
          body: { ko: "암호가 더 난해해진 2차전. 사진 + 글귀 양쪽을 봐야 풀리는 단서가 다수. 진행 중간에 카이토가 동행해 잡담 컷씬이 들어갑니다.", en: "Trickier ciphers requiring you to cross-reference photos and prose. Kaito tags along for banter cutscenes mid-investigation." },
          reward: { ko: "80,000엔 + 150 SP", en: "¥80,000 + 150 SP" },
        },
        {
          number: 7,
          title: { ko: "속속・미스터리 작가로부터의 도전장", en: "The Mystery Writer's Challenge III" },
          chapter: { ko: "챕터 5~", en: "Chapter 5+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "6번 클리어 + 평판 Lv.30", en: "Clear Case 6, reach Lv.30 reputation." },
          body: { ko: "시리즈 완결편. 카무로쵸 전역을 도는 대규모 보물찾기 후, 작가와 직접 대면해 진의를 가리는 추리 배틀.", en: "Series finale — a city-spanning treasure hunt that ends in a face-to-face deduction battle with the writer." },
          reward: { ko: "120,000엔 + 200 SP", en: "¥120,000 + 200 SP" },
        },
        {
          number: 8,
          title: { ko: "나를 찾아줘", en: "Find Me" },
          chapter: { ko: "챕터 2~", en: "Chapter 2+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "챕터 2 이후 + 평판 Lv.25", en: "Chapter 2+, Lv.25 reputation." },
          body: {
            ko: "「자신을 찾아달라」는 기묘한 의뢰. 의뢰인의 아이덴티티가 흔들리는 상황을 추적, 가족·직장·단골 가게에서 단서를 모아 본인을 다시 일깨워줍니다.",
            en: "A client asks Yagami to 'find me'. Piece together her identity from family, workplace, and her regular bar to bring her back to herself.",
          },
          choices: [
            { prompt: { ko: "「당신은 누구입니까?」", en: "'Who are you?'" }, correct: { ko: "당신은 당신 자신입니다", en: "You are still yourself" } },
          ],
          reward: { ko: "50,000엔 + 100 SP", en: "¥50,000 + 100 SP" },
        },
        {
          number: 9,
          title: { ko: "속・나를 찾아줘", en: "Find Me Again" },
          chapter: { ko: "챕터 4~", en: "Chapter 4+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "8번 클리어 + 평판 Lv.35", en: "Clear Case 8, reach Lv.35 reputation." },
          body: { ko: "같은 의뢰인이 다시 「자신을 찾아달라」고 의뢰. 이번엔 더 깊은 정체성 갈등이 얽혀 있어, 결말 선택지에서 의뢰인의 미래를 결정해야 합니다.", en: "The same client returns with a deeper identity crisis. A final choice locks in her future." },
          choices: [
            { prompt: { ko: "「앞으로 어떻게 살아야 할까요?」", en: "'How should I live now?'" }, correct: { ko: "있는 그대로의 자신으로", en: "As your true self" } },
          ],
          reward: { ko: "80,000엔 + 150 SP", en: "¥80,000 + 150 SP" },
        },
        {
          number: 10,
          title: { ko: "속속・나를 찾아줘", en: "Find Me, One More Time" },
          chapter: { ko: "챕터 6~", en: "Chapter 6+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "9번 클리어 + 평판 Lv.45", en: "Clear Case 9, reach Lv.45 reputation." },
          body: { ko: "「나를 찾아줘」 3부작 완결. 의뢰인과의 마지막 만남에서 야가미가 탐정으로서 결론을 내리는 감동 에피소드.", en: "The trilogy's closer. Yagami delivers a final detective verdict in a quietly emotional sendoff." },
          reward: { ko: "100,000엔 + 200 SP", en: "¥100,000 + 200 SP" },
        },
        {
          number: 11,
          title: { ko: "나의 귀여운 부하", en: "My Adorable Subordinate" },
          chapter: { ko: "챕터 2~", en: "Chapter 2+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 게시판", en: "Detective Agency bulletin board" },
          trigger: { ko: "챕터 2 이후 + 평판 Lv.5", en: "Chapter 2+, Lv.5 reputation." },
          body: { ko: "젊은 사원의 OJT 교육을 부탁받는 의뢰. 거리에서 신입에게 인생 조언을 해주는 가벼운 컨버세이션 케이스.", en: "A boss asks Yagami to mentor a green hire on the streets — light dialogue-driven case." },
          reward: { ko: "30,000엔 + 60 SP", en: "¥30,000 + 60 SP" },
        },
        {
          number: 12,
          title: { ko: "케이힌 동맹의 역습", en: "The Keihin Gang Strikes Back" },
          chapter: { ko: "챕터 7~", en: "Chapter 7+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "극장 광장 → 탐정 사무소", en: "Theater Square → Detective Agency" },
          trigger: { ko: "극장 광장 총격 이벤트 발생 + 위험도 상승 + 평판 Lv.50", en: "Trigger the Theater Square gunfire event, raise danger level, hit Lv.50 reputation." },
          body: { ko: "케이힌 동맹 잔당이 야가미를 노리고 카무로쵸 전역에서 매복. 대규모 보스 러시.", en: "Keihin Gang remnants ambush Yagami across Kamurocho in a series of boss-tier brawls." },
          reward: { ko: "200,000엔 + 300 SP", en: "¥200,000 + 300 SP" },
        },
        {
          number: 13,
          title: { ko: "최후의 의뢰", en: "The Final Request" },
          chapter: { ko: "엔드 콘텐츠", en: "Endgame" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "탐정 사무소 → 아시아 거리", en: "Detective Agency → Asia St." },
          trigger: { ko: "사이드 케이스 49건 클리어 + 거리 평판 Lv.50", en: "Clear 49 side cases, reach Street Reputation Lv.50." },
          body: {
            ko: "아몬 일족 자객 아몬 신과의 최종 결전. 4페이즈 + HP 게이지 7단으로 구성된 사이드 보스 최강전. 회복 아이템 풀 크래프트, EX 액션 단축키 세팅, 가드/회피 어려운 잡기 기술 위주 빌드가 권장.",
            en: "Showdown with Shin Amon — four phases, seven HP bars. Craft full healing stocks, set EX-action shortcuts, and lean on grapples that ignore guard/dodge.",
          },
          reward: { ko: "1,000,000엔 + 300 SP + 트로피 「카무로쵸의 정점」 + 「사이드 케이스 제패」", en: "¥1,000,000 + 300 SP + trophies 'Top of Kamurocho' and 'Side Case Master'" },
        },
      ],
    },
    {
      title: { ko: "BAR 텐더 의뢰", en: "Bar Tender Requests" },
      items: [
        {
          number: 14,
          title: { ko: "태양과 뱀파이어", en: "The Sun and the Vampire" },
          chapter: { ko: "챕터 3~", en: "Chapter 3+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "BAR 텐더", en: "Bar Tender" },
          trigger: { ko: "챕터 3 이후 BAR 텐더에서 마스터에게 말 걸기", en: "Talk to the master at Bar Tender from Chapter 3." },
          body: { ko: "「뱀파이어가 카무로쵸에 출몰한다」는 도시 전설을 조사. 밤거리에서 핏자국, 망토 차림 인물을 추적해 진상은 햇빛 알레르기 환자임을 밝혀냅니다.", en: "Investigate a 'vampire' rumor in Kamurocho. Blood smears and a caped figure lead to the truth — a man with sunlight allergy." },
          reward: { ko: "40,000엔 + 100 SP", en: "¥40,000 + 100 SP" },
        },
        {
          number: 15,
          title: { ko: "보도 카메라맨 야가미", en: "Photojournalist Yagami" },
          chapter: { ko: "챕터 5~", en: "Chapter 5+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "BAR 텐더", en: "Bar Tender" },
          trigger: { ko: "「허니 트랩」 클리어 + 히라누마 친구 이벤트 진행 + 평판 Lv.35", en: "Clear 'Honey Trap', advance Hiranuma's friend event, reach Lv.35 reputation." },
          body: { ko: "히라누마와 함께 보도 사진 특집을 위해 카무로쵸의 「진짜」 사건을 카메라에 담는 의뢰.", en: "Team up with Hiranuma to capture Kamurocho's seedy underside on camera for a magazine spread." },
          reward: { ko: "70,000엔 + 140 SP", en: "¥70,000 + 140 SP" },
        },
        {
          number: 16,
          title: { ko: "레이즈 모럴리티", en: "Raise Morality" },
          chapter: { ko: "챕터 6~", en: "Chapter 6+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "BAR 텐더", en: "Bar Tender" },
          trigger: { ko: "스토리 진행 + 평판 Lv.45", en: "Story progress, Lv.45 reputation." },
          body: { ko: "신흥 종교 단체 「레이즈 모럴리티」의 카무로쵸 잠입 조사. 신자 미행 + 본부 잠입 + 추리 시퀀스로 진행.", en: "Infiltrate a Kamurocho-based cult. Tail believers, sneak into HQ, and run a deduction sequence." },
          reward: { ko: "90,000엔 + 180 SP", en: "¥90,000 + 180 SP" },
        },
        {
          number: 17,
          title: { ko: "허니 트랩", en: "Honey Trap" },
          chapter: { ko: "챕터 6~", en: "Chapter 6+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "BAR 텐더", en: "Bar Tender" },
          trigger: { ko: "「팬티 교수」 클리어 + 챕터 6 + 평판 Lv.15", en: "Clear 'Professor Panty', reach Chapter 6 and Lv.15 reputation." },
          body: { ko: "외도 함정에 빠진 남편의 사진을 찍어달라는 부탁. 호텔 잠복 + 결정적 사진 촬영.", en: "Photograph a husband walking into a honey trap. Hotel stakeout + decisive shot." },
          reward: { ko: "60,000엔 + 120 SP", en: "¥60,000 + 120 SP" },
        },
        {
          number: 18,
          title: { ko: "잉어 부인 회 사건", en: "The Koi Wife Sashimi Case" },
          chapter: { ko: "챕터 6~", en: "Chapter 6+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "BAR 텐더", en: "Bar Tender" },
          trigger: { ko: "챕터 6 + 평판 Lv.25", en: "Chapter 6, Lv.25 reputation." },
          body: { ko: "아끼던 비단잉어가 회로 떠진 사건. 동네 회 가게 + 수상한 인물을 조사해 범인을 특정.", en: "A prized koi was butchered into sashimi. Canvas sushi shops and shady locals to ID the culprit." },
          reward: { ko: "60,000엔 + 130 SP", en: "¥60,000 + 130 SP" },
        },
        {
          number: 19,
          title: { ko: "다이아몬드의 눈을 가진 고양이", en: "The Cat with Diamond Eyes" },
          chapter: { ko: "챕터 3~", en: "Chapter 3+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "BAR 텐더", en: "Bar Tender" },
          trigger: { ko: "챕터 3 + 평판 Lv.5", en: "Chapter 3, Lv.5 reputation." },
          body: { ko: "다이아몬드 눈을 가진 고양이를 찾아달라는 의뢰. 골목길 추적 + 미끼 먹이 사용.", en: "Track down a cat allegedly fitted with diamond eyes — alley chase plus a bait setup." },
          reward: { ko: "40,000엔 + 80 SP", en: "¥40,000 + 80 SP" },
        },
        {
          number: 20,
          title: { ko: "부탁할 일이 있다", en: "I've Got a Job for You" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "BAR 텐더", en: "Bar Tender" },
          trigger: { ko: "챕터 3 스토리 진행 중 자동 발생", en: "Auto-triggers during Chapter 3 main story." },
          body: { ko: "BAR 텐더 시스템 자체를 풀어주는 튜토리얼 케이스. 마스터와의 첫 의뢰.", en: "The tutorial case that unlocks the Bar Tender request system." },
          reward: { ko: "20,000엔 + 50 SP", en: "¥20,000 + 50 SP" },
        },
      ],
    },
    {
      title: { ko: "겐다 법률사무소 의뢰", en: "Genda Law Office Requests" },
      items: [
        {
          number: 21,
          title: { ko: "유령 물건", en: "The Haunted Property" },
          chapter: { ko: "챕터 2~", en: "Chapter 2+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
          trigger: { ko: "챕터 2 이후 겐다에게 말 걸기", en: "Talk to Genda from Chapter 2 onward." },
          body: { ko: "임대 분쟁이 걸린 「유령 나오는 물건」을 조사. 야간 잠입 후 가짜 유령의 정체 폭로.", en: "Investigate a rental dispute over a 'haunted' apartment. A night stake-out exposes the fake ghost." },
          reward: { ko: "40,000엔 + 100 SP", en: "¥40,000 + 100 SP" },
        },
        {
          number: 22,
          title: { ko: "탐정의 방식", en: "A Detective's Method" },
          chapter: { ko: "챕터 4~", en: "Chapter 4+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
          trigger: { ko: "챕터 2 이후 + 평판 Lv.40", en: "Chapter 2+, Lv.40 reputation." },
          body: { ko: "라이벌 탐정과 같은 사건을 두고 추리 경쟁. 누가 먼저 진범을 특정하는지가 관건.", en: "Race a rival detective to crack the same case first." },
          reward: { ko: "90,000엔 + 180 SP", en: "¥90,000 + 180 SP" },
        },
        {
          number: 23,
          title: { ko: "돈거래는 불화의 근원", en: "Lending Money, Losing Friends" },
          chapter: { ko: "챕터 3~", en: "Chapter 3+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
          trigger: { ko: "챕터 2 이후 + 평판 Lv.30", en: "Chapter 2+, Lv.30 reputation." },
          body: { ko: "친구 사이의 차용 분쟁 조정. 양측 증언 + 차용서 확인 후 야가미가 화해 또는 법적 조치를 권합니다.", en: "Mediate a loan dispute between friends. Collect both sides' testimony, check the IOU, then push for either reconciliation or legal action." },
          reward: { ko: "50,000엔 + 110 SP", en: "¥50,000 + 110 SP" },
        },
        {
          number: 24,
          title: { ko: "아들의 며느리는 악마?", en: "Is My Son's Wife a Demon?" },
          chapter: { ko: "챕터 3~", en: "Chapter 3+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
          trigger: { ko: "챕터 2 이후 + 평판 Lv.20", en: "Chapter 2+, Lv.20 reputation." },
          body: { ko: "「며느리가 우리 아들을 학대한다」는 시어머니 의뢰. 잠복하면 오해였음이 밝혀지는 따뜻한 결말.", en: "A mother-in-law insists her daughter-in-law is abusing her son. A stake-out reveals the truth and ends warmly." },
          reward: { ko: "50,000엔 + 100 SP", en: "¥50,000 + 100 SP" },
        },
        {
          number: 25,
          title: { ko: "남편의 외출처", en: "Where Does Hubby Go?" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
          trigger: { ko: "챕터 2 스토리 진행 중 자동 발생 (튜토리얼)", en: "Auto-triggers in Chapter 2 main story (tutorial)." },
          body: { ko: "외도 조사 튜토리얼. 미행/사진/추리 탐정 액션을 처음 학습하는 케이스.", en: "Adultery investigation tutorial — first lesson in tailing, photo, and deduction." },
          reward: { ko: "20,000엔 + 60 SP + 사이드 케이스 시스템 해금", en: "¥20,000 + 60 SP + unlocks the side case system" },
        },
        {
          number: 26,
          title: { ko: "사오리 씨의 생크림 재판", en: "Saori's Whipped Cream Trial" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
          trigger: { ko: "챕터 4 스토리 진행 중 자동 발생", en: "Auto-triggers during Chapter 4." },
          body: { ko: "겐다 사무소 비서 사오리가 휘말린 위자료 재판을 야가미가 증거 수집으로 지원.", en: "Help Genda's secretary Saori win an absurd damages trial by gathering evidence." },
          reward: { ko: "50,000엔 + 120 SP", en: "¥50,000 + 120 SP" },
        },
        {
          number: 27,
          title: { ko: "숙명의 사제 대결", en: "Mentor vs. Disciple" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "겐다 법률사무소 → 법정", en: "Genda Law Office → Courtroom" },
          trigger: { ko: "챕터 4 스토리 진행 중 자동 발생", en: "Auto-triggers during Chapter 4." },
          body: { ko: "야가미의 변호사 시절 스승과 법정에서 격돌. 증거 제시 미니게임 + 추리 결정타.", en: "Square off with Yagami's old legal mentor in court — evidence-submission minigame plus a finishing deduction." },
          reward: { ko: "80,000엔 + 200 SP", en: "¥80,000 + 200 SP" },
        },
      ],
    },
    {
      title: { ko: "스토리 연동 케이스 28~32", en: "Story-Linked Cases 28-32" },
      items: [
        {
          number: 28,
          title: { ko: "개막, 드론 레이스!", en: "Drone Race, Begin!" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 드론 레이스장", en: "Kamurocho — Drone Race Arena" },
          trigger: { ko: "챕터 2 스토리 진행 중 자동 발생", en: "Auto-triggers in Chapter 2." },
          body: { ko: "드론 레이스 미니게임 해금 사이드 케이스. 첫 레이스를 클리어하면 본격 트랙들이 열립니다.", en: "Unlocks the Drone Race minigame. Clearing the intro race opens the full track list." },
          reward: { ko: "초보자용 드론 + 30,000엔 + 80 SP", en: "Starter drone + ¥30,000 + 80 SP" },
        },
        {
          number: 29,
          title: { ko: "VR 살롱 파라다이스 오픈", en: "VR Salon Paradise Opens" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — VR 살롱", en: "Kamurocho — VR Salon" },
          trigger: { ko: "챕터 3 스토리 진행 중 자동 발생", en: "Auto-triggers in Chapter 3." },
          body: { ko: "VR 보드게임 미니게임 해금. 첫 게임을 클리어하면 모든 보드가 풀립니다.", en: "Unlocks the VR board-game minigame. Beat the intro game to open all boards." },
          reward: { ko: "30,000엔 + 80 SP + VR 보드게임 해금", en: "¥30,000 + 80 SP + VR board game unlocked" },
        },
        {
          number: 30,
          title: { ko: "마리 누나의 비밀", en: "Big Sis Mari's Secret" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 스미레/마리 누나 가게", en: "Kamurocho — Mari's hostess club" },
          trigger: { ko: "챕터 4 스토리 진행 중 자동 발생", en: "Auto-triggers in Chapter 4." },
          body: { ko: "호스티스 클럽 마마 「마리 누나」의 비밀을 캐는 케이스. 친구 이벤트로 이어집니다.", en: "Probe the secret behind hostess-club mama 'Big Sis Mari'. Bridges into her friend event line." },
          reward: { ko: "50,000엔 + 120 SP + 마리 누나 친구 이벤트 진행", en: "¥50,000 + 120 SP + Mari friend-event progress" },
        },
        {
          number: 31,
          title: { ko: "카이토의 파트너", en: "Kaito's Partner" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 카이토 사무실 인근", en: "Kamurocho — near Kaito's office" },
          trigger: { ko: "챕터 6 스토리 진행 중 자동 발생", en: "Auto-triggers in Chapter 6." },
          body: { ko: "카이토가 한때 짝을 이뤘던 야쿠자 친구의 의뢰. 카이토와 야가미가 함께 거리를 누비는 버디 액션 회.", en: "A request from Kaito's old yakuza partner. Buddy-action chapter with both characters on the streets." },
          reward: { ko: "100,000엔 + 200 SP", en: "¥100,000 + 200 SP" },
        },
        {
          number: 32,
          title: { ko: "정의의 히어로・카이토 마사하루", en: "Justice Hero Masaharu Kaito" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 곳곳", en: "Various Kamurocho spots" },
          trigger: { ko: "챕터 7 스토리 진행 중 자동 발생", en: "Auto-triggers in Chapter 7." },
          body: { ko: "카이토가 「히어로 활동」에 빠지는 코믹 사이드 케이스. 시민 SOS 4~5건을 함께 해결.", en: "Kaito goes full superhero mode in a comic side case where you clear 4–5 citizen SOS calls together." },
          reward: { ko: "120,000엔 + 250 SP", en: "¥120,000 + 250 SP" },
        },
      ],
    },
    {
      title: { ko: "길거리 조우 케이스 33~50", en: "Street Encounters 33-50" },
      items: [
        {
          number: 33,
          title: { ko: "쏟아지는 재앙의 정체는?", en: "What Falls From Above?" },
          chapter: { ko: "챕터 5~", en: "Chapter 5+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "쇼와 거리", en: "Showa St." },
          trigger: { ko: "챕터 5 이후 길거리 조우 (머리 위에서 물건 낙하 이벤트)", en: "Chapter 5+ street encounter — object falls from above." },
          body: { ko: "고층에서 화분/물병이 떨어지는 사건. 낙하 지점을 분석해 발신지를 추적.", en: "Plant pots and water bottles keep landing on pedestrians — trace the trajectory to the source." },
          reward: { ko: "40,000엔 + 100 SP", en: "¥40,000 + 100 SP" },
        },
        {
          number: 34,
          title: { ko: "속・쏟아지는 재앙의 정체는?", en: "Falling Disasters II" },
          chapter: { ko: "챕터 6~", en: "Chapter 6+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "텐카이 거리", en: "Tenkaichi St." },
          trigger: { ko: "33번 클리어 후 거리에서 재발생", en: "After Case 33, re-encounter on the street." },
          body: { ko: "재앙이 더 위험해진 2탄. 진범 후보가 늘어남.", en: "Round two with bigger hazards and more suspects." },
          reward: { ko: "60,000엔 + 130 SP", en: "¥60,000 + 130 SP" },
        },
        {
          number: 35,
          title: { ko: "속속・쏟아지는 재앙의 정체는?", en: "Falling Disasters III" },
          chapter: { ko: "챕터 7~", en: "Chapter 7+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "나카미치 거리", en: "Nakamichi St." },
          trigger: { ko: "34번 클리어 후 거리에서 재발생", en: "After Case 34, re-encounter on the street." },
          body: { ko: "시리즈 완결. 진범의 동기와 함께 사건이 종결.", en: "Series wraps up with the motive revealed." },
          reward: { ko: "80,000엔 + 160 SP", en: "¥80,000 + 160 SP" },
        },
        {
          number: 36,
          title: { ko: "카무로쵸의 폭탄마", en: "The Kamurocho Bomber" },
          chapter: { ko: "챕터 2~", en: "Chapter 2+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 게시판 부근", en: "Kamurocho — public bulletin areas" },
          trigger: { ko: "챕터 2 이후 길거리 조우", en: "Chapter 2+ street encounter." },
          body: { ko: "폭탄 예고 포스터가 곳곳에 붙는 사건. 단서 사진을 모아 폭탄 위치를 추리.", en: "Bomb-threat posters spring up across town — collect them and deduce the target." },
          reward: { ko: "40,000엔 + 100 SP", en: "¥40,000 + 100 SP" },
        },
        {
          number: 37,
          title: { ko: "속・카무로쵸의 폭탄마", en: "The Bomber Returns" },
          chapter: { ko: "챕터 4~", en: "Chapter 4+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 새로운 폭탄 예고지", en: "Kamurocho — new threat sites" },
          trigger: { ko: "36번 클리어 후 발생", en: "After Case 36." },
          body: { ko: "폭탄마가 진화. 폭탄 해체 미니게임 + 추리.", en: "Bomber escalates with a defusal minigame layered onto the deduction." },
          reward: { ko: "60,000엔 + 130 SP", en: "¥60,000 + 130 SP" },
        },
        {
          number: 38,
          title: { ko: "속속・카무로쵸의 폭탄마", en: "Bomber Trilogy Finale" },
          chapter: { ko: "챕터 6~", en: "Chapter 6+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 마지막 폭탄 거점", en: "Kamurocho — final bomb site" },
          trigger: { ko: "37번 클리어 후 발생", en: "After Case 37." },
          body: { ko: "폭탄마 본거지 돌입. 보스 전투 + 마지막 해체.", en: "Storm the bomber's hideout — boss fight plus a last-second defusal." },
          reward: { ko: "100,000엔 + 200 SP", en: "¥100,000 + 200 SP" },
        },
        {
          number: 39,
          title: { ko: "꿈의 도중", en: "Halfway to the Dream" },
          chapter: { ko: "챕터 3~", en: "Chapter 3+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 거리", en: "Kamurocho — street" },
          trigger: { ko: "챕터 3 이후 + 애인 이벤트 진행", en: "Chapter 3+, girlfriend event progress." },
          body: { ko: "꿈을 좇다 좌절한 청년의 인생 상담. 다정한 권유로 다시 도전할 의지를 회복시켜 줍니다.", en: "Counsel a young man whose dream stalled. Nudge him back toward trying again." },
          reward: { ko: "50,000엔 + 100 SP", en: "¥50,000 + 100 SP" },
        },
        {
          number: 40,
          title: { ko: "산들바람과 함께 사라지다", en: "Gone with the Breeze" },
          chapter: { ko: "챕터 3~", en: "Chapter 3+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 골목길", en: "Kamurocho — alleyways" },
          trigger: { ko: "챕터 3 이후 길거리 조우", en: "Chapter 3+ street encounter." },
          body: { ko: "바람에 날려간 중요한 종이를 추적하는 짧은 추격 케이스 1편.", en: "Chase down a wind-blown important document. Part one of a three-case chain." },
          reward: { ko: "30,000엔 + 80 SP", en: "¥30,000 + 80 SP" },
        },
        {
          number: 41,
          title: { ko: "속・산들바람과 함께 사라지다", en: "Gone with the Breeze II" },
          chapter: { ko: "챕터 4~", en: "Chapter 4+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 골목길", en: "Kamurocho — alleyways" },
          trigger: { ko: "40번 클리어 후 발생", en: "After Case 40." },
          body: { ko: "다른 인물이 똑같이 종이를 날려버립니다. 동일한 추격 패턴.", en: "Different person, same wind problem — repeat the chase." },
          reward: { ko: "40,000엔 + 100 SP", en: "¥40,000 + 100 SP" },
        },
        {
          number: 42,
          title: { ko: "속속・산들바람과 함께 사라지다", en: "Gone with the Breeze III" },
          chapter: { ko: "챕터 5~", en: "Chapter 5+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 골목길", en: "Kamurocho — alleyways" },
          trigger: { ko: "41번 클리어 후 발생", en: "After Case 41." },
          body: { ko: "시리즈 완결. 세 사건이 사실은 같은 인물이 일으킨 일임이 드러나는 반전.", en: "Finale — twist reveals the three incidents share a single culprit." },
          reward: { ko: "60,000엔 + 130 SP", en: "¥60,000 + 130 SP" },
        },
        {
          number: 43,
          title: { ko: "스마트폰 탐정", en: "Smartphone Sleuth" },
          chapter: { ko: "챕터 8~", en: "Chapter 8+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 밤거리", en: "Kamurocho — at night" },
          trigger: { ko: "챕터 8 이후 야간 + 애인 이벤트 진행", en: "Chapter 8+ at night, girlfriend event progress." },
          body: { ko: "스마트폰만으로 사건을 해결한다는 자칭 탐정 소년에게 진짜 탐정 일을 가르치는 케이스.", en: "Teach a self-styled 'phone-only detective' kid how real legwork is done." },
          reward: { ko: "70,000엔 + 140 SP", en: "¥70,000 + 140 SP" },
        },
        {
          number: 44,
          title: { ko: "변태왕: 자이언트 임팩트", en: "Pervert King: Giant Impact" },
          chapter: { ko: "챕터 8~", en: "Chapter 8+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 거리", en: "Kamurocho — street" },
          trigger: { ko: "챕터 8 이후 + 애인 이벤트 진행 + 변태 삼총사 완료", en: "Chapter 8+, girlfriend event progress, Perv Trinity cleared." },
          body: { ko: "변태 삼총사를 잡은 야가미 앞에 진짜 「변태왕」이 등장. 보스급 변태 추격 + 추리.", en: "After the Perv Trinity falls, the true 'Pervert King' shows up for a boss-tier tail and deduction." },
          reward: { ko: "150,000엔 + 250 SP + 「변태왕」 트로피", en: "¥150,000 + 250 SP + 'Pervert King' trophy" },
        },
        {
          number: 45,
          title: { ko: "바가지 술집", en: "The Rip-off Bar" },
          chapter: { ko: "챕터 4~", en: "Chapter 4+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "챔피언 거리", en: "Champion St." },
          trigger: { ko: "챕터 4 이후 챔피언 거리 호객꾼 조우", en: "Chapter 4+, encounter a tout on Champion St." },
          body: { ko: "호객꾼에게 끌려간 바가지 술집에서 부당 청구를 받고, 증거 사진으로 점포를 무너뜨립니다.", en: "Get dragged into a rip-off bar, hit with absurd bills, then bring it down with photo evidence." },
          reward: { ko: "50,000엔 + 100 SP", en: "¥50,000 + 100 SP" },
        },
        {
          number: 46,
          title: { ko: "탈옥범", en: "The Escaped Convict" },
          chapter: { ko: "챕터 8~", en: "Chapter 8+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 변두리", en: "Kamurocho — outskirts" },
          trigger: { ko: "챕터 8 이후 길거리 조우", en: "Chapter 8+ street encounter." },
          body: { ko: "탈옥한 흉악범이 카무로쵸로 숨어든 사건. 추적 + 보스 전투.", en: "An escaped felon hides out in Kamurocho — chase him down for a boss fight." },
          reward: { ko: "100,000엔 + 200 SP", en: "¥100,000 + 200 SP" },
        },
        {
          number: 47,
          title: { ko: "와이프의 버스데이", en: "The Wife's Birthday" },
          chapter: { ko: "챕터 5~", en: "Chapter 5+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 쇼핑가", en: "Kamurocho — shopping street" },
          trigger: { ko: "챕터 5 이후 길거리 조우", en: "Chapter 5+ street encounter." },
          body: { ko: "아내 생일 선물을 못 고르는 남편을 도와 적절한 선물을 추천. 가게 안내 케이스.", en: "Help a flustered husband pick a birthday gift for his wife — shop-tour case." },
          reward: { ko: "40,000엔 + 100 SP", en: "¥40,000 + 100 SP" },
        },
        {
          number: 48,
          title: { ko: "강도범・오노 미치오", en: "Robber Michio Ono" },
          chapter: { ko: "챕터 6~", en: "Chapter 6+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 편의점 주변", en: "Kamurocho — near a convenience store" },
          trigger: { ko: "챕터 6 이후 길거리 조우", en: "Chapter 6+ street encounter." },
          body: { ko: "편의점 강도 현장에 야가미가 우연히 도착. 범인 추격 + 제압.", en: "Walk into a convenience-store robbery mid-act — chase and subdue the robber." },
          reward: { ko: "60,000엔 + 130 SP", en: "¥60,000 + 130 SP" },
        },
        {
          number: 49,
          title: { ko: "마모루의 실종?", en: "Mamoru's Disappearance?" },
          chapter: { ko: "챕터 7~", en: "Chapter 7+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 어린이 공원 부근", en: "Kamurocho — near the kids' park" },
          trigger: { ko: "챕터 7 이후 길거리 조우", en: "Chapter 7+ street encounter." },
          body: { ko: "사라진 아이 마모루를 찾는 의뢰. 카무로쵸 곳곳 미아 단서를 모아 발견.", en: "Hunt for a missing kid named Mamoru, piecing together leads across Kamurocho." },
          reward: { ko: "80,000엔 + 160 SP", en: "¥80,000 + 160 SP" },
        },
        {
          number: 50,
          title: { ko: "벼랑 끝의 조사 의뢰", en: "Cliff's-Edge Investigation" },
          chapter: { ko: "챕터 9~", en: "Chapter 9+" },
          protagonist: { ko: "야가미", en: "Yagami" },
          location: { ko: "카무로쵸 — 외곽", en: "Kamurocho — outskirts" },
          trigger: { ko: "엔드게임 + 평판 Lv.50 직전", en: "Endgame, approaching Lv.50 reputation." },
          body: { ko: "「최후의 의뢰」 전 마지막 통상 사이드 케이스. 진실에 가까이 다가갈수록 위험이 커지는 잠입 조사.", en: "The last regular side case before 'The Final Request' — an infiltration that gets riskier the closer you get to the truth." },
          reward: { ko: "150,000엔 + 280 SP + 「최후의 의뢰」 해금 진행", en: "¥150,000 + 280 SP + progress toward unlocking 'The Final Request'" },
        },
      ],
    },
  ],
};
