import type { SubstoriesData } from "./types";

export const yakuzaGaidenSubstories: SubstoriesData = {
  appId: 2375550,
  summary: {
    ko: "「용과 같이 외전: 이름을 지운 남자」의 서브스토리는 사실상 아카메 네트워크 의뢰로 통합되어 있습니다. 2장 초반 「긴급 의뢰!」를 클리어해 아카메 네트워크가 해금된 뒤, 의뢰 미션(약 22건)을 받아 진행하면 됩니다. 트리거는 모두 카무로초 지하의 아카메 네트워크 본부 또는 길거리 단말기에서 「아카메 네트워크에서 의뢰 수락」으로 동일합니다. 의뢰를 클리어할 때마다 아카메 포인트와 거액의 보수를 받으며, 일부 의뢰는 조란회의 신규 멤버(가토, 아즈마, 야마나카 등)를 영입하는 조건이 됩니다. 본 목록은 길거리 「아카메 순회(외근)」 미니 의뢰와는 구분되는 정식 의뢰 미션만 다룹니다.",
    en: "Gaiden's substories are folded into the Akame Network request system. Once Chapter 2's 'Emergency Request!' unlocks the Network, you can accept the ~22 numbered request missions from the Akame HQ basement or any street terminal — all share the same trigger ('Accept request from the Akame Network'). Each mission grants Akame Points plus a sizeable yen reward, and several gate Coliseum team recruits (Kato, Azuma, Yamanaka, etc.). This list covers the formal request missions only, not the smaller patrol (Akame Junkai) errands.",
  },
  source: {
    label: "game8.jp — 龍が如く7外伝 赤目ネットワーク依頼一覧",
    url: "https://game8.jp/ryu-ga-gotoku-gaiden/574644",
  },
  groups: [
    {
      title: { ko: "아카메 네트워크 — 입문 (해금/Lv.10)", en: "Akame Network — Intro (Unlock / Lv.10)" },
      items: [
        {
          number: 1,
          title: { ko: "긴급 의뢰!", en: "Emergency Request!" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 캬바쿠라 「헤븐리」", en: "Kamurocho — Cabaret 'Heavenly'" },
          trigger: { ko: "2장 메인 진행 중 아카메로부터 자동 발생 (아카메 네트워크 해금 의뢰)", en: "Auto-triggered by Akame during Chapter 2 — the mission that unlocks the Akame Network." },
          body: { ko: "헤븐리에서 도망친 호스티스를 보호하라는 의뢰. 가게로 향해 난입한 삥쟁이들을 쓸어버리고 점주를 진정시키면 아카메 네트워크 본격 가동 + 의뢰 게시판 해금.", en: "Save a hostess hiding in Club Heavenly. Storm the venue, clear the thugs, calm the manager — the Akame Network and its full request board unlock on completion." },
          reward: { ko: "10만 엔 + 아카메 포인트 1,000", en: "¥100,000 + 1,000 Akame Points" },
        },
        {
          number: 2,
          title: { ko: "동향 조사 의뢰", en: "Surveillance Request" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 쇼와 거리 일대", en: "Kamurocho — Showa St. area" },
          trigger: { ko: "아카메 네트워크 본부에서 「아카메 네트워크에서 의뢰 수락」", en: "Akame HQ — 'Accept request from the Akame Network.'" },
          body: { ko: "표적 인물의 동선을 추적해 사진을 찍는 의뢰. 스파이더 카메라로 표적을 줌인해 촬영하면 클리어. 표적은 거리 카페→골목→공원 순으로 이동.", en: "Tail a target and photograph him with the Spider Camera. He walks café → alley → park — line up a clean zoom shot at the final stop to clear." },
          reward: { ko: "30만 엔 + 아카메 포인트 3,000", en: "¥300,000 + 3,000 Akame Points" },
        },
        {
          number: 3,
          title: { ko: "촬영 어시스턴트 급구", en: "Photography Assistant Wanted" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 스마일 버거 2층", en: "Kamurocho — Smile Burger 2F" },
          trigger: { ko: "스마일 버거 2층의 의뢰인에게 말 걸기 (네트워크 의뢰)", en: "Speak to the client on Smile Burger's 2F (Network request)." },
          body: { ko: "도촬 의혹을 사고 있는 사진작가를 도와 「오해를 풀어줄 사진」을 찍는 임무. 지정된 길거리 풍경 3컷을 가이드 프레임에 맞춰 촬영하면 종료.", en: "Help a photographer accused of stalking by snapping three staged 'innocent' street shots matching the guide frame." },
          reward: { ko: "30만 엔 + 아카메 포인트 3,000", en: "¥300,000 + 3,000 Akame Points" },
        },
        {
          number: 4,
          title: { ko: "갱 팀 「홍공작」을 격파하라", en: "Crush the Crimson Peacock Gang" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 텐카이치 거리 외 3곳", en: "Kamurocho — Tenkaichi St. and 3 other spots" },
          trigger: { ko: "아카메 네트워크 의뢰 게시판에서 수락", en: "Accept from the Akame Network request board." },
          body: { ko: "거리에서 활보하는 홍공작 멤버 4팀을 차례로 제압. 모두 일반 삥쟁이 수준이라 야쿠자 스타일로 빠르게 정리 가능. 마지막 표적 격파 시 자동 클리어.", en: "Hunt four roaming Crimson Peacock cells around Kamurocho. They are mid-tier street goons — Yakuza style chews through them. The mission ends when the last cell falls." },
          reward: { ko: "30만 엔 + 아카메 포인트 3,000", en: "¥300,000 + 3,000 Akame Points" },
        },
      ],
    },
    {
      title: { ko: "아카메 네트워크 — 중반", en: "Akame Network — Mid (around Lv.30)" },
      items: [
        {
          number: 5,
          title: { ko: "간단한 힘쓰는 일입니다", en: "Just a Bit of Heavy Lifting" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 챔피언 거리", en: "Kamurocho — Champion District" },
          trigger: { ko: "팀 배틀 해금 후 네트워크 의뢰 수락", en: "After Team Battle unlocks, accept from the Network board." },
          body: { ko: "건달들에게 둘러싸인 운반업자를 호위. 3개 구역을 따라 이동하며 도중에 끼어드는 삥쟁이 무리를 모두 처리해야 종료된다.", en: "Escort a courier through three checkpoints, clearing each ambush of street toughs that jumps him along the way." },
          reward: { ko: "50만 엔 + 아카메 포인트 8,000", en: "¥500,000 + 8,000 Akame Points" },
        },
        {
          number: 6,
          title: { ko: "소텐보리의 망령", en: "Ghost of Soutenbori" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 폐가 골목", en: "Kamurocho — Abandoned alley" },
          trigger: { ko: "팀 배틀 해금 후 네트워크 의뢰 수락", en: "After Team Battle unlocks, accept from the Network board." },
          body: { ko: "소텐보리에서 흘러온 정체불명의 깡패가 동네에서 행패를 부린다는 신고. 지정 골목에서 등장하는 보스급 적을 1:1로 제압하면 완료.", en: "A drifter from Soutenbori is shaking down locals. Head to the marked alley and beat the boss-tier brawler in a 1v1." },
          reward: { ko: "50만 엔 + 아카메 포인트 8,000", en: "¥500,000 + 8,000 Akame Points" },
        },
        {
          number: 7,
          title: { ko: "상담 좀 부탁드려요", en: "I Need Someone to Talk To" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 텐카이치 거리 카페", en: "Kamurocho — Tenkaichi café" },
          trigger: { ko: "팀 배틀 해금 후 네트워크 의뢰 수락", en: "After Team Battle unlocks, accept from the Network board." },
          body: { ko: "고민이 있다는 청년의 상담을 들어주는 의뢰. 대사 도중 선택지가 등장하며, 무조건 「힘이 되어준다」를 선택해야 다음 단계가 진행된다.", en: "A young man wants advice. A choice prompt appears mid-conversation — pick the supportive option to advance." },
          choices: [
            { prompt: { ko: "「제 얘기 좀 들어주세요」", en: "'Will you hear me out?'" }, correct: { ko: "힘이 되어준다", en: "Lend a hand" } },
          ],
          reward: { ko: "50만 엔 + 아카메 포인트 8,000", en: "¥500,000 + 8,000 Akame Points" },
        },
        {
          number: 8,
          title: { ko: "금색의 무사", en: "The Golden Warrior" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 핑크 거리", en: "Kamurocho — Pink St." },
          trigger: { ko: "팀 배틀 해금 후 네트워크 의뢰 수락", en: "After Team Battle unlocks, accept from the Network board." },
          body: { ko: "갑옷 차림의 「금색 무사」가 거리에서 시민에게 시비를 건다. 발견 즉시 격투 → 무사의 패턴은 강력한 가드 위주이므로 야쿠자 스타일의 잡기로 무너뜨리는 것이 정석.", en: "A man in golden armor is harassing pedestrians on Pink St. Engage him directly — his strong guard yields cleanly to Yakuza-style grapples." },
          reward: { ko: "50만 엔 + 아카메 포인트 8,000", en: "¥500,000 + 8,000 Akame Points" },
        },
        {
          number: 9,
          title: { ko: "홈리스 야마나카를 동료로 만들어라", en: "Recruit Yamanaka the Homeless" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 강변 공원", en: "Kamurocho — Riverside park" },
          trigger: { ko: "팀 배틀 해금 후 네트워크 의뢰 수락", en: "After Team Battle unlocks, accept from the Network board." },
          body: { ko: "야마나카 노인을 영입하려면 그를 괴롭히던 삥쟁이 일당을 격파해야 한다. 전투 후 자동으로 콜로세움 팀에 합류.", en: "To bring Yamanaka into the Coliseum stable, wipe out the gang of toughs hassling him. He joins your team automatically after the fight." },
          reward: { ko: "동료 「야마나카」 영입 + 아카메 포인트 4,000", en: "Recruit 'Yamanaka' + 4,000 Akame Points" },
        },
        {
          number: 10,
          title: { ko: "최강의 편의점 점원", en: "The Strongest Convenience Clerk" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 포포 편의점", en: "Kamurocho — POPPO convenience store" },
          trigger: { ko: "팀 배틀 해금 후 네트워크 의뢰 수락", en: "After Team Battle unlocks, accept from the Network board." },
          body: { ko: "포포 점원이 강도 두 팀에게 연속으로 습격당한다. 2연속 배틀에서 모두 승리하면 점원이 콜로세움 합류 의사를 표명.", en: "A POPPO clerk is hit by two consecutive holdup crews. Win both back-to-back fights and the clerk volunteers for the Coliseum." },
          reward: { ko: "동료 영입 + 아카메 포인트 4,000", en: "New Coliseum teammate + 4,000 Akame Points" },
        },
        {
          number: 11,
          title: { ko: "해머 남자를 해방시켜라", en: "Free the Hammer Man" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카무로초 — 지하 주차장", en: "Kamurocho — Underground parking" },
          trigger: { ko: "팀 배틀 해금 후 네트워크 의뢰 수락", en: "After Team Battle unlocks, accept from the Network board." },
          body: { ko: "지하 주차장에 감금된 거구의 「해머 남자」를 구출하는 의뢰. 감시조 두 무리를 차례대로 격파하면 해머 남자가 콜로세움 동료로 합류.", en: "Bust the hulking 'Hammer Man' out of an underground lockup. Beat the two guard squads in order to recruit him to your Coliseum team." },
          reward: { ko: "동료 영입 + 아카메 포인트 4,000", en: "New Coliseum teammate + 4,000 Akame Points" },
        },
        {
          number: 12,
          title: { ko: "홍공작과의 최종 결전에서 승리하라", en: "Win the Final Battle vs. the Crimson Peacock" },
          chapter: { ko: "2~3장", en: "Chapter 2~3" },
          location: { ko: "카무로초 — 옥상 헬리포트", en: "Kamurocho — Rooftop helipad" },
          trigger: { ko: "의뢰 4(홍공작 격파) 완료 후 네트워크에서 후속 의뢰 수락", en: "Accept the follow-up after completing Request #4 (Crimson Peacock)." },
          body: { ko: "홍공작의 두목 구렌 아키요시와 일대일 결착. 두목 격파 후 동료 영입 대사가 발생.", en: "Square off solo with Guren Akiyoshi, the Crimson Peacock boss. He joins your team after defeat." },
          reward: { ko: "동료 「구렌 아키요시」 영입 + 30만 엔 + 아카메 포인트 3,000", en: "Recruit 'Guren Akiyoshi' + ¥300,000 + 3,000 Akame Points" },
        },
        {
          number: 13,
          title: { ko: "갱 팀 「백기사」를 격파하라", en: "Crush the White Knight Gang" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "카무로초 — 시내 4곳", en: "Kamurocho — 4 city spots" },
          trigger: { ko: "콜로세움 실버 랭크 도달 후 네트워크 의뢰 수락", en: "Reach Coliseum Silver Rank, then accept the Network request." },
          body: { ko: "갑주를 두른 백기사 단원 4팀을 차례로 분쇄. 본대보다 가드가 단단하므로 회피 후 카운터 위주가 안정적.", en: "Stomp four squads of armored White Knight grunts. Their guard is heavy — dodge then counter rather than trading blows." },
          reward: { ko: "50만 엔 + 아카메 포인트 8,000", en: "¥500,000 + 8,000 Akame Points" },
        },
      ],
    },
    {
      title: { ko: "아카메 네트워크 — 종반", en: "Akame Network — Endgame (Lv.50 / Platinum)" },
      items: [
        {
          number: 14,
          title: { ko: "백기사와의 최종 결전에서 승리하라", en: "Win the Final Battle vs. the White Knight" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "카무로초 — 옥상", en: "Kamurocho — Rooftop" },
          trigger: { ko: "의뢰 13 클리어 후 네트워크에서 후속 의뢰 수락", en: "After clearing Request #13, accept the follow-up." },
          body: { ko: "백기사 두목 시라니타 코지와 결착. 두목은 대형 무기로 광역 공격을 날리므로 거리를 두고 에이전트 스타일 가젯이 유효.", en: "Duel the White Knight's boss, Koji Shiranita. He swings a heavy weapon in wide arcs — kite him with Agent gadgets." },
          reward: { ko: "동료 「시라니타 코지」 영입 + 50만 엔 + 아카메 포인트 8,000", en: "Recruit 'Koji Shiranita' + ¥500,000 + 8,000 Akame Points" },
        },
        {
          number: 15,
          title: { ko: "피해를 막아라", en: "Stop the Damage" },
          chapter: { ko: "3~4장", en: "Chapter 3~4" },
          location: { ko: "카무로초 — 다구역", en: "Kamurocho — multiple zones" },
          trigger: { ko: "콜로세움 골드 랭크 도달 후 네트워크 의뢰 수락", en: "Reach Coliseum Gold Rank, then accept the Network request." },
          body: { ko: "도시 곳곳에서 동시 다발적으로 발생한 폭력 사태를 진압. 표시된 3개 구역을 차례로 돌며 적 그룹을 일소하면 가토와 아즈마가 합류한다.", en: "Quell simultaneous brawls in three flagged districts. Sweep each in turn — Masaji Kato and Tetsu Azuma join the team once all are cleared." },
          reward: { ko: "동료 「가토 마사지·아즈마 테츠」 영입 + 100만 엔 + 아카메 포인트 15,000", en: "Recruit 'Masaji Kato & Tetsu Azuma' + ¥1,000,000 + 15,000 Akame Points" },
        },
        {
          number: 16,
          title: { ko: "금색 구슬을 7개, 시간 나면 모아줘", en: "Grab Seven Golden Balls When You Have Time" },
          chapter: { ko: "3~4장", en: "Chapter 3~4" },
          location: { ko: "카무로초 — 거리 전역", en: "Kamurocho — across the streets" },
          trigger: { ko: "콜로세움 골드 랭크 도달 후 네트워크 의뢰 수락", en: "Reach Coliseum Gold Rank, then accept the Network request." },
          body: { ko: "거리 곳곳에 숨겨진 황금 구슬 7개를 회수. 맵 표식이 뜨므로 장 진행 중 자연스럽게 회수 가능하다.", en: "Recover seven hidden golden orbs scattered across town. They show up as map pings, so most can be picked up while you handle other business." },
          reward: { ko: "100만 엔 + 아카메 포인트 15,000", en: "¥1,000,000 + 15,000 Akame Points" },
        },
        {
          number: 17,
          title: { ko: "금색의 재앙", en: "Golden Calamity" },
          chapter: { ko: "3~4장", en: "Chapter 3~4" },
          location: { ko: "카무로초 — 핑크 거리 광장", en: "Kamurocho — Pink St. plaza" },
          trigger: { ko: "의뢰 8 클리어 후 네트워크 의뢰 수락 (골드 랭크 권장)", en: "After clearing Request #8, accept the Network follow-up (Gold Rank recommended)." },
          body: { ko: "「금색 무사」의 상위 개체가 떼로 출현. 광범위 회복 아이템을 챙기고 광장 한가운데에서 에이전트 스타일의 시거폭탄/드론 콤보로 정리하는 것이 안정적.", en: "Upgraded Golden Warriors mob the plaza. Stock AoE recovery and lean on Agent's cigar bombs / drones from the center to thin them safely." },
          reward: { ko: "100만 엔 + 아카메 포인트 15,000", en: "¥1,000,000 + 15,000 Akame Points" },
        },
        {
          number: 18,
          title: { ko: "갱 팀 「흑호접」을 격파하라", en: "Crush the Black Swallowtail Gang" },
          chapter: { ko: "4장", en: "Chapter 4" },
          location: { ko: "카무로초 — 시내 4곳", en: "Kamurocho — 4 city spots" },
          trigger: { ko: "의뢰 14 클리어 후 네트워크 의뢰 수락", en: "After clearing Request #14, accept the Network request." },
          body: { ko: "흑호접 단원 4팀을 거리에서 차례로 격파. 마지막 팀은 무기 사용 빈도가 높으므로 무기 빼앗기 액션이 유효.", en: "Wipe out four roaming Black Swallowtail crews. The final squad spams weapons — disarm with weapon-snatch actions." },
          reward: { ko: "100만 엔 + 아카메 포인트 15,000", en: "¥1,000,000 + 15,000 Akame Points" },
        },
        {
          number: 19,
          title: { ko: "흑호접과의 최종 결전에서 승리하라", en: "Win the Final Battle vs. the Black Swallowtail" },
          chapter: { ko: "4장", en: "Chapter 4" },
          location: { ko: "카무로초 — 클럽 세가 옥상", en: "Kamurocho — Club SEGA rooftop" },
          trigger: { ko: "의뢰 18 클리어 후 네트워크에서 후속 의뢰 수락", en: "After clearing Request #18, accept the follow-up." },
          body: { ko: "두목 쿠로야나기 케이타와 일대일. 빠른 연타 콤보와 카운터를 사용하므로 패링 후 잡기 콤보가 가장 안정적.", en: "Duel boss Keita Kuroyanagi. He spams fast strings and counters, so parry-into-grab is the safest loop." },
          reward: { ko: "동료 「쿠로야나기 케이타」 영입 + 100만 엔 + 아카메 포인트 15,000", en: "Recruit 'Keita Kuroyanagi' + ¥1,000,000 + 15,000 Akame Points" },
        },
        {
          number: 20,
          title: { ko: "금색의 도전장", en: "Golden Challenge Letter" },
          chapter: { ko: "4장", en: "Chapter 4" },
          location: { ko: "카무로초 — 캐슬 옥상", en: "Kamurocho — Castle rooftop" },
          trigger: { ko: "콜로세움 플래티넘 랭크 도달 후 네트워크 의뢰 수락", en: "Reach Coliseum Platinum Rank, then accept the Network request." },
          body: { ko: "금색 시리즈의 마지막 자객이 도전장을 보낸다. 옥상에서 단독 결투. 적의 카운터가 매우 강력하므로 무리한 콤보보다 「에센스 오브 매치 액션」 활용이 필수.", en: "The last of the Golden challengers arrives. It is a solo rooftop duel — his counters are brutal, so lean on Essence of Match Actions over long combos." },
          reward: { ko: "200만 엔 + 아카메 포인트 30,000", en: "¥2,000,000 + 30,000 Akame Points" },
        },
        {
          number: 21,
          title: { ko: "고쿠소조 괴멸 작전", en: "Operation: Destroy the Gokuso-gumi" },
          chapter: { ko: "4장", en: "Chapter 4" },
          location: { ko: "카무로초 — 고쿠소조 본부", en: "Kamurocho — Gokuso-gumi HQ" },
          trigger: { ko: "사천왕 우카가미 키요시 격파 후 네트워크에서 의뢰 수락", en: "After defeating Four Kings member Kiyoshi Ukagami, accept from the Network." },
          body: { ko: "조란회 잔당을 일소하는 본 게임의 사실상 최종 의뢰. 본부 내부의 3 구역 연속 전투 후 보스러시. 콜로세움 동료를 풀로 모은 뒤 도전하는 것이 권장.", en: "The de-facto endgame request — clear out the remnants. Three sequential interior arenas followed by a boss rush; bring a fully-leveled Coliseum roster." },
          reward: { ko: "200만 엔 + 아카메 포인트 30,000", en: "¥2,000,000 + 30,000 Akame Points" },
        },
      ],
    },
  ],
};
