import type { SubstoriesData } from "./types";

export const likeADragonPirateSubstories: SubstoriesData = {
  appId: 3061810,
  summary: {
    ko: "총 31건. 마지마가 해적 삥쟁이로 변신한 외전답게 호놀룰루 시가지 미니게임 도입형 + 매들랜티스/해상 함선 미션이 절반씩 섞여 있습니다. 2장에서 대부분이 해금되며 3장에서 「미나토 걸」 라인이 추가되어 「The One」으로 마무리. 컴플리션 보상 + 「해적단」 명성/콜로세움/고로마루 라인과 직결되므로 메인 스토리를 3장까지 끌어올린 뒤 일괄 정리하는 편이 효율적입니다.",
    en: "31 substories total. Honolulu town intros (minigame unlocks) + Madlantis/open-sea ship missions split roughly half-and-half. Most unlock in Chapter 2; Chapter 3 adds the Minato Girls arc capped by 'The One'. Tied to fleet reputation, Coliseum, and Goromaru lines — push the main story to Chapter 3, then sweep them.",
  },
  source: { label: "PowerPyx — All Substories Guide", url: "https://www.powerpyx.com/like-a-dragon-pirate-yakuza-in-hawaii-all-substories-guide/" },
  groups: [
    {
      title: { ko: "호놀룰루 — 2장 도입 / 미니게임 해금", en: "Honolulu — Chapter 2 Minigame Unlocks" },
      items: [
        {
          number: 1,
          title: { ko: "카물롭, 운명의 점괘", en: "Kamulop, Fortunes Unfolded" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "불스아이 주변", en: "Bullseye area" },
          trigger: { ko: "2장 진행 중 스토리 연동 자동 발생", en: "Auto-triggers during Chapter 2 story flow." },
          body: {
            ko: "「포춘 익스체인지」가 해금되고 하와이 전역에 점괘 종이가 출현. 이후 수집형 보상이 점괘 종이 회수에 연결되므로 가장 먼저 처리.",
            en: "Unlocks Fortune Exchange and spawns fortune slips across Hawaii — a prerequisite for several collection rewards.",
          },
          reward: { ko: "포춘 익스체인지 해금 + 점괘 종이 수집 활성화", en: "Fortune Exchange unlocked + fortune-slip collection enabled" },
        },
        {
          number: 2,
          title: { ko: "스트리트 서퍼의 상징", en: "The Symbol of the City Street Surfer" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "호놀룰루 시가지 (자동)", en: "Honolulu streets (auto)" },
          trigger: { ko: "스토리 자동 진행", en: "Auto-triggers via story." },
          body: { ko: "시가지를 가로지르는 스트리트 서퍼 이동 수단이 해금. 이후 광역 이동 효율이 급상승하므로 풀린 즉시 사용 습관화.", en: "Unlocks the Street Surfer board for fast city traversal." },
          reward: { ko: "스트리트 서퍼 상시 사용 가능", en: "Street Surfer traversal permanently enabled" },
        },
        {
          number: 3,
          title: { ko: "알로하한 사진 랠리", en: "An Alo-Happy Rally" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "호놀룰루 시내 다지점", en: "Various Honolulu spots" },
          trigger: { ko: "엘리자베스를 해적단에 영입한 뒤 사진 랠리 NPC에게 말 걸기", en: "After recruiting Elizabeth to the crew, talk to the Photo Rally NPC." },
          body: { ko: "포토 랠리 미니게임이 해금. 지정 스폿을 돌며 사진을 찍는 컴플리션 라인.", en: "Unlocks the Photo Rally minigame — visit and snap each tagged landmark." },
          reward: { ko: "포토 랠리 해금 + 사진 보상 라인", en: "Photo Rally unlocked + photo reward line" },
        },
        {
          number: 4,
          title: { ko: "5구역의 새끼 고양이", en: "The Kitten in District Five" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "다이아몬드 헤드 바 동선", en: "Diamond Head bar route" },
          trigger: { ko: "스토리 연동 자동 발생", en: "Auto-triggers via story." },
          body: { ko: "「펫 구조」 목표가 해금. 이후 추가 펫을 데려와 「모여봐요! 고로 왕국」 업적 라인의 베이스가 됩니다.", en: "Unlocks pet-rescue objectives — feeds into the Goro Kingdom pet-collection achievement." },
          reward: { ko: "펫 시스템 해금", en: "Pet system unlocked" },
        },
        {
          number: 5,
          title: { ko: "크레이지 그대로", en: "Stay Crazy" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "선셋 파크 분수대", en: "Sunset Park fountain" },
          trigger: { ko: "분수대 옆 담당자에게 말 걸기", en: "Speak with the contact by the fountain." },
          body: { ko: "크레이지 딜리버리 미니게임이 해금. 첫 코스를 클리어하면 이후 「크레이지 선장」 업적용 전 코스가 열립니다.", en: "Unlocks Crazy Delivery — clear the intro course to open every later route." },
          reward: { ko: "크레이지 딜리버리 해금", en: "Crazy Delivery unlocked" },
        },
        {
          number: 6,
          title: { ko: "가장 똑똑한 해적단!", en: "The Smartest Pirate Crew!" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "오나바라 직업학교", en: "Ounabara Vocational School" },
          trigger: { ko: "오나바라 직업학교 방문", en: "Visit the school location." },
          body: { ko: "퀴즈 미니게임이 해금. 정답을 맞히면 해적단원 능력치 보너스가 누적됩니다.", en: "Unlocks the Ounabara trivia minigame — correct answers grant crew stat boosts." },
          reward: { ko: "오나바라 직업학교 해금", en: "Vocational school minigame unlocked" },
        },
        {
          number: 7,
          title: { ko: "파라다이스의 드래곤 카트", en: "Dragon Kart in Paradise" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "하버 근처 드래곤 카트 트랙", en: "Dragon Kart course near the Harbor" },
          trigger: { ko: "트랙 입구에서 운영자와 대화", en: "Talk to the operator at the kart course." },
          body: { ko: "드래곤 카트 미니게임이 해금. 입문 레이스를 한 번 완주하면 「하와이 스피드왕」 트로피 라인에 진입.", en: "Unlocks Dragon Kart — finishing the intro race opens the road to the Hawaii Speed King line." },
          reward: { ko: "드래곤 카트 해금", en: "Dragon Kart unlocked" },
        },
        {
          number: 8,
          title: { ko: "하와이 최속", en: "The Fastest in Hawaii" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "드래곤 카트 트랙", en: "Dragon Kart course" },
          trigger: { ko: "그랑프리 3종 + 듀얼 레이스 3종을 먼저 완주", en: "Clear three Grand Prix and three Duel races first, then return." },
          body: { ko: "여성 라이벌 「란」과의 일대일 엘리미네이션 듀얼. 사전에 카트를 완전 강화하지 않으면 직선 가속에서 밀립니다.", en: "Elimination duel against Ran — fully upgrade your kart beforehand or you will lose on the straights." },
          reward: { ko: "신규 카트 파츠 + 경험치", en: "New kart parts + EXP" },
          prereq: { ko: "그랑프리 3 + 듀얼 3 완주", en: "Three GPs + three Duels cleared" },
        },
        {
          number: 9,
          title: { ko: "속도의 길", en: "The Path to Speed" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "드래곤 카트 트랙", en: "Dragon Kart course" },
          trigger: { ko: "「하와이 최속」 클리어 후 재방문", en: "Available after clearing 'The Fastest in Hawaii'." },
          body: { ko: "로보 미치오 군단과의 엘리미네이션 듀얼. 「라이징 드래곤」 카트로 출주해야 안정적으로 승리.", en: "Elimination duel vs the Robo Michio squad — race with the Rising Dragon kart." },
          reward: { ko: "라이징 드래곤 강화 파츠", en: "Rising Dragon upgrade parts" },
        },
        {
          number: 10,
          title: { ko: "변태들을 찍어라! 다시!", en: "Snap Those Sickos! Again!" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "알로하 비치 트롤리 정류장", en: "Aloha Beach Trolley Stop" },
          trigger: { ko: "트롤리를 호출해 탑승", en: "Call the trolley and ride it." },
          body: { ko: "「시코 스냅」 미니게임 해금. 입문 코스를 한 번 클리어하면 이후 11장 보스 코스까지 차례로 열립니다.", en: "Unlocks Sicko Snap — clear the intro course to open the full course list." },
          reward: { ko: "시코 스냅 해금", en: "Sicko Snap unlocked" },
        },
        {
          number: 11,
          title: { ko: "시코 스냅 사가", en: "The Sicko Snap Saga" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "알로하 비치 트롤리 정류장", en: "Aloha Beach Trolley Stop" },
          trigger: { ko: "시코 스냅 3코스 클리어 후 쿠로키와 대화", en: "Clear three Sicko Snap courses, then talk to Kuroki." },
          body: { ko: "특별 코스 「크리스털 파피용 섬에서 스냅」을 진행. 보스 변태 「크리스털 파피용」을 카메라로 잡아내면 클리어.", en: "Special course 'Snap on Crystal Papillon Island' — catch boss sicko Crystal Papillon on camera to clear." },
          reward: { ko: "시코 스냅 컴플리션 보상", en: "Sicko Snap completion reward" },
        },
      ],
    },
    {
      title: { ko: "호놀룰루 — 2장 거리 서브", en: "Honolulu — Chapter 2 Street Subs" },
      items: [
        {
          number: 12,
          title: { ko: "음식의 마법", en: "The Magic of Food" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "솔레유 레스토랑", en: "Soleil Restaurant" },
          trigger: { ko: "솔레유에서 식사 후 시간차를 두고 재방문 — 3회 반복", en: "Order at Soleil three times with travel breaks between visits." },
          body: { ko: "솔레유에서 음식을 시키고 자리를 비웠다가 돌아오는 패턴을 3회 반복. 마지막 방문에서 트집을 잡는 2인조와 전투.", en: "Eat, leave, come back — three times. The third visit ends with a 2-on-1 brawl." },
          reward: { ko: "회복 아이템 + 경험치", en: "Recovery items + EXP" },
        },
        {
          number: 13,
          title: { ko: "다시 한 번 웃기를", en: "Smile Again" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "월드와이드 마켓 빌리지 — 제프의 타코 트럭", en: "Jeff's Taco Truck, Worldwide Market Village" },
          trigger: { ko: "타코 트럭에서 구매 후 이동·재방문 3회 반복", en: "Buy from the truck, leave, return — three times." },
          body: { ko: "3회째 재방문에서 트럭을 노리는 갱단과 전투. 제프의 사연이 풀리며 회복 아이템과 추가 메뉴가 해금.", en: "On the third return, a gang ambushes the truck — defeat them to unlock Jeff's full menu." },
          reward: { ko: "타코 메뉴 확장 + 경험치", en: "Expanded taco menu + EXP" },
        },
        {
          number: 14,
          title: { ko: "고로의 진심", en: "Goro's Heart" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "아나콘다 하버 파크", en: "Anaconda Harbor Park" },
          trigger: { ko: "발명가의 「진심 측정기」 테스트에 응하기", en: "Agree to the inventor's heart-tester demo." },
          body: { ko: "수상한 발명가의 진심 측정기 데모에 참가. 일련의 컷씬을 거쳐 결국 사기였음이 드러나지만 마지마는 호쾌하게 돈을 돌려받습니다.", en: "Sit through the inventor's gauntlet of 'heart' tests. It is a scam, but Majima walks away with his money back." },
          reward: { ko: "전액 환불 + 경험치", en: "Full refund + EXP" },
        },
        {
          number: 15,
          title: { ko: "내가 아이돌이 아니었다면", en: "If I Weren't An Idol" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "보육원 앞 택시 승강장", en: "Orphanage taxi stop" },
          trigger: { ko: "정체를 숨긴 아이돌의 시내 투어 의뢰 수락", en: "Agree to give the incognito idol a city tour." },
          body: { ko: "쇼핑몰 주변을 2분 안에 충돌 없이 일주. 종료 직후 정체를 알아챈 팬과 시비가 붙어 1인과 전투.", en: "Drive a 2-minute collision-free mall loop, then fight a single fan who clocks her identity." },
          reward: { ko: "아이돌 굿즈 + 경험치", en: "Idol merch + EXP" },
        },
        {
          number: 16,
          title: { ko: "기적의 수족관", en: "The Miracle Aquarium" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "아나콘다 쇼핑센터 인근", en: "Anaconda Shopping Center area" },
          trigger: { ko: "지도 마커 지점에서 의뢰인에게 말 걸기", en: "Speak with the man at the marked spot." },
          body: { ko: "지정 지점으로 이동해 의뢰인과 대화 후 곰과 전투. 「기적의 수족관 외전」의 선행 조건.", en: "Travel to the marker, talk to the client, beat a bear — prerequisite for the Gaiden follow-up." },
          reward: { ko: "경험치 + 「외전」 해금", en: "EXP + unlocks the Gaiden follow-up" },
        },
        {
          number: 17,
          title: { ko: "기적의 수족관 외전", en: "The Miracle Aquarium Gaiden" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "아나콘다 하버 파크", en: "Anaconda Harbor Park" },
          trigger: { ko: "16번 클리어 후 야스다와 대화", en: "Complete #16, then talk to Yasuda." },
          body: { ko: "갱단 무리 + 호랑이와의 연속 전투로 마무리. 호랑이는 광역 공격에 약하므로 핫 검의 회전기로 대응 권장.", en: "Brawl through a group of thugs and a tiger — the tiger crumbles to sweep attacks." },
          reward: { ko: "고액 보상 + 경험치", en: "Big cash payout + EXP" },
          prereq: { ko: "「기적의 수족관」 완료", en: "Clear #16 first" },
        },
        {
          number: 18,
          title: { ko: "청동의 사나이", en: "Man of Bronze" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "월드 마켓 빌리지 북측", en: "World Market Village north side" },
          trigger: { ko: "거리의 청동 동상 퍼포머에게 접근", en: "Walk up to the living-statue performer." },
          body: { ko: "동상에게 100달러를 건네면 추가 컷씬이 열리며, 화장실 이벤트와 갱단 전투를 거쳐 낮 시간대에 다시 만나면 결말 도달.", en: "Tip the statue $100 for the extended cut: bathroom gag, brawl, and a daytime reunion to wrap it up." },
          choices: [
            { prompt: { ko: "「한 푼만 적선해 주십쇼…」", en: "'Spare some change…'" }, correct: { ko: "100달러를 준다", en: "Give $100" }, note: { ko: "팁을 줘야 후속 컷씬이 풀리고 정상 컴플리션", en: "Tipping unlocks the full scene chain." } },
          ],
          reward: { ko: "고액 환급 + 경험치", en: "Refund + EXP" },
        },
        {
          number: 19,
          title: { ko: "나의 야마토 나데시코", en: "I Want To Be Your Nadeshiko" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "알로하 비치 — 야자수 옆", en: "Aloha Beach — by the palm tree" },
          trigger: { ko: "야자수 옆 여성과 대화", en: "Talk to the woman by the palm tree." },
          body: { ko: "헌팅 일행을 클레어와 함께 격퇴 → 레스토랑 관찰 → 일본스러움 퀴즈 → 잔디밭에서 최종 전투의 4단 구성.", en: "Beat the harassers with Claire, scope out the restaurant, answer the Japan quiz, then finish on the grass." },
          choices: [
            { prompt: { ko: "「가장 일본스러운 것은?」", en: "'The most Japanese thing is…?'" }, correct: { ko: "후지산", en: "Mt. Fuji" } },
          ],
          reward: { ko: "장신구 + 경험치", en: "Accessory + EXP" },
        },
        {
          number: 20,
          title: { ko: "65세의 시게타 히로노부", en: "Hironobu Shigeta, 65 Years Old" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "오나가 마리타임 운임소", en: "Onaga Maritime Fare" },
          trigger: { ko: "데빌 플래그 도입 이벤트 이후 부두에서 말 걸기", en: "After the Devil Flags story intro, talk to him at the docks." },
          body: { ko: "노년 선장의 마지막 자존심을 건 함선 전투. 적 함선 1척을 격침해야 클리어 — 「해적단」 명성도 함께 누적.", en: "Single ship battle against the old captain — sink his vessel to clear and bank fleet rep." },
          reward: { ko: "해적단 명성 + 함선 파츠", en: "Fleet reputation + ship parts" },
        },
        {
          number: 21,
          title: { ko: "커피 앤드 코미디", en: "Coffee & Comedy" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "카페 소라마메 (아나콘다 쇼핑센터 북측)", en: "Cafe Soramame (north of Anaconda Shopping Center)" },
          trigger: { ko: "카페 입장", en: "Enter the cafe." },
          body: { ko: "카페를 세 번에 걸쳐 방문 — 매 방문 사이 다른 지점으로 이동해야 다음 컷씬이 트리거됩니다.", en: "Three cafe visits with travel between them — each leg must take you elsewhere to advance." },
          reward: { ko: "커피 메뉴 해금 + 경험치", en: "Coffee menu unlock + EXP" },
        },
        {
          number: 22,
          title: { ko: "선장의 귀환", en: "The Captain's Return" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "줄리의 기어웍스 인근", en: "Julie's Gearworks area" },
          trigger: { ko: "지정 지점 인근 보행 시 자동 컷씬", en: "Walk near the marked spot to trigger the scene." },
          body: { ko: "미니맵에 표시되는 쓰레기 5개를 회수 후 시비를 거는 일당과 짧은 전투.", en: "Pick up the 5 trash markers on the minimap, then handle a quick brawl." },
          reward: { ko: "함선 강화 소재 + 경험치", en: "Ship upgrade material + EXP" },
        },
        {
          number: 23,
          title: { ko: "콜포레이트 컴플라이언스", en: "Corpirate Compliance" },
          chapter: { ko: "2장", en: "Chapter 2" },
          location: { ko: "블랙 히비스커스 레스토랑", en: "Black Hibiscus restaurant" },
          trigger: { ko: "고로마루 업그레이드 후 가게 내부 남성과 대화", en: "After upgrading the Goromaru, talk to the man inside the restaurant." },
          body: { ko: "부두에서 컴플라이언스 강의 수강 → 퀴즈 응답 → 시비 건 2인조와 마무리 전투. 해적단도 컴플라이언스 시대라는 자기풍자 에피소드.", en: "Sit through the harbor compliance class, answer the quiz, then beat two hecklers to wrap." },
          prereq: { ko: "고로마루 1차 업그레이드", en: "First Goromaru upgrade completed" },
          reward: { ko: "해적단 명성 + 경험치", en: "Fleet reputation + EXP" },
        },
      ],
    },
    {
      title: { ko: "매들랜티스 + 해상 — 3장 ~ 종반", en: "Madlantis + Sea — Chapter 3 onward" },
      items: [
        {
          number: 24,
          title: { ko: "공이여, 소원을 들어다오", en: "When You Wish Upon Some Balls" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "하와이 + 매들랜티스 전역", en: "Across Hawaii and Madlantis" },
          trigger: { ko: "3장 시작 시 자동 발생", en: "Auto-triggers at the start of Chapter 3." },
          body: { ko: "하와이와 매들랜티스 곳곳에 숨겨진 「황금 구슬」 7개를 회수하는 장기 수집 라인. 일부는 함선이 있어야 도달 가능한 무인도에 배치.", en: "Find 7 Gold Balls scattered across Hawaii and Madlantis — several require sailing to outer islets." },
          reward: { ko: "황금 구슬 컴플리션 보상 + 경험치 대량", en: "Gold Balls completion reward + large EXP" },
        },
        {
          number: 25,
          title: { ko: "꿈에 그리던 미나토 걸", en: "My Dream Minato Girl" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "호놀룰루 시내 — 미나토 사무소", en: "Honolulu — Minato office" },
          trigger: { ko: "3장 도입부 자동 발생", en: "Auto-triggers during the Chapter 3 intro." },
          body: { ko: "「미나토 걸」 시스템이 해금. 이후 26~30번의 5인 라인 + 31번 「The One」으로 마무리되는 컴플리션 트로피 라인의 기점.", en: "Unlocks the Minato Girls system — feeds into the five-girl arc (#26–30) capped by #31 'The One' for the trophy." },
          reward: { ko: "미나토 걸 해금", en: "Minato Girls system unlocked" },
        },
        {
          number: 26,
          title: { ko: "#내새친구", en: "#MyNewFriend" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "크리스털 알로하 리조트", en: "Crystal Aloha Resort" },
          trigger: { ko: "마커 지점에서 에나와 만남", en: "Head to the marker and meet Ena." },
          body: { ko: "미나토 걸 「에나」를 만나 두 차례 갱단을 격퇴한 뒤 레스토랑 담당자와 대화로 마무리.", en: "Meet Minato Girl Ena, beat off two waves of thugs, then check in with the restaurant contact." },
          reward: { ko: "에나 유대 진행 + 경험치", en: "Ena bond progress + EXP" },
        },
        {
          number: 27,
          title: { ko: "Hello, World!", en: "Hello, World!" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "아나콘다 쇼핑센터", en: "Anaconda Shopping Center" },
          trigger: { ko: "마커 지점에서 미소시와 만남", en: "Head to the marker and meet Misoshi." },
          body: { ko: "미나토 걸 「미소시」와 만나자마자 전투, 이후 리볼브 바로 이동해 라이브 스트리밍 컷씬으로 종결.", en: "Meet Misoshi, brawl immediately, then move to the Revolve bar for the live-streaming scene." },
          reward: { ko: "미소시 유대 진행 + 경험치", en: "Misoshi bond progress + EXP" },
        },
        {
          number: 28,
          title: { ko: "비밀 지켜줄 수 있어?", en: "Can You Keep A Secret?" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "피전 패밀리 마켓 인근", en: "Pigeon Family Market area" },
          trigger: { ko: "마커 지점에서 카호와 만남", en: "Head to the marker and meet Kaho." },
          body: { ko: "미나토 걸 「카호」와 두 지점을 오가며 갱단을 두 차례 격퇴.", en: "Meet Minato Girl Kaho — two separate brawls at two different spots." },
          reward: { ko: "카호 유대 진행 + 경험치", en: "Kaho bond progress + EXP" },
        },
        {
          number: 29,
          title: { ko: "진실", en: "Truth" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "샤크 티스 기념품점", en: "Shark Teeth Souvenirs" },
          trigger: { ko: "마커 지점에서 세이코와 만남", en: "Head to the marker and meet Seiko." },
          body: { ko: "「드래곤 카트」 7번 클리어 필수. 세이코와 입문 트랙에서 1대1 레이스를 마친 뒤, 술자리 후 시비 건 일당과 전투.", en: "Requires #7 cleared. Race Seiko on the intro Dragon Kart track, then brawl the drunks afterwards." },
          prereq: { ko: "「파라다이스의 드래곤 카트」(#7) 완료", en: "Clear #7 first" },
          reward: { ko: "세이코 유대 진행 + 경험치", en: "Seiko bond progress + EXP" },
        },
        {
          number: 30,
          title: { ko: "사랑스러운 여행자", en: "Lovely Traveler" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "아나콘다 쇼핑센터", en: "Anaconda Shopping Center" },
          trigger: { ko: "마커 지점에서 아이와 만남", en: "Head to the marker and meet Ai." },
          body: { ko: "미나토 걸 「아이」와 사진집에 총 360달러를 지출해야 진행. 이후 쇼핑센터와 리치 아일랜드에서 갱단 전투 2회.", en: "Meet Minato Girl Ai — spend $360 total on photobooks, then two brawls (mall + Rich Island)." },
          reward: { ko: "아이 유대 진행 + 경험치", en: "Ai bond progress + EXP" },
        },
        {
          number: 31,
          title: { ko: "The One", en: "The One" },
          chapter: { ko: "3장", en: "Chapter 3" },
          location: { ko: "리볼브 바", en: "Revolve bar" },
          trigger: { ko: "26~30번 모두 클리어 후 바에서 마치코와 대화", en: "After clearing #26–30, talk to Machiko at Revolve." },
          body: { ko: "미나토 걸 5인이 모이는 마무리 컷씬. 대사 선택지는 자유 — 트로피·컴플리션에 영향 없음. 그룹 대화로 라인 종결.", en: "Final five-girl scene. Pick any reply — no trophy impact. Group chat closes the arc." },
          reward: { ko: "「미나토 걸」 컴플리션 트로피 + 경험치", en: "Minato Girls completion trophy + EXP" },
          prereq: { ko: "#26~#30 모두 완료", en: "Clear #26–#30 first" },
        },
      ],
    },
  ],
};
