import type { SubstoriesData } from "./types";

export const likeADragonInfiniteWealthSubstories: SubstoriesData = {
  appId: 2072450,
  summary: {
    ko: "총 52개. 챕터 1~9 진행 중에 모두 해금되며, 미스 불가(놓치는 것 없음) — 단, 시간대(낮/밤)나 매니저 랭크, 인간력(친절/용기 등) 7 이상 같은 조건이 붙은 의뢰가 있어 메인 진행과 병행이 효율적입니다. 호놀룰루 거점 의뢰가 대다수이며, 챕터 9 후반에 키류의 「엔딩 노트」와 묶이는 의뢰가 추가됩니다. 10/20/40개 클리어 시 트로피 라인(Touching Lives / Saving Lives / Living Your Best Life)이 풀립니다.",
    en: "52 substories total. All unlock between Chapter 1 and 9 and none are strictly missable, but several gate on time of day, manager rank, or personality stats (Kindness/Courage/etc. 7+), so run them alongside the main story. The bulk happen in Honolulu City; Chapter 9 adds Kiryu's 'Ending Note' threads. Clearing 10/20/40 unlocks the Touching Lives / Saving Lives / Living Your Best Life trophy line.",
  },
  source: {
    label: "game8.jp — 龍が如く8 サブストーリー攻略一覧",
    url: "https://game8.jp/ryu-ga-gotoku8/587557",
  },
  groups: [
    {
      title: { ko: "스토리 도입 — 챕터 1~2 (요코하마)", en: "Story Intro — Chapter 1~2 (Yokohama)" },
      items: [
        {
          number: 1,
          title: { ko: "라디오의 시간", en: "Radio Time" },
          chapter: { ko: "챕터 1", en: "Chapter 1" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "이세자키 이진초 — 사쿠라가와도리 남쪽", en: "Isezaki Ijincho — Sakuragawa St. south" },
          trigger: { ko: "챕터 1 메인 진행 중 자동 발생", en: "Auto-triggers during Chapter 1 main story." },
          body: {
            ko: "메인 진행 중 자동으로 풀리는 도입 의뢰. 클리어 시 스마트폰 앱 「플레이리스트」가 추가되어 BGM을 자유롭게 바꿀 수 있습니다.",
            en: "Auto-completes during the Chapter 1 story. Unlocks the 'Playlist' phone app for free BGM swapping.",
          },
          reward: { ko: "「플레이리스트」 앱", en: "Playlist app" },
        },
        {
          number: 2,
          title: { ko: "다시 한 번 노린다! 스지몬 마스터!", en: "Once More, Sujimon Master!" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "이세자키 이진초 — 로만도리", en: "Isezaki Ijincho — Roman St." },
          trigger: { ko: "챕터 2 메인 진행 중 자동 발생", en: "Auto-triggers during Chapter 2 main story." },
          body: {
            ko: "스지몬 도감 앱이 부활하는 도입 의뢰. 이후 호놀룰루에서 본격적인 스지몬 배틀 컨텐츠(36~42)가 풀립니다.",
            en: "Brings back the Sujimon dex app. Sets up the Sujimon battle chain (36~42) in Honolulu.",
          },
          reward: { ko: "「스지몬 도감」 앱", en: "Sujimon Dex app" },
        },
      ],
    },
    {
      title: { ko: "호놀룰루 도착 — 챕터 3 (도입 묶음)", en: "Arriving in Honolulu — Chapter 3 (Intro Wave)" },
      items: [
        {
          number: 3,
          title: { ko: "크레이지 딜리버리", en: "Crazy Delivery" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 스트리트", en: "Honolulu City — Aloha St." },
          trigger: { ko: "챕터 3 메인 진행 중 자동 발생", en: "Auto-triggers during Chapter 3." },
          body: {
            ko: "딜리버리 헬프(원군 호출) 시스템이 해금되는 도입 의뢰. 첫 동료 「찰리」가 합류하며 전투 중 원군 호출이 가능해집니다.",
            en: "Unlocks the Delivery Help (assist call) system. Adds first helper Charlie and lets you summon assists mid-fight.",
          },
          reward: { ko: "딜리버리 헬프 「찰리」 + 30달러", en: "Delivery Helper Charlie + $30" },
        },
        {
          number: 4,
          title: { ko: "치토세의 정체", en: "The Truth About Chitose" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 와이키키 스트리트", en: "Honolulu City — Waikiki St." },
          trigger: { ko: "챕터 3 메인 진행 중 자동 발생", en: "Auto-triggers during Chapter 3." },
          body: {
            ko: "치토세와의 인연을 본격 시작하는 의뢰. 이후 절(50)까지 이어지는 라인의 시작점.",
            en: "Kicks off Chitose's bond line that leads to Substory 50.",
          },
          reward: { ko: "딜리버리 헬프 기능 강화", en: "Delivery Help feature upgrade" },
        },
        {
          number: 5,
          title: { ko: "잘 부탁해 마이 프렌드", en: "Nice to Meet You, My Friend" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 후지 스트리트", en: "Honolulu City — Fuji St." },
          trigger: { ko: "챕터 3 메인 진행 중 자동 발생", en: "Auto-triggers during Chapter 3." },
          body: {
            ko: "스마트폰 앱 「알로하 링크」가 추가됩니다. 이후 챕터 3 후반의 사이드 의뢰 대부분이 이 앱을 통해 해금됩니다.",
            en: "Adds the Aloha Links app, which gates most of the rest of the Chapter 3 sidequests.",
          },
          reward: { ko: "「알로하 링크」 앱", en: "Aloha Links app" },
        },
        {
          number: 6,
          title: { ko: "도로에서 파도타는 OKA 서퍼", en: "OKA Surfer on the Road" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 시사이드 애비뉴", en: "Honolulu City — Seaside Ave." },
          trigger: { ko: "「알로하 링크」 해금 후 발생", en: "Available after unlocking Aloha Links." },
          body: {
            ko: "도로용 전동 서핑보드 「OKA 서퍼」를 받아 이동 수단으로 사용할 수 있게 됩니다. 호놀룰루 광역 이동 시 필수.",
            en: "Grants the OKA Surfer board, a key fast-traversal tool across Honolulu.",
          },
          reward: { ko: "OKA 서퍼 + 배터리 팩", en: "OKA Surfer + battery pack" },
        },
        {
          number: 7,
          title: { ko: "마치코 씨", en: "Ms. Machiko" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 시사이드 애비뉴", en: "Honolulu City — Seaside Ave." },
          trigger: { ko: "「알로하 링크」 해금 후 발생", en: "Available after unlocking Aloha Links." },
          body: {
            ko: "매칭 앱 「Miss Match」가 풀립니다. 이후 49 「매칭 마치코 선생」 라인으로 연결됩니다.",
            en: "Unlocks the Miss Match dating-app minigame, which feeds into Substory 49.",
          },
          reward: { ko: "Miss Match 앱 해금", en: "Miss Match app unlocked" },
        },
        {
          number: 8,
          title: { ko: "수상한 자 스냅", en: "Snap That Creep" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 스트리트", en: "Honolulu City — Aloha St." },
          trigger: { ko: "「알로하 링크」 해금 후 알로하 스트리트의 의뢰자에게 말 걸기", en: "Talk to the client on Aloha St. after Aloha Links is live." },
          body: {
            ko: "거리의 삥쟁이·수상한 자를 사진으로 찍어 신고하는 의뢰. 의뢰자의 지시대로 지정 인물을 카메라로 촬영하면 완료.",
            en: "Photo-tag suspicious loiterers on Aloha St. as instructed by the client.",
          },
          reward: { ko: "초회복의 환약", en: "Super Recovery Pill" },
        },
        {
          number: 9,
          title: { ko: "첫사랑은 레모네이드 맛", en: "First Love Tastes Like Lemonade" },
          chapter: { ko: "챕터 3 (낮)", en: "Chapter 3 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 아야메 스트리트", en: "Honolulu City — Ayame St." },
          trigger: { ko: "낮 시간대 아야메 스트리트의 소녀에게 말 걸기 (알로하 링크 해금 후)", en: "Daytime: talk to the girl on Ayame St. after Aloha Links unlocks." },
          body: {
            ko: "레모네이드 가판을 차리고 싶어 하는 소녀를 도와 「토니스 레모네이드 스탠드」 플레이스폿을 해금합니다. 이후 음료를 정기 구매할 수 있게 됩니다.",
            en: "Help the girl set up Tony's Lemonade Stand and unlock it as a recurring drink shop.",
          },
          reward: { ko: "「토니스 레모네이드 스탠드」 해금", en: "Tony's Lemonade Stand unlocked" },
        },
        {
          number: 10,
          title: { ko: "비치에 얽힌 이런저런", en: "Beach Etcetera" },
          chapter: { ko: "챕터 3 (낮)", en: "Chapter 3 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 비치", en: "Honolulu City — Aloha Beach" },
          trigger: { ko: "딜리버리 헬프 해금 후 낮 시간대 알로하 비치 방문", en: "Daytime on Aloha Beach after Delivery Help is live." },
          body: {
            ko: "비치의 조개껍데기 보물찾기 이벤트. 이후 딜리버리 헬프 「낸시 올리비아」가 합류합니다.",
            en: "Shell-hunting beach mini-event; adds Nancy Olivia as a Delivery Helper.",
          },
          reward: { ko: "조개 보물 + 딜리버리 헬프 「낸시 올리비아」", en: "Shell treasure + Helper Nancy Olivia" },
        },
        {
          number: 11,
          title: { ko: "트로피컬 레스토랑에 오신 걸 환영해요", en: "Welcome to the Tropical Restaurant" },
          chapter: { ko: "챕터 3 (낮)", en: "Chapter 3 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 모모 스트리트", en: "Honolulu City — Momo St." },
          trigger: { ko: "낮 시간대 모모 스트리트의 점원에게 말 걸기", en: "Daytime: talk to the staffer on Momo St." },
          body: {
            ko: "오아후 버거 옆 트로피컬 레스토랑에서 손님맞이·주문 받기 도우미. 인사 어조와 주문을 손님 성격에 맞게 골라야 합니다. 모든 답을 맞히면 보상이 강화됩니다.",
            en: "Help greet and take orders at the tropical restaurant. Match greeting tone and dish to each customer for the full reward.",
          },
          choices: [
            { prompt: { ko: "첫 손님 인사", en: "First customer greeting" }, correct: { ko: "친근하게 인사한다", en: "Friendly greeting" } },
            { prompt: { ko: "두 번째 손님 인사", en: "Second customer greeting" }, correct: { ko: "정중하게 인사한다", en: "Refined greeting" } },
            { prompt: { ko: "세 번째 손님 인사", en: "Third customer greeting" }, correct: { ko: "친근하게 인사한다", en: "Friendly greeting" } },
            { prompt: { ko: "흑인 손님 주문", en: "Order for the man in black" }, correct: { ko: "아사이볼과 라우라우", en: "Acai bowl and lau lau" } },
            { prompt: { ko: "쾌활한 손님 주문", en: "Order for the cheery customer" }, correct: { ko: "아히 포케와 하우피아 3개", en: "Ahi poke and 3x haupia" } },
            { prompt: { ko: "우아한 손님 주문", en: "Order for the elegant customer" }, correct: { ko: "마히마히", en: "Mahi mahi" } },
            { prompt: { ko: "가족석 첫 접시", en: "Family table — first dish" }, correct: { ko: "라우라우 (왼쪽)", en: "Lau lau (left)" } },
            { prompt: { ko: "가족석 두 번째 접시", en: "Family table — second dish" }, correct: { ko: "칼루아 피그 (가운데)", en: "Kalua pig (center)" } },
            { prompt: { ko: "마지막 질문 — 사장님 이름은?", en: "Final question — owner's name?" }, correct: { ko: "오비스포", en: "Obispo" } },
          ],
          reward: { ko: "도시락 + 요리 스킬 + 300달러", en: "Bento + Cooking skill + $300" },
        },
        {
          number: 12,
          title: { ko: "다정하게 대해준 사람", en: "Saved by Kindness" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 마카니 애비뉴 (택시 정류장 맞은편)", en: "Honolulu City — Makani Ave. (across from the taxi stop)" },
          trigger: { ko: "알로하 링크 해금 후 마카니 애비뉴에서 쓰러진 남자에게 말 걸기", en: "After Aloha Links unlocks, speak to the man on the ground on Makani Ave." },
          body: {
            ko: "쓰러진 남자를 두 번 더 방문한 뒤, 아야메 스트리트에서 일어나는 시비에 개입하는 의뢰. 도중 「누가 너에게 다정하게 대해줬지?」라는 질문에 정확한 인물을 골라야 인간력 보너스가 최대치로 들어옵니다.",
            en: "Revisit the fallen man twice, then break up a confrontation on Ayame St. The 'Who was kind to you?' prompt must be answered correctly for the full personality reward.",
          },
          choices: [
            {
              prompt: { ko: "「누가 너에게 다정하게 대해줬지?」", en: "'Who was kind to you?'" },
              correct: { ko: "레이를 걸어준 여자", en: "The lei girl" },
            },
          ],
          reward: { ko: "인간력 「친절함」 보너스 + 아이템", en: "Kindness personality boost + item" },
        },
        {
          number: 13,
          title: { ko: "폭풍을 부르고 싶은 남자", en: "Rock and Roil" },
          chapter: { ko: "챕터 3 (낮)", en: "Chapter 3 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 비치 (주서리 남쪽)", en: "Honolulu City — Aloha Beach (south of the Juicery)" },
          trigger: { ko: "딜리버리 헬프 해금 후 낮 시간대 알로하 비치 방문", en: "Daytime on Aloha Beach after Delivery Help is live." },
          body: {
            ko: "비를 부르고 싶다는 자칭 폭풍의 남자를 돕는 의뢰. 지정 지점으로 이동한 뒤 「정령에게 폭풍을 빌어준다」를 골라야 인간력 보너스가 정상 지급됩니다.",
            en: "Help a self-styled storm-summoner. Travel to the marker and pick 'Ask the spirits for a storm' for the full personality reward.",
          },
          choices: [
            {
              prompt: { ko: "「어떻게 폭풍을 부를까?」", en: "'How do we summon the storm?'" },
              correct: { ko: "정령에게 폭풍을 빌어준다", en: "Ask the spirits for a storm" },
            },
          ],
          reward: { ko: "디프래그 카세트 + 딜리버리 헬프 「카자미 에볼루션」", en: "Defrag cassette + Helper Kazami Evolution" },
        },
        {
          number: 14,
          title: { ko: "알로하 비치의 주문", en: "The Aloha Beach Charm" },
          chapter: { ko: "챕터 3 (낮)", en: "Chapter 3 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 비치", en: "Honolulu City — Aloha Beach" },
          trigger: { ko: "알로하 링크 해금 후 낮 시간대 알로하 비치 방문", en: "Daytime on Aloha Beach after Aloha Links is live." },
          body: {
            ko: "고백을 망설이는 청년을 도와 비치에서 「용기의 주문」을 거는 의뢰. 클리어 시 인간력 「용기」 보너스가 들어가는 펜던트를 받습니다.",
            en: "Help a nervous beachgoer cast a 'courage charm'. Rewards a pendant that boosts Courage.",
          },
          reward: { ko: "용기의 펜던트", en: "Courage pendant" },
        },
        {
          number: 15,
          title: { ko: "사무라이를 따라가도 될까요", en: "Samurai, May We Walk Together?" },
          chapter: { ko: "챕터 3 (낮/저녁)", en: "Chapter 3 (Day / Evening)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 비치 (오션 보이즈 남쪽)", en: "Honolulu City — Aloha Beach (south of Ocean Boys)" },
          trigger: { ko: "11 「트로피컬 레스토랑」 클리어 후 발생", en: "Available after clearing Substory 11." },
          body: {
            ko: "「사무라이를 동경하는」 외국인 청년을 안내해주는 의뢰. 두 차례 선택지가 나오며, 일본식으로 일관되게 답해야 인간력 보너스와 강화 보상이 들어옵니다.",
            en: "Guide a foreigner who admires samurai. Pick the Japanese-style answer at both prompts for the full personality reward.",
          },
          choices: [
            {
              prompt: { ko: "「아침 식사로 뭘 권할까요?」", en: "Breakfast choice" },
              correct: { ko: "쌀과 잡곡", en: "Rice and millet" },
            },
            {
              prompt: { ko: "「머리에 뭘 씌울까요?」", en: "What to put on his head" },
              correct: { ko: "…삿갓을.", en: "…The hat." },
            },
          ],
          reward: { ko: "딜리버리 헬프 「네이산」", en: "Delivery Helper Nathan" },
        },
        {
          number: 16,
          title: { ko: "라이프가드의 일", en: "A Lifeguard's Duty" },
          chapter: { ko: "챕터 3 (낮)", en: "Chapter 3 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 스트리트", en: "Honolulu City — Aloha St." },
          trigger: { ko: "알로하 링크 해금 후 발생", en: "Available after unlocking Aloha Links." },
          body: { ko: "신참 라이프가드의 임무 동행. 이후 17·18 라인으로 이어집니다.", en: "Tag along with a rookie lifeguard. Leads into Substories 17 and 18." },
          reward: { ko: "대회복의 환약", en: "Great Recovery Pill" },
        },
        {
          number: 17,
          title: { ko: "비치를 지킨다는 것", en: "Protecting the Beach" },
          chapter: { ko: "챕터 3 (낮)", en: "Chapter 3 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 비치", en: "Honolulu City — Aloha Beach" },
          trigger: { ko: "16 클리어 후 발생", en: "Available after clearing Substory 16." },
          body: { ko: "라이프가드 라인 2단계. 비치의 트러블을 해결합니다.", en: "Lifeguard chain part 2." },
          reward: { ko: "하트풀 골렘", en: "Heartful Golem" },
        },
        {
          number: 18,
          title: { ko: "비치의 수호신", en: "Guardian of the Beach" },
          chapter: { ko: "챕터 3 (낮)", en: "Chapter 3 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 비치", en: "Honolulu City — Aloha Beach" },
          trigger: { ko: "17 클리어 후 발생", en: "Available after clearing Substory 17." },
          body: { ko: "라이프가드 라인 최종 단계. 보스급 트러블을 정리하면 전용 워터고글을 받습니다.", en: "Final lifeguard chain entry; clears a boss-tier nuisance for a special water goggle." },
          reward: { ko: "스페셜 워터고글", en: "Special water goggles" },
        },
        {
          number: 19,
          title: { ko: "My Sweet Home", en: "My Sweet Home" },
          chapter: { ko: "챕터 3 (낮)", en: "Chapter 3 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 비치", en: "Honolulu City — Aloha Beach" },
          trigger: { ko: "딜리버리 헬프 해금 후 알로하 비치의 노숙자 「요제프」에게 말 걸기", en: "Speak to the homeless man Joseph on Aloha Beach after Delivery Help is live." },
          body: { ko: "비치에서 살고 있는 요제프와의 인연 의뢰. 이후 정기적으로 아이템을 받을 수 있게 됩니다.", en: "Bond with Joseph, who'll then drop items for you periodically." },
          reward: { ko: "요제프의 아이템 정기 지급 해금", en: "Recurring item drops from Joseph" },
        },
      ],
    },
    {
      title: { ko: "호놀룰루 — 챕터 4 묶음", en: "Honolulu — Chapter 4 Wave" },
      items: [
        {
          number: 20,
          title: { ko: "비밀의 차고", en: "The Secret Garage" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 훌라 애비뉴", en: "Honolulu City — Hula Ave." },
          trigger: { ko: "챕터 4 메인 진행 중 자동 발생", en: "Auto-triggers during Chapter 4." },
          body: { ko: "무기 제작/강화 시스템이 해금되는 도입 의뢰.", en: "Unlocks weapon crafting/upgrade." },
          reward: { ko: "무기 제작 해금", en: "Weapon crafting unlocked" },
        },
        {
          number: 21,
          title: { ko: "대해원으로 렛츠 다이브", en: "Let's Dive Into the Open Sea" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 하버 스트리트", en: "Honolulu City — Harbor St." },
          trigger: { ko: "챕터 4 메인 진행 중 발생", en: "Available in Chapter 4." },
          body: { ko: "라이센스 시험(자격 인정) 컨텐츠가 해금됩니다. 이후 47 라인의 전제 조건이 됩니다.", en: "Unlocks the license certification exams (prereq for Substory 47)." },
          reward: { ko: "라이센스 시험 해금", en: "License exams unlocked" },
        },
        {
          number: 22,
          title: { ko: "카페 소라마메", en: "Cafe Soramame (Rise and Grind)" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 아나콘다도리", en: "Honolulu City — Anaconda Blvd." },
          trigger: { ko: "챕터 4 진행 중 카페 점주에게 말 걸기", en: "Talk to the cafe owner on Anaconda Blvd. in Chapter 4." },
          body: { ko: "카페 소라마메의 점주를 돕는 의뢰. 대화 중 점주의 본명을 묻는 질문이 나오며, 「소라타」로 답해야 인간력 보너스가 들어옵니다.", en: "Help out at Cafe Soramame. When asked the owner's first name, answer 'Sorata' for the personality bonus." },
          choices: [
            { prompt: { ko: "「점주의 이름은?」", en: "'The owner's name?'" }, correct: { ko: "소라타", en: "Sorata" } },
          ],
          reward: { ko: "딜리버리 헬프 「마메오카」", en: "Delivery Helper Mameoka" },
        },
        {
          number: 23,
          title: { ko: "프루메리아를 그대에게", en: "Plumeria for You" },
          chapter: { ko: "챕터 4 (낮)", en: "Chapter 4 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 와이키키 스트리트", en: "Honolulu City — Waikiki St." },
          trigger: { ko: "지정 두 곳에서 꽃 이벤트 목격 후, 와이키키에서 청년들의 다툼 목격", en: "Witness flower scenes at two spots, then catch the youths' quarrel on Waikiki St." },
          body: { ko: "프루메리아 꽃을 둘러싼 두 청년의 다툼을 중재합니다.", en: "Mediate between two young men over a plumeria flower." },
          reward: { ko: "럭키 파레오", en: "Lucky pareo" },
        },
        {
          number: 24,
          title: { ko: "스노우 스마일", en: "Snow Smile" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 스트리트", en: "Honolulu City — Aloha St." },
          trigger: { ko: "챕터 4 진행 중 알로하 스트리트의 의뢰자에게 말 걸기", en: "Talk to the client on Aloha St. in Chapter 4." },
          body: { ko: "한겨울에 눈을 보고 싶다는 일본인 단원과 동행하는 의뢰.", en: "Help a Japanese visitor see 'snow' in midsummer Hawaii." },
          reward: { ko: "딜리버리 헬프 「곤다바라 조장」", en: "Delivery Helper Boss Gondabara" },
        },
        {
          number: 25,
          title: { ko: "You (don't) Listen to Rock", en: "You (don't) Listen to Rock" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 아나콘다 쇼핑센터", en: "Honolulu City — Anaconda Shopping Center" },
          trigger: { ko: "챕터 4 진행 중 발생", en: "Available in Chapter 4." },
          body: { ko: "쇼핑센터의 락 매니아 청년과 음악 취향으로 부딪히는 의뢰.", en: "Spar with a rock-snob youth at the mall over taste in music." },
          reward: { ko: "사인 티셔츠", en: "Signed t-shirt" },
        },
        {
          number: 26,
          title: { ko: "아나콘다 이스케이프", en: "Anaconda Escape" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 아나콘다 쇼핑센터", en: "Honolulu City — Anaconda Shopping Center" },
          trigger: { ko: "챕터 4 진행 중 발생", en: "Available in Chapter 4." },
          body: { ko: "쇼핑센터 내부에서 일어난 좀도둑·삥쟁이 사건을 해결하는 의뢰.", en: "Solve a petty-theft incident inside the Anaconda mall." },
          reward: { ko: "금고 열쇠", en: "Safe key" },
        },
        {
          number: 27,
          title: { ko: "리얼리즘의 추구", en: "An Authentic Production" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 리버사이드 워크", en: "Honolulu City — Riverside Walk" },
          trigger: { ko: "챕터 4 진행 중 발생", en: "Available in Chapter 4." },
          body: { ko: "리얼리즘에 집착하는 영화 감독의 액션 신 제작을 돕는 의뢰. 이후 28 라인의 전제.", en: "Help a realism-obsessed director shoot an action scene. Sets up Substory 28." },
          reward: { ko: "지갑 + 스피드 업퍼 + 딜리버리 헬프 「보니 카시와」", en: "Wallet + Speed Upper + Helper Bony Kashiwa" },
        },
        {
          number: 28,
          title: { ko: "폭풍 너머로", en: "An Authentic Blockbuster" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 선셋 파크 (마카니 커피 옆)", en: "Honolulu City — Sunset Park (next to Makani Coffee)" },
          trigger: { ko: "15 & 27 클리어 후 발생", en: "Available after clearing Substory 15 and 27." },
          body: { ko: "감독의 클라이맥스 액션 신 촬영. 캐스팅 선택에서 「보니 카시와」를 골라야 인간력 보너스가 들어옵니다.", en: "Shoot the director's climax scene. Pick 'Bony Kashiwa' in the casting prompt for the full personality bonus." },
          choices: [
            { prompt: { ko: "「누구를 캐스팅할까?」", en: "Casting choice" }, correct: { ko: "보니 카시와", en: "Bony Kashiwa" } },
          ],
          reward: { ko: "로켓 런처 강화 + 인간력 보너스", en: "Rocket launcher upgrade + personality boost" },
        },
        {
          number: 29,
          title: { ko: "오소우지마루 다시", en: "Mr. Cleanup Returns" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 아나콘다 쇼핑센터", en: "Honolulu City — Anaconda Shopping Center" },
          trigger: { ko: "챕터 4 진행 중 발생", en: "Available in Chapter 4." },
          body: { ko: "전작의 청소로봇 「오소우지마루」가 재등장. 이후 30 「미확인 비행물체와 조우」로 이어집니다.", en: "Mr. Cleanup (Osoujimaru) returns; sets up Substory 30." },
          reward: { ko: "본 후크 부적 + 스지몬 정보", en: "Bone Hook charm + Sujimon intel" },
        },
        {
          number: 37,
          title: { ko: "스지가미님은 갑자기", en: "The Sujigami Cometh" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 아나콘다 쇼핑센터", en: "Honolulu City — Anaconda Shopping Center" },
          trigger: { ko: "챕터 4 메인 진행 중 자동 발생", en: "Auto-triggers in Chapter 4." },
          body: { ko: "스지몬 배틀 컨텐츠가 본격적으로 해금됩니다.", en: "Unlocks the full Sujimon Battle system." },
          reward: { ko: "스지몬 배틀 해금", en: "Sujimon Battle unlocked" },
        },
        {
          number: 38,
          title: { ko: "스지가미 사천왕 등장", en: "Enter the Sujigami Four Kings" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 호텔 짐", en: "Honolulu City — Hotel gym" },
          trigger: { ko: "스지몬 매니저 랭크 10 달성", en: "Reach Sujimon manager rank 10." },
          body: { ko: "사천왕 중 첫 번째와의 대결. 클리어 시 이치반 전용 직업 「소환사」가 해금됩니다.", en: "First of the Four Kings. Clearing unlocks the Summoner job for Ichiban." },
          reward: { ko: "이치반 직업 「소환사」 해금", en: "Summoner job unlocked for Ichiban" },
        },
        {
          number: 39,
          title: { ko: "매혹의 비치 퀸", en: "The Alluring Beach Queen" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 비치", en: "Honolulu City — Aloha Beach" },
          trigger: { ko: "스지몬 매니저 랭크 20 달성", en: "Reach Sujimon manager rank 20." },
          body: { ko: "사천왕 두 번째 전투.", en: "Second of the Four Kings." },
          reward: { ko: "스지스폿 아이템 강화 + 택시 정류장 해금", en: "Suji-spot item buffs + new taxi stop" },
        },
        {
          number: 40,
          title: { ko: "청춘을 되찾아라", en: "Reclaim Your Youth" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 에이스 도장", en: "Honolulu City — Ace Dojo" },
          trigger: { ko: "스지몬 매니저 랭크 30 달성", en: "Reach Sujimon manager rank 30." },
          body: { ko: "사천왕 세 번째 전투.", en: "Third of the Four Kings." },
          reward: { ko: "스지스폿 아이템 추가 강화", en: "Further Suji-spot item buffs" },
        },
        {
          number: 41,
          title: { ko: "살의의 극도에 눈뜬 남자", en: "The Man Who Found Bloodlust" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 에이스 도장", en: "Honolulu City — Ace Dojo" },
          trigger: { ko: "스지몬 매니저 랭크 35 달성", en: "Reach Sujimon manager rank 35." },
          body: { ko: "사천왕 마지막 멤버 전투. 42 「정상결전」으로 이어집니다.", en: "Final Four Kings fight; leads into Substory 42." },
          reward: { ko: "스지 아이템 추가 강화 + 다음 의뢰 해금", en: "Suji item buffs + unlocks Substory 42" },
        },
        {
          number: 42,
          title: { ko: "정상결전", en: "Showdown at the Top" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — PC샵 스지가미", en: "Honolulu City — PC Shop Sujigami" },
          trigger: { ko: "41 클리어 후 발생", en: "Available after clearing Substory 41." },
          body: { ko: "스지몬 라인의 최종전. ★5 무기 「용혼 배트」와 섬 게스트 해금.", en: "Final Sujimon battle; rewards the 5★ weapon Dragon Soul Bat and a Dondoko Island guest." },
          reward: { ko: "★5 무기 「용혼 배트」 + 섬 게스트", en: "5★ 'Dragon Soul Bat' + island guest" },
        },
        {
          number: 43,
          title: { ko: "아사쿠라라는 남자", en: "The Man Called Asakura" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 스트리트", en: "Honolulu City — Aloha St." },
          trigger: { ko: "챕터 4 진행 중 발생", en: "Available in Chapter 4." },
          body: { ko: "복서 출신 아사쿠라와의 첫 만남. 이치반이 「파운드」 기술을 습득합니다.", en: "First meeting with ex-boxer Asakura. Ichiban learns the 'Pound' skill." },
          reward: { ko: "이치반 「파운드」 습득", en: "Ichiban learns 'Pound'" },
        },
        {
          number: 44,
          title: { ko: "과거와 미래", en: "Past and Future" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 하버 스트리트", en: "Honolulu City — Harbor St." },
          trigger: { ko: "43 클리어 후 발생", en: "Available after clearing Substory 43." },
          body: { ko: "아사쿠라 라인 2단계. 이치반이 「워밍업」을 습득.", en: "Asakura chain part 2; learns 'Warming Up'." },
          reward: { ko: "이치반 「워밍업」 습득", en: "Ichiban learns 'Warming Up'" },
        },
      ],
    },
    {
      title: { ko: "호놀룰루 — 챕터 5~6 묶음 (월드와이드 / 돈도코 섬)", en: "Honolulu — Chapter 5~6 Wave (Worldwide / Dondoko Island)" },
      items: [
        {
          number: 30,
          title: { ko: "미확인 비행물체와 조우", en: "Close Encounter of the UFO Kind" },
          chapter: { ko: "챕터 6 (낮/저녁)", en: "Chapter 6 (Day / Evening)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 카크 애비뉴", en: "Honolulu City — Kirk Ave." },
          trigger: { ko: "29 클리어 후 발생", en: "Available after clearing Substory 29." },
          body: { ko: "UFO에 닭을 빼앗긴 소녀를 도와 오소우지마루의 비행 개조판을 만들어 추격합니다.", en: "Help a girl whose chicken was abducted by a UFO by deploying a flight-mod Cleanup." },
          reward: { ko: "앤티크 코인 + 머리 장식 + 딜리버리 헬프 「오소우지마루 FLY-β MAX」", en: "Antique coin + hair piece + Helper Cleanup FLY-β MAX" },
        },
        {
          number: 31,
          title: { ko: "마법의 말 알로해피", en: "Magic Word: Alohappy" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 월드와이드 마켓 빌리지", en: "Honolulu City — Worldwide Market Village" },
          trigger: { ko: "챕터 5 메인 진행 중 자동 발생", en: "Auto-triggers in Chapter 5." },
          body: { ko: "직업 변경 시스템이 해금되고 마린 마스터가 추가됩니다.", en: "Unlocks job-change and adds the Marine Master job." },
          reward: { ko: "직업 변경 해금 + 마린 마스터", en: "Job change + Marine Master unlocked" },
        },
        {
          number: 32,
          title: { ko: "트로피컬 포토 랠리", en: "Tropical Photo Rally" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 월드와이드 마켓 빌리지", en: "Honolulu City — Worldwide Market Village" },
          trigger: { ko: "31 클리어 후 발생", en: "Available after clearing Substory 31." },
          body: { ko: "스마트폰 앱 「포토 랠리」가 추가되어 랜드마크 사진 수집 컨텐츠가 풀립니다.", en: "Adds the 'Photo Rally' app for landmark photo collection." },
          reward: { ko: "「포토 랠리」 앱", en: "Photo Rally app" },
        },
        {
          number: 33,
          title: { ko: "열려라! 밑바닥의 섬", en: "Open Up! Rock Bottom Island" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "돈도코 섬", en: "Dondoko Island" },
          trigger: { ko: "챕터 6 메인 진행 중 자동 발생", en: "Auto-triggers in Chapter 6." },
          body: { ko: "돈도코 섬 컨텐츠가 본격 해금됩니다.", en: "Unlocks Dondoko Island." },
          reward: { ko: "돈도코 섬 해금", en: "Dondoko Island unlocked" },
        },
        {
          number: 34,
          title: { ko: "하와이의 미궁", en: "The Hawaii Labyrinth" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 리버사이드 워크 (아나콘다 지구)", en: "Honolulu City — Riverside Walk (Anaconda area)" },
          trigger: { ko: "챕터 5 메인 진행 중 자동 발생", en: "Auto-triggers in Chapter 5." },
          body: {
            ko: "지하 던전 「하와이의 미궁」 입구의 노숙자에게 통행료를 지불하고 입장. B3까지 내려가 보스 「앨런」을 격파합니다. 통행료 선택지에서 「10달러」를 내야 정신력 +30 최대 보상이 들어옵니다.",
            en: "Pay the homeless gatekeeper, descend to B3, and beat the boss Allen. Tipping $10 nets the full +30 Mental personality bonus.",
          },
          choices: [
            { prompt: { ko: "「통행료」", en: "Toll" }, correct: { ko: "10달러를 낸다", en: "Pay $10" }, note: { ko: "1달러는 정신력 +20, 무지불은 0", en: "$1 = +20 Mental; refusing pays nothing" } },
          ],
          reward: { ko: "던전 해금 + ★3 무기 「제트 서핑보드」", en: "Dungeon unlocked + 3★ 'Jet Surfboard' weapon" },
        },
        {
          number: 35,
          title: { ko: "사랑과 벌", en: "Love and Punishment" },
          chapter: { ko: "챕터 6 (밤)", en: "Chapter 6 (Night)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 아트 월즈", en: "Honolulu City — Art Walls" },
          trigger: { ko: "야마이 전 클리어 후 발생", en: "Available after the Yamai battle." },
          body: { ko: "야마이와의 인연이 마무리되는 의뢰. 플래티넘 플레이트와 프리미엄 전단지를 받습니다.", en: "Closes Yamai's bond line; awards Platinum Plate and a Premium Flyer." },
          reward: { ko: "플래티넘 플레이트 + 프리미엄 전단지", en: "Platinum Plate + Premium Flyer" },
        },
      ],
    },
    {
      title: { ko: "호놀룰루 — 챕터 9 후반 묶음 (인연·엔딩 노트)", en: "Honolulu — Chapter 9 Wave (Bonds & Ending Note)" },
      items: [
        {
          number: 36,
          title: { ko: "SPARK", en: "SPARK" },
          chapter: { ko: "챕터 9 (낮)", en: "Chapter 9 (Daytime)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 알로하 비치", en: "Honolulu City — Aloha Beach" },
          trigger: { ko: "울트라 본드 기술 해금 후 낮 시간대 알로하 비치 방문", en: "Daytime on Aloha Beach after unlocking the Ultra Bond ability." },
          body: { ko: "동료들의 본드 연계 기술을 마무리하는 의뢰.", en: "Caps off the party's Ultra Bond technique." },
          reward: { ko: "고무 장갑", en: "Rubber gloves" },
        },
        {
          number: 45,
          title: { ko: "마지막 진검승부", en: "Final True Bout" },
          chapter: { ko: "후반부", en: "Late game" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 하버 스트리트", en: "Honolulu City — Harbor St." },
          trigger: { ko: "44 클리어 후 발생", en: "Available after clearing Substory 44." },
          body: { ko: "아사쿠라 라인 3단계. 이치반이 「KO 러시」를 습득.", en: "Asakura chain part 3; learns 'KO Rush'." },
          reward: { ko: "이치반 「KO 러시」 습득", en: "Ichiban learns 'KO Rush'" },
        },
        {
          number: 46,
          title: { ko: "미래를 짊어지고 설 남자", en: "The Man Who Will Carry the Future" },
          chapter: { ko: "후반부", en: "Late game" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 하버 스트리트", en: "Honolulu City — Harbor St." },
          trigger: { ko: "45 클리어 후 발생", en: "Available after clearing Substory 45." },
          body: { ko: "아사쿠라 라인 마지막 의뢰. 마우스가드와 딜리버리 헬프 「아사쿠라」 합류.", en: "Final Asakura chain. Adds Asakura as a Delivery Helper plus a mouthguard." },
          reward: { ko: "딜리버리 헬프 「아사쿠라」 + 마우스가드", en: "Delivery Helper Asakura + mouthguard" },
        },
        {
          number: 47,
          title: { ko: "로라에게 흠뻑", en: "Rola, All The Way" },
          chapter: { ko: "후반부", en: "Late game" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 하버 스트리트", en: "Honolulu City — Harbor St." },
          trigger: { ko: "라이센스 시험 전부 합격 + 「지식」 7 이상 + 로라에게 선물 3회", en: "Pass every license exam, Knowledge 7+, gift Rola 3 times." },
          body: { ko: "로라·이카리와의 인연 라인 마무리. 돈도코 섬에 게스트로 초대 가능.", en: "Wraps the Rola & Ikari bond line; invites them to Dondoko Island." },
          reward: { ko: "로라 & 이카리 섬 초대 해금", en: "Rola & Ikari invited to the island" },
        },
        {
          number: 48,
          title: { ko: "최고로 알로해피한 체험!", en: "The Most Alohappy Experience!" },
          chapter: { ko: "후반부", en: "Late game" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 월드와이드 마켓 빌리지", en: "Honolulu City — Worldwide Market Village" },
          trigger: { ko: "마켓 액티비티 전 종목 완료 + 「쾌활함」 7 이상 + 엘리자베스에게 선물 3회", en: "Clear all market activities, Cheer 7+, gift Elizabeth 3 times." },
          body: { ko: "엘리자베스와 마스코트를 돈도코 섬 게스트로 초대.", en: "Invite Elizabeth and her mascot to the island." },
          reward: { ko: "엘리자베스 & 마스코트 섬 초대", en: "Elizabeth & mascot invited" },
        },
        {
          number: 49,
          title: { ko: "매칭매칭 마치코 선생", en: "Match Me, Ms. Machiko" },
          chapter: { ko: "후반부", en: "Late game" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 와이키키 스트리트", en: "Honolulu City — Waikiki St." },
          trigger: { ko: "매칭 앱 10명 전원과 만남 + 「세련됨」 7 이상 + 선물 3회", en: "Meet all 10 Miss Match users, Style 7+, gift 3 times." },
          body: { ko: "마치코 선생을 돈도코 섬 게스트로 초대.", en: "Invite Ms. Machiko to the island." },
          reward: { ko: "마치코 섬 초대", en: "Ms. Machiko invited" },
        },
        {
          number: 50,
          title: { ko: "쭉 둘이서…", en: "Together, Forever…" },
          chapter: { ko: "후반부", en: "Late game" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 오아후 버거", en: "Honolulu City — Oahu Burger" },
          trigger: { ko: "딜리버리 헬프 10회 이상 호출 + 「열정」 7 이상 + 치토세에게 선물 3회", en: "Use Delivery Help 10+ times, Passion 7+, gift Chitose 3 times." },
          body: { ko: "치토세와의 인연 라인 마무리.", en: "Wraps the Chitose bond line." },
          reward: { ko: "치토세 섬 초대", en: "Chitose invited" },
        },
        {
          number: 51,
          title: { ko: "Virgin Emotion", en: "Virgin Emotion" },
          chapter: { ko: "후반부 (저녁/밤)", en: "Late game (Evening / Night)" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 줄리스 기어 웍스 본점", en: "Honolulu City — Julie's Gear Works (main shop)" },
          trigger: { ko: "줄리 시설 랭크 4 + 「친절함」 7 이상 + 선물 3회", en: "Julie shop rank 4, Kindness 7+, gift Julie 3 times." },
          body: { ko: "줄리와의 인연 라인 마무리. 민첩성 상승.", en: "Wraps the Julie bond line; raises Agility." },
          reward: { ko: "줄리 섬 초대 + 민첩 상승", en: "Julie invited + Agility up" },
        },
        {
          number: 52,
          title: { ko: "수라장", en: "Surviving Paradise" },
          chapter: { ko: "후반부", en: "Late game" },
          protagonist: { ko: "이치반", en: "Ichiban" },
          location: { ko: "호놀룰루 시티 — 리볼버", en: "Honolulu City — Revolver bar" },
          trigger: { ko: "47~51 인연 라인 전부 클리어 후 발생", en: "Available after clearing Substories 47~51." },
          body: { ko: "다섯 명의 여성 인연이 모두 풀린 뒤 리볼버에서 일어나는 「수라장」. 무사히 정리하면 이치반의 방어가 영구 상승합니다.", en: "After all five bond lines wrap, the women converge at the Revolver bar. Survive the showdown to permanently raise Ichiban's Defense." },
          reward: { ko: "이치반 방어 영구 상승", en: "Permanent Defense up for Ichiban" },
        },
      ],
    },
  ],
};
