import type { SubstoriesData } from "./types";

export const likeADragonIshinSubstories: SubstoriesData = {
  appId: 1805480,
  summary: {
    ko: "막말 교토를 무대로 한 「유신!극」의 서브스토리는 총 72건. 미스 불가 항목은 없으므로 본편 챕터 진행과 병행해도 무방하나, 챕터 종료 후에도 의뢰가 사라지지 않습니다. 구역(라쿠나이/라쿠가이/무쿠로가이/후시미/기온/미부)별로 분포하며, 일부는 흑표비각·야에·사토우 연쇄 의뢰로 묶여 순서대로 해금됩니다.",
    en: "Like a Dragon: Ishin! has 72 substories across Bakumatsu Kyoto. None are missable — chapters gate them but they remain available afterward. They sprawl across Rakunai, Rakugai, Mukurogai, Fushimi, Gion, and Mibu, with the Black Panther couriers, Yae, and Satow strands forming locked chains.",
  },
  source: {
    label: "PowerPyx — Like a Dragon: Ishin! Substory Guide",
    url: "https://www.powerpyx.com/like-a-dragon-ishin-substory-guide/",
  },
  groups: [
    {
      title: { ko: "라쿠나이 — 교토 도심", en: "Rakunai — Central Kyo" },
      items: [
        {
          number: 1,
          title: { ko: "니치부좌의 새 단골", en: "Nichibuza's Newest Fan" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠나이 — 극장 니치부좌 앞", en: "Rakunai — outside Nichibuza theater" },
          trigger: { ko: "니치부좌 앞에서 다투는 남녀 컷신을 본 뒤 개입", en: "Watch the arguing couple cutscene outside Nichibuza, then step in." },
          body: {
            ko: "다툼을 말리고 습격자를 제압한 뒤 부채춤 미니게임을 한 곡 완주하면 종료. 이후 부채춤이 정식 해금되어 라쿠나이 전반의 유흥 컴플리션이 풀립니다.",
            en: "Break up the fight, beat the thugs, and clear one round of the fan-dance minigame. Completing it unlocks the fan-dance feature city-wide.",
          },
          reward: { ko: "부채춤 미니게임 해금 + 덕 보상", en: "Fan-dance minigame unlocked + Virtue" },
        },
        {
          number: 2,
          title: { ko: "사기꾼 에비스님", en: "Deceitful Deity" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠나이 — 카라스마 거리", en: "Rakunai — Karasuma St." },
          trigger: { ko: "카라스마 거리에서 에비스님 행세하는 자를 묻는 남자에게 말 걸기", en: "Talk to the man asking about Ebisu-sama near Karasuma St." },
          body: {
            ko: "사이비 에비스 행세를 하는 노인을 신메이쵸 부근까지 추적해 전투로 정리합니다. 사기꾼이 막말 교토에서도 횡행함을 보여주는 코믹 의뢰.",
            en: "Track the fake Ebisu down to Shinmeicho and beat him in a one-on-one. A comic riff on small-time grifters in Bakumatsu Kyo.",
          },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 3,
          title: { ko: "누가 누구를 접대하는가", en: "Who's Entertaining Who?" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠나이 — 시코쿠야 앞", en: "Rakunai — outside Shikokuya" },
          trigger: { ko: "시코쿠야 앞 여인에게 말 걸기 (서브 1 클리어 + 가라오케 1회 필요)", en: "Talk to the woman outside Shikokuya (requires Substory 1 cleared and one karaoke session)." },
          body: {
            ko: "료마가 게이샤 대신 손님을 접대하게 되는 상황. 가라오케와 부채춤으로 마음을 사로잡은 뒤 마지막 전투까지 마무리.",
            en: "Ryoma has to entertain a guest in a geisha's place — perform karaoke and a fan dance, then settle things in a final brawl.",
          },
          choices: [
            { prompt: { ko: "「어떤 노래였습니까?」", en: "'How was the song?'" }, correct: { ko: "「대담하고 호쾌했지」", en: "'It was bold and virile'" } },
            { prompt: { ko: "「춤은 어땠는지요?」", en: "'And the dance?'" }, correct: { ko: "「대담하면서도 우아했어」", en: "'It's bold, yet elegant'" } },
          ],
          reward: { ko: "덕 보상 + 컴플리션", en: "Virtue + completion credit" },
        },
        {
          number: 4,
          title: { ko: "잘 가, 미호", en: "I'll Miss You, Miho" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠나이 — 니치부좌 뒤편", en: "Rakunai — behind Nichibuza" },
          trigger: { ko: "니치부좌 뒤편에서 료마와 부딪히는 아이의 이벤트", en: "A child runs into Ryoma behind Nichibuza." },
          body: {
            ko: "헤어지게 된 두 아이의 마지막 인사를 전달하는 의뢰. 가마를 쫓아가 메시지를 전하면 끝.",
            en: "Carry a final message between two children before they're separated. Chase the palanquin to deliver it.",
          },
          choices: [
            { prompt: { ko: "남자아이에게 첫 질문", en: "First prompt to the boy" }, correct: { ko: "첫 번째 선택지", en: "First option" } },
            { prompt: { ko: "남자아이에게 두 번째 질문", en: "Second prompt to the boy" }, correct: { ko: "세 번째 선택지", en: "Third option" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 5,
          title: { ko: "수다쟁이 토사 사나이", en: "Talking Tosa" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠나이 — 니치부좌 북동측 골목", en: "Rakunai — alley NE of Nichibuza" },
          trigger: { ko: "골목 구석에 서 있는 남자에게 말 걸기", en: "Talk to the man standing in the corner NE of Nichibuza." },
          body: {
            ko: "토사 사투리투성이 연애편지 세 통을 료마가 통역해 주는 의뢰. 세 차례에 걸쳐 선택지를 정확히 골라야 결말이 좋게 끝납니다.",
            en: "Translate three Tosa-dialect love letters for a tongue-tied admirer. Pick the right option each round for the happy ending.",
          },
          choices: [
            { prompt: { ko: "편지 1 — 첫 줄", en: "Letter 1, line 1" }, correct: { ko: "「오랜만이군」", en: "'It's been a while'" } },
            { prompt: { ko: "편지 1 — 둘째 줄", en: "Letter 1, line 2" }, correct: { ko: "「나」", en: "'I'" } },
            { prompt: { ko: "편지 1 — 셋째 줄", en: "Letter 1, line 3" }, correct: { ko: "「'당신'을 가리키는 말」", en: "'She means \"you\"'" } },
            { prompt: { ko: "편지 2 — 첫 줄", en: "Letter 2, line 1" }, correct: { ko: "「'매일같이'라는 뜻」", en: "'She means \"is that every day?\"'" } },
            { prompt: { ko: "편지 2 — 둘째 줄", en: "Letter 2, line 2" }, correct: { ko: "「마음이 아프다」", en: "'Her heart aches'" } },
            { prompt: { ko: "편지 2 — 셋째 줄", en: "Letter 2, line 3" }, correct: { ko: "「곧 만나자」", en: "'Meet soon'" } },
            { prompt: { ko: "편지 3 — 첫 줄", en: "Letter 3, line 1" }, correct: { ko: "「발을 헛디뎌 넘어진다」", en: "'Stumble and fall'" } },
            { prompt: { ko: "편지 3 — 둘째 줄", en: "Letter 3, line 2" }, correct: { ko: "「겁쟁이 남자들」", en: "'Cowardly men'" } },
            { prompt: { ko: "편지 3 — 셋째 줄", en: "Letter 3, line 3" }, correct: { ko: "「마음을 솔직히 전해라」", en: "'Tell her how you feel'" } },
          ],
          reward: { ko: "수다쟁이 토사 사나이와의 인연", en: "Bond with Talking Tosa" },
        },
        {
          number: 6,
          title: { ko: "사라진 떡의 수수께끼", en: "The Mochi Mystery" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠나이 — 대장간 북측", en: "Rakunai — north of the blacksmith" },
          trigger: { ko: "대장간 북측에 모여 있는 무리에게 말 걸기", en: "Approach the cluster of men north of the blacksmith." },
          body: {
            ko: "사라진 떡을 누가 먹었는지 추리하는 의뢰. 증언을 종합해 정답 두 명(히가시하라·미아미노)을 지목해야 클리어.",
            en: "Deduce which two of the suspects ate the missing mochi from their alibis.",
          },
          choices: [
            { prompt: { ko: "「첫 번째 범인」", en: "'First culprit'" }, correct: { ko: "히가시하라(1번)", en: "Higashihara (1st)" } },
            { prompt: { ko: "「두 번째 범인」", en: "'Second culprit'" }, correct: { ko: "미아미노(4번)", en: "Miamino (4th)" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 7,
          title: { ko: "정의를 위한 에에쟈나이카", en: "Ea Ja Nai For Justice" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠나이 — 신메이쵸 장기 도장 서측", en: "Rakunai — west of the Shogi Parlor in Shinmeicho" },
          trigger: { ko: "신메이쵸 서측의 「에에쟈나이카」 군중과 접촉 (서브 22 클리어 필요)", en: "Approach the Ee Ja Nai Ka dancers west of the Shogi Parlor (requires Substory 22)." },
          body: {
            ko: "에에쟈나이카 춤을 빙자해 행패를 부리는 무리를 진압. 막말 풍속의 한 단면을 다루는 코믹 의뢰.",
            en: "Break up a band exploiting the Ee Ja Nai Ka craze for hooliganism — a snapshot of Bakumatsu street culture.",
          },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 8,
          title: { ko: "내키지 않는 비각", en: "The Unwilling Courier" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "라쿠나이 — 기온으로 가는 다리", en: "Rakunai — bridge to Gion" },
          trigger: { ko: "기온으로 가는 다리를 처음 건널 때 자동 발생", en: "Auto-triggered when crossing the bridge to Gion." },
          body: {
            ko: "료마가 얼떨결에 비각(파발꾼)이 되어 제한 시간 내에 편지 6통을 배달해야 합니다. 흑표비각 연쇄 의뢰의 시작점.",
            en: "Ryoma's roped into delivering six letters within a strict time limit — the gateway to the Black Panther courier chain.",
          },
          reward: { ko: "흑표비각 라인 해금", en: "Unlocks Black Panther Couriers chain" },
        },
        {
          number: 9,
          title: { ko: "흑표비각 등장", en: "Enter the Black Panther Couriers" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "라쿠나이 — 기온행 다리", en: "Rakunai — bridge to Gion" },
          trigger: { ko: "서브 8 클리어 후 같은 다리에서 발생", en: "Same bridge as Substory 8, after clearing it." },
          body: {
            ko: "전설의 흑표비각 단원과 배달 속도 대결. 다음 의뢰의 해금 조건.",
            en: "Race a Black Panther courier in a delivery sprint to unlock the next link in the chain.",
          },
          reward: { ko: "다음 단계 해금", en: "Unlocks next chain step" },
        },
        {
          number: 10,
          title: { ko: "흑표비각의 간판", en: "The Panthers' Leading Man" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "라쿠나이 — 테라마치 거리 북단", en: "Rakunai — north end of Teramachi St." },
          trigger: { ko: "테라마치 북단에서 흑표비각 단원과 접촉 (서브 9 클리어 필요)", en: "Speak to the courier at north Teramachi (requires Substory 9)." },
          body: {
            ko: "12통의 편지를 경쟁 주자보다 빨리 배달. 코스가 라쿠나이 전역을 가로지르므로 단축 경로 파악이 중요.",
            en: "Deliver 12 letters faster than a rival courier across all of Rakunai. Shortcut knowledge matters.",
          },
          reward: { ko: "다음 의뢰 해금", en: "Unlocks next courier substory" },
        },
        {
          number: 11,
          title: { ko: "지구본 사기", en: "Global Fraud" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠나이 — 돈키호테 남측 도로", en: "Rakunai — road south of Don Quijote" },
          trigger: { ko: "지구본을 든 남자에게 말 걸기", en: "Talk to the man with the globe." },
          body: {
            ko: "지구본으로 아이들에게 사기를 치는 남자에게 올바른 나라를 짚어 망신 주는 의뢰. 막말기 양학 유행을 풍자.",
            en: "A street huckster lectures kids with a doctored globe. Call out the correct countries to shame him.",
          },
          choices: [
            { prompt: { ko: "「여기는 어디인가?」", en: "'Where is this?'" }, correct: { ko: "「일본」", en: "'Japan'" } },
            { prompt: { ko: "「그러면 여기는?」", en: "'And here?'" }, correct: { ko: "「대청국」", en: "'The Great Qing'" } },
            { prompt: { ko: "「마지막 질문」", en: "'Final question'" }, correct: { ko: "「4번 국가」", en: "'Country 4'" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 12,
          title: { ko: "허기진 스모토리", en: "The Hungry Sumo Wrestler" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "라쿠나이 — 테라마치 거리 남측", en: "Rakunai — south Teramachi St." },
          trigger: { ko: "길을 막은 스모토리에게 말 걸기", en: "Talk to the sumo wrestler blocking the road." },
          body: { ko: "굶주린 스모토리에게 음식 아이템을 건네 길을 트게 합니다.", en: "Hand the hungry sumo a food item to clear the road." },
          reward: { ko: "스모토리와의 인연", en: "Bond with Hungry Sumo Wrestler" },
        },
        {
          number: 13,
          title: { ko: "애정 결핍 남편", en: "The Love-Starved Husband" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "라쿠나이 — 동측 강변", en: "Rakunai — east riverbank" },
          trigger: { ko: "강을 바라보는 남자에게 말 걸기", en: "Talk to the man staring at the river on the east side." },
          body: { ko: "아내의 손맛이 그리운 남편 앞에서 료마가 손수 만든 요리를 먹어 보여 줍니다.", en: "Eat a homemade dish in front of a husband who misses his wife's cooking." },
          reward: { ko: "애정 결핍 남편과의 인연", en: "Bond with Love-Starved Husband" },
        },
        {
          number: 14,
          title: { ko: "정신 나간 여인", en: "The Oblivious Woman" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "라쿠나이 — 북측 가마터", en: "Rakunai — palanquin stand, north of map" },
          trigger: { ko: "가마 근처 여인에게 말 걸기", en: "Talk to the woman by the northern palanquin." },
          body: { ko: "지갑을 잃어버려 멍해 있는 여인에게 채소를 건넵니다.", en: "Hand a vegetable to a woman who's lost her wallet." },
          reward: { ko: "정신 나간 여인과의 인연", en: "Bond with Oblivious Woman" },
        },
        {
          number: 15,
          title: { ko: "다친 할머니", en: "The Injured Grandma" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠나이 — 동측 강변", en: "Rakunai — east riverbank" },
          trigger: { ko: "강변에 앉아 있는 여인에게 말 걸기", en: "Talk to the woman sitting on the east riverbank." },
          body: { ko: "다친 노부인의 부탁을 받아들이고 도움을 약속합니다.", en: "Agree to help the injured old woman." },
          reward: { ko: "다친 할머니와의 인연", en: "Bond with Injured Grandma" },
        },
        {
          number: 16,
          title: { ko: "짖어대는 개", en: "The Barking Dog" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "라쿠나이 — 에비스 전당포 부근 큰길 남측", en: "Rakunai — south of the main road near Ebisu Pawn" },
          trigger: { ko: "짖어대는 개에게 다가가기", en: "Approach the barking dog." },
          body: { ko: "개에게 뼈를 던져 주면 친해집니다.", en: "Toss a bone to the barking dog." },
          reward: { ko: "짖어대는 개와의 인연", en: "Bond with Barking Dog" },
        },
        {
          number: 17,
          title: { ko: "운수 좋은 고양이", en: "The Lucky Cat" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "라쿠나이 — 신사 동측", en: "Rakunai — east of the shrine" },
          trigger: { ko: "신사 동측의 고양이에게 말 걸기", en: "Approach the cat east of the shrine." },
          body: { ko: "복을 부르는 고양이에게 돈을 바칩니다.", en: "Offer coin to the lucky cat." },
          reward: { ko: "운수 좋은 고양이와의 인연", en: "Bond with Lucky Cat" },
        },
        {
          number: 67,
          title: { ko: "성깔 있는 빚쟁이", en: "The Spitfire Debt Collector" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "라쿠나이 — 쿠로가네 대장간 앞", en: "Rakunai — outside Kurogane Smithing" },
          trigger: { ko: "서브 69 클리어 후 쿠로가네 대장간 앞에서 야에에게 말 걸기", en: "Talk to Yae outside Kurogane Smithing (requires Substory 69)." },
          body: {
            ko: "성깔 있는 처녀 야에의 빚 수금에 동행. 변제 거부 채무자들을 차례차례 삥쟁이 못잖은 기세로 정리합니다.",
            en: "Tag along with the spitfire Yae as she shakes down delinquents — debtor by debtor.",
          },
          reward: { ko: "야에 연쇄 다음 단계 해금", en: "Advances the Yae chain" },
        },
        {
          number: 68,
          title: { ko: "성깔 있는 거짓말 탐지기", en: "The Spitfire Lie Detector" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "라쿠나이 — 쿠로가네 대장간", en: "Rakunai — Kurogane Smithing" },
          trigger: { ko: "서브 67 클리어 후 야에와 재회", en: "Return to Yae after clearing Substory 67." },
          body: { ko: "야에와 함께 거짓말쟁이를 색출하고 두 그룹과 연이어 전투.", en: "Help Yae sniff out a liar and clear two consecutive fights." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
      ],
    },
    {
      title: { ko: "라쿠가이 — 교토 외곽", en: "Rakugai — Outer Kyo" },
      items: [
        {
          number: 18,
          title: { ko: "은둔하는 아들", en: "The Reclusive Son" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠가이 — 동 우메코지쵸", en: "Rakugai — East Umekojicho" },
          trigger: { ko: "건물 밖에서 대화하는 두 사람에게 말 걸기", en: "Approach the two people talking outside the houses." },
          body: {
            ko: "히키코모리 아들을 둔 부모의 부탁. 본인의 자신감을 끌어올리는 방향으로 조언해야 정상 결말.",
            en: "Counsel a shut-in son toward self-confidence — pick the encouraging branches.",
          },
          choices: [
            { prompt: { ko: "「요즘 무엇을 하나?」", en: "'What are you up to?'" }, correct: { ko: "「요즘 무엇을 하나?」 선택", en: "'What are you up to?'" } },
            { prompt: { ko: "「조언은?」", en: "'Advice?'" }, correct: { ko: "「사람과 어울려라」", en: "'Make a personal connection'" } },
            { prompt: { ko: "「마지막 한 마디」", en: "'Final push'" }, correct: { ko: "「자신감을 북돋워라」", en: "'Boost his self-confidence'" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 19,
          title: { ko: "가마 호위", en: "Palanquin Paladin" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "라쿠가이 — 남서측 가마터", en: "Rakugai — southwest palanquin stand" },
          trigger: { ko: "가마 근처에서 시작", en: "Approach the palanquin at the SW corner." },
          body: { ko: "라쿠가이를 가로지르는 가마를 여러 무리로부터 지키는 호위 의뢰.", en: "Defend a moving palanquin through several waves of attackers." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 20,
          title: { ko: "한 마디 인용 좀 합시다", en: "Can I Quote You On That?" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "라쿠가이 — 동 우메코지쵸 신사 서측", en: "Rakugai — East Umekojicho, west of the shrine" },
          trigger: { ko: "기자를 두들기는 남자들을 발견하면 시작", en: "Intervene when a journalist is being roughed up." },
          body: {
            ko: "취재 기자의 5문 5답에 정답을 골라야 합니다. 신선조 일원다운 답을 선택.",
            en: "Answer five interview questions — pick the line a true Shinsengumi captain would say.",
          },
          choices: [
            { prompt: { ko: "「왜 싸우는가?」", en: "'Why fight?'" }, correct: { ko: "「내 임무일 뿐이오」", en: "'It's my duty, nothing more'" } },
            { prompt: { ko: "「적에게 한마디」", en: "'Word to the enemy?'" }, correct: { ko: "「집에 돌아가 가족이나 챙기시오」", en: "'Go home and be family men'" } },
            { prompt: { ko: "「이상형은?」", en: "'Ideal partner?'" }, correct: { ko: "「뜻이 통하는 사람」", en: "'Someone I get along with'" } },
            { prompt: { ko: "「검의 길이란?」", en: "'The way of the sword?'" }, correct: { ko: "「진정한 강함의 길」", en: "'It's a path for true strength'" } },
            { prompt: { ko: "「독자에게 한 말씀」", en: "'Final word?'" }, correct: { ko: "「순수함을 잃지 마시오」", en: "'Maintain your innocence'" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 21,
          title: { ko: "존왕양이", en: "Sonno Joui" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠가이 — 수상한 술집 북측 골목", en: "Rakugai — alley north of the Shady Bar" },
          trigger: { ko: "골목에서 대화 중인 두 남자에게 말 걸기", en: "Approach the two men talking in the alley." },
          body: { ko: "외국인을 노리는 존왕양이 낭사들을 두 장소에서 격퇴.", en: "Defend a foreigner from sonno-joui zealots at two locations." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 22,
          title: { ko: "에에쟈나이카(아니지)", en: "Ea Ja Not Ka" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠가이 — 무쿠로가이 인접 동 우메코지쵸", en: "Rakugai — East Umekojicho, near Mukurogai" },
          trigger: { ko: "서브 47 클리어 후 발생", en: "After clearing Substory 47." },
          body: { ko: "에에쟈나이카 무리를 미행해 진짜 정체를 확인. 추적 액션 중심.", en: "Tail a band of Ee Ja Nai Ka dancers to expose them — pure shadowing." },
          reward: { ko: "서브 7 해금", en: "Unlocks Substory 7" },
        },
        {
          number: 23,
          title: { ko: "엉뚱한 골목에서 큰소리치다", en: "Bluffin' Up the Wrong Alley" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "라쿠가이 — 도박장 앞", en: "Rakugai — outside the gambling den" },
          trigger: { ko: "도박장 앞 도박꾼 무리의 행패 장면", en: "Witness the gamblers harassing a passerby outside the den." },
          body: {
            ko: "도박꾼 일당의 행패를 막고 무쿠로가이까지 따라가 정리. 신선조 의복 착용 상태여야 진행이 풀립니다.",
            en: "Break up the gamblers' shakedown and finish them in Mukurogai. Requires Shinsengumi robes to advance.",
          },
          prereq: { ko: "신선조 의복 착용 필요", en: "Must be wearing Shinsengumi robes" },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 24,
          title: { ko: "흑표비각의 야전사령관", en: "The Panthers' Playmaker" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "라쿠가이 — 자택(편지 수령)", en: "Rakugai — your house (letter arrives)" },
          trigger: { ko: "서브 10 클리어 후 자택에 편지 도착", en: "Letter arrives at home after Substory 10." },
          body: { ko: "다리 위에서 비각 단원과 또 한 차례 배달 대결.", en: "Another bridge-side delivery race against a Panther." },
          reward: { ko: "다음 단계 해금", en: "Unlocks next chain step" },
        },
        {
          number: 25,
          title: { ko: "검 매니아", en: "The Sword Nut" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "라쿠가이 — 부두로 내려가는 계단 옆", en: "Rakugai — beside the dock stairs" },
          trigger: { ko: "검 매니아 남자에게 말 걸기", en: "Speak to the sword enthusiast." },
          body: { ko: "료마의 검을 검 마니아에게 보여 줍니다.", en: "Show your sword to the enthusiast." },
          reward: { ko: "검 매니아와의 인연", en: "Bond with Sword Nut" },
        },
        {
          number: 26,
          title: { ko: "지친 수호자", en: "The Battered Defender" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "라쿠가이 — 후시미 관문 북측", en: "Rakugai — north of the Fushimi gate" },
          trigger: { ko: "지친 무사에게 말 걸기", en: "Approach the worn-out defender." },
          body: { ko: "회복 아이템을 건네 부상자를 일으켜 세웁니다.", en: "Give a healing item to the wounded warrior." },
          reward: { ko: "지친 수호자와의 인연", en: "Bond with Battered Defender" },
        },
        {
          number: 27,
          title: { ko: "수상한 상인", en: "The Mysterious Merchant" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "라쿠가이 — 무기상 맞은편 헛간", en: "Rakugai — wooden shed across from the Arms Dealer" },
          trigger: { ko: "헛간 안 상인에게 말 걸기", en: "Speak to the merchant in the shed." },
          body: { ko: "토마토 10개를 모아 건네면 2냥을 받습니다.", en: "Bring 10 tomatoes for 2 ryo." },
          reward: { ko: "수상한 상인과의 인연 + 2냥", en: "Bond with Mysterious Merchant + 2 ryo" },
        },
        {
          number: 28,
          title: { ko: "굶주린 고양이", en: "The Hungry Cat" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "라쿠가이 — 동 우메코지쵸 건물 사이", en: "Rakugai — between buildings in East Umekojicho" },
          trigger: { ko: "고양이에게 다가가기", en: "Approach the hungry cat." },
          body: { ko: "생선을 던져 주어 친해집니다.", en: "Give the cat a fish." },
          reward: { ko: "굶주린 고양이와의 인연", en: "Bond with Hungry Cat" },
        },
        {
          number: 69,
          title: { ko: "성깔 있는 마을 수호자", en: "The Spitfire Town Protector" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "라쿠가이 — 닭싸움장 동측", en: "Rakugai — east of the Chicken Racing building" },
          trigger: { ko: "다투는 부부 사이에 끼어들기", en: "Step in between the arguing couple." },
          body: { ko: "부부 싸움에 끼어든 패거리를 제압하다 야에와 처음 만나게 됩니다.", en: "Break up a brawl and first meet Yae, who later headlines the chain." },
          reward: { ko: "야에 연쇄 시작", en: "Starts the Yae chain" },
        },
      ],
    },
    {
      title: { ko: "무쿠로가이 — 빈민·악소굴", en: "Mukurogai — Slums & Underworld" },
      items: [
        {
          number: 29,
          title: { ko: "험한 동네", en: "The Bad Side of Town" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "무쿠로가이 — 무기상 북측", en: "Mukurogai — north of Arms Dealer" },
          trigger: { ko: "무기상 북측을 지나갈 때 자동 발생", en: "Walk past the Arms Dealer northward." },
          body: { ko: "무쿠로가이의 험한 분위기를 보여주는 매복 전투.", en: "An automatic ambush that introduces Mukurogai's hostility." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 30,
          title: { ko: "삯싸움꾼", en: "Brawler for Hire" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "무쿠로가이 — 1층 흰 깃발 옆", en: "Mukurogai — 1F by the white flag" },
          trigger: { ko: "흰 깃발 옆에서 발생 (서브 7 클리어 필요)", en: "By the white flag (requires Substory 7)." },
          body: { ko: "삯싸움꾼 「스미보즈」와의 1차전.", en: "First duel with the brawler Sumi Bozu." },
          reward: { ko: "다음 단계 해금", en: "Unlocks next fight" },
        },
        {
          number: 31,
          title: { ko: "각성한 싸움꾼", en: "Brawler Incarnate" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "무쿠로가이 — 1층 흰 깃발 옆", en: "Mukurogai — same spot" },
          trigger: { ko: "서브 30 클리어 후 같은 장소", en: "Return to the spot after Substory 30." },
          body: { ko: "스미보즈와 2차전.", en: "Rematch with Sumi Bozu." },
          reward: { ko: "다음 단계 해금", en: "Unlocks next fight" },
        },
        {
          number: 32,
          title: { ko: "깨달음에 이른 싸움꾼", en: "Brawler Enlightened" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "무쿠로가이 — 1층 흰 깃발 옆", en: "Mukurogai — same spot" },
          trigger: { ko: "서브 31 클리어 후 같은 장소", en: "Return again after Substory 31." },
          body: { ko: "스미보즈와의 최종전.", en: "Final showdown with Sumi Bozu." },
          reward: { ko: "덕 대량", en: "Heavy Virtue" },
        },
        {
          number: 33,
          title: { ko: "패주 무사의 망령", en: "Night of the Living Rumor" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "무쿠로가이 — 동측 강변(야간)", en: "Mukurogai — eastern riverbank, nighttime" },
          trigger: { ko: "낮에 소문을 들은 뒤 밤에 강변 재방문", en: "Hear the rumor by day, return at night." },
          body: { ko: "유령 소문의 정체와 야간 전투.", en: "Confront the 'ghost' at night and beat the truth out of it." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 34,
          title: { ko: "비굴한 거지", en: "The Servile Beggar" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "무쿠로가이 — 무기상 동측 처마 밑(1층)", en: "Mukurogai — covered area east of Arms Dealer, 1F" },
          trigger: { ko: "앉아 있는 거지에게 말 걸기", en: "Approach the seated beggar." },
          body: { ko: "음식 아이템을 건넵니다.", en: "Give a food item." },
          reward: { ko: "비굴한 거지와의 인연", en: "Bond with Servile Beggar" },
        },
        {
          number: 35,
          title: { ko: "고물상", en: "The Trash Dealer" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "무쿠로가이 — 북서측 큰 문 옆", en: "Mukurogai — NW corner near the big gate" },
          trigger: { ko: "고물상 남자에게 말 걸기", en: "Talk to the trash dealer." },
          body: { ko: "인벤토리의 아이템 아무거나 하나를 건네면 됩니다.", en: "Hand over any inventory item." },
          reward: { ko: "고물상과의 인연", en: "Bond with Trash Dealer" },
        },
        {
          number: 36,
          title: { ko: "다친 개", en: "The Injured Dog" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "무쿠로가이 — 중앙 1층", en: "Mukurogai — central 1F" },
          trigger: { ko: "다친 개에게 다가가기", en: "Approach the injured dog." },
          body: { ko: "회복 아이템을 건넵니다.", en: "Give a healing item." },
          reward: { ko: "다친 개와의 인연", en: "Bond with Injured Dog" },
        },
      ],
    },
    {
      title: { ko: "후시미 — 사카모토 료마의 고향", en: "Fushimi — Ryoma's Home Base" },
      items: [
        {
          number: 37,
          title: { ko: "작가의 죽음", en: "Death of the Author" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          location: { ko: "후시미 — 데라다야 2층 복도", en: "Fushimi — Teradaya 2F hallway" },
          trigger: { ko: "데라다야 2층 복도의 작가에게 말 걸기", en: "Speak to the writer in the Teradaya 2F hall." },
          body: {
            ko: "슬럼프에 빠진 작가에게 세 차례 영감을 제공. 매번 다른 정답을 골라야 명작이 완성됩니다.",
            en: "Pitch three ideas to a blocked author across separate visits — each round has a unique correct answer.",
          },
          choices: [
            { prompt: { ko: "첫 방문", en: "First visit" }, correct: { ko: "「고양이 이야기는 어떻소」", en: "'A cat might be funny'" } },
            { prompt: { ko: "두 번째 방문", en: "Second visit" }, correct: { ko: "「봇짱!」", en: "'Botch-chan!'" } },
            { prompt: { ko: "세 번째 방문", en: "Third visit" }, correct: { ko: "「마음」", en: "'Heart'" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 38,
          title: { ko: "소중한 꾸러미", en: "Precious Packages" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "후시미 — 데라다야 북측 건물 사이", en: "Fushimi — between buildings north of Teradaya" },
          trigger: { ko: "서브 71 클리어 후 발생", en: "Available after Substory 71." },
          body: {
            ko: "뒤바뀐 꾸러미를 되찾아 본 주인에게 돌려주는 의뢰. 도중에 어묵을 먹지 말 것 — 먹으면 본래 보상이 사라집니다.",
            en: "Recover and return a swapped package. Crucially: do NOT eat the chikuwa or you lose the reward.",
          },
          choices: [
            { prompt: { ko: "「어묵을 먹어 볼까?」", en: "'Should I eat the chikuwa?'" }, correct: { ko: "「먹지 않는다」", en: "Don't eat it" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 39,
          title: { ko: "발가벗긴 사나이", en: "A Clean Streak" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "후시미 — 목욕탕 입구", en: "Fushimi — bathhouse entrance" },
          trigger: { ko: "목욕탕 앞에서 발생", en: "At the bathhouse entrance." },
          body: { ko: "옷을 훔쳐 달아난 도둑을 쫓아 목욕탕으로 되돌아옵니다.", en: "Chase a clothing thief and return to the bathhouse." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 40,
          title: { ko: "보자기 사나이", en: "A Man and His Sack" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "후시미 — 하나코 북측 줄선 자리", en: "Fushimi — line of men north of Hanako" },
          trigger: { ko: "줄에 서 있는 남자에게 말 걸기", en: "Join the queue and talk to the men." },
          body: { ko: "이나리(유부초밥) 줄을 세 번 서다가 도둑을 추적해 잡는 의뢰.", en: "Queue three times for inari, then chase down the thief who runs off with it." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 41,
          title: { ko: "허리에서 우러나는 맛", en: "All in the Hips" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          location: { ko: "후시미 — 우마이 우동", en: "Fushimi — Umai Udon" },
          trigger: { ko: "우마이 우동에서 주문 후 한 번 나갔다가 재방문", en: "Order at Umai Udon, leave, return." },
          body: { ko: "우동 반죽 미니게임 1라운드 클리어.", en: "Clear one round of the udon-kneading minigame." },
          reward: { ko: "우마이 우동 주인과의 인연", en: "Bond with Umai Udon Owner" },
        },
        {
          number: 42,
          title: { ko: "흑선 내습", en: "Invasion of the Black Ships" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "후시미 — 남측 수상지(주간)", en: "Fushimi — southern docks, daytime" },
          trigger: { ko: "낮 시간에 남측 수상지로 이동", en: "Visit the southern waterfront during daytime." },
          body: { ko: "뱃멀미하는 남자에게 매실 절임을 먹여 회복시킨 뒤 습격자를 격퇴.", en: "Cure a seasick man with umeboshi, then fend off attackers." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 43,
          title: { ko: "긴 이야기", en: "It's a Long Story" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          location: { ko: "후시미 — 하나코 서측 길", en: "Fushimi — path west of Hanako" },
          trigger: { ko: "수다스러운 여인에게 말 걸기", en: "Talk to the chatty woman west of Hanako." },
          body: { ko: "끝없이 이어지는 잡담의 1부. 매 단계 정답을 골라야 합니다.", en: "Endure part one of a meandering conversation — pick the right answer each step." },
          choices: [
            { prompt: { ko: "「무엇을 가지러 갔나?」", en: "'What was she fetching?'" }, correct: { ko: "「죽순」", en: "'Bamboo shoots'" } },
            { prompt: { ko: "「어디 앞에서?」", en: "'In front of where?'" }, correct: { ko: "「찻집 앞」", en: "'Outside a tea shop'" } },
            { prompt: { ko: "「그 사람의 이름은?」", en: "'Her name?'" }, correct: { ko: "「물론 사키코」", en: "'Of course – it's Sakiko'" } },
          ],
          reward: { ko: "다음 단계 해금", en: "Unlocks next part" },
        },
        {
          number: 44,
          title: { ko: "긴 이야기: 최종장", en: "It's a Long Story: The Final Chapter" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          location: { ko: "후시미 — 하나코 서측 길", en: "Fushimi — same spot" },
          trigger: { ko: "서브 43 클리어 후 재방문", en: "Return after Substory 43." },
          body: { ko: "사키코의 이야기 후속편.", en: "Round two with Sakiko." },
          choices: [
            { prompt: { ko: "「색은?」", en: "'Colors?'" }, correct: { ko: "「적·백·녹」", en: "'Red, white, and green'" } },
            { prompt: { ko: "「마신 것은?」", en: "'What did she drink?'" }, correct: { ko: "「아마자케」", en: "'Amazake'" } },
            { prompt: { ko: "「그녀의 이름은?」", en: "'Her name?'" }, correct: { ko: "「스미레」", en: "'Sumire'" } },
          ],
          reward: { ko: "다음 단계 해금", en: "Unlocks next part" },
        },
        {
          number: 45,
          title: { ko: "긴 이야기: 에필로그", en: "It's a Long Story: Epilogue" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          location: { ko: "후시미 — 하나코 서측 길", en: "Fushimi — same spot" },
          trigger: { ko: "서브 44 클리어 후 재방문", en: "Return after Substory 44." },
          body: { ko: "수다 연쇄의 대단원.", en: "Finale of the long-talk chain." },
          choices: [
            { prompt: { ko: "「본 것은?」", en: "'What did she see?'" }, correct: { ko: "「허수아비」", en: "'A scarecrow'" } },
            { prompt: { ko: "「먹은 것은?」", en: "'What did she eat?'" }, correct: { ko: "「단무지」", en: "'Pickled daikon'" } },
            { prompt: { ko: "「그것은 무엇이었나?」", en: "'What was it?'" }, correct: { ko: "「참치」", en: "'A tuna'" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 46,
          title: { ko: "향수", en: "Scented Water" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "후시미 — 남동 구석 지장보살", en: "Fushimi — SE corner by the jizo statue" },
          trigger: { ko: "여인에게 말 걸기", en: "Talk to the woman by the jizo." },
          body: { ko: "무쿠로가이의 판매자에게서 향수를 구입해 미행을 따돌리고 의뢰인에게 전달.", en: "Buy perfume in Mukurogai, shake the seller's tail, deliver to the client." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 47,
          title: { ko: "에에쟈나이카", en: "Ea Ja Nai Ka" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          location: { ko: "후시미 — 에비스 전당포 앞", en: "Fushimi — outside Ebisu Pawn" },
          trigger: { ko: "전당포 앞 군중에 막혀 발생", en: "Crowd blocks Ebisu Pawn." },
          body: { ko: "에에쟈나이카로 길을 막은 두 남자와의 전투.", en: "Brawl two ringleaders to disperse the crowd." },
          reward: { ko: "서브 22 해금", en: "Unlocks Substory 22" },
        },
        {
          number: 48,
          title: { ko: "사무라이의 길", en: "The Way of the Samurai" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "후시미 — 센고쿠 저택 서측", en: "Fushimi — west side near Sengoku Residence" },
          trigger: { ko: "지망 사무라이에게 말 걸기", en: "Approach the aspiring samurai." },
          body: { ko: "사무라이 지망생을 세 차례 훈련시킨 뒤 후시미 남측에서 공동 전투.", en: "Train an aspiring samurai across three duels, then fight beside him in South Fushimi." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 49,
          title: { ko: "흑표비각의 최후", en: "Last Stand of the Panthers" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "후시미 — 데라다야 앞", en: "Fushimi — outside Teradaya" },
          trigger: { ko: "서브 24 클리어 후 데라다야 앞", en: "Outside Teradaya after Substory 24." },
          body: { ko: "후시미 전역을 도는 흑표비각 시리즈의 최종 배달 레이스.", en: "Final delivery race around all of Fushimi to finish the Panther chain." },
          reward: { ko: "흑표비각 라인 완결", en: "Completes the Black Panther chain" },
        },
        {
          number: 50,
          title: { ko: "절박한 어부", en: "The Desperate Fisherman" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          location: { ko: "후시미 — 데라다야 남측 난간", en: "Fushimi — south of map near Teradaya railing" },
          trigger: { ko: "난간 옆 어부에게 말 걸기", en: "Speak to the fisherman by the railing." },
          body: { ko: "어부에게 생선을 건네 인연을 맺습니다.", en: "Give the fisherman a fish." },
          reward: { ko: "절박한 어부와의 인연", en: "Bond with Desperate Fisherman" },
        },
        {
          number: 51,
          title: { ko: "고물 마니아 소년", en: "The Junk Boy" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          location: { ko: "후시미 — 데라다야 북측 길", en: "Fushimi — road north of Teradaya" },
          trigger: { ko: "고물을 모으는 아이에게 말 걸기", en: "Approach the junk-collecting child." },
          body: { ko: "인벤토리의 아이템 아무거나 하나를 아이에게 건넵니다.", en: "Hand the boy any inventory item." },
          reward: { ko: "고물 소년과의 인연", en: "Bond with Junk Boy" },
        },
        {
          number: 52,
          title: { ko: "장작 패는 남자", en: "The Woodcutter" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          location: { ko: "후시미 — 남서 구석", en: "Fushimi — southwest corner" },
          trigger: { ko: "남서 구석의 장작꾼에게 말 걸기", en: "Speak to the woodcutter in the SW corner." },
          body: { ko: "장작 패기 미니게임으로 통나무 100개를 쪼개면 완료.", en: "Split 100 logs in the wood-cutting minigame." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 53,
          title: { ko: "방향치 비각", en: "The Frequently Lost Courier" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "후시미 — 남동 구석 지장보살", en: "Fushimi — SE corner by jizo" },
          trigger: { ko: "길 잃은 비각에게 세 차례 말 걸기", en: "Speak to the lost courier three times." },
          body: { ko: "방향치 비각을 세 번 도와주면 인연 성립.", en: "Help the disoriented courier three times to seal the bond." },
          reward: { ko: "방향치 비각과의 인연", en: "Bond with Frequently Lost Courier" },
        },
        {
          number: 54,
          title: { ko: "기다리는 개", en: "The Patient Dog" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "후시미 — 에비스 전당포 뒤 계단", en: "Fushimi — stairs behind Ebisu Pawn" },
          trigger: { ko: "계단의 개에게 다가가기", en: "Approach the dog on the stairs." },
          body: { ko: "음식 아이템을 건넵니다.", en: "Give the dog a food item." },
          reward: { ko: "기다리는 개와의 인연", en: "Bond with Patient Dog" },
        },
        {
          number: 55,
          title: { ko: "꾀죄죄한 고양이", en: "The Filthy Cat" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "후시미 — 가옥선 옆 부두", en: "Fushimi — dock beside the houseboat" },
          trigger: { ko: "더러운 고양이에게 다가가기", en: "Approach the filthy cat." },
          body: { ko: "고양이를 씻겨 줍니다.", en: "Clean up the dirty cat." },
          reward: { ko: "꾀죄죄한 고양이와의 인연", en: "Bond with Filthy Cat" },
        },
        {
          number: 70,
          title: { ko: "선장과 호기심", en: "The Captain and the Curious" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "후시미 — 우마이 우동 북측 식당", en: "Fushimi — restaurant north of Umai Udon" },
          trigger: { ko: "외국인 선장과 합석", en: "Sit with the foreign captain." },
          body: {
            ko: "외국인과의 술자리에서 습격자를 격퇴하고 회고록 수집 시스템이 해금됩니다.",
            en: "Drink with the foreigner, fend off an attacker, and unlock the memoir collection feature.",
          },
          reward: { ko: "회고록 수집 해금 + 선장과의 인연", en: "Memoirs unlocked + bond with the Captain" },
        },
        {
          number: 71,
          title: { ko: "암흑 속의 외교", en: "Diplomacy in Darkness" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "후시미 (야간)", en: "Fushimi — evening" },
          trigger: { ko: "서브 70 클리어 + 회고록 20권 이상", en: "Requires Substory 70 + at least 20 memoirs." },
          body: {
            ko: "사토우의 납치 사실을 알아내고 무쿠로가이에서 구출. 야간 진행이 강제됩니다.",
            en: "Discover Satow's kidnapping and rescue him from Mukurogai. Forces a night-time run.",
          },
          reward: { ko: "서브 38 해금", en: "Unlocks Substory 38" },
        },
        {
          number: 72,
          title: { ko: "지속되는 평화의 갈증", en: "A Lasting Thirst for Peace" },
          chapter: { ko: "챕터 14 (피날레)", en: "Chapter 14 (Finale)" },
          location: { ko: "후시미 → 기온 결전", en: "Fushimi → Gion final fight" },
          trigger: { ko: "회고록 96권 이상 사토우에게 모두 전달 후 발생", en: "After delivering 96+ memoirs to Satow." },
          body: {
            ko: "사토우와 다리 위에서 대치한 뒤 기온에서 나카무라와 결판. 나카무라는 일반 서브 보스보다 체력이 두텁습니다.",
            en: "Confront Satow at the bridge, then settle things with Nakamura in Gion — he's tankier than a normal substory boss.",
          },
          reward: { ko: "최후의 회고록 + 컴플리션", en: "Final memoir + completion credit" },
        },
      ],
    },
    {
      title: { ko: "기온 — 화류계", en: "Gion — Pleasure Quarter" },
      items: [
        {
          number: 56,
          title: { ko: "주운 자가 임자", en: "Finders Weepers" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "기온 — 도리이 동측", en: "Gion — east of the torii gate" },
          trigger: { ko: "라쿠나이 북측 신사에서 아카리와 만난 뒤 분홍 일기 발견", en: "After meeting Akari at the north Rakunai shrine, find the pink diary." },
          body: {
            ko: "주운 일기를 여러 차례 정독한 뒤 주인에게 어떤 조언을 해 줄지 세 번 선택. 일기 주인이 행복해지는 길로 안내.",
            en: "Read the found diary, then give the owner three pieces of advice toward a happy ending.",
          },
          choices: [
            { prompt: { ko: "「첫 조언」", en: "First piece of advice" }, correct: { ko: "「사랑은 모두 소중하다」", en: "'All love is precious'" } },
            { prompt: { ko: "「두 번째 조언」", en: "Second" }, correct: { ko: "「우선 그를 알아 가라」", en: "'Try getting to know him'" } },
            { prompt: { ko: "「세 번째 조언」", en: "Third" }, correct: { ko: "「솔직히 표현하는 편이 낫다」", en: "'Better to be simple and direct'" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 57,
          title: { ko: "보드랍고 매끄럽게", en: "Soft and Supple" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "기온 — 가마터 남측", en: "Gion — south of the palanquin stand" },
          trigger: { ko: "가마터 남측에서 발생", en: "South of the palanquin." },
          body: { ko: "유곽 비용을 거부한 손님과 호객꾼 일당 세 명을 제압.", en: "Reject a brothel shake-down and beat three thugs." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 58,
          title: { ko: "혁명의 요리사", en: "The Revolutionary Chef" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "기온 — 야마부키 맞은편", en: "Gion — across from Yamabuki" },
          trigger: { ko: "요리사 지망 남자에게 말 걸기", en: "Talk to the aspiring chef." },
          body: { ko: "료마가 직접 만든 요리를 시식시킵니다.", en: "Feed him a homemade dish." },
          reward: { ko: "혁명의 요리사와의 인연", en: "Bond with Revolutionary Chef" },
        },
        {
          number: 59,
          title: { ko: "요염한 마담", en: "The Sexy Madam" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "기온 — 키친 아오바 북측 나무 옆", en: "Gion — north of Kitchen Aoba by the tree" },
          trigger: { ko: "여인에게 말 걸기", en: "Speak to the madam." },
          body: { ko: "오이를 건네 주면 인연 성립.", en: "Offer her a cucumber." },
          reward: { ko: "요염한 마담과의 인연", en: "Bond with Sexy Madam" },
        },
      ],
    },
    {
      title: { ko: "미부 / 광역 — 신선조 거점 주변", en: "Mibu & Crossover — Around the Shinsengumi" },
      items: [
        {
          number: 60,
          title: { ko: "중요한 건 내면", en: "It's What's on the Inside" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "미부 — 오타케 찻집", en: "Mibu — Otake Tea Parlor" },
          trigger: { ko: "오타케 찻집 부근에서 자동 발생", en: "Auto-cutscene at Otake Tea Parlor." },
          body: {
            ko: "미모로 평가받지 못한 처녀 「스즈」를 외형이 아닌 본심으로 평가해야 합니다. 라쿠나이 강변 컷신과 미부 신사 전투를 거쳐 마무리.",
            en: "Stand up for Suzu — judge her by character, not looks. Plays out across a Rakunai riverside scene and a fight at Mibu shrine.",
          },
          choices: [
            { prompt: { ko: "「스즈를 어떻게 생각하는가?」", en: "'What about Suzu?'" }, correct: { ko: "「스즈를 믿으라」", en: "'Have faith in Suzu'" } },
          ],
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 61,
          title: { ko: "다시 피는 벚꽃", en: "Hope Blossoms Again" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "미부 — 신선조 둔소 좌측 길", en: "Mibu — path left of Shinsengumi Barracks" },
          trigger: { ko: "괴롭힘당하는 부부 발견", en: "Witness a couple being harassed." },
          body: { ko: "행패를 부리는 남자를 격퇴하고 인근 가옥에서 벚꽃나무를 확인.", en: "Beat the harasser, then find the cherry tree at the couple's home." },
          reward: { ko: "서브 64 해금", en: "Unlocks Substory 64" },
        },
        {
          number: 62,
          title: { ko: "야망 가득한 무장", en: "A Warlord's Ambition" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "미부 — 자택", en: "Mibu — your house" },
          trigger: { ko: "자택에서 요리 10회 이상 진행 후 발생", en: "After 10 cooking sessions at home." },
          body: { ko: "특정 생선 굽기 기법을 활용한 요리 한 접시를 완성.", en: "Cook a single dish using the fish-grilling technique." },
          reward: { ko: "덕 보상 + 요리 레시피", en: "Virtue + recipe" },
        },
        {
          number: 63,
          title: { ko: "곰이 나타났다", en: "The Boy Who Cried Bear" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "미부 — 서측 신사", en: "Mibu — shrine, west side" },
          trigger: { ko: "서브 60 클리어 후 발생", en: "After Substory 60." },
          body: { ko: "사실이었던 곰 출몰. 보스급 곰 1마리와 전투.", en: "Turns out the bear is real — fight the boss-class beast." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 64,
          title: { ko: "엄마 료마", en: "Mama Ryoma" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "미부 — 아이들 가마터 부근", en: "Mibu — near the children's palanquin" },
          trigger: { ko: "서브 61 클리어 후 발생", en: "After Substory 61." },
          body: { ko: "아이들과 소꿉놀이를 한 뒤 난입한 남자를 격퇴.", en: "Play house with the kids, then thrash the intruder." },
          reward: { ko: "덕 보상", en: "Virtue" },
        },
        {
          number: 65,
          title: { ko: "기억을 잃은 사나이", en: "The Amnesiac" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "기요미즈 사찰로 가는 길(라쿠가이 남교 동측)", en: "Path to Kiyomizu Temple — east of the south bridge from Rakugai" },
          trigger: { ko: "쓰러진 남자 옆에서 발생", en: "Find the unconscious man on the path." },
          body: { ko: "회복 아이템을 건네 의식을 되찾게 합니다.", en: "Give a healing item to wake him." },
          reward: { ko: "기억을 잃은 사나이와의 인연", en: "Bond with Amnesiac" },
        },
        {
          number: 66,
          title: { ko: "채소를 사랑하는 소년", en: "The Boy Who Loves Veggies" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "미부 — 신선조 본부 부근", en: "Mibu — Shinsengumi HQ area" },
          trigger: { ko: "본부 부근에서 자동 컷신", en: "Auto-scene by the Shinsengumi HQ." },
          body: { ko: "우는 소년에게 채소를 건네 줍니다.", en: "Hand the crying boy a vegetable." },
          reward: { ko: "채소 사랑 소년과의 인연", en: "Bond with Veggie-Loving Boy" },
        },
      ],
    },
  ],
};
