import type { SubstoriesData } from "./types";

export const yakuza3Substories: SubstoriesData = {
  appId: 1088710,
  summary: {
    ko: "PS3판 리마스터에 서양판 미수록 콘텐츠가 복원되어 총 119개의 서브 스토리. 카무로쵸(도쿄)와 류큐 거리(오키나와) 양쪽에서 발생하며, 챕터별로 잠금 해제됩니다. 미완료 항목은 클리어 후 프리미엄 어드벤처에서 마저 진행 가능. 서브 스토리 컴플리션이 「가장 부지런한 키류」 트로피와 직결됩니다.",
    en: "119 substories total — the Remaster restored the content cut from the original Western release. Substories run in Kamurocho (Tokyo) and Downtown Ryukyu (Okinawa) and gate by chapter. Anything missed during the main story can be cleaned up in Premium Adventure. Clearing all 119 unlocks the Substory Completionist trophy line.",
  },
  source: { label: "GameFAQs / Yakuza Wiki — Yakuza 3 Remastered Substories (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/239455-yakuza-3-remastered/faqs/77723/substories" },
  groups: [
    {
      title: { ko: "챕터 3 — 류큐 첫 자유 이동", en: "Chapter 3 — Power Struggle (Ryukyu opens)" },
      items: [
        {
          number: 27,
          title: { ko: "허슬러의 도전", en: "The Hustler's Challenge" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "아쿠아 스카이 풀에서 나인볼 3승 후 콧수염 신사가 도전", en: "Win three Nine-Ball games at Aqua Sky; the mustached gentleman challenges you." },
        },
        {
          number: 55,
          title: { ko: "도쿄에 가고 싶어 1", en: "I Want to Go to Tokyo 1" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "에비스 전당포 북쪽 여성에게 말 걸기", en: "Talk to the woman north of Ebisu Pawn." },
        },
        {
          number: 66,
          title: { ko: "벼랑 끝 사나이", en: "Walking the Plank" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "서쪽 다리에서 자살하려는 뚱뚱한 남자 말리기", en: "Stop the chubby man jumping off the west bridge." },
        },
        {
          number: 82,
          title: { ko: "잃어버린 열쇠", en: "A Lost Key" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "류큐 거리에서 열쇠를 잃어버린 여성 돕기", en: "Help the woman who lost her key on Ryukyu St." },
        },
        {
          number: 87,
          title: { ko: "봉선화가 피거든", en: "As the Rose Balsam Blooms" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "류큐 거리에서 봉선화 꽃을 들고 있는 노부인에게 말 걸기", en: "Talk to the elderly woman with rose balsam flowers on Ryukyu St." },
        },
        {
          number: 93,
          title: { ko: "배달 레이스", en: "Deliver Race" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "와라바 오키나와 소바 노점에서 3번째 방문 시 발생 — 5분 내 3건 배달", en: "Visit Waraba soba stand a third time: deliver three orders within 5 minutes." },
        },
        {
          number: 103,
          title: { ko: "강아지 훈련: 가져와", en: "New Dog, New Tricks: Fetch" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「돌아」 후 「가져와」 가르치기", en: "After 'Turn Around': teach 'Fetch'." },
        },
        {
          number: 109,
          title: { ko: "정상을 향해!", en: "Straight to the Top!" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "류큐 호스트 클럽에서 호스트 출세 의뢰 수락", en: "Take the host-club climbing job at the Ryukyu host club." },
        },
      ],
    },
    {
      title: { ko: "챕터 4 — 류큐 (오키나와)", en: "Chapter 4 — The Man in the Sketch (Ryukyu)" },
      items: [
        {
          number: 5,
          title: { ko: "한발 빠른 신혼여행", en: "Early Honeymoon" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "4장 후반(슈트 + 하루카 동반 + 낮): 해변에서 아키모토·미즈키 조우", en: "Late Ch.4 (suit + Haruka + daytime): meet Akimoto and Mizuki on the beach." },
          body: { ko: "4장 후반, 슈트 차림 + 하루카 동반 + 낮 시간대에만 발동. 해변에서 옛 시리즈 등장 인물 아키모토·미즈키 조우 → 공설시장 푸드코트 → 스톤 마켓(보석상) → 해변으로 복귀 → 코지와 대화 후 부부 점검. 마지막 대화에서 정답 5선택지를 모두 골라야 최고 보상.", en: "Late Ch.4, suit + Haruka + daytime only. Meet Akimoto and Mizuki on the beach, follow them to the food court, then Stone Market, then back to the beach via Koji." },
          choices: [
            { prompt: { ko: "왜 그녀가 노부인을 도왔다고 생각해?", en: "Why did she help the old lady?" }, correct: { ko: "그녀가 돕고 싶었던 거겠지", en: "She probably wanted to help the old lady." } },
            { prompt: { ko: "왜 어머니의 부탁을 거절 못 했을까?", en: "Why couldn't she say no to her mom?" }, correct: { ko: "어머니에게 거절을 못 하는 사람일 거야", en: "She probably couldn't say no to her mom." } },
            { prompt: { ko: "그게 어떻다고 보나?", en: "What do you think of that?" }, correct: { ko: "그건 훌륭한 일이야", en: "That's honorable of her." } },
            { prompt: { ko: "결혼하면 어떨 거 같아?", en: "What kind of wife will she make?" }, correct: { ko: "좋은 아내가 될 거야", en: "She's going to be a great wife." } },
            { prompt: { ko: "아이는?", en: "And kids?" }, correct: { ko: "너와 아이를 갖고 싶어 할 거야", en: "She must really want kids with you." } },
          ],
          reward: { ko: "대량 경험치 + 「이젠 정말 끝」 잠금 해제", en: "Big EXP and unlocks 'They Never Learn' in Ch.12" },
        },
        {
          number: 11,
          title: { ko: "류큐의 7가지 불가사의 1", en: "The Seven Mysteries of Ryukyu 1" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "야간 류큐 거리 M 스토어 앞 여고생 3인조에게 말 걸기", en: "At night: talk to the three schoolgirls outside M Store on Ryukyu St." },
        },
        {
          number: 12,
          title: { ko: "류큐의 7가지 불가사의 2", en: "The Seven Mysteries of Ryukyu 2" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "1편 클리어 후 블루씰 아이스크림 앞 여고생들에게 말 걸기", en: "After Pt.1: schoolgirls outside Blue Seal Ice Cream." },
        },
        {
          number: 13,
          title: { ko: "류큐의 7가지 불가사의 3", en: "The Seven Mysteries of Ryukyu 3" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "2편 클리어 후 키타류 다리 위 여고생들에게 말 걸기", en: "After Pt.2: schoolgirls on the Kitaryu bridge." },
        },
        {
          number: 14,
          title: { ko: "류큐의 7가지 불가사의 4", en: "The Seven Mysteries of Ryukyu 4" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "3편 클리어 후 공설시장 남서쪽 여고생들에게 말 걸기", en: "After Pt.3: southwest of the North Public Market." },
          body: { ko: "공설시장 남서쪽에서 여고생들이 「전설의 고야 주스」 이야기 → 한 소년의 어머니를 위해 재료 구함. 노점 아주머니에게서 재료 구매. 일반 보상은 고야·쿠루자타(흑설탕)·바사나이(바나나)·두구와이(알로에)·레몬 = 「스태미난 로얄」. 최고 보상은 고야·쿠루자타·두구와이 + 「섬 바나나」 + 시쿠와사 = 「스태미난 스파크」.", en: "Best outcome: buy bitter melon, brown sugar (kuruzata), aloe (dugwai), island bananas, and shikwasa from the market vendor — not regular bananas/lemon." },
          choices: [
            { prompt: { ko: "재료 선택", en: "Ingredients" }, correct: { ko: "고야·흑설탕·알로에·섬 바나나·시쿠와사", en: "Bitter melon, brown sugar, aloe, island bananas, shikwasa" }, note: { ko: "기본 5종(레몬·일반 바나나)은 「스태미난 로얄」, 섬 바나나·시쿠와사 조합은 「스태미난 스파크」", en: "Standard recipe yields Staminan Royale; the island-fruit recipe yields the better Staminan Spark" } },
          ],
          reward: { ko: "스태미난 스파크 (최고 보상)", en: "Staminan Spark (best outcome)" },
        },
        {
          number: 15,
          title: { ko: "류큐의 7가지 불가사의 5", en: "The Seven Mysteries of Ryukyu 5" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "4편 클리어 후 마에다 약국 북쪽에서 만나기", en: "After Pt.4: north of Maeda Drugs." },
        },
        {
          number: 16,
          title: { ko: "류큐의 7가지 불가사의 6", en: "The Seven Mysteries of Ryukyu 6" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "5편 클리어 후 공설시장 입구에서 만나기", en: "After Pt.5: in front of the Public Market entrance." },
        },
        {
          number: 20,
          title: { ko: "병에 담긴 사랑", en: "Bottled Love" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「한발 빠른 신혼여행」 + 맥의 진수 안내 후 서쪽 해변에서 병 발견", en: "After 'Early Honeymoon' and Mack's Revelations talk: find a bottle on the west beach." },
          body: { ko: "「한발 빠른 신혼여행」 + 맥의 진수 안내 후, 키류 단독으로 해변 서쪽 → 표류병 발견 → 하루카 합류·편지 낭독 → 카리유시 아케이드 남단 골목 → 다음 단서 따라가며 「이젠 정말 끝」으로 이어지는 복선 형성.", en: "Triggers only after 'Early Honeymoon' AND meeting Mack about Revelations. Find a washed-up bottle on the west beach alone; Haruka joins to read the letter, then continue to Kariyushi Arcade." },
          reward: { ko: "이벤트 시네마틱 + 컴플리션 카운트", en: "Event cinematic + completion credit" },
        },
        {
          number: 24,
          title: { ko: "시사 협박", en: "Shisa Shakedown" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "공설시장 근처에서 시사를 부수려는 양아치들 막기", en: "Stop the punks smashing a shisa near the Public Market." },
        },
        {
          number: 31,
          title: { ko: "마음의 패스트푸드", en: "Fast Food for the Heart" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "스마일 버거 류큐점 앞 부끄러워하는 청년에게 말 걸기", en: "Talk to the bashful young man outside Smile Burger Ryukyu." },
        },
        {
          number: 32,
          title: { ko: "넘사벽", en: "Out of His League" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「마음의 패스트푸드」 후속 — 청년의 데이트 코칭", en: "Follow-up to 'Fast Food for the Heart': coach his date." },
        },
        {
          number: 33,
          title: { ko: "고아원을 노린 강도", en: "Robbing the Orphanage" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「넘사벽」 클리어 후 모리닝글로리 고아원에서 사건 발생", en: "After 'Out of His League': incident at Morning Glory Orphanage." },
        },
        {
          number: 38,
          title: { ko: "모리닝글로리 숨바꼭질", en: "Morning Glory Hide-and-Seek" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "모리닝글로리 고아원에서 아이들과 숨바꼭질", en: "Play hide-and-seek with the kids at Morning Glory." },
        },
        {
          number: 42,
          title: { ko: "유혹", en: "Temptation" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "류큐 거리의 작부에게 말 걸어 삥쟁이 함정 회피", en: "Talk to the streetwalker on Ryukyu St. and dodge the shakedown." },
        },
        {
          number: 43,
          title: { ko: "도미 강탈", en: "Sea Bream Strongarm" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "공설시장 어물전에서 강탈범과 대치", en: "Confront the strongarm at the Public Market fish stall." },
        },
        {
          number: 44,
          title: { ko: "가방 날치기 추적", en: "Bag That Snatcher" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "류큐 거리에서 가방 날치기 추격", en: "Chase a purse snatcher on Ryukyu Blvd." },
        },
        {
          number: 46,
          title: { ko: "미키오의 폭식 도전", en: "Mikio's Munchathon" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "류도 사무소 미키오에게 말 걸기 → 와라바 소바 폭식 시합", en: "Talk to Mikio at the Ryudo office for a Waraba soba eating contest." },
        },
        {
          number: 52,
          title: { ko: "비밀 거래", en: "Under the Table" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "류큐 거리 뒷골목에서 수상한 거래 목격", en: "Witness a shady back-alley deal on Ryukyu." },
        },
        {
          number: 60,
          title: { ko: "잃어버린 물건", en: "Lost and Found" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "에비스 전당포 인근에서 분실물 의뢰 받기", en: "Take a lost-and-found request near Ebisu Pawn." },
        },
        {
          number: 61,
          title: { ko: "증류 장인의 보물", en: "The Distiller's Treasure" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "공설시장 남쪽 노포에서 노인에게 말 걸기", en: "Talk to the old distiller south of the Public Market." },
        },
        {
          number: 67,
          title: { ko: "물고기 떼 부르기", en: "Chumming the Waters" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "공설시장 어부의 미끼 운반 의뢰", en: "Help the Public Market fisherman ferry chum." },
        },
        {
          number: 69,
          title: { ko: "사기꾼의 위협", en: "The Con Menace" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "강가에서 「부딪치는 남자들」 사기꾼들과 부딪치기", en: "Bump into the 'bump-and-extort' con men by the river." },
        },
        {
          number: 70,
          title: { ko: "사기꾼 전쟁", en: "The Con Wars" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「사기꾼의 위협」 후 다시 부딪치기", en: "After 'The Con Menace': bump them again." },
        },
        {
          number: 86,
          title: { ko: "녹아내리는 마음", en: "A Melting Heart" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "블루씰 아이스크림 가게에서 여성에게 말 걸기", en: "Talk to the woman at the Blue Seal ice cream shop." },
        },
        {
          number: 88,
          title: { ko: "사장의 골프", en: "Presidential Golfer" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "골프장 클럽하우스에서 사장과 시합", en: "Meet and play against the President at the golf clubhouse." },
        },
        {
          number: 101,
          title: { ko: "강아지 훈련: 앉아", en: "New Dog, New Tricks: Sit" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "모리닝글로리 고아원에서 마메에게 「앉아」 가르치기", en: "Teach 'Sit' to the dog Mame at Morning Glory." },
        },
        {
          number: 102,
          title: { ko: "강아지 훈련: 돌아", en: "New Dog, New Tricks: Turn Around" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「앉아」 후 「돌아」 가르치기", en: "After 'Sit': teach 'Turn Around'." },
        },
        {
          number: 104,
          title: { ko: "영어 공부 1", en: "Let's Learn English 1" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "에비스 전당포 북쪽 영어 공부 중인 여성에게 말 걸기", en: "Talk to the English-studying woman north of Ebisu Pawn." },
        },
        {
          number: 105,
          title: { ko: "영어 공부 2", en: "Let's Learn English 2" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「영어 공부 1」 후 다시 말 걸기", en: "After Lesson 1: speak to her again." },
        },
      ],
    },
    {
      title: { ko: "챕터 5 — 카무로쵸 복귀", en: "Chapter 5 — The Curtain Rises (Kamurocho)" },
      items: [
        {
          number: 18,
          title: { ko: "인스턴트 라멘은 하루아침에 안 된다", en: "Instant Ramen Takes Time" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "큐슈 No.1 별 라멘에 입장해 주인과 손님의 다툼에 개입 (10장에서 완결)", en: "Enter Kyushu No. 1 Star ramen and intervene (concludes in Ch.10)." },
          body: { ko: "큐슈 No.1 별 라멘에서 주인과 우에다의 다툼 청취 → 우에다에게 인스턴트 라멘 시식 → \"격려한다\" 선택 → 밀레니엄 타워에서 양아치 격파 → 큐슈 No.1 별로 복귀, 우에다가 오키나와로 출발 → 10장 에비스 전당포 남쪽에서 우에다에게 와라바 안내 → 와라바에서 대화 → 카무로쵸 큐슈 No.1 별에서 시식.", en: "Kyushu No. 1 Star → talk to owner and to Ueda outside → eat his instant ramen and pick 'Encourage Him' → Millennium Tower brawl → back to Kyushu No. 1 Star, Ueda leaves for Okinawa → in Ch.10 find him south of Ebisu Pawn, direct him to Waraba, then return to Kamurocho." },
          choices: [
            { prompt: { ko: "우에다의 시제품 라멘", en: "Ueda's prototype ramen" }, correct: { ko: "「격려한다」", en: "'Encourage Him'" } },
          ],
          reward: { ko: "「큐슈 No.1 별 라멘 샘플」", en: "Kyushu No. 1 Star Ramen Sample" },
        },
        {
          number: 22,
          title: { ko: "초벌 스윙", en: "Rough Draft" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "배팅 센터 하드 코스 1100점 이상 → 입구의 정체 모를 노인", en: "Score 1100+ on Hard Course at the Batting Center; meet the Mysterious Old Man." },
        },
        {
          number: 26,
          title: { ko: "수금원 키류", en: "Kiryu the Collector" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "극장 광장에서 빚쟁이를 쫓는 수금원에게 말 걸기 (※「삥쟁이」 의미 아님)", en: "Speak to the debt collector chasing his client in Theater Square." },
        },
        {
          number: 28,
          title: { ko: "내 얘기 하는 거야?", en: "Talking About Me?" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "Love in Heart 1회 방문 후, 밴텀에 혼자 앉은 여성에게 말 걸기", en: "Visit Love in Heart, then talk to the lone woman in Bantam." },
        },
        {
          number: 29,
          title: { ko: "만화광", en: "Manga Mania" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "포포 매장 입장 시 타이치의 전화 → 카페 알프스로 (10장에서 완결)", en: "Enter any Poppo for Taichi's call (finishes in Ch.10)." },
        },
        {
          number: 35,
          title: { ko: "Mr. 때려봐 다시", en: "Mr. Try and Hit Me Again" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "야간 시치후쿠 주차장 동쪽 도전자에게 말 걸기", en: "At night, talk to the challenger east of Shichifuku Parking." },
        },
        {
          number: 39,
          title: { ko: "한 노인의 추억", en: "The Old Man's Memories" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "텐카이치 거리에서 멍하니 서 있는 노인에게 말 걸기", en: "Talk to the absent-minded old man on Tenkaichi St." },
        },
        {
          number: 48,
          title: { ko: "전채", en: "Hor D'oeuvres" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "쇼와 거리 라멘 가게 앞 무전취식범 추격", en: "Chase the dine-and-dasher from a Showa St. ramen stall." },
        },
        {
          number: 53,
          title: { ko: "사랑의 명중", en: "Bullseye of Love" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "Love in Heart에서 다트로 호감 얻기", en: "At Love in Heart: win her over at darts." },
        },
        {
          number: 54,
          title: { ko: "성난 폭주족", en: "Riled Riders" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "쇼와 거리에서 폭주족과 시비 붙기", en: "Tangle with bikers on Showa St." },
        },
        {
          number: 56,
          title: { ko: "도쿄에 가고 싶어 2", en: "I Want to Go to Tokyo 2" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "1편 후 카무로쵸에서 그녀와 재회", en: "After Pt.1: meet her again in Kamurocho." },
        },
        {
          number: 59,
          title: { ko: "과거의 망령", en: "Ghosts from the Past" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「잘못 짖었다」 후 텐카이치 거리에서 폭탄 사건 관련자 등장", en: "After 'Barking up the Wrong Tree': the bombing-incident father appears on Tenkaichi." },
        },
        {
          number: 62,
          title: { ko: "용궁 귀환", en: "Return to the Dragon Palace" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "텐카이치 거리에서 우라시마 같은 노인에게 말 걸기", en: "Talk to the Urashima-like old man on Tenkaichi St." },
        },
        {
          number: 63,
          title: { ko: "잘못 걸린 전화", en: "Missed Caller" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "공중전화 부스에서 울리는 전화 받기", en: "Pick up a ringing Kamurocho payphone." },
        },
        {
          number: 74,
          title: { ko: "땡처리 세일", en: "Bargain Sale" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "M 스토어 앞 세일 호객꾼에게 말 걸기", en: "Talk to the bargain sale tout at an M Store." },
        },
        {
          number: 79,
          title: { ko: "라자냐 대탈주", en: "Lasagna at Large" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "이탈리아 레스토랑 앞 셰프에게 말 걸기 → 라자냐 배달", en: "Talk to the chef outside an Italian restaurant; deliver lasagna." },
        },
        {
          number: 83,
          title: { ko: "데스 볼링", en: "Death Bowler" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "마하 볼링장에서 도전자와 대결", en: "Take on the challenger at Mach Bowl." },
        },
        {
          number: 84,
          title: { ko: "지난달의 챔피언", en: "Last Month's Winner" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "다트 가게에서 지난달 챔피언과 대결", en: "Face last month's darts champion." },
        },
        {
          number: 89,
          title: { ko: "정수기", en: "Water Purifiers" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "뉴 세레나 안에서 정수기 판매원과 대치", en: "Confront the water purifier salesmen in New Serena." },
        },
        {
          number: 94,
          title: { ko: "하이테크 훔쳐보기", en: "High-Tech Peeping Tom" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "핑크 거리에서 도촬 카메라 소문 듣고 범인 추적", en: "Hear about the high-tech peeper on Pink St." },
        },
        {
          number: 95,
          title: { ko: "경비원 모집", en: "Bouncers Needed" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "스타더스트에서 카즈키와 경비원 채용 상담", en: "Talk to Kazuki at Stardust about hiring bouncers." },
        },
        {
          number: 110,
          title: { ko: "배신당한 레이미", en: "Reimi Betrayed" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "SHINE 호스티스 레이미와 호스티스 메이커 풀 코스 진행", en: "Run the Hostess Maker storyline for Shine's Reimi." },
        },
        {
          number: 111,
          title: { ko: "곤경에 빠진 린", en: "Rin in Trouble" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "SHINE 호스티스 린의 사건 해결", en: "Resolve Shine hostess Rin's trouble." },
        },
        {
          number: 112,
          title: { ko: "카나와 그녀의 강아지", en: "Kana and Her Dog" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "SHINE 호스티스 카나의 강아지 사건", en: "Help Shine hostess Kana with her dog." },
        },
        {
          number: 113,
          title: { ko: "란코의 고민", en: "Ranko's Worry" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "SHINE 호스티스 란코의 고민 듣고 해결", en: "Address Shine hostess Ranko's worry." },
        },
        {
          number: 114,
          title: { ko: "미유와 아들", en: "Miyu and Her Son" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "주얼 호스티스 미유와 그 아들 이야기", en: "Jewel hostess Miyu's son storyline." },
        },
        {
          number: 115,
          title: { ko: "시오리의 스토커", en: "Shiori's Stalker" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "주얼 호스티스 시오리의 스토커 해결", en: "Solve Jewel hostess Shiori's stalker." },
        },
        {
          number: 116,
          title: { ko: "유이와 아담", en: "Yui and Adam" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "주얼 호스티스 유이와 외국인 친구 아담의 이야기", en: "Jewel hostess Yui and her foreigner friend Adam." },
        },
        {
          number: 117,
          title: { ko: "미카의 가족", en: "Mika's Family" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "플로리스 호스티스 미카의 가족 사정", en: "Flawless hostess Mika's family matter." },
        },
        {
          number: 118,
          title: { ko: "나오와 사기꾼들", en: "Nao and the Crooks" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "플로리스 호스티스 나오를 노리는 사기꾼 처리", en: "Drive off the crooks targeting Flawless hostess Nao." },
        },
        {
          number: 119,
          title: { ko: "위기의 사야", en: "Saya in Peril" },
          chapter: { ko: "챕터 5", en: "Chapter 5" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "플로리스 호스티스 사야의 위기 해결", en: "Save Flawless hostess Saya." },
        },
      ],
    },
    {
      title: { ko: "챕터 6 — 리키야 동반", en: "Chapter 6 — Gameplan (Rikiya)" },
      items: [
        {
          number: 3,
          title: { ko: "고향의 그녀", en: "Hometown Girl" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "리키야 동반 + 데이트와 대화 후 그를 클럽 ASIA로 안내", en: "With Rikiya after meeting Date: escort him to Club Asia." },
          body: { ko: "6장에서만 가능. 리키야 동반, 데이트와 대화 전에 리키야와 클럽 ASIA로 → 댄서가 리키야의 옛 친구의 동생으로 밝혀짐 → 스토커 격퇴, 배팅 센터·밀레니엄 타워 앞·나카미치 골목 등 마커 순회.", en: "Chapter 6 only. Take Rikiya to Club Asia before progressing the story. The dancer turns out to be related to a girl Rikiya knew. Run between markers (Batting Center, Millennium Tower, Nakamichi Alley) defeating stalkers." },
          reward: { ko: "이벤트 시네마틱 + 경험치", en: "Event cinematic + heavy EXP" },
        },
        {
          number: 4,
          title: { ko: "용두점정", en: "Dotting the Eye" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "리키야 동반 시 핑크 거리 디바인 드래곤 문신소 살피기", en: "With Rikiya: examine Divine Dragon tattoo parlor in Pink Alley." },
          body: { ko: "6장 리키야 동반 시에만 가능. 핑크 거리 디바인 드래곤 문신소(키류의 용을 새긴 곳)를 「조사」 → 우타보리에게 리키야의 미완성 살무사 마무리를 부탁 → 거절 후 바깥 골목에서 패거리 정리.", en: "Chapter 6 with Rikiya only. Examine Divine Dragon tattoo parlor in Pink Alley — Utabori refuses to finish Rikiya's viper, then a brawl in the alley settles it." },
          prereq: { ko: "리키야 동반 (6장 한정, 놓치면 프리미엄 어드벤처 한정)", en: "Must have Rikiya in Chapter 6 — otherwise only doable in Premium Adventure" },
          reward: { ko: "이벤트 시네마틱 + 컴플리션 카운트", en: "Event cinematic + completion credit" },
        },
        {
          number: 7,
          title: { ko: "은막의 용", en: "Silver Screen Dragon" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "극장 광장 동쪽 영화 촬영팀에게 말 걸기", en: "East side of Theater Square: talk to the film crew." },
          body: { ko: "극장 광장 동쪽 영화 촬영팀이 부상자 대신 키류를 캐스팅. 대사는 적힌 대로 읽지 말고 \"제멋대로\" 진행해야 200,000엔과 사쿠라 스톰 검 획득. 적은 하나이(짧은 머리) → 나루미(긴 머리) → 마츠카제(수염) → 오츠키(대머리) 순서로 격파. 히트 액션은 「벽치기」 → 「코마키 검술」 → 「벽돌 깨기의 정수」(다루마 사용). 야마시로 전에서 체력을 빨강까지 떨어뜨린 뒤 격파.", en: "Save first. Theater Square film crew casts Kiryu as the hero. Beat enemies in order Hanai → Narumi → Matsukaze → Otsuki, use Heat Actions 'Wall Crush', 'Komaki Sword Slash', 'Essence of Brick Breaking' (with the daruma), and let Yamashiro drop your HP to red before defeating him for max reward." },
          choices: [
            { prompt: { ko: "첫 번째 대사", en: "First line" }, correct: { ko: "「아버지의 원수, 받겠다」", en: "'You killed my father, and I want payback.'" } },
            { prompt: { ko: "두 번째 대사", en: "Second line" }, correct: { ko: "「사내답게 끝까지 싸워라!」", en: "'Fight me to the death like a man!'" } },
            { prompt: { ko: "세 번째 대사", en: "Third line" }, correct: { ko: "「지옥에서 아버지께 사죄해라!」", en: "'I'll make you apologize to my father... in hell!'" } },
            { prompt: { ko: "마지막 대사", en: "Final line" }, correct: { ko: "「돈은 필요 없다. 내가 원하는 건 정의다」", en: "'Keep your money. I want justice.'" } },
          ],
          reward: { ko: "200,000엔 + 사쿠라 스톰(일도)", en: "200,000 yen + Sakura Storm sword" },
        },
        {
          number: 8,
          title: { ko: "위로하는 야쿠자", en: "The Comforting Yakuza" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「Mr. 때려봐 도망」 클리어 후 리키야 미동반: 시치후쿠 주차장 남쪽에서 여성을 괴롭히는 남자 제압", en: "Clear 'Mr. Try and Flee Me' and ditch Rikiya: confront the harasser south of Shichifuku Parking." },
          body: { ko: "「Mr. 때려봐 도망」 + 칸다전 클리어 + 리키야 미동반 상태에서만 가능. 시치후쿠 남쪽에서 여성을 괴롭히는 남자를 위협 → 여성을 호텔로 안내 → 100,000엔 합의 거절 후 격투 → 바로 돌아가 한 명 더 처리.", en: "Clear 'Mr. Try and Flee Me' and Kanda, ditch Rikiya. Confront the harasser south of Shichifuku, then escort her — refuse the 100,000-yen hush money and beat him down." },
          choices: [
            { prompt: { ko: "괴롭히는 남자에게", en: "To the harasser" }, correct: { ko: "「내가 손봐주기 전에 꺼져」", en: "'Leave her alone before I make you'" } },
            { prompt: { ko: "호텔에 도착한 남자에게", en: "To the man at the hotel" }, correct: { ko: "「여자에게 그게 무슨 말투냐」", en: "'Is that any way to speak to her?'" } },
            { prompt: { ko: "100,000엔 합의 제안", en: "100,000-yen hush money" }, correct: { ko: "거절한다", en: "Refuse" }, note: { ko: "합의 시 보상 대폭 감소", en: "Accepting tanks the reward" } },
          ],
          reward: { ko: "경험치 + 컴플리션 카운트", en: "EXP + completion credit" },
        },
        {
          number: 10,
          title: { ko: "또 하나의 스타더스트", en: "Another Stardust" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「할머니의 사랑을 위해」 클리어 후 스타더스트 입장", en: "Clear 'Anything for Grandma's Love'; enter Stardust." },
          body: { ko: "「할머니의 사랑을 위해」 클리어 후 스타더스트 입장 → 카즈키와 손님의 다툼 청취 → 유야와 대화 → 외출 후 유야의 전화로 밴텀에서 에이지 만남 → 스타더스트 → 카페 알프스에서 카즈키 만남 → 공원 No.3 동쪽 골목에서 에이지 격파 → 밀레니엄 타워에서 잔당 격파.", en: "Clear 'Anything for Grandma's Love'. Enter Stardust → Yuya call → meet Yuya + Eiji at Bantam → back to Stardust → Café Alps → Public Park No. 3 alley to beat Eiji → Millennium Tower for the brawl." },
          reward: { ko: "100,000엔 + 컴플리션 카운트", en: "100,000 yen + completion credit" },
        },
        {
          number: 23,
          title: { ko: "극장 광장의 이유진", en: "Il in Theater Square" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「정수기」 클리어 후 극장 광장 동쪽 행복고트 부인들에게 말 걸기", en: "After 'Water Purifiers': happi-coat ladies east of Theater Square." },
        },
        {
          number: 25,
          title: { ko: "끝없는 스토커", en: "Nonstop Stalkers" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "주얼 앞 젊은 여성에게 말 걸기", en: "Talk to the young woman in front of Jewel." },
        },
        {
          number: 30,
          title: { ko: "신참의 고민", en: "Rookie's Dilemma" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "쇼와 거리 호스트 클럽 앞 호객 청년에게 말 걸기", en: "Talk to the rookie host scout on Showa St." },
        },
        {
          number: 36,
          title: { ko: "Mr. 때려봐 도망", en: "Mr. Try and Flee Me" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「Mr. 때려봐 다시」 후 시치후쿠 주차장 다음 도전자", en: "After 'Hit Me Again': next challenger at Shichifuku Parking." },
        },
        {
          number: 40,
          title: { ko: "수상한 부부", en: "Suspicious Spouses" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "쇼와 거리에서 부부 다툼에 휘말리기", en: "Step into a couple's quarrel on Showa St." },
        },
        {
          number: 41,
          title: { ko: "도둑을 잡아라!", en: "Catch Those Shoplifters!" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "포포 매장 앞에서 도둑 신고 받기", en: "Get flagged outside a Poppo about shoplifters." },
        },
        {
          number: 49,
          title: { ko: "오르되브르", en: "Appetizer" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「전채」 후 또 다른 무전취식범 추격", en: "After 'Hor D'oeuvres': chase another dasher." },
        },
        {
          number: 75,
          title: { ko: "돌아온 사나이", en: "The Returnee" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "쇼와 거리에서 돌아온 옛 야쿠자에게 말 걸기", en: "Talk to the returning old yakuza on Showa St." },
        },
        {
          number: 78,
          title: { ko: "할머니의 사랑을 위해", en: "Anything for Grandma's Love" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "공원 노점에서 어린 손녀를 돌보는 할머니에게 말 걸기", en: "Help the grandmother with her grandchild in a Kamurocho park." },
        },
        {
          number: 85,
          title: { ko: "소매치기 키류!?", en: "Kiryu the Pickpocket!?" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "쇼와 거리에서 누명을 쓰고 진범 추격", en: "Get falsely accused on Showa St. and chase the real thief." },
        },
        {
          number: 90,
          title: { ko: "라멘 No.1 스타", en: "Ramen No. 1 Star" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "큐슈 No.1 별 라멘에서 라멘 챌린지", en: "Take the challenge at Kyushu No. 1 Star ramen." },
        },
        {
          number: 96,
          title: { ko: "첫 번째 경비원", en: "The First Bouncer" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「경비원 모집」 후 문자 안내 위치에서 첫 후보 영입", en: "After 'Bouncers Needed': recruit the first candidate via text." },
        },
        {
          number: 97,
          title: { ko: "두 번째 경비원", en: "The Second Bouncer" },
          chapter: { ko: "챕터 6", en: "Chapter 6" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "두 번째 문자 위치에서 후보 영입", en: "Second recruit, follow the next text." },
        },
      ],
    },
    {
      title: { ko: "챕터 7 — 카무로쵸", en: "Chapter 7 — Mad Dog (Kamurocho)" },
      items: [
        {
          number: 21,
          title: { ko: "소년과 풍선", en: "A Boy and his Balloon" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「도둑을 잡아라!」 클리어 후 나카미치·타이헤이 교차로 남쪽 우는 소년에게 말 걸기", en: "After 'Catch Those Shoplifters!': the crying boy south of Nakamichi/Taihei." },
        },
        {
          number: 37,
          title: { ko: "Mr. 때려봐 잡아봐", en: "Mr. Try and Catch Me" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「Mr. 때려봐 도망」 후 시치후쿠 주차장 도주자 추격", en: "After 'Flee Me': chase the runner around Shichifuku Parking." },
        },
        {
          number: 50,
          title: { ko: "메인 코스", en: "Main Course" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「오르되브르」 후 젤라테리아 카무로 앞 여성에게 말 걸기", en: "After 'Appetizer': talk to the woman outside Gelateria Kamuro." },
        },
        {
          number: 58,
          title: { ko: "잘못 짖었다", en: "Barking up the Wrong Tree" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「끝없는 스토커」 후 시치후쿠·센료 교차로 호객꾼에게 말 걸기", en: "After 'Nonstop Stalkers': the barker at Shichifuku/Senryo." },
        },
        {
          number: 64,
          title: { ko: "참치 펀드", en: "The Tuna Fund" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「리노베이션 주의보」 후 스시 긴에서 참치 시식 → 어장에 투자", en: "After 'Watch Out for Renovations': order tuna at Sushi Gin and invest." },
          body: { ko: "「리노베이션 주의보」 클리어 후 스시 긴에 입장 → 셰프가 참치 권유 시 주문 → 옆자리 어장 사장 사와다와 대화 후 투자 (100주 = 100만엔이 최대 보상). 10장에서 오키나와로 가면 사와다 문자 → 하츠마치 북동쪽 사무실은 가짜 → 카무로쵸 스시 긴에서 진짜 위치 청취 → 밀레니엄 타워 동쪽 \"와일드 잭슨\" 남쪽 녹색 차양 건물에서 사와다 일당 격파.", en: "After 'Watch Out for Renovations'. Order tuna at Sushi Gin, then invest with Sawada (up to 100 shares = 1,000,000 yen for max reward). In Ch.10 he texts a fake Hatsumachi address; return to Sushi Gin for the real location east of Millennium Tower, then beat Sawada." },
          choices: [
            { prompt: { ko: "참치 주문", en: "Order the tuna?" }, correct: { ko: "주문한다", en: "Yes — order it" }, note: { ko: "주문하지 않으면 서브 스토리 미발생", en: "Skipping ends the substory" } },
            { prompt: { ko: "어장 투자 주식 수", en: "Shares to buy" }, correct: { ko: "가능한 한 많이 (최대 100주 = 100만엔)", en: "As many as possible (max 100 = 1M yen)" }, note: { ko: "투자 액수가 곧 보상 마구로 수", en: "Investment scales the Maguro reward" } },
          ],
          reward: { ko: "투자금 전액 환급 + 최대 마구로 4개", en: "Full refund + up to 4 Maguros" },
        },
        {
          number: 65,
          title: { ko: "명품 날치기", en: "Chic Snatcher" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "르 마르셰 앞에서 가방 날치기 소문 듣고, 가방 구매 후 추격", en: "Hear bag-snatching rumors at Le Marche, buy a bag, then chase." },
        },
        {
          number: 81,
          title: { ko: "리노베이션 주의보", en: "Watch Out for Renovations" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「편의점 강도」 후 뉴 세레나 앞 노인에게 말 걸기 → 가게 보기", en: "After 'Convenient Robbery': old man outside New Serena, then mind the bar." },
        },
        {
          number: 91,
          title: { ko: "카무로쵸의 여왕", en: "Queen of Kamurocho" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「Mr. 때려봐 잡아봐」 후 시치후쿠 동쪽 안경 남자가 의뢰 — 파파라치 5인 차단", en: "After 'Mr. Try and Catch Me': the bespectacled rep east of Shichifuku tasks you with blocking five paparazzi." },
          body: { ko: "「Mr. 때려봐 잡아봐」 클리어 후 시치후쿠 동쪽 안경 남자가 여배우 다카하시 마키코의 파파라치 5명을 차단 의뢰. 5명 위치: ① 길 건너편 (매니저가 지목) ② 파크 골목 첫 오른쪽 입구 ③ 카미야마 워크스 골목 안 왼쪽 ④ 거리 북단 파란 천막 옆 ⑤ 검은 모자, 택시 근처 왔다 갔다 하는 카메라 든 남자.", en: "After 'Mr. Try and Catch Me': the manager east of Shichifuku asks you to intercept five paparazzi: across the street, up Park Alley to the right, in the alley by Kamiyama Works, by the north-end blue tarp, and the man pacing near the taxi." },
          reward: { ko: "100,000엔 + 「이탈리아 향수」", en: "100,000 yen + Italian Perfume" },
        },
        {
          number: 92,
          title: { ko: "편의점 강도", en: "Convenient Robbery" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「돌아온 사나이」 후 파크 거리 서쪽 검은 옷의 남자에게 말 걸기", en: "Clear 'The Returnee': talk to the man in black west of West Park." },
        },
        {
          number: 98,
          title: { ko: "세 번째 경비원", en: "The Third Bouncer" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "세 번째 문자 위치에서 후보 영입", en: "Third recruit, follow the next text." },
        },
        {
          number: 99,
          title: { ko: "네 번째 경비원", en: "The Fourth Bouncer" },
          chapter: { ko: "챕터 7", en: "Chapter 7" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "네 번째 문자 위치에서 후보 영입", en: "Fourth recruit, follow the next text." },
        },
      ],
    },
    {
      title: { ko: "챕터 9 — 카무로쵸", en: "Chapter 9 — The Plot (Kamurocho)" },
      items: [
        {
          number: 9,
          title: { ko: "카페 알프스의 살인", en: "Murder at Café Alps" },
          chapter: { ko: "챕터 9", en: "Chapter 9" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "9장: 카페 알프스 앞 전단지 배포 여성에게 말 걸기 (12장 야간에 완결)", en: "Ch.9: talk to the flyer girl outside Café Alps; finish in Ch.12 at night." },
          body: { ko: "장기 추리 서브. 9장에 카페 알프스 앞 전단지 여성·기자 와카조와 대화 → 수첩 입수. 12장 야간에 밴텀의 마에다 형사 → 플로리스트·우사미·아사이·키노시타·이마가와 → 키노시타의 아내 유코를 스타더스트에서 추궁 → 마에다에게서 증거 목록 → 카페 알프스에서 와카조 앞 단죄. 증거 제출 순서: 우사미 증언 → 재떨이 지문 → 키노시타 증언 → 이마가와 증언 → 증거 목록 + 아사이 증언 2 → 「유코 키노시타가 범인이다」 → 아사이 증언 → 유코의 명함 → 와카조의 증언 → 플로리스트의 증언.", en: "Long mystery. Start in Ch.9 with Wakazo at Café Alps. Finish in Ch.12 at night: interview Maeda at Bantam, the Florist, Usami at Mach Bowl, Asai at Poppo Nakamichi, Kinoshita at Cafe Alps, Imagawa at Theater Square Club SEGA; corner Yuko at Stardust; pick up evidence list from Maeda; return to Alps. Present in this order: Usami's Testimony → Ashtray Fingerprints → Kinoshita's Testimony → Imagawa's Testimony → List of Evidence + Asai's Testimony 2 → J'accuse Yuko Kinoshita → Asai's Testimony → Yuko's Business Card → Wakazo's Testimony → Florist's Testimony." },
          reward: { ko: "200,000엔 + 컴플리션 카운트", en: "200,000 yen + completion credit" },
        },
        {
          number: 73,
          title: { ko: "도쿄의 마즈 파이터즈", en: "Mars Fighters in Tokyo" },
          chapter: { ko: "챕터 9", en: "Chapter 9" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "밀레니엄 타워 앞 빨간 재킷의 키타가와에게 말 걸기", en: "Talk to Kitagawa (red jacket) outside Millennium Tower." },
        },
        {
          number: 76,
          title: { ko: "끊긴 통화", en: "Disconnected" },
          chapter: { ko: "챕터 9", en: "Chapter 9" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「용의 보물 훔치기」 후 극장 광장 공중전화 받기 → 슬롯 하우스 앞 범인", en: "Clear 'Stealing from the Dragon's Hoard'; answer the Theater Square payphone — culprit is at Slot House." },
        },
        {
          number: 77,
          title: { ko: "용의 보물 훔치기", en: "Stealing from the Dragon's Hoard" },
          chapter: { ko: "챕터 9", en: "Chapter 9" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「당신의 운명을 봐드립니다」 후 타이헤이 서쪽에서 날치기 추격", en: "After 'Your Fortunes Told Here': chase the pickpocket west on Taihei." },
        },
        {
          number: 80,
          title: { ko: "당신의 운명을 봐드립니다", en: "Your Fortunes Told Here" },
          chapter: { ko: "챕터 9", en: "Chapter 9" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "핑크 거리 클럽 SHINE 남쪽 점쟁이에게 말 걸기", en: "Talk to the fortune-teller south of Club Shine on Pink St." },
        },
        {
          number: 100,
          title: { ko: "다섯 번째 경비원", en: "The Fifth Bouncer" },
          chapter: { ko: "챕터 9", en: "Chapter 9" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「네 번째 경비원」 후 시치후쿠 풍속 안내소에서 「개틀링 센도」 찾기", en: "After 'The Fourth Bouncer': find 'Gatling Sendo' at the Men's Entertainment Booth on Shichifuku." },
        },
      ],
    },
    {
      title: { ko: "챕터 10 — 류큐 재방문", en: "Chapter 10 — Unfinished Business (Ryukyu)" },
      items: [
        {
          number: 2,
          title: { ko: "두 아버지", en: "Two Fathers" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "10장 황혼: 류도 사무소 앞 남성에게 말 걸기", en: "Chapter 10 at sunset: talk to the man outside the Ryudo Office." },
          body: { ko: "타미야가 토마의 하츠마치 행을 알린 직후의 황혼대에만 발생. 류도 사무소 → 모리닝글로리에서 미키오 부자 갈등 → 해변 → 마작 진영 → 우마치 식당에서 상공회의소 회장 추격.", en: "Triggers only at sunset after Tamiya's call about Toma. Ryudo Office → Morning Glory (father-son spat) → beach → Mahjong Camp → Umachi restaurant, then chase the Commerce Union President." },
          choices: [
            { prompt: { ko: "미키오에게 어떤 말을 건넬까", en: "What to tell Mikio" }, correct: { ko: "어떤 선택지를 골라도 무방", en: "Either choice is fine" }, note: { ko: "결말 분기는 없음 — 진행만 하면 보상", en: "No branching outcome; any pick clears it" } },
          ],
          reward: { ko: "경험치 + 컴플리션 카운트", en: "EXP + completion credit" },
        },
        {
          number: 17,
          title: { ko: "류큐의 7가지 불가사의 7", en: "The Seven Mysteries of Ryukyu 7" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "10장 동쪽 다리에서 여고생들에게 말 걸기", en: "Chapter 10: schoolgirls on the east bridge." },
        },
        {
          number: 19,
          title: { ko: "야마시타의 보물찾기", en: "Yamashita Treasure Hunt" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「Let's Learn English 3」 후 에비스 전당포 앞 노인에게 말 걸기", en: "After 'Let's Learn English 3': old man outside Ebisu Pawn." },
        },
        {
          number: 34,
          title: { ko: "결단", en: "Reckoning" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「고아원을 노린 강도」 후 스마일 버거 앞에서 청년에게 다시 말 걸기", en: "After 'Robbing the Orphanage': the young man outside Smile Burger again." },
        },
        {
          number: 45,
          title: { ko: "이리오모테 사건", en: "The Iriomote Incident" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「물고기 떼 부르기」 후 공설시장 주인의 의뢰", en: "After 'Chumming the Waters': the market owner asks for help against wildcat smugglers." },
        },
        {
          number: 47,
          title: { ko: "치고 멈추기", en: "Hit-and-Stop" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「Let's Learn English 3」 + 「도쿄에 가고 싶어 3」 후 교차로 두 남자 대화 엿듣고 검은 세단과 충돌", en: "After 'Let's Learn English 3' and 'I Want to Go to Tokyo 3': eavesdrop at the crosswalk, then bump the black sedan." },
        },
        {
          number: 51,
          title: { ko: "디저트", en: "Dessert" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「메인 코스」 후 에비스 전당포 앞 가게 주인에게 말 걸기", en: "After 'Main Course': shop owner outside Ebisu Pawn." },
        },
        {
          number: 57,
          title: { ko: "도쿄에 가고 싶어 3", en: "I Want to Go to Tokyo 3" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "2편 후 에비스 전당포 북쪽에서 다시 말 걸기", en: "After Pt.2: speak to her again north of Ebisu Pawn." },
        },
        {
          number: 68,
          title: { ko: "사채업자에게 던져진 남자", en: "Thrown to the Loan Sharks" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「이리오모테 사건」 후 서쪽 다리에서 그 남자 재등장", en: "After 'The Iriomote Incident': the same man is back on the west bridge." },
        },
        {
          number: 71,
          title: { ko: "사기꾼들의 역습", en: "Revenge of the Con Men" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「비밀 거래」 + 「사기꾼 전쟁」 후 강가에 떼지어 나타난 사기꾼들", en: "After 'Under the Table' + 'The Con Wars': six punks at the riverside." },
        },
        {
          number: 72,
          title: { ko: "새로운 사기", en: "A New Con" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「사기꾼들의 역습」 후 도쿄 밴텀에서 사기꾼들 재회", en: "After 'Revenge of the Con Men': they show up at Bantam." },
        },
        {
          number: 106,
          title: { ko: "영어 공부 3", en: "Let's Learn English 3" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「잃어버린 물건」 후 그녀의 영어 교재 2만엔에 구매 → 아쿠아 스카이에서 「스테이시」와 만남", en: "After 'Lost and Found': buy her textbook for 20,000 yen, meet 'Stacy' at Aqua Sky." },
        },
        {
          number: 107,
          title: { ko: "영어 공부 4", en: "Let's Learn English 4" },
          chapter: { ko: "챕터 10", en: "Chapter 10" },
          location: { ko: "류큐 (오키나와)", en: "Downtown Ryukyu (Okinawa)" },
          trigger: { ko: "「영어 공부 3」 후 마지막 레슨", en: "Final lesson after Lesson 3." },
        },
      ],
    },
    {
      title: { ko: "챕터 12 — 최종 미션", en: "Chapter 12 — The End of Ambition" },
      items: [
        {
          number: 1,
          title: { ko: "데이트의 자존심", en: "Date's Pride" },
          chapter: { ko: "챕터 12", en: "Chapter 12" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "12장: 하루카를 뉴 세레나에 두고 르 마르셰 앞 데이트에게 말 걸기", en: "Chapter 12: leave Haruka at New Serena, talk to Date outside Le Marche." },
          body: { ko: "최종장 데이트의 자존심 결산. 하루카를 뉴 세레나에 두고 르 마르셰 앞에서 데이트와 대화 → 세레나 복귀 → 공원 → 다시 세레나 뒷문 → 나카미치 골목 마커에서 와카조의 호출 처리.", en: "Final-chapter Date storyline: leave Haruka at New Serena, chat with Date at Le Marche, return to Serena, then Public Park 3, then Serena's back door, then Nakamichi Alley once Wakazo calls." },
          reward: { ko: "이벤트 시네마틱 + 컴플리션 카운트", en: "Event cinematic + completion credit" },
        },
        {
          number: 6,
          title: { ko: "이젠 정말 끝", en: "They Never Learn" },
          chapter: { ko: "챕터 12", en: "Chapter 12" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "「한발 빠른 신혼여행」 후 하루카 동반, 밀레니엄 타워 앞 직원과 대화", en: "After 'Early Honeymoon' with Haruka: talk to the office worker by Millennium Tower." },
          body: { ko: "「한발 빠른 신혼여행」 클리어가 전제, 하루카 동반 필수. 밀레니엄 타워 앞 직원에게 말 걸기 → 옥상으로 자동 이동 → 신발만 남긴 채로 추락하는 아키모토 회상 → 강제 시네마틱.", en: "Requires 'Early Honeymoon' cleared and Haruka in tow. Talk to the office worker outside Millennium Tower, take the elevator up, approach the shoes at the edge." },
          prereq: { ko: "「한발 빠른 신혼여행」 클리어 + 하루카 동반", en: "Clear 'Early Honeymoon' + bring Haruka" },
          reward: { ko: "대량 경험치 + 시네마틱", en: "Massive EXP + cinematic" },
        },
        {
          number: 108,
          title: { ko: "아몬", en: "Amon" },
          chapter: { ko: "챕터 12", en: "Chapter 12" },
          location: { ko: "카무로쵸", en: "Kamurocho" },
          trigger: { ko: "다른 118개 서브 스토리·전 히트맨·미나미다 훈련 클리어 + 야간: 카무로 캐슬 HLA의 이부키에게 말 걸기 → 산기슭 콜로세움", en: "Clear all 118 other substories, all Hitman missions, all Minamida training; at night, talk to Ibuki at Kamuro Castle HLA, then taxi to Mountainside Coliseum." },
          body: { ko: "다른 118개 서브 스토리 + 모든 히트맨 미션 + 미나미다의 모든 훈련 완료가 전제. 야간에 카무로 캐슬 HLA에서 이부키 → 미나미다와 대화 → 택시로 「산기슭 콜로세움」 선택. 1페이즈: 듀얼 포톤 블레이드(가드 불가) — 좌우 콤보 사이에 타이거 드롭. 2페이즈: 듀얼 권총 — 뒤에서 공격. 3페이즈: 권총 + 회전 발차기 — 타이거 드롭으로 카운터.", en: "Requires all 118 other substories, all Hitman missions, and all Minamida training. At night, talk to Ibuki at Kamuro Castle HLA, then take a taxi to Mountainside Coliseum. Phase 1: Photon Blades (unblockable) — Tiger Drop between his left-right combos. Phase 2: dual pistols — strike from behind. Phase 3: pistols + rotating kicks — Tiger Drop counter." },
          prereq: { ko: "다른 모든 서브 스토리·히트맨·미나미다 훈련 클리어 + 야간", en: "All 118 substories + Hitman + Minamida training cleared, at night" },
          reward: { ko: "서브 스토리 컴플리션 보상", en: "Substory completion reward" },
        },
      ],
    },
  ],
};
