import type { SubstoriesData } from "./types";

export const yakuza6Substories: SubstoriesData = {
  appId: 1388590,
  summary: {
    ko: "카무로쵸 24건 + 오노미치 진가이초 26건 + 아몬 1건 = 총 51건(컴플리션 리스트 52번 슬롯은 「전체 클리어」). 챕터 진행에 따라 해금되며, 일부는 친구도(스낵 뉴 가우디)·야구·다이빙·캬바쿠라 등 미니게임 의존. 챕터 6 이후 카무로쵸 서브가 대량 해금되니 메인 스토리와 병행이 효율적.",
    en: "24 Kamurocho + 26 Onomichi Jingaicho + 1 Amon = 51 substories (completion-list slot 52 is the 'all cleared' tally). Many gate on Snack New Gaudi friendship, baseball, diving, or hostess clubs; the bulk of Kamurocho unlocks from Chapter 6, so pair them with the main story.",
  },
  source: {
    label: "光る原人 — 龍が如く6 サブストーリー一覧",
    url: "https://www.hikarugennjinn.com/entry/yakuza6-sub_story",
  },
  groups: [
    {
      title: { ko: "카무로쵸 (No.1~24)", en: "Kamurocho (No.1~24)" },
      items: [
        {
          number: 1,
          title: { ko: "키류의 카베동", en: "Kiryu's Wall Slam" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "텐카이치 거리 뒷골목", en: "Tenkaichi St. Alley" },
          trigger: { ko: "텐카이치 거리 뒷골목에서 남성들에게 말 걸기 → 반탐 앞으로 이동", en: "Talk to the men in Tenkaichi Alley, then head to Bantam." },
          body: { ko: "카베동을 가르쳐 달라는 남자들의 부탁. 시범 후 잡졸 무리와 전투.", en: "A group of men ask Kiryu to teach them the 'wall slam'. Demo it, then brawl their tormentors." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 2,
          title: { ko: "전화 상대", en: "The Phone Caller" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "밀레니엄 타워 앞", en: "Millennium Tower" },
          trigger: { ko: "밀레니엄 타워 앞 공중전화에서 걸려오는 전화 응답", en: "Answer the ringing payphone at Millennium Tower." },
          body: { ko: "오레오레 사기범의 전화. 정체를 캐묻고 사기임을 간파하면 일당과 전투로 이어진다.", en: "An 'It's me' scammer calls. Press him on his identity to expose the scam, then beat the crew." },
          choices: [
            { prompt: { ko: "「누구야?」 (1차)", en: "'Who is this?' (1st)" }, correct: { ko: "「타이치냐?」", en: "'Taichi?'" } },
            { prompt: { ko: "「누구야?」 (2차)", en: "'Who is this?' (2nd)" }, correct: { ko: "「타이치냐?」", en: "'Taichi?'" } },
            { prompt: { ko: "수상한가?", en: "Suspicious?" }, correct: { ko: "「이거 오레오레 사기 아냐?」", en: "'This is an It's-me scam, isn't it?'" } },
            { prompt: { ko: "확신하나?", en: "Sure?" }, correct: { ko: "「오레오레 사기가 분명해!」", en: "'Definitely an It's-me scam!'" } },
          ],
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 3,
          title: { ko: "동경하는 사람", en: "Idol Worship" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "시치후쿠 공원", en: "Shichifuku Park" },
          trigger: { ko: "시치후쿠 공원의 소녀 아야카에게 말 걸기", en: "Talk to the girl Ayaka at Shichifuku Park." },
          body: { ko: "하루카의 팬인 소녀 아야카가 하루카 굿즈를 찾고 있다. 도와주면 그림 선물.", en: "A young Haruka fan asks Kiryu to help her find merch. Help her out for a hand-drawn picture." },
          reward: { ko: "「아야카가 그린 하루카 일행 그림」", en: "Ayaka's drawing of Haruka and friends" },
        },
        {
          number: 4,
          title: { ko: "청소 로봇의 폭주", en: "Runaway Cleaner Bot" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "카무로쵸 곳곳", en: "Various Kamurocho streets" },
          trigger: { ko: "거리에서 폭주 중인 청소 로봇 발견 후 추적", en: "Chase the runaway robot vacuum spotted in the streets." },
          body: { ko: "폭주한 청소 로봇을 따라잡아 정지시키고 주인에게 돌려준다.", en: "Catch the rogue cleaning robot and return it to its owner." },
        },
        {
          number: 5,
          title: { ko: "I am human", en: "I am human" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "시치후쿠 공원 서쪽", en: "Shichifuku Park West" },
          trigger: { ko: "공원 서쪽의 AI 캐릭터 「히지」와 대화", en: "Talk to the AI character Hiji west of the park." },
          body: { ko: "자신을 인간이라 주장하는 AI 「히지」와 대화. 인간성에 관한 질문에 답하면 종료.", en: "An AI named Hiji insists he is human. Answer his questions about humanity." },
          reward: { ko: "개운 액막이 부적", en: "Lucky charm (Kaiun Yakuyoke)" },
        },
        {
          number: 6,
          title: { ko: "조회수가 전부", en: "Views Are Everything" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "씨어터 광장 앞", en: "Theater Square" },
          trigger: { ko: "씨어터 광장의 유튜버 우스이에게 말 걸기", en: "Talk to YouTuber Usui at Theater Square." },
          body: { ko: "노이즈 유튜버 우스이의 무모한 스턴트를 도와주거나 말리는 흐름. 결국 시청자 시비로 전투까지 이어진다.", en: "Help — or stop — viral creator Usui's stunt; ends in a brawl with hostile viewers." },
        },
        {
          number: 7,
          title: { ko: "드론을 쫓아라", en: "Chase the Drone" },
          chapter: { ko: "챕터 7 이후", en: "Chapter 7+" },
          location: { ko: "센료 거리", en: "Senryo Ave." },
          trigger: { ko: "센료 거리에서 드론을 발견 후 추적", en: "Spot the drone on Senryo Ave. and chase it." },
          body: { ko: "수상한 드론을 추적하여 다목적 빌딩까지 도달, 운영자와 대치.", en: "Chase a suspicious drone to a multipurpose building and confront its operator." },
        },
        {
          number: 8,
          title: { ko: "원한 가진 자들 1", en: "Those With a Grudge 1" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "텐카이치 거리 — 배팅 센터 앞", en: "Tenkaichi St. — outside Batting Center" },
          trigger: { ko: "배팅 센터 앞 핫피 차림 남성에게 말 걸기", en: "Talk to the man in a happi coat outside the Batting Center." },
          body: { ko: "키류에게 원한이 있다는 사내들과의 전투.", en: "Brawl with men who claim a grudge against Kiryu." },
        },
        {
          number: 9,
          title: { ko: "원한 가진 자들 2", en: "Those With a Grudge 2" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "배팅 센터 부근", en: "Near the Batting Center" },
          trigger: { ko: "No.8 클리어 후 배팅 센터 부근에서 재발생", en: "After clearing No.8, the grudge crew returns near the Batting Center." },
          prereq: { ko: "No.8 클리어", en: "Complete No.8" },
        },
        {
          number: 10,
          title: { ko: "매혹적인 권유", en: "An Alluring Invitation" },
          chapter: { ko: "챕터 6 이후 (야간)", en: "Chapter 6+, night" },
          location: { ko: "머핀 빌딩 부근", en: "Near Muffin Building" },
          trigger: { ko: "야간 머핀 빌딩 부근 여성에게 말 걸기", en: "Speak to the woman near the Muffin Building at night." },
          body: { ko: "셀카 모델을 부탁하는 여성과 동행. 3장의 사진 촬영 미니이벤트.", en: "Tag along with a woman who wants three selfies — pose for each." },
        },
        {
          number: 11,
          title: { ko: "지금 바빠?", en: "Are You Busy?" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "시치후쿠 공원", en: "Shichifuku Park" },
          trigger: { ko: "공원에서 곤란해하는 청년에게 말 걸기 → POPPO에서 5만엔 선불카드 구매", en: "Talk to the troubled young man at the park, then buy a 50,000 yen prepaid card at POPPO." },
          body: { ko: "선불카드 사기 의심 상황. 즉시 보내지 말고 끝까지 우겨야 사기범 일당이 등장하여 전투, 완전 보상.", en: "A prepaid-card scam setup. Refuse to send the number — push back twice — to draw out the crew and clear properly." },
          choices: [
            { prompt: { ko: "카드 번호 알려달라", en: "Send the number?" }, correct: { ko: "용도를 묻는다", en: "Ask their purpose" } },
            { prompt: { ko: "그래도 보내달라", en: "Send anyway?" }, correct: { ko: "버텨본다", en: "Push back" } },
            { prompt: { ko: "끝까지 보내달라", en: "Final ask?" }, correct: { ko: "더 버텨본다", en: "Push back harder" } },
          ],
          reward: { ko: "경험치 + 삥쟁이 일당 격파", en: "EXP + scammer crew defeated" },
        },
        {
          number: 12,
          title: { ko: "전설의 사나이 폴 림", en: "The Legend, Paul Lim" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "반탐", en: "Bantam" },
          trigger: { ko: "반탐에서 아카이시와 다트 대결", en: "Play darts against Akaishi at Bantam." },
          body: { ko: "다트 명인 폴 림에 도전하기 위한 자격 매치. 아카이시 격파 시 중급자의 화살 획득.", en: "Beat Akaishi at Bantam to qualify for a showdown against Paul Lim." },
          reward: { ko: "「중급자의 화살」", en: "Intermediate Darts" },
        },
        {
          number: 13,
          title: { ko: "폴 림과의 대결", en: "Battle with Paul Lim" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "반탐", en: "Bantam" },
          trigger: { ko: "No.12 클리어 후 폴 림에게 도전", en: "After clearing No.12, challenge Paul Lim." },
          prereq: { ko: "No.12 클리어", en: "Complete No.12" },
          reward: { ko: "「폴 림의 화살」", en: "Paul Lim's Darts" },
        },
        {
          number: 14,
          title: { ko: "맞서는 자", en: "Standing Up" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "밀레니엄 타워 부근 캬바쿠라", en: "Cabaret near Millennium Tower" },
          trigger: { ko: "캬바쿠라에서 사키를 No.1으로 만들기", en: "Make Saki No.1 at the cabaret." },
          body: { ko: "캬바쿠라 미니게임 연계. 사키 양성 후 트러블 해결.", en: "Cabaret minigame chain — train Saki to top, then handle the trouble that follows." },
        },
        {
          number: 15,
          title: { ko: "매혹의 데뷔", en: "Charming Debut" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "다목적 빌딩 캬바쿠라", en: "Multipurpose Bldg. Cabaret" },
          trigger: { ko: "히카루를 No.1으로 만들기", en: "Make Hikaru No.1 at the cabaret." },
        },
        {
          number: 16,
          title: { ko: "마음을 전하다", en: "Conveying Feelings" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "씨어터 광장 캬바쿠라", en: "Theater Square Cabaret" },
          trigger: { ko: "SORA를 No.1으로 만들기", en: "Make SORA No.1 at the cabaret." },
        },
        {
          number: 17,
          title: { ko: "꼬마 악마의 위기", en: "Little Devil's Crisis" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "씨어터 광장 캬바쿠라", en: "Theater Square Cabaret" },
          trigger: { ko: "에리나를 No.1으로 만들기", en: "Make Erina No.1 at the cabaret." },
        },
        {
          number: 18,
          title: { ko: "양심적인 캬바걸", en: "The Honest Hostess" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "핑크 거리 캬바쿠라", en: "Pink St. Cabaret" },
          trigger: { ko: "리오나를 No.1으로 만들기", en: "Make Riona No.1 at the cabaret." },
        },
        {
          number: 19,
          title: { ko: "ID 배팅 센터", en: "ID Batting Center" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "배팅 센터", en: "Batting Center" },
          trigger: { ko: "오노미치 No.35 클리어 후 5연속 홈런", en: "After Onomichi No.35, hit 5 home runs in a row." },
          prereq: { ko: "오노미치 No.35 클리어", en: "Clear Onomichi No.35" },
        },
        {
          number: 20,
          title: { ko: "나니와의 홈런왕", en: "Naniwa Home Run King" },
          chapter: { ko: "챕터 6 이후", en: "Chapter 6+" },
          location: { ko: "배팅 센터", en: "Batting Center" },
          trigger: { ko: "오노미치 No.35 클리어 후 홈런 7개 이상", en: "After Onomichi No.35, score 7+ home runs." },
          prereq: { ko: "오노미치 No.35 클리어", en: "Clear Onomichi No.35" },
        },
        {
          number: 21,
          title: { ko: "고양이 카페에 어서 오세요", en: "Welcome to the Cat Cafe" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "고양이 카페 냥냥", en: "Cat Cafe Nyan Nyan" },
          trigger: { ko: "고양이 카페 입장", en: "Enter the cat cafe." },
        },
        {
          number: 22,
          title: { ko: "라이브 챗의 유혹", en: "Live Chat Temptation" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "인터넷 카페 만타이", en: "Internet Cafe Mantai" },
          trigger: { ko: "인터넷 카페에서 라이브 챗 이용", en: "Use live chat at the internet cafe." },
        },
        {
          number: 23,
          title: { ko: "결과에 커밋하는 남자", en: "The Man Who Commits to Results" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "RIZAP", en: "RIZAP" },
          trigger: { ko: "RIZAP 입회 후 트레이닝 완료", en: "Join RIZAP and complete training." },
        },
        {
          number: 24,
          title: { ko: "다시 태어난 남자", en: "A Reborn Man" },
          chapter: { ko: "챕터 1 이후", en: "Chapter 1+" },
          location: { ko: "RIZAP / 카무로쵸 거리", en: "RIZAP / Kamurocho streets" },
          trigger: { ko: "No.23 클리어 후 소다와 재대결", en: "After No.23, rematch Soda multiple times." },
          prereq: { ko: "No.23 클리어", en: "Complete No.23" },
        },
      ],
    },
    {
      title: { ko: "오노미치 진가이초 (No.25~50)", en: "Onomichi Jingaicho (No.25~50)" },
      items: [
        {
          number: 25,
          title: { ko: "연애 금지", en: "No Dating Allowed" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "류난 신사", en: "Ryunan Shrine" },
          trigger: { ko: "류난 신사 부근의 젊은 커플에게 말 걸기", en: "Talk to the young couple near Ryunan Shrine." },
          body: { ko: "젊은 커플의 사정을 듣고 도와준 후, 방해하는 야쿠자 일당과 전투.", en: "Help a young couple, then fight off yakuza who interfere." },
        },
        {
          number: 26,
          title: { ko: "교주님의 속죄", en: "The Cult Leader's Atonement" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "신흥 종교 시설", en: "Cult compound" },
          trigger: { ko: "수상한 신흥 종교 권유자에게 말 걸기", en: "Talk to the suspicious cult recruiter." },
          body: { ko: "수상한 종교의 입회 시험. 모든 질문에 「올바르게」 답해 교주의 정체를 밝히고 격파.", en: "A bogus cult's induction quiz. Answer every prompt 'correctly' to expose the leader, then beat him." },
          choices: [
            { prompt: { ko: "입회 의사", en: "Intent" }, correct: { ko: "「무난쵸헤페트나스교에 들고 싶다」", en: "'I want to join the Munanchohepetonas religion'" } },
            { prompt: { ko: "인사", en: "Greeting" }, correct: { ko: "포즈를 잡고 인사", en: "Greet with the pose" } },
            { prompt: { ko: "주문 응답", en: "Mantra response" }, correct: { ko: "「헤페트나스」", en: "'Hepetonas'" } },
            { prompt: { ko: "외칠 말", en: "Sacred phrase" }, correct: { ko: "「쿠・리파스」", en: "'Ku-Ripaasu'" } },
            { prompt: { ko: "교명(이름)", en: "Cult name" }, correct: { ko: "「무난쵸・아카마츠」", en: "'Munancho-Akamatsu'" } },
            { prompt: { ko: "수업 내용", en: "Activity" }, correct: { ko: "「재교육」", en: "'Re-education'" } },
          ],
          reward: { ko: "「용의 눈」", en: "Dragon's Eye" },
        },
        {
          number: 27,
          title: { ko: "포케서 파이터, 다시", en: "Pocket Circuit Fighter Returns" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "후지사와 두부점", en: "Fujisawa Tofu Shop" },
          trigger: { ko: "후지사와 두부점에서 재회 이벤트", en: "Trigger the reunion event at Fujisawa Tofu." },
        },
        {
          number: 28,
          title: { ko: "오노미치의 저주", en: "The Onomichi Curse" },
          chapter: { ko: "챕터 4 이후 (야간)", en: "Chapter 4+, night" },
          location: { ko: "묘지", en: "Cemetery" },
          trigger: { ko: "야간에 묘지에서 발생하는 괴기 현상 조사", en: "Investigate the nightly hauntings at the cemetery." },
          body: { ko: "야간 묘지에서 시간차로 발생하는 유령 조우 이벤트. 모두 처리하면 진상 판명.", en: "A series of timed ghost encounters in the cemetery at night; clear them all to learn the truth." },
        },
        {
          number: 29,
          title: { ko: "지역 캐릭터가 되자!", en: "Become a Local Mascot!" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "오노미치 아케이드", en: "Onomichi Arcade" },
          trigger: { ko: "아케이드의 마스코트 「미치오」 데뷔를 돕기", en: "Help the mascot Michio make his debut." },
        },
        {
          number: 30,
          title: { ko: "미치오의 가요 쇼", en: "Michio's Song Show" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "노래방", en: "Karaoke" },
          trigger: { ko: "No.29, No.40 클리어 후 노래방에서 합창", en: "After No.29 and No.40, sing together at karaoke." },
          prereq: { ko: "No.29 + No.40 클리어", en: "Clear No.29 + No.40" },
        },
        {
          number: 31,
          title: { ko: "용기를 주다", en: "Giving Courage" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "오노미치", en: "Onomichi" },
          trigger: { ko: "No.30 클리어 후 소년을 격려", en: "After No.30, cheer up a young boy." },
          prereq: { ko: "No.30 클리어", en: "Clear No.30" },
        },
        {
          number: 32,
          title: { ko: "시간을 뛰어넘었다는 소녀", en: "The Girl Who Time-Travelled" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "사카노우에 거리", en: "Sakanoue Rd." },
          trigger: { ko: "사카노우에 거리의 소녀에게 말 걸기", en: "Talk to the girl on Sakanoue Rd." },
          body: { ko: "「미래에서 왔다」는 소녀의 말을 끝까지 들어주면 일당이 출현, 전투로 마무리.", en: "Hear out the 'time-traveler' girl all the way; her crew shows up and you brawl." },
          choices: [
            { prompt: { ko: "더 들을 것인가", en: "Hear more?" }, correct: { ko: "「알았다 조금 더 들어주마」", en: "'Fine, I'll hear more'" } },
            { prompt: { ko: "무엇을 물을 것인가", en: "What to ask" }, correct: { ko: "「난 1년 후 어떻게 됐지?」", en: "'How am I a year from now?'" } },
            { prompt: { ko: "믿을 것인가", en: "Believe?" }, correct: { ko: "「알았다 믿어주마」", en: "'Fine, I'll believe you'" } },
          ],
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 33,
          title: { ko: "뒤바뀐 두 사람?", en: "Did They Switch?" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "류난 신사 부근", en: "Near Ryunan Shrine" },
          trigger: { ko: "신사 부근에서 울고 있는 사람에게 말 걸기", en: "Talk to the crying person near the shrine." },
          body: { ko: "「몸이 뒤바뀌었다」는 두 사람을 도와주려 하면 무라나카 일당이 난입하여 전투.", en: "Help two people who claim their bodies switched; Muranaka and crew jump you." },
          choices: [
            { prompt: { ko: "어떻게 위로하나", en: "How to comfort?" }, correct: { ko: "「울 거면 내 가슴에 기대」", en: "'If you must cry, lean on me'" } },
          ],
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 34,
          title: { ko: "동네 야구 권유", en: "Sandlot Baseball" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "시시 거리 서쪽", en: "Shishi Rd. West" },
          trigger: { ko: "야구팀에 합류", en: "Join the local baseball team." },
        },
        {
          number: 35,
          title: { ko: "팀메이트를 찾아라", en: "Find Teammates" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.34 클리어 후 모리타 영입", en: "After No.34, recruit Morita." },
          prereq: { ko: "No.34 클리어", en: "Clear No.34" },
        },
        {
          number: 36,
          title: { ko: "첫 승리의 맛", en: "Taste of First Victory" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.35 클리어 후 2군 격파", en: "After No.35, beat the 2nd team." },
          prereq: { ko: "No.35 클리어", en: "Clear No.35" },
        },
        {
          number: 37,
          title: { ko: "결전! 진가이 선더즈", en: "Showdown! Jingai Thunders" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.36 클리어 후 1군 격파", en: "After No.36, beat the 1st team." },
          prereq: { ko: "No.36 클리어", en: "Clear No.36" },
        },
        {
          number: 38,
          title: { ko: "오노미치 최강의 자리", en: "Onomichi's Strongest" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.37 클리어 후 레전드 격파", en: "After No.37, beat the Legends." },
          prereq: { ko: "No.37 클리어", en: "Clear No.37" },
        },
        {
          number: 39,
          title: { ko: "유대", en: "Bonds" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.38 클리어 후 고저스 격파", en: "After No.38, beat the Gorgeous team." },
          prereq: { ko: "No.38 클리어", en: "Clear No.38" },
        },
        {
          number: 40,
          title: { ko: "어른으로의 계단", en: "Stairway to Adulthood" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "스낵 뉴 가우디", en: "Snack New Gaudi" },
          trigger: { ko: "스낵 뉴 가우디 입장", en: "Enter Snack New Gaudi." },
        },
        {
          number: 41,
          title: { ko: "부모 마음 자식은 모른다", en: "Parental Heart" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "하타케야마와 친구도 3 달성", en: "Reach Hatakeyama friendship lv.3." },
        },
        {
          number: 42,
          title: { ko: "그 시절의 추억", en: "Memories of Then" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "아키요시와 친구도 진행", en: "Build friendship with Akiyoshi." },
        },
        {
          number: 43,
          title: { ko: "하이테크는 지긋지긋", en: "Sick of Hi-Tech" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "겐과 친구도 진행", en: "Build friendship with Gen." },
        },
        {
          number: 44,
          title: { ko: "반지의 가치", en: "Price of a Ring" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "안도와 친구도 진행 후 야쿠자와 전투", en: "Befriend Ando, then brawl yakuza." },
        },
        {
          number: 45,
          title: { ko: "은퇴의 결의", en: "Resolve to Retire" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "카네코와 친구도 진행", en: "Build friendship with Kaneko." },
        },
        {
          number: 46,
          title: { ko: "엄마 늘 고마워요", en: "Thanks, Mama" },
          chapter: { ko: "챕터 5 이후", en: "Chapter 5+" },
          location: { ko: "스낵 뉴 가우디", en: "Snack New Gaudi" },
          trigger: { ko: "마마와 친구도 진행 후 스낵에 편지 남기기", en: "Befriend Mama, then leave a letter at the snack." },
        },
        {
          number: 47,
          title: { ko: "바다와 함께 사는 자들", en: "Those Who Live with the Sea" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "페리 부두", en: "Ferry Dock" },
          trigger: { ko: "부두에서 참치 조사 후 낚시 미션 개시", en: "Investigate the tuna at the dock, then start the fishing mission." },
        },
        {
          number: 48,
          title: { ko: "세계에서 가장 맛있는 문어", en: "The World's Tastiest Octopus" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "페리 부두", en: "Ferry Dock" },
          trigger: { ko: "잠수 미션에서 문어 격파", en: "Defeat the octopus in the diving mission." },
        },
        {
          number: 49,
          title: { ko: "소중한 장소", en: "An Important Place" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "항구", en: "Harbor" },
          trigger: { ko: "고급 잠수 미션에서 상어 격파", en: "Defeat the shark in the advanced diving mission." },
        },
        {
          number: 50,
          title: { ko: "위기관리의 프로", en: "Crisis Management Pro" },
          chapter: { ko: "챕터 4 이후", en: "Chapter 4+" },
          location: { ko: "로프웨이 역", en: "Ropeway Station" },
          trigger: { ko: "로프웨이 역의 남자에게 도시락 전달 후 트러블 해결", en: "Hand the bento to the man at the ropeway, then clear his trouble missions." },
        },
      ],
    },
    {
      title: { ko: "최종 도전 — 아몬", en: "Final Challenge — Amon" },
      items: [
        {
          number: 51,
          title: { ko: "아몬 죠", en: "Amon Jo" },
          chapter: { ko: "최종 챕터 이후", en: "Post-final chapter" },
          location: { ko: "아몬의 부유섬", en: "Amon's Floating Island" },
          trigger: { ko: "No.24, No.50 등 전제 클리어 후 아몬 키도와 결전", en: "Clear No.24 and No.50 prerequisites, then duel Amon Kido." },
          prereq: { ko: "No.24 + No.50 클리어 (사실상 전 서브 클리어)", en: "Clear No.24 + No.50 (effectively all substories)" },
        },
      ],
    },
  ],
};
