import type { SubstoriesData } from "./types";

export const yakuza5Substories: SubstoriesData = {
  appId: 1105510,
  summary: {
    ko: "5인 주인공(키류/사에지마/하루카/아키야마/시나다) × 5개 도시(나가스가이=후쿠오카·츠키미노=삿포로·소텐보리=오사카·카무로초=도쿄·킨에이초=나고야) 합산 약 79건. 키류·사에지마·아키야마·시나다는 거리 ?아이콘 → 격투 기반. 하루카 편은 댄스/아이돌 미니게임 기반으로 전투가 없음. 장 진행에 따라 해금되며 본편 도중 놓치면 일부는 회수 불가.",
    en: "~79 substories across 5 protagonists (Kiryu/Saejima/Haruka/Akiyama/Shinada) and 5 cities (Nagasugai=Fukuoka, Tsukimino=Sapporo, Sotenbori=Osaka, Kamurocho=Tokyo, Kineicho=Nagoya). Kiryu/Saejima/Akiyama/Shinada substories use standard combat; Haruka's chapter uses dance/idol minigame mechanics with no combat. Chapter-gated — some are missable.",
  },
  source: { label: "kamigame.jp — 龍が如く5 サブストーリー全イベントの一覧", url: "https://kamigame.jp/ryugagotoku5/page/53484799733530626.html" },
  groups: [
    {
      title: { ko: "키류 편 — 후쿠오카 나가스가이", en: "Kiryu — Fukuoka (Nagasugai)" },
      items: [
        {
          number: 1,
          title: { ko: "머나먼 땅에서", en: "From a Distant Land" },
          chapter: { ko: "1부 2장", en: "Part 1, Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 후쿠하쿠 거리 북쪽", en: "Nagasugai — Fukuhaku St. north" },
          trigger: { ko: "2장에서 아이자와/모리나가전 이후 거리에서 발생", en: "Chapter 2 — appears on the street after the Aizawa/Morinaga fight." },
          body: { ko: "오키나와에서 카무로초로 가던 청년이 길을 잃고 곤란해한다. 키류가 사정을 듣고 도와준다.", en: "A young man from Okinawa is lost on his way to Kamurocho. Kiryu hears him out and helps." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 2,
          title: { ko: "택시 S・O・S", en: "Taxi S.O.S." },
          chapter: { ko: "1부 2장~", en: "Part 1, Chapter 2+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 기온 거리", en: "Nagasugai — Gion St." },
          trigger: { ko: "기온 거리에서 곤란한 운전사에게 말 걸기", en: "Talk to the troubled taxi driver on Gion St." },
          body: { ko: "키류가 본업인 택시 드라이버로서 손님을 목적지로 모신다. 택시 드라이브 미니게임 도입.", en: "Kiryu takes the wheel as a taxi driver — introduces the Taxi Driver minigame line." },
          reward: { ko: "택시 드라이브 미션 해금", en: "Unlocks Taxi Driver missions" },
        },
        {
          number: 3,
          title: { ko: "합석의 제왕", en: "King of the Group Date" },
          chapter: { ko: "1부 2장~", en: "Part 1, Chapter 2+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 오세바시 거리 동쪽", en: "Nagasugai — Oosebashi St. east" },
          trigger: { ko: "어나더 드라마(택시) 일정 진척 후 발생", en: "Progress the Taxi Another Drama first, then talk to the man." },
          prereq: { ko: "택시 드라이브 어나더 드라마 진행", en: "Taxi Another Drama in progress" },
          body: { ko: "합석 자리에서 분위기를 살려달라는 의뢰. 멋들어지게 멘트를 받아치면 OK.", en: "A man asks Kiryu to liven up his group date. Pick smooth lines to carry the table." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 4,
          title: { ko: "유괴범을 쫓아라", en: "Chase the Kidnappers" },
          chapter: { ko: "1부 2장", en: "Part 1, Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 치쿠젠 강가 거리", en: "Nagasugai — Chikuzen River St." },
          trigger: { ko: "2장 보스전 이후 거리에서 비명 듣기", en: "Chapter 2 — hear screams on Chikuzen River St. after the boss fight." },
          body: { ko: "어린 아이가 유괴되는 현장. 키류가 추격해 범인 일당을 제압한다. 미씨블.", en: "Witness a kidnapping in progress. Chase down and beat the abductors. Missable." },
          reward: { ko: "경험치 + 회복 아이템", en: "EXP + recovery item" },
        },
        {
          number: 5,
          title: { ko: "하루카를 떠올리며", en: "Reminded of Haruka" },
          chapter: { ko: "1부 2장~", en: "Part 1, Chapter 2+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 치쿠젠 강가 거리 남쪽", en: "Nagasugai — Chikuzen River St. south" },
          trigger: { ko: "거리에서 울고 있는 소녀에게 말 걸기", en: "Talk to the crying girl on Chikuzen River St. south." },
          body: { ko: "엄마를 잃어버린 소녀를 도와준다. 하루카가 떠올라 키류의 마음이 흔들린다.", en: "Help a little girl find her mother — the encounter reminds Kiryu of Haruka." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 6,
          title: { ko: "사이버 테러", en: "Cyber Terror" },
          chapter: { ko: "1부 2장", en: "Part 1, Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 오세바시 거리 동쪽", en: "Nagasugai — Oosebashi St. east" },
          trigger: { ko: "2장 보스전 이후 발생. 노트북을 든 남자에게 말 걸기", en: "After the Chapter 2 boss fight, talk to the man with a laptop." },
          body: { ko: "해커를 자칭하는 남자가 키류에게 협박. 단호히 거절하면 일당이 덤벼들지만 가볍게 제압한다. 미씨블.", en: "A self-proclaimed hacker tries to threaten Kiryu. Refuse and beat his crew. Missable." },
          choices: [
            { prompt: { ko: "「돈을 내놔라」", en: "'Hand over the money.'" }, correct: { ko: "거절한다", en: "Refuse" } },
          ],
          reward: { ko: "경험치 + 현금", en: "EXP + cash" },
        },
        {
          number: 7,
          title: { ko: "키류는 연기파", en: "Kiryu the Method Actor" },
          chapter: { ko: "1부 4장~", en: "Part 1, Chapter 4+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 하쿠치쿠젠 거리", en: "Nagasugai — Hakuchikuzen St." },
          trigger: { ko: "거리의 영화 감독에게 말 걸기", en: "Talk to the film director on the street." },
          body: { ko: "야쿠자 연기에 맞는 배우를 찾는 감독. 키류가 즉석에서 야쿠자 역을 연기해준다.", en: "A director needs someone to play a yakuza role. Kiryu plays the part on the spot." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 8,
          title: { ko: "키류 씨 아니에요?", en: "Aren't You Kiryu-san?" },
          chapter: { ko: "1부 4장~", en: "Part 1, Chapter 4+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 후쿠하쿠 거리 서쪽", en: "Nagasugai — Fukuhaku St. west" },
          trigger: { ko: "거리에서 키류를 알아본 청년에게 말 걸기", en: "A young man recognizes Kiryu on Fukuhaku St. west." },
          body: { ko: "도쿄에서 키류를 알던 청년이 후쿠오카에서 우연히 마주친다. 신분이 드러나지 않게 능청을 떨어야 한다.", en: "A man from Tokyo bumps into Kiryu in Fukuoka. Play it cool to keep your cover." },
          choices: [
            { prompt: { ko: "「키류 씨 아니에요?」", en: "'Aren't you Kiryu-san?'" }, correct: { ko: "사람을 잘못 봤다", en: "You've got the wrong guy" } },
          ],
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 9,
          title: { ko: "노크 소리가", en: "A Knock at the Door" },
          chapter: { ko: "1부 3장~", en: "Part 1, Chapter 3+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "키류 아파트 — 침실", en: "Kiryu's apartment — bedroom" },
          trigger: { ko: "3장 이후 자택에서 잠을 청할 때 발생", en: "Try to sleep in Kiryu's apartment after Chapter 3." },
          body: { ko: "한밤중에 문을 두드리는 수상한 인물. 키류가 직접 응대한다.", en: "Someone knocks in the middle of the night. Kiryu answers in person." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 10,
          title: { ko: "용의 해선동", en: "The Dragon's Seafood Bowl" },
          chapter: { ko: "1부 2장~", en: "Part 1, Chapter 2+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 치쿠젠 거리 북쪽", en: "Nagasugai — Chikuzen St. north" },
          trigger: { ko: "해선동 가게 앞 점주에게 말 걸기", en: "Talk to the seafood-bowl shopkeeper." },
          body: { ko: "해선동 가게의 비법 레시피를 둘러싼 소동. 신선한 재료를 골라주면 점주가 인정한다.", en: "Help the seafood-bowl owner pick out fresh ingredients to revive his shop's flavor." },
          reward: { ko: "경험치 + 회복 아이템", en: "EXP + recovery item" },
        },
        {
          number: 11,
          title: { ko: "은빛 유성", en: "Glittering Meteor" },
          chapter: { ko: "1부 2장", en: "Part 1, Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 후쿠하쿠 거리 동쪽", en: "Nagasugai — Fukuhaku St. east" },
          trigger: { ko: "2장 보스전 이후 거리에서 발생", en: "After the Chapter 2 boss fight." },
          body: { ko: "정체불명의 마스크맨이 출몰. 키류가 격투로 진위를 가린다. 미씨블.", en: "A masked figure appears. Kiryu sorts it out with fists. Missable." },
          reward: { ko: "경험치 + 마스크 장비", en: "EXP + mask accessory" },
        },
        {
          number: 12,
          title: { ko: "드래곤 마스크 다시", en: "Dragon Mask Returns" },
          chapter: { ko: "1부 4장~", en: "Part 1, Chapter 4+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 나가스가이 거리 남쪽", en: "Nagasugai — Nagasugai Ave. south" },
          trigger: { ko: "이전 마스크 관련 서브 이후 발생", en: "After the prior mask substory." },
          body: { ko: "「드래곤 마스크」를 자칭하는 인물이 다시 나타나 키류에게 도전. 결판을 낸다.", en: "The 'Dragon Mask' returns and challenges Kiryu — finish what was started." },
          reward: { ko: "경험치 + 장비", en: "EXP + accessory" },
        },
        {
          number: 13,
          title: { ko: "텐진님, 부탁해요!", en: "Tenjin-sama, Please!" },
          chapter: { ko: "1부 2장~", en: "Part 1, Chapter 2+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 나가스가이 거리 북쪽", en: "Nagasugai — Nagasugai St. north" },
          trigger: { ko: "거리의 수험생에게 말 걸기", en: "Talk to the exam-prep student on the street." },
          body: { ko: "수험생이 합격을 위해 텐진님께 빈다. 키류가 함께 신사 참배를 도와준다.", en: "A student prays for exam luck. Kiryu accompanies him to the shrine." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 14,
          title: { ko: "폭주 포장마차", en: "Runaway Food Stall" },
          chapter: { ko: "1부 2장", en: "Part 1, Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 묘에 거리 동쪽 포장마차", en: "Nagasugai — Myoe St. east food stall" },
          trigger: { ko: "2장 보스전 이후 포장마차 앞", en: "After the Chapter 2 boss fight, near the food stall." },
          body: { ko: "포장마차가 폭주(?)하며 손님을 휘말리게 한다. 미씨블 격투 이벤트.", en: "A runaway food cart drags everyone in — short missable brawl event." },
          reward: { ko: "경험치 + 회복 아이템", en: "EXP + recovery item" },
        },
        {
          number: 15,
          title: { ko: "중요한 건 면의 탄력", en: "Springiness Is Everything" },
          chapter: { ko: "1부 2장~", en: "Part 1, Chapter 2+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 라멘 포장마차 「타마사」", en: "Nagasugai — Ramen stall 'Tamasa'" },
          trigger: { ko: "타마사 포장마차에 입점하면 발생", en: "Enter the Tamasa ramen stall." },
          body: { ko: "라멘 가게 손님 컴플레인 해결. 면의 「코시」를 둘러싼 라멘 강좌가 펼쳐진다.", en: "Settle a customer complaint at the ramen stall — turns into a lecture on noodle 'koshi'." },
          reward: { ko: "경험치 + 라멘 회복 아이템", en: "EXP + ramen recovery item" },
        },
        {
          number: 16,
          title: { ko: "마크와의 재회", en: "Reunion with Mack" },
          chapter: { ko: "1부 3장~", en: "Part 1, Chapter 3+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "나가스가이 — 키류 아파트", en: "Nagasugai — Kiryu's apartment" },
          trigger: { ko: "3장 이후 아파트로 귀가", en: "Return to the apartment after Chapter 3." },
          body: { ko: "옛 친구 마크가 키류 앞에 다시 나타나 회포를 푼다.", en: "An old acquaintance, Mack, drops by Kiryu's place." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 17,
          title: { ko: "아몬", en: "Amon" },
          chapter: { ko: "최종부 최종 장", en: "Final Part, Final Chapter" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "카무로초 — 뉴 세레나", en: "Kamurocho — New Serena" },
          trigger: { ko: "전 캐릭터 서브스토리 컴플리트 후 뉴 세레나에서 봉투 수령", en: "Clear all substories for every protagonist, then pick up the letter at New Serena." },
          prereq: { ko: "5인 전원 서브스토리 컴플리트", en: "All substories cleared for all 5 protagonists" },
          body: { ko: "전설의 자객 아몬 일가가 5인 전원에게 결투를 신청. 시리즈 최강 격의 보스 러시. 미씨블 (전체 컴플 필요).", en: "The Amon assassin family challenges all five protagonists — series-trademark superboss rush. Missable (requires full completion)." },
          reward: { ko: "아몬 일가 격파 트로피 + 최강 장비", en: "Amon Clan defeat trophy + top-tier gear" },
        },
        {
          number: 18,
          title: { ko: "최고의 조미료", en: "The Finest Seasoning" },
          chapter: { ko: "최종부 1장~", en: "Final Part, Chapter 1+" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "카무로초 — 킷사텐 알프스", en: "Kamurocho — Kissaten Alps" },
          trigger: { ko: "타츠야 택시 미션 전부 클리어 후 킷사텐 알프스에서 발생", en: "Clear every Tatsuya taxi mission, then visit Kissaten Alps." },
          prereq: { ko: "타츠야 어나더 드라마 전부 클리어", en: "All Tatsuya Another Drama missions cleared" },
          body: { ko: "타츠야와의 마지막 대화. 키류 편을 마무리하는 에필로그적 서브.", en: "A final conversation with Tatsuya — an epilogue-style closer for Kiryu's chapter." },
          reward: { ko: "경험치 + 컴플리션 카운트", en: "EXP + completion credit" },
        },
      ],
    },
    {
      title: { ko: "사에지마 편 — 삿포로 츠키미노", en: "Saejima — Sapporo (Tsukimino)" },
      items: [
        {
          number: 19,
          title: { ko: "거짓과 진실", en: "Lies and Truth" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 나카츠 거리", en: "Tsukimino — Nakatsu St." },
          trigger: { ko: "카지노 결투 이후 거리에서 발생", en: "Trigger on the street after the casino fight." },
          body: { ko: "사에지마를 알아본 인물이 정보를 흘리려 한다. 진위를 가려 처리.", en: "Someone tries to leak Saejima's whereabouts — sort out who's telling the truth." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 20,
          title: { ko: "눈축제 거리예술가", en: "Snow Festival Street Performer" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 타이지 공원", en: "Tsukimino — Taiji Park" },
          trigger: { ko: "거점 합류 이후 공원에서 발생", en: "After joining the base, visit Taiji Park." },
          body: { ko: "눈축제 거리예술가가 사에지마에게 한 수 청한다. 즉석 퍼포먼스 협력.", en: "A snow-festival street performer asks Saejima to join the act on the fly." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 21,
          title: { ko: "쫓는 자, 쫓기는 자", en: "Hunter and Hunted" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 바 앰비셔스", en: "Tsukimino — Bar Ambitious" },
          trigger: { ko: "카지노 결투 이후 바에서 발생. 미씨블", en: "After the casino fight, drop by Bar Ambitious. Missable." },
          body: { ko: "사에지마를 노리는 자객 정보가 들어온다. 추적해 결판. 미씨블.", en: "Intel arrives on assassins gunning for Saejima — track them down. Missable." },
          reward: { ko: "경험치 + 장비", en: "EXP + accessory" },
        },
        {
          number: 22,
          title: { ko: "추억의 도장", en: "The Dojo of Memories" },
          chapter: { ko: "2부 1장~", en: "Part 2, Chapter 1+" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "카무로초 — 소다 도장", en: "Kamurocho — Soda Dojo" },
          trigger: { ko: "1장 이후 카무로초 소다 도장 방문", en: "Visit the Soda Dojo in Kamurocho after Chapter 1." },
          body: { ko: "옛 스승의 도장을 다시 찾은 사에지마. 제자들과 가벼운 대련.", en: "Saejima revisits his old master's dojo — light sparring with the students." },
          reward: { ko: "경험치 + 격투 능력치", en: "EXP + combat stat boost" },
        },
        {
          number: 23,
          title: { ko: "둘도 없는 장소", en: "An Irreplaceable Place" },
          chapter: { ko: "2부 1장~", en: "Part 2, Chapter 1+" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "카무로초 — 소다 도장", en: "Kamurocho — Soda Dojo" },
          trigger: { ko: "「추억의 도장」 이후 재방문", en: "After 'The Dojo of Memories', revisit the dojo." },
          prereq: { ko: "「추억의 도장」 클리어", en: "Clear 'The Dojo of Memories' first" },
          body: { ko: "도장 운영을 둘러싼 트러블. 사에지마가 직접 해결한다.", en: "Trouble around the dojo's operation — Saejima settles it personally." },
          reward: { ko: "경험치 + 장비", en: "EXP + accessory" },
        },
        {
          number: 24,
          title: { ko: "산타 사냥", en: "Santa Hunt" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 타이지 골목 서쪽", en: "Tsukimino — Taiji Alley west" },
          trigger: { ko: "거점 합류 이후 거리에서 발생", en: "After joining the base, encounter on the street." },
          body: { ko: "산타 분장의 불량배들이 행인을 위협. 사에지마가 일망타진.", en: "Santa-suit punks harass passersby — Saejima cleans them out." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 25,
          title: { ko: "눈축제 MAP", en: "Snow Festival Map" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 니시4 거리 북쪽", en: "Tsukimino — West 4th St. north" },
          trigger: { ko: "거점 합류 이후 거리에서 발생", en: "After joining the base." },
          body: { ko: "관광객에게 눈축제 지도를 안내해주는 짧은 의뢰.", en: "Guide a tourist around the snow festival map." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 26,
          title: { ko: "도시에 대한 동경", en: "Yearning for the City" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 산촌", en: "Tsukimino — Settlement" },
          trigger: { ko: "거점 합류 이후 산촌 주민과 대화", en: "After joining the base, talk to the settlement resident." },
          body: { ko: "도시로 나가고 싶어하는 산촌 청년의 고민에 사에지마가 답한다.", en: "Saejima counsels a young villager who dreams of moving to the city." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 27,
          title: { ko: "식도락 여행자", en: "The Food Traveler" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 키타코지 골목 서쪽", en: "Tsukimino — Kita-Koji Alley west" },
          trigger: { ko: "거점 합류 이후 거리에서 발생", en: "After joining the base." },
          body: { ko: "츠키미노 명물을 찾아다니는 미식가 여행객을 안내.", en: "Guide a gourmet traveler hunting Tsukimino's local specialties." },
          reward: { ko: "경험치 + 회복 아이템", en: "EXP + recovery item" },
        },
        {
          number: 28,
          title: { ko: "최강의 방한 굿즈", en: "Ultimate Winter Gear" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 츠카사 거리", en: "Tsukimino — Tsukasa St." },
          trigger: { ko: "거점 합류 이후 거리에서 발생", en: "After joining the base." },
          body: { ko: "추위에 떨고 있는 사람을 위한 최강 방한구를 찾아준다.", en: "Find the ultimate winter gear for a freezing passerby." },
          reward: { ko: "경험치 + 방한 장비", en: "EXP + winter gear" },
        },
        {
          number: 29,
          title: { ko: "풀려난 것", en: "The Released One" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 키타코지", en: "Tsukimino — Kita-Koji" },
          trigger: { ko: "거점 합류 이후 거리에서 발생", en: "After joining the base." },
          body: { ko: "산에서 풀려난 야생 곰(?)에 얽힌 소동. 사에지마의 사냥 경험이 빛난다.", en: "A wild animal loose in town — Saejima's hunting experience pays off." },
          reward: { ko: "경험치 + 사냥 능력치", en: "EXP + hunt stat" },
        },
        {
          number: 30,
          title: { ko: "성냥팔이 소녀", en: "The Little Match Girl" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 바 앰비셔스", en: "Tsukimino — Bar Ambitious" },
          trigger: { ko: "카지노 결투 이후 바 인근에서 발생. 미씨블", en: "After the casino fight, near Bar Ambitious. Missable." },
          body: { ko: "추위에 떠는 소녀가 성냥을 팔러 다닌다. 사에지마가 도와주려 하지만…. 미씨블.", en: "A girl peddles matches in the cold — Saejima tries to help, but…. Missable." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 31,
          title: { ko: "얼어붙은 거리에서", en: "In the Frozen Town" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 키타코지", en: "Tsukimino — Kita-Koji" },
          trigger: { ko: "거점 합류 이후 거리에서 발생", en: "After joining the base." },
          body: { ko: "얼어붙은 길에서 곤란을 겪는 주민을 도와준다.", en: "Help a resident in trouble on a frozen street." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 32,
          title: { ko: "미끌미끌", en: "Slip-and-Slide" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 중앙역 거리 남쪽", en: "Tsukimino — Central Station St. south" },
          trigger: { ko: "거점 합류 이후 거리에서 발생", en: "After joining the base." },
          body: { ko: "빙판길에서 잇따라 넘어지는 행인들. 사에지마가 응급처치.", en: "Pedestrians keep slipping on the ice — Saejima lends a hand." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 33,
          title: { ko: "설상의 격투기", en: "Combat on Snow" },
          chapter: { ko: "2부 4장", en: "Part 2, Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "츠키미노 — 타이지 공원 남서쪽", en: "Tsukimino — Taiji Park southwest" },
          trigger: { ko: "눈축제 준비 진행 후 발생", en: "After the snow-festival prep progresses." },
          body: { ko: "눈 위 1대1 결투를 신청해오는 무도가. 격투 결판.", en: "A martial artist challenges Saejima to a snow duel — settle it with fists." },
          reward: { ko: "경험치 + 격투 장비", en: "EXP + combat gear" },
        },
      ],
    },
    {
      title: { ko: "하루카 편 — 오사카 소텐보리 (댄스/아이돌 미니게임 기반, 전투 없음)", en: "Haruka — Osaka (Sotenbori) — dance/idol minigame, no combat" },
      items: [
        {
          number: 34,
          title: { ko: "편지", en: "The Letter" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 쇼후쿠초 서쪽", en: "Sotenbori — Shoufuku-cho west" },
          trigger: { ko: "거리의 팬에게 말 걸기. 전투 없음(아이돌 일상 이벤트)", en: "Talk to a fan on the street — no combat, idol-life event." },
          body: { ko: "어린 팬의 편지를 받아 답례한다. 아이돌 이벤트라 전투 없음.", en: "Accept a letter from a young fan and reply in person — no combat, dance/idol style." },
          reward: { ko: "팬 호감도 + 경험치", en: "Fan affection + EXP" },
        },
        {
          number: 35,
          title: { ko: "힘이 되는 것", en: "Source of Strength" },
          chapter: { ko: "3부 4장~", en: "Part 3, Chapter 4+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 다이나 체어", en: "Sotenbori — Dyna Chair" },
          trigger: { ko: "다른 서브 진행 이후 발생. 전투 없음", en: "After another substory progresses. No combat." },
          prereq: { ko: "다른 하루카 서브 진행 필요", en: "Requires another Haruka substory" },
          body: { ko: "꿈을 잃을 뻔한 후배 연습생을 격려. 댄스 레슨 협력으로 진행.", en: "Encourage a junior trainee who almost gave up — supported via dance-lesson mechanic." },
          reward: { ko: "댄스 경험치 + 트로피 진척", en: "Dance EXP + trophy progress" },
        },
        {
          number: 36,
          title: { ko: "꿈이 꺾인 뒤에", en: "After the Dream Breaks" },
          chapter: { ko: "최종부 4장", en: "Final Part, Chapter 4" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "카무로초 — 센트럴 거리", en: "Kamurocho — Central St." },
          trigger: { ko: "특정 대화 이후 발생. 전투 없음", en: "After a specific conversation. No combat." },
          body: { ko: "꿈을 잃은 동료를 다시 일으켜 세우는 이야기. 댄스 미니게임으로 연결.", en: "Lift up a peer who lost her dream — resolves through the dance minigame." },
          reward: { ko: "댄스 경험치", en: "Dance EXP" },
        },
        {
          number: 37,
          title: { ko: "평범한 생활", en: "An Ordinary Life" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 비샤몬바시", en: "Sotenbori — Bishamon Bridge" },
          trigger: { ko: "어나더 드라마(아이돌) 진행 이후. 전투 없음", en: "After the Idol Another Drama progresses. No combat." },
          prereq: { ko: "아이돌 어나더 드라마 진행", en: "Idol Another Drama in progress" },
          body: { ko: "평범한 학교생활을 동경하는 하루카의 일상 에피소드.", en: "Haruka muses on the ordinary school life she gave up." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 38,
          title: { ko: "일일 점장", en: "One-Day Manager" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 소텐보리 거리 동쪽", en: "Sotenbori — Sotenbori St. east" },
          trigger: { ko: "거리의 가게 점주와 대화. 전투 없음", en: "Talk to a shop owner. No combat." },
          body: { ko: "하루카가 일일 점장으로 매장 홍보를 도와준다. 댄스/스피치 기반.", en: "Haruka serves as one-day manager — promotion handled via dance/speech." },
          reward: { ko: "경험치 + 팬 증가", en: "EXP + fan increase" },
        },
        {
          number: 39,
          title: { ko: "소텐보리 아나운스 학원", en: "Sotenbori Announce Academy" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 분타에몬 거리", en: "Sotenbori — Buntaemon St." },
          trigger: { ko: "거리의 강사와 대화. 전투 없음", en: "Talk to the instructor. No combat." },
          body: { ko: "아나운서를 꿈꾸는 학생들에게 발성 강좌. 정답 선택지를 골라야 한다.", en: "Coach aspiring announcers — pick the right enunciation lines." },
          reward: { ko: "경험치 + 토크 능력치", en: "EXP + talk stat" },
        },
        {
          number: 40,
          title: { ko: "그루메 리포터", en: "Gourmet Reporter" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 쇼후쿠초 서쪽", en: "Sotenbori — Shoufuku-cho west" },
          trigger: { ko: "타츠야 미션 진행 후 발생. 전투 없음", en: "After Tatsuya mission progress. No combat." },
          prereq: { ko: "타츠야 미션 일부 진행", en: "Tatsuya mission progress" },
          body: { ko: "TV 그루메 리포터 체험. 음식 코멘트가 댄스/리액션 미니게임으로 처리.", en: "Try gourmet TV reporting — food commentary handled via reaction minigame." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 41,
          title: { ko: "STB99", en: "STB99" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 쇼후쿠초 서쪽", en: "Sotenbori — Shoufuku-cho west" },
          trigger: { ko: "거리의 라이벌 아이돌 멤버와 대화. 전투 없음", en: "Talk to a rival idol group on the street. No combat." },
          body: { ko: "라이벌 아이돌 그룹 STB99와의 댄스 배틀로 진행. 미씨블.", en: "Dance-battle against rival idol unit STB99. Missable." },
          reward: { ko: "댄스 경험치 + 트로피 진척", en: "Dance EXP + trophy progress" },
        },
        {
          number: 42,
          title: { ko: "바운드 스타", en: "Bound Star" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 이와이바시", en: "Sotenbori — Iwai Bridge" },
          trigger: { ko: "다리 근처 캐스팅 매니저와 대화. 전투 없음", en: "Talk to the casting agent near the bridge. No combat." },
          body: { ko: "신예 스타 발굴 캐스팅. 댄스/스피치 어필로 진행.", en: "New-star casting call — appeal via dance/speech." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 43,
          title: { ko: "빛과 그림자", en: "Light and Shadow" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 소텐보리 골목", en: "Sotenbori — Sotenbori Alley" },
          trigger: { ko: "골목에서 동료 아이돌과 대화. 전투 없음", en: "Talk to a fellow idol in the alley. No combat." },
          body: { ko: "동료 아이돌의 빛과 그림자에 관한 고민 상담.", en: "Counsel a fellow idol on the light and shadow of stardom." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 44,
          title: { ko: "마법소녀 하루카", en: "Magical Girl Haruka" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 클럽 세가", en: "Sotenbori — Club SEGA" },
          trigger: { ko: "클럽 세가 앞 팬과 대화. 전투 없음", en: "Talk to the fan in front of Club SEGA. No combat." },
          body: { ko: "마법소녀 코스프레로 거리 팬 미팅. 댄스 미니게임으로 진행.", en: "Magical-girl cosplay fan meet — runs through the dance minigame." },
          reward: { ko: "코스튬 + 팬 호감도", en: "Costume + fan affection" },
        },
        {
          number: 45,
          title: { ko: "사인회", en: "Autograph Session" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 소텐보리 거리 서쪽", en: "Sotenbori — Sotenbori St. west" },
          trigger: { ko: "거리 행사 담당자와 대화. 전투 없음", en: "Talk to the event coordinator. No combat." },
          body: { ko: "사인회에서 팬들과의 상호작용. 정답 선택으로 호감도 상승.", en: "Handle a fan autograph session — pick the right replies." },
          reward: { ko: "경험치 + 팬 호감도", en: "EXP + fan affection" },
        },
        {
          number: 46,
          title: { ko: "와타미 VS 와타민가", en: "Watami vs. Watamin-ka" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리/카무로초", en: "Sotenbori / Kamurocho" },
          trigger: { ko: "양 도시 음식점 점장과 차례로 대화. 전투 없음", en: "Talk to the managers of both restaurants in turn. No combat." },
          body: { ko: "두 라이벌 체인점의 홍보 대결. 하루카가 양쪽 모두를 위해 활약.", en: "Two rival chain restaurants face off — Haruka promotes both." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 47,
          title: { ko: "파파라치", en: "Paparazzi" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 쇼후쿠초 동쪽", en: "Sotenbori — Shoufuku-cho east" },
          trigger: { ko: "거리에서 사진 기자에게 추적당한다. 전투 없음", en: "Photographers tail Haruka on the street. No combat." },
          body: { ko: "스캔들을 노리는 파파라치를 따돌리는 추격 이벤트. 댄스/이동.", en: "Shake the paparazzi chasing a scoop — movement-based, no fights." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 48,
          title: { ko: "목표는 개그맨", en: "Aspiring Comedian" },
          chapter: { ko: "3부 2장~", en: "Part 3, Chapter 2+" },
          protagonist: { ko: "하루카", en: "Haruka" },
          location: { ko: "소텐보리 — 소텐보리 거리 동쪽", en: "Sotenbori — Sotenbori St. east" },
          trigger: { ko: "거리의 개그 지망생과 대화. 전투 없음", en: "Talk to the aspiring comedian. No combat." },
          body: { ko: "개그맨이 되고 싶다는 청년의 만담을 함께 다듬어준다.", en: "Help an aspiring comic polish his stand-up routine." },
          reward: { ko: "경험치", en: "EXP" },
        },
      ],
    },
    {
      title: { ko: "아키야마 편 — 오사카 소텐보리 + 카무로초", en: "Akiyama — Osaka (Sotenbori) + Kamurocho" },
      items: [
        {
          number: 49,
          title: { ko: "꿈을 버릴 각오", en: "Resolve to Abandon the Dream" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 쇼후쿠초", en: "Sotenbori — Shoufuku-cho" },
          trigger: { ko: "사이고전 이후 거리에서 발생", en: "Trigger on the street after the Saigo fight." },
          body: { ko: "꿈을 포기하고 빚을 갚으려는 청년에게 「돈의 사용처」를 묻는다. 미씨블.", en: "A young man wants to give up his dream to repay a loan — Akiyama questions his use of money. Missable." },
          choices: [
            { prompt: { ko: "「꿈은 포기할게요」", en: "'I'm giving up the dream.'" }, correct: { ko: "포기하지 마라", en: "Don't give up" } },
          ],
          reward: { ko: "경험치 + 회수 자금", en: "EXP + recovered cash" },
        },
        {
          number: 50,
          title: { ko: "돈과 자존심", en: "Money and Pride" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 정보꾼 메일", en: "Sotenbori — informant email" },
          trigger: { ko: "다른 서브 클리어 후 메일 수신", en: "Receive an email after other substories." },
          prereq: { ko: "다른 아키야마 서브 클리어", en: "Earlier Akiyama substories cleared" },
          body: { ko: "거액을 빌리고 잠적한 채무자를 추적해 회수.", en: "Chase down a debtor who vanished with a heavy loan." },
          reward: { ko: "경험치 + 현금", en: "EXP + cash" },
        },
        {
          number: 51,
          title: { ko: "사채업자의 방식", en: "The Lender's Way" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 이와이바시", en: "Sotenbori — Iwai Bridge" },
          trigger: { ko: "사이고전 이후 다리에서 발생", en: "After the Saigo fight, near the bridge." },
          body: { ko: "악덕 삥쟁이가 행인을 협박. 아키야마식 흥행으로 정리한다.", en: "An abusive shakedown artist preys on a passerby — Akiyama settles it his way." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 52,
          title: { ko: "신천지에서", en: "In a New World" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 소텐보리 거리 동쪽", en: "Sotenbori — Sotenbori St. east" },
          trigger: { ko: "사이고전 이후 거리에서 발생", en: "After the Saigo fight." },
          body: { ko: "소텐보리로 갓 이주한 사람이 적응에 어려움. 아키야마가 조언.", en: "A newcomer struggles to settle in Sotenbori — Akiyama advises." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 53,
          title: { ko: "천연 아이돌 만들기", en: "Making a Natural Idol" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 쇼후쿠초 남쪽", en: "Sotenbori — Shoufuku-cho south" },
          trigger: { ko: "사이고전 이후 거리에서 발생", en: "After the Saigo fight." },
          body: { ko: "어색한 아이돌 지망생에게 매력 어필을 조언. 정답을 골라야 한다.", en: "Coach an awkward idol hopeful on charm — pick the right advice." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 54,
          title: { ko: "흥정의 도", en: "The Way of Haggling" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 분타에몬 거리(서점)", en: "Sotenbori — Buntaemon St. (bookstore)" },
          trigger: { ko: "서점 앞에서 발생", en: "Encounter at the bookstore." },
          body: { ko: "서점에서 가격 흥정을 펼친다. 적절한 응수를 골라야 OK.", en: "Haggle at the bookstore — pick the right retorts." },
          reward: { ko: "경험치 + 서적", en: "EXP + book" },
        },
        {
          number: 55,
          title: { ko: "스토커", en: "Stalker" },
          chapter: { ko: "3부 4장~", en: "Part 3, Chapter 4+" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리/카무로초 — 다이나 체어 외", en: "Sotenbori / Kamurocho — Dyna Chair area" },
          trigger: { ko: "4장 이후 의뢰 수령", en: "Take the request from Chapter 4 onward." },
          body: { ko: "스토커에게 시달리는 의뢰인을 보호하고 범인을 직접 제압.", en: "Protect a stalking victim and take down the perp." },
          reward: { ko: "경험치 + 장비", en: "EXP + accessory" },
        },
        {
          number: 56,
          title: { ko: "Dance With 노파", en: "Dance With Granny" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 쇼후쿠초 서쪽", en: "Sotenbori — Shoufuku-cho west" },
          trigger: { ko: "다른 서브 진행 후 발생", en: "After another substory." },
          prereq: { ko: "다른 아키야마 서브 진행 필요", en: "Earlier Akiyama substory required" },
          body: { ko: "할머니의 인생 마지막 댄스를 함께 춰주는 아키야마식 의리.", en: "Honor an old lady's final dance — Akiyama-style sentiment." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 57,
          title: { ko: "오코노미 퍼포머", en: "Okonomi Performer" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 분타에몬 거리", en: "Sotenbori — Buntaemon St." },
          trigger: { ko: "사이고전 이후 거리에서 발생", en: "After the Saigo fight." },
          body: { ko: "오코노미야키 가게의 묘기 퍼포머와 컬래버. 손님 끌기.", en: "Team up with an okonomiyaki stunt cook to draw customers." },
          reward: { ko: "경험치 + 음식 회복", en: "EXP + food item" },
        },
        {
          number: 58,
          title: { ko: "Dancin' 아키야마", en: "Dancin' Akiyama" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 분타에몬 거리", en: "Sotenbori — Buntaemon St." },
          trigger: { ko: "사이고전 이후 거리에서 발생", en: "After the Saigo fight." },
          body: { ko: "거리에서 댄스 배틀을 신청받는다. 아키야마의 풋워크가 빛난다.", en: "A street dancer challenges Akiyama — show off the footwork." },
          reward: { ko: "경험치 + 풋워크 보너스", en: "EXP + footwork stat" },
        },
        {
          number: 59,
          title: { ko: "고집불통 아저씨의 한 마디", en: "The Stubborn Old Man Speaks" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 소텐보리 거리 동쪽", en: "Sotenbori — Sotenbori St. east" },
          trigger: { ko: "사이고전 이후 거리에서 발생", en: "After the Saigo fight." },
          body: { ko: "고집불통 노점 주인의 자존심을 살려주는 짧은 에피소드.", en: "A short episode about salvaging the pride of a stubborn vendor." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 60,
          title: { ko: "전국 미식가", en: "Nationwide Foodie" },
          chapter: { ko: "최종부 최종 장", en: "Final Part, Final Chapter" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "카무로초 — 나카도리 거리", en: "Kamurocho — Naka-do St." },
          trigger: { ko: "다른 서브 클리어 후 발생", en: "After another substory clears." },
          prereq: { ko: "다른 아키야마 서브 클리어", en: "Earlier Akiyama substory cleared" },
          body: { ko: "전국 미식을 자랑하는 손님의 입맛을 만족시켜라.", en: "Satisfy a foodie who brags about nationwide cuisine." },
          reward: { ko: "경험치 + 진귀 음식", en: "EXP + rare food" },
        },
        {
          number: 61,
          title: { ko: "남자의 위태로움", en: "A Man's Folly" },
          chapter: { ko: "최종부 2장", en: "Final Part, Chapter 2" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "카무로초 — 타이헤이 거리", en: "Kamurocho — Taihei St." },
          trigger: { ko: "카츠야와의 합류 이후 발생", en: "After meeting Katsuya." },
          body: { ko: "위험한 짓을 벌이는 남자의 뒤를 캐서 사고를 예방한다.", en: "Track a reckless man and head off disaster before it happens." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 62,
          title: { ko: "원조 교제", en: "Compensated Dating" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 비샤몬바시", en: "Sotenbori — Bishamon Bridge" },
          trigger: { ko: "사이고전 이후 다리 근처에서 발생", en: "After the Saigo fight, near the bridge." },
          body: { ko: "원조 교제 현장을 목격한 아키야마가 사정을 듣고 개입. 청소년을 보호.", en: "Witness a compensated-dating scene — step in to protect the minor." },
          reward: { ko: "경험치 + 현금", en: "EXP + cash" },
        },
        {
          number: 63,
          title: { ko: "공포의 프리쿠라", en: "The Terrifying Purikura" },
          chapter: { ko: "3부 3장", en: "Part 3, Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "소텐보리 — 소텐보리 거리 서쪽", en: "Sotenbori — Sotenbori St. west" },
          trigger: { ko: "사이고전 이후 거리에서 발생", en: "After the Saigo fight." },
          body: { ko: "프리쿠라 부스에서 발생한 소동. 아키야마가 능청스럽게 해결.", en: "A purikura booth incident — Akiyama smooth-talks his way through." },
          reward: { ko: "경험치 + 프리쿠라 사진", en: "EXP + purikura photo" },
        },
      ],
    },
    {
      title: { ko: "시나다 편 — 나고야 킨에이초", en: "Shinada — Nagoya (Kineicho)" },
      items: [
        {
          number: 64,
          title: { ko: "더러워진 마음", en: "Tainted Heart" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — M 스토어", en: "Kineicho — M Store" },
          trigger: { ko: "M 스토어 앞에서 점원과 대화", en: "Talk to the clerk in front of M Store." },
          body: { ko: "도둑질을 일삼는 손님을 목격. 시나다가 직접 잡아준다.", en: "Witness a shoplifter at the M Store — Shinada nabs the thief." },
          reward: { ko: "경험치 + 음료", en: "EXP + drink item" },
        },
        {
          number: 65,
          title: { ko: "대디·파파", en: "Daddy / Papa" },
          chapter: { ko: "4부 3장", en: "Part 4, Chapter 3" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 쿠메 거리", en: "Kineicho — Kume Ave." },
          trigger: { ko: "다른 서브 진행 후 발생", en: "After another substory progresses." },
          prereq: { ko: "다른 시나다 서브 진행 필요", en: "Earlier Shinada substory required" },
          body: { ko: "아빠를 찾는 아이의 의뢰. 시나다가 임시 아빠 노릇.", en: "A kid looks for his dad — Shinada plays substitute father." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 66,
          title: { ko: "소중한 몸", en: "Precious Body" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 쿠마가야 거리", en: "Kineicho — Kumagaya Ave." },
          trigger: { ko: "거리에서 다친 사람을 발견", en: "Find an injured pedestrian on the street." },
          body: { ko: "다친 사람을 병원까지 호송. 시나다의 다정함이 드러난다.", en: "Escort an injured person to a clinic — Shinada's softer side shows." },
          reward: { ko: "경험치 + 회복 아이템", en: "EXP + recovery item" },
        },
        {
          number: 67,
          title: { ko: "사장님, 놀까요?", en: "Wanna Play, Boss?" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 이초초 거리", en: "Kineicho — Ichoucho St." },
          trigger: { ko: "거리의 호객꾼에게 말 걸기", en: "Talk to the street tout." },
          body: { ko: "사기성 호객을 일삼는 일당을 시나다가 정리. 미씨블.", en: "Clean out a scam-tout crew. Missable." },
          choices: [
            { prompt: { ko: "「사장님, 놀까요?」", en: "'Wanna play, boss?'" }, correct: { ko: "거절한다", en: "Refuse" } },
          ],
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 68,
          title: { ko: "심에 맞춰 쳐라", en: "Swing for the Core" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 배팅 센터", en: "Kineicho — Batting Center" },
          trigger: { ko: "배팅 센터에 입점", en: "Enter the batting center." },
          body: { ko: "타격 코칭 의뢰. 시나다의 전직 프로 야구 실력으로 풀어낸다.", en: "Coach hitting using Shinada's ex-pro experience — opens the batting minigame." },
          reward: { ko: "배팅 미니게임 해금 + 능력치", en: "Batting minigame unlock + stat boost" },
        },
        {
          number: 69,
          title: { ko: "시나다의 취업활동", en: "Shinada's Job Hunt" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 소데 거리", en: "Kineicho — Sode St." },
          trigger: { ko: "소데 거리 구인 게시판 앞", en: "Stand at the job board on Sode St." },
          body: { ko: "백수 시나다가 일자리를 찾는다. 면접 응대 선택지를 통과해야 OK.", en: "Out-of-work Shinada hunts for a job — pick the right interview answers." },
          choices: [
            { prompt: { ko: "「자기 PR 한 말씀」", en: "'A word about yourself.'" }, correct: { ko: "솔직하게 말한다", en: "Speak honestly" } },
          ],
          reward: { ko: "경험치 + 현금", en: "EXP + cash" },
        },
        {
          number: 70,
          title: { ko: "체인지", en: "Change" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 소데 거리", en: "Kineicho — Sode St." },
          trigger: { ko: "거리에서 손님 트러블 목격", en: "Witness customer trouble on Sode St." },
          body: { ko: "호스티스의 「체인지」 요구로 시작된 가벼운 트러블 해결.", en: "Settle a light scuffle that started with a hostess 'change' request." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 71,
          title: { ko: "미짱의 일", en: "Mi-chan's Job" },
          chapter: { ko: "4부 4장~", en: "Part 4, Chapter 4+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 배팅 센터", en: "Kineicho — Batting Center" },
          trigger: { ko: "배팅 센터 점장 미짱과의 후속 의뢰", en: "Follow-up request from Mi-chan at the batting center." },
          body: { ko: "배팅 센터 점장 미짱의 부탁으로 가게의 문제를 해결.", en: "Help Mi-chan resolve trouble at the batting center." },
          reward: { ko: "경험치 + 배팅 장비", en: "EXP + bat gear" },
        },
        {
          number: 72,
          title: { ko: "원고 셔플", en: "Manuscript Shuffle" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 고쇼쿠 거리 동쪽", en: "Kineicho — Goshoku St. east" },
          trigger: { ko: "거리의 작가 지망생과 대화", en: "Talk to the aspiring writer." },
          body: { ko: "뒤죽박죽 섞인 원고를 정리해주는 의뢰. 정답 순서로 골라야 OK.", en: "Reorder a shuffled manuscript — pick the correct sequence." },
          reward: { ko: "경험치 + 서적", en: "EXP + book" },
        },
        {
          number: 73,
          title: { ko: "특별한 한 끼", en: "A Special Meal" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 오벌 스테이지", en: "Kineicho — Oval Stage" },
          trigger: { ko: "오벌 스테이지 인근에서 발생", en: "Encounter near the Oval Stage." },
          body: { ko: "야구장 단골을 위한 특별한 한 끼를 찾아준다.", en: "Find a regular fan a 'special meal' near the ballpark." },
          reward: { ko: "경험치 + 음식 회복", en: "EXP + food item" },
        },
        {
          number: 74,
          title: { ko: "노련한 스카우터의 눈", en: "The Veteran Scout's Eye" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 이초초 거리 동쪽", en: "Kineicho — Ichoucho St. east" },
          trigger: { ko: "노년 스카우터와 대화", en: "Talk to the veteran scout." },
          body: { ko: "야구 유망주 발굴을 도와주는 시나다. 본인의 야구 인생도 돌아본다.", en: "Help a scout spot a promising hitter — Shinada reflects on his own career." },
          reward: { ko: "경험치 + 야구 능력치", en: "EXP + batting stat" },
        },
        {
          number: 75,
          title: { ko: "스쿠프 사진", en: "Scoop Photo" },
          chapter: { ko: "4부 3장", en: "Part 4, Chapter 3" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 혼진초 거리 동쪽", en: "Kineicho — Honjincho St. east" },
          trigger: { ko: "클리닉을 나온 직후 거리에서 발생", en: "Trigger on the street after leaving the clinic." },
          body: { ko: "유명인의 스쿠프 사진을 둘러싼 사기. 시나다가 진상을 파헤친다. 미씨블.", en: "Scam built around a celebrity 'scoop photo' — Shinada sniffs out the truth. Missable." },
          reward: { ko: "경험치 + 현금", en: "EXP + cash" },
        },
        {
          number: 76,
          title: { ko: "깨끗한 한 표", en: "A Clean Vote" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 오벌 스테이지", en: "Kineicho — Oval Stage" },
          trigger: { ko: "선거 운동 중인 후보자와 대화", en: "Talk to the campaigning candidate." },
          body: { ko: "지역 선거 캠페인을 도와준다. 깨끗한 선거 운동인지 확인.", en: "Help a clean-campaign candidate in the local election." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 77,
          title: { ko: "편의점 점원 시나다", en: "Shinada the Convenience Store Clerk" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 오비이타구미 거리", en: "Kineicho — Obiitagumi St." },
          trigger: { ko: "다른 서브 진행 후 점장과 대화", en: "After another substory, talk to the store manager." },
          prereq: { ko: "다른 시나다 서브 진행", en: "Earlier Shinada substory required" },
          body: { ko: "편의점 점원 알바 체험. 손님 응대를 통과해야 OK.", en: "Try a shift as a convenience-store clerk — handle customers correctly." },
          reward: { ko: "경험치 + 알바비", en: "EXP + part-time wages" },
        },
        {
          number: 78,
          title: { ko: "일확천금을 노려라", en: "Aim for the Jackpot" },
          chapter: { ko: "4부 2장~", en: "Part 4, Chapter 2+" },
          protagonist: { ko: "시나다", en: "Shinada" },
          location: { ko: "킨에이초 — 고쇼쿠 거리", en: "Kineicho — Goshoku St." },
          trigger: { ko: "거리의 도박꾼과 대화", en: "Talk to the street gambler." },
          body: { ko: "한방을 노리는 도박꾼과 함께 일확천금에 도전. 시나다 특유의 운빨이 시험대.", en: "Chase a jackpot with a street gambler — Shinada's trademark luck on the line." },
          reward: { ko: "경험치 + 거액 현금", en: "EXP + big cash payout" },
        },
      ],
    },
  ],
};
