import type { SubstoriesData } from "./types";

export const yakuza4Substories: SubstoriesData = {
  appId: 1105500,
  summary: {
    ko: "총 63건 — 아키야마 16 / 사에지마 15 / 타니무라 16 / 키류 16(아몬 포함). 4명의 주인공이 챕터별로 교대 진행되며, 한 번 챕터를 넘기면 해당 캐릭터의 미완료 서브는 최종부의 「과거 회상」(스카이 파이낸스·은신처·고향·뉴 세레나)에서만 다시 열 수 있으므로 챕터 안에서 정리하는 것이 안전합니다. 캬바쿠라·용궁성 도박·낚시 등 미니게임 잠금 해제와 연결되는 서브가 많으니 우선순위가 높습니다.",
    en: "63 substories — Akiyama 16 / Saejima 15 / Tanimura 16 / Kiryu 16 (incl. Amon). Each protagonist's substories are gated to their own part; once their chapter ends you can only revisit unfinished ones via the 'past' seat in Sky Finance / hideout / Furusato / New Serena during the final part, so clear them in-chapter when possible. Many gate minigame unlocks (Cabaret, Ryugu Castle gambling, fishing).",
  },
  source: { label: "kouryakutsushin.com — 龍が如く4 サブストーリー攻略", url: "https://kouryakutsushin.com/ryu4/" },
  groups: [
    {
      title: { ko: "아키야마 편 — 챕터 2~4", en: "Akiyama — Chapter 2~4" },
      items: [
        {
          number: 1,
          title: { ko: "구조조정의 대가", en: "The Price of an Education" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "스카이 파이낸스 → 시치후쿠 거리 서쪽 「우마모토」 앞 → 아동공원", en: "Sky Finance → Shichifuku St. west (Umamoto soba) → Children's Park" },
          trigger: { ko: "챕터 2 시작 시 하나의 전화로 자동 발생(스토리 강제)", en: "Auto-triggers via Hana's call at the start of Chapter 2." },
          body: {
            ko: "파라다이스 광고판을 빌미로 삥쟁이 일당을 단속하는 의뢰. 스카이 파이낸스에서 세 가지 대답을 모두 골라야 다음 단계로 넘어갑니다.",
            en: "Track down the punks shaking down the Paradise billboard crew. Pick all three dialogue options back at Sky Finance to advance.",
          },
          reward: { ko: "「액션 스타 비전록」 + 경험치 5000", en: "Action Star Legacy + 5000 EXP" },
        },
        {
          number: 2,
          title: { ko: "제자 지원", en: "The Apprentice" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "나오미의 저택 앞", en: "Outside Naomi's mansion" },
          trigger: { ko: "「구조조정의 대가」 클리어 후 발생", en: "Clear 'The Price of an Education' first." },
          body: { ko: "스카이 파이낸스의 제자가 되겠다는 청년을 시험. 후속 「제자의 반항」「아내의 마음」으로 이어집니다.", en: "A young man begs to be Akiyama's apprentice. Starts a chain into 'Disciple's Rebellion' and 'A Wife's Wish'." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 3,
          title: { ko: "맛집 리포터", en: "Gourmet Reporter" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "코토부키 약국(타이헤이 거리 동쪽) → 챔피언 거리 「아텐시」", en: "Kotobuki Pharmacy (Taihei E.) → Atenshi (Champion St.)" },
          trigger: { ko: "약국 앞에서 잡지 기자에게 말 걸기", en: "Talk to the magazine reporter near Kotobuki Pharmacy." },
          body: { ko: "리포터를 위해 「진짜 맛있는 가게」를 안내해야 합니다. 야키니쿠·라멘 순서로 정확히 지목해야 보상 정상 획득.", en: "Guide the reporter to the genuinely good joints. Order yakiniku then ramen with the right picks." },
          choices: [
            { prompt: { ko: "「야키니쿠 어디가 좋아요?」", en: "'Best yakiniku?'" }, correct: { ko: "칸라이 → 최상급 등심 → 최상급 갈비살", en: "Kanrai → Premium loin → Premium short rib" } },
            { prompt: { ko: "「라멘은요?」", en: "'And ramen?'" }, correct: { ko: "큐슈 이치반보시 → 하카타 진한 돈코츠 → 큐슈 멘타이코", en: "Kyushu Ichibanboshi → Rich Hakata tonkotsu → Kyushu mentaiko" } },
          ],
          reward: { ko: "10만엔 + 다이아몬드 + 경험치 5000", en: "¥100,000 + Diamond + 5000 EXP" },
        },
        {
          number: 4,
          title: { ko: "삥쟁이 지도", en: "Catch Master" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "엘리제(타이헤이 거리)", en: "Elise (Taihei St.)" },
          trigger: { ko: "엘리제 앞 캐치 남자에게 말 걸기", en: "Talk to the catch tout in front of Elise." },
          body: { ko: "5분 안에 나카미치 거리에서 여성 손님 3명 이상을 캐치하는 미니 챌린지.", en: "Scout 3+ women on Nakamichi St. within 5 minutes." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 5,
          title: { ko: "오타쿠 개조 계획", en: "Otaku Makeover" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "엘리제 앞 → 밀레니엄 타워", en: "Elise → Millennium Tower" },
          trigger: { ko: "엘리제 캐치 의뢰 후 오타쿠 청년에게 말 걸기", en: "Talk to the otaku after the catch substory." },
          body: { ko: "고백을 앞둔 오타쿠 청년을 코디. 마지막 조언에서 진심이 통하는 답을 골라야 합니다.", en: "Help an otaku confess. The advice line at the end is the make-or-break choice." },
          choices: [
            { prompt: { ko: "「마지막 조언 한 마디」", en: "'Final piece of advice'" }, correct: { ko: "분위기를 읽고 들어줘라", en: "Read the mood and listen" } },
          ],
          reward: { ko: "「반짝반짝 러브샤인」 + 경험치 5000", en: "Kirakira Love Shine + 5000 EXP" },
        },
        {
          number: 6,
          title: { ko: "돈의 사용처", en: "What Money Buys" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "마츠야(타이헤이 서) → 스시 긴(쇼와 서) → 르 마르셰 → ADAM", en: "Matsuya → Sushi Gin → Le Marche → ADAM" },
          trigger: { ko: "타이헤이 거리에서 융자 신청자에게 말 걸기", en: "Talk to the loan applicant on Taihei St." },
          body: { ko: "거액을 빌리려는 손님의 「돈 쓰임새」를 미행해 가치를 판단. 「3000만의 행방」으로 이어집니다.", en: "Follow the applicant to verify how he spends the loan. Leads into '30 Million Trail'." },
          reward: { ko: "부적 + 경험치 3000", en: "Amulet + 3000 EXP" },
        },
        {
          number: 7,
          title: { ko: "캬바쿠라 공략법 · 아키야마 편", en: "Cabaret Strategy — Akiyama" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "MEB · Jewel · SHINE · Cue's Bar", en: "MEB / Jewel / SHINE / Cue's Bar" },
          trigger: { ko: "큐즈 바에서 미나사와에게 말 걸기", en: "Talk to Minasawa at Cue's Bar." },
          body: { ko: "캬바쿠라 미니게임 본격 해금용. 각 호스티스의 취향에 맞춰 동반·선물·대화를 골라야 합니다.", en: "Unlocks the full Cabaret minigame. Match each hostess's taste in drink, gift, and talk." },
          choices: [
            { prompt: { ko: "리오 동반 선택", en: "Rio's preferences" }, correct: { ko: "샴페인 로제 · 강아지 · 섹시 탤런트", en: "Rosé champagne / dog / sexy talent" } },
            { prompt: { ko: "미즈타니 노아 동반 선택", en: "Mizutani Noa" }, correct: { ko: "발레 · 치킨 바스켓 · 능숙한 운전수", en: "Ballet / chicken basket / smooth driver" } },
            { prompt: { ko: "아이하라 엘레나 동반 선택", en: "Aihara Elena" }, correct: { ko: "오라니야 부유층 · 교토 · 야마자키 12년", en: "Old-money Oraniyan / Kyoto / Yamazaki 12-yr" } },
          ],
          reward: { ko: "9만엔 + 경험치 5000", en: "¥90,000 + 5000 EXP" },
        },
        {
          number: 8,
          title: { ko: "3000만의 행방", en: "Where the 30 Million Went" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "스카이 파이낸스 → 타이헤이 코인로커 → 시치후쿠 서쪽 아동공원 → 쇼와·센료·극장 앞·호텔가", en: "Sky Finance → Taihei locker → Shichifuku park → Showa/Senryo/Theater/Hotel Dist." },
          trigger: { ko: "「돈의 사용처」 클리어 후 발생", en: "Clear 'What Money Buys' first." },
          body: { ko: "거액을 빌려간 손님의 행방을 쫓는 추적극. 첫 분기에서 사정을 듣는 쪽을 골라야 후속 「하나의 우울」이 열립니다.", en: "Hunt down the borrower. The opening choice decides whether the chain (→ 'Hana's Melancholy') continues." },
          choices: [
            { prompt: { ko: "「어떻게 할까?」", en: "'How should we proceed?'" }, correct: { ko: "일단 사정을 듣는다", en: "Hear him out first" } },
          ],
          reward: { ko: "골드 플레이트 + 경험치 5000", en: "Gold Plate + 5000 EXP" },
        },
        {
          number: 9,
          title: { ko: "하나의 우울", en: "Hana's Melancholy" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "MEB 부근 → 나카미치 거리 → 극장 앞 광장 → 엘리제 부근 → 핑크 거리", en: "MEB area → Nakamichi → Theater Plaza → Elise → Pink St." },
          trigger: { ko: "「3000만의 행방」 클리어", en: "Clear 'Where the 30 Million Went'." },
          body: { ko: "하나의 기분을 풀어주기 위한 데이트. 4개 대화 선택지를 순서 무관 전부 골라야 종료됩니다.", en: "Cheer up Hana around town. Pick all four dialogue options (order doesn't matter) to finish." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 10,
          title: { ko: "위조지폐", en: "Counterfeit Bills" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "스시 긴 → 폿포 나카미치 → 볼케이노 → 파크 앞 → 핑크 거리 → 부두(야간)", en: "Sushi Gin → Poppo Nakamichi → Volcano → Park-front → Pink St. → Wharf (night)" },
          trigger: { ko: "「하나의 우울」 클리어 후 발생", en: "Clear 'Hana's Melancholy'." },
          body: { ko: "위조지폐 유통 경로 추적. 챕터 4 「가짜에 주의」 후속편으로 이어집니다.", en: "Trace counterfeits across town. Sets up the Chapter 4 sequel 'Beware of Counterfeits'." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 11,
          title: { ko: "제자의 반항", en: "Disciple's Rebellion" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "극장 앞 광장 · 스카이 파이낸스 · M-Store 옆 흰 건물", en: "Theater Plaza / Sky Finance / white building by M-Store" },
          trigger: { ko: "「제자 지원」 클리어", en: "Clear 'The Apprentice'." },
          body: { ko: "독립을 외치는 제자의 진의를 확인. 후속 「아내의 마음」으로 이어집니다.", en: "Track down the rebellious apprentice. Leads into 'A Wife's Wish'." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 12,
          title: { ko: "아내의 마음", en: "A Wife's Wish" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "타이헤이 거리 엘리제 입구", en: "Taihei St. — Elise entrance" },
          trigger: { ko: "「제자의 반항」 클리어", en: "Clear 'Disciple's Rebellion'." },
          body: { ko: "제자 부부의 사정을 듣고 마무리. 「리트라이」 챕터 4편으로 이어집니다.", en: "Resolve the apprentice's marriage trouble. Sets up the Chapter 4 finale 'Retry'." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 13,
          title: { ko: "FX로 돈 벌자", en: "Get Rich with FX" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "센료 거리", en: "Senryo Ave." },
          trigger: { ko: "스카이 파이낸스에 도착한 권유 메일에서 발생", en: "An email arrives at Sky Finance — no prior substory required." },
          body: {
            ko: "FX 투자 사기꾼과의 대면. 세 차례 대화에서 모두 정답을 골라야 사기를 막고 보상을 챙길 수 있는 미스블 후보.",
            en: "Sit down with an FX-pitching scammer. Pick the right line in all three exchanges to refuse the scam and pocket the reward.",
          },
          choices: [
            { prompt: { ko: "1차 질문", en: "First question" }, correct: { ko: "내가 돈을 내는 의미는…", en: "'What it means for me to pay…'" } },
            { prompt: { ko: "2차 질문", en: "Second question" }, correct: { ko: "무슨 일이 있어도…", en: "'No matter what happens…'" } },
            { prompt: { ko: "3차 질문", en: "Third question" }, correct: { ko: "완전 사기 상품이군", en: "'That's a total scam product'" } },
          ],
          reward: { ko: "8만엔 + 경험치 2000", en: "¥80,000 + 2000 EXP" },
        },
        {
          number: 14,
          title: { ko: "리트라이", en: "Retry" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "텐카이치 거리 남쪽 일대", en: "Tenkaichi St. south district" },
          trigger: { ko: "「아내의 마음」 클리어", en: "Clear 'A Wife's Wish'." },
          body: { ko: "제자 부부의 재도전을 돕는 챕터 4 마무리편.", en: "Help the apprentice couple try again — finishes the chain." },
          reward: { ko: "경험치 10000", en: "10000 EXP" },
        },
        {
          number: 15,
          title: { ko: "유사품에 주의", en: "Beware of Counterfeits" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "타이헤이 · 극장 앞 · 파크 앞 · 가짜 스카이 파이낸스", en: "Taihei / Theater-front / Park-front / fake Sky Finance" },
          trigger: { ko: "「위조지폐」 클리어", en: "Clear 'Counterfeit Bills'." },
          body: { ko: "가짜 스카이 파이낸스 사칭범 검거. 마지막에 보스급 전투가 있으니 회복 아이템을 챙겨두세요.", en: "Take down the gang impersonating Sky Finance. Boss fight at the end — bring healing." },
          reward: { ko: "초고압 배터리 + 경험치 5000", en: "Super High-Voltage Battery + 5000 EXP" },
        },
        {
          number: 16,
          title: { ko: "캬바쿠라 수행", en: "Cabaret Training" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "아키야마", en: "Akiyama" },
          location: { ko: "엘리제 앞", en: "Outside Elise" },
          trigger: { ko: "「오타쿠 개조 계획」 클리어", en: "Clear 'Otaku Makeover'." },
          body: { ko: "캬바쿠라 신인 호스티스의 접객 지도. 4개 접객 라인에서 모두 손님 마음을 읽는 답을 선택.", en: "Coach a rookie hostess. Pick the customer-first answer in all four lines." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
      ],
    },
    {
      title: { ko: "사에지마 편 — 챕터 3~4", en: "Saejima — Chapter 3~4" },
      items: [
        {
          number: 17,
          title: { ko: "누나와 동생 1", en: "Sister and Brother 1" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "카무로 지하상가", en: "Kamurocho Underground" },
          trigger: { ko: "소지금 3000엔 이상으로 지하상가 진입 시 소년과 충돌 이벤트", en: "Enter the underground with ¥3000+ to bump into the boy." },
          body: {
            ko: "유산을 노리는 누나를 찾는 소년을 돕는 4부작 체인의 시작. 노숙자에게 1000엔을 주고 정보를 사야 진행됩니다.",
            en: "First entry in the four-part 'Sister and Brother' chain. Pay the homeless informant ¥1,000 to advance.",
          },
          choices: [
            { prompt: { ko: "「정보를 살래?」", en: "'Wanna buy info?'" }, correct: { ko: "1000엔 지불", en: "Pay ¥1,000" } },
          ],
          reward: { ko: "고급 보석 + 경험치 5000", en: "High-grade stone + 5000 EXP" },
        },
        {
          number: 18,
          title: { ko: "낚아 올린 것은", en: "What I Caught" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "부두", en: "Wharf" },
          trigger: { ko: "부두에서 낚시꾼에게 말 걸기", en: "Talk to the fisherman at the wharf." },
          body: { ko: "낚시 미니게임 입문 격 서브. 미끼를 사서 세 번 낚으면 진행, 마지막에 야쿠자 난입 전투.", en: "Intro to the fishing minigame. Buy bait, land three fish, then take out the yakuza who barge in." },
          reward: { ko: "루비 + 경험치 5000", en: "Ruby + 5000 EXP" },
        },
        {
          number: 19,
          title: { ko: "고양이와 노숙자", en: "Cat and Homeless Man" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "극장 지하 B1", en: "Theater basement B1" },
          trigger: { ko: "극장 지하에서 고양이를 찾는 노숙자에게 말 걸기", en: "Talk to the homeless man searching for his cat." },
          body: {
            ko: "잃어버린 고양이를 찾아주는 의뢰. 미스블: 마지막에 5만엔을 요구받을 때 「건네지 않는다」를 골라야 「복수의 이유」 후속이 열립니다.",
            en: "Find the lost cat. Missable: when asked for ¥50,000 at the end, refuse — handing the money over kills the follow-up 'Reason for Revenge'.",
          },
          choices: [
            { prompt: { ko: "「도와줄래?」", en: "'Help me?'" }, correct: { ko: "해본다", en: "I'll try" } },
            { prompt: { ko: "「뭘 줄까?」", en: "'What should I give it?'" }, correct: { ko: "우유", en: "Milk" } },
            { prompt: { ko: "「5만엔 빌려줘」", en: "'Lend me ¥50,000'" }, correct: { ko: "건네지 않는다", en: "Refuse" } },
          ],
          reward: { ko: "고양이 열쇠 + 경험치 5000", en: "Cat key + 5000 EXP" },
        },
        {
          number: 20,
          title: { ko: "쫓기는 여자", en: "The Hunted Woman" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "카무로쵸 시내(다발 위치)", en: "Multiple Kamurocho spots" },
          trigger: { ko: "거리에서 쫓기는 여자와 충돌 이벤트", en: "Bump into the fleeing woman on the streets." },
          body: { ko: "여자를 쫓는 야쿠자들을 순서대로 격파. 후속 「부모와 자식」으로 이어집니다.", en: "Take down each wave of pursuers in turn. Sets up 'Parent and Child'." },
          reward: { ko: "플레이어의 말 + 경험치 5000", en: "Player's piece + 5000 EXP" },
        },
        {
          number: 21,
          title: { ko: "잔협", en: "Lingering Chivalry" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "시치후쿠 거리 아동공원 앞", en: "Shichifuku St. — children's park" },
          trigger: { ko: "공원 앞에서 카타기리를 도울지 묻는 이벤트", en: "Help Katagiri when prompted at the park." },
          body: { ko: "옛 협객 카타기리의 마지막 결투 보조. 협력 콤보로 적을 정리.", en: "Back up the old chivalrous fighter Katagiri in his last brawl." },
          reward: { ko: "고대 챔피언의 비전록 + 경험치 2000", en: "Ancient Champion's Legacy + 2000 EXP" },
        },
        {
          number: 22,
          title: { ko: "용궁성 용심봉(보디가드)", en: "Ryugu Castle Bodyguard" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "공원 앞 거리 — 용궁성 입구", en: "Park-front St. — Ryugu Castle entrance" },
          trigger: { ko: "「누나와 동생 1」 클리어", en: "Clear 'Sister and Brother 1'." },
          body: { ko: "지하 카지노 용궁성의 진상 손님을 처리해 출입 권한을 획득.", en: "Handle a rowdy patron to earn entry into the Ryugu Castle casino." },
          reward: { ko: "카지노 칩 300개 + 용궁성 이용 가능 + 경험치 5000", en: "300 casino chips + Ryugu Castle unlocked + 5000 EXP" },
        },
        {
          number: 23,
          title: { ko: "복수의 이유", en: "Reason for Revenge" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "극장 앞 거리", en: "Theater-front St." },
          trigger: { ko: "「고양이와 노숙자」에서 돈을 건네지 않고 클리어", en: "Clear 'Cat and Homeless Man' WITHOUT giving the ¥50,000." },
          body: {
            ko: "노숙자에게 친절했던 진실이 드러나는 후속편. 이구치 일당과의 다단 전투가 핵심.",
            en: "The truth behind the homeless man's kindness. Multi-stage brawl vs. Iguchi's crew.",
          },
          reward: { ko: "고급 우산 + 철못 + 뱅커의 말 + 경험치 5000", en: "Luxury umbrella + Iron nail + Banker's piece + 5000 EXP" },
        },
        {
          number: 24,
          title: { ko: "보디가드", en: "Bodyguard" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "밀레니엄 타워 주차장", en: "Millennium Tower parking" },
          trigger: { ko: "「용궁성 용심봉」 클리어", en: "Clear 'Ryugu Castle Bodyguard'." },
          body: { ko: "VIP를 노리는 자객 3인조를 순차 격파. 히트 게이지 관리가 핵심.", en: "Protect a VIP from three assassins. Manage your heat gauge." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 25,
          title: { ko: "누나와 동생 2", en: "Sister and Brother 2" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "로쿠란소 앞 및 옥상", en: "Rokuransō entrance & rooftop" },
          trigger: { ko: "「보디가드」 클리어", en: "Clear 'Bodyguard'." },
          body: { ko: "소년의 누나를 추적해 일당과 옥상에서 결전.", en: "Chase down the sister's gang to a rooftop showdown." },
          reward: { ko: "용의 눈 + 경험치 5000", en: "Dragon's Eye + 5000 EXP" },
        },
        {
          number: 26,
          title: { ko: "부모와 자식", en: "Parent and Child" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "카무로 극장 → 시치후쿠 공원", en: "Kamuro Theater → Shichifuku Park" },
          trigger: { ko: "「쫓기는 여자」 클리어", en: "Clear 'The Hunted Woman'." },
          body: { ko: "스토커에게 시달리는 모자를 보호. 첫 분기에서 「사정을 듣는다」 선택 후 보디가드 수락.", en: "Protect a mother and son from a stalker. Pick 'Listen' then accept the bodyguard role." },
          choices: [
            { prompt: { ko: "「어떻게 할래?」", en: "'What now?'" }, correct: { ko: "사정을 듣는다", en: "Hear them out" } },
          ],
          reward: { ko: "다이아몬드 + 경험치 5000", en: "Diamond + 5000 EXP" },
        },
        {
          number: 27,
          title: { ko: "연설 방해", en: "Disrupt the Speech" },
          chapter: { ko: "챕터 3", en: "Chapter 3" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "밀레니엄 타워 앞", en: "Millennium Tower plaza" },
          trigger: { ko: "「부모와 자식」 클리어", en: "Clear 'Parent and Child'." },
          body: {
            ko: "선거 연설을 방해하는 야유꾼을 군중 속에서 색출. 최대 3회 오답까지 허용되므로 신중하게.",
            en: "Spot the hecklers in the crowd. Up to three wrong picks allowed — choose carefully.",
          },
          choices: [
            { prompt: { ko: "「감시 부탁할 수 있을까?」", en: "'Could you watch for me?'" }, correct: { ko: "내가 감시해주지", en: "I'll keep an eye out" } },
          ],
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 28,
          title: { ko: "저마다의 25년", en: "Each One's 25 Years" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "극장 지하 ~ 시치후쿠 거리", en: "Theater B1 ~ Shichifuku St." },
          trigger: { ko: "「누나와 동생 2」 클리어", en: "Clear 'Sister and Brother 2'." },
          body: { ko: "25년 전 사건의 또 다른 당사자와 재회. 「누나와 동생 3」으로 직결.", en: "Reunite with another party from 25 years ago. Bridges into 'Sister and Brother 3'." },
          reward: { ko: "경험치 3000", en: "3000 EXP" },
        },
        {
          number: 29,
          title: { ko: "누나와 동생 3", en: "Sister and Brother 3" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "사이노카와라(지하 투기장)", en: "Sai no Kawara underground arena" },
          trigger: { ko: "「저마다의 25년」 클리어", en: "Clear 'Each One's 25 Years'." },
          body: { ko: "「무기 마스터 GP」에서 우승해야 진행. 무기 활용이 핵심.", en: "Win the Weapon Master GP to advance. Lean into weapon combat." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 30,
          title: { ko: "누나와 동생 4", en: "Sister and Brother 4" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "극장 지하 ~ 극장 광장 뒷편", en: "Theater B1 ~ rear of Theater Plaza" },
          trigger: { ko: "「누나와 동생 3」 클리어", en: "Clear 'Sister and Brother 3'." },
          body: { ko: "체인의 마무리. 야쿠자 3연전을 돌파해야 합니다.", en: "Closes the chain with three back-to-back yakuza fights." },
          reward: { ko: "용의 인장 + 경험치 10000", en: "Dragon Seal + 10000 EXP" },
        },
        {
          number: 31,
          title: { ko: "녹색 그림자", en: "Green Shadow" },
          chapter: { ko: "최종부", en: "Final" },
          protagonist: { ko: "사에지마", en: "Saejima" },
          location: { ko: "극장 일대(에스컬레이터·지하·아동공원)", en: "Theater area (escalator / B1 / kids' park)" },
          trigger: { ko: "야간에 극장 부근에서 자동 발생", en: "Auto-triggers at night near the Theater." },
          body: { ko: "녹색 옷의 추적자를 잡아 사건 종결. 야간 한정.", en: "Track the green-clad pursuer. Night-only." },
          reward: { ko: "스턴건 + 경험치 5000", en: "Stun gun + 5000 EXP" },
        },
      ],
    },
    {
      title: { ko: "타니무라 편 — 챕터 1~4", en: "Tanimura — Chapter 1~4" },
      items: [
        {
          number: 32,
          title: { ko: "도박꾼의 블루스", en: "Gambling Junkie Blues" },
          chapter: { ko: "챕터 1", en: "Chapter 1" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "아시아 거리 서쪽 입구 외 다발", en: "Asia St. west entrance + various" },
          trigger: { ko: "기지(고향) 도착 후 자동 발생", en: "Auto after reaching the Furusato base." },
          body: { ko: "타니무라 편의 용궁성 카지노 해금 트리거. 도박꾼을 추적해 정리.", en: "Unlocks Ryugu Castle for Tanimura. Chase down a degenerate gambler." },
          reward: { ko: "「대·대·대폭조!!」 + 5000엔 + 경험치 5000 + 용궁성 해금", en: "Massive Fishing Trophy + ¥5,000 + 5000 EXP + Ryugu unlocked" },
        },
        {
          number: 33,
          title: { ko: "애인이 되어주실래요?", en: "Be My Lover?" },
          chapter: { ko: "챕터 1", en: "Chapter 1" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "아시아 거리 — 고향", en: "Asia St. — Furusato" },
          trigger: { ko: "「도박꾼의 블루스」 클리어", en: "Clear 'Gambling Junkie Blues'." },
          body: {
            ko: "필리핀 여성의 부탁을 받는 미스블 후보. 「알았어, 애인이 되어줄게」를 골라야 보상이 풀립니다.",
            en: "Missable: pick the agree line to unlock the rewards.",
          },
          choices: [
            { prompt: { ko: "「애인이 되어주실래요?」", en: "'Will you be my lover?'" }, correct: { ko: "알았어, 애인이 되어줄게", en: "Sure, I'll be your lover" } },
          ],
          reward: { ko: "순간 냉각제 MAX + 신수의 나뭇조각 + 5000엔 + 경험치 5000", en: "Instant Cooler MAX + Divine Wood Chip + ¥5,000 + 5000 EXP" },
        },
        {
          number: 34,
          title: { ko: "캬바쿠라 공략법 · 타니무라 편", en: "Cabaret Strategy — Tanimura" },
          chapter: { ko: "챕터 1", en: "Chapter 1" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "MEB 앞 외 캬바쿠라", en: "Outside MEB + cabaret clubs" },
          trigger: { ko: "기지 도착 후 발생", en: "Auto after reaching base." },
          body: { ko: "타니무라용 캬바쿠라 미니게임 가이드. 호스티스 퀴즈에 정답을 내야 풀 해금.", en: "Cabaret intro for Tanimura. Answer the hostess trivia correctly." },
          reward: { ko: "6만엔 + 경험치 5000", en: "¥60,000 + 5000 EXP" },
        },
        {
          number: 35,
          title: { ko: "미팅 가자", en: "Let's Go to a Mixer" },
          chapter: { ko: "챕터 1", en: "Chapter 1" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "나카미치 거리 와민 앞", en: "Nakamichi St. — Wamin entrance" },
          trigger: { ko: "야스코를 찾아낸 후 발생", en: "After finding Yasuko." },
          body: { ko: "미팅에 동원되는 타니무라. 정해진 순서대로 회화 선택지를 골라 진행.", en: "Sit through a clumsy group date. Pick the lines in the intended order." },
          reward: { ko: "5만엔 + 경험치 3000", en: "¥50,000 + 3000 EXP" },
        },
        {
          number: 36,
          title: { ko: "또 하나의 사건", en: "Another Incident" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "아시아 거리 고향 앞 외 다발", en: "Asia St. Furusato + various" },
          trigger: { ko: "챕터 2 진행 중 자동 발생", en: "Auto in Chapter 2." },
          body: { ko: "「수사 라인」 체인의 출발점. 후속 「실마리」로 직결.", en: "Kicks off Tanimura's detective chain. Leads into 'Lead'." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 37,
          title: { ko: "실마리", en: "The Lead" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "마하 볼링 → 챔피언 거리 셸락 → 클럽 SEGA", en: "Mach Bowl → Shellac (Champion St.) → Club SEGA" },
          trigger: { ko: "「또 하나의 사건」 클리어", en: "Clear 'Another Incident'." },
          body: { ko: "용의자의 행적을 추적. 후속 「브릿지의 정체」로 연결됩니다.", en: "Trace the suspect's movements. Bridges to 'Bridge's True Identity'." },
          reward: { ko: "용의 눈 + 경험치 5000", en: "Dragon's Eye + 5000 EXP" },
        },
        {
          number: 38,
          title: { ko: "목격자", en: "Witness" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "카무로 극장 출구", en: "Kamuro Theater exit" },
          trigger: { ko: "극장 앞에서 사건 목격", en: "Witness the incident outside the theater." },
          body: { ko: "범인을 추격해 잡는 미스블 후보. 「알았어, 잡아줄게」를 골라야 보상 획득.", en: "Missable: pick 'I'll catch them' to claim the reward." },
          choices: [
            { prompt: { ko: "「잡아주실래요?」", en: "'Could you catch them?'" }, correct: { ko: "알았어, 잡아줄게", en: "I'll catch them" } },
          ],
          reward: { ko: "BJ의 부적 + 경험치 5000", en: "BJ's Charm + 5000 EXP" },
        },
        {
          number: 39,
          title: { ko: "위에서의 시선", en: "Gaze from Above" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "극장 앞 광장 · 신주쿠 서쪽 옥상", en: "Theater Plaza · west rooftop" },
          trigger: { ko: "「목격자」 클리어", en: "Clear 'Witness'." },
          body: { ko: "옥상에서 도시를 관찰하는 스파이 행세 청년 처리.", en: "Deal with a 'spy' watching the city from above." },
          reward: { ko: "경악 스파이 아이템 전집 + 경험치 5000", en: "Amazing Spy Item Collection + 5000 EXP" },
        },
        {
          number: 40,
          title: { ko: "에트랑제", en: "Étranger" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "시치후쿠 거리 동쪽", en: "Shichifuku St. East" },
          trigger: { ko: "외국인에게 시비 거는 야쿠자 자동 이벤트", en: "Auto-triggers when yakuza hassle a tourist." },
          body: {
            ko: "외국인 관광객에게 일본 문화를 통역. 미스블 후보로 두 답을 모두 맞춰야 보상 정상 획득.",
            en: "Translate Japanese culture for a tourist. Missable — both answers must be right.",
          },
          choices: [
            { prompt: { ko: "「판·왕·게임? 그게 뭐예요?」", en: "'Pan/oh/game? What is that?'" }, correct: { ko: "장기(쇼기) 얘기로군", en: "'Must be shogi'" } },
            { prompt: { ko: "「온·세·엔이 뭐예요?」", en: "'What's on-se-en?'" }, correct: { ko: "온천을 말하는 거겠지", en: "'Probably onsen'" } },
          ],
          reward: { ko: "5만엔 + 경험치 5000", en: "¥50,000 + 5000 EXP" },
        },
        {
          number: 41,
          title: { ko: "차량 절도", en: "Car Burglar" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "극장 북서쪽 · 아동공원 앞", en: "Theater NW · children's park" },
          trigger: { ko: "거리에서 절도범 이벤트 자동 발생", en: "Auto event with a car burglar." },
          body: {
            ko: "수상한 키를 든 남자 검문. 미스블 후보 — 「그거, 그 차 열쇠야?」를 골라 결정타.",
            en: "Missable — pick the keys line to nail the burglar.",
          },
          choices: [
            { prompt: { ko: "결정적 한 마디", en: "Decisive line" }, correct: { ko: "그거, 그 차 열쇠야?", en: "'That, is that the car's key?'" } },
          ],
          reward: { ko: "빨간 보석 + 경험치 2000", en: "Red Jewel + 2000 EXP" },
        },
        {
          number: 42,
          title: { ko: "도난당한 비자금", en: "Stolen Slush Fund" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "텐카이치 거리 뒷골목 · 제3공원 앞", en: "Tenkaichi back alley · 3rd Park" },
          trigger: { ko: "쵸에게 어태시 케이스를 맡긴 뒤 발생", en: "After leaving the attache case with Chou." },
          body: { ko: "잃어버린 비자금을 회수하는 미행극. 후속 「소리 없는 목소리」로 이어집니다.", en: "Tail the thief to recover the slush fund. Leads into 'Voiceless Voice'." },
          reward: { ko: "루비 + 경험치 5000", en: "Ruby + 5000 EXP" },
        },
        {
          number: 43,
          title: { ko: "소리 없는 목소리", en: "The Voiceless Voice" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "아시아 거리 고향 외 다발", en: "Asia St. Furusato + various interiors" },
          trigger: { ko: "「도난당한 비자금」 클리어", en: "Clear 'Stolen Slush Fund'." },
          body: { ko: "이주 노동자의 사연을 듣고 도와주는 후속편.", en: "Hear out the migrant worker and resolve his story." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 44,
          title: { ko: "위험한 놀이", en: "Dangerous Game" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "용궁성", en: "Ryugu Castle" },
          trigger: { ko: "용궁성에서 부유한 노인 도발 이벤트", en: "Encounter the wealthy elder inside Ryugu Castle." },
          body: {
            ko: "러시안 룰렛 도박. 세 단계 선택지에서 모두 정답을 골라야 300만엔. 한 번이라도 틀리면 보상이 날아가는 대표 미스블.",
            en: "Three-round Russian roulette. Get every prompt right to win ¥3M — one slip loses the reward entirely.",
          },
          choices: [
            { prompt: { ko: "1차", en: "Round 1" }, correct: { ko: "이야기를 듣는다 → 승부에 응한다", en: "Listen → Take the bet" } },
            { prompt: { ko: "2차", en: "Round 2" }, correct: { ko: "승부한다 → 강하게 방아쇠를 당긴다", en: "Bet → Pull the trigger firmly" } },
            { prompt: { ko: "3차", en: "Round 3" }, correct: { ko: "마지막 승부를 한다 → 무심으로 방아쇠를 당긴다", en: "Take the final bet → Pull with empty mind" } },
          ],
          reward: { ko: "300만엔 + 경험치 5000", en: "¥3,000,000 + 5000 EXP" },
        },
        {
          number: 45,
          title: { ko: "메이파에게 보내는 편지", en: "Letter to Maifa" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "아시아 거리 · 서공원 · 호텔가 북쪽", en: "Asia St. · West Park · Hotel Dist. north" },
          trigger: { ko: "고향 앞 챠오와 대화", en: "Talk to Zhao at Furusato." },
          body: { ko: "메이파의 마지막 편지를 전달하기 위한 호위 임무.", en: "Escort mission to deliver Maifa's last letter." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 46,
          title: { ko: "브릿지의 정체", en: "Bridge's True Identity" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "폿포 나카미치 · 챔피언 거리 · 나오미의 저택 · 카무로쵸 서쪽 옥상 · 자라 거리", en: "Poppo Nakamichi · Champion St. · Naomi's mansion · West rooftop · Suppon St." },
          trigger: { ko: "「실마리」 클리어", en: "Clear 'The Lead'." },
          body: { ko: "수상한 외국인 「브릿지」의 정체를 파헤치는 후속편.", en: "Unmask the mysterious 'Bridge'." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 47,
          title: { ko: "이어받는 것", en: "What is Inherited" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "타니무라", en: "Tanimura" },
          location: { ko: "챔피언 거리 · 핑크 거리 뒤 · 나오미의 저택", en: "Champion St. · Pink St. back · Naomi's mansion" },
          trigger: { ko: "「브릿지의 정체」 클리어 후 나오미 전화", en: "Clear 'Bridge' then take Naomi's call." },
          body: { ko: "타니무라 체인의 종착점. 추격 배틀까지 클리어 시 용의 인장 획득.", en: "Caps Tanimura's chain — chase battle finale awards the Dragon Seal." },
          reward: { ko: "용의 인장 + 경험치 10000", en: "Dragon Seal + 10000 EXP" },
        },
      ],
    },
    {
      title: { ko: "키류 편 — 챕터 2 · 4 · 최종부", en: "Kiryu — Chapter 2 / 4 / Final" },
      items: [
        {
          number: 48,
          title: { ko: "캬바쿠라 공략법 · 키류 편", en: "Cabaret Strategy — Kiryu" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "큐즈 바 → 캬바쿠라 4곳", en: "Cue's Bar → cabaret clubs" },
          trigger: { ko: "큐즈 바에서 미나사와와 대화", en: "Talk to Minasawa at Cue's Bar." },
          body: { ko: "키류용 캬바쿠라 미니게임 풀 해금. 각 호스티스 취향에 맞춘 동반 선택이 핵심.", en: "Unlocks the Cabaret minigame for Kiryu." },
          reward: { ko: "6만엔 + 경험치 5000", en: "¥60,000 + 5000 EXP" },
        },
        {
          number: 49,
          title: { ko: "삐뚤어진 녀석 재림", en: "Twisted Guy Returns" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "요시다 배팅 센터", en: "Yoshida Batting Center" },
          trigger: { ko: "뉴 세레나에서 나온 직후 메일", en: "Email after leaving New Serena." },
          body: { ko: "야쿠자 3의 그 삐뚤어진 「토라키치」 재등장. 타격 미니게임 챌린지.", en: "Yakuza 3's Torakichi returns. Batting challenge." },
          reward: { ko: "신수의 나뭇조각 + 경험치 5000", en: "Divine Wood Chip + 5000 EXP" },
        },
        {
          number: 50,
          title: { ko: "코타로의 취업 활동", en: "Kohtaro's Job Hunt" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "밴덤 부근", en: "Around Bantam" },
          trigger: { ko: "밴덤 부근에서 코타로 이벤트", en: "Event near Bantam with Kohtaro." },
          body: { ko: "면접 준비 중인 청년을 코칭. 키류식 정공법으로 격려.", en: "Coach a young job hunter through his interview prep." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 51,
          title: { ko: "유우야의 방식", en: "Yuya's Way" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "스타더스트(텐카이치 거리)", en: "Stardust (Tenkaichi St.)" },
          trigger: { ko: "유우야와 대화", en: "Talk to Yuya." },
          body: { ko: "캬바레 클럽 사장의 고민 상담.", en: "Counsel the cabaret club owner Yuya." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 52,
          title: { ko: "지치지 않는 녀석", en: "That Stubborn Guy" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "스타더스트 외", en: "Stardust + various" },
          trigger: { ko: "스타더스트 이벤트", en: "Event at Stardust." },
          body: { ko: "구작 단골 캐릭터의 변함없는 작업 멘트 시리즈.", en: "Recurring lothario character makes another pass at love." },
          reward: { ko: "모테모테 팔찌 + 경험치 5000", en: "Lothario Bracelet + 5000 EXP" },
        },
        {
          number: 53,
          title: { ko: "컬러 갱", en: "Color Gang" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "카무로쵸 다발 위치", en: "Multiple locations" },
          trigger: { ko: "커피 마이스터에서 회화 이벤트", en: "Conversation event at Coffee Meister." },
          body: { ko: "거리 곳곳의 컬러 갱들을 평정하는 시리즈.", en: "Bust color gangs across the city." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 54,
          title: { ko: "사제 대결", en: "Master vs. Apprentice" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "큐슈 이치반보시(핑크 거리 뒷골목)", en: "Kyushu Ichibanboshi (Pink St. alley)" },
          trigger: { ko: "큐슈 이치반보시 입장 시 발생", en: "Enter Kyushu Ichibanboshi." },
          body: { ko: "오키나와의 제자와 라멘 한 그릇 승부. 격투 + 미각 챌린지.", en: "A ramen showdown with Kiryu's Okinawa apprentice." },
          reward: { ko: "큐슈 이치반보시 메뉴 추가 + 경험치 5000", en: "New Kyushu Ichibanboshi menu + 5000 EXP" },
        },
        {
          number: 55,
          title: { ko: "다정한 거짓말", en: "A Gentle Lie" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "밴덤(밀레니엄 타워 동쪽 거리)", en: "Bantam (Millennium Tower East St.)" },
          trigger: { ko: "여성과의 회화에서 「사귄다」 선택", en: "Pick 'Date her' in the convo with the woman." },
          body: {
            ko: "오키나와에서 알게 된 여성의 부탁을 받는 미스블. 「사귄다」를 골라야 백금 페어링 보상이 풀립니다.",
            en: "Missable — pick 'Date her' to earn the platinum ring reward.",
          },
          choices: [
            { prompt: { ko: "「잠깐만 사귀어 줄래?」", en: "'Date me for a bit?'" }, correct: { ko: "사귄다", en: "Date her" } },
          ],
          reward: { ko: "백금 페어링 + 경험치 5000", en: "Platinum Pair Ring + 5000 EXP" },
        },
        {
          number: 56,
          title: { ko: "카레를 둘러싼 모험", en: "A Curry Adventure" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "파크 앞 거리(용궁성 부근)", en: "Park-front St. (near Ryugu)" },
          trigger: { ko: "배달원의 의뢰", en: "Delivery man's request." },
          body: { ko: "사라진 카레 배달을 추적해 회수.", en: "Track down a lost curry delivery." },
          reward: { ko: "스태미넌 스파크 + 경험치 5000", en: "Staminan Spark + 5000 EXP" },
        },
        {
          number: 57,
          title: { ko: "거리의 히어로", en: "Street Hero" },
          chapter: { ko: "챕터 2", en: "Chapter 2" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "카무로쵸 다발 위치", en: "Multiple locations" },
          trigger: { ko: "타이츠맨 이벤트", en: "Tights Man event." },
          body: { ko: "복면 히어로 「타이츠맨」을 도와 도시의 평화를 지킵니다.", en: "Help 'Tights Man' keep Kamurocho safe." },
          reward: { ko: "피트니스 기어 + 경험치 5000", en: "Fitness Gear + 5000 EXP" },
        },
        {
          number: 58,
          title: { ko: "의사와 마음", en: "The Doctor's Heart" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "부두(택시) → 뉴 세레나", en: "Wharf (taxi) → New Serena" },
          trigger: { ko: "야간 이동 시 자동 발생", en: "Auto at night." },
          body: { ko: "위급한 환자와 의사를 부두로 호송.", en: "Escort an injured patient and doctor to the wharf." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 59,
          title: { ko: "가족의 조건", en: "Family Conditions" },
          chapter: { ko: "챕터 4", en: "Chapter 4" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "뉴 세레나 · 밀레니엄 타워 · 극장 광장 · 시치후쿠 공원", en: "New Serena · Millennium Tower · Theater Plaza · Shichifuku Park" },
          trigger: { ko: "챕터 4 진행 중 자동 발생", en: "Auto in Chapter 4." },
          body: { ko: "최종부 「키류의 육아」 전편. 클리어 안 하면 후속이 잠깁니다.", en: "Sets up 'Kiryu's Babysitting' in the Final — required to keep the chain alive." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 60,
          title: { ko: "키류의 육아", en: "Kiryu's Babysitting" },
          chapter: { ko: "최종부", en: "Final" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "뉴 세레나 주변", en: "Around New Serena" },
          trigger: { ko: "「가족의 조건」 클리어", en: "Clear 'Family Conditions'." },
          body: { ko: "맡은 아이를 무사히 부모에게 돌려보내는 호위극.", en: "Get the kid safely back to her parents." },
          reward: { ko: "무의 보석 + 경험치 5000", en: "Gem of Nothingness + 5000 EXP" },
        },
        {
          number: 61,
          title: { ko: "꽃말", en: "Flower Language" },
          chapter: { ko: "최종부", en: "Final" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "밀레니엄 타워 외 다발", en: "Millennium Tower + various" },
          trigger: { ko: "최종부 자유행동 중 발생", en: "During Final-part free roam." },
          body: { ko: "한 청년의 고백을 도와주는 키류식 멘토링.", en: "Help a young man pull off his confession." },
          reward: { ko: "경험치 5000", en: "5000 EXP" },
        },
        {
          number: 62,
          title: { ko: "힐스의 소문", en: "Rumor of the Hills" },
          chapter: { ko: "최종부", en: "Final" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "사이노카와라(서공원) 외", en: "Sai no Kawara (West Park) + various" },
          trigger: { ko: "최종부 자유행동 중 발생", en: "During Final-part free roam." },
          body: { ko: "지하 격투장 「사이노카와라」 정상 결전.", en: "Climb the Sai no Kawara underground arena to the top." },
          reward: { ko: "용의 인장 + 경험치 5000", en: "Dragon Seal + 5000 EXP" },
        },
        {
          number: 63,
          title: { ko: "아몬", en: "Amon" },
          chapter: { ko: "최종부", en: "Final" },
          protagonist: { ko: "키류", en: "Kiryu" },
          location: { ko: "밀레니엄 타워 옥상", en: "Millennium Tower roof" },
          trigger: { ko: "나머지 62개 서브스토리 전부 클리어 후 자동 발생", en: "Clear all other 62 substories first." },
          body: {
            ko: "시리즈 명물 최강 보스 아몬 형제 결전. 본편 클리어 + 모든 서브 완료가 사실상 필수.",
            en: "Series-staple final challenge against the Amon clan. Effectively requires endgame gear and every other substory cleared.",
          },
          prereq: { ko: "다른 62개 서브스토리 전부 클리어", en: "All 62 other substories cleared." },
          reward: { ko: "「용신환」(최강 무기 계열)", en: "Ryuujin-maru (top-tier weapon)" },
        },
      ],
    },
  ],
};
