import type { SubstoriesData } from "./types";

export const yakuza6Substories: SubstoriesData = {
  appId: 1388590,
  summary: {
    ko: "카무로초 24건 + 오노미치 진가이초 26건 + 아몬 1건 = 총 51건(컴플리션 리스트 52번 슬롯은 「전체 클리어」). 장 진행에 따라 해금되며, 일부는 친구도(스낵 뉴 가우디)·야구·다이빙·캬바쿠라 등 미니게임 의존. 6장 이후 카무로초 서브가 대량 해금되니 메인 스토리와 병행이 효율적.",
    en: "24 Kamurocho + 26 Onomichi Jingaicho + 1 Amon = 51 substories (completion-list slot 52 is the 'all cleared' tally). Many gate on Snack New Gaudi friendship, baseball, diving, or hostess clubs; the bulk of Kamurocho unlocks from Chapter 6, so pair them with the main story.",
  },
  source: {
    label: "光る原人 — 龍が如く6 サブストーリー一覧",
    url: "https://www.hikarugennjinn.com/entry/yakuza6-sub_story",
  },
  groups: [
    {
      title: { ko: "카무로초", en: "Kamurocho (No.1~24)" },
      items: [
        {
          number: 1,
          title: { ko: "키류의 카베동", en: "Kiryu's Wall Slam" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "텐카이치 거리 뒷골목", en: "Tenkaichi St. Alley" },
          trigger: { ko: "텐카이치 거리 뒷골목에서 남성들에게 말 걸기 → 반탐 앞으로 이동", en: "Talk to the men in Tenkaichi Alley, then head to Bantam." },
          body: { ko: "카베동을 가르쳐 달라는 남자들의 부탁. 시범 후 잡졸 무리와 전투.", en: "A group of men ask Kiryu to teach them the 'wall slam'. Demo it, then brawl their tormentors." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 2,
          title: { ko: "전화 상대", en: "The Phone Caller" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "밀레니엄 타워 앞", en: "Millennium Tower" },
          trigger: { ko: "밀레니엄 타워 앞 공중전화에서 걸려오는 전화 응답", en: "Answer the ringing payphone at Millennium Tower." },
          body: { ko: "오레오레 사기범의 전화. 정체를 캐묻고 사기임을 간파하면 일당과 전투로 이어진다.", en: "An 'It's me' scammer calls. Press him on his identity to expose the scam, then beat the crew." },
          choices: [
            { prompt: { ko: "「누구야?」 (1차)", en: "'Who is this?' (1st)" }, correct: { ko: "「타이치냐?」", en: "'Taichi?'" } },
            { prompt: { ko: "「누구야?」 (2차)", en: "'Who is this?' (2nd)" }, correct: { ko: "「타이치냐?」", en: "'Taichi?'" } },
            { prompt: { ko: "수상한가?", en: "Suspicious?" }, correct: { ko: "「이거 오레오레 사기 아냐?」", en: "'This is an It's-me scam, isn't it?'" } },
            { prompt: { ko: "확신하나?", en: "Sure?" }, correct: { ko: "「오레오레 사기가 분명해!」", en: "'Definitely an It's-me scam!'" } },
          ],
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 3,
          title: { ko: "동경하는 사람", en: "Idol Worship" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "시치후쿠 공원", en: "Shichifuku Park" },
          trigger: { ko: "시치후쿠 공원의 소녀 아야카에게 말 걸기", en: "Talk to the girl Ayaka at Shichifuku Park." },
          body: { ko: "하루카의 팬인 소녀 아야카가 하루카 굿즈를 찾고 있다. 도와주면 그림 선물.", en: "A young Haruka fan asks Kiryu to help her find merch. Help her out for a hand-drawn picture." },
          reward: { ko: "「아야카가 그린 하루카 일행 그림」", en: "Ayaka's drawing of Haruka and friends" },
        },
        {
          number: 4,
          title: { ko: "청소 로봇의 폭주", en: "Runaway Cleaner Bot" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "카무로초 곳곳", en: "Various Kamurocho streets" },
          trigger: { ko: "거리에서 폭주 중인 청소 로봇 발견 후 추적", en: "Chase the runaway robot vacuum spotted in the streets." },
          body: { ko: "폭주한 청소 로봇을 따라잡아 정지시키고 주인에게 돌려준다.", en: "Catch the rogue cleaning robot and return it to its owner." },
        },
        {
          number: 5,
          title: { ko: "I am human", en: "I am human" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "시치후쿠 공원 서쪽", en: "Shichifuku Park West" },
          trigger: { ko: "공원 서쪽의 AI 캐릭터 「히지」와 대화", en: "Talk to the AI character Hiji west of the park." },
          body: { ko: "자신을 인간이라 주장하는 AI 「히지」와 대화. 인간성에 관한 질문에 답하면 종료.", en: "An AI named Hiji insists he is human. Answer his questions about humanity." },
          reward: { ko: "개운 액막이 부적", en: "Lucky charm (Kaiun Yakuyoke)" },
        },
        {
          number: 6,
          title: { ko: "조회수가 전부", en: "Views Are Everything" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "씨어터 광장 앞", en: "Theater Square" },
          trigger: { ko: "씨어터 광장의 유튜버 우스이에게 말 걸기", en: "Talk to YouTuber Usui at Theater Square." },
          body: { ko: "노이즈 유튜버 우스이의 무모한 스턴트를 도와주거나 말리는 흐름. 결국 시청자 시비로 전투까지 이어진다.", en: "Help — or stop — viral creator Usui's stunt; ends in a brawl with hostile viewers." },
        },
        {
          number: 7,
          title: { ko: "드론을 쫓아라", en: "Chase the Drone" },
          chapter: { ko: "7장 이후", en: "Chapter 7+" },
          location: { ko: "센료 거리", en: "Senryo Ave." },
          trigger: { ko: "센료 거리에서 드론을 발견 후 추적", en: "Spot the drone on Senryo Ave. and chase it." },
          body: { ko: "수상한 드론을 추적하여 다목적 빌딩까지 도달, 운영자와 대치.", en: "Chase a suspicious drone to a multipurpose building and confront its operator." },
        },
        {
          number: 8,
          title: { ko: "원한 가진 자들 1", en: "Those With a Grudge 1" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "텐카이치 거리 — 배팅 센터 앞", en: "Tenkaichi St. — outside Batting Center" },
          trigger: { ko: "배팅 센터 앞 핫피 차림 남성에게 말 걸기", en: "Talk to the man in a happi coat outside the Batting Center." },
          body: { ko: "키류에게 원한이 있다는 사내들과의 전투.", en: "Brawl with men who claim a grudge against Kiryu." },
        },
        {
          number: 9,
          title: { ko: "원한 가진 자들 2", en: "Those With a Grudge 2" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "배팅 센터 부근", en: "Near the Batting Center" },
          trigger: { ko: "No.8 클리어 후 배팅 센터 부근에서 재발생", en: "After clearing No.8, the grudge crew returns near the Batting Center." },
          body: { ko: "No.8을 끝내고 다시 텐카이치 거리 입구 부근으로 가면 발생. 요시다 배팅 센터로 향해 안에 있는 노란 저지 차림의 남자에게 말을 걸면 이벤트가 시작되고, 수상한 남자 10여 명과 한꺼번에 싸우게 된다. 다수전이므로 히트 액션과 무기를 아끼지 말 것.", en: "Unlocks near the Tenkaichi St. entrance once No.8 is done. Head to the Yoshida Batting Center and talk to the man in the yellow tracksuit inside; the scene ends in a brawl against roughly ten men at once, so lean on weapons and heat actions." },
          prereq: { ko: "No.8 클리어", en: "Complete No.8" },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 10,
          title: { ko: "매혹적인 권유", en: "An Alluring Invitation" },
          chapter: { ko: "6장 이후 (야간)", en: "Chapter 6+, night" },
          location: { ko: "머핀 빌딩 부근", en: "Near Muffin Building" },
          trigger: { ko: "야간 머핀 빌딩 부근 여성에게 말 걸기", en: "Speak to the woman near the Muffin Building at night." },
          body: { ko: "셀카 모델을 부탁하는 여성과 동행. 3장의 사진 촬영 미니이벤트.", en: "Tag along with a woman who wants three selfies — pose for each." },
        },
        {
          number: 11,
          title: { ko: "지금 바빠?", en: "Are You Busy?" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "시치후쿠 공원", en: "Shichifuku Park" },
          trigger: { ko: "공원에서 곤란해하는 청년에게 말 걸기 → 포포에서 5만엔 선불카드 구매", en: "Talk to the troubled young man at the park, then buy a 50,000 yen prepaid card at POPPO." },
          body: { ko: "선불카드 사기 의심 상황. 즉시 보내지 말고 끝까지 우겨야 사기범 일당이 등장하여 전투, 완전 보상.", en: "A prepaid-card scam setup. Refuse to send the number — push back twice — to draw out the crew and clear properly." },
          choices: [
            { prompt: { ko: "카드 번호 알려달라", en: "Send the number?" }, correct: { ko: "용도를 묻는다", en: "Ask their purpose" } },
            { prompt: { ko: "그래도 보내달라", en: "Send anyway?" }, correct: { ko: "버텨본다", en: "Push back" } },
            { prompt: { ko: "끝까지 보내달라", en: "Final ask?" }, correct: { ko: "더 버텨본다", en: "Push back harder" } },
          ],
          reward: { ko: "경험치 + 삥쟁이 일당 격파", en: "EXP + scammer crew defeated" },
        },
        {
          number: 12,
          title: { ko: "전설의 사나이 폴 림", en: "The Legend, Paul Lim" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "반탐", en: "Bantam" },
          trigger: { ko: "반탐에서 아카이시와 다트 대결", en: "Play darts against Akaishi at Bantam." },
          body: { ko: "다트 명인 폴 림에 도전하기 위한 자격 매치. 아카이시 격파 시 중급자의 화살 획득.", en: "Beat Akaishi at Bantam to qualify for a showdown against Paul Lim." },
          reward: { ko: "「중급자의 화살」", en: "Intermediate Darts" },
        },
        {
          number: 13,
          title: { ko: "폴 림과의 대결", en: "Battle with Paul Lim" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "반탐", en: "Bantam" },
          trigger: { ko: "No.12 클리어 후 폴 림에게 도전", en: "After clearing No.12, challenge Paul Lim." },
          body: { ko: "다트 연습을 하러 다가가면 폴 림이 승부를 걸어옵니다. 키류가 영어를 못해 아카이시자와 유야가 통역을 맡으며, 승패나 룰과 관계없이 폴 림이 레전드 다트를 건네줍니다.", en: "Approach the dartboard for a practice round and Paul Lim challenges you, with Yuya Akaishizawa translating since Kiryu does not speak English. Win or lose, whatever the ruleset, Paul gifts you his Legend's Darts." },
          prereq: { ko: "No.12 클리어", en: "Complete No.12" },
          reward: { ko: "레전드 다트", en: "Legend's Darts" },
        },
        {
          number: 14,
          title: { ko: "맞서는 자", en: "Standing Up" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "밀레니엄 타워 부근 캬바쿠라", en: "Cabaret near Millennium Tower" },
          trigger: { ko: "캬바쿠라에서 사키를 No.1으로 만들기", en: "Make Saki No.1 at the cabaret." },
          body: { ko: "캬바쿠라 미니게임 연계. 사키 양성 후 트러블 해결.", en: "Cabaret minigame chain — train Saki to top, then handle the trouble that follows." },
        },
        {
          number: 15,
          title: { ko: "매혹의 데뷔", en: "Charming Debut" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "다목적 빌딩 캬바쿠라", en: "Multipurpose Bldg. Cabaret" },
          trigger: { ko: "히카루를 No.1으로 만들기", en: "Make Hikaru No.1 at the cabaret." },
          body: { ko: "히카루의 명함을 받고 플래티넘 등급까지 올린 뒤 극장 광장에서 데이트 약속을 잡습니다. 그녀가 나타나지 않아 찾아보면 연예 기획사 면접에 가 있고, 관계자들의 속셈을 알게 되는 전개로 이어집니다.", en: "Get Hikaru's business card and reach Platinum level with her, then set up the date in Theatre Square. When she does not show, search around and you find she is at a talent agency interview — and learn what the staff are really after." },
          reward: { ko: "히카루 라인 진행", en: "Hikaru's line advances" },
        },
        {
          number: 16,
          title: { ko: "마음을 전하다", en: "Conveying Feelings" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "씨어터 광장 캬바쿠라", en: "Theater Square Cabaret" },
          trigger: { ko: "SORA를 No.1으로 만들기", en: "Make SORA No.1 at the cabaret." },
          body: { ko: "캬바쿠라 샤인에서 SORA를 No.1으로 올린 뒤 애프터 약속을 극장 앞 광장으로 잡고, 광장의 SORA에게 말을 건다. 장면이 바뀌며 대화 선택지가 두 번 나온다. 「순수하고 활기찬 여성」／「순수하고 참한 여성」, 이어서 「달리 해야 할 일이 있다」／「지금은 무리다……」／「언젠가는 하고 싶다」 중에서 고르면 되고, 어느 쪽을 골라도 클리어된다.", en: "Make SORA the No.1 hostess at Club Shine, set the after-hours date at the theater square, then talk to her there. The scene moves on its own into a dialogue with two prompts — a cheerful woman or a demure one, then whether you have other things to do, cannot manage it now, or would like to some day. Neither choice changes the outcome." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 17,
          title: { ko: "꼬마 악마의 위기", en: "Little Devil's Crisis" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "씨어터 광장 캬바쿠라", en: "Theater Square Cabaret" },
          trigger: { ko: "에리나를 No.1으로 만들기", en: "Make Erina No.1 at the cabaret." },
          body: { ko: "캬바쿠라 샤인에서 에리나를 No.1으로 올리고 애프터 약속을 극장 앞 광장으로 잡은 뒤 광장으로 향한다. 자동으로 스토커 이벤트가 발생하고, 악질적인 남자와 1대1 전투. 이기면 이벤트로 이어지며 완료.", en: "Make Erina the No.1 hostess at Club Shine, arrange the after-hours meet at the theater square and go there. A stalker scene triggers automatically and ends in a one-on-one fight; win it and the substory wraps up." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 18,
          title: { ko: "양심적인 캬바걸", en: "The Honest Hostess" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "핑크 거리 캬바쿠라", en: "Pink St. Cabaret" },
          trigger: { ko: "리오나를 No.1으로 만들기", en: "Make Riona No.1 at the cabaret." },
          body: { ko: "핑크 거리 끝에서 기다리는 리오나와 나서려는 순간, 거액을 쓰고 출입을 거부당한 남자가 캬바걸을 탓하는 장면을 목격합니다. 그 캬바걸이 클럽 샤인 소속이라는 사실이 드러나며 이야기가 이어집니다.", en: "Riona is waiting near the end of Pink Avenue, but as you set off you witness a man blaming a hostess for barring him after he ran up a huge bill — and it turns out she is from Club Shine." },
          reward: { ko: "리오나 라인 진행", en: "Riona's line advances" },
        },
        {
          number: 19,
          title: { ko: "ID 배팅 센터", en: "ID Batting Center" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "배팅 센터", en: "Batting Center" },
          trigger: { ko: "오노미치 No.35 클리어 후 5연속 홈런", en: "After Onomichi No.35, hit 5 home runs in a row." },
          body: { ko: "오노미치의 No.35를 끝낸 뒤 카무로초 요시다 배팅 센터에서 챌린지 코스를 3회 클리어하면 지배인과의 대화 이벤트가 발생한다. 이어서 시작(試作) 코스에 도전해 홈런 5개를 연속으로 쳐야 한다. 구종과 코스는 매번 동일하고 몇 번이든 재도전할 수 있으니 패턴을 외우면 된다. 지배인과의 대화 선택지가 두 번 나오지만 어느 쪽을 골라도 진행되며, 마지막에 지배인이 팀에 합류한다.", en: "After Onomichi's No.35, clear the Yoshida Batting Center's challenge course three times to trigger a chat with the manager. Then take the prototype course and hit five home runs in a row — the pitch types and locations never change and you can retry freely, so it is a memorisation job. There are two dialogue prompts along the way and neither changes anything; the manager signs on at the end regardless." },
          prereq: { ko: "오노미치 No.35 클리어", en: "Clear Onomichi No.35" },
          reward: { ko: "요시다 지배인이 세토우치 워리어즈 합류", en: "Manager Yoshida joins the Seto Warriors" },
        },
        {
          number: 20,
          title: { ko: "나니와의 홈런왕", en: "Naniwa Home Run King" },
          chapter: { ko: "6장 이후", en: "Chapter 6+" },
          location: { ko: "배팅 센터", en: "Batting Center" },
          trigger: { ko: "오노미치 No.35 클리어 후 홈런 7개 이상", en: "After Onomichi No.35, score 7+ home runs." },
          body: { ko: "오노미치의 No.35를 끝낸 뒤 요시다 배팅 센터의 홈런 코스를 3회 클리어하면 고리 씨와의 대화 이벤트. 그대로 승부에 들어가 홈런을 7개 이상 치면 고리 씨가 팀에 합류한다.", en: "Once Onomichi's No.35 is done, clear the Yoshida Batting Center's home-run course three times to meet Gori-san, then beat him by hitting seven or more home runs to recruit him." },
          prereq: { ko: "오노미치 No.35 클리어", en: "Clear Onomichi No.35" },
          reward: { ko: "고리 씨가 세토우치 워리어즈 합류", en: "Gori-san joins the Seto Warriors" },
        },
        {
          number: 21,
          title: { ko: "고양이 카페에 어서 오세요", en: "Welcome to the Cat Cafe" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "고양이 카페 냥냥", en: "Cat Cafe Nyan Nyan" },
          trigger: { ko: "고양이 카페 입장", en: "Enter the cat cafe." },
          body: { ko: "센료 거리 앞 건물 3층의 「cat cafe nyan nyan 차방」 앞을 지나가면 이벤트. 가게에 들어가면 자동으로 대화로 이어지고, 카무로초와 오노미치 곳곳에서 고양이를 찾아 데려오는 「고양이 찾기」가 해금된다.", en: "Walk up to the third floor of the building before Senryo Ave. and the \"cat cafe nyan nyan\" scene fires. Step inside and the conversation plays out on its own, unlocking Cat Search — the collectathon of strays scattered across Kamurocho and Onomichi." },
          reward: { ko: "「고양이 찾기」 해금", en: "Unlocks the Cat Search minigame" },
        },
        {
          number: 22,
          title: { ko: "라이브 챗의 유혹", en: "Live Chat Temptation" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "인터넷 카페 만타이", en: "Internet Cafe Mantai" },
          trigger: { ko: "인터넷 카페에서 라이브 챗 이용", en: "Use live chat at the internet cafe." },
          body: { ko: "「빗테 키친 타이헤이 거리 서점」 부근 모퉁이에 있는 커플 옆을 지나가면 발생. 커플이 무슨 이야기를 하는지 묻는 선택지가 나오는데 어느 쪽을 골라도 진행된다. 그 뒤 극장 앞 넷카페 「mantai」로 가서 남자에게 말을 걸고 라이브 챗을 체험하면 완료.", en: "Pass the couple on the corner near Vitte Kitchen (Taihei Blvd. West) to start it; you are asked what they are talking about and any answer moves it along. Then head to the mantai net cafe by the theater, talk to the man there and try live chat for yourself." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 23,
          title: { ko: "결과에 커밋하는 남자", en: "The Man Who Commits to Results" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "라이잡", en: "RIZAP" },
          trigger: { ko: "라이잡 입회 후 트레이닝 완료", en: "Join RIZAP and complete training." },
          body: { ko: "극장 광장 뒤 「RAIZAP」 앞의 남자 2인조에게 다가가면 이벤트. 설명을 다 듣고 「입회한다」를 선택한 뒤 마쿠타에게 말을 걸어 2종류의 트레이닝을 받는다. 이후 지시받은 식단대로 식사를 하고 마쿠타에게 보고하면 완료된다. 지정된 가게에서 지정된 메뉴를 먹어야 하므로, 트레이닝 직후 바로 식사하러 가는 편이 빠르다.", en: "Approach the two men outside RAIZAP behind the theater plaza, hear them out and choose to sign up. Talk to Makuta for two rounds of training, then eat according to the diet he prescribes and report back. The meals must be the specific dishes at the specific restaurants he names, so go straight there after each session." },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 24,
          title: { ko: "다시 태어난 남자", en: "A Reborn Man" },
          chapter: { ko: "1장 이후", en: "Chapter 1+" },
          location: { ko: "라이잡 / 카무로초 거리", en: "RIZAP / Kamurocho streets" },
          trigger: { ko: "No.23 클리어 후 소다지와 재대결", en: "After No.23, rematch Sotachi multiple times." },
          body: { ko: "No.23 클리어 후 RAIZAP에서 나오면 이벤트가 발생하고 소다지와 전투. 이후 카무로초를 걸어다니는 소다지에게 말을 걸어 트러블 미션 「강적을 쓰러뜨려라 1」, 다시 말을 걸어 「강적을 쓰러뜨려라 2」를 클리어한다. 소다지에게 메일이 오면 시치후쿠 거리 서쪽 어린이 공원에서 최종 대결. 이기면 키류회에 합류한다. 트러블 미션은 2장, 클랜 배틀은 5장부터 해금되므로 그 전에는 진행이 막힌다.", en: "After No.23, leaving RAIZAP triggers a fight with Sotachi. Then find him wandering Kamurocho and clear the trouble missions \"Defeat the Tough Guy 1\" and \"2\", talking to him again between each. He emails you afterwards; meet him at the children's park west of Shichifuku St. for the final bout. Note the chain stalls until trouble missions unlock in Chapter 2 and clan battles in Chapter 5." },
          prereq: { ko: "No.23 클리어", en: "Complete No.23" },
          reward: { ko: "소다지가 키류회 합류", en: "Sotachi joins the Kiryu Clan" },
        },
      ],
    },
    {
      title: { ko: "오노미치 진가이초", en: "Onomichi Jingaicho (No.25~50)" },
      items: [
        {
          number: 25,
          title: { ko: "연애 금지", en: "No Dating Allowed" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "류난 신사", en: "Ryunan Shrine" },
          trigger: { ko: "류난 신사 부근의 젊은 커플에게 말 걸기", en: "Talk to the young couple near Ryunan Shrine." },
          body: { ko: "젊은 커플의 사정을 듣고 도와준 후, 방해하는 야쿠자 일당과 전투.", en: "Help a young couple, then fight off yakuza who interfere." },
        },
        {
          number: 26,
          title: { ko: "교주님의 속죄", en: "The Cult Leader's Atonement" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "신흥 종교 시설", en: "Cult compound" },
          trigger: { ko: "수상한 신흥 종교 권유자에게 말 걸기", en: "Talk to the suspicious cult recruiter." },
          body: { ko: "수상한 종교의 입회 시험. 모든 질문에 「올바르게」 답해 교주의 정체를 밝히고 격파.", en: "A bogus cult's induction quiz. Answer every prompt 'correctly' to expose the leader, then beat him." },
          choices: [
            { prompt: { ko: "입회 의사", en: "Intent" }, correct: { ko: "「무난쵸헤페트나스교에 들고 싶다」", en: "'I want to join the Munanchohepetonas religion'" } },
            { prompt: { ko: "인사", en: "Greeting" }, correct: { ko: "포즈를 잡고 인사", en: "Greet with the pose" } },
            { prompt: { ko: "주문 응답", en: "Mantra response" }, correct: { ko: "「헤페트나스」", en: "'Hepetonas'" } },
            { prompt: { ko: "외칠 말", en: "Sacred phrase" }, correct: { ko: "「쿠・리파스」", en: "'Ku-Ripaasu'" } },
            { prompt: { ko: "교명(이름)", en: "Cult name" }, correct: { ko: "「무난쵸・아카마츠」", en: "'Munancho-Akamatsu'" } },
            { prompt: { ko: "수업 내용", en: "Activity" }, correct: { ko: "「재교육」", en: "'Re-education'" } },
          ],
          reward: { ko: "「용의 눈」", en: "Dragon's Eye" },
        },
        {
          number: 27,
          title: { ko: "포케서 파이터, 다시", en: "Pocket Circuit Fighter Returns" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "후지사와 두부점", en: "Fujisawa Tofu Shop" },
          trigger: { ko: "후지사와 두부점에서 재회 이벤트", en: "Trigger the reunion event at Fujisawa Tofu." },
          body: { ko: "결혼해 아들을 둔 포켓 서킷 파이터가 히로시마로 돌아와 있습니다. 오노미치의 두부 가게 앞에서 재회해 카무로초 시절 이야기를 나누고, 도중에 그의 아들이 합류합니다.", en: "Pocket Circuit Fighter, now married with a son, has moved back to Hiroshima. Reunite with him in front of his tofu shop in Onomichi and reminisce about his Kamurocho racing days — his son turns up partway through." },
        },
        {
          number: 28,
          title: { ko: "오노미치의 저주", en: "The Onomichi Curse" },
          chapter: { ko: "4장 이후 (야간)", en: "Chapter 4+, night" },
          location: { ko: "묘지", en: "Cemetery" },
          trigger: { ko: "야간에 묘지에서 발생하는 괴기 현상 조사", en: "Investigate the nightly hauntings at the cemetery." },
          body: { ko: "야간 묘지에서 시간차로 발생하는 유령 조우 이벤트. 모두 처리하면 진상 판명.", en: "A series of timed ghost encounters in the cemetery at night; clear them all to learn the truth." },
        },
        {
          number: 29,
          title: { ko: "지역 캐릭터가 되자!", en: "Become a Local Mascot!" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "오노미치 아케이드", en: "Onomichi Arcade" },
          trigger: { ko: "아케이드의 마스코트 「미치오」 데뷔를 돕기", en: "Help the mascot Michio make his debut." },
          body: { ko: "아케이드에 굴러다니는 오노 미치오의 머리를 조사하면 발생. 협력하겠다고 답한 뒤 미치오를 연기하는 선택지가 다섯 번 이어진다. 자기소개 방식, 인사말, 야유에 대한 반응, 좋아하는 것, 연애 경험을 차례로 고르게 되는데 정답이 정해진 것은 아니고 미치오다운 답을 고르는 연출이다. 마지막에 잡졸 4명과 전투 후 완료.", en: "Examine Ono Michio's discarded head in the arcade and agree to help. Five in-character prompts follow — how to introduce yourself, how to greet the crowd, how to answer a heckler, what you like, and your love life — none of which is a right-or-wrong answer; they just set how you play Michio. It closes with a fight against four thugs." },
          reward: { ko: "「싸움 사라시」", en: "Brawler's Sarashi" },
        },
        {
          number: 30,
          title: { ko: "미치오의 가요 쇼", en: "Michio's Song Show" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "노래방", en: "Karaoke" },
          trigger: { ko: "No.29, No.40 클리어 후 노래방에서 합창", en: "After No.29 and No.40, sing together at karaoke." },
          body: { ko: "No.29와 No.40을 모두 클리어한 뒤 해당 지점을 지나가면 프로듀서 히로나카가 말을 건다. 「협력한다」를 선택하고 노래방에서 「오늘은 다이아몬드」를 부르면 된다. 점수는 상관없으므로 대충 불러도 클리어된다.", en: "With both No.29 and No.40 cleared, walking past the spot gets you flagged down by the producer, Hironaka. Agree to help and sing \"Today is a Diamond\" at karaoke — your score does not matter, so a sloppy run still counts." },
          prereq: { ko: "No.29 + No.40 클리어", en: "Clear No.29 + No.40" },
          reward: { ko: "「극도 양성 깁스」, 「오노 미치오 CD 샘플」", en: "Yakuza Training Gear, Ono Michio CD sample" },
        },
        {
          number: 31,
          title: { ko: "용기를 주다", en: "Giving Courage" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "오노미치", en: "Onomichi" },
          trigger: { ko: "No.30 클리어 후 소년을 격려", en: "After No.30, cheer up a young boy." },
          body: { ko: "No.30 클리어 후 스이군 아파트 맞은편의 모녀 옆을 지나가면 발생. 여자아이 시즈코에게 말을 건 다음 「대중 술집 요네토쿠」 앞의 히로나카에게 향한다. 아픔에 대한 선택지가 하나 나오고 어느 쪽을 골라도 진행되며, 잡졸 4명과 싸우면 완료.", en: "After No.30, pass the mother and daughter across from the Suigun apartments, talk to the girl Shizuko, then go to Hironaka outside the Yonetoku tavern. One prompt about being afraid of pain comes up and any answer works; win the fight against four thugs to finish." },
          prereq: { ko: "No.30 클리어", en: "Clear No.30" },
          reward: { ko: "「시즈코가 그린 미치오 그림」", en: "Shizuko's drawing of Michio" },
        },
        {
          number: 32,
          title: { ko: "시간을 뛰어넘었다는 소녀", en: "The Girl Who Time-Travelled" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "사카노우에 거리", en: "Sakanoue Rd." },
          trigger: { ko: "사카노우에 거리의 소녀에게 말 걸기", en: "Talk to the girl on Sakanoue Rd." },
          body: { ko: "「미래에서 왔다」는 소녀의 말을 끝까지 들어주면 일당이 출현, 전투로 마무리.", en: "Hear out the 'time-traveler' girl all the way; her crew shows up and you brawl." },
          choices: [
            { prompt: { ko: "더 들을 것인가", en: "Hear more?" }, correct: { ko: "「알았다 조금 더 들어주마」", en: "'Fine, I'll hear more'" } },
            { prompt: { ko: "무엇을 물을 것인가", en: "What to ask" }, correct: { ko: "「난 1년 후 어떻게 됐지?」", en: "'How am I a year from now?'" } },
            { prompt: { ko: "믿을 것인가", en: "Believe?" }, correct: { ko: "「알았다 믿어주마」", en: "'Fine, I'll believe you'" } },
          ],
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 33,
          title: { ko: "뒤바뀐 두 사람?", en: "Did They Switch?" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "류난 신사 부근", en: "Near Ryunan Shrine" },
          trigger: { ko: "신사 부근에서 울고 있는 사람에게 말 걸기", en: "Talk to the crying person near the shrine." },
          body: { ko: "「몸이 뒤바뀌었다」는 두 사람을 도와주려 하면 무라나카 일당이 난입하여 전투.", en: "Help two people who claim their bodies switched; Muranaka and crew jump you." },
          choices: [
            { prompt: { ko: "어떻게 위로하나", en: "How to comfort?" }, correct: { ko: "「울 거면 내 가슴에 기대」", en: "'If you must cry, lean on me'" } },
          ],
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 34,
          title: { ko: "동네 야구 권유", en: "Sandlot Baseball" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "시시 거리 서쪽", en: "Shishi Rd. West" },
          trigger: { ko: "야구팀에 합류", en: "Join the local baseball team." },
          body: { ko: "시시도 서쪽 ~ 진가이 나루터 통로(「도쿠야마 교통 주식회사」 맞은편)에서 세토우치 워리어즈의 치바가 말을 건다. 택시를 타고 야구장으로 가면 진가이 선더즈와 시합. 이 시합은 반드시 지도록 되어 있으니 결과에 신경 쓸 필요 없다. 이후 로프웨이 승강장 앞에서 치바와 대화하면 완료되고 동네 야구가 해금된다.", en: "Chiba of the Seto Warriors stops you on the path between Shishido West and the Jingai ferry landing, opposite Tokuyama Transit. Take a taxi to the ballpark for a game against the Jingai Thunders — it is a scripted loss, so the result does not matter. Talk to Chiba by the ropeway station afterwards to finish and unlock sandlot baseball." },
          reward: { ko: "동네 야구 해금", en: "Unlocks sandlot baseball" },
        },
        {
          number: 35,
          title: { ko: "팀메이트를 찾아라", en: "Find Teammates" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.34 클리어 후 모리즈카 영입", en: "After No.34, recruit Morizuka." },
          body: { ko: "No.34 클리어 후 야구장으로 가서, 「오코노미야키 스미카와」 앞의 3인조에게 다가가면 이벤트. 모리즈카에게 말을 걸고 전투에서 이기면 그가 워리어즈에 합류하고, 이후 거리에서 팀원을 스카우트할 수 있게 된다.", en: "Return to the ballpark after No.34, then approach the trio outside the Sumikawa okonomiyaki shop. Talk to Morizuka and beat him in a fight: he joins the Warriors and scouting other players around town opens up." },
          prereq: { ko: "No.34 클리어", en: "Clear No.34" },
          reward: { ko: "모리즈카 합류, 팀원 스카우트 해금", en: "Morizuka joins; player scouting unlocked" },
        },
        {
          number: 36,
          title: { ko: "첫 승리의 맛", en: "Taste of First Victory" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.35 클리어 후 2군 격파", en: "After No.35, beat the 2nd team." },
          body: { ko: "No.35 클리어 후 야구장에서 진가이 선더즈 2군을 상대로 승리하면 된다. 스카우트한 선수로 타순과 수비를 정비하고 붙으면 어렵지 않다.", en: "With No.35 done, head to the ballpark and beat the Jingai Thunders' second string. Set your lineup and fielding with the players you have scouted and it is a straightforward win." },
          prereq: { ko: "No.35 클리어", en: "Clear No.35" },
          reward: { ko: "경험치", en: "EXP" },
        },
        {
          number: 37,
          title: { ko: "결전! 진가이 선더즈", en: "Showdown! Jingai Thunders" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.36 클리어 후 1군 격파", en: "After No.36, beat the 1st team." },
          body: { ko: "No.36 클리어 후 야구장에서 진가이 선더즈 1군에게 승리한다. 2군보다 투수의 구위가 확실히 높으므로, 스카우트로 타격 능력치가 높은 선수를 보강해두는 편이 안전하다. 승리하면 레전즈와 시합할 수 있게 된다.", en: "After No.36, beat the Jingai Thunders' first string at the ballpark. Their pitching is a clear step up from the second team, so scout in some better hitters first. Winning opens up matches against the Legends." },
          prereq: { ko: "No.36 클리어", en: "Clear No.36" },
          reward: { ko: "레전즈전 해금", en: "Unlocks matches against the Legends" },
        },
        {
          number: 38,
          title: { ko: "오노미치 최강의 자리", en: "Onomichi's Strongest" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.37 클리어 후 레전드 격파", en: "After No.37, beat the Legends." },
          body: { ko: "치바에게 말을 걸면 진행됩니다.", en: "Talk to Chiba." },
          prereq: { ko: "No.37 클리어", en: "Clear No.37" },
        },
        {
          number: 39,
          title: { ko: "유대", en: "Bonds" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "야구장", en: "Baseball Field" },
          trigger: { ko: "No.38 클리어 후 고저스 격파", en: "After No.38, beat the Gorgeous team." },
          body: { ko: "치바에게 말을 걸면 진행됩니다.", en: "Talk to Chiba." },
          prereq: { ko: "No.38 클리어", en: "Clear No.38" },
        },
        {
          number: 40,
          title: { ko: "어른으로의 계단", en: "Stairway to Adulthood" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "스낵 뉴 가우디", en: "Snack New Gaudi" },
          trigger: { ko: "스낵 뉴 가우디 입장", en: "Enter Snack New Gaudi." },
          body: { ko: "「Snack New Gaudi」 앞을 지나가면 이벤트가 발생한다. 가게에 들어가 대화 이벤트를 보면 그대로 완료. 이 서브스토리가 No.41~No.46의 출발점으로, 이후에는 스낵에서의 대화(미니게임)에서 합격점 이상을 내며 각 손님의 친구도를 올려야 한다.", en: "Walking past Snack New Gaudi triggers the scene; step inside, watch the conversation and it is done. This is the gateway to No.41 through No.46 — from here on you raise each regular's friendship by scoring a pass mark in the bar's conversation minigame." },
          reward: { ko: "스낵 뉴 가우디 대화 해금", en: "Opens up Snack New Gaudi conversations" },
        },
        {
          number: 41,
          title: { ko: "부모 마음 자식은 모른다", en: "Parental Heart" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "하타케야마와 친구도 3 달성", en: "Reach Hatakeyama friendship lv.3." },
          body: { ko: "스낵에서 하타케야마 씨의 친구도를 3까지 올린 뒤, 스낵 앞에 하타케야마 씨가 서 있는 상태에서 접근하면 이벤트. 하타케야마·겐·마마와 스낵에서 대화하고, 이어서 「La pente」에 들어가면 이벤트가 발생하며 완료. 후일 스낵에서 하타케야마 씨에게 말을 걸면 세토우치 워리어즈에 합류한다.", en: "Raise Hatakeyama's friendship to 3 at the bar, then approach while he is standing outside. Have the group conversation with him, Gen and Mama, then enter La pente for the closing scene. Talk to him at the bar on a later visit and he joins the Seto Warriors." },
          reward: { ko: "하타케야마가 세토우치 워리어즈 합류", en: "Hatakeyama joins the Seto Warriors" },
        },
        {
          number: 42,
          title: { ko: "그 시절의 추억", en: "Memories of Then" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "아키요시와 친구도 진행", en: "Build friendship with Akiyoshi." },
          body: { ko: "스낵에서 아키요시 씨의 친구도를 3까지 올린 뒤 스낵에 접근하면 말을 걸어온다. 「좋지」를 선택해 아키요시·하타케야마·마마와 대화하고, 국도 2호선 동쪽 육교 위에 있는 아키요시 씨를 찾아가 말을 걸면 완료. 후일 스낵에서 다시 말을 걸면 워리어즈에 합류한다(하타케야마 합류 이후여야 할 수 있음).", en: "Raise Akiyoshi's friendship to 3 and he will stop you near the bar — accept, sit through the conversation with him, Hatakeyama and Mama, then find him on the footbridge east of Route 2 and talk to him. Speak to him at the bar on a later day to sign him to the Warriors (this may require Hatakeyama first)." },
          reward: { ko: "아키요시가 세토우치 워리어즈 합류", en: "Akiyoshi joins the Seto Warriors" },
        },
        {
          number: 43,
          title: { ko: "하이테크는 지긋지긋", en: "Sick of Hi-Tech" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "겐과 친구도 진행", en: "Build friendship with Gen." },
          body: { ko: "스낵에서 겐 씨의 친구도를 3까지 올린 뒤, 스낵 입구에 겐 씨가 있는 상태에서 접근하면 이벤트. 겐·하타케야마·마마와 대화한 다음 조금 걸으면 겐 씨에게서 셀카가 첨부된 메일이 온다. 다시 스낵에서 겐 씨와 대화하면 완료되고, 후일 말을 걸면 워리어즈에 합류한다.", en: "Raise Gen's friendship to 3 and approach while he is at the bar's entrance. After the group conversation with Hatakeyama and Mama, walk a short distance and he emails you a selfie; return to the bar and talk to him to finish. He joins the Warriors when you speak to him on a later visit." },
          reward: { ko: "겐이 세토우치 워리어즈 합류", en: "Gen joins the Seto Warriors" },
        },
        {
          number: 44,
          title: { ko: "반지의 가치", en: "Price of a Ring" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "안도와 친구도 진행 후 야쿠자와 전투", en: "Befriend Ando, then brawl yakuza." },
          body: { ko: "스낵에서 안도 씨의 친구도를 3까지 올리면 스낵 부근에서 말을 걸어온다. 오타후쿠야에 들어가려 하면 이벤트가 발생하고, 스낵으로 가 「들어간다」를 선택해 안도·하타케야마·아키요시·마마와 대화. 이후 오타후쿠야 앞에서 이벤트가 발생하며 불량배와 전투. 마지막으로 바닷가 진가이 나루터 앞의 안도 씨에게 다가가면 완료. 후일 스낵에서 말을 걸면 키류회에 합류한다.", en: "Raise Ando's friendship to 3 and he will approach you near the bar. Trying to enter Otafukuya triggers a scene; go back to the bar and join the conversation with Ando, Hatakeyama, Akiyoshi and Mama. A scene at Otafukuya follows with a fight against a ruffian, and the story closes when you walk up to Ando by the Jingai ferry landing. Talk to him at the bar later to add him to the Kiryu Clan." },
          reward: { ko: "안도가 키류회 합류", en: "Ando joins the Kiryu Clan" },
        },
        {
          number: 45,
          title: { ko: "은퇴의 결의", en: "Resolve to Retire" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "스낵 부근", en: "Near the snack" },
          trigger: { ko: "카네코와 친구도 진행", en: "Build friendship with Kaneko." },
          body: { ko: "스낵에서 카네코 씨의 친구도를 3까지 올린 뒤 스낵 부근에서 그를 찾아 「좋지」를 선택한다. 카네코·겐·아키요시·마마와 대화를 마치면 자동으로 스낵 밖에서 이벤트가 발생하고, 신사 벤치에 앉아 있는 카네코 씨에게 말을 걸면 완료. 후일 스낵에서 말을 걸면 키류회에 합류한다.", en: "Raise Kaneko's friendship to 3, find him near the bar and accept his invitation. After the conversation with Gen, Akiyoshi and Mama a scene plays outside on its own; finish by talking to him on the shrine bench. Speak to him at the bar later and he joins the Kiryu Clan." },
          reward: { ko: "카네코가 키류회 합류", en: "Kaneko joins the Kiryu Clan" },
        },
        {
          number: 46,
          title: { ko: "엄마 늘 고마워요", en: "Thanks, Mama" },
          chapter: { ko: "5장 이후", en: "Chapter 5+" },
          location: { ko: "스낵 뉴 가우디", en: "Snack New Gaudi" },
          trigger: { ko: "마마와 친구도 진행 후 스낵에 편지 남기기", en: "Befriend Mama, then leave a letter at the snack." },
          body: { ko: "스낵에서 마마의 친구도를 3까지 올린 뒤 「대중 술집 요네토쿠」 부근의 정장 차림 여성에게 다가가면 이벤트. 이어서 스낵 근처로 가면 다시 이벤트가 발생하고, 스낵의 전기 포트 아래에 편지를 놓는다. 시간이 지난 뒤 페리 승강장으로 가면 이벤트가 발생하며 모두와의 대화로 이어져 완료. 후일 스낵에서 마마에게 말을 걸면 수중총 「스트롱거 극」을 받는다.", en: "Raise Mama's friendship to 3, then approach the woman in a suit near the Yonetoku tavern. Head back toward the bar for the next scene and leave the letter under the electric kettle. Come back to the ferry terminal after some time has passed and the story closes with everyone talking at the bar. Speak to Mama on a later visit for the reward." },
          reward: { ko: "수중총 「스트롱거 극」", en: "Speargun \"Stronger Kiwami\"" },
        },
        {
          number: 47,
          title: { ko: "바다와 함께 사는 자들", en: "Those Who Live with the Sea" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "페리 부두", en: "Ferry Dock" },
          trigger: { ko: "부두에서 참치 조사 후 낚시 미션 개시", en: "Investigate the tuna at the dock, then start the fishing mission." },
          body: { ko: "진가이 페리 선착장에서 부상당한 이사오를 만납니다. 부상으로 조업을 못 하게 된 그가 스탠더드 작살총을 건네며 대신 어획을 부탁하고, 이를 수락하면 작살 낚시 튜토리얼로 이어집니다.", en: "At the Jingai Ferry Dock you meet an injured Isao. His injury stops him fishing, so he hands over the Standard Speargun and asks you to finish the catch for him — accepting doubles as the spearfishing tutorial." },
          reward: { ko: "스탠더드 작살총", en: "Standard Speargun" },
        },
        {
          number: 48,
          title: { ko: "세계에서 가장 맛있는 문어", en: "The World's Tastiest Octopus" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "페리 부두", en: "Ferry Dock" },
          trigger: { ko: "잠수 미션에서 문어 격파", en: "Defeat the octopus in the diving mission." },
          body: { ko: "진가이 나루터의 정장 차림 남자 골초프에게 말을 걸면 발생. 맨몸 잠수 어업 중급 「침몰 래버린스」의 마지막에 등장하는 「딜리셔스 옥토퍼스」를 잡아야 한다. 항구로 돌아오면 이벤트가 발생하며 골초프가 세토우치 워리어즈에 합류한다.", en: "Talk to Golchov, the man in a suit at the Jingai ferry landing. You need to spear the Delicious Octopus that shows up at the end of the intermediate free-diving route, Sunken Labyrinth. Return to the harbor and Golchov signs on with the Seto Warriors." },
          reward: { ko: "「플러스 차지」, 골초프 합류", en: "Plus Charge; Golchov joins the Seto Warriors" },
        },
        {
          number: 49,
          title: { ko: "소중한 장소", en: "An Important Place" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "항구", en: "Harbor" },
          trigger: { ko: "고급 잠수 미션에서 상어 격파", en: "Defeat the shark in the advanced diving mission." },
          body: { ko: "항구의 아마노에게 말을 걸면 발생. 난이도 상급 「해저 드래곤 홀」로 들어가 마지막에 나오는 블러디 샤크를 쓰러뜨리면 된다. 상급 코스는 산소 관리가 빡빡하므로 도중의 물고기는 무시하고 진행하는 편이 안전하다.", en: "Talk to Amano at the harbor, then dive the advanced route, Undersea Dragon Hole, and kill the Bloody Shark waiting at the end. Oxygen is tight on that course, so ignore the fish along the way and push straight through." },
          reward: { ko: "수중총 「스탠더드 개」", en: "Speargun \"Standard Kai\"" },
        },
        {
          number: 50,
          title: { ko: "위기관리의 프로", en: "Crisis Management Pro" },
          chapter: { ko: "4장 이후", en: "Chapter 4+" },
          location: { ko: "로프웨이 역", en: "Ropeway Station" },
          trigger: { ko: "로프웨이 역의 남자에게 도시락 전달 후 트러블 해결", en: "Hand the bento to the man at the ropeway, then clear his trouble missions." },
          body: { ko: "로프웨이 승강장 앞에 쓰러져 있는 남자에게 다가가면 발생. 「돈가스 도시락」을 건네면 사이고 다이지로와 전투가 되고, 이기면 그가 트러블 미션으로 등장하게 된다. 「오노미치 진가이초의 강적을 쓰러뜨려라 1」과 「2」를 차례로 클리어하고, 사이고에게서 메일이 오면 처음 만났던 로프웨이 승강장으로 돌아가 최종 대결을 벌인다.", en: "Approach the man collapsed outside the ropeway station and hand over a tonkatsu bento; that starts a fight with Daijiro Saigo. Beating him turns him into a trouble mission — clear \"Defeat the Tough Guy of Onomichi Jingaicho 1\" and \"2\", and when he emails you, return to the ropeway station for the rematch that ends it." },
          reward: { ko: "경험치", en: "EXP" },
        },
      ],
    },
    {
      title: { ko: "최종 도전 — 아몬", en: "Final Challenge — Amon" },
      items: [
        {
          number: 51,
          title: { ko: "아몬 죠", en: "Amon Jo" },
          chapter: { ko: "최종 장 이후", en: "Post-final chapter" },
          location: { ko: "아몬의 부유섬", en: "Amon's Floating Island" },
          trigger: { ko: "No.24, No.50 등 전제 클리어 후 아몬 죠와 결전", en: "Clear No.24 and No.50 prerequisites, then duel Jo Amon." },
          body: { ko: "오노미치 진가이초에 있을 때 아몬 죠에게서 메일이 오면 발생. 택시로 「아몬의 부유섬」으로 이동해 아몬 죠와 결전을 벌인다. 발생 조건에는 여러 설이 있으나, 최소한 No.24와 No.50 클리어는 필요한 것으로 보인다. 시리즈 전통대로 최강의 상대이며 난이도 easy에서도 레벨과 조작 숙련도에 따라 크게 고전할 수 있으니, 회복 아이템을 대량으로 사 두고 도전할 것.", en: "While in Onomichi Jingaicho you get an email from Jo Amon; take a taxi to Amon's Floating Island for the duel. The exact trigger is debated, but clearing at least No.24 and No.50 appears to be required. He is the series' traditional superboss and can wall you even on Easy depending on your level and execution, so stock up heavily on healing items first." },
          prereq: { ko: "No.24 + No.50 클리어 (사실상 전 서브 클리어)", en: "Clear No.24 + No.50 (effectively all substories)" },
          reward: { ko: "경험치", en: "EXP" },
        },
      ],
    },
  ],
};
