import type { CollectiblesData } from "./types";

export const judgment: CollectiblesData = {
  appId: 2058180,
  categories: [
    {
      slug: "friend-events",
      title: { ko: "친구 이벤트 — 50명 전원", en: "Friend Events — All 50 NPCs" },
      summary: {
        ko: "카무로쵸의 친구 후보 NPC 50명과 친밀도를 최대치까지 올려 친구 이벤트를 모두 시청합니다. 친구를 만들면 평판이 올라 사이드 케이스가 추가로 풀리고, 전투 중 회복·지원도 받을 수 있습니다.",
        en: "Befriend all 50 NPCs across Kamurocho. Each new friend raises your reputation, unlocking extra side cases and giving you in-battle support and heals.",
      },
      tips: [
        { ko: "악수 아이콘이 표시된 위치에서 발생 조건을 만족시키면 이벤트가 시작됩니다. 발생하지 않으면 메인 스토리를 조금 더 진행하거나 시간대를 바꿔 보세요.", en: "Trigger at the handshake icon on the map once the listed condition is met. If nothing happens, push the story further or swap time of day." },
        { ko: "가게에서 발생하는 친구는 동일 가게에서 주문/구입을 반복해야 호감도가 오릅니다.", en: "Shop-bound friends gain affinity only by repeating purchases at their venue." },
      ],
      source: {
        label: "gamewith.jp — Judgment 친구 이벤트",
        url: "https://gamewith.jp/judgeeyes/article/show/134523",
      },
      items: [
      {
        number: 1,
        title: { ko: "츠쿠모 세이이치", en: "Seiichi Tsukumo" },
        location: { ko: "넷카페 mantai", en: "Internet Cafe Mantai" },
        body: { ko: "스토리 진행 중 반드시 친구가 됨", en: "Becomes a friend automatically during the main story" },
      },
      {
        number: 2,
        title: { ko: "노노무라 소타", en: "Sota Nonomura" },
        location: { ko: "POPPO 시치후쿠 거리 동쪽점", en: "POPPO Shichifuku Street East" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 3,
        title: { ko: "아사무라 세이시로", en: "Seishiro Asamura" },
        location: { ko: "POPPO 시치후쿠 거리 서쪽점", en: "POPPO Shichifuku Street West" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 4,
        title: { ko: "이이노 아리스", en: "Alice Iino" },
        location: { ko: "POPPO 쇼와 거리점", en: "POPPO Showa Street" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to her to trigger the event" },
      },
      {
        number: 5,
        title: { ko: "드웨인 크루즈", en: "Dwayne Cruz" },
        location: { ko: "POPPO 천하일 거리점", en: "POPPO Tenkaichi Street" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 6,
        title: { ko: "노리모토 카즈히사", en: "Kazuhisa Norimoto" },
        location: { ko: "카페 미죠레", en: "Cafe Mijolet" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 7,
        title: { ko: "시마 미하루", en: "Miharu Shima" },
        location: { ko: "카페 미죠레", en: "Cafe Mijolet" },
        body: { ko: "노리모토 카즈히사와 교류한 후 등장 → 말을 걸기", en: "Appears after befriending Kazuhisa Norimoto; talk to her" },
      },
      {
        number: 8,
        title: { ko: "이이다 하나에", en: "Hanae Iida" },
        location: { ko: "스마일 버거 극장 북서점", en: "Smile Burger Theater Northwest" },
        body: { ko: "메뉴 구입", en: "Purchase a menu item" },
      },
      {
        number: 9,
        title: { ko: "토미오카 리에", en: "Rie Tomioka" },
        location: { ko: "스마일 버거 나카미치 거리점", en: "Smile Burger Nakamichi Street" },
        body: { ko: "메뉴 구입 후 가게 밖으로 나가기", en: "Purchase a menu item, then leave the store" },
      },
      {
        number: 10,
        title: { ko: "슈 하오유", en: "Shu Haoyu" },
        location: { ko: "아카우시마루 천하일 거리점", en: "Akaushimaru Tenkaichi Street" },
        body: { ko: "메뉴 구입", en: "Purchase a menu item" },
      },
      {
        number: 11,
        title: { ko: "나스카와 히로토", en: "Hiroto Nasukawa" },
        location: { ko: "아카우시마루 호텔가점", en: "Akaushimaru Hotel District" },
        body: { ko: "메뉴 구입", en: "Purchase a menu item" },
      },
      {
        number: 12,
        title: { ko: "하타노 슈이치", en: "Shuichi Hatano" },
        location: { ko: "요시다 배팅 센터", en: "Yoshida Batting Center" },
        body: { ko: "배팅에 도전 후 말을 걸기", en: "Try batting, then talk to him" },
      },
      {
        number: 13,
        title: { ko: "요시다 지배인", en: "Manager Yoshida" },
        location: { ko: "요시다 배팅 센터", en: "Yoshida Batting Center" },
        body: { ko: "모든 코스를 클리어", en: "Clear every course" },
      },
      {
        number: 14,
        title: { ko: "마츠자키 후미오", en: "Fumio Matsuzaki" },
        location: { ko: "칸라이", en: "Kanrai" },
        body: { ko: "입장 시 남자가 나와 이벤트 발생", en: "Upon entering, a man appears and the event triggers" },
      },
      {
        number: 15,
        title: { ko: "사쿠마 마미", en: "Mami Sakuma" },
        location: { ko: "M SIDE CAFE", en: "M Side Cafe" },
        body: { ko: "케이크류 구입", en: "Purchase a cake" },
      },
      {
        number: 16,
        title: { ko: "우오즈미 켄타", en: "Kenta Uozumi" },
        location: { ko: "스시 긴", en: "Sushi Gin" },
        body: { ko: "니기리류 구입", en: "Purchase nigiri sushi" },
      },
      {
        number: 17,
        title: { ko: "이치노세 쿠니오", en: "Kunio Ichinose" },
        location: { ko: "이키나리! 스테이크", en: "Ikinari! Steak" },
        body: { ko: "메뉴 구입", en: "Purchase a menu item" },
      },
      {
        number: 18,
        title: { ko: "사나다 카에데", en: "Kaede Sanada" },
        location: { ko: "QUADRA GARDEN", en: "Quadra Garden" },
        body: { ko: "호텔 안으로 들어가기", en: "Enter the hotel" },
      },
      {
        number: 19,
        title: { ko: "네코미야 쇼이치", en: "Shoichi Nekomiya" },
        location: { ko: "나카미치 거리 뒷골목", en: "Nakamichi Street Back Alley" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 20,
        title: { ko: "타치바나 유리카", en: "Yurika Tachibana" },
        location: { ko: "마작 라라바이", en: "Mahjong Lullaby" },
        body: { ko: "마작을 플레이하면 이벤트 발생", en: "Play mahjong to trigger the event" },
      },
      {
        number: 21,
        title: { ko: "큐슈 이치반보시 점장", en: "Kyushu Ichibanboshi Manager" },
        location: { ko: "큐슈 이치반보시", en: "Kyushu Ichibanboshi" },
        body: { ko: "메뉴 구입", en: "Purchase a menu item" },
      },
      {
        number: 22,
        title: { ko: "김 원선", en: "Wonseon Kim" },
        location: { ko: "규유엔", en: "Gyuyuen" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 23,
        title: { ko: "타나고 켄지", en: "Kenji Tanago" },
        location: { ko: "시치후쿠 파크", en: "Shichifuku Park" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 24,
        title: { ko: "스사키 료", en: "Ryo Susaki" },
        location: { ko: "아텐시", en: "Atenshi" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 25,
        title: { ko: "타시로 군", en: "Tashiro" },
        location: { ko: "에메랄드 힐즈 앞", en: "In front of Emerald Hills" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 26,
        title: { ko: "라이언 아코스타", en: "Ryan Acosta" },
        location: { ko: "센료 거리", en: "Senryo Street" },
        body: { ko: "센료 거리를 지나가면 이벤트 발생", en: "Pass through Senryo Street to trigger the event" },
      },
      {
        number: 27,
        title: { ko: "사오토메 요스케", en: "Yosuke Saotome" },
        location: { ko: "시치후쿠 거리", en: "Shichifuku Street" },
        body: { ko: "시치후쿠 거리의 무료 안내소에 들어가면 이벤트 발생", en: "Enter the free info center on Shichifuku Street to trigger the event" },
      },
      {
        number: 28,
        title: { ko: "이노사카 슌", en: "Shun Inosaka" },
        location: { ko: "시치후쿠 거리", en: "Shichifuku Street" },
        body: { ko: "경찰로부터 도망쳐 본 적이 있는 상태에서 시치후쿠 거리를 지나가면 이벤트 발생", en: "After having escaped from the police, pass through Shichifuku Street to trigger the event" },
      },
      {
        number: 29,
        title: { ko: "타케미츠 점장", en: "Takemitsu Manager" },
        location: { ko: "시치후쿠 거리 동쪽 타케미츠 앞", en: "In front of Takemitsu, Shichifuku Street East" },
        body: { ko: "타케미츠 앞에 있는 야쿠자에게 말을 걸면 이벤트 발생", en: "Talk to the yakuza in front of Takemitsu to trigger the event" },
      },
      {
        number: 30,
        title: { ko: "니이사토 마도카", en: "Madoka Niisato" },
        location: { ko: "애플 파이", en: "Apple Pie" },
        body: { ko: "애플 파이의 접수원 남자에게 말을 걸면 이벤트 발생", en: "Talk to the man at the Apple Pie reception to trigger the event" },
      },
      {
        number: 31,
        title: { ko: "아메미야 사쿠라", en: "Sakura Amemiya" },
        location: { ko: "핑크 거리", en: "Pink Street" },
        body: { ko: "핑크 거리를 지나가면 이벤트 발생", en: "Pass through Pink Street to trigger the event" },
      },
      {
        number: 32,
        title: { ko: "오노데라 모리오", en: "Morio Onodera" },
        location: { ko: "오노데라 상점", en: "Onodera Shop" },
        body: { ko: "시치후쿠 거리 서쪽의 '아동공원' 맨홀에서 오노데라 상점으로 이동해 말을 걸면 이벤트 발생", en: "Take the manhole at the Children's Park west of Shichifuku Street to the Onodera Shop, then talk to him to trigger the event" },
      },
      {
        number: 33,
        title: { ko: "마리 누나", en: "Sister Mari" },
        location: { ko: "BAR 텐더", en: "Bar Tender" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to her to trigger the event" },
      },
      {
        number: 34,
        title: { ko: "타테야마 노보루", en: "Noboru Tateyama" },
        location: { ko: "쇼와 거리 서쪽", en: "Showa Street West" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 35,
        title: { ko: "후지모리 스스무", en: "Susumu Fujimori" },
        location: { ko: "쇼와 거리 서쪽", en: "Showa Street West" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      {
        number: 36,
        title: { ko: "코에즈카 토시로", en: "Toshiro Koezuka" },
        location: { ko: "야가미 탐정 사무소 앞", en: "In front of Yagami Detective Agency" },
        body: { ko: "토미오카 리에와 친구가 된 후 야가미 탐정 사무소 앞에서 말을 걸면 이벤트 발생", en: "After befriending Rie Tomioka, talk to him in front of Yagami Detective Agency to trigger the event" },
      },
      {
        number: 37,
        title: { ko: "후루야 야스히로", en: "Yasuhiro Furuya" },
        location: { ko: "베테 키친", en: "Vette Kitchen" },
        body: { ko: "메뉴 구입", en: "Purchase a menu item" },
      },
      {
        number: 38,
        title: { ko: "이노세 타케오", en: "Takeo Inose" },
        location: { ko: "와일드 잭슨", en: "Wild Jackson" },
        body: { ko: "메뉴 구입", en: "Purchase a menu item" },
      },
      {
        number: 39,
        title: { ko: "에비스야 점장 후쿠즈", en: "Ebisuya Manager Fukuzu" },
        location: { ko: "에비스야", en: "Ebisuya" },
        body: { ko: "시라누이 후카의 그림을 1장 이상 소지한 상태에서 말을 걸기", en: "Talk to him while holding at least one painting of Fuka Shiranui" },
      },
      {
        number: 40,
        title: { ko: "반탐의 마스터", en: "Master of Bantam" },
        location: { ko: "반탐", en: "Bantam" },
        body: { ko: "반탐의 마스터에게 말을 걸기", en: "Talk to the master of Bantam" },
      },
      {
        number: 41,
        title: { ko: "카타기리 타쿠미", en: "Takumi Katagiri" },
        location: { ko: "셸락", en: "Shellac" },
        body: { ko: "셸락에서 말을 걸기", en: "Talk to him at Shellac" },
      },
      {
        number: 42,
        title: { ko: "히라누마 노보루", en: "Noboru Hiranuma" },
        location: { ko: "셸락", en: "Shellac" },
        body: { ko: "셸락에서 말을 걸기", en: "Talk to him at Shellac" },
      },
      {
        number: 43,
        title: { ko: "류구죠의 선인・이야마", en: "Iyama, Sage of Ryugujo" },
        location: { ko: "류구죠 4F", en: "Ryugujo 4F" },
        body: { ko: "메인 스토리 중 이벤트 발생", en: "Event occurs during the main story" },
      },
      {
        number: 44,
        title: { ko: "데구치 히데아키", en: "Hideaki Deguchi" },
        location: { ko: "스타더스트 앞", en: "In front of Stardust" },
        body: { ko: "세이야에게 말을 걸기", en: "Talk to Seiya" },
      },
      {
        number: 45,
        title: { ko: "세바스티안 해튼", en: "Sebastian Hatton" },
        location: { ko: "드론 레이스 회장", en: "Drone Race Venue" },
        body: { ko: "드론 레이스 비기너 리그 우승 후 회장에서 말을 걸기", en: "After winning the Drone Race Beginner League, talk to him at the venue" },
      },
      {
        number: 46,
        title: { ko: "테라하라 나오타로", en: "Naotaro Terahara" },
        location: { ko: "르 마르셰", en: "Le Marche" },
        body: { ko: "가게 안에서 말을 걸기", en: "Talk to him inside the store" },
      },
      {
        number: 47,
        title: { ko: "모로호시 고로", en: "Goro Moroboshi" },
        location: { ko: "아동공원 맨홀 내부", en: "Inside the Children's Park manhole" },
        body: { ko: "메인 스토리 중 이벤트 발생", en: "Event occurs during the main story" },
      },
      {
        number: 48,
        title: { ko: "카마구치 이치몬", en: "Ichimon Kamaguchi" },
        location: { ko: "제니가메 금융 '애플 파이' 앞", en: "In front of Zenigame Finance 'Apple Pie'" },
        body: { ko: "이벤트 발생", en: "The event triggers" },
      },
      {
        number: 49,
        title: { ko: "엉덩이가 멋진 여자", en: "Woman with a Nice Butt" },
        location: { ko: "라 망 (코이뇨보의 지하)", en: "La Main (basement of Koinyobo)" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to her to trigger the event" },
      },
      {
        number: 50,
        title: { ko: "사가라 토시카즈", en: "Toshikazu Sagara" },
        location: { ko: "카페 알프스", en: "Cafe Alps" },
        body: { ko: "말을 걸면 이벤트 발생", en: "Talk to him to trigger the event" },
      },
      ],
    },
    {
      slug: "side-cases",
      title: { ko: "사이드 케이스 50건", en: "Side Cases — All 50" },
      summary: {
        ko: "야가미 탐정 사무소·바 텐더·겐다 법률사무소에서 받거나 메인 스토리·거리에서 발생하는 사이드 케이스 50건의 발생 조건과 장소를 정리했습니다. 도시 평판 레벨이 핵심 게이트입니다.",
        en: "Side cases triggered from Yagami Detective Agency, Bar Tender, Genda Law Office, or out in the world. 50 entries with chapter + city-reputation conditions.",
      },
      tips: [
        { ko: "평판은 사이드 케이스를 클리어할 때마다 오릅니다. Lv.15·25·35·45 같은 게이트가 많아 평판 우선 정리가 효율적입니다.", en: "City reputation rises with each side case cleared. Many gate at Lv.15/25/35/45, so frontload them." },
        { ko: "여자친구 전제 케이스 일부는 그녀 만들기 진행이 선행 조건입니다.", en: "A handful require dating route progress as prerequisite." },
      ],
      source: {
        label: "gamewith.jp — Judgment 사이드 케이스",
        url: "https://gamewith.jp/judgeeyes/article/show/134172",
      },
      items: [
      {
        number: 1,
        title: { ko: "변태 삼총사: 팬티 교수", en: "Pervert Trio: Professor Panty (Catch the Underwear Thief)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "2장 도중까지 클리어 / 여자친구 전제 케이스", en: "Clear partway into Chapter 2; girlfriend route prerequisite" },
      },
      {
        number: 2,
        title: { ko: "변태 삼총사: 엉덩이 마이스터", en: "Pervert Trio: The Butt Meister (Catch the Groper)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "‘변태 삼총사: 팬티 교수’ 클리어 / 2장 도중까지 클리어 / 도시 평판 Lv.5 이상 / 여자친구 전제 케이스", en: "Clear 'Pervert Trio: Professor Panty'; clear partway into Chapter 2; City Reputation Lv.5+; girlfriend route prerequisite" },
      },
      {
        number: 3,
        title: { ko: "변태 삼총사: 엿보기 판사", en: "Pervert Trio: The Peeping Judge (A Discreet Consultation About a Pervert)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "‘변태 삼총사: 엉덩이 마이스터’ 클리어 / ‘다이아몬드 눈을 가진 고양이’ 클리어 / 2장 도중까지 클리어 / 도시 평판 Lv.15 이상", en: "Clear 'Pervert Trio: The Butt Meister'; clear 'The Cat with Diamond Eyes'; clear partway into Chapter 2; City Reputation Lv.15+" },
      },
      {
        number: 4,
        title: { ko: "사라진 스카잔의 행방", en: "Where Did the Sukajan Go?" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "2장 도중까지 클리어 (게시판 해금 직후)", en: "Clear partway into Chapter 2 (right after the request board unlocks)" },
      },
      {
        number: 5,
        title: { ko: "미스터리 작가의 도전장", en: "The Mystery Writer's Challenge (A Publishing-Related Request)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "2장 도중까지 클리어 / 도시 평판 Lv.10 이상", en: "Clear partway into Chapter 2; City Reputation Lv.10+" },
      },
      {
        number: 6,
        title: { ko: "속・미스터리 작가의 도전장", en: "The Mystery Writer's Challenge II (Another Publishing Request)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "‘미스터리 작가의 도전장’ 클리어 / 약간의 시간 경과 / 2장 이후 / 도시 평판 Lv.20 이상", en: "Clear 'The Mystery Writer's Challenge'; let some time pass; Chapter 2 onward; City Reputation Lv.20+" },
      },
      {
        number: 7,
        title: { ko: "속속・미스터리 작가의 도전장", en: "The Mystery Writer's Challenge III (Yet Another Publishing Request)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "‘속・미스터리 작가의 도전장’ 클리어 / 약간의 시간 경과 / 메인 스토리 진행 / 도시 평판 Lv.30 이상", en: "Clear 'The Mystery Writer's Challenge II'; let some time pass; advance the main story; City Reputation Lv.30+" },
      },
      {
        number: 8,
        title: { ko: "나를 찾아줘", en: "Find Me (Please Find My Son)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "2장 도중까지 클리어 / 도시 평판 Lv.25 이상", en: "Clear partway into Chapter 2; City Reputation Lv.25+" },
      },
      {
        number: 9,
        title: { ko: "속・나를 찾아줘", en: "Find Me II (Find My Son Again)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "‘나를 찾아줘’ 클리어 / 메인 스토리 진행 / 도시 평판 Lv.35 이상", en: "Clear 'Find Me'; advance the main story; City Reputation Lv.35+" },
      },
      {
        number: 10,
        title: { ko: "속속・나를 찾아줘", en: "Find Me III (Find My Son Yet Again)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "‘속・나를 찾아줘’ 클리어 / 메인 스토리 진행 / 도시 평판 Lv.45 이상", en: "Clear 'Find Me II'; advance the main story; City Reputation Lv.45+" },
      },
      {
        number: 11,
        title: { ko: "나의 사랑스러운 부하", en: "My Adorable Subordinate (Please Find My Subordinate)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "2장 도중까지 클리어 / 도시 평판 Lv.5 이상", en: "Clear partway into Chapter 2; City Reputation Lv.5+" },
      },
      {
        number: 12,
        title: { ko: "케이힌 동맹의 역습", en: "The Keihin Gang's Counterattack (Catch the Precious Rat)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "극장 앞 광장에서 발포 이벤트 시청 / 위험도를 올려 케이힌 동맹 간부 4명 격파 / 메인 스토리 진행 / 도시 평판 Lv.50", en: "Witness the gunfire event at the theater plaza; raise the threat level and defeat the four Keihin Gang executives; advance the main story; City Reputation Lv.50" },
      },
      {
        number: 13,
        title: { ko: "마지막 의뢰 (도전장)", en: "The Final Request (The Challenge)" },
        location: { ko: "야가미 탐정 사무소", en: "Yagami Detective Agency" },
        body: { ko: "사이드 케이스 49건 클리어 / 메인 스토리 진행 / 도시 평판 Lv.50", en: "Clear 49 side cases; advance the main story; City Reputation Lv.50" },
      },
      {
        number: 14,
        title: { ko: "태양과 뱀파이어", en: "The Sun and the Vampire (A Showbiz Job)" },
        location: { ko: "바 텐더", en: "Bar Tender" },
        body: { ko: "3장 도중까지 클리어", en: "Clear partway into Chapter 3" },
      },
      {
        number: 15,
        title: { ko: "보도 카메라맨, 야가미", en: "Press Photographer Yagami" },
        location: { ko: "바 텐더", en: "Bar Tender" },
        body: { ko: "‘허니트랩’ 클리어 / 히라누마와 친해지기 / 메인 스토리 진행 / 도시 평판 Lv.35 이상", en: "Clear 'Honey Trap'; befriend Hiranuma; advance the main story; City Reputation Lv.35+" },
      },
      {
        number: 16,
        title: { ko: "레이즈 모럴리티", en: "Raise Morality (Sexual Harassment Investigation)" },
        location: { ko: "바 텐더", en: "Bar Tender" },
        body: { ko: "메인 스토리 진행 / 도시 평판 Lv.45 이상", en: "Advance the main story; City Reputation Lv.45+" },
      },
      {
        number: 17,
        title: { ko: "허니트랩", en: "Honey Trap (Investigate the Woman Who Set Him Up)" },
        location: { ko: "바 텐더", en: "Bar Tender" },
        body: { ko: "‘변태 삼총사: 팬티 교수’ 클리어 / 6장 이후 / 도시 평판 Lv.15 이상", en: "Clear 'Pervert Trio: Professor Panty'; Chapter 6 onward; City Reputation Lv.15+" },
      },
      {
        number: 18,
        title: { ko: "잉어 아내 회 사건", en: "The Carp Wife Sashimi Case (Identify the Dismemberment Culprit)" },
        location: { ko: "바 텐더", en: "Bar Tender" },
        body: { ko: "6장 이후 / 도시 평판 Lv.25 이상", en: "Chapter 6 onward; City Reputation Lv.25+" },
      },
      {
        number: 19,
        title: { ko: "다이아몬드 눈을 가진 고양이", en: "The Cat with Diamond Eyes (Search for a Troublesome Cat)" },
        location: { ko: "바 텐더", en: "Bar Tender" },
        body: { ko: "3장 도중까지 클리어 / 도시 평판 Lv.5 이상", en: "Clear partway into Chapter 3; City Reputation Lv.5+" },
      },
      {
        number: 20,
        title: { ko: "맡기고 싶은 일이 있다", en: "I Have a Job for You" },
        location: { ko: "바 텐더", en: "Bar Tender" },
        body: { ko: "3장 도중까지 클리어 (스토리 진행 중 발생)", en: "Clear partway into Chapter 3 (triggered during story progression)" },
      },
      {
        number: 21,
        title: { ko: "유령 매물", en: "The Haunted Property (Ghost Capture Request)" },
        location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
        body: { ko: "2장 도중까지 클리어", en: "Clear partway into Chapter 2" },
      },
      {
        number: 22,
        title: { ko: "탐정의 방식", en: "A Detective's Way (Second Infidelity Investigation)" },
        location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
        body: { ko: "2장 이후 / 도시 평판 Lv.40 이상", en: "Chapter 2 onward; City Reputation Lv.40+" },
      },
      {
        number: 23,
        title: { ko: "돈거래는 불화의 씨앗", en: "Money Lending Breeds Discord (Search for the Missing Nephew)" },
        location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
        body: { ko: "2장 이후 / 도시 평판 Lv.30 이상", en: "Chapter 2 onward; City Reputation Lv.30+" },
      },
      {
        number: 24,
        title: { ko: "아들의 며느리는 악마?", en: "Is My Son's Wife a Devil? (Background Check on the Daughter-in-Law)" },
        location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
        body: { ko: "2장 이후 / 도시 평판 Lv.20 이상", en: "Chapter 2 onward; City Reputation Lv.20+" },
      },
      {
        number: 25,
        title: { ko: "남편의 외출지", en: "Where the Husband Goes (Infidelity Investigation)" },
        location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
        body: { ko: "2장 도중까지 클리어 (스토리 진행 중 발생)", en: "Clear partway into Chapter 2 (triggered during story progression)" },
      },
      {
        number: 26,
        title: { ko: "사오리 씨의 생크림 케이크 재판", en: "Saori-san's Fresh Cake Trial" },
        location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
        body: { ko: "4장에서 발생 (스토리 진행 중 발생)", en: "Triggers in Chapter 4 (during story progression)" },
      },
      {
        number: 27,
        title: { ko: "숙명의 사제 대결", en: "The Fated Master-Disciple Duel" },
        location: { ko: "겐다 법률사무소", en: "Genda Law Office" },
        body: { ko: "4장에서 발생 (스토리 진행 중 발생)", en: "Triggers in Chapter 4 (during story progression)" },
      },
      {
        number: 28,
        title: { ko: "개막, 드론 레이스!", en: "Drone Race Showdown!" },
        location: { ko: "스토리 진행 중", en: "Story-triggered" },
        body: { ko: "2장에서 발생", en: "Triggers in Chapter 2" },
      },
      {
        number: 29,
        title: { ko: "VR 살롱 파라다이스 오픈", en: "VR Salon Paradise Opens" },
        location: { ko: "스토리 진행 중", en: "Story-triggered" },
        body: { ko: "3장에서 발생", en: "Triggers in Chapter 3" },
      },
      {
        number: 30,
        title: { ko: "마리 누나의 비밀", en: "Mari's Secret" },
        location: { ko: "스토리 진행 중", en: "Story-triggered" },
        body: { ko: "4장에서 발생", en: "Triggers in Chapter 4" },
      },
      {
        number: 31,
        title: { ko: "카이토의 파트너", en: "Kaito's Partner" },
        location: { ko: "스토리 진행 중", en: "Story-triggered" },
        body: { ko: "6장에서 발생", en: "Triggers in Chapter 6" },
      },
      {
        number: 32,
        title: { ko: "정의의 히어로・카이토 마사하루", en: "Hero of Justice: Masaharu Kaito" },
        location: { ko: "스토리 진행 중", en: "Story-triggered" },
        body: { ko: "7장에서 발생", en: "Triggers in Chapter 7" },
      },
      {
        number: 33,
        title: { ko: "재앙의 정체는?", en: "What's Behind the Misfortune?" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "5장 이후 / 여자친구 전제 케이스", en: "Chapter 5 onward; girlfriend route prerequisite" },
      },
      {
        number: 34,
        title: { ko: "속・재앙의 정체는?", en: "What's Behind the Misfortune? II" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "7장 이후 / ‘재앙의 정체는?’ 클리어 / 여자친구 전제 케이스", en: "Chapter 7 onward; clear 'What's Behind the Misfortune?'; girlfriend route prerequisite" },
      },
      {
        number: 35,
        title: { ko: "속속・재앙의 정체는?", en: "What's Behind the Misfortune? III" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "9장 이후 / ‘속・재앙의 정체는?’ 클리어 / 여자친구 전제 케이스", en: "Chapter 9 onward; clear 'What's Behind the Misfortune? II'; girlfriend route prerequisite" },
      },
      {
        number: 36,
        title: { ko: "카무로쵸의 폭탄마", en: "The Kamurocho Bomber" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "2장 도중까지 클리어 / 맵 하단 뒷골목 (중앙거리와 핑크거리 사이)에서 발생", en: "Clear partway into Chapter 2; triggers in the back alley at the bottom of the map (between Nakamichi St. and Pink St.)" },
      },
      {
        number: 37,
        title: { ko: "속・카무로쵸의 폭탄마", en: "The Kamurocho Bomber II" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "4장 이후 / ‘카무로쵸의 폭탄마’ 클리어", en: "Chapter 4 onward; clear 'The Kamurocho Bomber'" },
      },
      {
        number: 38,
        title: { ko: "속속・카무로쵸의 폭탄마", en: "The Kamurocho Bomber III" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "6장 이후 / ‘속・카무로쵸의 폭탄마’ 클리어", en: "Chapter 6 onward; clear 'The Kamurocho Bomber II'" },
      },
      {
        number: 39,
        title: { ko: "꿈의 도중", en: "Mid-Dream" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "3장 이후 / 여자친구 전제 케이스", en: "Chapter 3 onward; girlfriend route prerequisite" },
      },
      {
        number: 40,
        title: { ko: "산들바람과 함께 사라지다", en: "Gone with the Breeze" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "3장 이후", en: "Chapter 3 onward" },
      },
      {
        number: 41,
        title: { ko: "속・산들바람과 함께 사라지다", en: "Gone with the Breeze II" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "5장 이후 / ‘산들바람과 함께 사라지다’ 클리어", en: "Chapter 5 onward; clear 'Gone with the Breeze'" },
      },
      {
        number: 42,
        title: { ko: "속속・산들바람과 함께 사라지다", en: "Gone with the Breeze III" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "9장 이후 / ‘속・산들바람과 함께 사라지다’ 클리어", en: "Chapter 9 onward; clear 'Gone with the Breeze II'" },
      },
      {
        number: 43,
        title: { ko: "스마트폰 탐정", en: "Smartphone Detective" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "8장 이후 (야간) / 여자친구 전제 케이스", en: "Chapter 8 onward (nighttime); girlfriend route prerequisite" },
      },
      {
        number: 44,
        title: { ko: "변태왕: 자이언트 임팩트", en: "Pervert King: Giant Impact" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "8장 이후 / ‘변태 삼총사: 엿보기 판사’ 클리어 / 여자친구 전제 케이스", en: "Chapter 8 onward; clear 'Pervert Trio: The Peeping Judge'; girlfriend route prerequisite" },
      },
      {
        number: 45,
        title: { ko: "바가지 술집", en: "The Rip-Off Bar" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "4장 이후 / 챔피언 거리에 가면 발생", en: "Chapter 4 onward; triggers when you visit Champion District" },
      },
      {
        number: 46,
        title: { ko: "탈옥수", en: "The Escaped Convict" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "8장 이후", en: "Chapter 8 onward" },
      },
      {
        number: 47,
        title: { ko: "와이프의 생일", en: "The Wife's Birthday" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "메인 스토리 진행", en: "Advance the main story" },
      },
      {
        number: 48,
        title: { ko: "강도범 오노 미치오", en: "The Robber: Michio Ono" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "메인 스토리 진행", en: "Advance the main story" },
      },
      {
        number: 49,
        title: { ko: "마모루의 실종?", en: "Mamoru's Disappearance?" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "메인 스토리 진행 / ‘유령 매물’ 클리어 / ‘속속・산들바람과 함께 사라지다’ 클리어 / 위 두 건 클리어 후 야가미 탐정 사무소에 들어가기", en: "Advance the main story; clear 'The Haunted Property'; clear 'Gone with the Breeze III'; after clearing both, enter the Yagami Detective Agency" },
      },
      {
        number: 50,
        title: { ko: "벼랑 끝의 조사 의뢰", en: "Cliffside Investigation Request" },
        location: { ko: "거리 트리거", en: "Street trigger" },
        body: { ko: "메인 스토리 진행", en: "Advance the main story" },
      },
      ],
    },
    {
      slug: "drone-races",
      title: { ko: "드론 레이스 — 모든 코스 1위", en: "Drone Races — 1st in Every Course" },
      summary: {
        ko: "드론 카페에서 모든 코스를 1위로 클리어합니다. 부품을 강화해야 후반 코스 가능. 추가 코스는 챕터 진행으로 풀립니다.",
        en: "Win every drone race course. Upgrade parts before late courses; new tracks unlock per chapter.",
      },
    },
    {
      slug: "vr-club",
      title: { ko: "VR 클럽 — 모든 게임 클리어", en: "VR Club Games" },
      summary: {
        ko: "VR 클럽에서 모든 미니게임을 클리어합니다. 푸루리에 슈팅·VR 퍼즐 등이 포함됩니다.",
        en: "Clear every VR Club game — shooting, puzzles, and rhythm boards.",
      },
    },
    {
      slug: "photo-rumors",
      title: { ko: "포토 의뢰 50건", en: "Photo Rumors (50)" },
      summary: {
        ko: "카무로쵸 곳곳에서 발생하는 잠복·사진 의뢰를 50건 이상 완수합니다. 야가미 탐정 사무소 게시판에서 신규 의뢰를 확인하세요.",
        en: "Clear 50+ stakeout/photo rumor cases. New ones post on the agency board as the story advances.",
      },
    },
    {
      slug: "mole-investigations",
      title: { ko: "잠입 수사 — 모두 클리어", en: "Mole Investigations" },
      summary: {
        ko: "스토리 잠입 수사 미션을 모두 진행합니다. 놓치기 쉬운 항목이 일부 있어 챕터별로 챙기는 편이 안전합니다.",
        en: "Clear every Mole Investigation mission. Some are chapter-missable — handle them as they appear.",
      },
    },
    {
      slug: "dialog-choices",
      title: { ko: "이면 보고서 — 챕터 8 대화 선택", en: "Investigation Reports — Chapter 8 Dialogs" },
      summary: {
        ko: "챕터 8의 핵심 대화 이벤트에서 정답 선택지를 첫 시도에 모두 맞춰야 합니다. 놓치기 쉬운 업적이라 사전에 수동 세이브를 분리해 두세요.",
        en: "Pick every correct dialog option in Chapter 8 on the first try. Missable — keep a separate manual save.",
      },
    },
  ],
};
