import type { CollectiblesData } from "./types";

export const judgment: CollectiblesData = {
  appId: 2058180,
  categories: [
    {
      slug: "side-cases",
      title: { ko: "사건 파일 50건", en: "Side Cases (50)" },
      summary: {
        ko: "카무로초 곳곳에서 발생하는 의뢰형 사건을 50건 해결합니다. 10건 시 「On the Case」, 30건 시 「Local Detective」, 전부 시 「Got to the Bottom of It」 업적이 발동합니다. 미달성 요소는 없습니다.",
        en: "Solve 50 request-based side cases around Kamurocho. 10 unlocks 'On the Case', 30 unlocks 'Local Detective', all 50 unlocks 'Got to the Bottom of It'. None are missable.",
      },
      tips: [
        { ko: "겐다 법률사무소·야가미 탐정사무소·바텐더 세 곳에서 대부분의 사건이 시작되며, 나머지는 거리를 돌아다니다 자동 발생합니다.", en: "Most cases start at the Genda Law Office, Yagami Detective Agency, or the bar tender — the rest trigger automatically while exploring the city." },
        { ko: "「도전」(49건 완료 필요)과 「미싱 다이아몬드」(겐다 의뢰, 후반)는 다른 사건들을 먼저 끝내야 열립니다.", en: "'A Final Request' (needs 49 other cases) and 'The Missing Diamond' (Genda's late-game request) only unlock after most others are done." },
      ],
      source: { label: "PowerPyx — Judgment Side Cases Walkthrough", url: "https://www.powerpyx.com/judgment-side-cases-walkthrough/" },
      items: [
        { number: 1, title: { ko: "불륜 조사", en: "Infidelity Investigation" }, location: { ko: "겐다 법률사무소", en: "Genda Law Office" }, prereq: { ko: "챕터 2, 필수 진행", en: "Chapter 2, required" } },
        { number: 2, title: { ko: "두 번째 불륜 조사", en: "Second Infidelity Investigation" }, location: { ko: "겐다 법률사무소", en: "Genda Law Office" } },
        { number: 3, title: { ko: "행방불명 조카 찾기", en: "Searching for Missing Nephew" }, location: { ko: "겐다 법률사무소", en: "Genda Law Office" } },
        { number: 4, title: { ko: "유령 포획 의뢰", en: "Ghost Capture Request" }, location: { ko: "겐다 법률사무소", en: "Genda Law Office" } },
        { number: 5, title: { ko: "며느리 신원 조사", en: "Background Investigation of My Son's Wife" }, location: { ko: "겐다 법률사무소", en: "Genda Law Office" } },
        { number: 6, title: { ko: "정의는 달콤하게", en: "Justice is Sweet" }, location: { ko: "겐다 법률사무소", en: "Genda Law Office" }, prereq: { ko: "챕터 4, 필수 진행", en: "Chapter 4, required" } },
        { number: 7, title: { ko: "법의 고리", en: "The Circle of Law" }, location: { ko: "겐다 법률사무소", en: "Genda Law Office" }, prereq: { ko: "챕터 4, 필수 진행", en: "Chapter 4, required" } },
        { number: 8, title: { ko: "팬티 도둑이 출몰한다!", en: "There's a Panty Thief on the Loose!" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 9, title: { ko: "내 재킷 어디 갔지?", en: "Where'd My Jacket Go?" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 10, title: { ko: "치한이 출몰한다!", en: "There's a Groper on the Loose!" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 11, title: { ko: "변태에 대해 이야기해보자", en: "Let's Chat About a Pervert" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 12, title: { ko: "출판사의 의뢰", en: "A Publisher's Request" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 13, title: { ko: "또 다른 사건!", en: "Another Mystery Event!" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 14, title: { ko: "마지막 사건", en: "A Final Event" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 15, title: { ko: "부하가 사라졌어", en: "My Subordinate is Missing" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 16, title: { ko: "황금 쥐", en: "A Golden Mouse" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 17, title: { ko: "아들을 찾아주세요", en: "Please Find My Son" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 18, title: { ko: "아들을 다시 찾아주세요", en: "Please Find My Son Again" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 19, title: { ko: "아들을 또 찾아주세요", en: "Please Find My Son (Again)" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" } },
        { number: 20, title: { ko: "도전", en: "A Final Request" }, location: { ko: "야가미 탐정사무소", en: "Yagami Detective Agency" }, prereq: { ko: "다른 사건 49건 완료 필요", en: "Requires 49 other cases completed" } },
        { number: 21, title: { ko: "가면 아래", en: "Underneath the Mask" }, location: { ko: "바텐더", en: "Bar Tender" }, prereq: { ko: "챕터 3, 필수 진행", en: "Chapter 3, required" } },
        { number: 22, title: { ko: "포토저널리스트 의뢰", en: "Photojournalist Job" }, location: { ko: "바텐더", en: "Bar Tender" } },
        { number: 23, title: { ko: "성희롱 조사", en: "Sexual Harassment Investigation" }, location: { ko: "바텐더", en: "Bar Tender" } },
        { number: 24, title: { ko: "엔터테인먼트 업계 의뢰", en: "Entertainment Industry Job" }, location: { ko: "바텐더", en: "Bar Tender" } },
        { number: 25, title: { ko: "허니 트랩에 걸렸어!", en: "I Got Honey Trapped!" }, location: { ko: "바텐더", en: "Bar Tender" } },
        { number: 26, title: { ko: "너무 많은 살인", en: "So Much Murder" }, location: { ko: "바텐더", en: "Bar Tender" } },
        { number: 27, title: { ko: "귀중한 고양이", en: "A Valuable Cat" }, location: { ko: "바텐더", en: "Bar Tender" } },
        { number: 28, title: { ko: "사교계 인사의 비밀", en: "The Socialite's Secret" }, location: { ko: "바텐더", en: "Bar Tender" }, prereq: { ko: "챕터 4, 필수 진행", en: "Chapter 4, required" } },
        { number: 29, title: { ko: "비둘기가 날아오르다", en: "The Pigeon Takes Flight" }, location: { ko: "카무로초 전역", en: "Around Town" }, prereq: { ko: "챕터 2, 자동 발생", en: "Chapter 2, automatic" } },
        { number: 30, title: { ko: "카무로초의 미친 폭탄마", en: "Kamurocho's Mad Bomber" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 31, title: { ko: "바람과 함께 사라지다", en: "Gone with the Breeze" }, location: { ko: "카무로초 전역", en: "Around Town" }, prereq: { ko: "챕터 3 이후", en: "After Chapter 3" } },
        { number: 32, title: { ko: "돌풍과 함께 사라지다", en: "Gone with the Gust" }, location: { ko: "카무로초 전역", en: "Around Town" }, prereq: { ko: "챕터 4 이후", en: "After Chapter 4" } },
        { number: 33, title: { ko: "VR 주사위 게임", en: "A VR Game of Dice" }, location: { ko: "카무로초 전역", en: "Around Town" }, prereq: { ko: "챕터 3, 자동 발생", en: "Chapter 3, automatic" } },
        { number: 34, title: { ko: "폭탄마가 다시 나타나다", en: "The Mad Bomber Strikes Again" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 35, title: { ko: "함정", en: "Entrapment" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 36, title: { ko: "검은 재앙", en: "The Black Calamity" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 37, title: { ko: "파트너", en: "Partners" }, location: { ko: "카무로초 전역", en: "Around Town" }, prereq: { ko: "챕터 6", en: "Chapter 6" } },
        { number: 38, title: { ko: "폭탄마의 귀환", en: "Return of the Mad Bomber" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 39, title: { ko: "꿈 속에서", en: "Amidst a Dream" }, location: { ko: "극장 앞 광장 (낮 시간대)", en: "Theater Square, daytime" } },
        { number: 40, title: { ko: "돌풍과 함께", en: "Gone with the Gale" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 41, title: { ko: "흑백의 재앙", en: "The Black and White Calamity" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 42, title: { ko: "스마트 워칭", en: "Smart Watching" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 43, title: { ko: "캡틴 캅", en: "Captain Cop" }, location: { ko: "카무로초 전역", en: "Around Town" }, prereq: { ko: "챕터 7", en: "Chapter 7" } },
        { number: 44, title: { ko: "버거 도망자", en: "Burger Fugitive" }, location: { ko: "카무로초 전역", en: "Around Town" }, prereq: { ko: "챕터 8", en: "Chapter 8" } },
        { number: 45, title: { ko: "20분 안에 사라지다", en: "Gone in 20 Minutes" }, location: { ko: "카무로초 전역", en: "Around Town" }, prereq: { ko: "챕터 11", en: "Chapter 11" } },
        { number: 46, title: { ko: "사랑과 광기", en: "Love and Madness" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 47, title: { ko: "최악의 생일", en: "Worst Birthday Ever" }, location: { ko: "칸라이", en: "Kanrai" } },
        { number: 48, title: { ko: "화재의 재앙", en: "The Fire Calamity" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 49, title: { ko: "변태 왕", en: "The Pervert King" }, location: { ko: "카무로초 전역", en: "Around Town" } },
        { number: 50, title: { ko: "오노 미치오 산적", en: "The Ono Michio Bandit" }, location: { ko: "카무로초 전역", en: "Around Town" } },
      ],
    },
    {
      slug: "stray-cats",
      title: { ko: "길고양이 14마리 — 「이런 데 고양이가!」", en: "Stray Cats — All 14 (\"Oh Look, a Cat!\")" },
      summary: {
        ko: "메인 스토리 중 탐색 모드(Active Search)에서 나오는 고양이 14마리를 한 회차 안에 전부 발견해야 업적이 발동합니다. 서브 사건 중 등장하는 고양이는 카운트되지 않습니다.",
        en: "Find all 14 cats that appear during main-story Active Search sequences, in the same playthrough. Cats seen during side cases do NOT count.",
      },
      source: { label: "PowerPyx — Judgment Stray Cat Locations", url: "https://www.powerpyx.com/judgment-stray-cat-locations/" },
      items: [
        { number: 1, title: { ko: "챕터 1, 2번째 탐색", en: "Chapter 1, 2nd Active Search" }, location: { ko: "「드론을 찾아라」 — 에어컨 실외기 위, 벽을 보고 앉아 있음", en: "'Locate your drone' — on top of the AC unit, facing the wall, right in front of you" } },
        { number: 2, title: { ko: "챕터 1, 3번째 탐색", en: "Chapter 1, 3rd Active Search" }, location: { ko: "클럽 아무르 밖 — 시작 위치에서 돌아서면 왼쪽 출입구", en: "Outside club Amour — in a doorway to the left after turning around from the start position" } },
        { number: 3, title: { ko: "챕터 1, 4번째 탐색", en: "Chapter 1, 4th Active Search" }, location: { ko: "KJ 아트 밖 — 자판기 위에 앉아 있음", en: "Outside KJ Art — sitting on top of a vending machine" } },
        { number: 4, title: { ko: "챕터 1, 1번째 드론 탐색", en: "Chapter 1, 1st Drone Search" }, location: { ko: "카이토와 만난 뒤 — KJ 아트 건물 위쪽 모서리 턱", en: "After meeting Kaito — top corner ledge of the KJ Art building" } },
        { number: 5, title: { ko: "챕터 1, 5번째 탐색", en: "Chapter 1, 5th Active Search" }, location: { ko: "KJ 아트 경비실 — 창문 너머 왼쪽, 건물 문 바로 밖", en: "KJ Art Security Room — just outside the building door, visible to the left through the window" } },
        { number: 6, title: { ko: "챕터 1, 6번째 탐색", en: "Chapter 1, 6th Active Search" }, location: { ko: "큐슈 일등스시 밖 — 골목 남쪽 끝, 보행 가능 구역 경계 바깥", en: "Outside Kyushu No. 1 Sushi — south end of the alley, just past the walkable boundary" } },
        { number: 7, title: { ko: "챕터 2, 1번째 탐색", en: "Chapter 2, 1st Active Search" }, location: { ko: "연쇄살인 현장 — 입구 왼쪽, 노란 상자들 위 턱", en: "Serial murder location — left side from the entrance, on the ledge above the yellow crates" } },
        { number: 8, title: { ko: "챕터 4, 1번째 탐색", en: "Chapter 4, 1st Active Search" }, location: { ko: "겐다 법률사무소 — 파란 차고 문 앞 배전함 위", en: "Genda Law Office — sitting on the power box in front of the blue garage door" } },
        { number: 9, title: { ko: "챕터 5, 1번째 탐색", en: "Chapter 5, 1st Active Search" }, location: { ko: "야가미 탐정사무소 — 길 건너 출입구", en: "Yagami Detective Agency — in the entryway across the road" } },
        { number: 10, title: { ko: "챕터 5, 2번째 탐색", en: "Chapter 5, 2nd Active Search" }, location: { ko: "ADDC 회상 — 스카이브리지 아래 기둥, 사각 받침대 맨 아래", en: "ADDC Flashback — at the very bottom of the square base, near the pillar under the sky bridge" } },
        { number: 11, title: { ko: "챕터 7, 1번째 탐색", en: "Chapter 7, 1st Active Search" }, location: { ko: "카이토의 소동 — 왼쪽, 쓰러진 간판 뒤", en: "Kaito's Ruckus — on the left, behind the tipped-over sign" } },
        { number: 12, title: { ko: "챕터 8, 1번째 탐색", en: "Chapter 8, 1st Active Search" }, location: { ko: "수색 미션 — 왼쪽 창문 블라인드 틈 아래", en: "Search Mission — just under the gap in the blinds on the left window pane" } },
        { number: 13, title: { ko: "챕터 9, 1번째 탐색", en: "Chapter 9, 1st Active Search" }, location: { ko: "쇼노를 찾아라 — 오른쪽 창문 근처, 바깥에 앉아 있음", en: "Find Shono — sitting outside near the window to your right" } },
        { number: 14, title: { ko: "최종장, 1번째 탐색", en: "Finale, 1st Active Search" }, location: { ko: "골드 키카드를 찾아라 — 연구동으로 가는 다리 오른쪽, 나무 옆 바닥", en: "Find the gold keycard — to the right of the bridge to the Research Wing, on the ground by the tree" }, reward: { ko: "마지막 고양이 — 발견 시 업적 해금", en: "Final cat — achievement unlocks on discovery" } },
      ],
    },
    {
      slug: "friends",
      title: { ko: "친구 50명 — 「A Friendly Guy」→「A Guy Everybody Knows」", en: "Friends — All 50 (\"A Friendly Guy\" → \"A Guy Everybody Knows\")" },
      summary: {
        ko: "카무로초 각지의 NPC와 특정 조건(반복 상호작용, 퀴즈 정답, 미니게임 승리 등)을 채우면 친구가 됩니다. 10명 시 「A Friendly Guy」, 30명 시 「A Popular Guy」, 50명 시 「A Guy Everybody Knows」 업적이 발동합니다.",
        en: "Meet a trigger condition (repeat interactions, quiz answers, minigame wins, etc.) with NPCs around Kamurocho to befriend them. 10 unlocks 'A Friendly Guy', 30 unlocks 'A Popular Guy', 50 unlocks 'A Guy Everybody Knows'.",
      },
      source: { label: "PowerPyx — Judgment Friends List and Locations", url: "https://www.powerpyx.com/judgment-friends-list-and-locations/" },
      items: [
        { number: 1, title: { ko: "츠쿠모 마코토", en: "Makoto Tsukumo" }, location: { ko: "스토리 연계", en: "Story related" }, body: { ko: "챕터 1 스토리 중 전당포에서 피규어를 사서 건네준다.", en: "Buy Tsukumo a figurine from the pawn shop during Chapter 1's story." } },
        { number: 2, title: { ko: "오노데라 모리오", en: "Morio Onodera" }, location: { ko: "지하도", en: "Sewers" }, body: { ko: "물건을 3회 구매한다.", en: "Purchase items from him 3 separate times." } },
        { number: 3, title: { ko: "이노세 타케오", en: "Takeo Inose" }, location: { ko: "와일드 잭슨 (천하일 거리)", en: "Wild Jackson (Tenkaichi St.)" }, body: { ko: "매출 개선 상호작용 3회.", en: "Help improve sales through 3 interactions." } },
        { number: 4, title: { ko: "요시다", en: "Yoshida" }, location: { ko: "요시다 배팅 센터", en: "Yoshida Batting Center" }, body: { ko: "일반 배팅 코스를 전부 완료.", en: "Complete all regular batting courses." } },
        { number: 5, title: { ko: "하타노 슈이치", en: "Shuichi Hatano" }, location: { ko: "요시다 배팅 센터 내부", en: "Inside Yoshida Batting Center" }, body: { ko: "코스 완료 후 배팅 용품을 2회 구매.", en: "Buy batting items twice after completing courses." } },
        { number: 6, title: { ko: "라이언 아코스타", en: "Ryan Acosta" }, location: { ko: "시내 여러 장소", en: "Various city locations" }, body: { ko: "KJ 아트 벽에서 발견 → 클럽 세가에서 다트로 승부 → 밖에서 대결.", en: "Find him at the KJ Art wall, beat him at darts at Club SEGA, then fight him outside." } },
        { number: 7, title: { ko: "마리", en: "Mari" }, location: { ko: "텐더 바", en: "Tender bar" }, body: { ko: "챕터 10에서 자동으로 만남.", en: "Met automatically in Chapter 10." } },
        { number: 8, title: { ko: "큐슈 일등스시 사장", en: "Kyushu No. 1 Star Owner" }, location: { ko: "큐슈 일등스시", en: "Kyushu No. 1 Star" }, body: { ko: "음식 퀴즈 정답 3회.", en: "Answer food questions correctly 3 times." } },
        { number: 9, title: { ko: "토미오카 리에", en: "Rie Tomioka" }, location: { ko: "스마일버거", en: "Smile Burger" }, body: { ko: "사무실 냉장고 음식 시식 5회.", en: "Try her meals from the office fridge 5 times." } },
        { number: 10, title: { ko: "후루야 야스히로", en: "Yasuhiro Furuya" }, location: { ko: "베테 키친", en: "Wette Kitchen" }, body: { ko: "경영 제안 대화 3회.", en: "Discuss corporate suggestions 3 times." } },
        { number: 11, title: { ko: "사가라 토시카즈", en: "Toshikazu Sagara" }, location: { ko: "카페 알프스", en: "Cafe Alps" }, body: { ko: "커피 퀴즈 정답 3회.", en: "Answer coffee quiz questions correctly 3 times." } },
        { number: 12, title: { ko: "아마미야 사쿠라", en: "Sakura Amamiya" }, location: { ko: "핑크 거리", en: "Pink Street" }, body: { ko: "사무실에서 마사지 요청 3회.", en: "Request massages at the office 3 times." } },
        { number: 13, title: { ko: "밴텀 사장", en: "Bantam Owner" }, location: { ko: "밴텀 바", en: "Bantam bar" }, body: { ko: "메뉴 구매 후 진상 손님 응대 시 대화.", en: "Buy menu items, then interact after tough customers." } },
        { number: 14, title: { ko: "마츠자키 후미오", en: "Fumio Matsuzaki" }, location: { ko: "칸라이", en: "Kanrai" }, body: { ko: "소고기 퀴즈 정답 3회.", en: "Answer beef quiz questions correctly 3 times." } },
        { number: 15, title: { ko: "마츠자키 료", en: "Ryo Matsuzaki" }, location: { ko: "어스 엔젤", en: "Earth Angel" }, body: { ko: "케인맨 처치 후 바에서 3회 술자리.", en: "Drink with him at the bar 3 times, after defeating Cane Man." } },
        { number: 16, title: { ko: "김원순", en: "Kim Won-Soon" }, location: { ko: "비프 존", en: "Beef Zone" }, body: { ko: "메뉴 추천 대화 4회.", en: "Provide restaurant suggestions 4 times." } },
        { number: 17, title: { ko: "타시로 군", en: "Tashiro-kun" }, location: { ko: "어린이 공원과 겐다 법률사무소 사이", en: "Between Children's Park and Genda Law Office" }, body: { ko: "야쿠자로부터 2회 보호.", en: "Protect him from yakuza 2 times." } },
        { number: 18, title: { ko: "네코미야 마사카즈", en: "Masakazu Nekomiya" }, location: { ko: "나카미치 골목", en: "Nakamichi Alley" }, body: { ko: "삼색·얼룩·검은 고양이 사진을 전송.", en: "Send pictures of calico, tabby, and black cats." } },
        { number: 19, title: { ko: "카타기리 타쿠미", en: "Takumi Katagiri" }, location: { ko: "쉘락 내부", en: "Inside Shellac" }, body: { ko: "사건 3건 완료 후 완료 소식을 10회 전달.", en: "Complete 3 side cases, then tell him about completed cases 10 times." } },
        { number: 20, title: { ko: "세바스찬 허튼", en: "Sebastian Hutton" }, location: { ko: "밀레니엄 타워 B1", en: "Millennium Tower B1" }, body: { ko: "드론 QR코드 세트를 전부(5세트) 발견.", en: "Find each drone QR code set (5 total)." } },
        { number: 21, title: { ko: "슈 하오위", en: "Haoyu Xiu" }, location: { ko: "아카우시마루 (천하일 거리)", en: "Akaushimaru (Tenkaichi St.)" }, body: { ko: "음식 구매 후 무전취식범을 추격.", en: "Chase the dine-and-dash runner after purchasing food." } },
        { number: 22, title: { ko: "글래머러스한 여성", en: "Voluptuous Woman" }, location: { ko: "라망", en: "L'Amant" }, body: { ko: "포커 승부에서 2회 승리.", en: "Win poker hands against her 2 times." } },
        { number: 23, title: { ko: "우오즈미 켄타", en: "Kenta Uozumi" }, location: { ko: "스시 긴", en: "Sushi Gin" }, body: { ko: "구매 후 퀴즈 정답 4회.", en: "Answer questions correctly 4 times after purchasing." } },
        { number: 24, title: { ko: "사쿠마 마미", en: "Mami Sakuma" }, location: { ko: "M사이드 카페", en: "M Side Cafe" }, body: { ko: "페이스트리 시식 후 감상 전달.", en: "Give feedback on baking after eating pastries." } },
        { number: 25, title: { ko: "나스가와 히로토", en: "Hiroto Nasugawa" }, location: { ko: "아카우시마루 (호텔가)", en: "Akaushimaru (Hotel District)" }, body: { ko: "특별 요리 시식 2회 + 잃어버린 레시피 회수.", en: "Try special dishes 2 times, then retrieve his lost recipe." } },
        { number: 26, title: { ko: "타나고 케니", en: "Keni Tanago" }, location: { ko: "시치후쿠 주차장", en: "Shichifuku Parking Lot" }, body: { ko: "「때려봐」 내기에서 2회 승리.", en: "Beat him in the 'Try and Hit Me' bet 2 times." } },
        { number: 27, title: { ko: "이다 하나에", en: "Hanae Ida" }, location: { ko: "스마일버거 (극장 앞 광장 북서쪽)", en: "Smile Burger (NW Theater Square)" }, body: { ko: "콘테스트용 셀카를 3회 촬영.", en: "Take selfies for the contest 3 times." } },
        { number: 28, title: { ko: "이노 아리스", en: "Alice Ino" }, location: { ko: "포포 (쇼와 거리)", en: "Poppo (Showa St.)" }, body: { ko: "구매로 10포인트 적립.", en: "Earn 10 points through purchases." } },
        { number: 29, title: { ko: "노노무라 소타", en: "Sota Nonomura" }, location: { ko: "포포 (E 시치후쿠 거리)", en: "Poppo (E Schichifuku St.)" }, body: { ko: "구매로 10포인트 적립.", en: "Earn 10 points through purchases." } },
        { number: 30, title: { ko: "아사무라 키요시로", en: "Kiyoshiro Asamura" }, location: { ko: "포포 (W 시치후쿠 거리)", en: "Poppo (W Shichifuku St.)" }, body: { ko: "구매로 10포인트 적립.", en: "Earn 10 points through purchases." } },
        { number: 31, title: { ko: "히라누마 노보루", en: "Noboru Hiranuma" }, location: { ko: "쉘락 내부", en: "Inside Shellac" }, body: { ko: "지정 대상 사진 촬영 3회.", en: "Take pictures of specific targets 3 times." } },
        { number: 32, title: { ko: "드웨인 크루즈", en: "Dwayne Cruise" }, location: { ko: "포포 (천하일 거리)", en: "Poppo (Tenkaichi St.)" }, body: { ko: "구매로 10포인트 적립.", en: "Earn 10 points through purchases." } },
        { number: 33, title: { ko: "타테야마 노보루", en: "Noboru Tateyama" }, location: { ko: "맵 남서쪽 모서리", en: "Southwest map corner" }, body: { ko: "퀵스타터 캠페인에 3단계 투자.", en: "Invest in Quickstarter campaigns across 3 levels." } },
        { number: 34, title: { ko: "사나다 카에데", en: "Kaede Sanada" }, location: { ko: "쿼드라 가든 레스토랑", en: "Quadra Garden Restaurant" }, body: { ko: "대화 4회.", en: "Talk to her 4 times." } },
        { number: 35, title: { ko: "테라하라 나오타로", en: "Naotaro Terahara" }, location: { ko: "르 마르쉐", en: "La Marche" }, body: { ko: "구매 후 방문 시 상호작용 3회.", en: "Interact when visiting after purchases, 3 times." } },
        { number: 36, title: { ko: "모로보시 고로", en: "Goro Moroboshi" }, location: { ko: "모로보시 진료소", en: "Moroboshi Clinic" }, body: { ko: "챕터 2 스토리로 첫 만남, 재방문 시 호감도 상승.", en: "Met through the story in Chapter 2, raise friendship on return visits." } },
        { number: 37, title: { ko: "타케미츠 사장", en: "Takemitsu Owner" }, location: { ko: "이스트 시치후쿠 거리", en: "East Shichifuku Street" }, body: { ko: "야쿠자 갈취로부터 3회 보호.", en: "Protect him from yakuza extortion 3 times." } },
        { number: 38, title: { ko: "후지모리 신", en: "Shin Fujimori" }, location: { ko: "사우스 나카미치 거리", en: "South Nakamichi St." }, body: { ko: "퀵스타터 프로젝트에 투자.", en: "Invest in Quickstarter projects." } },
        { number: 39, title: { ko: "노리모토 카즈히사", en: "Kazuhisa Norimoto" }, location: { ko: "카페 미조레 (2층)", en: "Cafe Mijore (2nd floor)" }, body: { ko: "다른 여자 이야기를 5회 대화.", en: "Talk about the other girl 5 times." } },
        { number: 40, title: { ko: "시마 미하루", en: "Miharu Shima" }, location: { ko: "카페 미조레 (2층)", en: "Cafe Mijore (2nd floor)" }, body: { ko: "다른 남자 이야기를 5회 대화.", en: "Talk about the other boy 5 times." } },
        { number: 41, title: { ko: "이사카 슌", en: "Shun Isaka" }, location: { ko: "이키나리 스테이크 남서쪽", en: "Southwest of Ikinari Steak" }, prereq: { ko: "챕터 10 이상, 경찰 도주 경험 필요", en: "Chapter 10+, must have evaded police at least once" }, body: { ko: "달리는 그를 2회 추격.", en: "Chase him while running, 2 times." } },
        { number: 42, title: { ko: "에비스 전당포 사장 후쿠츠", en: "Ebisu Pawn Owner, Fukutsu" }, location: { ko: "에비스 전당포", en: "Ebisu Pawn" }, body: { ko: "후카 시라누이 그림 5점을 전부 판매.", en: "Sell all 5 Fuka Shiranui paintings." } },
        { number: 43, title: { ko: "코이즈카 토시로", en: "Toshiro Koizuka" }, location: { ko: "천량 거리·이스트 타이헤이 대로", en: "Senryo Ave. and East Taihei Blvd." }, body: { ko: "열쇠공 작업을 9회 완료.", en: "Complete locksmithing jobs 9 times." } },
        { number: 44, title: { ko: "이야마", en: "Iyama" }, location: { ko: "드래곤 팰리스 (4층)", en: "Dragon's Palace (4th floor)" }, body: { ko: "특정 추출물을 만들고 레시피 대화.", en: "Create specific extracts and discuss recipes." } },
        { number: 45, title: { ko: "사오토메 요스케", en: "Yosuke Saotome" }, location: { ko: "맨즈 엔터테인먼트 록스", en: "Men's Entertainment Rox" }, body: { ko: "「팬티 도둑」 사건 완료 후 마도카를 돕는다.", en: "Complete the 'Panty Thief' side case, then help with Madoka." } },
        { number: 46, title: { ko: "시나자토 마도카", en: "Shinzato Madoka" }, location: { ko: "애플파이 클럽", en: "Apple Pie Club" }, prereq: { ko: "요스케와 먼저 친구가 되어야 함 (Boozehound 특성 필요)", en: "Requires Yosuke's friendship first (needs the Boozehound perk)" }, body: { ko: "요스케 우호도 확보 후 대화.", en: "Talk to her after securing Yosuke's friendship." } },
        { number: 47, title: { ko: "카마구치 카즈후미", en: "Kazufumi Kamaguchi" }, location: { ko: "터틀 파이낸싱 (3층)", en: "Turtle Financing (3rd floor)" }, body: { ko: "갱단 두목들에게 빚 수금을 도움.", en: "Help collect debts from gang leaders." } },
        { number: 48, title: { ko: "데구치 히데아키", en: "Hideaki Deguchi" }, location: { ko: "룰라바이 마작 밖", en: "Outside Lullaby Mahjong" }, body: { ko: "세이야와 함께 사진 콘테스트를 완료.", en: "Complete photography contests with Seiya." } },
        { number: 49, title: { ko: "이치노세 쿠니오", en: "Kunio Ichinose" }, location: { ko: "이키나리 스테이크", en: "Ikinari Steaks" }, body: { ko: "음식 구매 후 밖에서 만나 퀴즈에 답변.", en: "Meet him outside after purchasing food and answer his questions." } },
        { number: 50, title: { ko: "타치바나 유리카", en: "Yurika Tachibana" }, location: { ko: "타치바나 마작", en: "Tachibana Mahjong" }, body: { ko: "마작을 플레이해 와레메로 승리.", en: "Play mahjong games and win as Wareme." } },
      ],
    },
  ],
};
