import type { CollectiblesData } from "./types";

export const likeADragonInfiniteWealth: CollectiblesData = {
  appId: 2072450,
  categories: [
    {
      slug: "sujidex",
      title: { ko: "야쿠몬 도감(수지덱스) — 전체 150종", en: "Sujidex — All 150 Sujimon" },
      summary: {
        ko: "야쿠몬(수지몬)은 도감 번호 150종이 존재하며(포획 전용 잔몹 「위원회 요원」 1종은 도감 번호 없이 각성 재료로만 사용). 「수지매니악」은 100종 등록, 「수지몬 센세이」는 200회 등록 시 발동 — 후자는 고유 종 수가 아니라 누적 등록 횟수(중복 포획 포함)라 150종을 다 모아도 부족하면 흔한 개체를 더 포획하면 됩니다.",
        en: "150 numbered Sujimon exist in the Sujidex (plus 1 unnumbered fodder-only enemy, the Committee Agent, used only for Awakening material). 'Sujimaniac' needs 100 registered, 'Sujimon Sensei' needs 200 registrations — the latter counts cumulative registrations (duplicates included), not unique species, so catching extra common ones closes the gap even after registering all 150.",
      },
      tips: [
        { ko: "포획 10마리 시 「수지몬 스내그 뎀」, 전체 전투 서브스토리 클리어 시 「수지 리그 챔피언」, 한 마리 레벨+우정도 만렙 시 「프라이즈 파이터」 업적도 함께 발동됩니다.", en: "Recruit 10 for 'Sujimon Snag 'Em', clear all Sujimon-related substories for 'Suji League Champion', and max one Sujimon's level + friendship for 'Prize Fighter'." },
        { ko: "예: 소다치(도감 #1)는 서브스토리 37 「스타터 고르기」로 확정 입수. 익스터미네이션 군(#044)은 와이키키 거리 모퉁이 스트리트 킹전 승리로 입수. 키와미 레드(#130)는 전설급 화염 속성 레이드(Lv.60) 보상. 키류 카즈마(#135/#136)는 엔딩 클리어 보상 또는 마스터 베케이션 번들 DLC 한정.", en: "Examples: Sodachi (#1) is a guaranteed pick from substory 37 'Choosing Your Starter'. Extermination-kun (#044) drops from a Street King battle at the Waikīkī St. corner. Kiwami Red (#130) comes from a Legendary Fire Element Raid (Lv.60). Kazuma Kiryu (#135/#136) is either a game-clear reward or DLC-exclusive." },
      ],
      source: [
        { label: "TheGamer — Complete Sujimon Dossier List", url: "https://www.thegamer.com/like-a-dragon-infinite-wealth-complete-sujimon-dossier-complete-list/" },
        { label: "GameFAQs — Sujimon Dossier 1-50 / 101-150", url: "https://gamefaqs.gamespot.com/ps5/409974-like-a-dragon-infinite-wealth/faqs/81106/sujimon-dossier-1-50" },
      ],
    },
    {
      slug: "photo-rally",
      title: { ko: "포토 랠리 — 8개 지역 110곳", en: "Photo Rally — 110 Spots across 8 Areas" },
      summary: {
        ko: "알로하피 투어즈의 포토 랠리 스팟 110곳입니다. 게임은 「어느 가게의 진열창」 같은 힌트만 주므로, 각 항목의 사진 위쪽 인게임 지도에서 위치를, 아래쪽 화면에서 실제 촬영 대상을 확인하세요. 하와이 4개 지역과 이세자키 이진초 4개 지역으로 나뉩니다.",
        en: "All 110 Alo-Happy Tours photo rally spots. The game only gives a hint like \"a certain shop window\", so each entry carries a picture that is the in-game map on top and the thing you actually photograph underneath. Four areas in Hawaii, four in Isezaki Ijincho.",
      },
      source: [
        { label: "PowerPyx — All Photo Rally Locations", url: "https://www.powerpyx.com/like-a-dragon-infinite-wealth-all-photo-rally-locations/" },
        { label: "ゲーム攻略マン — 龍が如く8 フォトラリースポット（マップ付き）", url: "https://dswiipspwikips3.jp/yakuza8/photo-rally/" },
      ],
      groups: [
        {
          title: { ko: "리틀 재팬 — 15곳", en: "Little Japan — 15 Spots" },
          items: [
            { number: 1, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img01.jpg", title: { ko: "주택가 벽 코코넛 거북이", en: "Coconut Turtle on Housing Complex Wall" }, location: { ko: "마카니 애비뉴 캐릭터 조형물", en: "Character figure on Makani Ave." } },
            { number: 2, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img02.jpg", title: { ko: "거리 진열창", en: "Streetside Window Display" }, location: { ko: "모모 거리 매장 창문", en: "Shop window on Momo St." } },
            { number: 3, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img03.jpg", title: { ko: "황금 푸드트럭", en: "Golden Food Truck" }, location: { ko: "제프의 타코 트럭", en: "Jeff's Taco Truck" } },
            { number: 4, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img04.jpg", title: { ko: "빙수 가게 그림", en: "Shave Ice Shop Painting" }, location: { ko: "마츠모토 빙수 내부", en: "Inside Matsumoto Shave Ice" } },
            { number: 5, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img05.jpg", title: { ko: "인기 바·아지트", en: "Popular Bar and Hangout Spot" }, location: { ko: "리볼브 바 간판", en: "Revolve Bar signage" } },
            { number: 6, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img06.jpg", title: { ko: "리볼브 근처 장비점", en: "Equipment Store Near Revolve" }, location: { ko: "리볼브 맞은편 야마비코 상점", en: "Yamabiko shop across from Revolve" } },
            { number: 7, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img07.jpg", title: { ko: "주택 우편함", en: "On a Residential Mailbox" }, location: { ko: "츠바키 거리 동쪽", en: "East side of Tsubaki St." } },
            { number: 8, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img08.jpg", title: { ko: "이건 배짱이 필요해", en: "This One Takes Confidence" }, location: { ko: "도박장 내부", en: "Inside the Gambling Hall" } },
            { number: 9, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img09.jpg", title: { ko: "주택 벽면", en: "On a Housing Wall" }, location: { ko: "신사 맞은편 후지 거리", en: "Fuji St. opposite the Shrine" } },
            { number: 10, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img10.jpg", title: { ko: "닌자가 스시 먹는 곳", en: "The Ninja Up Where Ninja Sup" }, location: { ko: "시노비 스시 내부", en: "Inside Shinobi Sushi" } },
            { number: 11, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img11.jpg", title: { ko: "신사 건물 내부", en: "Inside the Shrine Building" }, location: { ko: "포춘 익스체인지 옆", en: "By the Fortune Exchange" } },
            { number: 12, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img12.jpg", title: { ko: "사무라이 진열창", en: "Samurai Window Display" }, location: { ko: "간류지마 무기점 정면", en: "Ganryujima Armory storefront" } },
            { number: 13, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img13.jpg", title: { ko: "무기점 내부", en: "Inside the Weapons Shop" }, location: { ko: "간류지마 무기점 내부", en: "Ganryujima Armory interior" } },
            { number: 14, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img14.jpg", title: { ko: "컨테이너 속 정원", en: "Garden in a Shipping Container" }, location: { ko: "아히 포케 가든 간판", en: "Ahi Poke Garden sign" } },
            { number: 15, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-little-japan-img15.jpg", title: { ko: "길모퉁이 식당 간판", en: "Street Corner Restaurant Sign" }, location: { ko: "이스트 와이키키 빅 피자 킹", en: "Big Pizza King at East Waikiki" } },
          ],
        },
        {
          title: { ko: "와이키키 — 15곳", en: "Waikiki — 15 Spots" },
          items: [
            { number: 16, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img01.jpg", title: { ko: "트로피컬 진열창", en: "Tropical Window Display" }, location: { ko: "시워디 트레저스 창문", en: "Seaworthy Treasures window" } },
            { number: 17, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img02.jpg", title: { ko: "서핑보드 디저트 가게 간판", en: "Surfboard Sweets Shop Sign" }, location: { ko: "크림&베리 내부", en: "Inside Cream & Berry" } },
            { number: 18, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img03.jpg", title: { ko: "광장 한가운데", en: "Middle of Park Square" }, location: { ko: "시사이드 애비뉴·와이키키 거리 공원", en: "Seaside Ave. and Waikiki St. park" } },
            { number: 19, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img04.jpg", title: { ko: "빙수 메뉴판", en: "Shave Ice Menu Board" }, location: { ko: "모할로 빙수", en: "Mohalo Shave Ice" } },
            { number: 20, title: { ko: "알로하피 투어즈", en: "Alo-Happy Tours" }, location: { ko: "스토리 도입부 관련 위치", en: "Story-related introduction location" }, prereq: { ko: "서브스토리로 진행되는 스팟", en: "Handled by a substory" } },
            { number: 21, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img06.jpg", title: { ko: "쇼핑센터 입구", en: "Shopping Center Entrance" }, location: { ko: "월드와이드 마켓 빌리지", en: "Worldwide Market Village" } },
            { number: 22, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img07.jpg", title: { ko: "거리 진열창", en: "Streetside Window Display" }, location: { ko: "크레페 포 미 근처", en: "Near Crepes for Me" } },
            { number: 23, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img08.jpg", title: { ko: "서핑샵 뒤편", en: "Behind the Surf Shop" }, location: { ko: "노 서프 노 라이프 벽면", en: "No Surf No Life wall" } },
            { number: 24, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img09.jpg", title: { ko: "아이스크림 가판 네온 간판", en: "Ice Cream Stand Neon Sign" }, location: { ko: "스노우타운 USA 벽면", en: "Snowtown USA wall" } },
            { number: 25, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img10.jpg", title: { ko: "모카 마할로 옆", en: "Beside Mocha Mahalo" }, location: { ko: "인접 상점", en: "Adjacent shop" } },
            { number: 26, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img11.jpg", title: { ko: "차고 로고", en: "Garage Logo" }, location: { ko: "줄리스 기어웍스 본점", en: "Julie's Gearworks (Main Store)" } },
            { number: 27, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img12.jpg", title: { ko: "레스토랑 내부", en: "Inside the Restaurant" }, location: { ko: "오아후 버거 간판", en: "Oahu Burger sign" } },
            { number: 28, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img13.jpg", title: { ko: "모래사장 서핑보드 조형물", en: "Surfboard Statue on the Sands" }, location: { ko: "알로하 비치프런트 남쪽", en: "South of Aloha Beachfront" } },
            { number: 29, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img14.jpg", title: { ko: "해변가 골목", en: "Alleyway by the Beach" }, location: { ko: "웨스트 알로하 비치 북쪽", en: "North of West Aloha Beach" } },
            { number: 30, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-waikiki-town-img15.jpg", title: { ko: "큰 호텔 로고", en: "A big hotel logo" }, location: { ko: "크리스탈 알로하 리조트", en: "Crystal Aloha Resort" } },
          ],
        },
        {
          title: { ko: "아트 나이트 파크 — 15곳", en: "Art Night Park — 15 Spots" },
          items: [
            { number: 31, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img01.jpg", title: { ko: "바닷가 공원", en: "The seaside park" }, location: { ko: "아나콘다 하버 파크", en: "Anaconda Harbor Park" } },
            { number: 32, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img02.jpg", title: { ko: "항구의 모뉴먼트", en: "The harbor monument" }, location: { ko: "마리나", en: "Marina" } },
            { number: 33, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img03.jpg", title: { ko: "길모퉁이 주차장 옆", en: "Next to the corner car park" }, location: { ko: "Horizon Drugs", en: "Horizon Drugs" } },
            { number: 34, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img04.jpg", title: { ko: "길모퉁이 진열창", en: "A shop window on the corner" }, location: { ko: "플라워 디스플레이", en: "Flower display" } },
            { number: 35, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img05.jpg", title: { ko: "밤놀이 장소", en: "A place for a night out" }, location: { ko: "클럽 돌즈 & 데빌즈", en: "Club Dolls & Devils" } },
            { number: 36, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img06.jpg", title: { ko: "과감한 진열창", en: "A rather bold shop window" }, location: { ko: "하이퍼 엑스터시", en: "Hyper Ecstasy" } },
            { number: 37, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img07.jpg", title: { ko: "선착장 근처 왜건", en: "The wagon near the dock" }, location: { ko: "힙합 슈림프", en: "Hip Hop Shrimp" } },
            { number: 38, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img08.jpg", title: { ko: "아트 월", en: "The art walls" }, location: { ko: "월 아트 버드", en: "Wall Art: Bird" } },
            { number: 39, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img09.jpg", title: { ko: "찻집 간판", en: "A coffee shop sign" }, location: { ko: "사이키델릭 커피", en: "Psychedelic Coffee" } },
            { number: 40, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img10.jpg", title: { ko: "아트 월이 있는 바", en: "The bar with the art wall" }, location: { ko: "BAR MODERNE", en: "BAR MODERNE" } },
            { number: 41, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img11.jpg", title: { ko: "어느 학교 안", en: "Inside a certain school" }, location: { ko: "오오우나바라 라이선스 스쿨", en: "Ounabara License School" } },
            { number: 42, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img12.jpg", title: { ko: "어느 극장 간판", en: "A certain theater's sign" }, location: { ko: "Cabaret ELDORADO", en: "Cabaret ELDORADO" } },
            { number: 43, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img13.jpg", title: { ko: "거리의 파인애플", en: "The pineapple on the street" }, location: { ko: "사격용품 불렛헬", en: "Bullet Hell shooting supplies" } },
            { number: 44, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img14.jpg", title: { ko: "길모퉁이 찻집", en: "A coffee shop on the corner" }, location: { ko: "찻집 리버티", en: "Tea House Liberty" } },
            { number: 45, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-park-img15.jpg", title: { ko: "거리의 간판", en: "A sign on the street" }, location: { ko: "음식점 간판", en: "A restaurant's sign" } },
          ],
        },
        {
          title: { ko: "아나콘다 쇼핑센터 — 10곳", en: "Anaconda Shopping Center — 10 Spots" },
          items: [
            { number: 46, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img01.jpg", title: { ko: "쇼핑센터 1층", en: "Shopping centre, 1F" }, location: { ko: "아나콘다 쇼핑센터 주차장", en: "Anaconda Shopping Center car park" } },
            { number: 47, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img02.jpg", title: { ko: "쇼핑센터 1층", en: "Shopping centre, 1F" }, location: { ko: "아나콘다 아케이드", en: "Anaconda Arcade" } },
            { number: 48, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img03.jpg", title: { ko: "쇼핑센터 1층", en: "Shopping centre, 1F" }, location: { ko: "얼굴 끼우기 판넬", en: "Face-in-hole board" } },
            { number: 49, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img04.jpg", title: { ko: "쇼핑센터 2층", en: "Shopping centre, 2F" }, location: { ko: "츠보헤비", en: "Tsubohebi" } },
            { number: 50, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img05.jpg", title: { ko: "쇼핑센터 북쪽 입구", en: "Shopping centre, north entrance" }, location: { ko: "아나콘다 쇼핑센터 북쪽 입구", en: "Anaconda Shopping Center north entrance" } },
            { number: 51, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img06.jpg", title: { ko: "쇼핑센터 남쪽 입구", en: "Shopping centre, south entrance" }, location: { ko: "아나콘다 쇼핑센터 남쪽 입구", en: "Anaconda Shopping Center south entrance" } },
            { number: 52, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img07.jpg", title: { ko: "쇼핑센터 서쪽 입구", en: "Shopping centre, west entrance" }, location: { ko: "아나콘다 쇼핑센터 서쪽 입구", en: "Anaconda Shopping Center west entrance" } },
            { number: 53, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img08.jpg", title: { ko: "쇼핑센터 2층", en: "Shopping centre, 2F" }, location: { ko: "숨은 아나콘다: 화단", en: "Hidden Anaconda: the planter" } },
            { number: 54, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img09.jpg", title: { ko: "쇼핑센터 2층", en: "Shopping centre, 2F" }, location: { ko: "숨은 아나콘다: 진열창", en: "Hidden Anaconda: the shop window" } },
            { number: 55, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-anaconda-shopping-center-img10.jpg", title: { ko: "쇼핑센터 화장실", en: "Shopping centre, toilets" }, location: { ko: "숨은 아나콘다: 화장실", en: "Hidden Anaconda: the toilets" } },
          ],
        },
        {
          title: { ko: "다운타운 차이나타운 — 15곳", en: "Downtown Chinatown — 15 Spots" },
          items: [
            { number: 56, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-district-5-img01.jpg", title: { ko: "제5지구의 벽 낙서", en: "Graffiti on a wall in District Five" }, location: { ko: "월 아트 옥토퍼스", en: "Wall Art: Octopus" } },
            { number: 57, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-district-5-img02.jpg", title: { ko: "하나만 다른 피자", en: "The one pizza that is different" }, location: { ko: "피자 양키", en: "Pizza Yankee" } },
            { number: 58, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-district-5-img03.jpg", title: { ko: "수갑투성이 클럽", en: "The club covered in handcuffs" }, location: { ko: "Club Guilty", en: "Club Guilty" } },
            { number: 59, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-district-5-img04.jpg", title: { ko: "폐허 안", en: "Inside the ruins" }, location: { ko: "수갑과 글러브", en: "Handcuffs and glove" } },
            { number: 60, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-downtown-img05.jpg", title: { ko: "가게 안 선반 위", en: "On a shelf inside the shop" }, location: { ko: "소라마메의 콩들", en: "The beans at Soramame" } },
            { number: 61, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-downtown-img06.jpg", title: { ko: "거리에 면한 분수 광장 (1)", en: "The fountain plaza facing the street (1)" }, location: { ko: "다운타운 분수 광장", en: "Downtown fountain plaza" } },
            { number: 62, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-downtown-img07.jpg", title: { ko: "거리에 면한 분수 광장 (2)", en: "The fountain plaza facing the street (2)" }, location: { ko: "스파의 분수 광장", en: "The spa's fountain plaza" } },
            { number: 63, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-downtown-img08.jpg", title: { ko: "상어 이빨 같은 가게", en: "The shop shaped like shark teeth" }, location: { ko: "기념품점 샤크투스", en: "Souvenir Shop Shark Tooth" } },
            { number: 64, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-chinatown-img09.jpg", title: { ko: "중화 무구 가게", en: "The Chinese weapons shop" }, location: { ko: "무술관의 판다", en: "The panda at the martial arts hall" } },
            { number: 65, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-chinatown-img10.jpg", title: { ko: "크고 화려한 호텔", en: "The big, lavish hotel" }, location: { ko: "열반안", en: "Nehangan" } },
            { number: 66, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-chinatown-img11.jpg", title: { ko: "한약방 마스코트", en: "The herbal shop's mascot" }, location: { ko: "고려인삼짱", en: "Ginseng-chan" } },
            { number: 67, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-chinatown-img12.jpg", title: { ko: "엘리베이터 위의 판다", en: "The panda above the lift" }, location: { ko: "하와이 마작 입구", en: "Hawaii Mahjong entrance" } },
            { number: 68, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-chinatown-img13.jpg", title: { ko: "거리의 와인 가게", en: "The wine shop on the street" }, location: { ko: "Another Bottle", en: "Another Bottle" } },
            { number: 69, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-chinatown-img14.jpg", title: { ko: "시장의 스무디 가게", en: "The smoothie stand in the market" }, location: { ko: "판타지 스무디즈", en: "Fantasy Smoothies" } },
            { number: 70, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-chinatown-img15.jpg", title: { ko: "길모퉁이 가게", en: "A shop on the corner" }, location: { ko: "생활용품 클린클린", en: "Clean Clean Housewares" } },
          ],
        },
        {
          title: { ko: "이세자키 이진초 북부 — 15곳", en: "Isezaki Ijincho North — 15 Spots" },
          items: [
            { number: 71, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img01.jpg", title: { ko: "고등학교 교문", en: "The high school gate" }, location: { ko: "세이료 고등학교 교문", en: "Seiryo High School gate" } },
            { number: 72, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img02.jpg", title: { ko: "골프장 간판", en: "The golf place's sign" }, location: { ko: "HEAVEN'S GOLF", en: "HEAVEN'S GOLF" } },
            { number: 73, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img03.jpg", title: { ko: "고가 아래 셔터 거리", en: "The shuttered row under the overpass" }, location: { ko: "5·6 바이크", en: "5-6 Bike" } },
            { number: 74, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img04.jpg", title: { ko: "역 개찰구", en: "The station ticket gates" }, location: { ko: "진나이 역", en: "Jinnai Station" } },
            { number: 75, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img05.jpg", title: { ko: "알로하피짱 다시 한 번", en: "Alo-Happy, again" }, location: { ko: "요코하마의 알로하피짱", en: "Yokohama's Alo-Happy" } },
            { number: 76, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img06.jpg", title: { ko: "다트 바 안", en: "Inside the darts bar" }, location: { ko: "다츠 바 Bee", en: "Darts Bar Bee" } },
            { number: 77, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img07.jpg", title: { ko: "배팅 센터 안", en: "Inside the batting centre" }, location: { ko: "Shark Stars", en: "Shark Stars" } },
            { number: 78, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img08.jpg", title: { ko: "큰 호텔 입구", en: "The big hotel's entrance" }, location: { ko: "진나이 브론즈 호텔", en: "Jinnai Bronze Hotel" } },
            { number: 79, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img09.jpg", title: { ko: "포커장 마크", en: "The poker room's mark" }, location: { ko: "m HOLD'EM 진나이", en: "m HOLD'EM Jinnai" } },
            { number: 80, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img10.jpg", title: { ko: "큰 빌딩 모퉁이", en: "The corner of the big building" }, location: { ko: "컷하우스 TIMELINE", en: "Cut House TIMELINE" } },
            { number: 81, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img11.jpg", title: { ko: "공원 분수", en: "The park fountain" }, location: { ko: "하마키타 공원 분수와 상", en: "Hamakita Park fountain and statue" } },
            { number: 82, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img12.jpg", title: { ko: "차이나타운의 조형물", en: "An objet in Chinatown" }, location: { ko: "산라톤", en: "Sanraton" } },
            { number: 83, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img13.jpg", title: { ko: "차이나타운 공원", en: "The Chinatown park" }, location: { ko: "중화가 공원", en: "Chinatown Park" } },
            { number: 84, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img14.jpg", title: { ko: "차이나타운 제일의 음식점", en: "Chinatown's best restaurant" }, location: { ko: "헤이안로", en: "Heianro" } },
            { number: 85, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-northern-img15.jpg", title: { ko: "차이나타운 아치", en: "The arch into Chinatown" }, location: { ko: "젠쇼몬", en: "Zenshomon" } },
          ],
        },
        {
          title: { ko: "이세자키 이진초 남부 — 15곳", en: "Isezaki Ijincho South — 15 Spots" },
          items: [
            { number: 86, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img01.jpg", title: { ko: "동네 개인 사우나", en: "A private sauna in town" }, location: { ko: "개인 사우나 신·센·칸", en: "Private Sauna Shin-Sen-Kan" } },
            { number: 87, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img02.jpg", title: { ko: "거리의 아치", en: "The arch over the street" }, location: { ko: "「덕」", en: "\"Toku\"" } },
            { number: 88, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img03.jpg", title: { ko: "길모퉁이 이자카야", en: "An izakaya on the corner" }, location: { ko: "쿠시카츠 카도야", en: "Kushikatsu Kadoya" } },
            { number: 89, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img04.jpg", title: { ko: "예전 공장", en: "A former factory" }, location: { ko: "줄리즈 기어웍스 이진초 출장소", en: "Julie's Gearworks, Ijincho branch" } },
            { number: 90, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img05.jpg", title: { ko: "헬로워크 근처 사진관", en: "The photo shop near the job centre" }, location: { ko: "사진의 타키야마", en: "Takiyama Photography" } },
            { number: 91, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img06.jpg", title: { ko: "헬로워크", en: "The job centre" }, location: { ko: "헬로워크 미사키", en: "Hello Work Misaki" } },
            { number: 92, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img07.jpg", title: { ko: "대로변 찻집", en: "A coffee shop along the main street" }, location: { ko: "고블린 커피", en: "Goblin Coffee" } },
            { number: 93, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img08.jpg", title: { ko: "길모퉁이 분홍 건물", en: "The pink building on the corner" }, location: { ko: "메르헨헬스 핑키래빗", en: "Marchen Health Pinky Rabbit" } },
            { number: 94, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img09.jpg", title: { ko: "어느 극장 옥상", en: "A certain theater's roof" }, location: { ko: "유성극장 옥상", en: "Ryusei Theater roof" } },
            { number: 95, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img10.jpg", title: { ko: "예전에 영업하던 영화관", en: "A cinema that used to run" }, location: { ko: "명화좌 우미네코자", en: "Meigaza Umineko-za" } },
            { number: 96, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img11.jpg", title: { ko: "길모퉁이 호텔", en: "A hotel on the corner" }, location: { ko: "HOTEL BUNNY'S", en: "HOTEL BUNNY'S" } },
            { number: 97, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img12.jpg", title: { ko: "길모퉁이 큰 건물", en: "A big building on the corner" }, location: { ko: "REVENGEBOOKS", en: "REVENGEBOOKS" } },
            { number: 98, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img13.jpg", title: { ko: "거리의 레스토랑", en: "A restaurant on the street" }, location: { ko: "OLD MOUNTAIN", en: "OLD MOUNTAIN" } },
            { number: 99, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img14.jpg", title: { ko: "패스트푸드점 간판", en: "A fast-food sign" }, location: { ko: "빗테 키친의 공룡", en: "Vitte Kitchen's dinosaur" } },
            { number: 100, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-ijincho-southern-img15.jpg", title: { ko: "이세자키 이진초를 대표하는 거리", en: "The street that defines Isezaki Ijincho" }, location: { ko: "이세자키 로드", en: "Isezaki Road" } },
          ],
        },
        {
          title: { ko: "스낵 거리 — 10곳", en: "Snack Street — 10 Spots" },
          items: [
            { number: 101, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img01.jpg", title: { ko: "예전에 회사가 있던 자리", en: "A place where a company was once run" }, location: { ko: "이치반 제과", en: "Ichiban Confectionery" } },
            { number: 102, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img02.jpg", title: { ko: "길모퉁이 빌딩 1층", en: "Ground floor of a corner building" }, location: { ko: "LEDA", en: "LEDA" } },
            { number: 103, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img03.jpg", title: { ko: "거리의 옷가게", en: "A clothing store in town" }, location: { ko: "핫슬 양품점", en: "Hustle Clothiers" } },
            { number: 104, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img04.jpg", title: { ko: "아지트 근처 찻집", en: "The coffee shop near the hangout" }, location: { ko: "음악 찻집 ♪마아자", en: "Music Cafe Mother" } },
            { number: 105, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img05.jpg", title: { ko: "아지트 간판", en: "The hangout's sign" }, location: { ko: "서바이버", en: "Survivor" } },
            { number: 106, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img06.jpg", title: { ko: "2층 스낵 거리 구역", en: "The second-floor snack bar row" }, location: { ko: "긴샤린", en: "Ginsharin" } },
            { number: 107, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img07.jpg", title: { ko: "골목에 늘어선 가게", en: "A shop along the backstreet" }, location: { ko: "애니멀 매니아", en: "Animal Mania" } },
            { number: 108, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img08.jpg", title: { ko: "거리의 호텔", en: "A hotel on the street" }, location: { ko: "캡슐호텔 아케비", en: "Capsule Hotel Akebi" } },
            { number: 109, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img09.jpg", title: { ko: "거리의 이자카야", en: "An izakaya in town" }, location: { ko: "이자카야 야마이모", en: "Izakaya Yamaimo" } },
            { number: 110, image: "https://dswiipspwikips3-images.jp/yakuza8/photo-spots-snack-street-img10.jpg", title: { ko: "길모퉁이 점집", en: "A fortune-teller on the corner" }, location: { ko: "점술관 토키와 만사쿠", en: "Tokiwa Mansaku Fortunes" } },
          ],
        },
      ],
    },
  ],
};
