import type { CollectiblesData } from "./types";

export const likeADragonPirate: CollectiblesData = {
  appId: 3061810,
  categories: [
    {
      slug: "treasures",
      title: { ko: "트레저 오브 트레저스 — 보물 65종", en: "A Treasury of Treasures — All 65 Treasures" },
      summary: {
        ko: "바다·마들란티스·하와이·플레임/프로스트 헤븐 전역에 흩어진 보물 65종. 「신참 보물 사냥꾼」은 10종, 「베테랑 보물 사냥꾼」은 40종을 모으면 달성됩니다.",
        en: "65 treasures scattered across the seas, Madlantis, Hawaii, and Flame/Frost Heaven. 'Novice Treasure Hunter' needs 10, 'Expert Treasure Hunter' needs 40.",
      },
      source: { label: "PowerPyx — All Treasure Locations", url: "https://www.powerpyx.com/like-a-dragon-pirate-yakuza-in-hawaii-all-treasure-locations/" },
      groups: [
        {
          title: { ko: "바다 보물 — 1~20", en: "Sea Treasures — 1-20" },
          items: [
            { number: 1, title: { ko: "물의 정령 램프", en: "Water Spirit's Lamp" }, location: { ko: "리치 아일랜드 인근 해역 — 다이나 아일랜드", en: "Waters Near Rich Island — Dyna Island" } },
            { number: 2, title: { ko: "선원의 두루마리", en: "Sailor's Scroll" }, location: { ko: "리치 아일랜드 인근 해역 — 점보 아일랜드", en: "Waters Near Rich Island — Jumbo Island" } },
            { number: 3, title: { ko: "물의 여신의 약병", en: "Water Goddess's Vial" }, location: { ko: "네레 아일랜드 인근 해역 — 알레 아일랜드", en: "Waters Near Nele Island — Ahle Island" } },
            { number: 4, title: { ko: "바다새의 성배", en: "Seabird's Chalice" }, location: { ko: "마들란티스 인근 해역 — 바하 아일랜드", en: "Waters Near Madlantis — Baja Island" } },
            { number: 5, title: { ko: "잔물결 물거울", en: "Rippling Water Mirror" }, location: { ko: "마들란티스 인근 해역", en: "Waters Near Madlantis" }, body: { ko: "스토리 진행으로 자동 입수.", en: "Story-obtained automatically." } },
            { number: 6, title: { ko: "바다의 반지", en: "Ring of the Ocean" }, location: { ko: "리치 아일랜드 인근 해역 — 코코 아일랜드", en: "Waters Near Rich Island — Koko Island" }, body: { ko: "스토리 진행으로 자동 입수.", en: "Story-obtained automatically." } },
            { number: 7, title: { ko: "밀물의 반지", en: "Ring of Tides" }, location: { ko: "리치 아일랜드 인근 해역 — 라파차차 아일랜드", en: "Waters Near Rich Island — Rapachacha Island" } },
            { number: 8, title: { ko: "마린 카펫", en: "Marine Carpet" }, location: { ko: "리치 아일랜드 인근 해역 — 다이나 아일랜드", en: "Waters Near Rich Island — Dyna Island" }, body: { ko: "데빌 플래그스 소속 배를 격파해야 입수.", en: "Defeat the Devil Flags ship here to obtain." } },
            { number: 9, title: { ko: "물의 성배", en: "Watery Goblet" }, location: { ko: "네레 아일랜드 인근 해역 — 엘레아나 아일랜드", en: "Waters Near Nele Island — Eleahna Island" } },
            { number: 10, title: { ko: "아쿠아 스톤", en: "Aqua Stone" }, location: { ko: "네레 아일랜드 인근 해역", en: "Waters Near Nele Island" }, body: { ko: "데빌 플래그스 소속 배를 격파해야 입수.", en: "Defeat the Devil Flags ship here to obtain." } },
            { number: 11, title: { ko: "바람의 서書", en: "Writings of the Winds" }, location: { ko: "하와이 인근 해역 — 나하나하 아일랜드", en: "Waters Near Hawaii — Nahanaha Island" } },
            { number: 12, title: { ko: "바람 정령의 성배", en: "Wind Spirit's Chalice" }, location: { ko: "하와이 인근 해역 — 후아카이 아일랜드", en: "Waters Near Hawaii — Huaka'i Island" } },
            { number: 13, title: { ko: "질풍의 회중시계", en: "Pocket Watch of Gales" }, location: { ko: "하와이 인근 해역 — 하우올리 아일랜드", en: "Waters Near Hawaii — Hau'oli Island" }, body: { ko: "데빌 플래그스 소속 배를 격파해야 입수.", en: "Defeat the Devil Flags ship here to obtain." } },
            { number: 14, title: { ko: "토네이도 브로치", en: "Tornado Brooch" }, location: { ko: "아탈리 아일랜드 인근 해역 — 야나기 아일랜드", en: "Waters Near Atali Island — Yanagi Island" } },
            { number: 15, title: { ko: "폭풍의 반지", en: "Ring of the Tempest" }, location: { ko: "아탈리 아일랜드 인근 해역 — 사산콰 아일랜드", en: "Waters Near Atali Island — Sasanqua Island" } },
            { number: 16, title: { ko: "폭풍우 반지들", en: "Rings of Storms" }, location: { ko: "네레 아일랜드 인근 해역 — 이모스 아일랜드", en: "Waters Near Nele Island — Eamoth Island" } },
            { number: 17, title: { ko: "태풍의 성배", en: "Typhoon Goblet" }, location: { ko: "하와이 인근 해역 — 마카우 누이 아일랜드", en: "Waters Near Hawaii — Makau Nui Island" } },
            { number: 18, title: { ko: "날개 달린 카펫", en: "Winged Carpet" }, location: { ko: "아탈리 아일랜드 인근 해역 — 엠마 아일랜드", en: "Waters Near Atali Island — Emma Island" } },
            { number: 19, title: { ko: "폭풍 소환사의 부채", en: "Stormcaller's Fan" }, location: { ko: "마들란티스 인근 해역 — 바낙 아일랜드", en: "Waters Near Madlantis — Varnack Island" } },
            { number: 20, title: { ko: "바람의 돌", en: "Wind Stone" }, location: { ko: "마들란티스 인근 해역 — 이스트 마들란티스 등대 부근", en: "Waters Near Madlantis — East Madlantis Lighthouse" }, body: { ko: "데빌 플래그스 소속 배를 격파해야 입수.", en: "Defeat the Devil Flags ship here to obtain." } },
          ],
        },
        {
          title: { ko: "마들란티스 육상 보물 — 21~30", en: "Madlantis Land Treasures — 21-30" },
          items: [
            { number: 21, title: { ko: "대지 정령 램프", en: "Earth Spirit's Lamp" }, location: { ko: "마들란티스 — 게이밍 구역", en: "Madlantis — Gaming Area" }, body: { ko: "컨테이너 위로 그래플.", en: "Grapple onto the containers." } },
            { number: 22, title: { ko: "고대 동굴 두루마리", en: "Ancient Cave Scroll" }, location: { ko: "마들란티스 — 바 지구", en: "Madlantis — Bar District" }, body: { ko: "덩힐 바 위로 그래플.", en: "Grapple above Dunghill Bar." } },
            { number: 23, title: { ko: "대지모의 향로", en: "Earth Mother's Censer" }, location: { ko: "마들란티스 — 럭셔리 팰리스 호텔", en: "Madlantis — Luxury Palace Hotel" }, body: { ko: "우든 보물상자 15,000달러에 구매.", en: "Purchase a Wooden Treasure Chest for $15,000." } },
            { number: 24, title: { ko: "돌 깨는 회중시계", en: "Stonebreaker Pocket Watch" }, location: { ko: "마들란티스 — 럭셔리 팰리스 호텔", en: "Madlantis — Luxury Palace Hotel" }, body: { ko: "우든 보물상자를 로얄 카지노 칩 2,000개로 구매.", en: "Purchase a Wooden Treasure Chest for 2,000 Royal Casino chips." } },
            { number: 25, title: { ko: "돌의 반지", en: "Ring of Stone" }, location: { ko: "마들란티스 — 바 지구", en: "Madlantis — Bar District" }, body: { ko: "뱅뱅 배팅 센터 위로 그래플.", en: "Grapple above Bang Bang Batting Center." } },
            { number: 26, title: { ko: "가이아의 반지", en: "Ring of Gaia" }, location: { ko: "리치 아일랜드 — 스텔라 상점", en: "Rich Island — Stella's Shop" }, body: { ko: "탑 측면으로 그래플.", en: "Grapple on the tower side." } },
            { number: 27, title: { ko: "대지의 반지", en: "Ring of Earth" }, location: { ko: "마들란티스 — 뱅뱅 배팅 센터", en: "Madlantis — Bang Bang Batting Center" }, body: { ko: "실버 보물상자를 90,000포인트로 구매.", en: "Purchase a Silver Treasure Chest for 90,000 points." } },
            { number: 28, title: { ko: "바위 성배", en: "Boulder Goblet" }, location: { ko: "마들란티스 — 골프장", en: "Madlantis — Golf area" }, body: { ko: "상품 교환소에서 6,000포인트로 교환.", en: "Purchase from the prize exchange for 6,000 points." } },
            { number: 29, title: { ko: "돌 카펫", en: "Stone Carpet" }, location: { ko: "마들란티스 — 퀸즈 캐슬", en: "Madlantis — The Queen's Castle" }, body: { ko: "아치 위로 그래플.", en: "Grapple on the arch." } },
            { number: 30, title: { ko: "대지의 돌", en: "Earth Stone" }, location: { ko: "마들란티스 — 콜로세움 부지", en: "Madlantis — Coliseum Grounds" }, body: { ko: "파이어리츠 콜로세움 전 경기 우승 후 스토리로 입수.", en: "Story-obtained after winning all Pirates' Coliseum matches." } },
          ],
        },
        {
          title: { ko: "하와이 육상 보물 — 31~50", en: "Hawaii Land Treasures — 31-50" },
          items: [
            { number: 31, title: { ko: "빛의 정령 램프", en: "Light Spirit's Lamp" }, location: { ko: "하와이 — 사우스 와이키키, 크리스탈 알로하 리조트", en: "Hawaii — South Waikiki, Crystal Aloha Resort" }, body: { ko: "흰색 창문 건물로 그래플.", en: "Grapple on the white window building." } },
            { number: 32, title: { ko: "신성한 권위의 두루마리", en: "Scroll of Divine Authority" }, location: { ko: "하와이 — 이스트 와이키키, 피자리아 펠리체", en: "Hawaii — East Waikiki, Pizzeria Felice" }, body: { ko: "차양으로 그래플.", en: "Grapple on the awning." } },
            { number: 33, title: { ko: "달빛 성배", en: "Moonlight Chalice" }, location: { ko: "하와이 — 알로하 비치, 호누 월드 마켓 근처", en: "Hawaii — Aloha Beach, near Honu World Market" }, body: { ko: "붉은 차양으로 그래플.", en: "Grapple on the red awning." } },
            { number: 34, title: { ko: "빛나는 짐승의 거울", en: "Mirror of the Shining Beast" }, location: { ko: "하와이 — 사우스 와이키키, 팬시 쿠키 근처", en: "Hawaii — South Waikiki, near Fancy Cookies" }, body: { ko: "차양으로 그래플.", en: "Grapple on the awning." } },
            { number: 35, title: { ko: "명암의 회중시계", en: "Chiaroscuro Pocket Watch" }, location: { ko: "하와이 — 이스트 와이키키, 노 서프 노 라이프 근처", en: "Hawaii — East Waikiki, near No Surf No Life" }, body: { ko: "지붕으로 그래플.", en: "Grapple on the rooftop." } },
            { number: 36, title: { ko: "영광의 핀", en: "Glorious Pin" }, location: { ko: "하와이 — 이스트 와이키키, 줄리스 기어웍스 남쪽", en: "Hawaii — East Waikiki, south of Julie's Gearworks" }, body: { ko: "호텔 차양으로 그래플.", en: "Grapple on the hotel awning." } },
            { number: 37, title: { ko: "백열의 반지", en: "Ring of Candescence" }, location: { ko: "하와이 — 웨스트 와이키키, L&L 하와이안 바베큐", en: "Hawaii — West Waikiki, L&L Hawaiian Barbecue" }, body: { ko: "차양으로 그래플.", en: "Grapple on the awning." } },
            { number: 38, title: { ko: "광명의 반지", en: "Ring of Illumination" }, location: { ko: "하와이 — 알로하 비치, 그레이슨의 무기점", en: "Hawaii — Aloha Beach, Grayson's Weapons at Sea" }, body: { ko: "실버 보물상자를 30,000달러에 구매.", en: "Purchase a Silver Treasure Chest for $30,000." } },
            { number: 39, title: { ko: "신성한 빛의 성배", en: "Divine Light Goblet" }, location: { ko: "하와이 — 리틀 재팬, 오픈 로드 쇼기", en: "Hawaii — Little Japan, Open Road Shogi" }, body: { ko: "실버 보물상자를 3,000포인트로 구매.", en: "Purchase a Silver Treasure Chest for 3,000 points." } },
            { number: 40, title: { ko: "햇살의 돌", en: "Sunshine Stone" }, location: { ko: "하와이 — 리틀 재팬, 포춘 익스체인지", en: "Hawaii — Little Japan, Fortune Exchange" }, body: { ko: "실버 보물상자를 35포인트로 구매.", en: "Purchase a Silver Treasure Chest for 35 points." } },
            { number: 41, title: { ko: "나무 정령 램프", en: "Tree Spirit's Lamp" }, location: { ko: "하와이 — 컬처럴 디스트릭트, 하이퍼 엑스터시", en: "Hawaii — Cultural District, Hyper Ecstasy" }, body: { ko: "차양으로 그래플.", en: "Grapple on the awning." } },
            { number: 42, title: { ko: "꽃의 성배", en: "Floral Chalice" }, location: { ko: "하와이 — 아나콘다, 트레저 셀렉트 전당포", en: "Hawaii — Anaconda, Treasure Select Pawn" }, body: { ko: "우든 보물상자를 20,000달러에 구매.", en: "Purchase a Wooden Treasure Chest for $20,000." } },
            { number: 43, title: { ko: "번영의 거울", en: "Mirror of Prosperity" }, location: { ko: "하와이 — 차이나타운, 판타지아 마작", en: "Hawaii — Chinatown, Fantasia Mahjong" }, body: { ko: "차양으로 그래플.", en: "Grapple on the awning." } },
            { number: 44, title: { ko: "꽃의 부적", en: "Flower Charm" }, location: { ko: "하와이 — 아나콘다", en: "Hawaii — Anaconda" }, body: { ko: "챕터 2 스토리로 자동 입수.", en: "Story-obtained in Chapter 2." } },
            { number: 45, title: { ko: "나뭇잎의 반지", en: "Ring of Leaves" }, location: { ko: "하와이 — 시퍼스 워프, 부두", en: "Hawaii — Shipper's Wharf, Pier" }, body: { ko: "차양으로 그래플.", en: "Grapple on the awning." } },
            { number: 46, title: { ko: "만개의 반지들", en: "Rings of Blossom" }, location: { ko: "하와이 — 하버 파크, 드래곤 카트", en: "Hawaii — Harbor Park, Dragon Kart" }, body: { ko: "상품 교환소에서 1,500포인트로 교환.", en: "Purchase from the prize exchange for 1,500 points." } },
            { number: 47, title: { ko: "꽃의 반지", en: "Ring of Flowers" }, location: { ko: "하와이 — 알로하 비치, 식코 스냅", en: "Hawaii — Aloha Beach, Sicko Snap" }, body: { ko: "29,000포인트로 구매.", en: "Purchase for 29,000 points." } },
            { number: 48, title: { ko: "숲의 성배", en: "Forest Goblet" }, location: { ko: "하와이 — 디스트릭트 파이브, 다이아몬드 헤드 바", en: "Hawaii — District Five, Diamond Head Bar" }, body: { ko: "실버 보물상자를 2,500포인트로 구매.", en: "Purchase a Silver Treasure Chest for 2,500 points." } },
            { number: 49, title: { ko: "초원 카펫", en: "Grassy Plain Carpet" }, location: { ko: "하와이 — 다운타운, 샤크 티스 기념품점 근처", en: "Hawaii — Downtown, near Shark Teeth Souvenirs" }, body: { ko: "차양으로 그래플.", en: "Grapple on the awning." } },
            { number: 50, title: { ko: "정글의 돌", en: "Jungle Stone" }, location: { ko: "하와이 — 다운타운, 크레이지 딜리버리", en: "Hawaii — Downtown, Crazy Delivery" }, body: { ko: "25,000포인트로 구매.", en: "Purchase for 25,000 points." } },
          ],
        },
        {
          title: { ko: "플레임/프로스트 헤븐 — 51~60", en: "Flame / Frost Heaven — 51-60" },
          items: [
            { number: 51, title: { ko: "불의 여신의 화로", en: "Fire Goddess's Brazier" }, location: { ko: "플레임 헤븐 — 선셋 아일랜드", en: "Flame Heaven — Sunset Island" } },
            { number: 52, title: { ko: "화산의 반지", en: "Ring of Volcanoes" }, location: { ko: "플레임 헤븐 — 히트웨이브 아일랜드", en: "Flame Heaven — Heatwave Island" } },
            { number: 53, title: { ko: "화산의 성배", en: "Volcanic Goblet" }, location: { ko: "플레임 헤븐 — 웰던 아일랜드", en: "Flame Heaven — Welldone Island" } },
            { number: 54, title: { ko: "불타는 융단", en: "Burning Rug" }, location: { ko: "플레임 헤븐 — 스코칭 히트 아일랜드", en: "Flame Heaven — Scorching Heat Island" } },
            { number: 55, title: { ko: "인페르노 스톤", en: "Inferno Stone" }, location: { ko: "플레임 헤븐 — 플레임 아일랜드 등대 남동쪽", en: "Flame Heaven — southeast of Flame Island Lighthouse" }, body: { ko: "데빌 플래그스 소속 배를 격파해야 입수.", en: "Defeat the Devil Flags ship here to obtain." } },
            { number: 56, title: { ko: "얼음 여신의 얼음 그릇", en: "Ice Goddess's Frozen Bowl" }, location: { ko: "프로스트 헤븐 — 스노우뷰 아일랜드", en: "Frost Heaven — Snowview Island" } },
            { number: 57, title: { ko: "영원한 서리의 거울", en: "Eternal Freeze Mirror" }, location: { ko: "프로스트 헤븐 — 콜드웨이브 아일랜드", en: "Frost Heaven — Coldwave Island" } },
            { number: 58, title: { ko: "서리의 반지", en: "Ring of Frost" }, location: { ko: "프로스트 헤븐 — 아이시클 아일랜드", en: "Frost Heaven — Icicle Island" } },
            { number: 59, title: { ko: "눈보라 스노우글로브", en: "Snowstorm Snow Globe" }, location: { ko: "프로스트 헤븐 — 글레이셜 아일랜드", en: "Frost Heaven — Glacial Island" } },
            { number: 60, title: { ko: "빙산의 돌", en: "Iceberg Stone" }, location: { ko: "프로스트 헤븐 — 프로스트 아일랜드 등대 남서쪽", en: "Frost Heaven — southwest of Frost Island Lighthouse" }, body: { ko: "데빌 플래그스 소속 배를 격파해야 입수.", en: "Defeat the Devil Flags ship here to obtain." } },
          ],
        },
        {
          title: { ko: "다크 갓 시리즈 + 최종 보상 — 61~65", en: "Dark God Series + Final Reward — 61-65" },
          items: [
            { number: 61, title: { ko: "암흑신의 바이올린", en: "Dark God's Violin" }, location: { ko: "마들란티스 인근 해역", en: "Waters Near Madlantis" }, body: { ko: "챕터 2 스토리로 자동 입수.", en: "Story-obtained in Chapter 2." } },
            { number: 62, title: { ko: "암흑신의 오카리나", en: "Dark God's Ocarina" }, location: { ko: "아탈리 아일랜드 인근 해역", en: "Waters Near Atali Island" }, body: { ko: "데빌 플래그스 첫 번째 간부 격파 시 입수.", en: "Defeat the first Devil Flags officer to obtain." } },
            { number: 63, title: { ko: "암흑신의 기타", en: "Dark God's Guitar" }, location: { ko: "플레임 헤븐", en: "Flame Heaven" }, body: { ko: "데빌 플래그스 두 번째 간부 격파 시 입수.", en: "Defeat the second Devil Flags officer to obtain." } },
            { number: 64, title: { ko: "암흑신의 색소폰", en: "Dark God's Saxophone" }, location: { ko: "프로스트 헤븐", en: "Frost Heaven" }, body: { ko: "데빌 플래그스 세 번째 간부 격파 시 입수.", en: "Defeat the third Devil Flags officer to obtain." } },
            { number: 65, title: { ko: "우리가 함께 걸어온 길", en: "The Friends We Made Along the Way" }, location: { ko: "스토리 최종장", en: "Story finale" }, body: { ko: "데빌 플래그스 두목을 격파하면 입수.", en: "Obtained after defeating the Devil Flags leader." } },
          ],
        },
      ],
    },
    {
      slug: "pets",
      title: { ko: "고로 킹덤 — 펫 11마리", en: "Goro Kingdom — All 11 Pets" },
      summary: {
        ko: "「Making a Menagerie」 업적은 펫 7마리 확보 시 발동. 3마리(고로·피닉스·오니기리)는 스토리로 자동 합류하니 나머지 8마리 중 4마리만 더 찾으면 됩니다.",
        en: "'Making a Menagerie' needs 7 pets. 3 (Goro, Phoenix, Onigiri) join automatically via the story, so only 4 more of the remaining 8 are needed.",
      },
      source: { label: "TheGamer — Goro Kingdom Complete Animal Location Guide", url: "https://www.thegamer.com/like-a-dragon-pirate-yakuza-in-hawaii-goro-kingdom-complete-animal-location-guide/" },
      items: [
        { number: 1, title: { ko: "고로", en: "Goro" }, location: { ko: "게임 시작 시 자동 합류", en: "Joins automatically at game start" }, reward: { ko: "레벨업마다 고기 보상", en: "Provides meat at various levels" } },
        { number: 2, title: { ko: "피닉스", en: "Phoenix" }, location: { ko: "스텔라 상점 — 스토리 진행 중 합류", en: "Stella's Shop — joins during story progression" }, reward: { ko: "달걀 보상", en: "Provides eggs as rewards" } },
        { number: 3, title: { ko: "오니기리", en: "Onigiri" }, location: { ko: "디스트릭트 파이브", en: "District Five" }, body: { ko: "학대범을 처치하는 \"디스트릭트 파이브의 새끼 고양이\" 서브스토리로 필수 합류(스토리 진행상 피할 수 없음).", en: "Recruited through the unavoidable 'Kitten in District Five' substory after defeating an abuser." } },
        { number: 4, title: { ko: "바클리", en: "Barkley" }, location: { ko: "아나콘다 쇼핑센터 북쪽 입구", en: "North entrance of the Anaconda Shopping Center" }, body: { ko: "그 자리의 여성과 함께 먹이를 줘서 친해진다.", en: "Give food to befriend, alongside the woman present there." } },
        { number: 5, title: { ko: "주미즈", en: "Zoomies" }, location: { ko: "하버 디스트릭트", en: "Harbor District" }, body: { ko: "붙잡은 뒤 북서쪽으로 달아나면 \"부드럽게 대하기\"를 선택.", en: "Help catch them, then select 'Be gentle' when they run to the northwest section." } },
        { number: 6, title: { ko: "코코", en: "Coco" }, location: { ko: "알로하 다리 근처, 크림&베리 레스토랑 북쪽", en: "Near Aloha Bridge, north of Cream & Berry restaurant" }, body: { ko: "나무 흔들기·코코넛 던지기·포즈 취하기 세 가지 상호작용을 모두 완료해야 합류.", en: "Complete all three interaction options (shake tree, toss coconut, strike pose) to recruit." } },
        { number: 7, title: { ko: "얼루어", en: "Allure" }, location: { ko: "알로하 거리, L&L 하와이안 바베큐 서쪽", en: "Aloha St., west of L&L Hawaiian Barbecue" }, prereq: { ko: "리버 티(Liber Tea) 은색 컨테이너에서 고로미 의상 입수 필요", en: "Requires the Goromi outfit from a Silver Container at Liber Tea" }, body: { ko: "고로미 의상을 입어야 다가와 합류.", en: "Must wear the Goromi outfit to recruit." } },
        { number: 8, title: { ko: "더 거먼드", en: "The Gourmand" }, location: { ko: "아나콘다 강변 구역", en: "Along the Anaconda river section" }, body: { ko: "해변에서 직접 손낚시로 잡은 \"와일드 캐치 사시미\"를 줘야 합류.", en: "Provide Wild Caught Sashimi, obtained by hand-fishing on the beach." } },
        { number: 9, title: { ko: "알람 클럭", en: "Alarm Cluck" }, location: { ko: "아야메 거리 서쪽 아파트 단지", en: "West of Ayame Street in the apartments" }, body: { ko: "수면 부족에 시달리는 남자가 공격 중인 수탉을 구해주면 합류.", en: "Defeat the sleep-deprived man attacking the rooster." } },
        { number: 10, title: { ko: "터틀", en: "Turtle" }, location: { ko: "리버 스트리트·카쿠 애비뉴 교차로, 크레이프 포 미 서쪽", en: "Intersection between River St. and Kaku Ave, west of Crepes for Me" }, body: { ko: "괴롭히는 불량배들을 처치하면 합류.", en: "Battle the goons harassing it." } },
        { number: 11, title: { ko: "산젠", en: "Sanzen" }, location: { ko: "선셋 파크 파빌리온", en: "Sunset Park pavilion area" }, body: { ko: "주인에게 3,000달러를 지불하고 구매.", en: "Pay $3,000 to purchase from the owner." } },
      ],
    },
    {
      slug: "islands",
      title: { ko: "섬 탐험 10개 — Island Adventurer", en: "Island Exploration — 10 Islands (Island Adventurer)" },
      summary: {
        ko: "던전형 섬 10곳을 클리어하면 「Island Adventurer」 업적이 발동합니다. 확인된 던전 섬은 다이나·점보(리치 아일랜드 해역), 알레·엘레아나·이모스(네레 아일랜드 해역), 바하·바낙·고알레가(마들란티스 해역), 후아카이·나하나하·마카우누이(하와이 해역), 야나기·사산콰·엠마(아탈리 아일랜드 해역) 등 20곳 이상 존재 — 어느 10곳을 고르든 상관없이 클리어하면 카운트됩니다.",
        en: "Clear 10 dungeon-style islands for 'Island Adventurer'. Confirmed dungeon islands include Dyna & Jumbo (Rich Island waters), Ahle, Eleahna & Eamoth (Nele Island waters), Baja, Varnack & Goalega (Madlantis waters), Huaka'i, Nahanaha & Makau Nui (Hawaii waters), Yanagi, Sasanqua & Emma (Atali Island waters) — 20+ exist in total, and any 10 cleared count toward the achievement.",
      },
      tips: [
        { ko: "각 섬은 배를 타고 접근한 뒤 상륙해서 클리어하는 소규모 던전입니다. 보물 목록(위 카테고리)의 '위치'란에 적힌 섬 이름이 곧 탐험 대상 섬이므로, 보물을 모으며 자연스럽게 여러 섬을 들르게 됩니다.", en: "Each island is a small sail-to-and-clear dungeon. The island names in the Treasure list above double as your exploration targets — collecting treasures naturally routes you through several of them." },
      ],
      source: { label: "GameFAQs — Island Life and Exploration", url: "https://gamefaqs.gamespot.com/ps5/487752-like-a-dragon-pirate-yakuza-in-hawaii/faqs/81725/island-life-and-exploration" },
    },
    {
      slug: "crew",
      title: { ko: "고로 해적단 — 크루 영입 (30/50/80명)", en: "Goro Pirates — Crew Recruitment (30/50/80)" },
      summary: {
        ko: "전체 107명 중 30명 합류 시 「Welcome to the Goro Pirates!」, 50명 시 「The Goro Pirates Set Sail!」, 80명 시 「Goro Pirates, Go Go Go!」 업적이 발동합니다. 영입 방법은 스카우트·서브스토리·미니게임 포인트 교환 세 가지로 나뉩니다.",
        en: "Of 107 total crew, recruit 30 for 'Welcome to the Goro Pirates!', 50 for 'The Goro Pirates Set Sail!', 80 for 'Goro Pirates, Go Go Go!'. Recruitment splits into three methods: scouting, substories, and minigame-point exchanges.",
      },
      tips: [
        { ko: "스카우트 대상은 맵에 아이콘으로 표시되며, 커서를 올리면 필요한 조건(아이템 전달·평판 등급·알로하 링크 친구 수·전투 승리 등)이 바로 보입니다.", en: "Scoutable crew show as map icons — hover to see the exact condition (item hand-off, reputation rank, Aloha Links friend count, fight win, etc.)." },
        { ko: "예: 바텐더(하와이 리볼브 바 — 알로하 링크 100명), 줄리(줄리스 기어웍스 — 대포 3종 제작 후 대화), 이카리(오나바라 직업학교 — 시험 10회 합격).", en: "Examples: Bartender (Revolve Bar, Hawaii — 100 Aloha Links friends), Julie (Julie's Gearworks — talk to her after crafting any 3 cannons), Ikari (Ounabara Vocational School — pass any 10 exams)." },
        { ko: "서브스토리 한정 크루도 있습니다 (드레드 파이럿 훅 — \"선장의 귀환\", 스테파니 챈 — \"기적의 아쿠아리움\", 에나 — \"그 하나\" 최종 파트).", en: "Some crew are substory-locked only (Dread Pirate Hook — 'The Captain's Return', Stephanie Chan — 'The Miracle Aquarium', Ena — final part of 'The One')." },
        { ko: "마들란티스 쪽 크루는 대부분 결투 승리나 금전 지불처럼 더 거친 방식으로 영입해야 합니다.", en: "Madlantis-side crew mostly require rougher methods — winning a melee/duel or paying them off." },
      ],
      source: [
        { label: "PowerPyx — All Crew Members Locations Guide", url: "https://www.powerpyx.com/like-a-dragon-pirate-yakuza-in-hawaii-all-crew-members-locations-guide/" },
        { label: "TheGamer — Crew Member Recruitment Location Guide", url: "https://www.thegamer.com/like-a-dragon-pirate-yakuza-in-hawaii-crew-member-recruitment-location-guide/" },
      ],
    },
    {
      slug: "photo-rally",
      title: { ko: "포토랠리 — 「Memories of Honolulu」", en: "Photo Rally — 'Memories of Honolulu'" },
      summary: {
        ko: "하와이·리치 아일랜드·마들란티스 전역에 사진 촬영 지점 100곳이 있으며, 그중 30장만 찍으면 업적이 발동합니다. 챕터 2 서브스토리 3 「사진으로 남기고 싶어서」로 처음 해금됩니다. 지역 세트를 전부 채우면 그 지역 한정 코스메틱 보상을 받습니다.",
        en: "100 photo spots exist across Hawaii, Rich Island, and Madlantis; only 30 are needed for the achievement. First unlocked via Chapter 2 Substory #3. Completing a full regional set grants a cosmetic item exclusive to that set.",
      },
      tips: [
        { ko: "예: '주택가 벽 위 코코넛 거북이'(마카니 애비뉴 서쪽, 노란 계단 두 개 사이), '트로피컬 창문 진열'(Seaworthy Treasures 매장), '이스트 알로하 비치 돌고래'(알로하 비치 동쪽 끝 기둥 위).", en: "Examples: 'Coconut Turtle on Housing Complex Wall' (west Makani Ave., between two yellow stairs), 'Tropical Window Display' (Seaworthy Treasures shop), 'East Aloha Beach' dolphin (post at the east end of Aloha Beach)." },
        { ko: "어디서든 30장만 채우면 되므로 접근하기 쉬운 하와이 본토 지점부터 우선 채우는 편이 효율적입니다.", en: "Since any 30 count, prioritize the easily-reached Hawaii mainland spots first." },
      ],
      source: { label: "PowerPyx — All Photo Rally Locations", url: "https://www.powerpyx.com/like-a-dragon-pirate-yakuza-in-hawaii-all-photo-rally-locations/" },
    },
    {
      slug: "outfits",
      title: { ko: "의상 수집 — 20/50/100종", en: "Outfit Collection — 20/50/100" },
      summary: {
        ko: "의상 20종 입수 시 「Goodbye, Old Me」, 50종 시 「Fashionista」, 100종 시 「Trendsetter」 업적이 발동합니다. 상점 구매·미니게임 상품 교환·서브스토리 보상 세 경로로 모입니다.",
        en: "20 items unlocks 'Goodbye, Old Me', 50 unlocks 'Fashionista', 100 unlocks 'Trendsetter'. Items come from shop purchases, minigame prize exchanges, and substory rewards.",
      },
      tips: [
        { ko: "하와이·마들란티스 각지의 의류점을 한 바퀴 돌며 사는 것만으로도 초반 목표(20종)는 금방 채워집니다.", en: "Simply shopping your way through the clothing stores in Hawaii and Madlantis fills the first tier (20) quickly." },
      ],
      source: { label: "Selphie1999Gaming — Outfit Sets Guide", url: "https://selphie1999gaming.com/game-guides/like-a-dragon-pirate-yakuza-in-hawaii/like-a-dragon-pirate-yakuza-in-hawaii-outfit-sets-how-to-get-all-the-costumes/" },
    },
    {
      slug: "hooking-and-gathering",
      title: { ko: "훅 채집 — 물고기·벌레 30마리", en: "Hooking and Gathering — 30 Fish & Bugs" },
      summary: {
        ko: "체인 훅으로 물고기·벌레를 30마리 채집하면 업적 발동. 종류별 위치를 전부 정리한 가이드는 존재하지 않아 개별 체크리스트는 제공하지 않습니다 — 아래 요령만 참고하세요.",
        en: "Achievement unlocks after catching 30 fish/bugs with the chain hook. No guide catalogs every species by location, so this isn't presented as a per-item checklist — just the tips below.",
      },
      tips: [
        { ko: "잠자리 등 곤충은 공원·수풀 근처에 반짝이는 형태로 나타납니다 (예: 골든 드래곤플라이 — 아나콘다 하버 파크, 알로하 다리 아래, 마카니 애비뉴·사쿠라 스트리트 모퉁이).", en: "Bugs like dragonflies spawn as shimmering shapes near parks/foliage (e.g. Golden Dragonfly — Anaconda Harbor Park, under Aloha Bridge, Makani Ave./Sakura Street corner)." },
        { ko: "물고기는 해안가·부두에서 훅으로 직접 낚아채면 되고, 종 구분 없이 30마리 누적이면 충분합니다.", en: "Fish can be hooked directly at shorelines/piers — any 30 catches count, no species requirement." },
      ],
      source: { label: "ScreenRant — All Dragonfly Locations", url: "https://screenrant.com/like-dragon-pirate-yukiza-hawaii-all-dragonfly-locations/" },
    },
  ],
};
