import type { CollectiblesData } from "./types";

export const yakuzaGaiden: CollectiblesData = {
  appId: 2375550,
  categories: [
    {
      slug: "coin-lockers",
      title: { ko: "물품 보관함 — 50개 열쇠와 보상", en: "Coin Lockers — 50 Keys & Rewards" },
      summary: {
        ko: "소텐보리·캐슬 전역에 흩어진 코인로커 열쇠 50개(A1~J5). 「Locked Up」 업적은 그중 30개만 열면 달성됩니다.",
        en: "50 coin-locker keys (A1-J5) scattered across Sotenbori and The Castle. The 'Locked Up' achievement only needs 30 of the 50 opened.",
      },
      tips: [
        { ko: "열쇠 자체는 거리·건물 구석에 떨어져 있고, 실제 로커함은 각 구역의 코인로커 부스에서 엽니다.", en: "Keys sit on the ground in streets/buildings; the actual lockers are opened at each district's coin-locker booth." },
      ],
      source: { label: "GameLeap — All 50 Locker Key Locations", url: "https://www.gameleap.com/articles/like-a-dragon-gaiden-guide-all-50-locker-key-locations-locked-up-trophy" },
      groups: [
        {
          title: { ko: "소텐보리 — 31개", en: "Sotenbori — 31 Keys" },
          items: [
            { number: 1, title: { ko: "A1", en: "A1" }, location: { ko: "화분 옆 계단을 내려간 곳", en: "Down the stairs next to some plants" }, reward: { ko: "스태미난 스파크", en: "Staminan Spark" } },
            { number: 2, title: { ko: "A2", en: "A2" }, location: { ko: "POPPO 매장 안쪽", en: "Inside the Poppo store, in the back" }, reward: { ko: "방탄조끼", en: "Bulletproof Vest" } },
            { number: 3, title: { ko: "A3", en: "A3" }, location: { ko: "거리의 파란 자판기 옆", en: "Next to the blue vending machine on the street" }, reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" } },
            { number: 5, title: { ko: "A5", en: "A5" }, location: { ko: "'Club Sun Shine' 간판 옆", en: "Next to the 'Club Sun Shine' board on the street" }, reward: { ko: "스태미난 스파크", en: "Staminan Spark" } },
            { number: 6, title: { ko: "B1", en: "B1" }, location: { ko: "아시타바 공원 화장실 안", en: "In the toilet in Ashitaba Park" }, reward: { ko: "스태미난 로열", en: "Staminan Royale" } },
            { number: 7, title: { ko: "B2", en: "B2" }, location: { ko: "차고 안 흰색 차 옆", en: "In the car garage next to the white car" }, reward: { ko: "퓨어 화이트 브리프", en: "Pure White Briefs" } },
            { number: 8, title: { ko: "B3", en: "B3" }, location: { ko: "세가 클럽 안 자판기 옆", en: "Inside the Sega club, next to the vending machines" }, reward: { ko: "그린 젬 브레이슬릿", en: "Green Gem Bracelet" } },
            { number: 9, title: { ko: "B4", en: "B4" }, location: { ko: "이와오 다리 위 전등갓 안", en: "On Iwao Bridge, inside of a lampshade" }, reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" } },
            { number: 11, title: { ko: "C1", en: "C1" }, location: { ko: "거북이 석상 뒤쪽 중 하나", en: "Behind one of the turtle statues" }, reward: { ko: "골드 플레이트", en: "Gold Plate" } },
            { number: 14, title: { ko: "C4", en: "C4" }, location: { ko: "도박장 위층", en: "On the upper floor of the gambling hall" }, reward: { ko: "페이백 링", en: "Payback Ring" } },
            { number: 16, title: { ko: "D1", en: "D1" }, location: { ko: "니시소텐보리 거리 화분 뒤", en: "Behind the plants on West Sotenbori Street" }, reward: { ko: "카리스마틱 포토", en: "Charismatic Photo" } },
            { number: 17, title: { ko: "D2", en: "D2" }, location: { ko: "인포멘 매장 안", en: "Inside the Infomen shop" }, reward: { ko: "콘택트렌즈", en: "Contact Lenses" } },
            { number: 18, title: { ko: "D3", en: "D3" }, location: { ko: "세실 커피숍 간판 위", en: "On top of the Sesil Coffee Shop sign" }, reward: { ko: "골드 플레이트", en: "Gold Plate" } },
            { number: 21, title: { ko: "E1", en: "E1" }, location: { ko: "흰 오토바이와 빨간 자판기 사이, 와일드 잭슨 근처", en: "Between the white bike and red vending machine, close to Wild Jackson" }, reward: { ko: "바디 아머", en: "Body Armor" } },
            { number: 22, title: { ko: "E2", en: "E2" }, location: { ko: "뉴 모모코 바 지하 통로", en: "Under the New Momoko Bar — find the passage under the building" }, reward: { ko: "플래티넘 플레이트", en: "Platinum Plate" } },
            { number: 23, title: { ko: "E3", en: "E3" }, location: { ko: "쇼후쿠초 거리 대형 고양이 상 앞", en: "In front of the large cat on Shofukucho street" }, reward: { ko: "골드 플레이트", en: "Gold Plate" } },
            { number: 26, title: { ko: "F1", en: "F1" }, location: { ko: "다이도지 아지트 1층", en: "On the ground floor of the Daidoji Hideout" }, reward: { ko: "에일리언 신드롬", en: "Alien Syndrome" } },
            { number: 27, title: { ko: "F2", en: "F2" }, location: { ko: "슈틸 바 안, 나무 테이블 아래", en: "Inside Stijl Bar, under a wooden table" }, reward: { ko: "플래티넘 플레이트", en: "Platinum Plate" } },
            { number: 29, title: { ko: "F4", en: "F4" }, location: { ko: "빵집과 문 리버 사이 좁은 틈", en: "In a small gap between the pastry shop and Moon River" }, reward: { ko: "판타지 존 II", en: "Fantasy Zone II" } },
            { number: 31, title: { ko: "G1", en: "G1" }, location: { ko: "거리 옆 계단 위", en: "On top of the stairs to the side of the street" }, reward: { ko: "블러디 바인딩", en: "Bloody Binding" } },
            { number: 32, title: { ko: "G2", en: "G2" }, location: { ko: "소텐보리 거리 복어 간판 위", en: "On top of the pufferfish sign on Sotenbori Street" }, reward: { ko: "방탄조끼", en: "Bulletproof Vest" } },
            { number: 36, title: { ko: "H1", en: "H1" }, location: { ko: "계단 위, 소화기 옆", en: "At the top of the stairs, next to the fire extinguisher" }, reward: { ko: "스태미난 로열", en: "Staminan Royale" } },
            { number: 37, title: { ko: "H2", en: "H2" }, location: { ko: "릿치 타워 마작장 안, 나무 테이블 아래", en: "Inside Ricchi Tower Mahjong, under the wooden tables" }, reward: { ko: "골드 플레이트", en: "Gold Plate" } },
            { number: 38, title: { ko: "H3", en: "H3" }, location: { ko: "쿠쿠루 매장 앞 차양 위", en: "On the canopy in front of the Kukuru shop" }, reward: { ko: "플래티넘 플레이트", en: "Platinum Plate" } },
            { number: 40, title: { ko: "H5", en: "H5" }, location: { ko: "소텐보리 도박장 최상층, 파란 책상 뒤", en: "On the top floor of the Gambling Hall in Sotenbori, behind the blue desk" }, reward: { ko: "고토크 모터 Mk.III", en: "High Torque Motor Mark III" } },
            { number: 41, title: { ko: "I1", en: "I1" }, location: { ko: "코스타 포켓 레이싱 건물 세면대 옆", en: "Next to one of the sinks in the CourStar Pocket Racing building" }, reward: { ko: "스태미난 로열", en: "Staminan Royale" } },
            { number: 42, title: { ko: "I2", en: "I2" }, location: { ko: "소텐보리 거리 붉은 문어상 촉수 위", en: "On one of the tentacles of the red octopus statue on Sotenbori Street" }, reward: { ko: "스자쿠 브레이슬릿", en: "Suzaku Bracelet" } },
            { number: 43, title: { ko: "I3", en: "I3" }, location: { ko: "소텐보리 도박장 남쪽 건물 환기구 위", en: "On top of one of the vents of the building south of the Sotenbori Gambling Hall" }, reward: { ko: "골드 플레이트", en: "Gold Plate" } },
            { number: 44, title: { ko: "I4", en: "I4" }, location: { ko: "소텐보리 강변 산책로 나무 위", en: "On a tree close to the river on Sotenbori Footpath" }, reward: { ko: "엔듀로 레이서 ROM", en: "Enduro Racer ROM" } },
            { number: 46, title: { ko: "J1", en: "J1" }, location: { ko: "키스 샷 빌리아드&바 안쪽 구석", en: "In the corner inside Kiss Shot Billiards & Bar" }, reward: { ko: "블레스우드 아머 레플리카", en: "Blesswood Armor Replica" } },
            { number: 47, title: { ko: "J2", en: "J2" }, location: { ko: "바샤몬 다리 등롱 안", en: "In a lantern on Bashamon Bridge" }, reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" } },
            { number: 50, title: { ko: "J5", en: "J5" }, location: { ko: "콜로세움 접수처 구석", en: "In the Coliseum reception area, in the corner of the room" }, reward: { ko: "스태미난 스파크", en: "Staminan Spark" } },
          ],
        },
        {
          title: { ko: "캐슬 — 19개", en: "The Castle — 19 Keys" },
          items: [
            { number: 4, title: { ko: "A4", en: "A4" }, location: { ko: "헬기 착륙장 옆 난간 끝", en: "Next to the helicopter pad, on the edge of the rail" }, reward: { ko: "서클 이어링", en: "Circle Earrings" } },
            { number: 10, title: { ko: "B5", en: "B5" }, location: { ko: "도박장 정문 앞", en: "In front of the Gambling Hall" }, reward: { ko: "피어리스 바인딩", en: "Fearless Binding" } },
            { number: 12, title: { ko: "C2", en: "C2" }, location: { ko: "트윈 오거 게이트 북쪽, 웨이트리스 옆", en: "On the north side of the Twin Ogre Gate, next to the waitress" }, reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" } },
            { number: 13, title: { ko: "C3", en: "C3" }, location: { ko: "캐슬 캬바레 안, 의자 위", en: "Inside the Castle Cabaret on a chair" }, reward: { ko: "블레스우드 아머 레플리카", en: "Blesswood Armor Replica" } },
            { number: 15, title: { ko: "C5", en: "C5" }, location: { ko: "캐슬 중앙 거리, 붉은 수레 뒤", en: "Behind the red carriage on Castle Central Street" }, reward: { ko: "센고쿠 아머", en: "Sengoku Armor" } },
            { number: 19, title: { ko: "D4", en: "D4" }, location: { ko: "파이터즈 라운지 대형 스크린 위", en: "On top of the big screen in the Fighters' Lounge" }, reward: { ko: "블루 볼트", en: "Blue Bolt" } },
            { number: 20, title: { ko: "D5", en: "D5" }, location: { ko: "트윈 오거 게이트 진입 전 남쪽 컨테이너 위", en: "On top of a container at the south edge, before entering the Twin Ogre Gate area" }, reward: { ko: "겐부 브레이슬릿", en: "Genbu Bracelet" } },
            { number: 24, title: { ko: "E4", en: "E4" }, location: { ko: "맵 북서쪽 끝, 지면보다 약간 높은 곳", en: "On the northwest edge of the map, a bit above ground" }, reward: { ko: "ZONe", en: "ZONe" } },
            { number: 25, title: { ko: "E5", en: "E5" }, location: { ko: "도박장 상층, 칸막이 뒤 가장자리", en: "On the upper level of the Gambling Hall, behind the dividers on the edge" }, reward: { ko: "슈퍼 슬릭 타이어", en: "Super Slick Tires" } },
            { number: 28, title: { ko: "F3", en: "F3" }, location: { ko: "도박장 안 달 그림 위", en: "On the moon picture/painting in the Gambling Hall" }, reward: { ko: "골드 플레이트", en: "Gold Plate" } },
            { number: 30, title: { ko: "F5", en: "F5" }, location: { ko: "카지노 상층, 계단 근처", en: "On the upper floor of the casino, close to the stairs" }, reward: { ko: "골드 다트", en: "Gold Darts" } },
            { number: 33, title: { ko: "G3", en: "G3" }, location: { ko: "VIP 라운지 수영장 모서리 근처", en: "Near the corner of the pool in the VIP Lounge" }, reward: { ko: "썬더 다트", en: "Thunder Darts" } },
            { number: 34, title: { ko: "G4", en: "G4" }, location: { ko: "부티크 앞 화분 속", en: "In the plants in front of the Boutique" }, reward: { ko: "플래티넘 플레이트", en: "Platinum Plate" } },
            { number: 35, title: { ko: "G5", en: "G5" }, location: { ko: "부티크 VIP 구역 구석", en: "In VIP Area of the Boutique in the corner" }, reward: { ko: "럭셔리 타임피스", en: "Luxury Timepiece" } },
            { number: 39, title: { ko: "H4", en: "H4" }, location: { ko: "카지노 앞 거대 광대 조각상 위", en: "On the huge clown statue in front of the Casino" }, reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" } },
            { number: 45, title: { ko: "I5", en: "I5" }, location: { ko: "파이터즈 라운지 구역 나무 캐비닛 위", en: "On wooden cabinet in the Fighters' Lounge area" }, reward: { ko: "킬러 비", en: "Killer Bee" } },
            { number: 48, title: { ko: "J3", en: "J3" }, location: { ko: "부티크 안, 검은 재킷들 옆", en: "Inside the Boutique, next to the black jackets" }, reward: { ko: "플래티넘 플레이트", en: "Platinum Plate" } },
            { number: 49, title: { ko: "J4", en: "J4" }, location: { ko: "VIP 라운지 스피커 위, 스크린 근처", en: "On top of the speakers next to the screen in the VIP Lounge Area" }, reward: { ko: "로얄 조커 카드", en: "Royal Joker Card" } },
          ],
        },
      ],
    },
    {
      slug: "gold-balls",
      title: { ko: "골드볼 7개 — 전부 찾기", en: "Gold Balls — All 7 Locations" },
      summary: {
        ko: "「Gotta Catch Some Balls!」 업적용 골드볼 7개의 정확한 위치와 입수 조건입니다.",
        en: "Exact location + acquisition condition for all 7 Gold Balls needed for 'Gotta Catch Some Balls!'.",
      },
      source: { label: "PowerPyx — All Gold Ball Locations", url: "https://www.powerpyx.com/like-a-dragon-gaiden-all-gold-ball-locations/" },
      items: [
        {
          number: 1,
          title: { ko: "키스 샷 빌리아드&바", en: "Kiss Shot Billiards & Bar" },
          location: { ko: "소텐보리", en: "Sotenbori" },
          body: { ko: "일반 원샷 챌린지 포인트를 모아 777점으로 교환.", en: "Trade for 777 billiard pts, earned from the Normal One-Shot challenge." },
        },
        {
          number: 2,
          title: { ko: "에비스 전당포 소텐보리점", en: "Ebisu Pawn Sotenbori" },
          location: { ko: "소텐보리", en: "Sotenbori" },
          body: { ko: "77,777엔에 구매 가능. 소텐보리 입장 즉시 구매 가능.", en: "Purchase for 77,777 yen — available as soon as you access Sotenbori." },
        },
        {
          number: 3,
          title: { ko: "낮의 유람선", en: "Daytime River Boat" },
          location: { ko: "소텐보리", en: "Sotenbori" },
          body: { ko: "낮 시간대에 다리 근처에서 스파이더 그래플로 지나가는 유람선(남자 탑승) 위 골드볼을 낚아챈다.", en: "During daytime hours, use the Spider grapple near the bridges to grab the ball from a moving sightseeing boat with a man aboard." },
        },
        {
          number: 4,
          title: { ko: "아카메 상점", en: "Akame Shop" },
          location: { ko: "소텐보리", en: "Sotenbori" },
          body: { ko: "\"이것저것 다 노려보겠어\" 옵션에 15만 엔을 투자하면 777포인트로 교환 가능.", en: "Trade for 777 pts, unlocked after investing 150,000 Yen in the 'I'm aimin' to have a bit o' everything!' option." },
        },
        {
          number: 5,
          title: { ko: "파이터즈 라운지", en: "Fighters Lounge" },
          location: { ko: "캐슬", en: "The Castle" },
          body: { ko: "실버 랭크부터 진입 가능. 계단 근처 대형 석상 다리 사이를 스파이더 그래플로 낚아챈다.", en: "Accessible at Silver Rank; use Spider grapple between the legs of a large statue near stairs to street level." },
        },
        {
          number: 6,
          title: { ko: "캐슬 중앙 거리", en: "Castle Central Street" },
          location: { ko: "캐슬", en: "The Castle" },
          body: { ko: "카지노 입구 왼쪽. 근처 건물 안 컨베이어 벨트 위를 도는 복면남에게서 스파이더 그래플로 낚아챈다.", en: "Left of the Casino entrance — use Spider grapple to grab the ball from a masked man rotating on conveyor belts inside a nearby building." },
        },
        {
          number: 7,
          title: { ko: "쇼후쿠초 거리", en: "Shofukucho Street" },
          location: { ko: "소텐보리", en: "Sotenbori" },
          prereq: { ko: "챕터 4 스트롤 앤 패트롤 의뢰 \"수상한 메모를 해결하라\" 수락", en: "Accept the Stroll n' Patrol request 'Solve the Mysterious Note' in Chapter 4" },
          body: { ko: "단서를 따라가면 쇼후쿠 호텔 근처 거북이 석상 북쪽 차양 위에서 발견.", en: "Follow the clues to find the ball on an awning north of the turtle pillars near Syoufuku Hotel." },
        },
      ],
    },
    {
      slug: "outfits",
      title: { ko: "의상 수집 — Fashion Scrub → Fashionista → Trendsetter", en: "Outfit Collection — Fashion Scrub → Fashionista → Trendsetter" },
      summary: {
        ko: "의상 15종 입수 시 「Fashion Scrub」, 30종 시 「Fashionista」, 50종 시 「Trendsetter」 업적 발동. 개별 의상 하나하나의 고정 획득처를 정리한 가이드는 없고, 세 가지 입수 경로로 나뉩니다.",
        en: "Collect 15 outfit pieces for 'Fashion Scrub', 30 for 'Fashionista', 50 for 'Trendsetter'. No guide tracks every single piece's fixed source individually — items come from three acquisition paths instead.",
      },
      tips: [
        { ko: "캐슬(챕터 2부터 접근 가능)의 '부티크'에 처음 방문하면 기본 아이템 다수가 바로 열려 있습니다.", en: "The Boutique in The Castle (accessible from Chapter 2) unlocks a batch of default items the moment you first visit." },
        { ko: "아카메 상점에서는 네트워크 포인트로, 부티크에서는 엔으로 구매합니다.", en: "Akame's Shop sells items for Network Points; the Boutique sells for yen." },
        { ko: "콜로세움에서 골드 랭크를 달성하면 부티크에 추가 의상이 잠금 해제·구매 가능해집니다.", en: "Reaching Gold Rank in the Coliseum unlocks additional purchasable items at the Boutique." },
      ],
      source: { label: "GameRant — All Outfit Clothing Items & How to Get Them", url: "https://gamerant.com/like-a-dragon-gaiden-all-outfit-clothing-items-how-to-get-them/" },
    },
  ],
};
