import type { CollectiblesData } from "./types";

export const yakuza5: CollectiblesData = {
  appId: 1105510,
  categories: [
    {
      slug: "purikura-frames",
      title: { ko: "현지 프레이머 — 프리서클 지역 한정 프레임 (전 도시)", en: "Local Framer — Print Club Regional Frames" },
      summary: {
        ko: "카무로초·소텐보리·나가스가이·츠키미노·킨에이초·사쿠라가와의 프리서클 부스를 모두 방문해 지역 한정 프레임으로 1회씩 촬영하면 「현지 프레이머」 업적 발동.",
        en: "Visit every Print Club booth across the six cities and shoot one photo with the regional frame to unlock 'Local Framer'.",
      },
    },
    {
      slug: "viewpoints",
      title: { ko: "관광의 용 — 뷰 포인트 각 도시 1개 이상 촬영", en: "Sightseeing Dragon — Viewpoints in Every City" },
      summary: {
        ko: "각 도시의 지정된 뷰 포인트를 카메라로 찍으면 「관광의 용」 업적 발동. 디지털 카메라 해금 후 도시 탐색 중 병행 진행이 효율적입니다.",
        en: "Photograph the marked viewpoint in every city to unlock 'Sightseeing Dragon'. Easiest done alongside city exploration after the camera unlocks.",
      },
    },
    {
      slug: "scavenger",
      title: { ko: "바닥을 보며 걷자 — 쓰레기·지도·추첨권·열쇠 누적 100개", en: "Eyes on the Ground — 100 Pickups" },
      summary: {
        ko: "쓰레기·지도 조각·경품 추첨권·보관함 열쇠를 누적 100개 이상 입수하면 「바닥을 보며 걷자」 업적 발동. 모든 도시를 도보로 돌며 자연스럽게 모이는 컴플리트 라인.",
        en: "Pick up 100+ ground items (trash / map fragments / lottery tickets / locker keys) to unlock 'Eyes on the Ground'. Builds passively while walking the cities.",
      },
    },
    {
      slug: "coin-lockers",
      title: { ko: "물품 보관함 — 양 도시 100개 열쇠와 보상", en: "Coin Lockers — All 100 Keys & Rewards (Both Cities)" },
      summary: {
        ko: "카무로초 50개 + 소텐보리 50개, 총 100개 코인로커 열쇠의 위치와 내용물을 정리했습니다. 「~을 주시」 항목은 시점을 맞춰야 반짝임이 보입니다. 지도의 번호가 카드 번호와 일치합니다.",
        en: "All 100 coin-locker keys (50 Kamurocho + 50 Sotenbori) with locations and contents. 'Look at ~' spots need the right camera angle to reveal the shine. Map numbers match the card numbers.",
      },
      tips: [
        { ko: "열쇠는 바닥의 반짝이는 지점을 조사해 얻습니다. 일부는 시점(카메라)을 맞춰야 보입니다.", en: "Keys come from shining ground spots; some only appear at the right camera angle." },
      ],
      source: { label: "龍が如く5攻略マップ付き — 神室町のコインロッカー", url: "http://ryugagotoku5.riroa.com/coinlocker_kamuro.html" },
      groups: [
        {
          title: { ko: "카무로초 — 50개 열쇠", en: "Kamurocho — 50 Keys" },
          mapImage: "/yakuza-5-lockers/kamuro.gif",
        hotspots: {
          1: [40.7, 26.6], 2: [58.4, 57.7], 3: [28.1, 15], 4: [38.2, 96.4], 5: [5.8, 23.8], 6: [28.5, 64.6], 7: [15.2, 67.6], 8: [23.6, 46.2], 9: [50.4, 37.2], 10: [30.9, 73.6],
          11: [30.4, 58.5], 12: [47.3, 66.4], 13: [63, 51.7], 14: [61.3, 67.4], 15: [41, 12.3], 16: [41.6, 16.5], 17: [14.5, 58], 19: [52.5, 53], 20: [57.5, 43.5],
          21: [47.3, 73.9], 22: [31.7, 31.9], 23: [30.3, 42.2], 24: [50.7, 79.5], 25: [66.9, 59], 27: [43.1, 73.8], 28: [36.6, 81.5], 29: [6.9, 38.6], 30: [36.3, 69.2],
          31: [23.6, 30.5], 32: [60.9, 78.1], 33: [9.7, 13.3], 34: [22.3, 17.1], 35: [77.2, 30], 36: [11.2, 31.9], 37: [52.2, 29.4], 38: [22.9, 74.8], 39: [21, 35.5], 40: [41.2, 42.9],
          41: [72.7, 37.3], 42: [11, 17.2], 43: [55.8, 16.8], 44: [68.9, 22.2], 45: [32.6, 51.5], 46: [9.5, 15.3], 47: [72.7, 40.3], 48: [64.5, 25.5], 49: [48.5, 57.5], 50: [68.5, 73.5],
        },
          items: [
        {
          number: 1,
          title: { ko: "A1", en: "A1" },
          location: { ko: "밀레니엄 타워 북쪽 트리(서쪽에서 2번째) 노면", en: "Road by the tree north of Millennium Tower (2nd from west)" },
          reward: { ko: "핀조로의 패", en: "Pinzoro Tile" },
        },
        {
          number: 2,
          title: { ko: "A2", en: "A2" },
          location: { ko: "큐슈 이치반보시 점내 화장실 앞", en: "Inside Kyushu Ichibanboshi, by the restroom" },
          reward: { ko: "SSS 건파우더", en: "SSS Gunpowder" },
        },
        {
          number: 3,
          title: { ko: "A3", en: "A3" },
          location: { ko: "배팅센터 내 담배 자판기 앞", en: "By the cigarette vending machine in the batting center" },
          reward: { ko: "고확 메달", en: "High-Chance Medal" },
        },
        {
          number: 4,
          title: { ko: "A4", en: "A4" },
          location: { ko: "지하상가 CuezBAR 점내 당구 대회 포스터 위를 주시", en: "Look above the pool-tournament poster in CuezBAR" },
          reward: { ko: "전국 사슬갑주", en: "Sengoku Chainmail" },
        },
        {
          number: 5,
          title: { ko: "A5", en: "A5" },
          location: { ko: "시치후쿠 거리 서쪽 24시간 주차장 앞", en: "In front of the West Shichifuku 24h parking" },
          reward: { ko: "쵸고로의 염주", en: "Chogoro Beads" },
        },
        {
          number: 6,
          title: { ko: "B1", en: "B1" },
          location: { ko: "제3공원 안", en: "Inside Third Park" },
          reward: { ko: "피트니스 기어", en: "Fitness Gear" },
        },
        {
          number: 7,
          title: { ko: "B2", en: "B2" },
          location: { ko: "뉴 세레나 뒤", en: "Behind New Serena" },
          reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" },
        },
        {
          number: 8,
          title: { ko: "B3", en: "B3" },
          location: { ko: "마츠야 천하일 거리점 북쪽 옆 스낵 유나기 간판 위 통풍구를 주시", en: "Vent above the Snack Yunagi sign north of Matsuya" },
          reward: { ko: "수수께끼의 휘석", en: "Mysterious Gem" },
        },
        {
          number: 9,
          title: { ko: "B4", en: "B4" },
          location: { ko: "밴텀 점내 오른쪽 선반을 주시", en: "Look at the right shelf inside Bantam" },
          reward: { ko: "슬래시 톤파", en: "Slash Tonfa" },
        },
        {
          number: 10,
          title: { ko: "B5", en: "B5" },
          location: { ko: "킷사 알프스 점내 점장 왼손 방향 바닥", en: "Floor left of the manager inside Cafe Alps" },
          reward: { ko: "강철 레가스", en: "Steel Greaves" },
        },
        {
          number: 11,
          title: { ko: "C1", en: "C1" },
          location: { ko: "천하일 거리 뒤 벽에 걸린 실외기를 주시", en: "Look at the AC unit on the wall behind Tenkaichi St" },
          reward: { ko: "스태미난 로열", en: "Staminan Royal" },
        },
        {
          number: 12,
          title: { ko: "C2", en: "C2" },
          location: { ko: "나카미치 거리 뒤", en: "Behind Nakamichi St" },
          reward: { ko: "앉아 한 방 패", en: "Sit-Down One-Shot Tile" },
        },
        {
          number: 13,
          title: { ko: "C3", en: "C3" },
          location: { ko: "2층 창에 노란 Mixed Reality라 쓰인 빌딩 벽면을 주시", en: "Wall of the building with the yellow 'Mixed Reality' 2F sign" },
          reward: { ko: "하이퍼 우콘", en: "Hyper Ukon" },
        },
        {
          number: 14,
          title: { ko: "C4", en: "C4" },
          location: { ko: "핑크 거리 뒤 동쪽 좁은 골목", en: "Narrow east alley behind Pink St" },
          reward: { ko: "행운 화투", en: "Lucky Hanafuda" },
        },
        {
          number: 15,
          title: { ko: "C5", en: "C5" },
          location: { ko: "류구죠 벽면 공사 부분을 주시", en: "Look at the construction part of the Ryugujo wall" },
          reward: { ko: "로열 조커", en: "Royal Joker" },
        },
        {
          number: 16,
          title: { ko: "D1", en: "D1" },
          location: { ko: "류구죠 도박장 안 통로", en: "Passage inside the Ryugujo gambling den" },
          reward: { ko: "버스트의 부적", en: "Burst Charm" },
        },
        {
          number: 17,
          title: { ko: "D2", en: "D2" },
          location: { ko: "슷폰 거리 카무로 라멘 입구 차양을 주시", en: "Look at the awning of Kamuro Ramen on Suppon St" },
          reward: { ko: "방탄유리 부적", en: "Bulletproof-Glass Charm" },
        },
        {
          number: 18,
          title: { ko: "D3", en: "D3" },
          location: { ko: "사이노카와라, 투기장을 나와 바로 있는 긴 의자 사이", en: "Between the benches just outside the Sai no Kawara arena" },
          reward: { ko: "검은 보석", en: "Black Gem" },
        },
        {
          number: 19,
          title: { ko: "D4", en: "D4" },
          location: { ko: "고토부키 약국 앞 붉은 에이라쿠테 간판(캬바걸 4인 간판) 아래", en: "Under the red Eirakutei sign (4 hostesses) by Kotobuki Pharmacy" },
          reward: { ko: "가시 철갑", en: "Thorn Iron Armor" },
        },
        {
          number: 20,
          title: { ko: "D5", en: "D5" },
          location: { ko: "핑크 거리 북쪽 주차장 3번", en: "Pink St north parking, spot 3" },
          reward: { ko: "도싯핀즈", en: "Doshippins" },
        },
        {
          number: 21,
          title: { ko: "E1", en: "E1" },
          location: { ko: "록란소 점내 바닥", en: "Floor inside Rokuranso" },
          reward: { ko: "강철 눈차크", en: "Steel Nunchaku" },
        },
        {
          number: 22,
          title: { ko: "E2", en: "E2" },
          location: { ko: "극장 지하 IF8 방 벽을 주시", en: "Look at the wall of the Theater B IF8 room" },
          reward: { ko: "짜고치기 패", en: "Loaded Tile" },
        },
        {
          number: 23,
          title: { ko: "E3", en: "E3" },
          location: { ko: "극장 티켓 판매 공간 비스듬히 위를 주시", en: "Look diagonally up at the theater ticket booth" },
          reward: { ko: "포톤 블레이드 MG", en: "Photon Blade MG" },
        },
        {
          number: 24,
          title: { ko: "E4", en: "E4" },
          location: { ko: "POPPO 쇼와 거리점 핑크 거리 쪽 벽면 기계를 주시", en: "Look at the wall machine on the Pink St side of POPPO Showa" },
          reward: { ko: "숀벤 산맥의 돌", en: "Shonben Mountain Stone" },
        },
        {
          number: 25,
          title: { ko: "E5", en: "E5" },
          location: { ko: "천량 거리 적백 울타리 인도 쪽", en: "Red-white fence sidewalk side, Senryo Ave" },
          reward: { ko: "바닥없는 라이터", en: "Bottomless Lighter" },
        },
        {
          number: 26,
          title: { ko: "F1", en: "F1" },
          location: { ko: "택시로 부두에 가서 창고 D3 앞 터릿을 주시", en: "Take a taxi to the pier; look at the turret in front of warehouse D3" },
          reward: { ko: "고설정 메달", en: "High-Setting Medal" },
        },
        {
          number: 27,
          title: { ko: "F2", en: "F2" },
          location: { ko: "에비스야 점내 입구 근처 선반", en: "Shelf near the Ebisuya entrance" },
          reward: { ko: "고양이 쓰다듬기 슈즈", en: "Cat-Pet Shoes" },
        },
        {
          number: 28,
          title: { ko: "F3", en: "F3" },
          location: { ko: "돈키호테 앞 모퉁이", en: "Corner in front of Don Quijote" },
          reward: { ko: "미끌미끌 샷", en: "Slippery Shot" },
        },
        {
          number: 29,
          title: { ko: "F4", en: "F4" },
          location: { ko: "마하 볼 점내 볼링공 선반 아래", en: "Under the bowling-ball rack in Mach Bowl" },
          reward: { ko: "축제 대형 부채", en: "Festival Big Fan" },
        },
        {
          number: 30,
          title: { ko: "F5", en: "F5" },
          location: { ko: "클럽 세가 나카미치 거리점 입구 앞", en: "In front of the Club SEGA Nakamichi entrance" },
          reward: { ko: "아라시의 양갱", en: "Arashi's Yokan" },
        },
        {
          number: 31,
          title: { ko: "G1", en: "G1" },
          location: { ko: "클럽 세가 극장 앞점 입구 앞", en: "In front of the Club SEGA Theater entrance" },
          reward: { ko: "행운 화투", en: "Lucky Hanafuda" },
        },
        {
          number: 32,
          title: { ko: "G2", en: "G2" },
          location: { ko: "쇼텐 안쪽에 있는 트로피를 주시", en: "Look at the trophy at the back of Shoten" },
          reward: { ko: "수수께끼의 휘석", en: "Mysterious Gem" },
        },
        {
          number: 33,
          title: { ko: "G3", en: "G3" },
          location: { ko: "사이노카와라에서 하수도로 내려가면 있는 낚시꾼 오른쪽", en: "Right of the angler down in the sewer from Sai no Kawara" },
          reward: { ko: "붉은 보석", en: "Red Gem" },
        },
        {
          number: 34,
          title: { ko: "G4", en: "G4" },
          location: { ko: "M스토어 카무로초점 북쪽 옆 카네무라 흥업 간판 아래", en: "Under the Kanemura Kogyo sign north of M Store" },
          reward: { ko: "터프니스 엠퍼러", en: "Toughness Emperor" },
        },
        {
          number: 35,
          title: { ko: "G5", en: "G5" },
          location: { ko: "타이헤이 거리 동쪽 골판지가 쌓인 빌딩 벽을 주시", en: "Wall of the building with stacked cardboard, East Taihei Blvd" },
          reward: { ko: "큐티 걸 스틱", en: "Cutie Girl Stick" },
        },
        {
          number: 36,
          title: { ko: "H1", en: "H1" },
          location: { ko: "마하 볼 북쪽 옆 WILD JACKSON 입구 앞", en: "In front of WILD JACKSON north of Mach Bowl" },
          reward: { ko: "튼튼한 철 파이프", en: "Sturdy Iron Pipe" },
        },
        {
          number: 37,
          title: { ko: "H2", en: "H2" },
          location: { ko: "시치후쿠 거리 동쪽 교자 다이묘 앞", en: "In front of Gyoza Daimyo, East Shichifuku St" },
          reward: { ko: "항복 말", en: "Surrender Piece" },
        },
        {
          number: 38,
          title: { ko: "H3", en: "H3" },
          location: { ko: "만에이마루 조금 남쪽 앞", en: "Just south of Maneimaru" },
          reward: { ko: "하이테크 암", en: "High-Tech Arm" },
        },
        {
          number: 39,
          title: { ko: "H4", en: "H4" },
          location: { ko: "극장 앞 광장 관광협회 회원 뒤쪽 방향", en: "Behind the tourism-association member at Theater Square" },
          reward: { ko: "BJ의 부적", en: "BJ Charm" },
        },
        {
          number: 40,
          title: { ko: "H5", en: "H5" },
          location: { ko: "밀레니엄 타워 반원 통로", en: "Millennium Tower semicircular passage" },
          reward: { ko: "휘두르기 부적", en: "Swing Charm" },
        },
        {
          number: 41,
          title: { ko: "I1", en: "I1" },
          location: { ko: "챔피언 거리 아텐시 북쪽 골목 벽을 주시", en: "Look at the wall of the alley north of Atenshi, Champion District" },
          reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
        },
        {
          number: 42,
          title: { ko: "I2", en: "I2" },
          location: { ko: "아동 공원 벤치 옆 검은 파이프를 주시", en: "Look at the black pipe beside the children's-park bench" },
          reward: { ko: "BANKER 말", en: "BANKER Piece" },
        },
        {
          number: 43,
          title: { ko: "I3", en: "I3" },
          location: { ko: "공원 앞 거리 LUNA BLUE HOTEL 서쪽 끝", en: "West end of LUNA BLUE HOTEL, Park Blvd" },
          reward: { ko: "카타요리사의 담배", en: "Katayori Cigarettes" },
        },
        {
          number: 44,
          title: { ko: "I4", en: "I4" },
          location: { ko: "웍스 우에야마 입구 동쪽 벽면을 주시", en: "Look at the wall east of the Works Ueyama entrance" },
          reward: { ko: "더블액션 리볼버", en: "Double-Action Revolver" },
        },
        {
          number: 45,
          title: { ko: "I5", en: "I5" },
          location: { ko: "나카미치 거리와 타이헤이 거리 교차로 모퉁이 간판 위를 주시", en: "Look above the sign at the Nakamichi/Taihei intersection" },
          reward: { ko: "고순도 플래티넘", en: "High-Purity Platinum" },
        },
        {
          number: 46,
          title: { ko: "J1", en: "J1" },
          location: { ko: "아동 공원 맨홀을 내려가 지하로 나온 정면의 「머리 주의」 붉은 간판을 주시", en: "Look at the red 'mind your head' sign in the children's-park manhole" },
          reward: { ko: "오토 메달", en: "Auto Medal" },
        },
        {
          number: 47,
          title: { ko: "J2", en: "J2" },
          location: { ko: "챔피언 거리 아텐시 점내 입구 부근", en: "Near the entrance inside Atenshi, Champion District" },
          reward: { ko: "PLAYER 말", en: "PLAYER Piece" },
        },
        {
          number: 48,
          title: { ko: "J3", en: "J3" },
          location: { ko: "시치후쿠 파크 안 1번", en: "Spot 1 inside Shichifuku Park" },
          reward: { ko: "너덜너덜한 머플러", en: "Tattered Muffler" },
        },
        {
          number: 49,
          title: { ko: "J4", en: "J4" },
          location: { ko: "고토부키 약국 뒤편 공터 빌딩 계단을 주시", en: "Look at the building stairs in the lot behind Kotobuki Pharmacy" },
          reward: { ko: "고확석", en: "High-Chance Stone" },
        },
        {
          number: 50,
          title: { ko: "J5", en: "J5" },
          location: { ko: "천량 거리 자전거 행렬 앞", en: "In front of the bike row on Senryo Ave" },
          reward: { ko: "무의 보석", en: "Void Gem" },
        },
          ],
        },
        {
          title: { ko: "소텐보리 — 50개 열쇠", en: "Sotenbori — 50 Keys" },
          mapImage: "/yakuza-5-lockers/sotenbori.gif",
        hotspots: {
          1: [33.1, 51.3], 2: [34.3, 73], 3: [74.7, 31.7], 4: [77.3, 41.3], 5: [49.4, 79.6], 6: [35.7, 64.6], 7: [33, 11.7], 8: [85.9, 6.8], 9: [60.2, 28.5], 10: [47.4, 62.8],
          11: [75.5, 35.3], 12: [40.6, 17.2], 13: [53.4, 20], 14: [49.2, 45.5], 15: [32.6, 24.3], 16: [14.3, 91.6], 17: [46.1, 80.4], 18: [33, 38], 19: [48.6, 9], 20: [23.7, 27.9],
          21: [4.2, 70.5], 22: [22.4, 73.3], 23: [17.1, 24.3], 24: [9, 49.5], 25: [71.4, 31.7], 26: [22.9, 34.5], 27: [61.2, 68.5], 28: [11.1, 13.9], 29: [23.8, 47.2], 30: [49.5, 82.5],
          31: [50.8, 37.4], 32: [32.5, 20.3], 33: [9.6, 8.4], 35: [19.1, 71.3], 36: [27.9, 20], 37: [60.2, 56], 38: [18.1, 10.5], 39: [63.8, 9.6], 40: [59.3, 65.2],
          41: [5.5, 11.6], 42: [44.5, 90.2], 43: [86.7, 11.7], 44: [52.4, 83.7], 45: [14.2, 62.2], 46: [75.3, 9], 47: [71.8, 76.1], 48: [83.3, 41.4], 49: [56.5, 13.6], 50: [41.4, 61.4],
        },
          items: [
        {
          number: 1,
          title: { ko: "A1", en: "A1" },
          location: { ko: "쇼후쿠초 돈키호테 앞", en: "In front of Don Quijote, Shofukucho" },
          reward: { ko: "구리 접시", en: "Copper Plate" },
        },
        {
          number: 2,
          title: { ko: "A2", en: "A2" },
          location: { ko: "호겐지 요코초 코료리 토모코 입구 위를 주시", en: "Look above the entrance of Tomoko, Hogenji Alley" },
          reward: { ko: "깜짝 맥주병", en: "Surprise Beer Bottle" },
        },
        {
          number: 3,
          title: { ko: "A3", en: "A3" },
          location: { ko: "이와하시 다리 한가운데", en: "Center of Iwa Bridge" },
          reward: { ko: "플래티넘 자", en: "Platinum Ruler" },
        },
        {
          number: 4,
          title: { ko: "A4", en: "A4" },
          location: { ko: "분자에몬스지 리사이클북 가게 입구 앞", en: "In front of the Recycle Book shop, Bunzaemon St" },
          reward: { ko: "오토 메달", en: "Auto Medal" },
        },
        {
          number: 5,
          title: { ko: "A5", en: "A5" },
          location: { ko: "다이나스티아 연예사무소 옥상", en: "Rooftop of the Dynasty Talent Agency" },
          reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
        },
        {
          number: 6,
          title: { ko: "B1", en: "B1" },
          location: { ko: "호겐지 요코초 소텐묘오 분향대 위를 주시", en: "Look atop the Soten Myo-o incense stand, Hogenji Alley" },
          reward: { ko: "터프니스 엠퍼러", en: "Toughness Emperor" },
        },
        {
          number: 7,
          title: { ko: "B2", en: "B2" },
          location: { ko: "소텐보리 거리 서쪽 다이코쿠 약국 앞", en: "In front of Daikoku Pharmacy, West Sotenbori St" },
          reward: { ko: "히후미 껌", en: "Hifumi Gum" },
        },
        {
          number: 8,
          title: { ko: "B3", en: "B3" },
          location: { ko: "M스토어 소텐보리점 안 계산대 앞 부근", en: "Near the register inside M Store Sotenbori" },
          reward: { ko: "금속 배트", en: "Metal Bat" },
        },
        {
          number: 9,
          title: { ko: "B4", en: "B4" },
          location: { ko: "소텐보리 측도 동쪽 강가 인도", en: "Riverside sidewalk, East Sotenbori Path" },
          reward: { ko: "스태미난 로열", en: "Staminan Royal" },
        },
        {
          number: 10,
          title: { ko: "B5", en: "B5" },
          location: { ko: "쇼후쿠초와 호겐지 요코초 교차로 건물을 주시", en: "Look at the building at the Shofukucho/Hogenji junction" },
          reward: { ko: "목제 칼리 스틱", en: "Wooden Kali Stick" },
        },
        {
          number: 11,
          title: { ko: "C1", en: "C1" },
          location: { ko: "이와하시 다리 계단을 내려가 다리 밑", en: "Under the bridge, down the Iwa Bridge stairs" },
          reward: { ko: "짜고치기 패", en: "Loaded Tile" },
        },
        {
          number: 12,
          title: { ko: "C2", en: "C2" },
          location: { ko: "소텐보리 거리 식당 와카키 위 가바야키 등롱을 주시", en: "Look at the eel-grill lantern above Wakaki, Sotenbori St" },
          reward: { ko: "거대 비닐 인형", en: "Giant Vinyl Doll" },
        },
        {
          number: 13,
          title: { ko: "C3", en: "C3" },
          location: { ko: "소텐보리 거리 와타미 옆 골목 자전거 위 벽을 주시", en: "Wall above the bike in the alley beside Watami" },
          reward: { ko: "오징어", en: "Squid" },
        },
        {
          number: 14,
          title: { ko: "C4", en: "C4" },
          location: { ko: "쇼후쿠초 좁은 골목 모퉁이 에어컨 실외기를 주시", en: "Look at the AC unit at the Shofukucho alley corner" },
          reward: { ko: "구리 접시", en: "Copper Plate" },
        },
        {
          number: 15,
          title: { ko: "C5", en: "C5" },
          location: { ko: "소텐보리 측도 서쪽 선라이즈 뒤 기계를 주시", en: "Look at the machine behind Sunrise, West Sotenbori Path" },
          reward: { ko: "방염 셔츠", en: "Flameproof Shirt" },
        },
        {
          number: 16,
          title: { ko: "D1", en: "D1" },
          location: { ko: "쇼후쿠초 서쪽 주차장 안 자판기를 주시", en: "Look at the vending machine in the West Shofukucho lot" },
          reward: { ko: "철 접시", en: "Iron Plate" },
        },
        {
          number: 17,
          title: { ko: "D2", en: "D2" },
          location: { ko: "다이나스티아 연예사무소 입구 옆 정사각 간판을 주시", en: "Look at the square sign beside the talent-agency entrance" },
          reward: { ko: "중력 변환 장치", en: "Gravity Converter" },
        },
        {
          number: 18,
          title: { ko: "D3", en: "D3" },
          location: { ko: "소텐보리 측도 서쪽 돈키호테 입구 앞", en: "In front of Don Quijote, West Sotenbori Path" },
          reward: { ko: "스태미난 로열", en: "Staminan Royal" },
        },
        {
          number: 19,
          title: { ko: "D4", en: "D4" },
          location: { ko: "소텐보리 거리 요코보리 골프 옆 와사이 마츠우라 입구 옆 벽 위를 주시", en: "Wall by Matsuura's entrance next to Yokobori Golf" },
          reward: { ko: "신사 우산", en: "Gentleman's Umbrella" },
        },
        {
          number: 20,
          title: { ko: "D5", en: "D5" },
          location: { ko: "소텐보리 측도 서쪽 계단 아래쪽", en: "Lower side of the West Sotenbori Path stairs" },
          reward: { ko: "어쌔신 스피어", en: "Assassin Spear" },
        },
        {
          number: 21,
          title: { ko: "E1", en: "E1" },
          location: { ko: "쇼후쿠초 서쪽 골목", en: "West Shofukucho alley" },
          reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" },
        },
        {
          number: 22,
          title: { ko: "E2", en: "E2" },
          location: { ko: "호겐지 요코초 BAR 크레스트 앞 골목", en: "Alley in front of BAR Crest, Hogenji Alley" },
          reward: { ko: "초합금 파이프", en: "Super-Alloy Pipe" },
        },
        {
          number: 23,
          title: { ko: "E3", en: "E3" },
          location: { ko: "비사몬교 앞 빌딩 벽의 기계를 주시", en: "Look at the wall machine of the building before Bishamon Bridge" },
          reward: { ko: "부적", en: "Charm" },
        },
        {
          number: 24,
          title: { ko: "E4", en: "E4" },
          location: { ko: "쇼후쿠초 서쪽 택시 옆 건물 간판 랏시를 주시", en: "Look at the Lassi sign beside the taxi, West Shofukucho" },
          reward: { ko: "강철 톤파", en: "Steel Tonfa" },
        },
        {
          number: 25,
          title: { ko: "E5", en: "E5" },
          location: { ko: "이와하시 다리 난간(바깥 통로 쪽)", en: "Railing of Iwa Bridge (outer path side)" },
          reward: { ko: "고설정 메달", en: "High-Setting Medal" },
        },
        {
          number: 26,
          title: { ko: "F1", en: "F1" },
          location: { ko: "비사몬교 다리 밑을 주시", en: "Look under Bishamon Bridge" },
          reward: { ko: "아미 나이프", en: "Army Knife" },
        },
        {
          number: 27,
          title: { ko: "F2", en: "F2" },
          location: { ko: "아시타바 공원 리어카 옆", en: "Beside the handcart in Ashitaba Park" },
          reward: { ko: "은 접시", en: "Silver Plate" },
        },
        {
          number: 28,
          title: { ko: "F3", en: "F3" },
          location: { ko: "소텐보리 거리 서쪽 캬바레 앞 끝", en: "Edge in front of the West Sotenbori cabaret" },
          reward: { ko: "조장의 드라이버", en: "Boss's Driver" },
        },
        {
          number: 29,
          title: { ko: "F4", en: "F4" },
          location: { ko: "쇼후쿠초 서쪽 모퉁이 주차장 3번", en: "Spot 3 of the corner lot, West Shofukucho" },
          reward: { ko: "강철 갑주", en: "Steel Chainmail" },
        },
        {
          number: 30,
          title: { ko: "F5", en: "F5" },
          location: { ko: "다이나스티아 연예사무소 2층 로커룸 긴 의자 아래", en: "Under the 2F locker-room bench, talent agency" },
          reward: { ko: "아오다모 나무 조각", en: "Aodamo Wood Chip" },
        },
        {
          number: 31,
          title: { ko: "G1", en: "G1" },
          location: { ko: "소텐보리 측도 사각 우산 파이프 부분을 주시", en: "Look at the pipe of the square umbrella, Sotenbori Path" },
          reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
        },
        {
          number: 32,
          title: { ko: "G2", en: "G2" },
          location: { ko: "아키야마 편 선라이즈 점내 카운터 옆 자판기 앞", en: "By the counter vending machine in Sunrise (Akiyama chapter)" },
          reward: { ko: "칠흑 재킷", en: "Jet-Black Jacket" },
        },
        {
          number: 33,
          title: { ko: "G3", en: "G3" },
          location: { ko: "소텐보리 거리 서쪽 빌딩 공사장 끝 파이프를 옆에서 주시", en: "Look from the side at the pipe at the West Sotenbori construction edge" },
          reward: { ko: "고확 메달", en: "High-Chance Medal" },
        },
        {
          number: 34,
          title: { ko: "G4", en: "G4" },
          location: { ko: "다이나스티아 연예사무소 4층 계단 통풍구를 주시", en: "Look at the 4F stair vent, talent agency" },
          reward: { ko: "코테 블레이드", en: "Kote Blade" },
        },
        {
          number: 35,
          title: { ko: "G5", en: "G5" },
          location: { ko: "쇼후쿠초 서쪽에서 호겐지 요코초로 가는 골목 전봇대를 주시", en: "Look at the pole in the alley from West Shofukucho to Hogenji" },
          reward: { ko: "고확 메달", en: "High-Chance Medal" },
        },
        {
          number: 36,
          title: { ko: "H1", en: "H1" },
          location: { ko: "BAR 스테일 점내 1인용 소파 위", en: "On the single sofa inside BAR Stail" },
          reward: { ko: "은 접시", en: "Silver Plate" },
        },
        {
          number: 37,
          title: { ko: "H2", en: "H2" },
          location: { ko: "에비스야 점내 카운터 앞 통로", en: "Passage before the Ebisuya counter" },
          reward: { ko: "고확 메달", en: "High-Chance Medal" },
        },
        {
          number: 38,
          title: { ko: "H3", en: "H3" },
          location: { ko: "소텐보리 거리 서쪽 입구 옆", en: "Beside the West Sotenbori St entrance" },
          reward: { ko: "초고반발 수지", en: "Ultra-Rebound Resin" },
        },
        {
          number: 39,
          title: { ko: "H4", en: "H4" },
          location: { ko: "클럽 세가 간판을 주시", en: "Look at the Club SEGA sign" },
          reward: { ko: "항복 말", en: "Surrender Piece" },
        },
        {
          number: 40,
          title: { ko: "H5", en: "H5" },
          location: { ko: "아시타바 공원 긴 의자 아래", en: "Under the Ashitaba Park bench" },
          reward: { ko: "포켓 티슈", en: "Pocket Tissue" },
        },
        {
          number: 41,
          title: { ko: "I1", en: "I1" },
          location: { ko: "소텐보리 거리 서쪽 택시 앞 둥근 의자를 주시", en: "Look at the round stool in front of the West Sotenbori taxi" },
          reward: { ko: "은 접시", en: "Silver Plate" },
        },
        {
          number: 42,
          title: { ko: "I2", en: "I2" },
          location: { ko: "쇼후쿠초 남쪽 가라오케관 옆 노상", en: "Roadside beside Karaoke-kan, south Shofukucho" },
          reward: { ko: "강철 톤파", en: "Steel Tonfa" },
        },
        {
          number: 43,
          title: { ko: "I3", en: "I3" },
          location: { ko: "소텐보리 거리 동쪽 긴 의자 아래", en: "Under the East Sotenbori St bench" },
          reward: { ko: "스턴건", en: "Stun Gun" },
        },
        {
          number: 44,
          title: { ko: "I4", en: "I4" },
          location: { ko: "다이나스티아 연예사무소 빌딩 뒷골목", en: "Back alley of the talent-agency building" },
          reward: { ko: "고확석", en: "High-Chance Stone" },
        },
        {
          number: 45,
          title: { ko: "I5", en: "I5" },
          location: { ko: "하루카의 아파트 2층 통로 끝", en: "End of the 2F hall of Haruka's apartment" },
          reward: { ko: "하이퍼 우콘", en: "Hyper Ukon" },
        },
        {
          number: 46,
          title: { ko: "J1", en: "J1" },
          location: { ko: "소텐보리 거리 동쪽 노면", en: "East Sotenbori St road" },
          reward: { ko: "짜고치기 패", en: "Loaded Tile" },
        },
        {
          number: 47,
          title: { ko: "J2", en: "J2" },
          location: { ko: "분자에몬스지 오코노미야키 노점 위를 주시", en: "Look above the okonomiyaki stall, Bunzaemon St" },
          reward: { ko: "기 흡수 장갑", en: "Ki-Drain Glove" },
        },
        {
          number: 48,
          title: { ko: "J3", en: "J3" },
          location: { ko: "분자에몬스지 우편함 위를 주시", en: "Look atop the mailbox, Bunzaemon St" },
          reward: { ko: "버스트의 부적", en: "Burst Charm" },
        },
        {
          number: 49,
          title: { ko: "J4", en: "J4" },
          location: { ko: "클럽 세가 앞 긴 의자 근처", en: "Near the bench in front of Club SEGA" },
          reward: { ko: "무의 보석", en: "Void Gem" },
        },
        {
          number: 50,
          title: { ko: "J5", en: "J5" },
          location: { ko: "호겐지 요코초 대나무 벽을 주시", en: "Look at the bamboo wall, Hogenji Alley" },
          reward: { ko: "오토 메달", en: "Auto Medal" },
        },
          ],
        },
      ],
    },
  ],
};
