import type { CollectiblesData } from "./types";

export const yakuza4: CollectiblesData = {
  appId: 1105500,
  categories: [
    {
      slug: "hostess-cards",
      title: { ko: "명함 헌터 — 캬바걸 명함 풀 컴플리트", en: "Card Hunter — Every Hostess Card" },
      summary: {
        ko: "캬바레 클럽 + 「No.1 캬바걸을 만들자」 호스티스 메이커 트레이닝 호스티스까지 포함해 자유 입장으로 모든 명함을 입수하면 「명함 헌터」 업적 발동.",
        en: "Collect a business card from every hostess via free-entry visits — main cabarets + 'Make a #1 Hostess' trainees included. Unlocks 'Card Hunter'.",
      },
    },
    {
      slug: "lockers",
      title: { ko: "물품 보관함 — 100개 열쇠와 보상", en: "Coin Lockers — All 100 Keys & Rewards" },
      summary: {
        ko: "카무로초 지상 50개 + 지하·옥상 50개, 총 100개 물품 보관함 열쇠 위치와 보상을 정리했습니다. 5개만 열어도 「열쇠 마스터의 길」 업적이 풀립니다. 지도의 번호가 카드 번호와 일치합니다.",
        en: "All 100 coin-locker keys (50 surface + 50 underground/rooftop) with locations and rewards across Kamurocho. Opening just 5 unlocks 'Path of the Locker Master'. Map numbers match the card numbers.",
      },
      tips: [
        { ko: "타이헤이 거리 보관함 앞 남자에게서 「열쇠 워처」를 받으면 미니맵에 열쇠 위치가 표시됩니다. 2장부터 회수 가능합니다.", en: "Get the Key Watcher from the man by the Taihei St lockers to mark keys on the minimap. Available from Chapter 2." },
      ],
      source: { label: "龍が如く4攻略通信 — コインロッカーの鍵（マップ付き）", url: "https://kouryakutsushin.com/ryu4/locker.htm" },
      groups: [
      {
        title: { ko: "카무로초 지상 — 50개 열쇠", en: "Kamurocho Surface — 50 Keys" },
        mapImage: "https://kouryakutsushin.com/ryu4/img/key1.gif",
        items: [
      {
        number: 1,
        title: { ko: "A1", en: "A1" },
        location: { ko: "클럽 세가 나카미치 거리점 앞 노상", en: "Road in front of Club SEGA Nakamichi St" },
        reward: { ko: "너덜너덜한 머플러", en: "Tattered Muffler" },
      },
      {
        number: 2,
        title: { ko: "A2", en: "A2" },
        location: { ko: "아시아 점내 바닥", en: "Floor inside Asia" },
        reward: { ko: "강철 갑주", en: "Steel Chainmail" },
      },
      {
        number: 3,
        title: { ko: "A3", en: "A3" },
        location: { ko: "카무로 극장 소화전 위", en: "Atop the Kamuro Theater fire hydrant" },
        reward: { ko: "격신 나이프", en: "Spicy Knife" },
      },
      {
        number: 4,
        title: { ko: "A4", en: "A4" },
        location: { ko: "빔 점내 화분", en: "Planter inside Beam" },
        reward: { ko: "귀면석", en: "Oni-Face Stone" },
      },
      {
        number: 5,
        title: { ko: "A5", en: "A5" },
        location: { ko: "POPPO 쇼와 거리점 바닥", en: "Floor inside POPPO Showa St" },
        reward: { ko: "용의 눈동자", en: "Dragon's Eye" },
      },
      {
        number: 6,
        title: { ko: "B1", en: "B1" },
        location: { ko: "코인로커 입구 밖 벽 왼쪽 상부, 무단투기 금지 안내문 위", en: "Above the no-littering notice, upper-left wall outside the locker entrance" },
        reward: { ko: "하이퍼 스턴건", en: "Hyper Stun Gun" },
      },
      {
        number: 7,
        title: { ko: "B2", en: "B2" },
        location: { ko: "챔피언 거리 남서쪽 모서리", en: "Southwest corner of Champion District" },
        reward: { ko: "형상기억 스프링", en: "Shape-Memory Spring" },
      },
      {
        number: 8,
        title: { ko: "B3", en: "B3" },
        location: { ko: "나카미치 거리 뒤 에비스야 점내 바닥", en: "Floor inside Ebisuya, behind Nakamichi St" },
        reward: { ko: "진주", en: "Pearl" },
      },
      {
        number: 9,
        title: { ko: "B4", en: "B4" },
        location: { ko: "웍스 우에야마 조금 앞 배기관 위", en: "On the exhaust pipe just before Works Ueyama" },
        reward: { ko: "수수께끼의 휘석", en: "Mysterious Gem" },
      },
      {
        number: 10,
        title: { ko: "B5", en: "B5" },
        location: { ko: "POPPO 나카마치 거리 뒤점 뒷골목 파이프 위", en: "On the pipe in the back alley of POPPO Nakamachi" },
        reward: { ko: "수수께끼의 휘석", en: "Mysterious Gem" },
      },
      {
        number: 11,
        title: { ko: "C1", en: "C1" },
        location: { ko: "시치후쿠 거리 동쪽 칸라이 앞 노상", en: "Road in front of Kanrai, East Shichifuku St" },
        reward: { ko: "고대의 철강", en: "Ancient Steel" },
      },
      {
        number: 12,
        title: { ko: "C2", en: "C2" },
        location: { ko: "시치후쿠 거리 서쪽 M스토어 점내 바닥", en: "Floor inside M Store, West Shichifuku St" },
        reward: { ko: "고장난 라디오", en: "Broken Radio" },
      },
      {
        number: 13,
        title: { ko: "C3", en: "C3" },
        location: { ko: "밴텀 점내 스피커 위", en: "Atop the speaker inside Bantam" },
        reward: { ko: "BJ의 부적", en: "BJ Charm" },
      },
      {
        number: 14,
        title: { ko: "C4", en: "C4" },
        location: { ko: "인도 쓰레기 더미 앞", en: "In front of the trash pile on the sidewalk" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 15,
        title: { ko: "C5", en: "C5" },
        location: { ko: "타이헤이 거리 동쪽 고토부키 약국 점내 선반", en: "Shelf inside Kotobuki Pharmacy, East Taihei Blvd" },
        reward: { ko: "무의 보석", en: "Void Gem" },
      },
      {
        number: 16,
        title: { ko: "D1", en: "D1" },
        location: { ko: "클럽 세가 극장 앞점 뒤 자판기 위", en: "Atop the vending machine behind Club SEGA Theater" },
        reward: { ko: "핀조로의 패", en: "Pinzoro Tile" },
      },
      {
        number: 17,
        title: { ko: "D2", en: "D2" },
        location: { ko: "아시아 거리 북쪽 입구 정면 화장실", en: "Restroom facing the north entrance of Asia St" },
        reward: { ko: "터프니스 엠퍼러", en: "Toughness Emperor" },
      },
      {
        number: 18,
        title: { ko: "D3", en: "D3" },
        location: { ko: "아시아 거리 2층 통로", en: "2nd-floor passage of Asia St" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 19,
        title: { ko: "D4", en: "D4" },
        location: { ko: "나카미치 거리 입구 돈키호테 앞 자전거 바구니 안", en: "In the bicycle basket in front of Don Quijote" },
        reward: { ko: "피지매직 저지", en: "Fiji Magic Jersey" },
      },
      {
        number: 20,
        title: { ko: "D5", en: "D5" },
        location: { ko: "타이헤이 거리 동쪽 주차장", en: "Parking lot on East Taihei Blvd" },
        reward: { ko: "카리스마 링", en: "Charisma Ring" },
      },
      {
        number: 21,
        title: { ko: "E1", en: "E1" },
        location: { ko: "밀레니엄 타워 앞뜰 나뭇가지", en: "Tree branch in the Millennium Tower front garden" },
        reward: { ko: "숀벤 산맥의 돌", en: "Shonben Mountain Stone" },
      },
      {
        number: 22,
        title: { ko: "E2", en: "E2" },
        location: { ko: "천하일 거리 뉴 세레나 빌딩 앞 노상", en: "Road in front of the New Serena building, Tenkaichi St" },
        reward: { ko: "귀자모신의 부적", en: "Kishimojin Charm" },
      },
      {
        number: 23,
        title: { ko: "E3", en: "E3" },
        location: { ko: "뉴 세레나 점내 북쪽 조명", en: "North light fixture inside New Serena" },
        reward: { ko: "소형 모터", en: "Small Motor" },
      },
      {
        number: 24,
        title: { ko: "E4", en: "E4" },
        location: { ko: "쇼와 거리 서쪽 가장 서쪽 지하상가 입구 벽 위", en: "Above the westernmost underground-mall entrance, West Showa St" },
        reward: { ko: "중력 변환 장치?", en: "Gravity Converter?" },
      },
      {
        number: 25,
        title: { ko: "E5", en: "E5" },
        location: { ko: "아동 공원 나무 위", en: "Up the tree in the children's park" },
        reward: { ko: "전국 사슬갑주", en: "Sengoku Chainmail" },
      },
      {
        number: 26,
        title: { ko: "F1", en: "F1" },
        location: { ko: "뉴 세레나 뒤 자판기 벽 위", en: "Above the vending machine wall behind New Serena" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
      },
      {
        number: 27,
        title: { ko: "F2", en: "F2" },
        location: { ko: "제3공원 벤치 아래", en: "Under the bench in Third Park" },
        reward: { ko: "형상기억 스프링", en: "Shape-Memory Spring" },
      },
      {
        number: 28,
        title: { ko: "F3", en: "F3" },
        location: { ko: "나카미치 거리 뒤 록란소 바닥", en: "Floor of Rokuranso, behind Nakamichi St" },
        reward: { ko: "진주", en: "Pearl" },
      },
      {
        number: 29,
        title: { ko: "F4", en: "F4" },
        location: { ko: "핑크 거리 뒤 큐슈 이치반보시 점내 바닥", en: "Floor inside Kyushu Ichibanboshi, behind Pink St" },
        reward: { ko: "쾌적 솔", en: "Comfort Sole" },
      },
      {
        number: 30,
        title: { ko: "F5", en: "F5" },
        location: { ko: "밀레니엄 타워 북쪽 트리 꼭대기", en: "Top of the tree north of Millennium Tower" },
        reward: { ko: "수수께끼의 액체", en: "Mysterious Liquid" },
      },
      {
        number: 31,
        title: { ko: "G1", en: "G1" },
        location: { ko: "클럽 세가 나카미치 거리점 바닥", en: "Floor inside Club SEGA Nakamichi St" },
        reward: { ko: "로열 조커", en: "Royal Joker" },
      },
      {
        number: 32,
        title: { ko: "G2", en: "G2" },
        location: { ko: "천량 거리 간판 위 조명", en: "Light atop the Senryo Ave sign" },
        reward: { ko: "쵸고로의 염주", en: "Chogoro Beads" },
      },
      {
        number: 33,
        title: { ko: "G3", en: "G3" },
        location: { ko: "클럽 세가 나카미치 거리점 뒤 쓰레기통 안", en: "In the trash bin behind Club SEGA Nakamichi St" },
        reward: { ko: "카타요리사의 담배", en: "Katayori Cigarettes" },
      },
      {
        number: 34,
        title: { ko: "G4", en: "G4" },
        location: { ko: "나카미치 거리 킷사 알프스 점내", en: "Inside Cafe Alps, Nakamichi St" },
        reward: { ko: "붉은 보석", en: "Red Gem" },
      },
      {
        number: 35,
        title: { ko: "G5", en: "G5" },
        location: { ko: "챔피언 거리 북동쪽 슷톤쿄 처마 위", en: "Above the Suttonkyo eaves, NE Champion District" },
        reward: { ko: "고순도 플래티넘", en: "High-Purity Platinum" },
      },
      {
        number: 36,
        title: { ko: "H1", en: "H1" },
        location: { ko: "시치후쿠 거리 MEB 바닥", en: "Floor of MEB, Shichifuku St" },
        reward: { ko: "메이플 나무 조각", en: "Maple Wood Chip" },
      },
      {
        number: 37,
        title: { ko: "H2", en: "H2" },
        location: { ko: "슷폰 거리 카무로 라멘 앞 노상", en: "Road in front of Kamuro Ramen, Suppon St" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
      },
      {
        number: 38,
        title: { ko: "H3", en: "H3" },
        location: { ko: "마츠야 타이헤이 거리점 옆 주차장 정산기 지붕 위", en: "Atop the payment-machine roof beside Matsuya Taihei St" },
        reward: { ko: "어깨 패드", en: "Shoulder Pad" },
      },
      {
        number: 39,
        title: { ko: "H4", en: "H4" },
        location: { ko: "극장 앞 광장 영화 간판", en: "Movie billboard at Theater Square" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 40,
        title: { ko: "H5", en: "H5" },
        location: { ko: "아시아 거리 후루사토 뒤편 골목 배관 상부", en: "Upper piping in the alley behind Furusato, Asia St" },
        reward: { ko: "렌가의 청룡도", en: "Renge Blue-Dragon Blade" },
      },
      {
        number: 41,
        title: { ko: "I1", en: "I1" },
        location: { ko: "시치후쿠 파크 서쪽 밖 CENTURY 간판", en: "CENTURY sign west outside Shichifuku Park" },
        reward: { ko: "아오다모 나무 조각", en: "Aodamo Wood Chip" },
      },
      {
        number: 42,
        title: { ko: "I2", en: "I2" },
        location: { ko: "극장 앞 거리 볼케이노 쪽 자판기 앞", en: "In front of the vending machine on the Volcano side, Theater Ave" },
        reward: { ko: "합성 폴리머", en: "Synthetic Polymer" },
      },
      {
        number: 43,
        title: { ko: "I3", en: "I3" },
        location: { ko: "카무로 극장 에스컬레이터 옆 쿠로사와 간판 위", en: "Above the Kurosawa sign beside the Kamuro Theater escalator" },
        reward: { ko: "개조 라이터", en: "Modified Lighter" },
      },
      {
        number: 44,
        title: { ko: "I4", en: "I4" },
        location: { ko: "시치후쿠 거리 Jewl 옆 커피 남작 간판", en: "Coffee Baron sign next to Jewl, Shichifuku St" },
        reward: { ko: "카리스마의 사진", en: "Charisma Photo" },
      },
      {
        number: 45,
        title: { ko: "I5", en: "I5" },
        location: { ko: "극장 앞 거리 모바게 TOWN 간판 아래 처마 ※밤에는 제브라맨 간판", en: "Eaves under the Mobage TOWN sign (Zebraman sign at night), Theater Ave" },
        reward: { ko: "용의 인장", en: "Dragon Seal" },
      },
      {
        number: 46,
        title: { ko: "J1", en: "J1" },
        location: { ko: "핑크 거리 동쪽 카무로초 동쪽 옥상 오르막 입구 근처 쓰레기통 앞", en: "By the trash bin near the east-rooftop ramp, East Pink St" },
        reward: { ko: "히후미 껌", en: "Hifumi Gum" },
      },
      {
        number: 47,
        title: { ko: "J2", en: "J2" },
        location: { ko: "류구죠 도박장 계단 바닥", en: "Floor of the Ryugujo gambling den stairs" },
        reward: { ko: "거대 비닐 인형", en: "Giant Vinyl Doll" },
      },
      {
        number: 48,
        title: { ko: "J3", en: "J3" },
        location: { ko: "요시다 배팅센터 내 통풍구", en: "Vent inside Yoshida Batting Center" },
        reward: { ko: "고장난 라디오", en: "Broken Radio" },
      },
      {
        number: 49,
        title: { ko: "J4", en: "J4" },
        location: { ko: "마하 볼 점내 정면 안쪽 금색 핀", en: "Golden pin at the back of Mach Bowl" },
        reward: { ko: "루비", en: "Ruby" },
      },
      {
        number: 50,
        title: { ko: "J5", en: "J5" },
        location: { ko: "호텔가 호텔 Volescia 앞 전봇대 위", en: "Atop the utility pole in front of Hotel Volescia" },
        reward: { ko: "아라시의 양갱", en: "Arashi's Yokan" },
      },
        ],
      },
      {
        title: { ko: "카무로초 지하·옥상 — 50개 열쇠", en: "Kamurocho Underground & Rooftop — 50 Keys" },
        mapImage: "https://kouryakutsushin.com/ryu4/img/key2.gif",
        items: [
      {
        number: 1,
        title: { ko: "A1", en: "A1" },
        location: { ko: "카무로 지하상가 동쪽 카무로 중앙 주차장 입구 앞", en: "Karaoke underground mall, east — in front of Kamuro Central Parking entrance" },
        reward: { ko: "형상기억 스프링", en: "Shape-Memory Spring" },
      },
      {
        number: 2,
        title: { ko: "A2", en: "A2" },
        location: { ko: "카무로초 동쪽 옥상 배전반 위", en: "East rooftop — atop the distribution board" },
        reward: { ko: "합성 폴리머", en: "Synthetic Polymer" },
      },
      {
        number: 3,
        title: { ko: "A3", en: "A3" },
        location: { ko: "카무로 극장 출구 계단 아래 바닥", en: "Kamuro Theater — floor below the exit stairs" },
        reward: { ko: "호피 가죽 벨트", en: "Tiger-Hide Belt" },
      },
      {
        number: 4,
        title: { ko: "A4", en: "A4" },
        location: { ko: "카무로초 동쪽 옥상 저수 탱크 쪽 울타리 아래", en: "East rooftop — under the railing by the water tank" },
        reward: { ko: "고장난 라디오", en: "Broken Radio" },
      },
      {
        number: 5,
        title: { ko: "A5", en: "A5" },
        location: { ko: "중앙 하수도 중앙 다리 조명 아래", en: "Central sewer — under the central bridge light" },
        reward: { ko: "휘두르기 부적", en: "Swing Charm" },
      },
      {
        number: 6,
        title: { ko: "B1", en: "B1" },
        location: { ko: "카무로초 서쪽 옥상 사이고의 수련장 바닥", en: "West rooftop — floor of Saejima's training spot" },
        reward: { ko: "스태미난 로열", en: "Staminan Royal" },
      },
      {
        number: 7,
        title: { ko: "B2", en: "B2" },
        location: { ko: "카무로 중앙 주차장 208블록 부근 바닥", en: "Central Parking — floor near block 208" },
        reward: { ko: "로열 조커", en: "Royal Joker" },
      },
      {
        number: 8,
        title: { ko: "B3", en: "B3" },
        location: { ko: "극장 지하 B1 서브스토리 「고양이와 노숙자」에서 입수", en: "Theater B1 — from substory \"The Cat and the Homeless Man\"" },
        reward: { ko: "5만 엔", en: "¥50,000" },
      },
      {
        number: 9,
        title: { ko: "B4", en: "B4" },
        location: { ko: "카무로 중앙 주차장 북서쪽 남자 화장실 안", en: "Central Parking — inside the NW men's restroom" },
        reward: { ko: "대자성 금속 조각", en: "Magnetized Metal Shard" },
      },
      {
        number: 10,
        title: { ko: "B5", en: "B5" },
        location: { ko: "극장 지하 B1 에스컬레이터 위 나무상자 위", en: "Theater B1 — atop the crate above the escalator" },
        reward: { ko: "핏물 든 천", en: "Bloodstained Cloth" },
      },
      {
        number: 11,
        title: { ko: "C1", en: "C1" },
        location: { ko: "카무로 중앙 주차장 102 기둥 부근 바닥", en: "Central Parking — floor near pillar 102" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
      },
      {
        number: 12,
        title: { ko: "C2", en: "C2" },
        location: { ko: "카무로 지하상가 나카미치 거리 방면 출구 앞 바닥", en: "Underground mall — floor by the Nakamichi St exit" },
        reward: { ko: "강철 레가스", en: "Steel Greaves" },
      },
      {
        number: 13,
        title: { ko: "C3", en: "C3" },
        location: { ko: "카무로초 서쪽 옥상 사이고 수련장 앞 LoveBrace 간판", en: "West rooftop — LoveBrace sign in front of Saejima's spot" },
        reward: { ko: "포켓 티슈", en: "Pocket Tissue" },
      },
      {
        number: 14,
        title: { ko: "C4", en: "C4" },
        location: { ko: "카무로 중앙 주차장 북서쪽 요금소 안", en: "Central Parking — inside the NW toll booth" },
        reward: { ko: "중력 변환 장치?", en: "Gravity Converter?" },
      },
      {
        number: 15,
        title: { ko: "C5", en: "C5" },
        location: { ko: "카무로초 서쪽 옥상 분수 광장 계단 아래", en: "West rooftop — below the stairs to the fountain plaza" },
        reward: { ko: "WAT 사양 아머", en: "WAT-Spec Armor" },
      },
      {
        number: 16,
        title: { ko: "D1", en: "D1" },
        location: { ko: "카무로초 동쪽 옥상 핑크 거리 뒤에서 올라가 오른쪽 녹색 바닥", en: "East rooftop — green floor right after climbing from behind Pink St" },
        reward: { ko: "고대의 철강", en: "Ancient Steel" },
      },
      {
        number: 17,
        title: { ko: "D2", en: "D2" },
        location: { ko: "중앙 하수도 남쪽 하수 안", en: "Central sewer — in the south sewage" },
        reward: { ko: "고대의 철강", en: "Ancient Steel" },
      },
      {
        number: 18,
        title: { ko: "D3", en: "D3" },
        location: { ko: "카무로초 서쪽 옥상 분수 하단 물속", en: "West rooftop — in the water at the lower fountain" },
        reward: { ko: "사우스포 브레스", en: "Southpaw Bless" },
      },
      {
        number: 19,
        title: { ko: "D4", en: "D4" },
        location: { ko: "카무로 지하상가 CuezBAR 점내 당구대 아래", en: "Underground mall — under the CuezBAR pool table" },
        reward: { ko: "숀벤 산맥의 돌", en: "Shonben Mountain Stone" },
      },
      {
        number: 20,
        title: { ko: "D5", en: "D5" },
        location: { ko: "카무로초 동쪽 옥상 DMM 간판 앞 난간", en: "East rooftop — railing in front of the DMM sign" },
        reward: { ko: "진주", en: "Pearl" },
      },
      {
        number: 21,
        title: { ko: "E1", en: "E1" },
        location: { ko: "극장 지하 B1 IF7 방 입구 앞 바닥", en: "Theater B1 — floor at the IF7 room entrance" },
        reward: { ko: "버스트의 부적", en: "Burst Charm" },
      },
      {
        number: 22,
        title: { ko: "E2", en: "E2" },
        location: { ko: "카무로 중앙 주차장 천량 거리 출구 안내 근처 천장 배관 위 붉은 사각 부분", en: "Central Parking — atop the ceiling pipe (red square) near the Senryo exit sign" },
        reward: { ko: "카타요리사의 담배", en: "Katayori Cigarettes" },
      },
      {
        number: 23,
        title: { ko: "E3", en: "E3" },
        location: { ko: "카무로초 서쪽 옥상 니코니코 동화 간판 위", en: "West rooftop — atop the Niconico sign" },
        reward: { ko: "붉은 보석", en: "Red Gem" },
      },
      {
        number: 24,
        title: { ko: "E4", en: "E4" },
        location: { ko: "중앙 하수도 중앙 다리 북쪽 배관 위", en: "Central sewer — atop the pipe north of the central bridge" },
        reward: { ko: "히후미 껌", en: "Hifumi Gum" },
      },
      {
        number: 25,
        title: { ko: "E5", en: "E5" },
        location: { ko: "카무로초 동쪽 옥상 문 처마 위", en: "East rooftop — above the door eaves" },
        reward: { ko: "티타늄 드라이버", en: "Titanium Driver" },
      },
      {
        number: 26,
        title: { ko: "F1", en: "F1" },
        location: { ko: "카무로초 서쪽 옥상 급수 탱크 받침대 위", en: "West rooftop — atop the water-tank pedestal" },
        reward: { ko: "모노그램 백", en: "Monogram Bag" },
      },
      {
        number: 27,
        title: { ko: "F2", en: "F2" },
        location: { ko: "극장 지하 B2 중앙 북쪽 막다른 곳 바닥", en: "Theater B2 — floor at the central-north dead end" },
        reward: { ko: "핏물 든 사라시", en: "Bloodstained Sarashi" },
      },
      {
        number: 28,
        title: { ko: "F3", en: "F3" },
        location: { ko: "극장 지하 B1 남쪽 자판기 위", en: "Theater B1 — atop the south vending machine" },
        reward: { ko: "BJ의 부적", en: "BJ Charm" },
      },
      {
        number: 29,
        title: { ko: "F4", en: "F4" },
        location: { ko: "카무로초 동쪽 옥상 화분 앞", en: "East rooftop — in front of the planter" },
        reward: { ko: "앉아 한 방 패", en: "Sit-Down One-Shot Tile" },
      },
      {
        number: 30,
        title: { ko: "F5", en: "F5" },
        location: { ko: "카무로초 동쪽 옥상 건축 현장 발판", en: "East rooftop — on the construction scaffolding" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
      },
      {
        number: 31,
        title: { ko: "G1", en: "G1" },
        location: { ko: "카무로 중앙 주차장 111 기둥 옆 남색 왜건 아래", en: "Central Parking — under the navy wagon beside pillar 111" },
        reward: { ko: "금속 배트", en: "Metal Bat" },
      },
      {
        number: 32,
        title: { ko: "G2", en: "G2" },
        location: { ko: "중앙 하수도 북동 통로 쓰레기봉투 앞 바닥", en: "Central sewer — floor by the trash bags, NE passage" },
        reward: { ko: "대자성 금속 조각", en: "Magnetized Metal Shard" },
      },
      {
        number: 33,
        title: { ko: "G3", en: "G3" },
        location: { ko: "사이노카와라 지하 후쿠마덴 앞 기둥 부근 바닥", en: "Sai no Kawara underground — floor near the pillar before Fukumaden" },
        reward: { ko: "소형 모터", en: "Small Motor" },
      },
      {
        number: 34,
        title: { ko: "G4", en: "G4" },
        location: { ko: "중앙 하수도 센닌이 있는 곳 바닥", en: "Central sewer — floor where the Sennin is" },
        reward: { ko: "금 접시", en: "Gold Plate" },
      },
      {
        number: 35,
        title: { ko: "G5", en: "G5" },
        location: { ko: "카무로초 서쪽 옥상 건물을 잇는 다리 아래로 보이는 C-WORLD 파란 간판 위 (매우 보기 어려움)", en: "West rooftop — atop the blue C-WORLD sign under the connecting bridge (very hard to spot)" },
        reward: { ko: "수수께끼의 액체", en: "Mysterious Liquid" },
      },
      {
        number: 36,
        title: { ko: "H1", en: "H1" },
        location: { ko: "카무로초 서쪽 옥상 바닥", en: "West rooftop — floor" },
        reward: { ko: "BLUE-FOX", en: "BLUE-FOX" },
      },
      {
        number: 37,
        title: { ko: "H2", en: "H2" },
        location: { ko: "카무로초 서쪽 옥상 바닥", en: "West rooftop — floor" },
        reward: { ko: "부적", en: "Charm" },
      },
      {
        number: 38,
        title: { ko: "H3", en: "H3" },
        location: { ko: "카무로 중앙 주차장 중앙 통로 바닥", en: "Central Parking — central passage floor" },
        reward: { ko: "건틀릿", en: "Gauntlet" },
      },
      {
        number: 39,
        title: { ko: "H4", en: "H4" },
        location: { ko: "북쪽 하수도 선글라스 낀 노숙자 머리 위 배관 위", en: "North sewer — atop the pipe above the sunglasses homeless man" },
        reward: { ko: "초고반발 수지", en: "Ultra-Rebound Resin" },
      },
      {
        number: 40,
        title: { ko: "H5", en: "H5" },
        location: { ko: "극장 지하 B3 변전실 형광등 위", en: "Theater B3 substation — atop the fluorescent light" },
        reward: { ko: "티타늄 코어 볼", en: "Titanium Core Ball" },
      },
      {
        number: 41,
        title: { ko: "I1", en: "I1" },
        location: { ko: "카무로초 동쪽 옥상 나카미치 거리 뒤 계단 옆 실외기 앞 바닥", en: "East rooftop — floor by the AC unit beside the Nakamichi-back stairs" },
        reward: { ko: "검은 보석", en: "Black Gem" },
      },
      {
        number: 42,
        title: { ko: "I2", en: "I2" },
        location: { ko: "카무로초 동쪽 옥상 무기점 남쪽 계단 아래 근처 바닥", en: "East rooftop — floor near the bottom of the stairs south of the weapon shop" },
        reward: { ko: "대자성 금속 조각", en: "Magnetized Metal Shard" },
      },
      {
        number: 43,
        title: { ko: "I3", en: "I3" },
        location: { ko: "극장 지하 B3 변전실 농구 골대", en: "Theater B3 substation — basketball hoop" },
        reward: { ko: "아이언", en: "Iron" },
      },
      {
        number: 44,
        title: { ko: "I4", en: "I4" },
        location: { ko: "카무로초 서쪽 옥상 붉은 간판 뒤편 하부", en: "West rooftop — lower back of the red sign" },
        reward: { ko: "소형 모터", en: "Small Motor" },
      },
      {
        number: 45,
        title: { ko: "I5", en: "I5" },
        location: { ko: "카무로초 서쪽 옥상 녹슨 계단 아래", en: "West rooftop — below the rusted stairs" },
        reward: { ko: "고확석", en: "High-Chance Stone" },
      },
      {
        number: 46,
        title: { ko: "J1", en: "J1" },
        location: { ko: "카무로 극장 통로(셔터 앞)", en: "Kamuro Theater — passage (in front of the shutter)" },
        reward: { ko: "RED-SHARK", en: "RED-SHARK" },
      },
      {
        number: 47,
        title: { ko: "J2", en: "J2" },
        location: { ko: "북쪽 하수도 다리 아래", en: "North sewer — under the bridge" },
        reward: { ko: "중력 변환 장치?", en: "Gravity Converter?" },
      },
      {
        number: 48,
        title: { ko: "J3", en: "J3" },
        location: { ko: "극장 지하 B1 부티크 키무라 앞 맥주 상자 안", en: "Theater B1 — in the beer crate in front of Boutique Kimura" },
        reward: { ko: "합성 폴리머", en: "Synthetic Polymer" },
      },
      {
        number: 49,
        title: { ko: "J4", en: "J4" },
        location: { ko: "카무로초 동쪽 옥상 나카미치 거리 계단 앞 실외기 위", en: "East rooftop — atop the AC unit before the Nakamichi St stairs" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
      },
      {
        number: 50,
        title: { ko: "J5", en: "J5" },
        location: { ko: "카무로초 동쪽 옥상 무기점 옆 통풍구 안", en: "East rooftop — in the vent beside the weapon shop" },
        reward: { ko: "다이아몬드", en: "Diamond" },
      },
        ],
      },
      ],
    }
  ],
};
