import type { CollectiblesData } from "./types";

export const yakuzaKiwami: CollectiblesData = {
  appId: 3717330,
  categories: [
    {
      slug: "trouble-missions",
      title: { ko: "트러블 미션 78종", en: "Trouble Missions" },
      summary: {
        ko: "거리 곳곳에서 발생하는 시민 구조·배달·호위 의뢰 78종을 모두 처리합니다. 같은 종류 반복보다 새로운 유형을 우선 챙겨야 컴플리트 리스트가 빠르게 채워집니다.",
        en: "Clear all 78 Trouble Missions across the city. Prioritize new mission types over repeats to fill the Completion List faster.",
      },
    },
    {
      slug: "majima-everywhere",
      title: { ko: "마지마 에브리웨어 — 4 스타일 + 매드 독", en: "Majima Everywhere — 4 Styles + Mad Dog" },
      summary: {
        ko: "거리에서 마지마와의 전투를 반복해 4가지 스타일(맨손 「치고받고 싸워 보까!」 / 단도 「내도 좀 즐겨 보자!」 / 배트 「풀 스윙 간데이!」 / 춤추는 「춤 안 추고 뭐 하노!」)을 모두 경험하고, 인연 랭크 B 이상에서 매드 독 마지마 전을 풀어 「도지마의 용이 부활한기라!」를 트리거합니다.",
        en: "Repeat random Majima encounters across town to log all four styles (Brawler 'Let's Fight!', Slugger 'Swing For the Fences!', Tantou 'Are Ya Havin' Fun Yet?', Breaker 'Break it Down!'). Reach Bond Rank B+ to face Mad Dog Majima for 'The Dragon of Dojima Returns!'",
      },
    },
    {
      slug: "mesuking",
      title: { ko: "메스킹 — 곤충 대왕 (모든 라이벌 우승)", en: "MesuKing — Throne of the Insect King" },
      summary: {
        ko: "코트 어드벤처에서 시작하는 메스킹 카드 배틀. 모든 라이벌과의 대결에서 우승하면 「곤충 대왕 탄생!」 업적이 트리거됩니다. 카드는 챕터 진행 + 서브스토리 보상으로 풀립니다.",
        en: "MesuKing card battler at the Children's Adventure. Beat every rival match to trigger 'Throne of the MesuKing!'. Cards unlock via story progress + substory rewards.",
      },
    },
    {
      slug: "komaki-training",
      title: { ko: "코마키류 수련 — 전수 완료", en: "Komaki Style — All Training Complete" },
      summary: {
        ko: "코마키 사부의 모든 수련을 완료해 「코마키류 전수 완료!」를 잠금 해제합니다. 「도지마의 용」 스타일 부활 흐름과 직접 연결됩니다.",
        en: "Complete every Komaki training session to unlock 'Komaki Style Master'. Directly feeds the Dragon of Dojima style revival arc.",
      },
    },
  {
    slug: "pocket-circuit",
    title: { ko: "포켓 서킷 — 파츠 119종 + 우승 보상", en: "Pocket Circuit — All 119 Parts & Tournament Rewards" },
    summary: { ko: "시치후쿠 거리 서쪽 포켓 서킷 스타디움에서 모든 파츠를 모으고 그랑프리에서 1위를 차지합니다. 챕터 4 이후 자유 진행 가능합니다. 일부 파츠는 에비스야 전당포, 볼링 스플릿, 코인로커, 타쿠마군 이벤트 등에서만 얻을 수 있습니다.", en: "Collect every Pocket Circuit part and win the Grand Prix at the Shichifuku St. West Pocket Circuit Stadium. Free play unlocks in Chapter 4. Some parts come only from Ebisuya pawn shop, Bowling splits, Coin Lockers, and Takuma-kun events." },
    tips: [
        { ko: "대회 우승 보상은 파츠 상점 라인업을 늘립니다. 대회 1~13 순서대로 격파해 상위 모터·서스펜션을 해금하세요.", en: "Tournament wins unlock new parts shop stock. Beat tournaments 1-13 in order to access high-end motors and suspensions." },
        { ko: "마지마와의 1·2·3회차 레이스는 메인 스토리 외부에서도 트리거 가능. 특수 스티커/파츠 보상이 있습니다.", en: "The 3 Majima races trigger outside the main story too — they reward unique stickers and parts." },
    ],
    source: { label: "龍が如く極 最速攻略wiki — パーツ", url: "https://spwiki.net/ryukiwami/wikis/100.html" },
    groups: [
    {
      title: { ko: "스티커 — 7종", en: "Sticker — 7 parts" },
      items: [
      {
        number: 1,
        title: { ko: "센터 스트라이프", en: "Center Stripe" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 2,
        title: { ko: "사이드 스트라이프", en: "Side Stripe" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 3,
        title: { ko: "와일드 스네이크", en: "Wild Snake" },
        location: { ko: "마지마와의 3회차 레이스 승리", en: "Win Race 3 vs. Majima" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 7,
        title: { ko: "파이어 레드", en: "Fire Red" },
        location: { ko: "초기", en: "Initial" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 8,
        title: { ko: "아쿠아 블루", en: "Aqua Blue" },
        location: { ko: "에비스야 (전당포)", en: "Ebisuya (pawn shop)" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 9,
        title: { ko: "써니 옐로우", en: "Sunny Yellow" },
        location: { ko: "볼링 스플릿 (3프레임)", en: "Bowling Split (Frame 3)" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 10,
        title: { ko: "다크 퍼플", en: "Dark Purple" },
        location: { ko: "에비스야 (전당포)", en: "Ebisuya (pawn shop)" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      ],
    },
    {
      title: { ko: "프론트 — 2종", en: "Front — 2 parts" },
      items: [
      {
        number: 4,
        title: { ko: "뉴 범퍼 플레이트", en: "New Bumper Plate" },
        location: { ko: "에비스야 (전당포)", en: "Ebisuya (pawn shop)" },
        reward: { ko: "코스트 6", en: "Cost 6" },
      },
      {
        number: 41,
        title: { ko: "범퍼 플레이트", en: "Bumper Plate" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      ],
    },
    {
      title: { ko: "모터 — 21종", en: "Motor — 21 parts" },
      items: [
      {
        number: 5,
        title: { ko: "극·하이 토크 모터", en: "Kiwami Hi-Torque Motor" },
        location: { ko: "파츠샵 — 대회 13 우승", en: "Parts Shop — Tournament 13 Win" },
        reward: { ko: "코스트 7", en: "Cost 7" },
      },
      {
        number: 6,
        title: { ko: "극·이다텐 모터", en: "Kiwami Idaten Motor" },
        location: { ko: "파츠샵 — 대회 13 우승", en: "Parts Shop — Tournament 13 Win" },
        reward: { ko: "코스트 7", en: "Cost 7" },
      },
      {
        number: 42,
        title: { ko: "파워 모터", en: "Power Motor" },
        location: { ko: "초기", en: "Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 43,
        title: { ko: "슈퍼 파워 모터", en: "Super Power Motor" },
        location: { ko: "사이노카와라 무기점", en: "Sai no Kawara Weapon Shop" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 44,
        title: { ko: "하이퍼 파워 모터", en: "Hyper Power Motor" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 45,
        title: { ko: "울트라 파워 모터", en: "Ultra Power Motor" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 46,
        title: { ko: "극·파워 모터", en: "Kiwami Power Motor" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 47,
        title: { ko: "스피드 모터", en: "Speed Motor" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 48,
        title: { ko: "슈퍼 스피드 모터", en: "Super Speed Motor" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 49,
        title: { ko: "하이퍼 스피드 모터", en: "Hyper Speed Motor" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 50,
        title: { ko: "울트라 스피드 모터", en: "Ultra Speed Motor" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 51,
        title: { ko: "극·스피드 모터", en: "Kiwami Speed Motor" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 52,
        title: { ko: "미들 모터", en: "Middle Motor" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 53,
        title: { ko: "슈퍼 미들 모터", en: "Super Middle Motor" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 54,
        title: { ko: "하이퍼 미들 모터", en: "Hyper Middle Motor" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 55,
        title: { ko: "울트라 미들 모터", en: "Ultra Middle Motor" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 56,
        title: { ko: "극·미들 모터", en: "Kiwami Middle Motor" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 57,
        title: { ko: "하이 토크 모터", en: "Hi-Torque Motor" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 58,
        title: { ko: "하이 토크 모터 改", en: "Hi-Torque Motor Kai" },
        location: { ko: "빔 (전자제품점)", en: "Beam (electronics store)" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 59,
        title: { ko: "이다텐 모터", en: "Idaten Motor" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 60,
        title: { ko: "이다텐 모터 마크 II", en: "Idaten Motor Mark II" },
        location: { ko: "타쿠마군 이벤트 승리", en: "Win Takuma-kun Event" },
        reward: { ko: "코스트 6", en: "Cost 6" },
      },
      ],
    },
    {
      title: { ko: "머신 — 5종", en: "Machine — 5 parts" },
      items: [
      {
        number: 11,
        title: { ko: "DRA-GON", en: "DRA-GON" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 12,
        title: { ko: "골렘 타이거", en: "Golem Tiger" },
        location: { ko: "초기", en: "Initial" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 13,
        title: { ko: "쿨 스트라이커", en: "Cool Striker" },
        location: { ko: "코인로커 E5", en: "Coin Locker E5" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 14,
        title: { ko: "데빌 킬러", en: "Devil Killer" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      {
        number: 15,
        title: { ko: "DON-벌", en: "DON-Bee" },
        location: { ko: "DLC (2016/3/3)", en: "DLC (2016/3/3)" },
        reward: { ko: "코스트 −", en: "Cost −" },
      },
      ],
    },
    {
      title: { ko: "핀 — 25종", en: "Fin — 25 parts" },
      items: [
      {
        number: 16,
        title: { ko: "미들 핀", en: "Middle Fin" },
        location: { ko: "초기", en: "Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 17,
        title: { ko: "슈퍼 미들 핀", en: "Super Middle Fin" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 18,
        title: { ko: "하이퍼 미들 핀", en: "Hyper Middle Fin" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 19,
        title: { ko: "울트라 미들 핀", en: "Ultra Middle Fin" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 20,
        title: { ko: "극·미들 핀", en: "Kiwami Middle Fin" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 21,
        title: { ko: "메탈 핀", en: "Metal Fin" },
        location: { ko: "코인로커 J2", en: "Coin Locker J2" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 22,
        title: { ko: "슈퍼 메탈 핀", en: "Super Metal Fin" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 23,
        title: { ko: "하이퍼 메탈 핀", en: "Hyper Metal Fin" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 24,
        title: { ko: "울트라 메탈 핀", en: "Ultra Metal Fin" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 25,
        title: { ko: "극·메탈 핀", en: "Kiwami Metal Fin" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 26,
        title: { ko: "퀵 핀", en: "Quick Fin" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 27,
        title: { ko: "슈퍼 퀵 핀", en: "Super Quick Fin" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 28,
        title: { ko: "하이퍼 퀵 핀", en: "Hyper Quick Fin" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 29,
        title: { ko: "울트라 퀵 핀", en: "Ultra Quick Fin" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 30,
        title: { ko: "극·퀵 핀", en: "Kiwami Quick Fin" },
        location: { ko: "에비스야 (전당포)", en: "Ebisuya (pawn shop)" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 31,
        title: { ko: "러버 핀", en: "Rubber Fin" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 32,
        title: { ko: "슈퍼 러버 핀", en: "Super Rubber Fin" },
        location: { ko: "에비스야 (전당포)", en: "Ebisuya (pawn shop)" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 33,
        title: { ko: "하이퍼 러버 핀", en: "Hyper Rubber Fin" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 34,
        title: { ko: "울트라 러버 핀", en: "Ultra Rubber Fin" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 35,
        title: { ko: "극·러버 핀", en: "Kiwami Rubber Fin" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 36,
        title: { ko: "스피드 핀", en: "Speed Fin" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 37,
        title: { ko: "슈퍼 스피드 핀", en: "Super Speed Fin" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 38,
        title: { ko: "하이퍼 스피드 핀", en: "Hyper Speed Fin" },
        location: { ko: "볼링 스플릿 (5프레임)", en: "Bowling Split (Frame 5)" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 39,
        title: { ko: "울트라 스피드 핀", en: "Ultra Speed Fin" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 40,
        title: { ko: "극·스피드 핀", en: "Kiwami Speed Fin" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      ],
    },
    {
      title: { ko: "타이어 — 25종", en: "Tire — 25 parts" },
      items: [
      {
        number: 61,
        title: { ko: "슬릭 타이어", en: "Slick Tire" },
        location: { ko: "초기", en: "Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 62,
        title: { ko: "슈퍼 슬릭 타이어", en: "Super Slick Tire" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 63,
        title: { ko: "하이퍼 슬릭 타이어", en: "Hyper Slick Tire" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 64,
        title: { ko: "울트라 슬릭 타이어", en: "Ultra Slick Tire" },
        location: { ko: "사이노카와라 무기점", en: "Sai no Kawara Weapon Shop" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 65,
        title: { ko: "극·슬릭 타이어", en: "Kiwami Slick Tire" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 66,
        title: { ko: "스펀지 타이어", en: "Sponge Tire" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 67,
        title: { ko: "슈퍼 스펀지 타이어", en: "Super Sponge Tire" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 68,
        title: { ko: "하이퍼 스펀지 타이어", en: "Hyper Sponge Tire" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 69,
        title: { ko: "울트라 스펀지 타이어", en: "Ultra Sponge Tire" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 70,
        title: { ko: "극·울트라 스펀지 타이어", en: "Kiwami Ultra Sponge Tire" },
        location: { ko: "볼링 스플릿 (7프레임)", en: "Bowling Split (Frame 7)" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 71,
        title: { ko: "스파이크 타이어", en: "Spike Tire" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 72,
        title: { ko: "슈퍼 스파이크 타이어", en: "Super Spike Tire" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 73,
        title: { ko: "하이퍼 스파이크 타이어", en: "Hyper Spike Tire" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 74,
        title: { ko: "울트라 스파이크 타이어", en: "Ultra Spike Tire" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 75,
        title: { ko: "극·스파이크 타이어", en: "Kiwami Spike Tire" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 76,
        title: { ko: "로우 하이트 타이어", en: "Low-Height Tire" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 77,
        title: { ko: "슈퍼 로우 하이트 타이어", en: "Super Low-Height Tire" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 78,
        title: { ko: "하이퍼 로우 하이트 타이어", en: "Hyper Low-Height Tire" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 79,
        title: { ko: "울트라 로우 하이트 타이어", en: "Ultra Low-Height Tire" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 80,
        title: { ko: "극·로우 하이트 타이어", en: "Kiwami Low-Height Tire" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 81,
        title: { ko: "배럴 타이어", en: "Barrel Tire" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 82,
        title: { ko: "슈퍼 배럴 타이어", en: "Super Barrel Tire" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 83,
        title: { ko: "하이퍼 배럴 타이어", en: "Hyper Barrel Tire" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 84,
        title: { ko: "울트라 배럴 타이어", en: "Ultra Barrel Tire" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 85,
        title: { ko: "극·배럴 타이어", en: "Kiwami Barrel Tire" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      ],
    },
    {
      title: { ko: "기어 — 25종", en: "Gear — 25 parts" },
      items: [
      {
        number: 86,
        title: { ko: "파워 기어", en: "Power Gear" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 87,
        title: { ko: "슈퍼 파워 기어", en: "Super Power Gear" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 88,
        title: { ko: "하이퍼 파워 기어", en: "Hyper Power Gear" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 89,
        title: { ko: "울트라 파워 기어", en: "Ultra Power Gear" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 90,
        title: { ko: "극·파워 기어", en: "Kiwami Power Gear" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 91,
        title: { ko: "중속 기어", en: "Mid-Speed Gear" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 92,
        title: { ko: "슈퍼 중속 기어", en: "Super Mid-Speed Gear" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 93,
        title: { ko: "하이퍼 중속 기어", en: "Hyper Mid-Speed Gear" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 94,
        title: { ko: "울트라 중속 기어", en: "Ultra Mid-Speed Gear" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 95,
        title: { ko: "극·중속 기어", en: "Kiwami Mid-Speed Gear" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 96,
        title: { ko: "노멀 기어", en: "Normal Gear" },
        location: { ko: "초기", en: "Initial" },
        reward: { ko: "코스트 1", en: "Cost 1" },
      },
      {
        number: 97,
        title: { ko: "슈퍼 노멀 기어", en: "Super Normal Gear" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 2", en: "Cost 2" },
      },
      {
        number: 98,
        title: { ko: "하이퍼 노멀 기어", en: "Hyper Normal Gear" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 99,
        title: { ko: "울트라 노멀 기어", en: "Ultra Normal Gear" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 100,
        title: { ko: "극·노멀 기어", en: "Kiwami Normal Gear" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 101,
        title: { ko: "대시 기어", en: "Dash Gear" },
        location: { ko: "빔 (전자제품점)", en: "Beam (electronics store)" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 102,
        title: { ko: "슈퍼 대시 기어", en: "Super Dash Gear" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 103,
        title: { ko: "하이퍼 대시 기어", en: "Hyper Dash Gear" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 104,
        title: { ko: "울트라 대시 기어", en: "Ultra Dash Gear" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 6", en: "Cost 6" },
      },
      {
        number: 105,
        title: { ko: "극·대시 기어", en: "Kiwami Dash Gear" },
        location: { ko: "파츠샵 — 대회 12 우승", en: "Parts Shop — Tournament 12 Win" },
        reward: { ko: "코스트 7", en: "Cost 7" },
      },
      {
        number: 106,
        title: { ko: "신속 기어", en: "Godspeed Gear" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 107,
        title: { ko: "슈퍼 신속 기어", en: "Super Godspeed Gear" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 108,
        title: { ko: "하이퍼 신속 기어", en: "Hyper Godspeed Gear" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 109,
        title: { ko: "울트라 신속 기어", en: "Ultra Godspeed Gear" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 6", en: "Cost 6" },
      },
      {
        number: 110,
        title: { ko: "극·신속 기어", en: "Kiwami Godspeed Gear" },
        location: { ko: "파츠샵 — 대회 12 우승", en: "Parts Shop — Tournament 12 Win" },
        reward: { ko: "코스트 7", en: "Cost 7" },
      },
      ],
    },
    {
      title: { ko: "배터리 — 3종", en: "Battery — 3 parts" },
      items: [
      {
        number: 111,
        title: { ko: "터프니스 배터리", en: "Toughness Battery" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 112,
        title: { ko: "고속 배터리", en: "High-Speed Battery" },
        location: { ko: "파츠샵 — 초기", en: "Parts Shop — Initial" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      {
        number: 113,
        title: { ko: "노멀 배터리", en: "Normal Battery" },
        location: { ko: "초기", en: "Initial" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      ],
    },
    {
      title: { ko: "사이드 파츠 — 3종", en: "Side Part — 3 parts" },
      items: [
      {
        number: 114,
        title: { ko: "사이드 스테이", en: "Side Stay" },
        location: { ko: "파츠샵 — 대회 4 우승", en: "Parts Shop — Tournament 4 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 115,
        title: { ko: "사이드 스테이 改", en: "Side Stay Kai" },
        location: { ko: "에비스야 (전당포)", en: "Ebisuya (pawn shop)" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 116,
        title: { ko: "사이드 스테이 改-II", en: "Side Stay Kai-II" },
        location: { ko: "파츠샵 — 대회 8 우승", en: "Parts Shop — Tournament 8 Win" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      ],
    },
    {
      title: { ko: "서스펜션 — 3종", en: "Suspension — 3 parts" },
      items: [
      {
        number: 117,
        title: { ko: "라이트 서스펜션", en: "Light Suspension" },
        location: { ko: "파츠샵 — 대회 1 우승", en: "Parts Shop — Tournament 1 Win" },
        reward: { ko: "코스트 3", en: "Cost 3" },
      },
      {
        number: 118,
        title: { ko: "미들 서스펜션", en: "Middle Suspension" },
        location: { ko: "파츠샵 — 대회 6 우승", en: "Parts Shop — Tournament 6 Win" },
        reward: { ko: "코스트 4", en: "Cost 4" },
      },
      {
        number: 119,
        title: { ko: "헤비 서스펜션", en: "Heavy Suspension" },
        location: { ko: "에비스야 (전당포)", en: "Ebisuya (pawn shop)" },
        reward: { ko: "코스트 5", en: "Cost 5" },
      },
      ],
    },
    ],
  },
  ],
};
