import type { CollectiblesData } from "./types";

export const yakuza3: CollectiblesData = {
  appId: 1088710,
  categories: [
    {
      slug: "coin-lockers",
      title: { ko: "물품 보관함 — 양 도시 100개 열쇠와 보상", en: "Coin Lockers — All 100 Keys & Rewards (Both Cities)" },
      summary: {
        ko: "카무로초 50개 + 류큐 거리 50개, 도시 곳곳에 흩어진 물품 보관함 열쇠 100개의 위치와 보상을 정리했습니다. 누적 10개를 열면 「열쇠의 방랑자」 업적이 풀립니다.",
        en: "All 100 coin-locker keys (50 Kamurocho + 50 Ryukyu Street) with locations and rewards. Open 10 total to unlock 'Wanderer of Keys'.",
      },
      tips: [
        { ko: "「러브박스 입수」 표시가 있는 열쇠는 거리의 러브박스(반짝이는 상자)에서 회수합니다. 카드 번호는 game8 공략의 로커 ID와 일치합니다.", en: "Keys marked 'Love Box' come from the shining Love Boxes around town. Card IDs match the game8 locker IDs." },
      ],
      source: { label: "game8.jp — 龍が如く極3 コインロッカーの鍵の場所", url: "https://game8.jp/ryu-ga-gotoku-kiwami3/755828" },
      groups: [
      {
        title: { ko: "카무로초 — 50개 열쇠", en: "Kamurocho — 50 Keys" },
        items: [
      {
        number: 1,
        title: { ko: "A1 · 호텔가", en: "A1 · Hotel District" },
        location: { ko: "호텔가 중앙 건물 앞", en: "In front of the central building in Hotel District" },
        reward: { ko: "사운드트랙 CD「데이토나」", en: "Soundtrack CD \"Daytona\"" },
      },
      {
        number: 2,
        title: { ko: "A2 · 서공원", en: "A2 · West Park" },
        location: { ko: "서공원의 화장실", en: "West Park restroom" },
        reward: { ko: "특공복 안쪽 단추·극 ×2", en: "Tokko-fuku Inner Button (Kiwami) ×2" },
      },
      {
        number: 3,
        title: { ko: "A3 · 천하일 거리 뒤", en: "A3 · Behind Tenkaichi St" },
        location: { ko: "천하일 거리 뒤 북쪽 골목 북동", en: "Northeast of the north alley behind Tenkaichi St" },
        reward: { ko: "입체 스티커: 물방울(스카이블루)", en: "3D Sticker: Drop (Sky Blue)" },
      },
      {
        number: 4,
        title: { ko: "A4 · 타이헤이 거리 동쪽", en: "A4 · East Taihei Blvd" },
        location: { ko: "타이헤이 거리 동쪽 무료 안내소 안", en: "Inside the info center on East Taihei Blvd" },
        reward: { ko: "스타디움 점퍼", en: "Stadium Jacket" },
      },
      {
        number: 5,
        title: { ko: "A5 · 나카미치 거리", en: "A5 · Nakamichi St" },
        location: { ko: "러브박스 입수, 돈키호테 맞은편 건물 간판", en: "Love Box — sign of the building across from Don Quijote" },
        reward: { ko: "갑옷 ×1, 투구 ×1, 손목보호대 ×1", en: "Armor ×1, Helmet ×1, Gauntlet ×1" },
      },
      {
        number: 6,
        title: { ko: "B1 · 호텔가", en: "B1 · Hotel District" },
        location: { ko: "호텔가 서쪽 검은 차가 선 주차장 안", en: "Parking lot with the black car, west Hotel District" },
        reward: { ko: "CD「카무로 설월화」", en: "CD \"Kamuro Setsugekka\"" },
      },
      {
        number: 7,
        title: { ko: "B2 · 시치후쿠 거리 동쪽", en: "B2 · East Shichifuku St" },
        location: { ko: "시치후쿠 거리 동쪽 건물 엘리베이터 앞", en: "Elevator of the building on East Shichifuku St" },
        reward: { ko: "보디수트", en: "Bodysuit" },
      },
      {
        number: 8,
        title: { ko: "B3 · 천하일 거리", en: "B3 · Tenkaichi St" },
        location: { ko: "천하일 거리 미나미다가 간판 아래로 진행한 곳", en: "Past the Minamida-ke sign on Tenkaichi St" },
        reward: { ko: "반팔 와이셔츠(크로커다일)", en: "Short-Sleeve Shirt (Crocodile)" },
      },
      {
        number: 9,
        title: { ko: "B4 · 시치후쿠 거리 동쪽", en: "B4 · East Shichifuku St" },
        location: { ko: "시치후쿠 거리 동쪽 주차장", en: "Parking lot on East Shichifuku St" },
        reward: { ko: "쌀 ×3", en: "Rice ×3" },
      },
      {
        number: 10,
        title: { ko: "B5 · 시치후쿠 거리", en: "B5 · Shichifuku St" },
        location: { ko: "러브박스 입수, 비탈길 건물 간판", en: "Love Box — sign of the building on the slope" },
        reward: { ko: "마지마 건설 헬멧", en: "Majima Construction Helmet" },
      },
      {
        number: 11,
        title: { ko: "C1 · 호텔가", en: "C1 · Hotel District" },
        location: { ko: "호텔가에서 배팅센터 동쪽 계단을 올라 길 따라 끝까지", en: "Up the east stairs from the batting center, follow the road to the end" },
        reward: { ko: "키넥 셔츠(아우터)", en: "Key-Neck Shirt (Outer)" },
      },
      {
        number: 12,
        title: { ko: "C2 · 챔피언 거리", en: "C2 · Champion District" },
        location: { ko: "챔피언 거리 남동쪽 장기판 광장", en: "Southeast Champion District, the shogi plaza" },
        reward: { ko: "티셔츠(영문)", en: "T-Shirt (Letters)" },
      },
      {
        number: 13,
        title: { ko: "C3 · 뉴 세레나 뒤", en: "C3 · Behind New Serena" },
        location: { ko: "뉴 세레나 뒤 북서쪽 모서리", en: "Northwest corner behind New Serena" },
        reward: { ko: "CD「MachineGun Kiss(키류)」", en: "CD \"MachineGun Kiss (Kiryu)\"" },
      },
      {
        number: 14,
        title: { ko: "C4 · 천하일 거리", en: "C4 · Tenkaichi St" },
        location: { ko: "엘리베이터로 마작 라라바이에 들어간 정면", en: "Straight ahead after taking the elevator into Mahjong Lullaby" },
        reward: { ko: "슬랙스(표범무늬)", en: "Slacks (Leopard)" },
      },
      {
        number: 15,
        title: { ko: "C5 · 극장 앞 광장 뒤", en: "C5 · Behind Theater Sq" },
        location: { ko: "러브박스 입수, 볼링장 동쪽 외벽", en: "Love Box — east outer wall of the bowling alley" },
        reward: { ko: "뱀 안대", en: "Snake Eyepatch" },
      },
      {
        number: 16,
        title: { ko: "D1 · 공원 앞 거리", en: "D1 · Park Blvd" },
        location: { ko: "길모퉁이 바닥", en: "On the ground at the corner" },
        reward: { ko: "풀오버 파카", en: "Pullover Parka" },
      },
      {
        number: 17,
        title: { ko: "D2 · 천하일 거리 뒤", en: "D2 · Behind Tenkaichi St" },
        location: { ko: "천하일 거리에서 들어가는 골목 안쪽", en: "Deep in the alley off Tenkaichi St" },
        reward: { ko: "CD「TONIGHT-restart from this night-(키류)」", en: "CD \"TONIGHT (Kiryu)\"" },
      },
      {
        number: 18,
        title: { ko: "D3 · 나카미치 거리 뒤", en: "D3 · Behind Nakamichi St" },
        location: { ko: "나카미치 거리 뒤 골목 빌딩 엘리베이터 앞", en: "Elevator of the alley building behind Nakamichi St" },
        reward: { ko: "긴팔 와이셔츠(골드)", en: "Long-Sleeve Shirt (Gold)" },
      },
      {
        number: 19,
        title: { ko: "D4 · 나카미치 거리 뒤", en: "D4 · Behind Nakamichi St" },
        location: { ko: "나카미치 거리 뒤 전당포 앞", en: "In front of the pawnshop behind Nakamichi St" },
        reward: { ko: "CD「고동」", en: "CD \"Kodou\"" },
      },
      {
        number: 20,
        title: { ko: "D5 · 뉴 세레나 뒤", en: "D5 · Behind New Serena" },
        location: { ko: "러브박스 입수, 자판기 쪽 건물 외벽", en: "Love Box — building wall by the vending machine" },
        reward: { ko: "안테나: 마지마 건설 헬멧", en: "Antenna: Majima Construction Helmet" },
      },
      {
        number: 21,
        title: { ko: "E1 · 호텔가", en: "E1 · Hotel District" },
        location: { ko: "배팅센터 주차장 북쪽", en: "North of the batting-center parking lot" },
        reward: { ko: "입체 스티커: 리본(퍼플)", en: "3D Sticker: Ribbon (Purple)" },
      },
      {
        number: 22,
        title: { ko: "E2 · 타이헤이 거리 동쪽", en: "E2 · East Taihei Blvd" },
        location: { ko: "타이헤이 거리 동쪽 주차장 자판기 뒤", en: "Behind the vending machine in the East Taihei Blvd lot" },
        reward: { ko: "CD「Now or Never」", en: "CD \"Now or Never\"" },
      },
      {
        number: 23,
        title: { ko: "E3 · 슷폰 거리", en: "E3 · Suppon St" },
        location: { ko: "슷폰 거리 서쪽 가게 앞", en: "In front of the west-side shop on Suppon St" },
        reward: { ko: "특공복 안쪽 단추·특 ×3", en: "Tokko-fuku Inner Button (Special) ×3" },
      },
      {
        number: 24,
        title: { ko: "E4 · 쇼와 거리 동쪽", en: "E4 · East Showa St" },
        location: { ko: "르 망셰 가게 안", en: "Inside Le Manche" },
        reward: { ko: "카고 팬츠(하프)", en: "Cargo Pants (Half)" },
      },
      {
        number: 25,
        title: { ko: "E5 · 천하일 거리 입구", en: "E5 · Tenkaichi St Entrance" },
        location: { ko: "러브박스 입수, 쇼와 거리 서쪽 끝 건물 외벽", en: "Love Box — west-end building wall on Showa St" },
        reward: { ko: "스트랩: 게임기어", en: "Strap: Game Gear" },
      },
      {
        number: 26,
        title: { ko: "F1 · 공원 앞 거리", en: "F1 · Park Blvd" },
        location: { ko: "공원 앞 거리 호텔 외벽 안쪽", en: "Inner wall of the hotel on Park Blvd" },
        reward: { ko: "입체 스티커: 리본(스카이블루)", en: "3D Sticker: Ribbon (Sky Blue)" },
      },
      {
        number: 27,
        title: { ko: "F2 · 천량 거리", en: "F2 · Senryo Ave" },
        location: { ko: "천량 거리 건물 엘리베이터 앞", en: "Elevator of the Senryo Ave building" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 28,
        title: { ko: "F3 · 극장 북서", en: "F3 · NW of Theater" },
        location: { ko: "스마일 버거 가게 안", en: "Inside Smile Burger" },
        reward: { ko: "슈트(표범무늬)", en: "Suit (Leopard)" },
      },
      {
        number: 29,
        title: { ko: "F4 · 핑크 거리", en: "F4 · Pink St" },
        location: { ko: "핑크 거리 무료 안내소 안", en: "Inside the Pink St info center" },
        reward: { ko: "아라시의 양갱 ×1, 도싯핀즈 ×1, 행운 화투 ×1, 보등의 패 ×1", en: "Arashi's Yokan ×1, Doshippins ×1, Lucky Hanafuda ×1, Houtou Tile ×1" },
      },
      {
        number: 30,
        title: { ko: "F5 · 핑크 거리", en: "F5 · Pink St" },
        location: { ko: "러브박스 입수, 고토부키 약국 남쪽 건물 외벽", en: "Love Box — wall south of Kotobuki Pharmacy" },
        reward: { ko: "스트랩: 마지마 동상", en: "Strap: Majima Statue" },
      },
      {
        number: 31,
        title: { ko: "G1 · 시치후쿠 거리 동쪽", en: "G1 · East Shichifuku St" },
        location: { ko: "시치후쿠 거리 동쪽과 공원 앞 거리 사이 공터", en: "Vacant lot between East Shichifuku St and Park Blvd" },
        reward: { ko: "금 접시", en: "Gold Plate" },
      },
      {
        number: 32,
        title: { ko: "G2 · 핑크 거리 뒤", en: "G2 · Behind Pink St" },
        location: { ko: "핑크 거리 뒤 남쪽 골목 T자로", en: "T-junction of the south alley behind Pink St" },
        reward: { ko: "CD「Let Me See You Dancin」", en: "CD \"Let Me See You Dancin\"" },
      },
      {
        number: 33,
        title: { ko: "G3 · 나카미치 거리 뒤", en: "G3 · Behind Nakamichi St" },
        location: { ko: "나카미치 거리 뒤 북서쪽 가게 앞", en: "In front of the NW shop behind Nakamichi St" },
        reward: { ko: "사운드트랙 CD「North Star」", en: "Soundtrack CD \"North Star\"" },
      },
      {
        number: 34,
        title: { ko: "G4 · 천량 거리", en: "G4 · Senryo Ave" },
        location: { ko: "천량 거리 북쪽 무료 안내소 안", en: "Inside the north info center on Senryo Ave" },
        reward: { ko: "뱀가죽 슈즈", en: "Snakeskin Shoes" },
      },
      {
        number: 35,
        title: { ko: "G5 · 시치후쿠 거리", en: "G5 · Shichifuku St" },
        location: { ko: "러브박스 입수, 밀레니엄 타워 동쪽 거리와 교차하는 건물 외벽", en: "Love Box — wall where it meets Millennium Tower East St" },
        reward: { ko: "대기화면: 카무로초", en: "Wallpaper: Kamurocho" },
      },
      {
        number: 36,
        title: { ko: "H1 · 극장 앞 광장 뒤", en: "H1 · Behind Theater Sq" },
        location: { ko: "마하 볼 입구 왼쪽", en: "Left of the Mach Bowl entrance" },
        reward: { ko: "CD「후부키 코우타」", en: "CD \"Fubuki Kouta\"" },
      },
      {
        number: 37,
        title: { ko: "H2 · 천량 거리", en: "H2 · Senryo Ave" },
        location: { ko: "천량 거리 남쪽 경트럭 뒤", en: "Behind the kei-truck on south Senryo Ave" },
        reward: { ko: "스트랩: 포트", en: "Strap: Pot" },
      },
      {
        number: 38,
        title: { ko: "H3 · 타이헤이 거리", en: "H3 · Taihei Blvd" },
        location: { ko: "타이헤이 거리와 밀레니엄 타워 동쪽 거리 교차 지점 주차장", en: "Lot where Taihei Blvd meets Millennium Tower East St" },
        reward: { ko: "맨몸 재킷", en: "Bare Jacket" },
      },
      {
        number: 39,
        title: { ko: "H4 · 호텔가", en: "H4 · Hotel District" },
        location: { ko: "호텔가 북서쪽 호텔 엘리베이터 앞", en: "Elevator of the NW hotel in Hotel District" },
        reward: { ko: "핀조로의 패 ×1, 히후미 껌 ×1, 쵸고로의 염주 ×1, 카타요리사의 담배 ×1", en: "Pinzoro Tile ×1, Hifumi Gum ×1, Chogoro Beads ×1, Katayori Cigarettes ×1" },
      },
      {
        number: 40,
        title: { ko: "H5 · 천량 거리", en: "H5 · Senryo Ave" },
        location: { ko: "러브박스 입수, 남쪽 건물 외벽", en: "Love Box — south building wall" },
        reward: { ko: "CD「24시간 신데렐라(마지마)」", en: "CD \"24-Hour Cinderella (Majima)\"" },
      },
      {
        number: 41,
        title: { ko: "I1 · 극장 앞 광장", en: "I1 · Theater Sq" },
        location: { ko: "극장 앞 광장 북쪽 길가", en: "Roadside north of Theater Square" },
        reward: { ko: "입체 스티커: 스타(그린)", en: "3D Sticker: Star (Green)" },
      },
      {
        number: 42,
        title: { ko: "I2 · 타이헤이 거리 동쪽", en: "I2 · East Taihei Blvd" },
        location: { ko: "타이헤이 거리 동쪽 옷가게 「코스 라버즈」 입구 옆", en: "Beside the Cos Lovers shop entrance, East Taihei Blvd" },
        reward: { ko: "입체 스티커: 스타(핑크)", en: "3D Sticker: Star (Pink)" },
      },
      {
        number: 43,
        title: { ko: "I3 · 호텔가", en: "I3 · Hotel District" },
        location: { ko: "호텔가 북쪽 호텔 외벽 안쪽", en: "Inner wall of the north hotel in Hotel District" },
        reward: { ko: "입체 스티커: 물방울(그린)", en: "3D Sticker: Drop (Green)" },
      },
      {
        number: 44,
        title: { ko: "I4 · 시치후쿠 거리", en: "I4 · Shichifuku St" },
        location: { ko: "시치후쿠 거리 길모퉁이", en: "At the corner of Shichifuku St" },
        reward: { ko: "구멍 뚫린 글러브", en: "Holey Glove" },
      },
      {
        number: 45,
        title: { ko: "I5 · 챔피언 거리", en: "I5 · Champion District" },
        location: { ko: "러브박스 입수, 남쪽 좁은 골목 외벽", en: "Love Box — wall of the narrow south alley" },
        reward: { ko: "CD「카무로초 랩소디(키류)」", en: "CD \"Kamurocho Rhapsody (Kiryu)\"" },
      },
      {
        number: 46,
        title: { ko: "J1 · 시치후쿠 거리 서쪽", en: "J1 · West Shichifuku St" },
        location: { ko: "시치후쿠 거리 서쪽 월정 주차장 입구", en: "Entrance of the monthly lot on West Shichifuku St" },
        reward: { ko: "입체 스티커: 스타(옐로)", en: "3D Sticker: Star (Yellow)" },
      },
      {
        number: 47,
        title: { ko: "J2 · 나카미치 거리", en: "J2 · Nakamichi St" },
        location: { ko: "모퉁이 건물 계단을 올라간 곳", en: "Up the stairs of the corner building" },
        reward: { ko: "구리 접시 ×1, 은 접시 ×1, 금 접시 ×1", en: "Copper Plate ×1, Silver Plate ×1, Gold Plate ×1" },
      },
      {
        number: 48,
        title: { ko: "J3 · 챔피언 거리", en: "J3 · Champion District" },
        location: { ko: "챔피언 거리 북동쪽 바닥", en: "On the ground, NE Champion District" },
        reward: { ko: "슈트(토죠회 문장)", en: "Suit (Tojo Clan Emblem)" },
      },
      {
        number: 49,
        title: { ko: "J4 · 극장 앞 거리", en: "J4 · Theater Ave" },
        location: { ko: "극장 앞 거리 남쪽 끝 무료 안내소 안", en: "Inside the south-end info center on Theater Ave" },
        reward: { ko: "파인애플 ×3", en: "Pineapple ×3" },
      },
      {
        number: 50,
        title: { ko: "J5 · 호텔가", en: "J5 · Hotel District" },
        location: { ko: "러브박스 입수, 호텔가 북쪽 끝 호텔 외벽", en: "Love Box — north-end hotel wall in Hotel District" },
        reward: { ko: "스티커: 디스코 마지마", en: "Sticker: Disco Majima" },
      },
        ],
      },
      {
        title: { ko: "류큐 거리(오키나와) — 50개 열쇠", en: "Ryukyu Street (Okinawa) — 50 Keys" },
        items: [
      {
        number: 1,
        title: { ko: "A1 · 하츠마치 거리", en: "A1 · Hatsumachi St" },
        location: { ko: "하츠마치 거리 창작요리 사토 앞", en: "In front of Sato (creative cuisine) on Hatsumachi St" },
        reward: { ko: "최상급 동물 사료 ×2", en: "Top-Grade Animal Food ×2" },
      },
      {
        number: 2,
        title: { ko: "A2 · 하츠마치 이나리 거리", en: "A2 · Hatsumachi Inari St" },
        location: { ko: "하츠마치 이나리 거리 사쿠라콘고 앞", en: "In front of Sakura Kongo, Hatsumachi Inari St" },
        reward: { ko: "BJ의 부적 ×1, 버스트의 부적 ×1, 로열 조커 ×1", en: "BJ Charm ×1, Burst Charm ×1, Royal Joker ×1" },
      },
      {
        number: 3,
        title: { ko: "A3 · 하츠마치 거리", en: "A3 · Hatsumachi St" },
        location: { ko: "하츠마치 거리 무료 안내소 앞", en: "In front of the info center on Hatsumachi St" },
        reward: { ko: "CD「절망정 프라이드(마지마&키류)」", en: "CD \"Zetsuboucho Pride (Majima & Kiryu)\"" },
      },
      {
        number: 4,
        title: { ko: "A4 · 하츠마치 거리", en: "A4 · Hatsumachi St" },
        location: { ko: "하츠마치 거리 마작 캠프 옆", en: "Beside Mahjong Camp on Hatsumachi St" },
        reward: { ko: "해수욕 팬츠(트로피컬)", en: "Swim Trunks (Tropical)" },
      },
      {
        number: 5,
        title: { ko: "A5 · 하츠마치 이나리 거리", en: "A5 · Hatsumachi Inari St" },
        location: { ko: "러브박스 입수, 하츠마치 이나리 거리 서쪽 「대중주점 루루파」 간판", en: "Love Box — sign of Izakaya Rurupa, west Hatsumachi Inari St" },
        reward: { ko: "보디수트(류큐 카스리)", en: "Bodysuit (Ryukyu Kasuri)" },
      },
      {
        number: 6,
        title: { ko: "B1 · 하츠마치 이나리 거리", en: "B1 · Hatsumachi Inari St" },
        location: { ko: "하츠마치 이나리 거리 아쿠아 스카이 입구", en: "Entrance of Aqua Sky, Hatsumachi Inari St" },
        reward: { ko: "알로하 셔츠(트로피컬)", en: "Aloha Shirt (Tropical)" },
      },
      {
        number: 7,
        title: { ko: "B2 · 쿠보치가와 측도 남쪽", en: "B2 · South Kubochigawa Path" },
        location: { ko: "쿠보치가와 측도 남쪽 모노레일 승강장 아래", en: "Under the monorail platform, south Kubochigawa Path" },
        reward: { ko: "CD「오토메탈 my life(하루카)」", en: "CD \"Otometal my life (Haruka)\"" },
      },
      {
        number: 8,
        title: { ko: "B3 · 쿠보치가와 측도 남쪽", en: "B3 · South Kubochigawa Path" },
        location: { ko: "쿠보치가와 측도 남쪽 요노 오토 서비스 앞", en: "In front of Yono Auto Service, south Kubochigawa Path" },
        reward: { ko: "슬랙스(광택)", en: "Slacks (Glossy)" },
      },
      {
        number: 9,
        title: { ko: "B4 · 쿠보치가와 측도 남쪽", en: "B4 · South Kubochigawa Path" },
        location: { ko: "히비스커스 아이스크림 류큐 본점 뒤 주차장", en: "Parking lot behind Hibiscus Ice Cream Ryukyu" },
        reward: { ko: "스티커: 체리", en: "Sticker: Cherry" },
      },
      {
        number: 10,
        title: { ko: "B5 · 류큐 거리", en: "B5 · Ryukyu St" },
        location: { ko: "러브박스 입수, 스테이크하우스와 아이스크림 가게 사이", en: "Love Box — between the steakhouse and ice cream shop" },
        reward: { ko: "도복", en: "Dogi" },
      },
      {
        number: 11,
        title: { ko: "C1 · 류큐 거리", en: "C1 · Ryukyu St" },
        location: { ko: "류큐 거리 스테이크하우스 오키나ONE 본점 옆", en: "Beside Steakhouse Okina ONE (main), Ryukyu St" },
        reward: { ko: "금 접시", en: "Gold Plate" },
      },
      {
        number: 12,
        title: { ko: "C2 · 하츠마치 거리", en: "C2 · Hatsumachi St" },
        location: { ko: "하츠마치 거리 POPPO 하츠마치점 계단 앞", en: "In front of the POPPO Hatsumachi stairs" },
        reward: { ko: "고급 물고기 먹이 ×2", en: "Fine Fish Bait ×2" },
      },
      {
        number: 13,
        title: { ko: "C3 · 류큐 중앙가도", en: "C3 · Ryukyu Central Rd" },
        location: { ko: "류큐 중앙가도 우마치에서 류큐 가도로 향하는 길가", en: "Roadside from Umachi toward Ryukyu Rd" },
        reward: { ko: "붉은 보석 ×1, 검은 보석 ×1, 무의 보석 ×1, PLAYER 말 ×1, BANKER 말 ×1", en: "Red/Black/Void Gem ×1 each, PLAYER ×1, BANKER ×1" },
      },
      {
        number: 14,
        title: { ko: "C4 · 츄라바", en: "C4 · Churabaa" },
        location: { ko: "츄라바 2층", en: "2nd floor of Churabaa" },
        reward: { ko: "스티커: 빙수", en: "Sticker: Shaved Ice" },
      },
      {
        number: 15,
        title: { ko: "C5 · 하츠마치 이나리 거리", en: "C5 · Hatsumachi Inari St" },
        location: { ko: "러브박스 입수, 하츠마치 이나리 거리 택시 서쪽 빌딩 2층 외벽", en: "Love Box — 2F wall of the building west of the taxi" },
        reward: { ko: "슷파이만 코스튬 외 매실과자 3종", en: "Suppaiman Costume + 3 ume snacks" },
      },
      {
        number: 16,
        title: { ko: "D1 · 유시빈 거리", en: "D1 · Yushibin St" },
        location: { ko: "유시빈 거리 입구 전단지가 붙은 곳", en: "Just inside Yushibin St, where the flyers are" },
        reward: { ko: "CD「행복하면 됐어(마지마)」", en: "CD \"Shiawase nara ii ya (Majima)\"" },
      },
      {
        number: 17,
        title: { ko: "D2 · 류큐 거리", en: "D2 · Ryukyu St" },
        location: { ko: "카리유시 아케이드 북쪽 끝 간판 뒤편", en: "Behind the sign at the north end of Kariyushi Arcade" },
        reward: { ko: "슈트(광택)", en: "Suit (Glossy)" },
      },
      {
        number: 18,
        title: { ko: "D3 · 류큐 거리 동쪽", en: "D3 · East Ryukyu St" },
        location: { ko: "류큐 거리 동쪽 횡단보도", en: "Crosswalk on East Ryukyu St" },
        reward: { ko: "카고 팬츠(하프)", en: "Cargo Pants (Half)" },
      },
      {
        number: 19,
        title: { ko: "D4 · 류큐 거리 동쪽", en: "D4 · East Ryukyu St" },
        location: { ko: "류큐 거리 동쪽 POPPO 우편함 위", en: "On the POPPO mailbox, East Ryukyu St" },
        reward: { ko: "티어드롭 안경", en: "Teardrop Glasses" },
      },
      {
        number: 20,
        title: { ko: "D5 · 쿠보치가와 측도 남쪽", en: "D5 · South Kubochigawa Path" },
        location: { ko: "러브박스 입수, 쿠보치가와 측도 남쪽 「시마시마 주시」 간판", en: "Love Box — Shimashima Juicy sign, south Kubochigawa Path" },
        reward: { ko: "슈트(도지마구미 문장)", en: "Suit (Dojima Family Emblem)" },
      },
      {
        number: 21,
        title: { ko: "E1 · 류큐 거리", en: "E1 · Ryukyu St" },
        location: { ko: "류큐 거리 스마일 버거 옆", en: "Beside Smile Burger on Ryukyu St" },
        reward: { ko: "안테나: 딸기 ×2", en: "Antenna: Strawberry ×2" },
      },
      {
        number: 22,
        title: { ko: "E2 · 카리유시 아케이드", en: "E2 · Kariyushi Arcade" },
        location: { ko: "카리유시 아케이드 「마~상즈 주스」 앞", en: "In front of Maa-san's Juice, Kariyushi Arcade" },
        reward: { ko: "구리 접시 ×1, 은 접시 ×1, 금 접시 ×1", en: "Copper/Silver/Gold Plate ×1 each" },
      },
      {
        number: 23,
        title: { ko: "E3 · 유시빈 거리", en: "E3 · Yushibin St" },
        location: { ko: "유시빈 거리 나카하라 흥행 앞", en: "In front of Nakahara Kogyo, Yushibin St" },
        reward: { ko: "CD「As a man, As a brother」", en: "CD \"As a man, As a brother\"" },
      },
      {
        number: 24,
        title: { ko: "E4 · 공설시장 앞", en: "E4 · Public Market Front" },
        location: { ko: "공설시장 앞 가게 Ayako 앞", en: "In front of shop Ayako, Public Market" },
        reward: { ko: "병밑 안경", en: "Bottle-Bottom Glasses" },
      },
      {
        number: 25,
        title: { ko: "E5 · 류큐 중앙가도", en: "E5 · Ryukyu Central Rd" },
        location: { ko: "러브박스 입수, 전당포 남쪽 빌딩 외벽", en: "Love Box — wall of the building south of the pawnshop" },
        reward: { ko: "CD「여행의 노래 -grandioso-」", en: "CD \"Tabidachi no Uta -grandioso-\"" },
      },
      {
        number: 26,
        title: { ko: "F1 · 공설시장 앞", en: "F1 · Public Market Front" },
        location: { ko: "공설시장 앞 주류점 앞", en: "In front of the liquor store, Public Market" },
        reward: { ko: "입체 스티커: 하트(스카이블루)", en: "3D Sticker: Heart (Sky Blue)" },
      },
      {
        number: 27,
        title: { ko: "F2 · 스테이크하우스 오키나ONE 류큐 거리점", en: "F2 · Okina ONE Ryukyu St" },
        location: { ko: "스테이크하우스 오키나ONE 류큐 거리점 안 계단 앞", en: "Inside Okina ONE (Ryukyu St), by the stairs" },
        reward: { ko: "스트랩: 우치나 치이네코", en: "Strap: Uchina Chiineko" },
      },
      {
        number: 28,
        title: { ko: "F3 · 카리유시 아케이드", en: "F3 · Kariyushi Arcade" },
        location: { ko: "요시다 제과점 옆 계단 앞", en: "By the stairs next to Yoshida Confectionery" },
        reward: { ko: "CD「Fly」", en: "CD \"Fly\"" },
      },
      {
        number: 29,
        title: { ko: "F4 · 류큐 중앙가도", en: "F4 · Ryukyu Central Rd" },
        location: { ko: "류큐 중앙가도 우마치 옆", en: "Beside Umachi on Ryukyu Central Rd" },
        reward: { ko: "CD「신·이·치·즈 사무라이(키류)」", en: "CD \"Shin Ichizu Samurai (Kiryu)\"" },
      },
      {
        number: 30,
        title: { ko: "F5 · 류큐 광장", en: "F5 · Ryukyu Plaza" },
        location: { ko: "러브박스 입수, 광장 북쪽 외벽", en: "Love Box — north wall of the plaza" },
        reward: { ko: "CD「파라라이(키류)」", en: "CD \"Pararai (Kiryu)\"" },
      },
      {
        number: 31,
        title: { ko: "G1 · 카리유시 아케이드", en: "G1 · Kariyushi Arcade" },
        location: { ko: "카리유시 아케이드 복권 노점 옆", en: "Beside the lottery stall, Kariyushi Arcade" },
        reward: { ko: "CD「Receive You」", en: "CD \"Receive You\"" },
      },
      {
        number: 32,
        title: { ko: "G2 · 카리유시 아케이드", en: "G2 · Kariyushi Arcade" },
        location: { ko: "카리유시 아케이드 「하나하나야」 남쪽 악기점 앞", en: "South of Hanahanaya, in front of the instrument shop" },
        reward: { ko: "파인애플 ×3", en: "Pineapple ×3" },
      },
      {
        number: 33,
        title: { ko: "G3 · 아케이드 뒤편 측도", en: "G3 · Behind-Arcade Path" },
        location: { ko: "카리유시 아케이드 SHIMA BIAD 옆 자판기 앞", en: "By the vending machine next to SHIMA BIAD" },
        reward: { ko: "알로하 팬츠(트로피컬)", en: "Aloha Pants (Tropical)" },
      },
      {
        number: 34,
        title: { ko: "G4 · 류큐 광장", en: "G4 · Ryukyu Plaza" },
        location: { ko: "류큐 광장 담장 옆", en: "Beside the wall in Ryukyu Plaza" },
        reward: { ko: "설탕 ×3", en: "Sugar ×3" },
      },
      {
        number: 35,
        title: { ko: "G5 · 류큐 거리 동쪽", en: "G5 · East Ryukyu St" },
        location: { ko: "러브박스 입수, 스마일 버거 빌딩 측면 상부", en: "Love Box — upper side of the Smile Burger building" },
        reward: { ko: "안테나: 츠보헤비", en: "Antenna: Tsubo-snake" },
      },
      {
        number: 36,
        title: { ko: "H1 · 아케이드 뒤편 측도", en: "H1 · Behind-Arcade Path" },
        location: { ko: "코인로커가 있는 건물 남쪽 외벽", en: "South wall of the coin-locker building" },
        reward: { ko: "입체 스티커: 하트(그린)", en: "3D Sticker: Heart (Green)" },
      },
      {
        number: 37,
        title: { ko: "H2 · 류큐 거리 동쪽", en: "H2 · East Ryukyu St" },
        location: { ko: "코인로커 남쪽 계단을 내려가 꺾인 지점 엘리베이터 앞", en: "Elevator past the south coin-locker stairs" },
        reward: { ko: "입체 스티커: 리본(그린)", en: "3D Sticker: Ribbon (Green)" },
      },
      {
        number: 38,
        title: { ko: "H3 · 류큐 거리 동쪽", en: "H3 · East Ryukyu St" },
        location: { ko: "코인로커 남쪽 계단을 내려가 꺾인 지점", en: "Past the south coin-locker stairs, around the bend" },
        reward: { ko: "입체 스티커: 물방울(퍼플)", en: "3D Sticker: Drop (Purple)" },
      },
      {
        number: 39,
        title: { ko: "H4 · 류큐 거리 동쪽", en: "H4 · East Ryukyu St" },
        location: { ko: "코인로커 앞 엘리베이터 앞", en: "Elevator in front of the coin lockers" },
        reward: { ko: "CD「분명 Change myself(하루카)」", en: "CD \"Kitto Change myself (Haruka)\"" },
      },
      {
        number: 40,
        title: { ko: "H5 · 아케이드 뒤편 측도", en: "H5 · Behind-Arcade Path" },
        location: { ko: "러브박스 입수, 도박장 입구 위쪽", en: "Love Box — above the gambling den entrance" },
        reward: { ko: "스트랩: 카리유시 분짱", en: "Strap: Kariyushi Bun-chan" },
      },
      {
        number: 41,
        title: { ko: "I1 · 스테이크하우스 오키나ONE 본점", en: "I1 · Okina ONE Main" },
        location: { ko: "스테이크하우스 오키나ONE 본점 안", en: "Inside Steakhouse Okina ONE (main)" },
        reward: { ko: "최상급 비료 ×2", en: "Top-Grade Fertilizer ×2" },
      },
      {
        number: 42,
        title: { ko: "I2 · 류큐 거리 동쪽", en: "I2 · East Ryukyu St" },
        location: { ko: "류큐 거리 동쪽 스마일 버거 안 왼쪽 계단 근처", en: "Left stairs inside Smile Burger, East Ryukyu St" },
        reward: { ko: "입체 스티커: 리본(옐로)", en: "3D Sticker: Ribbon (Yellow)" },
      },
      {
        number: 43,
        title: { ko: "I3 · 하츠마치 거리", en: "I3 · Hatsumachi St" },
        location: { ko: "하츠마치 거리 가라오케관 류큐 본점 옆 자판기 근처", en: "By the vending machine next to Karaoke-kan Ryukyu" },
        reward: { ko: "입체 스티커: 물방울(핑크)", en: "3D Sticker: Drop (Pink)" },
      },
      {
        number: 44,
        title: { ko: "I4 · 류큐 거리", en: "I4 · Ryukyu St" },
        location: { ko: "류큐 거리 동쪽 옷가게 「고~잉·마이웨~」 앞", en: "In front of shop Going My Way, east Ryukyu St" },
        reward: { ko: "스트랩: 조개껍데기(화이트)", en: "Strap: Seashell (White)" },
      },
      {
        number: 45,
        title: { ko: "I5 · 카리유시 아케이드", en: "I5 · Kariyushi Arcade" },
        location: { ko: "러브박스 입수, 카리유시 아케이드 북쪽 끝 동쪽 건물 외벽", en: "Love Box — east building wall, north end of Kariyushi Arcade" },
        reward: { ko: "대기화면: 류큐 거리", en: "Wallpaper: Ryukyu St" },
      },
      {
        number: 46,
        title: { ko: "J1 · 우마치", en: "J1 · Umachi" },
        location: { ko: "우마치 가게 안", en: "Inside Umachi" },
        reward: { ko: "탱크탑(제브라)", en: "Tank Top (Zebra)" },
      },
      {
        number: 47,
        title: { ko: "J2 · 류큐 거리 서쪽", en: "J2 · West Ryukyu St" },
        location: { ko: "류큐 거리 서쪽 히비스커스 아이스크림 류큐 본점 옆", en: "Beside Hibiscus Ice Cream Ryukyu, West Ryukyu St" },
        reward: { ko: "청 재킷(티셔츠)", en: "Denim Jacket (T-Shirt)" },
      },
      {
        number: 48,
        title: { ko: "J3 · 류큐 거리", en: "J3 · Ryukyu St" },
        location: { ko: "류큐 거리 스테이크하우스 오키나ONE 류큐점에서 오른쪽 모퉁이", en: "Corner right of Okina ONE (Ryukyu St)" },
        reward: { ko: "해수욕 팬츠(무지)", en: "Swim Trunks (Plain)" },
      },
      {
        number: 49,
        title: { ko: "J4 · 류큐 거리 동쪽", en: "J4 · East Ryukyu St" },
        location: { ko: "스마일 버거 맞은편 빌딩 입구 기둥 뒤", en: "Behind the pillar across from Smile Burger" },
        reward: { ko: "입체 스티커: 하트(옐로)", en: "3D Sticker: Heart (Yellow)" },
      },
      {
        number: 50,
        title: { ko: "J5 · 공설시장 앞", en: "J5 · Public Market Front" },
        location: { ko: "러브박스 입수, 공설시장 입구 상부", en: "Love Box — above the Public Market entrance" },
        reward: { ko: "스티커: 디스코 키류", en: "Sticker: Disco Kiryu" },
      },
        ],
      },
      ],
    }
  ],
};
