import type { CollectiblesData } from "./types";

export const yakuzaKiwami3: CollectiblesData = {
  appId: 3937550,
  categories: [
    {
      slug: "coin-lockers",
      title: { ko: "물품 보관함 — 카무로초 50개 + 류큐 50개", en: "Coin Lockers — 50 Kamurocho + 50 Ryukyu Keys" },
      summary: {
        ko: "카무로초와 다운타운 류큐에 각각 50개씩, 총 100개의 코인로커 열쇠가 흩어져 있습니다. 열쇠는 길바닥·건물 구석에 떨어져 있거나(A~D열) 노란 「러브박스」 안에 들어있습니다(E/5열).",
        en: "100 coin-locker keys total — 50 in Kamurocho, 50 in Downtown Ryukyu. Keys sit on the ground/building corners (A-D rows) or inside yellow 'Love Boxes' (row 5).",
      },
      tips: [
        { ko: "카무로초 보관함은 타이헤이 거리, LaLaLa 모바일 매대 서쪽에 있습니다. 류큐 보관함은 맵 남동쪽 상단, 포포(류큐 거리점) 옆 계단으로 올라간 곳에 있습니다.", en: "The Kamurocho lockers sit on Taihei Blvd, just west of the LaLaLa Mobile stall. The Ryukyu lockers are in the map's southeast corner, up the stairs beside Poppo (Ryukyu Blvd.)." },
      ],
      source: [
        { label: "TheGamer — Kamurocho Coin Locker Key Location & Reward Guide", url: "https://www.thegamer.com/yakuza-kiwami-3-kamurocho-coin-locker-key-location-reward-guide/" },
        { label: "TheGamer — Downtown Ryukyu Coin Locker Key Location & Reward Guide", url: "https://www.thegamer.com/yakuza-kiwami-3-downtown-ryukyu-coin-locker-key-location-reward-guide/" },
      ],
      groups: [
        {
          title: { ko: "카무로초 — 50개 열쇠", en: "Kamurocho — 50 Keys" },
          items: [
            { number: 1, title: { ko: "A1", en: "A1" }, location: { ko: "호텔가 거리 지명 표시 아래 골목", en: "Hotel District Road alcove below map label" }, reward: { ko: "데이토나 사운드트랙 CD", en: "Daytona Soundtrack CD" } },
            { number: 2, title: { ko: "B1", en: "B1" }, location: { ko: "요시다 배팅 센터 북서쪽 주차장", en: "Parking garage northwest of Yoshida Batting Center" }, reward: { ko: "카무로초 자장가 CD", en: "Kamurocho Lullaby CD" } },
            { number: 3, title: { ko: "C1", en: "C1" }, location: { ko: "요시다 배팅 센터 옥상 북동쪽 모서리", en: "Yoshida Batting Center roof, northeastern corner" }, reward: { ko: "키넥 셔츠+재킷", en: "Keyneck Shirt with Jacket" } },
            { number: 4, title: { ko: "D1", en: "D1" }, location: { ko: "드래곤 팰리스·이키나리 스테이크 북동쪽 모서리", en: "Northeast corner near Dragon Palace and Ikinari Steak" }, reward: { ko: "풀오버 후드", en: "Pullover Hoodie" } },
            { number: 5, title: { ko: "E1", en: "E1" }, location: { ko: "요시다 배팅 센터 정문 왼쪽", en: "Outside Yoshida Batting Center, left of doors" }, reward: { ko: "퍼피 스티커: 리본(퍼플)", en: "Puffy Sticker: Ribbon (Purple)" } },
            { number: 6, title: { ko: "F1", en: "F1" }, location: { ko: "칸라이 북쪽 파크 대로, 빨간 환영매트 문", en: "Park Blvd north of Kanrai, red welcome mat door" }, reward: { ko: "퍼피 스티커: 리본(스카이블루)", en: "Puffy Sticker: Ribbon (Sky Blue)" } },
            { number: 7, title: { ko: "G1", en: "G1" }, location: { ko: "키스 샷 빌리아드 동쪽 골목 북쪽 구간", en: "Alleyway east of Kiss Shot Billiards, northern section" }, reward: { ko: "골드 플레이트", en: "Gold Plate" } },
            { number: 8, title: { ko: "H1", en: "H1" }, location: { ko: "맥 볼 내부 엘리베이터 앞", en: "Front of elevator inside Mach Bowl" }, reward: { ko: "후부키 코우타 CD", en: "Fubuki Kouta CD" } },
            { number: 9, title: { ko: "I1", en: "I1" }, location: { ko: "극장 앞 광장 북쪽, 클럽 세가 근처 볼라드 옆", en: "Theater Square north side near Club SEGA, by bollard" }, reward: { ko: "퍼피 스티커: 별(그린)", en: "Puffy Sticker: Star (Green)" } },
            { number: 10, title: { ko: "J1", en: "J1" }, location: { ko: "어린이 공원 맞은편 W 시치후쿠 거리, 문 근처", en: "W Shichifuku St opposite Children's Park, near doors" }, reward: { ko: "퍼피 스티커: 별(옐로우)", en: "Puffy Sticker: Star (Yellow)" } },
            { number: 11, title: { ko: "A2", en: "A2" }, location: { ko: "웨스트 파크 공중화장실 모서리", en: "West Park public toilets, corner" }, reward: { ko: "특공복 버튼: 극 x2", en: "Baddie Uniform Button: Kiwami x2" } },
            { number: 12, title: { ko: "B2", en: "B2" }, location: { ko: "포포 맞은편 E 시치후쿠 거리 입구, 엘리베이터 옆", en: "E Shichifuku St entryway opposite Poppo, by elevator" }, reward: { ko: "보디슈트", en: "Bodysuit" } },
            { number: 13, title: { ko: "C2", en: "C2" }, location: { ko: "챔피언 지구 남쪽, 장기 아저씨 구역 북서쪽", en: "South of Champion District, shogi guy's square northwest" }, reward: { ko: "티셔츠(레터링)", en: "T-Shirt (Lettering)" } },
            { number: 14, title: { ko: "D2", en: "D2" }, location: { ko: "W 쇼와 거리 스시긴 뒤 골목, 쓰레기통 옆", en: "Alleyway behind Sushi Gin on W Showa St, by dumpster" }, reward: { ko: "TONIGHT -restart from this night- 키류 CD", en: "TONIGHT -restart from this night- Kiryu CD" } },
            { number: 15, title: { ko: "E2", en: "E2" }, location: { ko: "E 타이헤이 대로 남쪽 주차장, 초록 유닛 뒤", en: "Car parking lot southern side E Taihei Blvd, behind green unit" }, reward: { ko: "Now or Never CD", en: "Now or Never CD" } },
            { number: 16, title: { ko: "F2", en: "F2" }, location: { ko: "천량 거리 하단 동쪽 도로, 엘리베이터 있는 골목", en: "Lower eastern road off Senryo Ave, alcove with elevator" }, reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" } },
            { number: 17, title: { ko: "G2", en: "G2" }, location: { ko: "핑크 골목 북쪽 끝 합류부, 흰 유닛", en: "Northern end of Pink Alley path convergence, white unit" }, reward: { ko: "Let Me See You Dancin' CD", en: "Let Me See You Dancin' CD" } },
            { number: 18, title: { ko: "H2", en: "H2" }, location: { ko: "핑크 골목과 천량 거리 남쪽 출구 합류부, 트럭 방수포 모서리", en: "Pink Alley meets Senryo Ave southern exit, tarp truck corner" }, reward: { ko: "화분 스트랩", en: "Pot Strap" } },
            { number: 19, title: { ko: "I2", en: "I2" }, location: { ko: "E 타이헤이 대로 코스튬 마니아 계단 왼쪽, 문 옆", en: "E Taihei Blvd left of Costume Mania stairs, by door" }, reward: { ko: "퍼피 스티커: 별(핑크)", en: "Puffy Sticker: Star (Pink)" } },
            { number: 20, title: { ko: "J2", en: "J2" }, location: { ko: "나카미치 거리 입구 계단, W 쇼와 거리 모서리 위쪽", en: "Nakamichi St Entrance stairs at W Showa St corner, top" }, reward: { ko: "청동 접시, 은 접시, 금 접시", en: "Bronze Plate, Silver Plate, Gold Plate" } },
            { number: 21, title: { ko: "A3", en: "A3" }, location: { ko: "천하일 골목 북쪽 골목, 북동쪽 에어컨 실외기 근처", en: "Alleyway north of Tenkaichi Alley, northeast corner AC units" }, reward: { ko: "퍼피 스티커: 물방울(스카이블루)", en: "Puffy Sticker: Waterdrop (Sky Blue)" } },
            { number: 22, title: { ko: "B3", en: "B3" }, location: { ko: "천하일 거리 입구 서쪽 건물 엘리베이터, 아래에서 두 번째", en: "Tenkaichi St Entrance western building elevator, second from bottom" }, reward: { ko: "반팔 셔츠(크로커다일)", en: "Short-Sleeve Button-Up (Crocodile)" } },
            { number: 23, title: { ko: "C3", en: "C3" }, location: { ko: "뉴 세레나 뒤편, 북서쪽 골목 파란 쓰레기통", en: "Behind New Serena, northwest alley corner, blue dumpster" }, reward: { ko: "Machine Gun Kiss (키류) CD", en: "Machine Gun Kiss (Kiryu) CD" } },
            { number: 24, title: { ko: "D3", en: "D3" }, location: { ko: "나카미치 골목 남쪽, 빨간 오토바이와 엘리베이터 문 모서리", en: "Red motorcycle and elevator door corner, south of Nakamichi Alley" }, reward: { ko: "긴팔 셔츠(골드)", en: "Long-Sleeve Button-Up (Gold)" } },
            { number: 25, title: { ko: "E3", en: "E3" }, location: { ko: "숏폰 거리 남쪽, 선샤인 매장 엘리베이터", en: "Suppon St southern side, Sunshine store elevator" }, reward: { ko: "특공복 버튼: 토쿠 x3", en: "Baddie Uniform Button: Toku x3" } },
            { number: 26, title: { ko: "F3", en: "F3" }, location: { ko: "극장 앞 광장 북서쪽 스마일버거 안, 문 오른쪽", en: "Inside Smile Burger NW Theater Square, right of door" }, reward: { ko: "정장(레오파드 무늬)", en: "Suit (Leopard Print)" } },
            { number: 27, title: { ko: "G3", en: "G3" }, location: { ko: "나카미치 거리 클럽 세가 뒤, 에비스 전당포 뒤 골목 북서쪽 출입구", en: "Alley behind Ebisu Pawn, behind Club SEGA on Nakamichi St, northwest doorway" }, reward: { ko: "North Star 사운드트랙 CD", en: "North Star Soundtrack CD" } },
            { number: 28, title: { ko: "H3", en: "H3" }, location: { ko: "E 타이헤이 대로 동쪽 끝, 빨간 정산기 옆 주차장", en: "E Taihei Blvd eastern end, car parking lot by red pay machine" }, reward: { ko: "노숄더 블레이저", en: "Shirtless Blazer" } },
            { number: 29, title: { ko: "I3", en: "I3" }, location: { ko: "호텔가 거리 동쪽 끝, 벽과 노란 간판 뒤 모서리", en: "Hotel District road eastern end, corner behind wall and yellow sign" }, reward: { ko: "퍼피 스티커: 물방울(그린)", en: "Puffy Sticker: Waterdrop (Green)" } },
            { number: 30, title: { ko: "J3", en: "J3" }, location: { ko: "챔피언 지구 북동쪽 모서리, 실크햇 간판 매장 앞", en: "Champion District northeast corner, outside top hat sign store" }, reward: { ko: "정장(도조 클랜 문장)", en: "Suit (Tojo Clan Crest)" } },
            { number: 31, title: { ko: "A4", en: "A4" }, location: { ko: "E 타이헤이 대로 인포메이션 스테이션 뒤, 큐슈 일등성 구역", en: "E Taihei Blvd Information Station store rear, Kyushu No. 1 Star area" }, reward: { ko: "스타디움 재킷", en: "Stadium Jacket" } },
            { number: 32, title: { ko: "B4", en: "B4" }, location: { ko: "E 시치후쿠 거리 북쪽 주차장, 안쪽 표지판 옆", en: "Parking lot north of E Shichifuku St, far end by sign" }, reward: { ko: "쌀 x3", en: "Rice x3" } },
            { number: 33, title: { ko: "C4", en: "C4" }, location: { ko: "룰라바이 마작 북서쪽 모서리, 천하일 거리 진입부", en: "Lullaby Mahjong northwest corner, Tenkaichi St access" }, reward: { ko: "정장 바지(레오파드 무늬)", en: "Suit Pants (Leopard Print)" } },
            { number: 34, title: { ko: "D4", en: "D4" }, location: { ko: "카무로초 남쪽 에비스 전당포 앞, 오토바이 옆", en: "In front of Ebisu Pawn southern Kamurocho, by motorcycle" }, reward: { ko: "Heartbeat CD", en: "Heartbeat CD" } },
            { number: 35, title: { ko: "E4", en: "E4" }, location: { ko: "E 쇼와 거리 르 마르쉐 오른쪽 아래 모서리", en: "Le Marche bottom right corner, E Showa St" }, reward: { ko: "카고 팬츠", en: "Cargo Pants" } },
            { number: 36, title: { ko: "F4", en: "F4" }, location: { ko: "핑크 거리 인포메이션 스테이션 택시 승강장 왼쪽 뒤편", en: "Information Station Pink St, left of taxi point, rear" }, reward: { ko: "트립스 양갱, 10-10-1 부적, 행운의 화투패, 규환 패", en: "Trips Yokan, 10-10-1 Charm, Lucky Hanafuda Card, Nine Gates Tile" } },
            { number: 37, title: { ko: "G4", en: "G4" }, location: { ko: "천량 거리 북쪽 끝 인포메이션 스테이션 뒤 오른쪽 모서리", en: "Information Station Senryo Ave northern end, back right corner" }, reward: { ko: "스네이크스킨 슈즈", en: "Snakeskin Shoes" } },
            { number: 38, title: { ko: "H4", en: "H4" }, location: { ko: "아카우시마루 남쪽 호텔가, 벽 뒤 엘리베이터 옆 빨간 매트", en: "South of Akaushimaru Hotel District, red mat by elevator behind wall" }, reward: { ko: "올원 부적, 123 껌, 피스마운틴 스톤, 짝짝이 고로 염주, 삐뚤어진 담배", en: "All 1's Charm, 1-2-3 Gum, Piss Mountain Stone, Even Goro's Beads, Lopsided Cigarette" } },
            { number: 39, title: { ko: "I4", en: "I4" }, location: { ko: "시치후쿠 거리 칸라이 건물 남서쪽 모서리, 메뉴판 아래", en: "Shichifuku St, Kanrai building southwestern corner below menu" }, reward: { ko: "손가락 없는 장갑", en: "Fingerless Gloves" } },
            { number: 40, title: { ko: "J4", en: "J4" }, location: { ko: "타이헤이 대로 인포메이션 스테이션, 긴다코 하이볼 주점 동쪽 뒤편", en: "Taihei Blvd Information Station, east of Gindaco Highball Tavern, rear" }, reward: { ko: "파인애플 x3", en: "Pineapple x3" } },
            { number: 41, title: { ko: "A5", en: "A5" }, location: { ko: "나카미치 거리 입구, 카페 알프스 위 노란 러브박스", en: "Nakamichi St Entrance, Love Box above Café Alps, yellow" }, reward: { ko: "갑옷, 전사 투구, 장갑", en: "Armor, Warrior Helmet, Gloves" } },
            { number: 42, title: { ko: "B5", en: "B5" }, location: { ko: "시치후쿠 거리에서 드래곤 팰리스로 가는 길, 파란 간판 위 노란 러브박스", en: "Road to Dragon Palace from Shichifuku St, Love Box on blue sign, yellow" }, reward: { ko: "마지마 건설 헬멧", en: "Majima Construction Helmet" } },
            { number: 43, title: { ko: "C5", en: "C5" }, location: { ko: "맥 볼 동쪽 건물, 네온 볼링핀 간판 옆 노란 러브박스", en: "Mach Bowl eastern building, Love Box by neon skittles sign, yellow" }, reward: { ko: "스네이크 안대", en: "Snake Eyepatch" } },
            { number: 44, title: { ko: "D5", en: "D5" }, location: { ko: "뉴 세레나 뒤 골목, 남쪽 벽 노란 러브박스", en: "Alley behind New Serena, Love Box southern wall, yellow" }, reward: { ko: "마지마 건설 헬멧 안테나", en: "Majima Construction Helmet Antenna" } },
            { number: 45, title: { ko: "E5", en: "E5" }, location: { ko: "천하일 거리 입구 남서쪽, 피터스 블렌드 위 노란 러브박스", en: "Tenkaichi St Entrance southwest Kamurocho, Love Box above Peter's Blend, yellow" }, reward: { ko: "게임 기어 스트랩", en: "Game Gear Strap" } },
            { number: 46, title: { ko: "F5", en: "F5" }, location: { ko: "나카미치 골목과 핑크 거리 합류부, 빨간 세로 간판 아래 노란 러브박스", en: "Nakamichi Alley meets Pink St, Love Box under red vertical sign, yellow" }, reward: { ko: "마지마 동상 스트랩", en: "Majima Statue Strap" } },
            { number: 47, title: { ko: "G5", en: "G5" }, location: { ko: "시치후쿠 거리와 E 밀레니엄 타워 거리 합류부, 빨간 벽돌 건물 노란 러브박스", en: "Shichifuku St meets E Millenium Tower St, Love Box red brick building, yellow" }, reward: { ko: "카무로초 잠금화면", en: "Kamurocho Lock Screen" } },
            { number: 48, title: { ko: "H5", en: "H5" }, location: { ko: "핑크 골목 하단 입구에서 천량 거리로, 왼쪽 노란 러브박스", en: "Pink Alley lower entrance to Senryo Ave, Love Box left side, yellow" }, reward: { ko: "24-hour CINDERELLA (마지마) CD", en: "24-hour CINDERELLA (Majima) CD" } },
            { number: 49, title: { ko: "I5", en: "I5" }, location: { ko: "E 타이헤이 대로에서 챔피언 지구로 가는 골목 동쪽, 위쪽 노란 러브박스", en: "Alleyway to Champion District from E Taihei Blvd, path east, Love Box above, yellow" }, reward: { ko: "Kamurocho Rhapsody (키류) CD", en: "Kamurocho Rhapsody (Kiryu) CD" } },
            { number: 50, title: { ko: "J5", en: "J5" }, location: { ko: "아카우시마루 맞은편 카무로초 북쪽, 빨간 건물 모서리 노란 러브박스", en: "North Kamurocho opposite Akaushimaru, Love Box red building corner, yellow" }, reward: { ko: "스티커: 디스코 마지마", en: "Sticker: Disco Majima" } },
          ],
        },
        {
          title: { ko: "다운타운 류큐 — 50개 열쇠", en: "Downtown Ryukyu — 50 Keys" },
          items: [
            { number: 1, title: { ko: "A1", en: "A1" }, location: { ko: "하츠마치 거리, 타마시로 파밀리 사무소 오른쪽 문 앞", en: "In front of a door to the right of the Tamashiro Family Office on Hatsumachi St." }, reward: { ko: "고급 동물 사료 x2", en: "Extra-Fancy Animal Feed x2" } },
            { number: 2, title: { ko: "B1", en: "B1" }, location: { ko: "아쿠아 스카이로 가는 엘리베이터 옆", en: "Beside the elevator leading to Aqua Sky" }, reward: { ko: "알로하 셔츠(트로피컬)", en: "Aloha Shirt (Tropical)" } },
            { number: 3, title: { ko: "C1", en: "C1" }, location: { ko: "오키나원 스테이크하우스 입구 오른쪽", en: "To the right of the entrance to The Original OkinaOne Steakhouse" }, reward: { ko: "골드 플레이트", en: "Gold Plate" } },
            { number: 4, title: { ko: "D1", en: "D1" }, location: { ko: "유시빈 거리 화분 두 개 사이", en: "Between two planters on Yushibin St." }, reward: { ko: "As Long as You're Happy (마지마) CD", en: "As Long as You're Happy (Majima) CD" } },
            { number: 5, title: { ko: "E1", en: "E1" }, location: { ko: "스마일버거(류큐 대로) 오른쪽", en: "To the right of Smile Burger (Ryukyu Blvd.)" }, reward: { ko: "스트로베리 안테나", en: "Strawberry Antenna" } },
            { number: 6, title: { ko: "F1", en: "F1" }, location: { ko: "공설시장 입구 바깥", en: "Outside the entrance to the Public Market" }, reward: { ko: "퍼피 스티커: 하트(스카이블루)", en: "Puffy Sticker: Heart (Sky Blue)" } },
            { number: 7, title: { ko: "G1", en: "G1" }, location: { ko: "카리유시 아케이드 추첨 부스 옆", en: "Next to the raffle booth in Kariyushi Arcade" }, reward: { ko: "Receive You CD", en: "Receive You CD" } },
            { number: 8, title: { ko: "H1", en: "H1" }, location: { ko: "아케이드 뒷골목, 흰색 양문 앞", en: "In the Arcade Rear Alley, in front of some white double doors" }, reward: { ko: "퍼피 스티커: 하트(그린)", en: "Puffy Sticker: Heart (Green)" } },
            { number: 9, title: { ko: "I1", en: "I1" }, location: { ko: "오키나원 스테이크하우스 안쪽 뒤편", en: "Near the back of the restaurant in The Original OkinaOne Steakhouse" }, reward: { ko: "고급 비료 x2", en: "Extra Fertilizer x2" } },
            { number: 10, title: { ko: "J1", en: "J1" }, location: { ko: "우마치이 내부 화분 앞", en: "In front of the pots inside of Umachii" }, reward: { ko: "탱크톱(제브라)", en: "Tank Top (Zebra)" } },
            { number: 11, title: { ko: "A2", en: "A2" }, location: { ko: "맵 서쪽, 파란 간판·빨간 꽃 로고 매장 밖", en: "Outside a store with a blue sign and red flower logo on western map side" }, reward: { ko: "블랙잭 부적, 버스트 부적, 로얄 조커 카드", en: "Blackjack Amulet, Bust Amulet, Royal Joker Card" } },
            { number: 12, title: { ko: "B2", en: "B2" }, location: { ko: "모노레일로 올라가는 엘리베이터 옆", en: "By the elevator leading up to where the monorail is" }, reward: { ko: "Otometal MY LIFE (하루카) CD", en: "Otometal MY LIFE (Haruka) CD" } },
            { number: 13, title: { ko: "C2", en: "C2" }, location: { ko: "포포(하츠마치) 북쪽 계단 앞", en: "In front of some stairs to the north of Poppo (Hatsumachi)" }, reward: { ko: "특상 낚싯밥 x2", en: "Outstanding Fish Bait x2" } },
            { number: 14, title: { ko: "D2", en: "D2" }, location: { ko: "카리유시 아케이드 입구 오른쪽", en: "At the entrance to Kariyushi Arcade, on the right side" }, reward: { ko: "정장(광택)", en: "Suit (Lustrous)" } },
            { number: 15, title: { ko: "E2", en: "E2" }, location: { ko: "카리유시 아케이드 마아상 주스 가판대 바로 앞", en: "Just outside of Maa-san's Juice stall in Kariyushi Arcade" }, reward: { ko: "청동 접시, 은 접시, 금 접시", en: "Bronze Plate, Silver Plate, Gold Plate" } },
            { number: 16, title: { ko: "F2", en: "F2" }, location: { ko: "오키나원 스테이크하우스 서쪽 계단 앞", en: "In front of the stairs on the western side of OkinaOne Steakhouse" }, reward: { ko: "우치나 키티캣 스트랩", en: "Uchina Kitty Kat Strap" } },
            { number: 17, title: { ko: "G2", en: "G2" }, location: { ko: "카리유시 아케이드, 빨간 시사 로고 매장 밖", en: "Outside of a store with a red shisa logo in Kariyushi Arcade" }, reward: { ko: "파인애플 x3", en: "Pineapple x3" } },
            { number: 18, title: { ko: "H2", en: "H2" }, location: { ko: "보관함 북쪽 지상층 엘리베이터 문 밖", en: "Outside of the elevator door on the ground level, north of where you can find the lockers" }, reward: { ko: "퍼피 스티커: 리본(그린)", en: "Puffy Sticker: Ribbon (Green)" } },
            { number: 19, title: { ko: "I2", en: "I2" }, location: { ko: "스마일버거(류큐 대로) 동쪽 내부", en: "Inside the Smile Burger (Ryukyu Blvd.) on the eastern side" }, reward: { ko: "퍼피 스티커: 리본(옐로우)", en: "Puffy Sticker: Ribbon (Yellow)" } },
            { number: 20, title: { ko: "J2", en: "J2" }, location: { ko: "프린트 클럽 동쪽, 히비스커스 아이스크림 오른쪽 골목", en: "East of the Print Club, in the alley to the right of Hibiscus Ice Cream" }, reward: { ko: "데님 재킷+티셔츠", en: "Denim Jacket with T-Shirt" } },
            { number: 21, title: { ko: "A3", en: "A3" }, location: { ko: "하츠마치 거리 모서리, 밝은 핑크 간판 매장 밖", en: "Outside of the store with the bright pink sign on the corner of Hatsumachi St." }, reward: { ko: "Pride From Despair (마지마&키류) CD", en: "Pride From Despair (Majima & Kiryu) CD" } },
            { number: 22, title: { ko: "B3", en: "B3" }, location: { ko: "S 쿠보치 로드 남쪽 골목의 우체통 앞", en: "In front of a mailbox in the little alley area south of S Kubochi Rd." }, reward: { ko: "정장 바지(광택)", en: "Suit Pants (Lustrous)" } },
            { number: 23, title: { ko: "C3", en: "C3" }, location: { ko: "우마치이 바로 남쪽, 셔터 앞", en: "In front of a store shutter just south of Umachii" }, reward: { ko: "레드 주얼, 블랙 주얼, 제로 주얼, 플레이어 패, 뱅커 패", en: "Red Jewel, Black Jewel, Zero Jewel, Player's Piece, Banker's Piece" } },
            { number: 24, title: { ko: "D3", en: "D3" }, location: { ko: "E 류큐 대로, 맵이 잘리는 지점 바로 옆", en: "Beside the road on E Ryukyu Blvd., right next to where the map cuts off" }, reward: { ko: "카고 반바지", en: "Cargo Shorts" } },
            { number: 25, title: { ko: "E3", en: "E3" }, location: { ko: "유시빈 거리 모서리, 유시빈 셀러 남쪽", en: "On the corner of Yushibin St., south of Yushibin Cellars" }, reward: { ko: "As a Man, As a Brother CD", en: "As a Man, As a Brother CD" } },
            { number: 26, title: { ko: "F3", en: "F3" }, location: { ko: "공설시장 동쪽, 매장 두 곳 사이 출입구 앞", en: "East of the Public Market, in front of a doorway between two stores" }, reward: { ko: "Fly CD", en: "Fly CD" } },
            { number: 27, title: { ko: "G3", en: "G3" }, location: { ko: "공설시장과 아케이드 뒷골목 사이 가스통 옆", en: "Next to some gas canisters in the alley between the Public Market and the Arcade Rear Alley" }, reward: { ko: "알로하 반바지(트로피컬)", en: "Aloha Shorts (Tropical)" } },
            { number: 28, title: { ko: "H3", en: "H3" }, location: { ko: "보관함 북쪽 지상층, 레스토랑 바로 앞", en: "On the ground level, north of where the lockers are, just in front of the restaurant" }, reward: { ko: "퍼피 스티커: 물방울(퍼플)", en: "Puffy Sticker: Waterdrop (Purple)" } },
            { number: 29, title: { ko: "I3", en: "I3" }, location: { ko: "포포(하츠마치) 남쪽 자판기 옆", en: "Beside a vending machine on the south side of Poppo (Hatsumachi)" }, reward: { ko: "퍼피 스티커: 물방울(핑크)", en: "Puffy Sticker: Waterdrop (Pink)" } },
            { number: 30, title: { ko: "J3", en: "J3" }, location: { ko: "류큐 중앙 고속도로·류큐 대로 모서리, 잡지꽂이 옆 문 앞", en: "In front of a door beside a magazine rack on the corner of Ryukyu Central Hwy. and Ryukyu Blvd." }, reward: { ko: "수영복 반바지(무지)", en: "Swimming Shorts (Plain)" } },
            { number: 31, title: { ko: "A4", en: "A4" }, location: { ko: "마작 캠프 옆 칸알그란데 바깥", en: "Outside the Canal Grande, which is next to Mahjong Camp" }, reward: { ko: "수영복 반바지(트로피컬)", en: "Swimming Shorts (Tropical)" } },
            { number: 32, title: { ko: "B4", en: "B4" }, location: { ko: "히비스커스 아이스크림(류큐) 북쪽 주차장 모서리", en: "In the corner of the parking lot area north of Hibiscus Ice Cream (Downtown Ryukyu)" }, reward: { ko: "스티커: 체리", en: "Sticker: Cherry" } },
            { number: 33, title: { ko: "C4", en: "C4" }, location: { ko: "츄라 바 위층, 우산꽂이 옆", en: "Upstairs in Chura Bar, beside the umbrella stand" }, reward: { ko: "정장 바지(레오파드 무늬)", en: "Suit Pants (Leopard Print)" } },
            { number: 34, title: { ko: "D4", en: "D4" }, location: { ko: "포포(류큐 대로) 밖 빨간 박스 위, 입구 왼쪽", en: "On top of the red box outside of Poppo (Ryukyu Blvd.), to the left of the entrance" }, reward: { ko: "에비에이터 선글라스", en: "Aviator Sunglasses" } },
            { number: 35, title: { ko: "E4", en: "E4" }, location: { ko: "공설시장 입구 서쪽 매장 앞", en: "In front of a store to the west of the Public Market entrance" }, reward: { ko: "보틀바텀 안경", en: "Bottle-Bottom Glasses" } },
            { number: 36, title: { ko: "F4", en: "F4" }, location: { ko: "우마치이 바로 오른쪽 셔터 앞", en: "In front of a store shutter just to the right of Umachii" }, reward: { ko: "Shin Ichizu Samurai (키류) CD", en: "Shin Ichizu Samurai (Kiryu) CD" } },
            { number: 37, title: { ko: "G4", en: "G4" }, location: { ko: "류큐 플라자 건물 앞, 도박장 약간 북쪽", en: "In front of a building in Ryukyu Plaza, just slightly north of the Gambling Hall" }, reward: { ko: "설탕 x3", en: "Sugar x3" } },
            { number: 38, title: { ko: "H4", en: "H4" }, location: { ko: "보관함 위층 엘리베이터 앞", en: "In front of the elevator on the upper level of where the lockers are" }, reward: { ko: "I Wanna Change Myself (하루카) CD", en: "I Wanna Change Myself (Haruka) CD" } },
            { number: 39, title: { ko: "I4", en: "I4" }, location: { ko: "류큐 대로 고인 마이 웨이 매장 밖", en: "Outside of the Goin' My Way store on Ryukyu Blvd." }, reward: { ko: "조개 스트랩(화이트)", en: "Shell Strap (White)" } },
            { number: 40, title: { ko: "J4", en: "J4" }, location: { ko: "E 류큐 대로 북쪽 건물 앞 기둥 뒤", en: "Behind a pillar in front of the building on the northern side of E Ryukyu Blvd." }, reward: { ko: "퍼피 스티커: 하트(옐로우)", en: "Puffy Sticker: Heart (Yellow)" } },
            { number: 41, title: { ko: "A5", en: "A5" }, location: { ko: "하츠마치 이나리 거리 서쪽, 노란 세로 간판 위 러브박스", en: "Yellow Love Box on a vertical yellow sign on the western side of the road on Inari St., Hatsumachi" }, reward: { ko: "보디슈트(류큐 카스리 무늬)", en: "Bodysuit (Ryukyu Kasuri Pattern)" } },
            { number: 42, title: { ko: "B5", en: "B5" }, location: { ko: "히비스커스 아이스크림(류큐) 건물 정면 러브박스", en: "Yellow Love Box on the front of the Hibiscus Ice Cream (Downtown Ryukyu) building" }, reward: { ko: "무술복", en: "Martial Arts Uniform" } },
            { number: 43, title: { ko: "C5", en: "C5" }, location: { ko: "하츠마치 이나리 거리 동쪽, OKXX 건물 러브박스", en: "Yellow Love Box on the OKXX building on the eastern side of the road on Inari St., Hatsumachi" }, reward: { ko: "숩빠이맨 코스튬·헬멧, 매실 아이템 컬렉션", en: "Suppai Man Costume, Helmet, Plum items collection" } },
            { number: 44, title: { ko: "D5", en: "D5" }, location: { ko: "S 쿠보치 로드 남쪽 건물 계단 옆 러브박스", en: "Yellow Love Box beside the stairs on the building south of S Kubochi Rd." }, reward: { ko: "정장(도지마 파밀리 문장)", en: "Suit (Dojima Family Crest)" } },
            { number: 45, title: { ko: "E5", en: "E5" }, location: { ko: "에비스 전당포 오른쪽 붉은 벽돌 건물 왼쪽 러브박스", en: "Yellow Love Box on the left side of the red brick building, to the right of Ebisu Pawn" }, reward: { ko: "Song of Departure -grandioso- CD", en: "Song of Departure -grandioso- CD" } },
            { number: 46, title: { ko: "F5", en: "F5" }, location: { ko: "류큐 플라자 벽 높은 곳 러브박스", en: "Yellow Love Box high up on the wall in Ryukyu Plaza" }, reward: { ko: "Pararirai (키류) CD", en: "Pararirai (Kiryu) CD" } },
            { number: 47, title: { ko: "G5", en: "G5" }, location: { ko: "류큐가이 댄스 스쿨 건물 러브박스", en: "Yellow Love Box on the building that houses the Ryukyugai Dance School" }, reward: { ko: "스네이크 자 안테나", en: "Snake Jar Antenna" } },
            { number: 48, title: { ko: "H5", en: "H5" }, location: { ko: "류큐 플라자 카지노·도박장 위 러브박스", en: "Yellow Love Box above the Casino and Gambling Hall in Ryukyu Plaza" }, reward: { ko: "카리유시 분짱 스트랩", en: "Kariyushi Bun-chan Strap" } },
            { number: 49, title: { ko: "I5", en: "I5" }, location: { ko: "카리유시 아케이드 입구 바로 위 러브박스", en: "Yellow Love Box just above the entrance to the Kariyushi Arcade" }, reward: { ko: "다운타운 류큐 잠금화면", en: "Downtown Ryukyu Lock Screen" } },
            { number: 50, title: { ko: "J5", en: "J5" }, location: { ko: "공설시장 입구 위 러브박스", en: "Yellow Love Box above the entrance to the Public Market" }, reward: { ko: "스티커: 디스코 키류", en: "Sticker: Disco Kiryu" } },
          ],
        },
      ],
    },
    {
      slug: "lalala-friends",
      title: { ko: "LaLaLa 프렌드 — 카무로초 60명 + 류큐 40명", en: "LaLaLa Friends — 60 Kamurocho + 40 Ryukyu" },
      summary: {
        ko: "휴대폰 검색 모드(L2)로 하트 아이콘이 뜬 NPC와 교류(R2)하면 친구가 됩니다. 100명 중 30명만 사귀면 「운명의 붉은 실」 업적이 발동합니다. 이름과 거리가 고정된 네임드 NPC라 매번 같은 자리에 있습니다.",
        en: "Use Search Mode (L2) to spot NPCs with a heart icon, then interact (R2) to befriend them. Only 30 of the 100 are needed for 'Fate's Fiery Filament'. These are fixed, named NPCs — always in the same spot.",
      },
      tips: [
        { ko: "카무로초의 라라 아이자와는 챕터 1에서 자동으로 첫 친구가 됩니다.", en: "Kamurocho's Lala Aizawa auto-unlocks as your first friend in Chapter 1." },
        { ko: "교류를 3회 반복하면 게이지가 가득 차 '러블리' 단계로 승급, 추가 보상을 받습니다.", en: "3 interactions fill the gauge and promote them to 'Lovely' tier for an extra reward." },
      ],
      source: [
        { label: "GameRant — LaLaLa Lovelies Friends Locations & Rewards", url: "https://gamerant.com/yakuza-kiwami-3-lalala-lovelies-friends-locations-rewards/" },
        { label: "TheGamer — LaLaLa Loveland Lovelies Friend Location & Rewards Guide", url: "https://www.thegamer.com/yakuza-kiwami-3-lalala-loveland-lovelies-friend-location-rewards-unlock-guide/" },
      ],
      groups: [
        {
          title: { ko: "카무로초 — 60명", en: "Kamurocho — 60 Friends" },
          items: [
            { number: 1, title: { ko: "라라 아이자와", en: "Lala Aizawa" }, location: { ko: "챕터 1 자동 해금", en: "Automatically unlocked in Chapter 1" } },
            { number: 2, title: { ko: "검객 요시오카", en: "Swordsman Yoshioka" }, location: { ko: "나카미치 거리", en: "Nakamichi St." } },
            { number: 3, title: { ko: "영웅적 은행원 카네모토", en: "Heroic Banker Kanemoto" }, location: { ko: "나카미치 거리", en: "Nakamichi St." } },
            { number: 4, title: { ko: "유연한 야마모토", en: "Flexible Yamamoto" }, location: { ko: "나카미치 거리", en: "Nakamichi St." } },
            { number: 5, title: { ko: "특수경비원 마모루", en: "Special Security Guard Mamoru" }, location: { ko: "나카미치 거리", en: "Nakamichi St." } },
            { number: 6, title: { ko: "사업가 이시카와", en: "Ishikawa the Businessman" }, location: { ko: "나카미치 거리", en: "Nakamichi St." } },
            { number: 7, title: { ko: "유명 미용사 하시즈메", en: "Well-Known Hairdresser Hashizume" }, location: { ko: "나카미치 거리", en: "Nakamichi St." } },
            { number: 8, title: { ko: "조용한 니시", en: "Quiet Nishi" }, location: { ko: "나카미치 거리", en: "Nakamichi St." } },
            { number: 9, title: { ko: "호객꾼 켄", en: "Ken the Barker" }, location: { ko: "핑크 거리", en: "Pink St." } },
            { number: 10, title: { ko: "눈이 흐릿한 도박꾼 요시다", en: "Blurry-Eyed Baller Yoshida" }, location: { ko: "핑크 거리", en: "Pink St." } },
            { number: 11, title: { ko: "뉴스캐스터 타마키", en: "Newscaster Tamaki" }, location: { ko: "핑크 거리", en: "Pink St." } },
            { number: 12, title: { ko: "카피라이터 나이토", en: "Copywriter Naito" }, location: { ko: "핑크 거리", en: "Pink St." } },
            { number: 13, title: { ko: "세심한 켄타", en: "Attentive Kenta" }, location: { ko: "천량 거리", en: "Senryo Ave." } },
            { number: 14, title: { ko: "초식남 아이코", en: "Herbivorous Aiko" }, location: { ko: "천량 거리", en: "Senryo Ave." } },
            { number: 15, title: { ko: "카메라맨 메구로", en: "Meguro the Cameraman" }, location: { ko: "천량 거리", en: "Senryo Ave." } },
            { number: 16, title: { ko: "클라이머 히무로", en: "Climber Himuro" }, location: { ko: "숏폰 거리", en: "Suppon St." } },
            { number: 17, title: { ko: "레트로 걸 레이코", en: "Retro Gal Reiko" }, location: { ko: "천하일 거리", en: "Tenkaichi St." } },
            { number: 18, title: { ko: "진실 추구자 히토츠바시", en: "Truth-Seeker Hitotsubashi" }, location: { ko: "천하일 거리", en: "Tenkaichi St." } },
            { number: 19, title: { ko: "기만적인 호스트 쿠로유메", en: "Deceptive Host Kuroyume" }, location: { ko: "천하일 거리", en: "Tenkaichi St." } },
            { number: 20, title: { ko: "겁 많은 직장인 오기", en: "Scaredy-Cat Worker Ogi" }, location: { ko: "천하일 거리", en: "Tenkaichi St." } },
            { number: 21, title: { ko: "바이커 노부오", en: "Biker Nobuo" }, location: { ko: "시치후쿠 거리", en: "Shicifuku St." } },
            { number: 22, title: { ko: "얼리버드 유미", en: "Yumi the Early Bird" }, location: { ko: "시치후쿠 거리", en: "Shicifuku St." } },
            { number: 23, title: { ko: "기타 소녀 아키", en: "Guitar Girl Aki" }, location: { ko: "시치후쿠 거리", en: "Shicifuku St." } },
            { number: 24, title: { ko: "열정적인 프리클러 히토미", en: "Passionate Purikurist Hitomi" }, location: { ko: "시치후쿠 거리", en: "Shicifuku St." } },
            { number: 25, title: { ko: "야구 감독 하라다", en: "Baseball Manager Harada" }, location: { ko: "시치후쿠 거리", en: "Shicifuku St." } },
            { number: 26, title: { ko: "부장 타케루", en: "Department Head Takeru" }, location: { ko: "시치후쿠 거리", en: "Shicifuku St." } },
            { number: 27, title: { ko: "흰 셔츠 애호가 시라이시", en: "Plain White Shirts Lover Shiraishi" }, location: { ko: "시치후쿠 거리", en: "Shicifuku St." } },
            { number: 28, title: { ko: "야구부원 니라사와", en: "Baseball Club Member Nirasawa" }, location: { ko: "시치후쿠 거리", en: "Shicifuku St." } },
            { number: 29, title: { ko: "쌍둥이 리카", en: "Twin Sister Rika" }, location: { ko: "극장 앞 광장", en: "Theater Square" } },
            { number: 30, title: { ko: "주부 사사오카", en: "Homemaker Sasaoka" }, location: { ko: "극장 앞 광장", en: "Theater Square" } },
            { number: 31, title: { ko: "일본사학자 오코시", en: "Okoshi, Japanese Historian" }, location: { ko: "극장 앞 광장", en: "Theater Square" } },
            { number: 32, title: { ko: "애완동물 하타케야마", en: "Hatakeyama the Pet" }, location: { ko: "극장 앞 광장", en: "Theater Square" } },
            { number: 33, title: { ko: "시소 점술가 햐카", en: "Seesaw Fortune Teller Hyakka" }, location: { ko: "극장 앞 광장", en: "Theater Square" } },
            { number: 34, title: { ko: "미소 후지사키", en: "Smiley Fujisaki" }, location: { ko: "극장 앞 광장", en: "Theater Square" } },
            { number: 35, title: { ko: "엔지니어 야나기바", en: "Engineer Yanagiba" }, location: { ko: "E 밀레니엄 타워 거리", en: "E Millennium Tower St." } },
            { number: 36, title: { ko: "음식 감별사 우레시노", en: "Food Tester Ureshino" }, location: { ko: "E 밀레니엄 타워 거리", en: "E Millennium Tower St." } },
            { number: 37, title: { ko: "인내심 있는 피에르", en: "Patient Pierre" }, location: { ko: "E 밀레니엄 타워 거리", en: "E Millennium Tower St." } },
            { number: 38, title: { ko: "컨시어지 마스오카", en: "Concierge Masuoka" }, location: { ko: "챔피언 지구", en: "Champion District" } },
            { number: 39, title: { ko: "펫 그루머 카노", en: "Pet Groomer Kano" }, location: { ko: "챔피언 지구", en: "Champion District" } },
            { number: 40, title: { ko: "코미디 만화가 히로타", en: "Comedy Manga Artist Hirota" }, location: { ko: "챔피언 지구", en: "Champion District" } },
            { number: 41, title: { ko: "바리스타 마메카와", en: "Mamekawa the Barista" }, location: { ko: "챔피언 지구", en: "Champion District" } },
            { number: 42, title: { ko: "다크 라이터 시노부", en: "Shinobu the Dark Writer" }, location: { ko: "챔피언 지구", en: "Champion District" } },
            { number: 43, title: { ko: "엉뚱한 예보관 야마세", en: "Fuzzy Forecaster Yamase" }, location: { ko: "타이헤이 대로", en: "Taihei Blvd." } },
            { number: 44, title: { ko: "특수효과 감독 마루야마", en: "Special Effects Director Maruyama" }, location: { ko: "타이헤이 대로", en: "Taihei Blvd." } },
            { number: 45, title: { ko: "인간 프레스기 오타", en: "Human Press Machine Ota" }, location: { ko: "타이헤이 대로", en: "Taihei Blvd." } },
            { number: 46, title: { ko: "전기기사 사이토", en: "Electrician Saito" }, location: { ko: "타이헤이 대로", en: "Taihei Blvd." } },
            { number: 47, title: { ko: "기계공 미사키", en: "Machinery Gal Misaki" }, location: { ko: "타이헤이 대로", en: "Taihei Blvd." } },
            { number: 48, title: { ko: "유사마 팬 요시에", en: "Yu-sama Lover Yoshie" }, location: { ko: "밀레니엄 타워", en: "Millennium Tower" } },
            { number: 49, title: { ko: "고귀한 팔라딘 키시", en: "Noble Paladin Kishi" }, location: { ko: "밀레니엄 타워", en: "Millennium Tower" } },
            { number: 50, title: { ko: "졸린 철도원 우에다", en: "Dozing Railroad Worker Ueda" }, location: { ko: "밀레니엄 타워", en: "Millennium Tower" } },
            { number: 51, title: { ko: "카페 사장 긴자키", en: "Café Owner Ginzaki" }, location: { ko: "밀레니엄 타워", en: "Millennium Tower" } },
            { number: 52, title: { ko: "인스턴트 미츠이", en: "Instant Mitsui" }, location: { ko: "밀레니엄 타워", en: "Millennium Tower" } },
            { number: 53, title: { ko: "초고속 배달원 하야미", en: "High-Speed Delivery Hayami" }, location: { ko: "호텔가", en: "Hotel District" } },
            { number: 54, title: { ko: "열혈 배우 타모", en: "Hardworking Actor Tamo" }, location: { ko: "호텔가", en: "Hotel District" } },
            { number: 55, title: { ko: "열정적인 경비원 이와타", en: "Enthusiastic Guard Iwata" }, location: { ko: "호텔가", en: "Hotel District" } },
            { number: 56, title: { ko: "덩치 큰 보육교사 마키", en: "Massive Daycare Worker Maki" }, location: { ko: "호텔가", en: "Hotel District" } },
            { number: 57, title: { ko: "럭키 원히트원더", en: "Lucky the One-Hit Wonder" }, location: { ko: "호텔가", en: "Hotel District" } },
            { number: 58, title: { ko: "수면부족 철도원 시모무라", en: "Sleep-Deprived Railway Worker Shimomura" }, location: { ko: "파크 대로", en: "Park Blvd." } },
            { number: 59, title: { ko: "다정한 시식원 야마오카", en: "Amorous Food Sampler Yamaoka" }, location: { ko: "파크 대로", en: "Park Blvd." } },
            { number: 60, title: { ko: "접수원 나츠메", en: "Receptionist Natsume" }, location: { ko: "파크 대로", en: "Park Blvd." } },
          ],
        },
        {
          title: { ko: "다운타운 류큐 — 40명", en: "Downtown Ryukyu — 40 Friends" },
          items: [
            { number: 1, title: { ko: "죽음을 부르는 타부치", en: "Deathbringer Tabuchi" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 2, title: { ko: "단 것 좋아하는 노조미", en: "Sweet Tooth Nozomi" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 3, title: { ko: "여행 가이드 타사키", en: "Vacation Guide Tasaki" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 4, title: { ko: "운전기사 사키", en: "Saki the Driver" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 5, title: { ko: "광견 나카타", en: "Rabid Nakata" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 6, title: { ko: "골퍼 하야마", en: "Golfer Hayama" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 7, title: { ko: "힐러 히메노", en: "Himeno the Healer" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 8, title: { ko: "당당한 야스오", en: "Assertive Yasuo" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 9, title: { ko: "시인 마사아키", en: "Masaaki the Poet" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 10, title: { ko: "애연가 하이자키", en: "Haizaki the Smoker" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 11, title: { ko: "고기 애호가 우시다", en: "Meat Lover Ushida" }, location: { ko: "류큐 대로", en: "Ryukyu Blvd." } },
            { number: 12, title: { ko: "폰 러버 린린", en: "Phone-Loving Rinrin" }, location: { ko: "유시빈 거리", en: "Yushibin St." } },
            { number: 13, title: { ko: "얼렁뚱땅 하시다", en: "Thrown-Together Hashida" }, location: { ko: "유시빈 거리", en: "Yushibin St." } },
            { number: 14, title: { ko: "버거남 마츠오모토", en: "Matsuomoto the Burger Guy" }, location: { ko: "유시빈 거리", en: "Yushibin St." } },
            { number: 15, title: { ko: "열정적인 가수 나나", en: "Passionate Crooner Nana" }, location: { ko: "카리유시 아케이드", en: "Kariyushi Arcade" } },
            { number: 16, title: { ko: "여주 애호가 가나하", en: "Goya Enthusiast Ganaha" }, location: { ko: "카리유시 아케이드", en: "Kariyushi Arcade" } },
            { number: 17, title: { ko: "귀농 호스티스 루카", en: "Homesteader Hostess Ruka" }, location: { ko: "카리유시 아케이드", en: "Kariyushi Arcade" } },
            { number: 18, title: { ko: "타워맨션 54층 스미다", en: "Tower Mansion 54th Floor Sumida" }, location: { ko: "아케이드 뒷골목", en: "Arcade Rear Alley" } },
            { number: 19, title: { ko: "스트리트 레이서 켄이치", en: "Street Racer Kenichi" }, location: { ko: "아케이드 뒷골목", en: "Arcade Rear Alley" } },
            { number: 20, title: { ko: "네일 아티스트 아케미", en: "Nail Artist Akemi" }, location: { ko: "아케이드 뒷골목", en: "Arcade Rear Alley" } },
            { number: 21, title: { ko: "백기 타테루", en: "White Flag Tateru" }, location: { ko: "공설시장", en: "Public Market" } },
            { number: 22, title: { ko: "스팽글 마스다", en: "Sequins Masuda" }, location: { ko: "공설시장", en: "Public Market" } },
            { number: 23, title: { ko: "건강식 노무라", en: "Conscious Eater Nomura" }, location: { ko: "공설시장", en: "Public Market" } },
            { number: 24, title: { ko: "난폭한 타다노", en: "Violent Tadano" }, location: { ko: "공설시장", en: "Public Market" } },
            { number: 25, title: { ko: "버섯 연구가 히라츠카", en: "Mushroom Researcher Hiratsuka" }, location: { ko: "공설시장", en: "Public Market" } },
            { number: 26, title: { ko: "잽촙 이나가키", en: "Zap-Chop Inagaki" }, location: { ko: "공설시장", en: "Public Market" } },
            { number: 27, title: { ko: "라멘 평론가 멘스케", en: "Ramen Critic Mensuke" }, location: { ko: "공설시장", en: "Public Market" } },
            { number: 28, title: { ko: "젊은 마작꾼 나카모토", en: "Young Mahjonger Nakamoto" }, location: { ko: "공설시장", en: "Public Market" } },
            { number: 29, title: { ko: "캔 연구가 모모코", en: "Can Researcher Momoko" }, location: { ko: "류큐 중앙 고속도로", en: "Ryukyu Central Hwy." } },
            { number: 30, title: { ko: "꽃집 오토리", en: "Otori the Florist" }, location: { ko: "류큐 중앙 고속도로", en: "Ryukyu Central Hwy." } },
            { number: 31, title: { ko: "배고픈 다이버 나기사", en: "Hungry Hungry Diver Nagisa" }, location: { ko: "류큐 중앙 고속도로", en: "Ryukyu Central Hwy." } },
            { number: 32, title: { ko: "밀랍인형 와쿠사베", en: "Waxwork Kusakabe" }, location: { ko: "류큐 중앙 고속도로", en: "Ryukyu Central Hwy." } },
            { number: 33, title: { ko: "도쿄사람 타이세이", en: "Taisei the Tokyoite" }, location: { ko: "쿠보치 로드", en: "Kubochi Rd." } },
            { number: 34, title: { ko: "아이언 마스크 킨조", en: "Iron Mask Kinjo" }, location: { ko: "쿠보치 로드", en: "Kubochi Rd." } },
            { number: 35, title: { ko: "파워 일러스트레이터 토도로키", en: "Power Illustrator Todoroki" }, location: { ko: "쿠보치 로드", en: "Kubochi Rd." } },
            { number: 36, title: { ko: "즉석 캐리커처 화가 야나우치", en: "Instantaneous Caricaturist Yanauchi" }, location: { ko: "하츠마치", en: "Hatsumachi" } },
            { number: 37, title: { ko: "이중 안경 하나시로", en: "Double Glass Hanashiro" }, location: { ko: "하츠마치", en: "Hatsumachi" } },
            { number: 38, title: { ko: "심판 아카가와", en: "Judgment Akagawa" }, location: { ko: "하츠마치", en: "Hatsumachi" } },
            { number: 39, title: { ko: "자극쟁이 타나하시", en: "Tanahashi the Stimulator" }, location: { ko: "하츠마치", en: "Hatsumachi" } },
            { number: 40, title: { ko: "두근두근 심호흡 마에다", en: "Doki Doki Deep Breaths Maeda" }, location: { ko: "하츠마치", en: "Hatsumachi" } },
          ],
        },
      ],
    },
    {
      slug: "clothing",
      title: { ko: "의상 수집 — 200종 이상", en: "Clothing Collection — 200+ Items" },
      summary: {
        ko: "머리·안경·메이크업·귀·상의·하의·아우터·손·발 9개 슬롯에 걸쳐 200종 이상의 의상이 있습니다. 「멋쟁이 대장」 업적은 50종만 모으면 발동됩니다. 상점 구매·미니게임 교환·코인로커/러브박스 보상·서브스토리·우호도 보상 등 여러 경로로 모입니다.",
        en: "200+ clothing pieces across 9 slots — head, eyewear, makeup, ear, upper body, lower body, outfit, hands, feet. 'Dapper Dragon' only needs 50. Items come from shop purchases, minigame exchanges, coin-locker/Love Box rewards, substories, and friendship-tier rewards.",
      },
      tips: [
        { ko: "위 코인로커·러브박스 목록에서 얻는 의상만 모아도 상당수를 채울 수 있습니다 (예: C4 정장 바지, A5 갑옷 세트 등).", en: "The coin-locker/Love Box list above alone yields a large chunk (e.g. C4 Suit Pants, the A5 armor set)." },
        { ko: "체인지룸에서는 아무 옷이나 저렴하게(800~2,000엔대) 구매 가능합니다.", en: "Any Changing Room sells basic pieces cheaply (roughly ¥800-2,000)." },
        { ko: "쥬얼리&스타일리(류큐)에서 귀 장신구·장갑류를, 도박장 상품 교환소에서 태그로 특수 의상을 교환할 수 있습니다.", en: "Jewelry & Styley (Ryukyu) sells ear accessories/gloves; the Gambling Hall prize exchange trades tags for specialty outfits." },
        { ko: "LaLaLa 프렌드를 75명까지 모으면 전용 신발이 보상으로 풀립니다.", en: "Reaching 75 LaLaLa Friends unlocks an exclusive pair of shoes as a reward." },
      ],
      source: { label: "TheGamer — Clothing Item Locations & Unlock Guide", url: "https://www.thegamer.com/yakuza-kiwami-3-clothing-item-locations-unlock-guide/" },
    },
  ],
};
