import type { CollectiblesData } from "./types";

export const yakuzaKiwami2: CollectiblesData = {
  appId: 3717340,
  categories: [
    {
      slug: "coin-lockers",
      title: { ko: "물품 보관함 — 양 도시 100개 열쇠와 보상", en: "Coin Lockers — All 100 Keys & Rewards (Both Cities)" },
      summary: {
        ko: "카무로초 50개 + 소텐보리 50개, 총 100개 코인로커 열쇠의 위치와 내용물을 정리했습니다. 보관함은 카무로초 타이헤이 거리·소텐보리 쇼후쿠초 서쪽에 있습니다. 지도의 번호가 카드 번호와 일치합니다.",
        en: "All 100 coin-locker keys (50 Kamurocho + 50 Sotenbori) with locations and contents. Map numbers match the card numbers.",
      },
      tips: [
        { ko: "거리·건물 바닥에서 반짝이는 곳을 조사하면 열쇠를 얻습니다. 「로커키 워처(E3)」를 입수하면 미니맵에 열쇠 위치가 표시됩니다.", en: "Investigate shining spots on the ground to get keys. The Locker Key Watcher (E3) marks keys on the minimap." },
      ],
      source: [
        { label: "ゲーム攻略マン — 龍が如く極2 神室町のコインロッカー", url: "https://dswiipspwikips3.jp/yakuza-kiwami2/cheats-data/kamurocho-coin-locker-keys.html" },
        { label: "ゲーム攻略マン — 龍が如く極2 蒼天堀のコインロッカー", url: "https://dswiipspwikips3.jp/yakuza-kiwami2/cheats-data/soutenbori-coin-locker-keys.html" },
        { label: "お家ゲーマー — 極2 コインロッカーのカギ探し in神室町 part.1", url: "https://home-gamer.com/2019/09/22/ryuugagotoku_kiwami2_coinlocker_kamurochou_part1/" },
        { label: "お家ゲーマー — 極2 コインロッカーのカギ探し in神室町 part.2", url: "https://home-gamer.com/2019/09/22/ryuugagotoku_kiwami2_coinlocker_kamurotyou_part2/" },
        { label: "お家ゲーマー — 極2 コインロッカーのカギ探し in神室町 part.3", url: "https://home-gamer.com/2019/10/05/ryuugagotoku_kiwami2_coinlocker_part3/" },
        { label: "お家ゲーマー — 極2 コインロッカーのカギ探し in神室町 part.4", url: "https://home-gamer.com/2019/10/05/ryuugagotoku_kiwami2_coinlocker_part4/" },
        { label: "お家ゲーマー — 極2 コインロッカーのカギ探し in神室町 part.5", url: "https://home-gamer.com/2019/10/05/ryuugagotoku_kiwami2_coinlocker_part5/" },
        { label: "お家ゲーマー — 極2 コインロッカーのカギ探し in蒼天堀 part.1", url: "https://home-gamer.com/2019/10/18/ryugagotoku_kiwami2_coinlocker_soutenbori_part1/" },
        { label: "Selphie1999Gaming — YK2 All Kamurocho Coin Locker Keys (video timestamps)", url: "https://selphie1999gaming.com/game-guides/yk2-yakuza-kiwami-2-all-kamurocho-coin-locker-key-locations-guide/" },
        { label: "Selphie1999Gaming — YK2 All Sotenbori Coin Locker Keys (video timestamps)", url: "https://selphie1999gaming.com/game-guides/yk2-yakuza-kiwami-2-all-sotenbori-coin-locker-key-locations-guide/" },
      ],
      groups: [
      {
        title: { ko: "카무로초 — 50개 열쇠", en: "Kamurocho — 50 Keys" },
        mapImage: "https://dswiipspwikips3-images.jp/yakuza-kiwami2/kamurocho-coin-locker-keys.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0",
        hotspots: {
          1: [85.4, 41.1], 2: [8.4, 60.7], 3: [94.1, 66.3], 4: [19.3, 76.9], 5: [58.6, 51.6], 6: [6.5, 18.6], 7: [21.5, 83.4], 8: [80.1, 35.5], 9: [51, 89.3], 10: [36.2, 74.7],
          11: [10.2, 18.6], 12: [50.5, 65.2], 13: [17.8, 57.3], 14: [12.1, 36.6], 15: [37.1, 44.7], 16: [13.4, 50.5], 17: [86.9, 65.9], 18: [35.7, 85.2], 19: [96.3, 26.6], 20: [50.5, 54],
          21: [50.1, 63.7], 22: [78.9, 48.1], 23: [28.6, 88.8], 24: [97.1, 61.3], 25: [87.7, 74], 26: [72.3, 89.1], 27: [57.7, 53.6], 28: [63.7, 75], 29: [75.5, 86.3], 30: [33.4, 31.7],
          31: [93.1, 72.1], 32: [24, 54.3], 33: [93.2, 89.2], 34: [35.1, 86], 35: [66.2, 81.6], 36: [44, 59.1], 37: [97.1, 37.6], 38: [77.8, 35.4], 39: [45.2, 22.1], 40: [91.3, 36.1],
          41: [42.2, 69.9], 42: [82.8, 27.3], 43: [58.9, 84.3], 44: [44.1, 53.3], 45: [51.8, 48.5], 46: [52.2, 81.6], 47: [67.8, 23.9], 48: [78, 73.6], 49: [50.4, 34.1], 50: [50.5, 39.8],
        },
        items: [
      {
        number: 1,
        title: { ko: "A1 · 1장", en: "A1 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_A-1-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=0s",
        location: { ko: "막다른 곳에 열쇠가 떨어져 있다", en: "Key at the dead end" },
        reward: { ko: "잭나이프", en: "Switchblade" },
      },
      {
        number: 2,
        title: { ko: "A2 · 1장", en: "A2 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAA2-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=41s",
        location: { ko: "「극장 앞 광장 뒤」 도로에 열쇠가 떨어져 있다", en: "Key on the road behind Theater Square" },
        reward: { ko: "살충제", en: "Insecticide" },
      },
      {
        number: 3,
        title: { ko: "A3 · 1장", en: "A3 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAA3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=68s",
        location: { ko: "쓰레기통 부근에 열쇠가 떨어져 있다", en: "Key near the trash bin" },
        reward: { ko: "스태미난 로열", en: "Staminan Royal" },
      },
      {
        number: 4,
        title: { ko: "A4 · 1장", en: "A4 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_A-4-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=101s",
        location: { ko: "넷카페 간판 근처에 열쇠가 떨어져 있다", en: "Key near the net cafe sign" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 5,
        title: { ko: "A5 · 1장", en: "A5 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_A-5-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=127s",
        location: { ko: "주차장 기둥 부근에 열쇠가 떨어져 있다", en: "Key near the parking pillar" },
        reward: { ko: "플래티넘 접시", en: "Platinum Plate" },
      },
      {
        number: 6,
        title: { ko: "B1 · 6장", en: "B1 · Ch.6" },
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=150s",
        location: { ko: "서브스토리 No.16 「비밀의 물건」 진행 중 입수", en: "From substory No.16 \"Secret Goods\"" },
        reward: { ko: "수상한 비디오", en: "Suspicious Video" },
      },
      {
        number: 7,
        title: { ko: "B2 · 1장", en: "B2 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_B-2-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=204s",
        location: { ko: "「세레나 뒤」 쓰레기통 근처에 열쇠가 떨어져 있다", en: "Key near the trash bin behind Serena" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 8,
        title: { ko: "B3 · 1장", en: "B3 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_B-3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=227s",
        location: { ko: "건물 4층 창가 부근에 열쇠가 떨어져 있다", en: "Key by the 4th-floor window inside the building" },
        reward: { ko: "전국 사슬갑주", en: "Sengoku Chainmail" },
      },
      {
        number: 9,
        title: { ko: "B4 · 1장", en: "B4 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_B-4-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=274s",
        location: { ko: "거리 도로에 열쇠가 떨어져 있다", en: "Key on the street road" },
        reward: { ko: "철 파이프", en: "Iron Pipe" },
      },
      {
        number: 10,
        title: { ko: "B5 · 1장", en: "B5 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_B-5-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=300s",
        location: { ko: "「천하일 거리 뒤」 구석 바닥에 열쇠가 떨어져 있다", en: "Key in the corner behind Tenkaichi St" },
        reward: { ko: "100파운드 마이볼", en: "100-Pound My Ball" },
      },
      {
        number: 11,
        title: { ko: "C1 · 5장", en: "C1 · Ch.5" },
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=330s",
        location: { ko: "서브스토리 No.9 「메일로 일하기」 진행 중 입수", en: "From substory No.9 \"Work by Email\"" },
        reward: { ko: "녹색 상자", en: "Green Box" },
      },
      {
        number: 12,
        title: { ko: "C2 · 1장", en: "C2 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_C-2-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=419s",
        location: { ko: "작은 지붕 기둥 밑동에 열쇠가 놓여 있다", en: "Key at the base of the small roof pillar" },
        reward: { ko: "스태미난 X", en: "Staminan X" },
      },
      {
        number: 13,
        title: { ko: "C3 · 1장", en: "C3 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_C-3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=446s",
        location: { ko: "간판 아래에 열쇠가 떨어져 있다", en: "Key under the sign" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 14,
        title: { ko: "C4 · 1장", en: "C4 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAC4-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=472s",
        location: { ko: "「아동 공원」 자판기 근처 바닥에 열쇠가 떨어져 있다", en: "Key by the children's park vending machine" },
        reward: { ko: "구리 접시", en: "Copper Plate" },
      },
      {
        number: 15,
        title: { ko: "C5 · 1장", en: "C5 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_C-5-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=500s",
        location: { ko: "교통 표지판 근처 도로에 열쇠가 떨어져 있다", en: "Key on the road near the traffic sign" },
        reward: { ko: "램프 스탠드", en: "Lamp Stand" },
      },
      {
        number: 16,
        title: { ko: "D1 · 1장", en: "D1 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_D-1-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=527s",
        location: { ko: "「뉴 텐포 시네마」 입구에 열쇠가 떨어져 있다", en: "Key at the New Tenpo Cinema entrance" },
        reward: { ko: "아라시의 양갱", en: "Arashi's Yokan" },
      },
      {
        number: 17,
        title: { ko: "D2 · 1장", en: "D2 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_D-2-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=548s",
        location: { ko: "스쿠터 근처에 열쇠가 떨어져 있다", en: "Key near the scooter" },
        reward: { ko: "빠루", en: "Crowbar" },
      },
      {
        number: 18,
        title: { ko: "D3 · 1장", en: "D3 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_D-3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=568s",
        location: { ko: "「제3공원」 바닥에 열쇠가 떨어져 있다", en: "Key on the Third Park ground" },
        reward: { ko: "터프니스 라이트", en: "Toughness Light" },
      },
      {
        number: 19,
        title: { ko: "D4 · 5장", en: "D4 · Ch.5" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAD4-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=596s",
        location: { ko: "카무로초 힐즈 건설 현장 구석 바닥에 열쇠가 떨어져 있다", en: "Key in the corner of the Kamurocho Hills site" },
        reward: { ko: "도싯핀즈", en: "Doshippins" },
      },
      {
        number: 20,
        title: { ko: "D5 · 8장", en: "D5 · Ch.8" },
        image: "https://home-gamer.com/wp-content/uploads/2019/09/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_D-5-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=643s",
        location: { ko: "밀레니엄 타워 1층 에스컬레이터 부근(서쪽). 메인 스토리 진행 후 진입 가능", en: "Millennium Tower 1F escalator (west); enter via story progress" },
        reward: { ko: "타우리너++", en: "Tauriner++" },
      },
      {
        number: 21,
        title: { ko: "E1 · 1장", en: "E1 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_E-1-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=683s",
        location: { ko: "벤치 근처 바닥에 열쇠가 떨어져 있다", en: "Key on the floor near the bench" },
        reward: { ko: "근육의 서", en: "Tome of Muscle" },
      },
      {
        number: 22,
        title: { ko: "E2 · 1장", en: "E2 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_E-2-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=707s",
        location: { ko: "「시치후쿠 파크」 간판 뒤에 열쇠가 떨어져 있다", en: "Key behind the Shichifuku Park sign" },
        reward: { ko: "샷건", en: "Shotgun" },
      },
      {
        number: 23,
        title: { ko: "E3 · 1장", en: "E3 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_E-3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=740s",
        location: { ko: "「천하일 거리」 도로에 열쇠가 떨어져 있다", en: "Key on Tenkaichi St road" },
        reward: { ko: "로커키 워처", en: "Locker Key Watcher" },
      },
      {
        number: 24,
        title: { ko: "E4 · 1장", en: "E4 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAE4-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=776s",
        location: { ko: "쓰레기통 부근에 열쇠가 떨어져 있다", en: "Key near the trash bin" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 25,
        title: { ko: "E5 · 1장", en: "E5 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_E-5-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=803s",
        location: { ko: "자판기 뒤쪽에 열쇠가 떨어져 있다", en: "Key behind the vending machine" },
        reward: { ko: "톤파", en: "Tonfa" },
      },
      {
        number: 26,
        title: { ko: "F1 · 1장", en: "F1 · Ch.1" },
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=826s",
        location: { ko: "통로 모퉁이에 열쇠가 떨어져 있다", en: "Key at the passage corner" },
        reward: { ko: "플래티넘 접시", en: "Platinum Plate" },
      },
      {
        number: 27,
        title: { ko: "F2 · 8장", en: "F2 · Ch.8" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190728223918-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=855s",
        location: { ko: "밀레니엄 타워 1층 에스컬레이터 부근(동쪽). 메인 스토리 진행 후 진입 가능", en: "Millennium Tower 1F escalator (east); enter via story progress" },
        reward: { ko: "스태미난 로열", en: "Staminan Royal" },
      },
      {
        number: 28,
        title: { ko: "F3 · 1장", en: "F3 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_F-3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=892s",
        location: { ko: "가스통 부근에 열쇠가 떨어져 있다", en: "Key near the gas cylinder" },
        reward: { ko: "금 접시", en: "Gold Plate" },
      },
      {
        number: 29,
        title: { ko: "F4 · 1장", en: "F4 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_F-1-1-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=915s",
        location: { ko: "쓰레기통 부근에 열쇠가 떨어져 있다", en: "Key near the trash bin" },
        reward: { ko: "유도봉", en: "Guide Baton" },
      },
      {
        number: 30,
        title: { ko: "F5 · 1장", en: "F5 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190728225433-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=943s",
        location: { ko: "「요시다 배팅센터」 지붕에 열쇠가 떨어져 있다. 정면 반대편 동쪽 계단으로 지붕에 오를 수 있다", en: "Key on the Yoshida Batting Center roof; climb via the east stairs" },
        reward: { ko: "개조 다리미", en: "Modified Iron" },
      },
      {
        number: 31,
        title: { ko: "G1 · 1장", en: "G1 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_G-1-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1003s",
        location: { ko: "택시 승차장 부근 도로에 열쇠가 떨어져 있다", en: "Key on the road near the taxi stand" },
        reward: { ko: "구리 접시", en: "Copper Plate" },
      },
      {
        number: 32,
        title: { ko: "G2 · 1장", en: "G2 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190728224759-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1027s",
        location: { ko: "「극장 앞 광장」 바닥에 열쇠가 떨어져 있다", en: "Key on the Theater Square ground" },
        reward: { ko: "투박한 복대", en: "Rugged Belly Wrap" },
      },
      {
        number: 33,
        title: { ko: "G3 · 1장", en: "G3 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAG3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1060s",
        location: { ko: "자전거 보관소에 열쇠가 떨어져 있다", en: "Key at the bicycle parking" },
        reward: { ko: "쇠몽둥이", en: "Iron Club" },
      },
      {
        number: 34,
        title: { ko: "G4 · 1장", en: "G4 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_G-4-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1084s",
        location: { ko: "건물 1층 통로 안쪽 화장실 근처 바닥에 열쇠가 떨어져 있다", en: "Key by the 1F restroom inside the building" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 35,
        title: { ko: "G5 · 1장", en: "G5 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_G-5-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1118s",
        location: { ko: "「무료 안내소」 바닥에 열쇠가 떨어져 있다", en: "Key on the info-center floor" },
        reward: { ko: "로열 조커", en: "Royal Joker" },
      },
      {
        number: 36,
        title: { ko: "H1 · 1장", en: "H1 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAH1-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1145s",
        location: { ko: "코인로커가 있는 곳 통로 안쪽에 열쇠가 떨어져 있다", en: "Key deep in the passage by the coin lockers" },
        reward: { ko: "스태미난 XX", en: "Staminan XX" },
      },
      {
        number: 37,
        title: { ko: "H2 · 1장", en: "H2 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_H-2-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1176s",
        location: { ko: "노숙자 텐트 근처에 열쇠가 떨어져 있다", en: "Key near the homeless tent" },
        reward: { ko: "싸움 사라시", en: "Brawler's Sarashi" },
      },
      {
        number: 38,
        title: { ko: "H3 · 1장", en: "H3 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_H-3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1194s",
        location: { ko: "건물 계단 층계참(2/3)에 열쇠가 떨어져 있다", en: "Key on the stair landing (2/3)" },
        reward: { ko: "경쾌 벨트", en: "Light Belt" },
      },
      {
        number: 39,
        title: { ko: "H4 · 1장", en: "H4 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_H-4-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1230s",
        location: { ko: "택시 승차장 근처 금속판 위에 열쇠가 떨어져 있다", en: "Key on the metal plate near the taxi stand" },
        reward: { ko: "터프니스 Z", en: "Toughness Z" },
      },
      {
        number: 40,
        title: { ko: "H5 · 1장", en: "H5 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_H-5-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1253s",
        location: { ko: "화장실 안 세면대 바닥에 열쇠가 떨어져 있다", en: "Key on the restroom sink floor" },
        reward: { ko: "행운 화투", en: "Lucky Hanafuda" },
      },
      {
        number: 41,
        title: { ko: "I1 · 1장", en: "I1 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAI3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1281s",
        location: { ko: "건물 안 바닥에 열쇠가 떨어져 있다", en: "Key on the floor inside the building" },
        reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" },
      },
      {
        number: 42,
        title: { ko: "I2 · 5장", en: "I2 · Ch.5" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAI2-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1306s",
        location: { ko: "카무로초 힐즈 건설 현장 경트럭 근처에 열쇠가 떨어져 있다", en: "Key near the kei-truck at the Kamurocho Hills site" },
        reward: { ko: "BJ의 부적", en: "BJ Charm" },
      },
      {
        number: 43,
        title: { ko: "I3 · 1장", en: "I3 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_I-3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1344s",
        location: { ko: "거리 도로에 열쇠가 떨어져 있다", en: "Key on the street road" },
        reward: { ko: "식탁 소금", en: "Table Salt" },
      },
      {
        number: 44,
        title: { ko: "I4 · 1장", en: "I4 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_I-4-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1365s",
        location: { ko: "피자 가게 근처 통로에 열쇠가 떨어져 있다", en: "Key in the passage near the pizza shop" },
        reward: { ko: "구리 접시", en: "Copper Plate" },
      },
      {
        number: 45,
        title: { ko: "I5 · 1장", en: "I5 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_I-5-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1396s",
        location: { ko: "벤치 근처에 열쇠가 떨어져 있다", en: "Key near the bench" },
        reward: { ko: "절연체 셔츠", en: "Insulator Shirt" },
      },
      {
        number: 46,
        title: { ko: "J1 · 1장", en: "J1 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_J-1-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1421s",
        location: { ko: "「무료 안내소」 바닥에 열쇠가 떨어져 있다", en: "Key on the info-center floor" },
        reward: { ko: "레더 브레스", en: "Leather Bracelet" },
      },
      {
        number: 47,
        title: { ko: "J2 · 5장", en: "J2 · Ch.5" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC%E7%A5%9E%E5%AE%A4%E7%94%BAJ2-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1445s",
        location: { ko: "카무로초 힐즈 건설 현장 구석 바닥에 열쇠가 떨어져 있다", en: "Key in the corner of the Kamurocho Hills site" },
        reward: { ko: "버스트의 부적", en: "Burst Charm" },
      },
      {
        number: 48,
        title: { ko: "J3 · 1장", en: "J3 · Ch.1" },
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1503s",
        location: { ko: "「타이헤이 거리 동쪽」 도로에 열쇠가 떨어져 있다", en: "Key on East Taihei Blvd road" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 49,
        title: { ko: "J4 · 4장", en: "J4 · Ch.4" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190728234739-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1526s",
        location: { ko: "서브스토리 No.22 「류구죠」 클리어 후 갈 수 있는 류구죠 3층 복도에 열쇠가 떨어져 있다", en: "Key in the Ryugujo 3F hall (after substory No.22)" },
        reward: { ko: "목발", en: "Crutch" },
      },
      {
        number: 50,
        title: { ko: "J5 · 1장", en: "J5 · Ch.1" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190728223602-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=8SHE0VK3ql0&t=1773s",
        location: { ko: "「무료 안내소」 안 바닥에 열쇠가 떨어져 있다", en: "Key inside the info center" },
        reward: { ko: "매력의 서", en: "Tome of Charm" },
      },
        ],
      },
      {
        title: { ko: "소텐보리 — 50개 열쇠", en: "Sotenbori — 50 Keys" },
        mapImage: "https://dswiipspwikips3-images.jp/yakuza-kiwami2/soutenbori-coin-locker-keys.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY",
        hotspots: {
          1: [28, 31.4], 2: [89.8, 47.7], 3: [81.1, 20.5], 4: [45.2, 73.5], 5: [4.1, 62.1], 6: [89.3, 34.5], 7: [57.4, 32.2], 8: [45.3, 30.5], 9: [41.1, 51.6], 10: [19.1, 62.3],
          11: [42.5, 84], 12: [13, 84.2], 13: [61.8, 48], 14: [48.6, 61.1], 15: [21, 65.1], 16: [68.1, 20.5], 17: [55, 36.7], 18: [22.4, 47.6], 19: [72.8, 43], 20: [44.3, 70.4],
          21: [85.1, 15.2], 22: [75.4, 35], 23: [33.4, 40.1], 24: [49.3, 49.6], 25: [56.7, 78.9], 26: [83.6, 36.2], 27: [61.5, 25.8], 28: [73.5, 39.6], 29: [30.1, 75.1], 30: [24.4, 94.1],
          31: [45.6, 40.5], 32: [22.3, 27.1], 33: [44.1, 20.3], 34: [36.8, 37.4], 35: [29.2, 39.8], 36: [16.6, 19.6], 37: [13.3, 61], 38: [52.7, 69.7], 39: [63.1, 41.7], 40: [28.8, 14.2],
          41: [22.3, 45.9], 42: [23.3, 96.7], 43: [58.9, 18.7], 44: [49.3, 28.9], 45: [30.9, 72.9], 46: [69.4, 29.1], 47: [26.6, 27.2], 48: [27.9, 47.6], 49: [86.7, 73.5], 50: [49.9, 51.8],
        },
        items: [
      {
        number: 1,
        title: { ko: "A1 · 2장", en: "A1 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190729214023-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=27s",
        location: { ko: "「비사몬교」 아래 통로에 열쇠가 떨어져 있다", en: "Key in the passage under Bishamon Bridge" },
        reward: { ko: "스태미난 XX", en: "Staminan XX" },
      },
      {
        number: 2,
        title: { ko: "A2 · 2장", en: "A2 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190729223604-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=61s",
        location: { ko: "택시 승차장 부근 바닥에 열쇠가 떨어져 있다", en: "Key near the taxi stand" },
        reward: { ko: "구리 접시", en: "Copper Plate" },
      },
      {
        number: 3,
        title: { ko: "A3 · 2장", en: "A3 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_%E8%92%BC%E5%A4%A9_A-3-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=93s",
        location: { ko: "아래로 내려가는 에스컬레이터 부근에 열쇠가 떨어져 있다", en: "Key near the down escalator" },
        reward: { ko: "환상의 톤파", en: "Phantom Tonfa" },
      },
      {
        number: 4,
        title: { ko: "A4 · 2장", en: "A4 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_%E8%92%BC%E5%A4%A9%E5%A0%80_A-4-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=128s",
        location: { ko: "건물 현관에 열쇠가 떨어져 있다", en: "Key at the building entrance" },
        reward: { ko: "펜치", en: "Pliers" },
      },
      {
        number: 5,
        title: { ko: "A5 · 2장", en: "A5 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_%E8%92%BC%E5%A4%A9%E5%A0%80_A-5-1024x576.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=168s",
        location: { ko: "통로 안쪽 막다른 바닥에 열쇠가 떨어져 있다", en: "Key at the dead-end floor inside the passage" },
        reward: { ko: "로열 조커", en: "Royal Joker" },
      },
      {
        number: 6,
        title: { ko: "B1 · 2장", en: "B1 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190729214415-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=205s",
        location: { ko: "「이와하시 다리」 아래 통로에 열쇠가 떨어져 있다", en: "Key in the passage under Iwa Bridge" },
        reward: { ko: "구식 오토 권총", en: "Old Auto Pistol" },
      },
      {
        number: 7,
        title: { ko: "B2 · 2장", en: "B2 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190729214205-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=236s",
        location: { ko: "「소텐보리 측도」 강가에 열쇠가 떨어져 있다", en: "Key along the river on Sotenbori Path" },
        reward: { ko: "아라시의 양갱", en: "Arashi's Yokan" },
      },
      {
        number: 8,
        title: { ko: "B3 · 2장", en: "B3 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190729214129-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=277s",
        location: { ko: "「소텐보리 측도」 강가 벤치 근처에 열쇠가 떨어져 있다", en: "Key near the riverside bench, Sotenbori Path" },
        reward: { ko: "메탈 글러브", en: "Metal Glove" },
      },
      {
        number: 9,
        title: { ko: "B4 · 2장", en: "B4 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190729215958-1024x581.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=312s",
        location: { ko: "돈키호테 앞 도로에 열쇠가 떨어져 있다", en: "Key on the road in front of Don Quijote" },
        reward: { ko: "검은 띠", en: "Black Belt" },
      },
      {
        number: 10,
        title: { ko: "B5 · 2장", en: "B5 · Ch.2" },
        image: "https://home-gamer.com/wp-content/uploads/2019/10/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F-%E6%A5%B5%EF%BC%92_20190729220112-1024x579.jpg",
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=348s",
        location: { ko: "건물 계단을 올라 가라오케 스낵 앞 층계참에 열쇠가 떨어져 있다", en: "Key on the landing in front of the karaoke snack" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 11,
        title: { ko: "C1 · 2장", en: "C1 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=393s",
        location: { ko: "가게 앞 현관 아래에 열쇠가 떨어져 있다", en: "Key below the shop entrance" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 12,
        title: { ko: "C2 · 2장", en: "C2 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=427s",
        location: { ko: "차 주차장에 열쇠가 떨어져 있다", en: "Key at the car park" },
        reward: { ko: "준민의 서", en: "Tome of Agility" },
      },
      {
        number: 13,
        title: { ko: "C3 · 2장", en: "C3 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=473s",
        location: { ko: "건물 진입을 막는 폴 아래에 열쇠가 떨어져 있다", en: "Key under the pole blocking the building" },
        reward: { ko: "기교의 서", en: "Tome of Technique" },
      },
      {
        number: 14,
        title: { ko: "C4 · 2장", en: "C4 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=512s",
        location: { ko: "도로에 열쇠가 떨어져 있다", en: "Key on the road" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 15,
        title: { ko: "C5 · 2장", en: "C5 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=551s",
        location: { ko: "가게 앞 도로에 열쇠가 떨어져 있다", en: "Key on the road in front of the shop" },
        reward: { ko: "팔각봉", en: "Octagonal Staff" },
      },
      {
        number: 16,
        title: { ko: "D1 · 2장", en: "D1 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=589s",
        location: { ko: "자전거 보관소에 열쇠가 떨어져 있다", en: "Key at the bicycle parking" },
        reward: { ko: "하라헤루 RX", en: "Harahel RX" },
      },
      {
        number: 17,
        title: { ko: "D2 · 2장", en: "D2 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=614s",
        location: { ko: "「소텐보리 측도」 강가에 열쇠가 떨어져 있다", en: "Key along the river on Sotenbori Path" },
        reward: { ko: "대신 돌", en: "Decoy Stone" },
      },
      {
        number: 18,
        title: { ko: "D3 · 2장", en: "D3 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=644s",
        location: { ko: "건물 내 계단을 오른 2층 실내에 열쇠가 떨어져 있다", en: "Key in the 2F room up the building stairs" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 19,
        title: { ko: "D4 · 2장", en: "D4 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=690s",
        location: { ko: "계단 아래 건물 현관에 열쇠가 떨어져 있다", en: "Key at the building entrance below the stairs" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 20,
        title: { ko: "D5 · 2장", en: "D5 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=727s",
        location: { ko: "건물 현관에 열쇠가 떨어져 있다", en: "Key at the building entrance" },
        reward: { ko: "경구", en: "Hardball" },
      },
      {
        number: 21,
        title: { ko: "E1 · 2장", en: "E1 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=769s",
        location: { ko: "「맹렬초 가부키 마츠리」 간판 아래 입구에 열쇠가 떨어져 있다", en: "Key at the entrance under the Kabuki Festival sign" },
        reward: { ko: "스태미난 XX", en: "Staminan XX" },
      },
      {
        number: 22,
        title: { ko: "E2 · 2장", en: "E2 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=801s",
        location: { ko: "「이와하시 다리」 중앙 바닥에 열쇠가 떨어져 있다", en: "Key on the center floor of Iwa Bridge" },
        reward: { ko: "하라헤루 하프", en: "Harahel Half" },
      },
      {
        number: 23,
        title: { ko: "E3 · 2장", en: "E3 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=830s",
        location: { ko: "「소텐보리 측도」 블록 쪽에 열쇠가 떨어져 있다", en: "Key by the block on Sotenbori Path" },
        reward: { ko: "BJ의 부적", en: "BJ Charm" },
      },
      {
        number: 24,
        title: { ko: "E4 · 2장", en: "E4 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=854s",
        location: { ko: "무료 안내소 간판 근처 도로에 열쇠가 떨어져 있다", en: "Key on the road near the info-center sign" },
        reward: { ko: "버스트의 부적", en: "Burst Charm" },
      },
      {
        number: 25,
        title: { ko: "E5 · 2장", en: "E5 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=886s",
        location: { ko: "막다른 도로에 열쇠가 떨어져 있다", en: "Key on the dead-end road" },
        reward: { ko: "도싯핀즈", en: "Doshippins" },
      },
      {
        number: 26,
        title: { ko: "F1 · 2장", en: "F1 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=936s",
        location: { ko: "「이와하시 다리」 아래 통로에 열쇠가 떨어져 있다", en: "Key in the passage under Iwa Bridge" },
        reward: { ko: "떡갈나무 목도", en: "Oak Bokken" },
      },
      {
        number: 27,
        title: { ko: "F2 · 2장", en: "F2 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=970s",
        location: { ko: "올라가는 에스컬레이터 부근 바닥에 열쇠가 떨어져 있다", en: "Key near the up escalator" },
        reward: { ko: "우도", en: "Cleaver" },
      },
      {
        number: 28,
        title: { ko: "F3 · 2장", en: "F3 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1000s",
        location: { ko: "「소텐보리 측도」로 내려가는 계단에 열쇠가 떨어져 있다", en: "Key on the stairs down to Sotenbori Path" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 29,
        title: { ko: "F4 · 2장", en: "F4 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1029s",
        location: { ko: "건물 계단을 올라 4층(옥상) 골포스트에 열쇠가 떨어져 있다", en: "Key at the 4F (roof) goalpost" },
        reward: { ko: "전기포트", en: "Electric Kettle" },
      },
      {
        number: 30,
        title: { ko: "F5 · 2장", en: "F5 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1083s",
        location: { ko: "카지노행 지하 계단을 내려간 곳에 열쇠가 떨어져 있다", en: "Key down the basement stairs toward the casino" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 31,
        title: { ko: "G1 · 2장", en: "G1 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1119s",
        location: { ko: "「소텐보리 측도」 블록 쪽에 열쇠가 떨어져 있다", en: "Key by the block on Sotenbori Path" },
        reward: { ko: "금 접시", en: "Gold Plate" },
      },
      {
        number: 32,
        title: { ko: "G2 · 2장", en: "G2 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1147s",
        location: { ko: "건물 내 남자 화장실에 열쇠가 떨어져 있다", en: "Key in the building men's restroom" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
      },
      {
        number: 33,
        title: { ko: "G3 · 2장", en: "G3 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1178s",
        location: { ko: "벤치 아래에 열쇠가 떨어져 있다", en: "Key under the bench" },
        reward: { ko: "스태미난 로열", en: "Staminan Royal" },
      },
      {
        number: 34,
        title: { ko: "G4 · 2장", en: "G4 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1203s",
        location: { ko: "비사몬교 선착장 아래에 열쇠가 떨어져 있다", en: "Key under the Bishamon Bridge dock" },
        reward: { ko: "터프니스 Z", en: "Toughness Z" },
      },
      {
        number: 35,
        title: { ko: "G5 · 2장", en: "G5 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1229s",
        location: { ko: "계단 아래 블록 쪽에 열쇠가 떨어져 있다", en: "Key by the block below the stairs" },
        reward: { ko: "특수 경봉", en: "Special Baton" },
      },
      {
        number: 36,
        title: { ko: "H1 · 2장", en: "H1 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1252s",
        location: { ko: "관엽식물 뒤편 바닥에 열쇠가 떨어져 있다", en: "Key on the floor behind the houseplant" },
        reward: { ko: "스태미난 Z", en: "Staminan Z" },
      },
      {
        number: 37,
        title: { ko: "H2 · 2장", en: "H2 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1284s",
        location: { ko: "건물 안쪽으로 이어지는 통로에 열쇠가 떨어져 있다", en: "Key in the passage leading deeper into the building" },
        reward: { ko: "피녹 사슬갑주", en: "Bloodrust Chainmail" },
      },
      {
        number: 38,
        title: { ko: "H3 · 2장", en: "H3 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1311s",
        location: { ko: "계단 아래 화단 근처에 열쇠가 떨어져 있다", en: "Key near the planter below the stairs" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 39,
        title: { ko: "H4 · 2장", en: "H4 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1343s",
        location: { ko: "타코야키 가게 부근 바닥에 열쇠가 떨어져 있다", en: "Key near the takoyaki stand" },
        reward: { ko: "개조 버너", en: "Modified Burner" },
      },
      {
        number: 40,
        title: { ko: "H5 · 2장", en: "H5 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1374s",
        location: { ko: "진입 금지 간판 근처 바닥에 열쇠가 떨어져 있다", en: "Key near the no-entry sign" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 41,
        title: { ko: "I1 · 2장", en: "I1 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1402s",
        location: { ko: "건물 내 계단 층계참에 열쇠가 떨어져 있다", en: "Key on the building stair landing" },
        reward: { ko: "스태미난 X", en: "Staminan X" },
      },
      {
        number: 42,
        title: { ko: "I2 · 2장", en: "I2 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1435s",
        location: { ko: "카지노 앞 복도 골판지 부근에 열쇠가 떨어져 있다", en: "Key by the cardboard in the casino hallway" },
        reward: { ko: "청룡도", en: "Blue-Dragon Blade" },
      },
      {
        number: 43,
        title: { ko: "I3 · 2장", en: "I3 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1482s",
        location: { ko: "「간코 스시」 가게 앞 바닥에 열쇠가 떨어져 있다", en: "Key in front of Ganko Sushi" },
        reward: { ko: "터프니스 라이트", en: "Toughness Light" },
      },
      {
        number: 44,
        title: { ko: "I4 · 2장", en: "I4 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1508s",
        location: { ko: "「소텐보리 측도」 셔터 부근 바닥에 열쇠가 떨어져 있다", en: "Key by the shutter on Sotenbori Path" },
        reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" },
      },
      {
        number: 45,
        title: { ko: "I5 · 2장", en: "I5 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1537s",
        location: { ko: "도박장행 복도에 열쇠가 떨어져 있다", en: "Key in the hall toward the gambling den" },
        reward: { ko: "행운 화투", en: "Lucky Hanafuda" },
      },
      {
        number: 46,
        title: { ko: "J1 · 2장", en: "J1 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1569s",
        location: { ko: "계단 아래 거리에 열쇠가 떨어져 있다", en: "Key on the street below the stairs" },
        reward: { ko: "개조 화로", en: "Modified Stove" },
      },
      {
        number: 47,
        title: { ko: "J2 · 2장", en: "J2 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1601s",
        location: { ko: "자판기 앞 테이블 아래에 열쇠가 떨어져 있다", en: "Key under the table in front of the vending machine" },
        reward: { ko: "군용 방탄조끼", en: "Military Bulletproof Vest" },
      },
      {
        number: 48,
        title: { ko: "J3 · 2장", en: "J3 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1626s",
        location: { ko: "차 주차장에 열쇠가 떨어져 있다", en: "Key at the car park" },
        reward: { ko: "근성의 서", en: "Tome of Guts" },
      },
      {
        number: 49,
        title: { ko: "J4 · 10장", en: "J4 · Ch.10" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1656s",
        location: { ko: "서브스토리 No.47 「원한 대행」 클리어 보상으로 받는다", en: "Reward from clearing substory No.47" },
        reward: { ko: "플래티넘 접시", en: "Platinum Plate" },
      },
      {
        number: 50,
        title: { ko: "J5 · 2장", en: "J5 · Ch.2" },
        video: "https://www.youtube.com/watch?v=oOjdzCDuFLY&t=1712s",
        location: { ko: "건물 계단 근처에 열쇠가 떨어져 있다", en: "Key near the building stairs" },
        reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" },
      },
        ],
      },
      ],
    },
    {
      slug: "encounter-bosses",
      title: { ko: "인카운트 보스 — 카무로초 & 소텐보리 18인", en: "Encounter Bosses — All 18 Street Bosses (Both Cities)" },
      summary: {
        ko: "제5장 사야마에게 물품 전달 후 해금되는 인카운트 보스. 각 도시마다 야쿠자·양아치·불량배 계열로 3명씩 이어지는 보스 체인이 3개(총 9명)씩 존재합니다. 전원 격파 시 오의 「트리플 스웨이」를 습득할 수 있습니다.",
        en: "Street-encounter bosses, unlocked after delivering the item to Sayama in Chapter 5. Each city has three 3-boss chains (Yakuza / Delinquent / Thug lineage, 9 bosses total). Beating all of them unlocks the Triple Sway heat move.",
      },
      tips: [
        { ko: "각 계열 첫 보스는 해당 잡몹(야쿠자/양아치/불량배)을 5회 격파하면 메일로 인카운트 위치 안내를 받습니다.", en: "Beat the linked mob type (Yakuza/Delinquent/Thug) 5 times to get an email pointing to the first boss in each chain." },
        { ko: "체인의 다음 보스는 이전 보스 격파 후 같은 잡몹을 5회 더 격파해야 등장합니다.", en: "The next boss in a chain appears after beating the previous boss plus 5 more fights against the same mob type." },
        { ko: "야쿠자 타입은 등장 빈도가 낮으므로 지도의 Ⓑ 표시가 많은 구역에서 컨텐츠 초반부터 노리는 편이 좋습니다. 카무로초는 밀레니엄 타워 동·서 통과 루트, 소텐보리는 야쿠자·불량배는 동쪽, 양아치는 서쪽에서 잘 나옵니다.", en: "Yakuza-type mobs spawn rarely, so target areas marked Ⓑ on the map early. In Kamurocho, crossing east-west through Millennium Tower helps; in Sotenbori, Yakuza/Thugs favor the east side and Delinquents the west." },
      ],
      source: [
        { label: "funkygame — Yakuza Kiwami 2 encounter bosses", url: "https://funkygame.tistory.com/2026" },
        { label: "ゲーム攻略マン — 龍が如く極2 エンカウントボス", url: "https://dswiipspwikips3.jp/yakuza-kiwami2/cheats-data/encount-bosses.html" },
      ],
      groups: [
        {
          title: { ko: "카무로초 — 9인", en: "Kamurocho — 9 Bosses" },
          mapImage: "/yakuza-kiwami-2-encounter-bosses/kamurocho.jpg",
          legend: [
            { marker: "Ⓐ", label: { ko: "チンピラ = 양아치", en: "チンピラ = Delinquent" } },
            { marker: "Ⓑ", label: { ko: "ヤクザ = 야쿠자", en: "ヤクザ = Yakuza" } },
            { marker: "Ⓒ", label: { ko: "チーマー = 불량배", en: "チーマー = Thug" } },
          ],
          hotspots: {
            1: [66, 35.9], 2: [65.1, 88.6], 3: [23.4, 75.8], 4: [12.8, 37.2], 5: [34.1, 22.6],
            6: [77.2, 95.3], 7: [79.5, 61.7], 8: [23.7, 40.9], 9: [88.3, 74.4],
          },
          items: [
            {
              number: 1,
              title: { ko: "매드 나타기리", en: "Mad Natagiri" },
              location: { ko: "야쿠자 5회 격파 후 등장", en: "Appears after beating Yakuza mobs 5×" },
              mail: { ko: "위험한 녀석", en: "Dangerous Guy" },
              reward: { ko: "중식칼", en: "Chinese Cleaver" },
            },
            {
              number: 2,
              title: { ko: "파이어 카라사와", en: "Fire Karasawa" },
              location: { ko: "매드 나타기리 격파 + 야쿠자 5회 격파", en: "Beat Mad Natagiri + 5 more Yakuza fights" },
              mail: { ko: "신세대 야쿠자", en: "New-Generation Yakuza" },
              reward: { ko: "개조 모델건", en: "Modified Model Gun" },
            },
            {
              number: 3,
              title: { ko: "갓 겐조", en: "God Genzo" },
              location: { ko: "파이어 카라사와 격파 + 야쿠자 5회 격파", en: "Beat Fire Karasawa + 5 more Yakuza fights" },
              mail: { ko: "도지마의 용에게", en: "To the Dragon of Dojima" },
              reward: { ko: "쇠망치, 마지마 건설 스카우트", en: "Sledgehammer, Majima Construction scout" },
            },
            {
              number: 4,
              title: { ko: "복서 후지키", en: "Boxer Fujiki" },
              location: { ko: "양아치 5회 격파 후 등장", en: "Appears after beating Delinquent mobs 5×" },
              mail: { ko: "실력자 출현", en: "A Skilled Fighter Appears" },
              reward: { ko: "너클 더스터, 마지마 건설 스카우트", en: "Knuckle Duster, Majima Construction scout" },
            },
            {
              number: 5,
              title: { ko: "머슬 후지키", en: "Muscle Fujiki" },
              location: { ko: "복서 후지키 격파 + 양아치 5회 격파", en: "Beat Boxer Fujiki + 5 more Delinquent fights" },
              mail: { ko: "또 다른 실력자", en: "Another Skilled Fighter" },
              reward: { ko: "스턴 그레네이드, 마지마 건설 스카우트", en: "Stun Grenade, Majima Construction scout" },
            },
            {
              number: 6,
              title: { ko: "앰부쉬 쿠로사와", en: "Ambush Kurosawa" },
              location: { ko: "머슬 후지키 격파 + 양아치 5회 격파", en: "Beat Muscle Fujiki + 5 more Delinquent fights" },
              mail: { ko: "불의의 습격", en: "Surprise Attack" },
              reward: { ko: "조장의 배트", en: "Foreman's Bat" },
            },
            {
              number: 7,
              title: { ko: "데들리 후키시마", en: "Deadly Fukishima" },
              location: { ko: "불량배 5회 격파 후 등장", en: "Appears after beating Thug mobs 5×" },
              mail: { ko: "불량클럽", en: "Delinquent Club" },
              reward: { ko: "톱, 마지마 건설 스카우트", en: "Saw, Majima Construction scout" },
            },
            {
              number: 8,
              title: { ko: "편의점 사냥꾼 사이토", en: "Convenience Store Hunter Saito" },
              location: { ko: "데들리 후키시마 격파 + 불량배 5회 격파", en: "Beat Deadly Fukishima + 5 more Thug fights" },
              mail: { ko: "편의점 사냥꾼", en: "Convenience Store Hunter" },
              reward: { ko: "고압 전기충격기", en: "High-Voltage Stun Gun" },
            },
            {
              number: 9,
              title: { ko: "사무라이 가면", en: "Samurai Mask" },
              location: { ko: "편의점 사냥꾼 사이토 격파 + 불량배 5회 격파", en: "Beat Convenience Store Hunter Saito + 5 more Thug fights" },
              mail: { ko: "사무라이", en: "Samurai" },
              reward: { ko: "신수의 목도", en: "Divine Beast Bokken" },
            },
          ],
        },
        {
          title: { ko: "소텐보리 — 9인", en: "Sotenbori — 9 Bosses" },
          mapImage: "/yakuza-kiwami-2-encounter-bosses/sotenbori.jpg",
          legend: [
            { marker: "Ⓐ", label: { ko: "チンピラ = 양아치", en: "チンピラ = Delinquent" } },
            { marker: "Ⓑ", label: { ko: "ヤクザ = 야쿠자", en: "ヤクザ = Yakuza" } },
            { marker: "Ⓒ", label: { ko: "チーマー = 불량배", en: "チーマー = Thug" } },
          ],
          hotspots: {
            1: [24.4, 80.1], 2: [31.2, 87.9], 3: [5.1, 69.4], 4: [82.4, 17.5], 5: [26.1, 34.5],
            6: [73.8, 35.3], 7: [41.9, 88.4], 8: [18.6, 67], 9: [34.2, 20.7],
          },
          items: [
            {
              number: 1,
              title: { ko: "수수께끼의 암살자", en: "Mysterious Assassin" },
              location: { ko: "야쿠자 5회 격파 후 등장", en: "Appears after beating Yakuza mobs 5×" },
              mail: { ko: "자객", en: "Assassin" },
              reward: { ko: "흑자수의 목도", en: "Black Embroidered Bokken" },
            },
            {
              number: 2,
              title: { ko: "피바람 츠지모토", en: "Blood-Rain Tsujimoto" },
              location: { ko: "수수께끼의 암살자 격파 + 야쿠자 5회 격파", en: "Beat Mysterious Assassin + 5 more Yakuza fights" },
              mail: { ko: "피바람", en: "Bloodbath" },
              reward: { ko: "섬광탄, 마지마 건설 스카우트", en: "Flashbang, Majima Construction scout" },
            },
            {
              number: 3,
              title: { ko: "금색의 가네모토", en: "Golden Kanemoto" },
              location: { ko: "피바람 츠지모토 격파 + 야쿠자 5회 격파", en: "Beat Blood-Rain Tsujimoto + 5 more Yakuza fights" },
              mail: { ko: "금색의", en: "The Golden One" },
              reward: { ko: "닌자 단도", en: "Ninja Dagger" },
            },
            {
              number: 4,
              title: { ko: "위타천 나가부치", en: "Fleet-Footed Nagabuchi" },
              location: { ko: "양아치 5회 격파 후 등장", en: "Appears after beating Delinquent mobs 5×" },
              mail: { ko: "실력 테스트", en: "Skill Test" },
              reward: { ko: "긴 단도, 마지마 건설 스카우트", en: "Long Dagger, Majima Construction scout" },
            },
            {
              number: 5,
              title: { ko: "무기 사냥꾼 사쿄", en: "Weapon Hunter Sakyo" },
              location: { ko: "위타천 나가부치 격파 + 양아치 5회 격파", en: "Beat Fleet-Footed Nagabuchi + 5 more Delinquent fights" },
              mail: { ko: "무기 사냥꾼", en: "Weapon Hunter" },
              reward: { ko: "이름 없는 검", en: "Nameless Sword" },
            },
            {
              number: 6,
              title: { ko: "다리 파수꾼 우쿄", en: "Bridge Guardian Ukyo" },
              location: { ko: "무기 사냥꾼 사쿄 격파 + 양아치 5회 격파", en: "Beat Weapon Hunter Sakyo + 5 more Delinquent fights" },
              mail: { ko: "돌다리에서", en: "At the Stone Bridge" },
              reward: { ko: "쌍룡의 북채, 마지마 건설 스카우트", en: "Twin Dragon Drumsticks, Majima Construction scout" },
            },
            {
              number: 7,
              title: { ko: "강격의 나가사와", en: "Heavy-Strike Nagasawa" },
              location: { ko: "불량배 5회 격파 후 등장", en: "Appears after beating Thug mobs 5×" },
              mail: { ko: "싸움 중독자", en: "Fight Addict" },
              reward: { ko: "지렛대, 마지마 건설 스카우트", en: "Crowbar, Majima Construction scout" },
            },
            {
              number: 8,
              title: { ko: "파괴자 미네기시", en: "Destroyer Minegishi" },
              location: { ko: "강격의 나가사와 격파 + 불량배 5회 격파", en: "Beat Heavy-Strike Nagasawa + 5 more Thug fights" },
              mail: { ko: "파괴자", en: "Destroyer" },
              reward: { ko: "더블 스타이커", en: "Double Stryker" },
            },
            {
              number: 9,
              title: { ko: "철권 사카이", en: "Iron Fist Sakai" },
              location: { ko: "파괴자 미네기시 격파 + 불량배 5회 격파", en: "Beat Destroyer Minegishi + 5 more Thug fights" },
              mail: { ko: "강한 녀석", en: "Tough Guy" },
              reward: { ko: "특제 특수 경찰봉", en: "Custom Special Baton" },
            },
          ],
        },
      ],
    },
    {
      slug: "videos",
      title: { ko: "비디오 마니아 — 본편 비디오 15편 전부 시청", en: "Video Maniac — Watch All 15 Videos" },
      summary: {
        ko: "개인실 비디오 가게(카무로초 「퓨전」, 소텐보리 「간다라」)에서 15편을 한 번씩 시청하면 「비디오 마니아」 업적이 발동합니다. 입장료는 2편에 1,000엔이며, 3편은 처음부터 보유하고 나머지 12편은 빔과 웍스 카미야마에서 각 2,800엔에 구입합니다. 카미야마의 비디오는 서브스토리 No.24 「무기 비디오 상인」을 클리어해야 팔기 시작하니 이것부터 처리할 것.",
        en: "Watch all 15 at a private video booth — Fusion in Kamurocho or Gandhara in Sotenbori — to unlock 'Video Maniac'. A booth costs ¥1,000 for two videos. Three are in your stock from the start; the other twelve are ¥2,800 each from Beam and from Kamiyama, who only starts selling once substory No.24 'Weapon Video Merchant' is cleared, so do that first.",
      },
      tips: [
        { ko: "두 편은 시청만으로 능력이 해금될 뿐, 실제 습득에는 별도의 경험치가 필요합니다.", en: "The two videos that teach abilities only unlock them — you still have to buy each with EXP." },
      ],
      source: [
        { label: "GameFAQs — Yakuza Kiwami 2 Video Shops (CyricZ)", url: "https://gamefaqs.gamespot.com/ps4/218734-yakuza-kiwami-2/faqs/76366/video-shops" },
        { label: "ゲーム攻略マン — 龍が如く極2 個室ビデオ屋", url: "https://dswiipspwikips3.jp/yakuza-kiwami2/play-spot/private-videos.html" },
      ],
      items: [
        {
          number: 1,
          title: { ko: "내 여자친구는 소악마", en: "My Girlfriend is a Demon" },
          location: { ko: "기본 보유", en: "Available by default" },
        },
        {
          number: 2,
          title: { ko: "매혹의 핑크 스테이지", en: "A Splash of Pink" },
          location: { ko: "기본 보유", en: "Available by default" },
        },
        {
          number: 3,
          title: { ko: "미망인 — 남편이 큰개미핥기에게 죽고", en: "An Anteater Killed My Husband!" },
          location: { ko: "기본 보유", en: "Available by default" },
        },
        {
          number: 4,
          title: { ko: "신혼 러브러브 이야기", en: "Newlywed Paradise" },
          location: { ko: "빔에서 구입 (2,800엔)", en: "Buy at Beam (¥2,800)" },
        },
        {
          number: 5,
          title: { ko: "버니짱을 잡아라", en: "The Hunt for Bunny-Chan" },
          location: { ko: "빔에서 구입 (2,800엔)", en: "Buy at Beam (¥2,800)" },
        },
        {
          number: 6,
          title: { ko: "극도 이야기", en: "Yakuza Heartbreak" },
          location: { ko: "빔에서 구입 (2,800엔)", en: "Buy at Beam (¥2,800)" },
        },
        {
          number: 7,
          title: { ko: "침몰선", en: "Sinking Ship" },
          location: { ko: "빔에서 구입 (2,800엔)", en: "Buy at Beam (¥2,800)" },
        },
        {
          number: 8,
          title: { ko: "마스크 & 리퍼", en: "The Masked Ripper" },
          location: { ko: "빔에서 구입 (2,800엔)", en: "Buy at Beam (¥2,800)" },
        },
        {
          number: 9,
          title: { ko: "더 스토커", en: "No Escape" },
          location: { ko: "빔에서 구입 (2,800엔)", en: "Buy at Beam (¥2,800)" },
        },
        {
          number: 10,
          title: { ko: "크레이지 배트", en: "Batshit Crazy" },
          location: { ko: "빔에서 구입 (2,800엔)", en: "Buy at Beam (¥2,800)" },
        },
        {
          number: 11,
          title: { ko: "슈퍼 쿵푸맨", en: "Super Kung Fu Man" },
          location: { ko: "웍스 카미야마에서 구입 (2,800엔)", en: "Buy from Kamiyama (¥2,800)" },
          reward: { ko: "배틀 스킬 「톤파의 마음가짐」, 히트 액션 「톤파의 극」", en: "Tonfa Mastery and Essence of Tonfa" },
        },
        {
          number: 12,
          title: { ko: "가라테 사범! 세가타 욘시로", en: "Yonshiro Segata, Karate Master" },
          location: { ko: "웍스 카미야마에서 구입 (2,800엔)", en: "Buy from Kamiyama (¥2,800)" },
        },
        {
          number: 13,
          title: { ko: "취권 전설! 샴페인의 극!", en: "Legend of the Drunken Fist: Essence of Champagne" },
          location: { ko: "웍스 카미야마에서 구입 (2,800엔)", en: "Buy from Kamiyama (¥2,800)" },
        },
        {
          number: 14,
          title: { ko: "싸움 지남! 오늘부터 이걸로 무적!", en: "Enemies Begone: The Brawler's Path" },
          location: { ko: "웍스 카미야마에서 구입 (2,800엔)", en: "Buy from Kamiyama (¥2,800)" },
        },
        {
          number: 15,
          title: { ko: "경악! 필리핀의 비법", en: "The Filipino Ace" },
          location: { ko: "웍스 카미야마에서 구입 (2,800엔). 8장 하야시 전투 이후에만 입고됩니다.", en: "Buy from Kamiyama (¥2,800); only stocked from Chapter 8, after the Hayashi fight" },
          reward: { ko: "배틀 스킬 「칼리 스틱의 마음가짐」, 히트 액션 「칼리 스틱의 극」", en: "Kali Stick Mastery and Essence of Kali Sticks" },
        },
      ],
    }
  ],
};
