import type { CollectiblesData } from "./types";

export const yakuza4: CollectiblesData = {
  appId: 1105500,
  categories: [
    {
      slug: "hostess-cards",
      title: { ko: "명함 헌터 — 캬바걸 명함 10장", en: "Card Hunter — All 10 Hostess Cards" },
      summary: {
        ko: "명함은 총 10장이며, 어느 캬바걸의 명함을 받을 수 있는지는 주인공별로 정해져 있습니다. 아키야마 3명, 타니무라 3명, 키류 4명이며 한 회차 안에서 세 주인공 모두로 각 가게를 자유 입장해야 「명함 헌터」 업적이 발동합니다. 자유 입장으로 접객을 받고 퇴점할 때 명함을 받으며, 명함을 받으면 다음부터 지명할 수 있게 됩니다. 에리제의 3명은 「No.1 캬바걸을 만들자」에서 그 아이를 No.1으로 만들어야 대상이 됩니다.",
        en: "There are 10 cards, and which hostess gives you hers is fixed per protagonist — three for Akiyama, three for Tanimura, four for Kiryu — so a single playthrough has to visit each club as all three. Enter on a free-entry visit and you get the card on the way out, after which you can request her by name. The three at Elise only become available once you have made that girl No.1 in Hostess Maker.",
      },
      tips: [
        { ko: "서브스토리를 끝내고 받는 「호화 명함」은 업적과 무관합니다. 처음 받는 일반 명함만 세어집니다.", en: "The deluxe card you get for finishing a hostess's substory does not count — only the ordinary card from that first visit." },
      ],
      source: [
        { label: "攻略通信 — 龍が如く4 キャバ嬢攻略", url: "https://kouryakutsushin.com/ryu4/caba.htm" },
        { label: "PlayStationTrophies — Business Card Hunter", url: "https://www.playstationtrophies.org/game/yakuza-4-remastered-ps4/trophy/284339-business-card-hunter-.html" },
        { label: "Yakuza Wiki (Fandom) — Y4 hostess business cards", url: "https://yakuza.fandom.com/wiki/Club_Shine" },
      ],
      groups: [
        {
          title: { ko: "아키야마 — 3장", en: "Akiyama — 3 cards" },
          items: [
            { number: 1, title: { ko: "리오", en: "Rio" }, location: { ko: "샤인", en: "Shine" }, image: "https://static.wikia.nocookie.net/yakuza/images/5/5d/Y4_-_Hostess_Business_Card_-_Rio.png/revision/latest" },
            { number: 2, title: { ko: "노아 (미즈타니 노아)", en: "Noa Mizutani" }, location: { ko: "쥬얼", en: "Jewel" }, image: "https://static.wikia.nocookie.net/yakuza/images/5/51/Y4_-_Hostess_Business_Card_-_Noa_Mizutani.png/revision/latest" },
            { number: 3, title: { ko: "에레나 (아이하라 에레나)", en: "Erena Aihara" }, location: { ko: "쥬얼", en: "Jewel" }, image: "https://static.wikia.nocookie.net/yakuza/images/3/3e/Y4_-_Hostess_Business_Card_-_Erena_Aihara.png/revision/latest" },
          ],
        },
        {
          title: { ko: "타니무라 — 3장", en: "Tanimura — 3 cards" },
          items: [
            { number: 4, title: { ko: "히메카 (카와사키 히메카)", en: "Himeka Kawasaki" }, location: { ko: "샤인", en: "Shine" }, image: "https://static.wikia.nocookie.net/yakuza/images/e/e4/Y4_-_Hostess_Business_Card_-_Himeka_Kawasaki.png/revision/latest" },
            { number: 5, title: { ko: "치히로 (이치키 치히로)", en: "Chihiro Ikki" }, location: { ko: "쥬얼", en: "Jewel" }, image: "https://static.wikia.nocookie.net/yakuza/images/f/fe/Y4_-_Hostess_Business_Card_-_Chihiro_Ikki.png/revision/latest" },
            { number: 6, title: { ko: "나나미", en: "Nanami" }, location: { ko: "에리제 — 「No.1 캬바걸을 만들자」로 No.1 달성 후", en: "Elise — after making her No.1 in Hostess Maker" }, image: "https://static.wikia.nocookie.net/yakuza/images/f/fd/Y4_-_Hostess_Business_Card_-_Nanami_Minemura.png/revision/latest" },
          ],
        },
        {
          title: { ko: "키류 — 4장", en: "Kiryu — 4 cards" },
          items: [
            { number: 7, title: { ko: "시즈카 (사이토 시즈카)", en: "Shizuka Saito" }, location: { ko: "샤인", en: "Shine" }, image: "https://static.wikia.nocookie.net/yakuza/images/a/a7/Y4_-_Hostess_Business_Card_-_Shizuka_Saito.png/revision/latest" },
            { number: 8, title: { ko: "마야 (모리 마야)", en: "Maya Mori" }, location: { ko: "쥬얼", en: "Jewel" }, image: "https://static.wikia.nocookie.net/yakuza/images/f/ff/Y4_-_Hostess_Business_Card_-_Maya_Mori.png/revision/latest" },
            { number: 9, title: { ko: "히요리", en: "Hiyori" }, location: { ko: "에리제 — 「No.1 캬바걸을 만들자」로 No.1 달성 후", en: "Elise — after making her No.1 in Hostess Maker" }, image: "https://static.wikia.nocookie.net/yakuza/images/c/cc/Y4_-_Hostess_Business_Card_-_Hiyori_Matsuoka.png/revision/latest" },
            { number: 10, title: { ko: "쿄코", en: "Kyoko" }, location: { ko: "에리제 — 「No.1 캬바걸을 만들자」로 No.1 달성 후", en: "Elise — after making her No.1 in Hostess Maker" }, image: "https://static.wikia.nocookie.net/yakuza/images/4/4d/Y4_-_Hostess_Business_Card_-_Kyoko_Mochizuki.png/revision/latest" },
          ],
        },
      ],
    },
    {
      slug: "lockers",
      title: { ko: "물품 보관함 — 100개 열쇠와 보상", en: "Coin Lockers — All 100 Keys & Rewards" },
      summary: {
        ko: "카무로초 지상 50개 + 지하·옥상 50개, 총 100개 물품 보관함 열쇠 위치와 보상을 정리했습니다. 5개만 열어도 「열쇠 마스터의 길」 업적이 풀립니다. 지도의 번호가 카드 번호와 일치합니다.",
        en: "All 100 coin-locker keys (50 surface + 50 underground/rooftop) with locations and rewards across Kamurocho. Opening just 5 unlocks 'Path of the Locker Master'. Map numbers match the card numbers.",
      },
      tips: [
        { ko: "타이헤이 거리 보관함 앞 남자에게서 「열쇠 워처」를 받으면 미니맵에 열쇠 위치가 표시됩니다. 2장부터 회수 가능합니다.", en: "Get the Key Watcher from the man by the Taihei St lockers to mark keys on the minimap. Available from Chapter 2." },
      ],
      source: [
        { label: "龍が如く4攻略通信 — コインロッカーの鍵（マップ付き）", url: "https://kouryakutsushin.com/ryu4/locker.htm" },
        { label: "神ゲー攻略 — 龍が如く4 コインロッカーの鍵の場所一覧（鍵別MAP・場所画像）", url: "https://kamigame.jp/%E9%BE%8D%E3%81%8C%E5%A6%82%E3%81%8F4/%E6%94%BB%E7%95%A5%E3%82%AC%E3%82%A4%E3%83%89/%E3%82%B3%E3%82%A4%E3%83%B3%E3%83%AD%E3%83%83%E3%82%AB%E3%83%BC.html" },
        { label: "光る原人 — 龍が如く4(PS4版) コインロッカーの鍵の場所一覧（入手画面）", url: "https://www.hikarugennjinn.com/entry/yakuza4-coin_locker_key" },
      ],
      groups: [
      {
        title: { ko: "카무로초 지상 — 50개 열쇠", en: "Kamurocho Surface — 50 Keys" },
        mapImage: "/yakuza-4-lockers/surface.webp",
        hotspots: {
          "1": [29.55, 82.28],
          "2": [44.37, 69.67],
          "3": [71.53, 55.76],
          "4": [41.13, 46.63],
          "5": [39.43, 91.2],
          "6": [26.93, 57.72],
          "7": [54.24, 55.11],
          "8": [33.41, 85.54],
          "9": [53.32, 33.37],
          "10": [36.65, 68.37],
          "11": [46.68, 39.46],
          "12": [17.21, 29.02],
          "13": [38.97, 49.02],
          "14": [48.69, 26.2],
          "15": [41.28, 67.28],
          "16": [19.52, 35.11],
          "17": [88.04, 28.37],
          "18": [81.4, 59.24],
          "19": [30.48, 93.8],
          "20": [55.94, 68.15],
          "21": [30.63, 52.72],
          "22": [17.82, 78.37],
          "23": [15.05, 78.37],
          "24": [21.99, 94.24],
          "25": [7.95, 27.28],
          "26": [13.04, 80.76],
          "27": [23.38, 76.85],
          "28": [37.42, 85.54],
          "29": [46.84, 71.2],
          "30": [32.02, 36.85],
          "31": [33.26, 97.72],
          "32": [54.55, 87.5],
          "33": [32.79, 79.89],
          "34": [25.69, 84.67],
          "35": [59.65, 47.28],
          "36": [31.1, 31.41],
          "37": [11.19, 70.33],
          "38": [39.27, 60.76],
          "39": [12.58, 46.63],
          "40": [93.29, 15.54],
          "41": [49, 37.93],
          "42": [20.14, 54.02],
          "43": [64.27, 30.11],
          "44": [38.5, 33.37],
          "45": [22.76, 42.5],
          "46": [45.91, 83.59],
          "47": [32.79, 25.76],
          "48": [22.92, 26.41],
          "49": [5.02, 39.89],
          "50": [25.54, 13.37],
        },
        items: [
      {
        number: 1,
        title: { ko: "A1", en: "A1" },
        location: { ko: "클럽 세가 나카미치 거리점 앞 노상", en: "Road in front of Club SEGA Nakamichi St" },
        reward: { ko: "너덜너덜한 머플러", en: "Tattered Muffler" },
        image: "https://lh3.googleusercontent.com/N52GyJHcRUAcmdQJigN4J7E7p5wG4rkRtCznbepIF02uwLBfwIZHMfiIcjOn-LlP6K5WLkRsmMHdQ3U5MaK49G-FjBUJ4ycZJeZ_L0kLNHt5=s0",
        images: ["https://lh3.googleusercontent.com/ssICHgR4gLjb-TO2ShNPYCIOC4FaTW_ATfRjnJCD_OlgKQWi1gtk0q6Ig_kszeBkJ7bAPo_AHNQi66mTxQ5cI78DKemRtTO4sBut-8z22zZn=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-135024.jpg"],
      },
      {
        number: 2,
        title: { ko: "A2", en: "A2" },
        location: { ko: "아시아 점내 바닥", en: "Floor inside Asia" },
        reward: { ko: "강철 갑주", en: "Steel Chainmail" },
        image: "https://lh3.googleusercontent.com/8OLaeA1NI1Fqwrypjr4gpMgFS6hab8j4KIlh0zPi5HQ0CXxDYb-0C0Wo9DA3YcjeXXwB_i-s3Vob7SppivzuU63TYzKhe53Y28HKx41O_w4W=s0",
        images: ["https://lh3.googleusercontent.com/_ZiRwgjUPFODkIdA2FX6IjC7c0Olzca73Ouq-1tPN9W9ANibJJTTvCNr7Y0xuTFxtIKXx0VTZl7k31Eyt0MgZnNFVv5XB3oO6fkvwfT4gzd_cw=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190120-073957.jpg"],
      },
      {
        number: 3,
        title: { ko: "A3", en: "A3" },
        location: { ko: "카무로 극장 소화전 위", en: "Atop the Kamuro Theater fire hydrant" },
        reward: { ko: "격신 나이프", en: "Spicy Knife" },
        image: "https://lh3.googleusercontent.com/R4L0VbHsILmdWfVDo45L_eARn2YIeRw2nmLFhXV_964pSmKMHL-OMj9U_IAUZbW4UqQ1qoJp2dXwZ2Zf7cFKZB2xlkHRhI_TxWWO_Gl83jpQ=s0",
        images: ["https://lh3.googleusercontent.com/R4L0VbHsILmdWfVDo45L_eARn2YIeRw2nmLFhXV_964pSmKMHL-OMj9U_IAUZbW4UqQ1qoJp2dXwZ2Zf7cFKZB2xlkHRhI_TxWWO_Gl83jpQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-134453.jpg"],
      },
      {
        number: 4,
        title: { ko: "A4", en: "A4" },
        location: { ko: "빔 점내 화분", en: "Planter inside Beam" },
        reward: { ko: "귀면석", en: "Oni-Face Stone" },
        image: "https://lh3.googleusercontent.com/QLfyDeoc4wivKvsJhNn0UjFg0cUPfTqG-DRkjLuHljSp9Zc7nWltk5Y9ud-YM0WE6xHYLACGAukwPYzKjfGRCy_M2r4tQdJ2AyZ6cFX002SI=s0",
        images: ["https://lh3.googleusercontent.com/xRAuOZVUGDjgIF0OCg_q-7NKO2Z0bunwtLDA2SqdQiI4sklGktGnXtrIQR2_0W6zOvNGR6FEMECfIPVzenxL2YcqgMTHKsJsMVaJBl-RnSo=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-174906.jpg"],
      },
      {
        number: 5,
        title: { ko: "A5", en: "A5" },
        location: { ko: "POPPO 쇼와 거리점 바닥", en: "Floor inside POPPO Showa St" },
        reward: { ko: "용의 눈동자", en: "Dragon's Eye" },
        image: "https://lh3.googleusercontent.com/56lk6tl4kgt6hjftuT5Rd7Y5fl4E1TdDDkUMW3aOqqS5K-sbYNYboHX1PaeC2mS2jozRK_nRJD7f00f6X4LUtEQ3Jf7wdzU1fBm6Nw28xgDr=s0",
        images: ["https://lh3.googleusercontent.com/z9NRZ-TLLS-gHUIYg7vDi51CfhNLbJLeDSkdfdnn2YwonCptGumqVeMtKS2Cc3Q3p_rHVNcV7V-D1Ngyoe6yu4W4Oj81ckumudk9ECG6wSVzTQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-175207.jpg"],
      },
      {
        number: 6,
        title: { ko: "B1", en: "B1" },
        location: { ko: "코인로커 입구 밖 벽 왼쪽 상부, 무단투기 금지 안내문 위", en: "Above the no-littering notice, upper-left wall outside the locker entrance" },
        reward: { ko: "하이퍼 스턴건", en: "Hyper Stun Gun" },
        image: "https://lh3.googleusercontent.com/CyUFuyvxgWA8Ef0hcRdA3_laRAxbswyPvxEjTCFAQDNq_XftKTMeFpUzvSVw_teLr176gNFP5yr0m0j8PS1JIqVfRPxU6xOmjXLAgQgR4Vak=s0",
        images: ["https://lh3.googleusercontent.com/H5v5doVREBy3-seN9oEmF_1d0g5bI16mGHutpJQTQflrTvFQClHj47btZo_h1e3oadAAKZ-C3-2l8Eqnd3XPmq7KCqjyK1E08z_ZbcJSlryv=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-180301.jpg"],
      },
      {
        number: 7,
        title: { ko: "B2", en: "B2" },
        location: { ko: "챔피언 거리 남서쪽 모서리", en: "Southwest corner of Champion District" },
        reward: { ko: "형상기억 스프링", en: "Shape-Memory Spring" },
        image: "https://lh3.googleusercontent.com/H7NuqYV2W_uh14wKJmUHqhdWq6Xo3qtGUHBU_TukkJndNUpVO7iK_t0iED4pszpaB3qGjeAK9S_ncd0SgC9qeCxrLqzUkeQUWPdyyxFeqPOA8Q=s0",
        images: ["https://lh3.googleusercontent.com/P7lQecft7KZI4VtxbK5HDYI6m57hk-BZTmJtjueuIaP05axJWhWJky-HL32tLW2MhBI14UZslk95L5X1xn3UpWp2FiVEUcSl3msp7APSCvxv=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-175430.jpg"],
      },
      {
        number: 8,
        title: { ko: "B3", en: "B3" },
        location: { ko: "나카미치 거리 뒤 에비스야 점내 바닥", en: "Floor inside Ebisuya, behind Nakamichi St" },
        reward: { ko: "진주", en: "Pearl" },
        image: "https://lh3.googleusercontent.com/R0YKhf_nUxKjHdzf5UbPR19FtXTcJsYQ9_E_Jild9Cy_fL23neYYRvr8rMBzrw43OcYpWk4BiK2CP5XwEzmG9xKgaFO5RFf80b34xRMt_mqo0A=s0",
        images: ["https://lh3.googleusercontent.com/BgnW_e-63X_Al1Y0iCbBKO0yQDmJDufMfxbuYQVZ5bGIxOPSf-vXk9ocPSexJ3XQelbopXfFintiAk4H2bfZ0xlI3AkFDBULwxWloatA2u8fgA=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-171305.jpg"],
      },
      {
        number: 9,
        title: { ko: "B4", en: "B4" },
        location: { ko: "웍스 우에야마 조금 앞 배기관 위", en: "On the exhaust pipe just before Works Ueyama" },
        reward: { ko: "수수께끼의 휘석", en: "Mysterious Gem" },
        image: "https://lh3.googleusercontent.com/vwAHlusro7QuhSVhMtbK5opNMo82YysyUoCInN-YRjT4J7TxoZcNtVWID62daRMvtPBo8IG_uVmWTaxpA98JJYbM4xWCJj2drwGZ3M4R8Y_y=s0",
        images: ["https://lh3.googleusercontent.com/cbroX7fiC8140wCWxNC61raUHO2EBF-3oBrutxYwM5_--LA1uCCkCSPd1ZQ8DOY2uhUiVMrkqO2Z-4ApZXmRsSaPtkNuUr1xN6ERXQrLo2g=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-175706.jpg"],
      },
      {
        number: 10,
        title: { ko: "B5", en: "B5" },
        location: { ko: "POPPO 나카마치 거리 뒤점 뒷골목 파이프 위", en: "On the pipe in the back alley of POPPO Nakamachi" },
        reward: { ko: "수수께끼의 휘석", en: "Mysterious Gem" },
        image: "https://lh3.googleusercontent.com/qEkq73km4OY0FNiG9fT7WClhcUG0kJXtVjtbX0u_vXiiK4IiGbXm2CBEwwjc9aO32YyPdQkcyCg4Je5ST9YH1ympFjYgz5tm0SdHcSLzjN27jA=s0",
        images: ["https://lh3.googleusercontent.com/njkEt0mK6RmTKsWPd0Zwifkq1CGVTd64VL2BvjHCK7bpQEUpKrP-3wu5oAXYouK5n52Zt00kWFQF5TfHVvCKTSemK6DpIYk9Ex2gK_jvM6kI=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-161343.jpg"],
      },
      {
        number: 11,
        title: { ko: "C1", en: "C1" },
        location: { ko: "시치후쿠 거리 동쪽 칸라이 앞 노상", en: "Road in front of Kanrai, East Shichifuku St" },
        reward: { ko: "고대의 철강", en: "Ancient Steel" },
        image: "https://lh3.googleusercontent.com/rKTaZRB1IK5pLvgJb4K7Td3VgmqgTPikEFQgjzWTZKbOX_xb6jt6p0pJxUHPU1eCcma040p73znLjrGUv0H9TmhwSVyu-AqlkCRPpMVG4fuTXA=s0",
        images: ["https://lh3.googleusercontent.com/Ca768ho7WVBdq-ZV96zOmaDr0zxMnZdQ_EmkQCBL0t8ZKfnivTMKn7ZKARS9KgiDF8kPs_LvhsISjJFkwuLtt6Mfeo3B8ORMRBzehQsSinj9xg=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-131436.jpg"],
      },
      {
        number: 12,
        title: { ko: "C2", en: "C2" },
        location: { ko: "시치후쿠 거리 서쪽 M스토어 점내 바닥", en: "Floor inside M Store, West Shichifuku St" },
        reward: { ko: "고장난 라디오", en: "Broken Radio" },
        image: "https://lh3.googleusercontent.com/P8PziMwluSW5aJRSO0G53-40Qd-744RKWeQav3VxuFNbUSW9BeqXv931iQCjBIhHccOEf9UsXLqDpqKy4_xqE0AzNOpziOQZTKtoiwVC1aPi=s0",
        images: ["https://lh3.googleusercontent.com/hPRc3xmKrTtG__rNsY36HMhO3zyMT0cBqGVCMUBUlwImSe4xI_cg7W1NR0bkrMb2tYCTXeLs-oRpSqOvy9CMGDHjuK14MsL2owESVEsH-MXh=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-180700.jpg"],
      },
      {
        number: 13,
        title: { ko: "C3", en: "C3" },
        location: { ko: "밴텀 점내 스피커 위", en: "Atop the speaker inside Bantam" },
        reward: { ko: "BJ의 부적", en: "BJ Charm" },
        image: "https://lh3.googleusercontent.com/FVuCRZARGTH70-O80RS01-LK-5phYak6TpdI9InSHIb3534A_DXJ-SnpC5-WW8czj79JIXbFbey2MljoWaICCJYzbuUPfGZlik-Bf5hKOPoe=s0",
        images: ["https://lh3.googleusercontent.com/Jz1WSx6oMfruzEDZWFxDx9a7Qavabk9qP4JgZv7q3AGH94Fy63C-KejZP3Um667s3AImWNXRB4SIhKzFVp5fDhBbXoJVGXDG-r9_4GMRx2M0=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-134321.jpg"],
      },
      {
        number: 14,
        title: { ko: "C4", en: "C4" },
        location: { ko: "인도 쓰레기 더미 앞", en: "In front of the trash pile on the sidewalk" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
        image: "https://lh3.googleusercontent.com/UGvEjiKjvChDAntHuhIYgQ36_n7uZwcqVp4ikd0LwLxgmQw9q3Vl7Gdo7r_8Puu4_pifIVb9JTc3miSG2lb4J7O1ebnAzIM4LufnDD2XKGnPaA=s0",
        images: ["https://lh3.googleusercontent.com/VYccGTMJHzg2KtURZqmNubDVRY4o6HF5m1KQePVf7usQWbhX921-Ks2g8uTCZdds4GIVzhJpb-E6xNQT0yPt2HRnsmdHm8JT3CG9qQQH798=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190120-042831.jpg"],
      },
      {
        number: 15,
        title: { ko: "C5", en: "C5" },
        location: { ko: "타이헤이 거리 동쪽 고토부키 약국 점내 선반", en: "Shelf inside Kotobuki Pharmacy, East Taihei Blvd" },
        reward: { ko: "무의 보석", en: "Void Gem" },
        image: "https://lh3.googleusercontent.com/g3b0OO8baNi9lmi9yu0bVKKuYJLWQLGD3eWhBMXRr-m1Yn7aBY0hMiyDdG20TCFP5jU8RL2YXHOjZdIjRFNJysHGrG5R7LrdbPV-Z0_mtcjU=s0",
        images: ["https://lh3.googleusercontent.com/qxBIE13OJ0yJtbo-e-8LZyvB0yl-k6HAep48CCwZgXgBLmRP5fNYxuARm2gqdUun9gJJHShxMgix9BEnRuhZ1bk9umAcE3vu0niV7B_j5cN3=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-181642.jpg"],
      },
      {
        number: 16,
        title: { ko: "D1", en: "D1" },
        location: { ko: "클럽 세가 극장 앞점 뒤 자판기 위", en: "Atop the vending machine behind Club SEGA Theater" },
        reward: { ko: "핀조로의 패", en: "Pinzoro Tile" },
        image: "https://lh3.googleusercontent.com/bLDPWSQZb2sD0o79ieJ-zYg2xp7elU6MZiN3sOO37bHL4a5--YiBeX7UpWvK0R_HTxm0XNteZ7xTTEilvSbL9vjn3sFu_dJPopE4rLQ664Uj=s0",
        images: ["https://lh3.googleusercontent.com/XYVeCYMhGUMcuJfn3Wjkeg5Aq7BiB2YDkzaYYUbSMaU9qjVxZo_rXALrAfpFs82kCJnDqNi6eUndnUDMsdkvjBa3DGNcyWyhjpV4tu7edhYk=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-180526.jpg"],
      },
      {
        number: 17,
        title: { ko: "D2", en: "D2" },
        location: { ko: "아시아 거리 북쪽 입구 정면 화장실", en: "Restroom facing the north entrance of Asia St" },
        reward: { ko: "터프니스 엠퍼러", en: "Toughness Emperor" },
        image: "https://lh3.googleusercontent.com/dGcRI0_qqXd06Qf8pkJAurcUHMfjROE8VfQAyitlPB4IIX-b1jJ8EM5Na7UTX4JeKQPvJnPOuJb9Y_EJo9Bt13xvIRuMprlhEXUFnWhOTFJp4g=s0",
        images: ["https://lh3.googleusercontent.com/RFKX5M90YCMow-KtQCK_LKszbnY976ck1FCgAqBj42GzpvIwXlSJXFkCK--kd7dH2UI3-hgSOHKkA0hWP3iNjt-akXfxc0pB41c38QV6iq4=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-182039.jpg"],
      },
      {
        number: 18,
        title: { ko: "D3", en: "D3" },
        location: { ko: "아시아 거리 2층 통로", en: "2nd-floor passage of Asia St" },
        reward: { ko: "은 접시", en: "Silver Plate" },
        image: "https://lh3.googleusercontent.com/g-ifd3tI80T1NV5xVsyngEyECjKvlE-VmRTOtnMqjqa-W4tP0MTyzpMJpZWTp0qFTTYDEj4dlZt6CgMG8ZHoUb0gSfdqn5BQnTHXjZJW1tk=s0",
        images: ["https://lh3.googleusercontent.com/16-JqQvFxqXC0J2malTcuB0p_7KI03VRCOTLTbZPPLr6DU8KB0zejx4cq3u0m9utLb20q3d9Gdxana4AeQJ1eydoMyEwLthHPSXF_i-jcsVB=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-181905.jpg"],
      },
      {
        number: 19,
        title: { ko: "D4", en: "D4" },
        location: { ko: "나카미치 거리 입구 돈키호테 앞 자전거 바구니 안", en: "In the bicycle basket in front of Don Quijote" },
        reward: { ko: "피지매직 저지", en: "Fiji Magic Jersey" },
        image: "https://lh3.googleusercontent.com/LPsxHOMzdm3NDxbmlJLI3x3lL1kJjrtk-cGNfOy0ILkNX5Xk_-5UXwljEpaEiMm8vTMCAaU5Q4Do5otiB0CN3D7DKRpSvemfLCSKZvO_Vzc=s0",
        images: ["https://lh3.googleusercontent.com/YJW7GLYquJgT_rB3lqr4ljVqNcL5dJQWWY3OUBNTA20MrOYHfoZptSWhH7nj1vAwoUl_GbApughG8bvWgQbSXZhMhiZiShn_hYnpo1wh3ay5kg=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-173712.jpg"],
      },
      {
        number: 20,
        title: { ko: "D5", en: "D5" },
        location: { ko: "타이헤이 거리 동쪽 주차장", en: "Parking lot on East Taihei Blvd" },
        reward: { ko: "카리스마 링", en: "Charisma Ring" },
        image: "https://lh3.googleusercontent.com/iDQERcFiNBjjVJppWz3E20v8hc-sY02dNA64_4yeUYMxBR1ACRZ4cdQVjNibkzjLur75XqbK4A1yGHg9Q015W9YoaUrxegjiGfpS5QTNgAY=s0",
        images: ["https://lh3.googleusercontent.com/zRP0pNeXoES7FoW9_8Qkt1Il3NLqNIaofaLXNgFpbW0qJEd0KtX2bqeWpSCq0wUzyUgLz8VVzywvggar2MoLYf2OVvFDcrAUPA_pySfzoasbYQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-182312.jpg"],
      },
      {
        number: 21,
        title: { ko: "E1", en: "E1" },
        location: { ko: "밀레니엄 타워 앞뜰 나뭇가지", en: "Tree branch in the Millennium Tower front garden" },
        reward: { ko: "숀벤 산맥의 돌", en: "Shonben Mountain Stone" },
        image: "https://lh3.googleusercontent.com/IAkNP2li6XNoAYY32t9cMTm2IPqkwK7Uw50gP3dR7UsXCP8GV__7fNI2OV60AdiHLJxspRC1uMQpODpa7VevHosGnAWnlFWkOqWWrnEjbmZF_Q=s0",
        images: ["https://lh3.googleusercontent.com/1JUSh0xn48qGcYnrglBMAvasdF6iqYNFu_QVZ9bPIMZTxejKGbTUN-hQEVc5icOvvPRXhTffzNQNxyADY74KkBBt9Q_JU7qyrRcQUC_xthg=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-182831.jpg"],
      },
      {
        number: 22,
        title: { ko: "E2", en: "E2" },
        location: { ko: "천하일 거리 뉴 세레나 빌딩 앞 노상", en: "Road in front of the New Serena building, Tenkaichi St" },
        reward: { ko: "귀자모신의 부적", en: "Kishimojin Charm" },
        image: "https://lh3.googleusercontent.com/3Flt127xx5FqaLb3ASgDsZd5zJv2HPDa2uamogGrRisUDf29x2DUFbSgdq077AfmMatwXoBltH7t6oPnKFho8BcxebatlV4-_yRKQBAbpiAX=s0",
        images: ["https://lh3.googleusercontent.com/c7ViI2IIqUtiAvrBwLe5blQsVkcDM38-FrNBIfI7pDgetrBbkU2XqMLWhvDqlgts1kO5FMw-T4DS_pgbtsQHuu4QdbD3gKegf_yGXlO-cPU=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-135744.jpg"],
      },
      {
        number: 23,
        title: { ko: "E3", en: "E3" },
        location: { ko: "뉴 세레나 점내 북쪽 조명", en: "North light fixture inside New Serena" },
        reward: { ko: "소형 모터", en: "Small Motor" },
        image: "https://lh3.googleusercontent.com/dd6dsXvtUJdIZLW5QOHvNLMeVau7D1hp8FUM89O_UQc4Xsjml8G8PiaQfYzewnIQv_eFaJ0tg80z0xnedhDovwa9GJ_im1LyE6MoUZY4jJCw=s0",
        images: ["https://lh3.googleusercontent.com/LgxkwlFJNY1WoCpbKN5gyw7paqQsO9rHZq7u-SEboxc8aviKm0mxej1ptZuGWVEC4AiOoaS4NoFa-YXo2OVdBNUYUN4Hy1aLkbRA3qegsTI=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-183108.jpg"],
      },
      {
        number: 24,
        title: { ko: "E4", en: "E4" },
        location: { ko: "쇼와 거리 서쪽 가장 서쪽 지하상가 입구 벽 위", en: "Above the westernmost underground-mall entrance, West Showa St" },
        reward: { ko: "중력 변환 장치?", en: "Gravity Converter?" },
        image: "https://lh3.googleusercontent.com/GNJ0oeZe4j9q4NG_YH0wPJmFYxAvb3QO8ttPTkv6J0WgSE-M9n78kD2oEbmK7OyLlm_Y7i7XyUIcziDWanscoUSUZBikr-6_wBWSbmEDeEMT=s0",
        images: ["https://lh3.googleusercontent.com/ayPwxWjmtvFLoQEH1svbR-gFgvl8Cp0lYOmNrpSUu9TF2BN5OQhu_IrOKwAHbnS-VwnJWeutcEoSMhIZvC9ODxxK68pzXnGGrL926KM6nNfZ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-170459.jpg"],
      },
      {
        number: 25,
        title: { ko: "E5", en: "E5" },
        location: { ko: "아동 공원 나무 위", en: "Up the tree in the children's park" },
        reward: { ko: "전국 사슬갑주", en: "Sengoku Chainmail" },
        image: "https://lh3.googleusercontent.com/PmBumV5qd7_8B_w58xuOtem7oSP91o2v8OiXyjNbV2SR4jfYaU5xsAwf0Z5Ws6Dhc3L7Lh9a4AVloW4Ig15FvRVxqrslzcEg7n8zWSjLgibG=s0",
        images: ["https://lh3.googleusercontent.com/wTMuy-Kasj4CMrrzOBdssOHHOqD8UjM1EGbpd6f4WZVJ_wjQ003wN9xAxlHVOIeqRxLMCTXW0OfzRDdPB3mOXEbcklhannj2rV7Mi4EZpzfa=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-183612.jpg"],
      },
      {
        number: 26,
        title: { ko: "F1", en: "F1" },
        location: { ko: "뉴 세레나 뒤 자판기 벽 위", en: "Above the vending machine wall behind New Serena" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
        image: "https://lh3.googleusercontent.com/06B59IxuSUH08nkUw7xYkdDprLn6A3A9IglLG7z-EX219qn063OX_SuPmch90Y6VIl6aGdEk7RG2zsS2KT0_KL9eFb2HLOymhorY8H6sxBU=s0",
        images: ["https://lh3.googleusercontent.com/KImomLmnKEAMTB9v3dmYhBwLbfIfg9zzOpnUhaRZF2h9L8MKfx8c_gpiReOKFNWc4E9TJrHT9ESNFVkiDBDrju5kf7lcZDW4TVC1eCh1SZR2ow=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-170158.jpg"],
      },
      {
        number: 27,
        title: { ko: "F2", en: "F2" },
        location: { ko: "제3공원 벤치 아래", en: "Under the bench in Third Park" },
        reward: { ko: "형상기억 스프링", en: "Shape-Memory Spring" },
        image: "https://lh3.googleusercontent.com/dDElSqiBwHOjWVFt7mwVNBOKGf0yD9IvQyh1bTjP48816Hq1X2rgpy78KM-Xz_F-OyymP1gzKn6drPhqJIQl3qLESwb7SiF0svdgRb8P7QaH=s0",
        images: ["https://lh3.googleusercontent.com/QDoXmG3gHjxNsqOlm1e6HOprTE7Xl2tdx9JnUb0trPvlkxUwqRdYa22IeYkRF6LuyKUppD0dXm25Jxip1yvVvp4E15y-2rshkiY4xZZtJeBULQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-164532.jpg"],
      },
      {
        number: 28,
        title: { ko: "F3", en: "F3" },
        location: { ko: "나카미치 거리 뒤 록란소 바닥", en: "Floor of Rokuranso, behind Nakamichi St" },
        reward: { ko: "진주", en: "Pearl" },
        image: "https://lh3.googleusercontent.com/0U9mpEoZgQu6nclgOQt-rpeN4y9MHmzYGZZBasuionMhicA-pALrlEFywT-tBl3g_RT5M84v_cStYTp7N0Unb3YpKnDRHPIJojNCsVxOGqpb=s0",
        images: ["https://lh3.googleusercontent.com/Y8XsuWm5RqEWJ-2oMdMQ-scImls_kSi0gmhYKDYgOvXzFRc5Ovs0AYiKZNyhYR-SSa1bAg5kG-2dHS70SYPi8ij61aqC_kAmqfowCM3GBAeQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-171127.jpg"],
      },
      {
        number: 29,
        title: { ko: "F4", en: "F4" },
        location: { ko: "핑크 거리 뒤 큐슈 이치반보시 점내 바닥", en: "Floor inside Kyushu Ichibanboshi, behind Pink St" },
        reward: { ko: "쾌적 솔", en: "Comfort Sole" },
        image: "https://lh3.googleusercontent.com/H3s_F44_j2v3R4-mFcS6OGIexvrF1KsDbpkY_SFh9RhlXyXD8Z_DzAzhDKAIWR_vo93h6ErjUzZ95kD5ZllTe-jfZcxT2QRMrvkq427xRgAM=s0",
        images: ["https://lh3.googleusercontent.com/3lGsfa2T5S9LJfg2d-UYM_IiUvsQgGZd720Ttktwl5tGnuzst5c9P2_insN36HgmlKNE2nMh6aU-vofDuq5YX5_Ja9-GqYDCYSfFzIEvonuW=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-174647.jpg"],
      },
      {
        number: 30,
        title: { ko: "F5", en: "F5" },
        location: { ko: "밀레니엄 타워 북쪽 트리 꼭대기", en: "Top of the tree north of Millennium Tower" },
        reward: { ko: "수수께끼의 액체", en: "Mysterious Liquid" },
        image: "https://lh3.googleusercontent.com/Qg53WIbW19d88gqe_9Tc13rtKNvJxLHdyvCvRgDoKH589kxDlrZkpcDqqd7IGcJ_yMQ0ZoBnbqYhI2_O9NG_ttmGcc7FDmZ_CQ9YNbBUau1b=s0",
        images: ["https://lh3.googleusercontent.com/wDttw_x4cbLQUewMl0RTyJ4lYYEvbkWWwF9LSUaoHrqbF5R55zZ5pqBud7nQurlW335dZihuCPjiD-rkxPhKA3_PycxLpvR4zOo90BAFAHQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-134914.jpg"],
      },
      {
        number: 31,
        title: { ko: "G1", en: "G1" },
        location: { ko: "클럽 세가 나카미치 거리점 바닥", en: "Floor inside Club SEGA Nakamichi St" },
        reward: { ko: "로열 조커", en: "Royal Joker" },
        image: "https://lh3.googleusercontent.com/kEN6kOmM94MhxS8Noes7eUhUADITPyBlRb82y-aBUOrv0grSRq_BNzKwjyDVnegHVDoewOqirZuPJ7Zb4wHfvbIyUO6rHMdrQK80l15uRWc=s0",
        images: ["https://lh3.googleusercontent.com/3IOdz_Mz6vZ2Y8xn1n8sn3zZ4ysTxM3jW8lGCPhqGeUYSuANmNPU556DsWdHpE7YMw-TFH9_8ZE8TfrX0sPP89Rv9jfQrOkzBPw37cNuhpkiFA=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-161710.jpg"],
      },
      {
        number: 32,
        title: { ko: "G2", en: "G2" },
        location: { ko: "천량 거리 간판 위 조명", en: "Light atop the Senryo Ave sign" },
        reward: { ko: "쵸고로의 염주", en: "Chogoro Beads" },
        image: "https://lh3.googleusercontent.com/DeWJj0REKyVXXrBRGBcMxdVFaNbJqgWfho2cqvsGtamUlUkU_rXqaVeShA49zG4mVu-qIchRd3rnPpeeNuUsCOf9LcsCmv4Z6G7v7D0IbyD7=s0",
        images: ["https://lh3.googleusercontent.com/mQI56O8Ah1O4ztfHu51H_dQ9xRyD9C8owwXFKyhlJjpOCAGMluSU2ewVIKWV4u-Mde14BzGGDuxASCT-tWNbT-3oY8NSSt4YOyLktz3TGGXE=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-183958.jpg"],
      },
      {
        number: 33,
        title: { ko: "G3", en: "G3" },
        location: { ko: "클럽 세가 나카미치 거리점 뒤 쓰레기통 안", en: "In the trash bin behind Club SEGA Nakamichi St" },
        reward: { ko: "카타요리사의 담배", en: "Katayori Cigarettes" },
        image: "https://lh3.googleusercontent.com/B8KkK8NG1WlyQiRMYP7HsweTRRFB7SirhO2jYDSHTUuLlJ9Iy8Y_xRl8kdt5YTxH8fOu9OKMz7r2YBLv07Kcrrm9sXDntVH0UxAYu4PuGfja=s0",
        images: ["https://lh3.googleusercontent.com/f_XX1cMk48QXwX_aTlHKxXOUcaaCNtw_eN0u8KycNbL2IT1vjnaZiZcLMhbnU8jMhzOsoNvrjUkVb3Nx724GOfVTKZnO_BIHzQcB8mDx2TRc=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-162023.jpg"],
      },
      {
        number: 34,
        title: { ko: "G4", en: "G4" },
        location: { ko: "나카미치 거리 킷사 알프스 점내", en: "Inside Cafe Alps, Nakamichi St" },
        reward: { ko: "붉은 보석", en: "Red Gem" },
        image: "https://lh3.googleusercontent.com/EviVOU24CR201LeIG4jANuX9wNNlPMQzcXeNKiQm8eOFpXdTlby2YlLrQMbZK3_vkYTgDWBvjXas9Vgm4e3WgQK8cPBcMa4yLIVzZSIBG9tRjQ=s0",
        images: ["https://lh3.googleusercontent.com/KgkQGinUAirNDO5RCUAyOA6Cc-AgndiuXNhNnLs1eHl6v8xIDUmzs3nTpBUrXdo18jCovd6IqqU1aLIu-DSEv23A2iI8P92FABE8sN7cO_E=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-135211.jpg"],
      },
      {
        number: 35,
        title: { ko: "G5", en: "G5" },
        location: { ko: "챔피언 거리 북동쪽 슷톤쿄 처마 위", en: "Above the Suttonkyo eaves, NE Champion District" },
        reward: { ko: "고순도 플래티넘", en: "High-Purity Platinum" },
        image: "https://lh3.googleusercontent.com/r9IByQ1APkoUV0EOaRfNfqVxrb6R0KxtaqwLKriKBPYDf9w7IWhMwJA7wC5IyErOoSbhyN8AlaiZUBsucKGQ27MBXOqvHtWi3u18sGBpe20=s0",
        images: ["https://lh3.googleusercontent.com/I0D3CV9dGGHxUXN6wyKJNGAPqECAC2L17LG11VOhlQpAC55CPjXolW-on4SO_0UkYndEWaYGwTUNkMZ2cRy86Ouqxhai_6w8XXHeMaTl5OakJQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-184412.jpg"],
      },
      {
        number: 36,
        title: { ko: "H1", en: "H1" },
        location: { ko: "시치후쿠 거리 MEB 바닥", en: "Floor of MEB, Shichifuku St" },
        reward: { ko: "메이플 나무 조각", en: "Maple Wood Chip" },
        image: "https://lh3.googleusercontent.com/Wly1On3dzOBCj8uRnWiD01TMc12V8qJTr8v6UyHrXw022fzGNULeu9TvBEcsC6KOR2EK7gXQiNQ_lyFY3jjvQPPE-SNnYXgC7acitjiNvX8=s0",
        images: ["https://lh3.googleusercontent.com/IQZ9QxI983nRM6wBdMA6SLn6oPubrHrG0TDj05R4A1fdk3j5EAT_DLkvz269LaoVJGuwhEJMXtdzYVIq83BmMXBPoVQ1vVNc18Fors6yZ44=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-184625.jpg"],
      },
      {
        number: 37,
        title: { ko: "H2", en: "H2" },
        location: { ko: "슷폰 거리 카무로 라멘 앞 노상", en: "Road in front of Kamuro Ramen, Suppon St" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
        image: "https://lh3.googleusercontent.com/IMcXpm2us_XBziy14g1g62w-3E0X4ll_uX2f8fCQUgudATshtwP4B7Ts1bAKxD7ElXXGE-5Zt2pQ-732q2rWoZq9RbixgGGjcaXLGtA6H-ltHw=s0",
        images: ["https://lh3.googleusercontent.com/HyrTGyDdSiwcD5_NjcD3nZSXslSs86_qTXL1e8tAcKhNTna78MAMWxS8EfQGOerKJCr11h3nKczGF4hCtmEREVwR7mWw4ZrccmmZfvmMwwDc=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-164814.jpg"],
      },
      {
        number: 38,
        title: { ko: "H3", en: "H3" },
        location: { ko: "마츠야 타이헤이 거리점 옆 주차장 정산기 지붕 위", en: "Atop the payment-machine roof beside Matsuya Taihei St" },
        reward: { ko: "어깨 패드", en: "Shoulder Pad" },
        image: "https://lh3.googleusercontent.com/9k5tjgGRsETkwhGnQXWm2BwEtVp5veAQ7XIVY4jUynIX_-X6RFgiQdTcXPbA41qV3hIXLCNVNAYVsEb-PqBW8ZZr3M-ooTBunETXHVSHj-do=s0",
        images: ["https://lh3.googleusercontent.com/SEbNPBTs9wstIu53UggzvS6b4Fchdla3Lzkb7COb--V_-otg3JFmNx3kUBj0uUSEGSdyWOjoZxJLo72HcOYV0j5luvE4c74x6o9OQwaVKZn0qQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190120-050215.jpg"],
      },
      {
        number: 39,
        title: { ko: "H4", en: "H4" },
        location: { ko: "극장 앞 광장 영화 간판", en: "Movie billboard at Theater Square" },
        reward: { ko: "은 접시", en: "Silver Plate" },
        image: "https://lh3.googleusercontent.com/JPs12htG2JA_5EAfnTHSz1QwMDHkYFlOTQDjDjPEHmgbQvgmPm2CYaF0X4lPecKkcedZ8SPPdNRFHoIU7c8fuHld73rfqPI5BRRMTGdacyg=s0",
        images: ["https://lh3.googleusercontent.com/PlR5EZrlUtguQoeIqyZd-PhMzAaSFadDjgqSRN6-qrFLF1lHcPkh8NMdBkI4-arFhpkZjaSy0S6AKdDBzntDEo2kQFYrN-p-35OgW4rr02A=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-185449.jpg"],
      },
      {
        number: 40,
        title: { ko: "H5", en: "H5" },
        location: { ko: "아시아 거리 후루사토 뒤편 골목 배관 상부", en: "Upper piping in the alley behind Furusato, Asia St" },
        reward: { ko: "렌가의 청룡도", en: "Renge Blue-Dragon Blade" },
        image: "https://lh3.googleusercontent.com/RUtQb5UPM43qhhn3B4cmn3djjbELXX2DzQdQnshC668kvDbT13g4-eE6mwSp6wNjSZzIGW7VZHkg_Lpt4xNBJ2oBRFznTo8VpNfYsgJ0q3U=s0",
        images: ["https://lh3.googleusercontent.com/JQBbkdp4bHehNQ_ElKkQdx0Ukx0fzDhPNINCbceZ73NgWBQtPJ0mw-75UfnWYGqCuHpZ2VF-kFOSldarcFOi15l5hgEic9JmJJhxlzRGEqaXAQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-184958.jpg"],
      },
      {
        number: 41,
        title: { ko: "I1", en: "I1" },
        location: { ko: "시치후쿠 파크 서쪽 밖 CENTURY 간판", en: "CENTURY sign west outside Shichifuku Park" },
        reward: { ko: "아오다모 나무 조각", en: "Aodamo Wood Chip" },
        image: "https://lh3.googleusercontent.com/lbf1dFDYQEjEca5ecqByYd_pN3R4WsT5MtGvCbTzfAli2thKHiXWkyEt0NNHNQlo_uIuhU2Y9HWqBa2pYs8V3YgHZcvSJbJQ_SozhO3ClOgn=s0",
        images: ["https://lh3.googleusercontent.com/bzxfnAy7R9zWBxu8gEBzg-1G2C3z0TTZTFvrMWItZpWFRmKkRPrxGNOLplEqPZasrIvDgBOGBdI4INwf7dkLWpXvTEhKxPaosSU6MF7T-5Zb=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-131645.jpg"],
      },
      {
        number: 42,
        title: { ko: "I2", en: "I2" },
        location: { ko: "극장 앞 거리 볼케이노 쪽 자판기 앞", en: "In front of the vending machine on the Volcano side, Theater Ave" },
        reward: { ko: "합성 폴리머", en: "Synthetic Polymer" },
        image: "https://lh3.googleusercontent.com/TFxZsJxPrKR3fFu05ToqPRLdC4qWVsJN74JLX9cxj2uT-0slwNeNRDKSbws6-2iJfXOgUGP1X1Fc-NaED4MtzxfCdAwGS6m1ShSiQhSgCm0=s0",
        images: ["https://lh3.googleusercontent.com/hYdQGaO69LWJ9CL4NKTsLZzr_L8cbdY1JbPY0SMzGmSJcWR6Ev7xvptmKPaf-HTo6OEUAffUOtvKd0-GDlozPJXUUachkdLLegJUrFjaSFA=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-181427.jpg"],
      },
      {
        number: 43,
        title: { ko: "I3", en: "I3" },
        location: { ko: "카무로 극장 에스컬레이터 옆 쿠로사와 간판 위", en: "Above the Kurosawa sign beside the Kamuro Theater escalator" },
        reward: { ko: "개조 라이터", en: "Modified Lighter" },
        image: "https://lh3.googleusercontent.com/sCCMJUUAl0VsKSUto3NJkTdmBbUibq-ag9P4poXQmgZWikkL4Atfeok3Ok0ohbBI0YY1noI_2KXim_jNrHafU7oAHvG1TTziF2XKzXVYWbE-=s0",
        images: ["https://lh3.googleusercontent.com/t5i0GkPGiD9T7zkXqBQ2l3BBgqA0SdTm9f1xHux_qn4nV2HcxlPA6A-yZ7xV-oTQ2-PK3hPWNEMFvy5BtbqpYkeJDn0OFdXy4WQK0V1Ioo0x=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-185708.jpg"],
      },
      {
        number: 44,
        title: { ko: "I4", en: "I4" },
        location: { ko: "시치후쿠 거리 Jewl 옆 커피 남작 간판", en: "Coffee Baron sign next to Jewl, Shichifuku St" },
        reward: { ko: "카리스마의 사진", en: "Charisma Photo" },
        image: "https://lh3.googleusercontent.com/8X5BuJLT9qPBCt_uWzXBt3qZZvdGH8gVlnr6-gHCYr4jQBAD0NY90cTM_3aanS07Hernv84AdlTDnUjOzX6fytwMg6o8Hpqcb_xBswwx-ctD=s0",
        images: ["https://lh3.googleusercontent.com/YWIMFb3luoOWlQ8_B80Kr344uwfJOoyVv64LYahSw1js4RArxBaulz3jznAralZHwQUj1H8egPe3OpVkMi6TlsdaYZya0gc_7CAYasc6R4w=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-152626.jpg"],
      },
      {
        number: 45,
        title: { ko: "I5", en: "I5" },
        location: { ko: "극장 앞 거리 모바게 TOWN 간판 아래 처마 ※밤에는 제브라맨 간판", en: "Eaves under the Mobage TOWN sign (Zebraman sign at night), Theater Ave" },
        reward: { ko: "용의 인장", en: "Dragon Seal" },
        image: "https://lh3.googleusercontent.com/ddmX2eVcsUH_usYug8UltvAFFFHHMwTMywHU4H6cERCNcz-yUyb8UwwymibSmZNNKS9HiWZ4osV97JuoQlVMmpcq9TQ9tJRZ8vvork6_4Ak=s0",
        images: ["https://lh3.googleusercontent.com/sHPwyuRCQJ9RKOyxY-EELH--DbuL7Pn2yI18FM1iztiaNz2bRO6ZYG0wKCwpiyoowgmYMrgBU6Mb8PFjMEIFWYSH6kMn7jeJ6ztfdxKj1B0=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-181222.jpg"],
      },
      {
        number: 46,
        title: { ko: "J1", en: "J1" },
        location: { ko: "핑크 거리 동쪽 카무로초 동쪽 옥상 오르막 입구 근처 쓰레기통 앞", en: "By the trash bin near the east-rooftop ramp, East Pink St" },
        reward: { ko: "히후미 껌", en: "Hifumi Gum" },
        image: "https://lh3.googleusercontent.com/Ov2AbFKVk9bQWFusLllQPBBdriz3ikO5xb0w4Y4TsK3nzeQMbwZvZfxPMUkxJepQTQlOLHTdAVEXGeLgOGJ5EiI1a2MnOrMoHmWp9JO2jswaiA=s0",
        images: ["https://lh3.googleusercontent.com/qL0ZqRBKGvxsxy2Tne-iAZbxsidEVPg6yFIwCiWvcdP6-81u2lr7EPN5yTCBO7u9CbitQ17IWwmJ03vpr22mtFDd0fDIjG_gM2pjf_906Bq1=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-190256.jpg"],
      },
      {
        number: 47,
        title: { ko: "J2", en: "J2" },
        location: { ko: "류구죠 도박장 계단 바닥", en: "Floor of the Ryugujo gambling den stairs" },
        reward: { ko: "거대 비닐 인형", en: "Giant Vinyl Doll" },
        image: "https://lh3.googleusercontent.com/i1P0m9NHhDjWdwLhRKsLGLobx_DesU2Hb4RPnxXVXSUglGU3cliLtXAIAXdXttFw-hBzd2B8la_Yb2Aw6qjdKZwI8Lraye_p8JDLu90EnPUV=s0",
        images: ["https://lh3.googleusercontent.com/xmGVcwXiypDRSvCAk8FKKWB5l7U0EWjZzd1WL3o_RIlm_W6-YkoMnRd2g6FOOV29FLWeGNDULYKnd37IALoeaOBNxkLVw0kHElmhV1p7zg=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190120-044506.jpg"],
      },
      {
        number: 48,
        title: { ko: "J3", en: "J3" },
        location: { ko: "요시다 배팅센터 내 통풍구", en: "Vent inside Yoshida Batting Center" },
        reward: { ko: "고장난 라디오", en: "Broken Radio" },
        image: "https://lh3.googleusercontent.com/yqJhGvHnJ1_KkJXJqvQfA39J_8An0G1vBiArrsVjU8mDupw5nmUv3F67h2iqYLZS0yumHjjDCR7r4aqRJmmvJOB3Uet6Qq8F6u9jU0dtIAkK3A=s0",
        images: ["https://lh3.googleusercontent.com/rakiZNBX_wYrMl5qU3ZTdFxxDwUDpMFRj4MRgb90GqF50InBYA2K4TFFm-NO8C1e1Sn0MwDvOyABVKBRZQYRCPAw2IMkM1j-jHGe_4Ge05I=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-133452.jpg"],
      },
      {
        number: 49,
        title: { ko: "J4", en: "J4" },
        location: { ko: "마하 볼 점내 정면 안쪽 금색 핀", en: "Golden pin at the back of Mach Bowl" },
        reward: { ko: "루비", en: "Ruby" },
        image: "https://lh3.googleusercontent.com/UZDsU55sCqSbkQ5ErOgybem5aqTdIGcPnlMq6aASk5-GY9JMpGKRMotBvbuX6RkvZcTE35MkxgB5hHlWMPSDQOz20XOgogyg6VoFzbEmtmdGkg=s0",
        images: ["https://lh3.googleusercontent.com/3ImCZBVRjq6O6Gig3l4mdSR5Uq7v-rzNOCmOO0_MvZIWT_5UZAyKbRsDGzuWIShW7qPOazvoTK7BhZhp9FQjnz-JGFeYcqyWKXKkuybUAEWd=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-165051.jpg"],
      },
      {
        number: 50,
        title: { ko: "J5", en: "J5" },
        location: { ko: "호텔가 호텔 Volescia 앞 전봇대 위", en: "Atop the utility pole in front of Hotel Volescia" },
        reward: { ko: "아라시의 양갱", en: "Arashi's Yokan" },
        image: "https://lh3.googleusercontent.com/0HTS-6oIdgirafXmTsKmiKb7at9mYkeu6zvlVUQYJef9I8Yj6lW5EI9qugDOn-ppfJZgLnrto4X9ce4Z89N0dVUoQgC9e03-nbXIsDm6FJoX=s0",
        images: ["https://lh3.googleusercontent.com/QZbsoXba_-G6pHhAOoFdI9Afo6hEZbOXCrzVk-0YjuSufJ5bmC3Y48OXq2Jvh0795YL1azAGte3m0q6wKSAI5e8d6g6Ua67MfPfT_O01Lkc=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-190538.jpg"],
      },
        ],
      },
      {
        title: { ko: "카무로초 지하·옥상 — 50개 열쇠", en: "Kamurocho Underground & Rooftop — 50 Keys" },
        mapImage: "/yakuza-4-lockers/underground.webp",
        hotspots: {
          "1": [45.68, 13.56],
          "2": [89.62, 76.99],
          "3": [7.95, 52.36],
          "4": [80.98, 86.44],
          "5": [70.38, 30.22],
          "6": [62.2, 54.1],
          "7": [22.65, 40.17],
          "9": [11.59, 30.47],
          "10": [21.59, 63.56],
          "11": [12.65, 41.92],
          "12": [30.08, 7.59],
          "13": [58.56, 54.1],
          "14": [7.8, 25.25],
          "15": [66.59, 70.77],
          "16": [88.26, 70.02],
          "17": [70.08, 42.16],
          "18": [66.59, 67.04],
          "19": [26.14, 18.28],
          "20": [82.95, 57.84],
          "21": [20.68, 73.76],
          "22": [26.59, 31.72],
          "23": [65.08, 77.99],
          "24": [70.83, 24.5],
          "25": [82.5, 83.71],
          "26": [56.44, 69.03],
          "27": [31.44, 71.77],
          "28": [19.02, 92.16],
          "29": [97.95, 68.03],
          "30": [92.05, 44.15],
          "31": [28.11, 38.18],
          "32": [75.08, 19.03],
          "33": [50.38, 39.68],
          "34": [66.89, 19.53],
          "35": [59.92, 71.77],
          "36": [66.29, 89.43],
          "37": [61.14, 77.74],
          "38": [19.17, 38.18],
          "39": [82.35, 28.98],
          "40": [45.83, 76.74],
          "41": [84.02, 53.61],
          "42": [82.2, 72.76],
          "43": [48.11, 81.47],
          "44": [61.14, 83.46],
          "45": [64.17, 87.69],
          "46": [10.98, 64.55],
          "47": [89.17, 9.83],
          "48": [32.5, 79.23],
          "49": [76.74, 96.14],
          "50": [83.56, 65.05],
        },
        items: [
      {
        number: 1,
        title: { ko: "A1", en: "A1" },
        location: { ko: "카무로 지하상가 동쪽 카무로 중앙 주차장 입구 앞", en: "Karaoke underground mall, east — in front of Kamuro Central Parking entrance" },
        reward: { ko: "형상기억 스프링", en: "Shape-Memory Spring" },
        image: "https://lh3.googleusercontent.com/rVJFt4blTkei93Pm44gKVzyIg3B8N3wF-DnmFE81o2zgJz2j9wxq3mhg2aL8CkeJmMRfT04RCCLXqrk8Y2_TQ2Jm1-U5T0xBOoA1Gc0W6Q0_=s0",
        images: ["https://lh3.googleusercontent.com/7MrNdfxVt7lK0j7Nvy2zOdGFF_nT-6aUF7Of5mZqVrpXK14c5zIBMsZGzgrhWuc0aklt67HJ6IOTe0N1eIqlfhDNlJMdClc2FmpChHEnkL17=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-182905.jpg"],
      },
      {
        number: 2,
        title: { ko: "A2", en: "A2" },
        location: { ko: "카무로초 동쪽 옥상 배전반 위", en: "East rooftop — atop the distribution board" },
        reward: { ko: "합성 폴리머", en: "Synthetic Polymer" },
        image: "https://lh3.googleusercontent.com/NDHqbKLgJodtai02mNLE_6JCarbaKMp9XsSpewVuyK1t9LHL3KyIeuQat1xbbZQrO4CfHWe8mXJiiRBeI2oxL5NTt-lUklDCAHTDmuLPNhaR=s0",
        images: ["https://lh3.googleusercontent.com/ASnBFjYiiXuqcnuTsV4Xrs3Wm2IwEdVxC2FZ7zk6FJT67hPviEz8J1R18Lkt6zQiIVjGEfAToXL-GIIqSuBrnhoqxE3TWAmC2Y_4UgnNFelMAQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-191753.jpg"],
      },
      {
        number: 3,
        title: { ko: "A3", en: "A3" },
        location: { ko: "카무로 극장 출구 계단 아래 바닥", en: "Kamuro Theater — floor below the exit stairs" },
        reward: { ko: "호피 가죽 벨트", en: "Tiger-Hide Belt" },
        image: "https://lh3.googleusercontent.com/7wqoVQ2lgns0nMVoa7iLkv75pgMvOlQ0W4ord-FrM33L_ilL7yYCoCszfyVTqZSgHRp-mmR_g75_2VueJ52ybvvait1Ygbq0yhURukQSOlJM=s0",
        images: ["https://lh3.googleusercontent.com/EV4jH_bT24vUgwMJcmh6veQTDZoTtQo0Ik_LEgqVAw62RHbqjrbzvD5nCcVrNokGetEFLX6fUe63FWMIJaa3jAl2S0dpZeif5qfIwfr3ziJZ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-192303.jpg"],
      },
      {
        number: 4,
        title: { ko: "A4", en: "A4" },
        location: { ko: "카무로초 동쪽 옥상 저수 탱크 쪽 울타리 아래", en: "East rooftop — under the railing by the water tank" },
        reward: { ko: "고장난 라디오", en: "Broken Radio" },
        image: "https://lh3.googleusercontent.com/CXajToLYjSS5k87TFItEzxPtAEVtn-sqMnc-RaORl1mGw64vyKSeHj67bElgH6Ntd5Yrmy7yWS-z8-RSmSq3NsazxUlFVCzy7P6AG9gscMez7w=s0",
        images: ["https://lh3.googleusercontent.com/nY04T_n0msSXg8uRm8_tcN0xOsNwVlg8UfmDaEe2E2SIfp_Lu9jJEWvctRBnjKoY3J2FxkmhVbgHIO2inwwQ15GuhdZvr4yDMzseYm6Hulpsyg=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-190905.jpg"],
      },
      {
        number: 5,
        title: { ko: "A5", en: "A5" },
        location: { ko: "중앙 하수도 중앙 다리 조명 아래", en: "Central sewer — under the central bridge light" },
        reward: { ko: "휘두르기 부적", en: "Swing Charm" },
        image: "https://lh3.googleusercontent.com/gkVIxgdxE8-Fd4dzPbzupbKNm5QeE3TNe7ckU8GdMbduzaWEC2GgnS59ptsM8gpWveymUi8uTn0RgmNC6fy44KR7wHigMTGtSOVO6nxWM2s=s0",
        images: ["https://lh3.googleusercontent.com/qAecYD8LYF34Umfi7AppYLhyb1yNM8J-_owrdp0Ni80Gc76-SQk_WELfMaa32LaJD2kkgEvdvvVEmKB1SeXyPN-F1hgEfs-qj4EdQDZqdBEl=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-172018.jpg"],
      },
      {
        number: 6,
        title: { ko: "B1", en: "B1" },
        location: { ko: "카무로초 서쪽 옥상 사이고의 수련장 바닥", en: "West rooftop — floor of Saejima's training spot" },
        reward: { ko: "스태미난 로열", en: "Staminan Royal" },
        image: "https://lh3.googleusercontent.com/l9vqfsW5NQKr-uOwfpB0lnJEGMla0HiuD1zi_8f3fbZID7uZ9GnKwOJf87E4tRTDpIn6dOdPwFzzb-kDg6YNHlvNEQp2lAcjC4fkvlsEqrmBKA=s0",
        images: ["https://lh3.googleusercontent.com/yKEf3aEwAgSy2pxgKsbAPXY4BNaOxQt16lL_Hmk-2ZXwPuWIXViuI5T98NZE2PkVKbXOaDapDZjhDgfsyzJErELoB-bsLWDBu_4fkAyPBM0=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-151008.jpg"],
      },
      {
        number: 7,
        title: { ko: "B2", en: "B2" },
        location: { ko: "카무로 중앙 주차장 208블록 부근 바닥", en: "Central Parking — floor near block 208" },
        reward: { ko: "로열 조커", en: "Royal Joker" },
        image: "https://lh3.googleusercontent.com/Hnk-18Omxh389yrAVwISCD8egdp3zYffCFupyArF973TgN7Oa_pYr_P1hpGv3H5MnkOiinbJVgHEZV3Y-5PxZ4Inel7C1L5-QZou0z0n9FMa=s0",
        images: ["https://lh3.googleusercontent.com/uvSno01oXdGQe52CYFY094nJ9N_MB8t8S_Vs28UNFrgLwv6ONzlE7ZopMoSn_ZOoe8EHCpC95p2ia0hwB3jnCpNcMWAdhVUl-Zhs3AYhhZYYhw=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-173230.jpg"],
      },
      {
        number: 8,
        title: { ko: "B3", en: "B3" },
        location: { ko: "극장 지하 B1 서브스토리 「고양이와 노숙자」에서 입수", en: "Theater B1 — from substory \"The Cat and the Homeless Man\"" },
        reward: { ko: "5만 엔", en: "¥50,000" },
      },
      {
        number: 9,
        title: { ko: "B4", en: "B4" },
        location: { ko: "카무로 중앙 주차장 북서쪽 남자 화장실 안", en: "Central Parking — inside the NW men's restroom" },
        reward: { ko: "대자성 금속 조각", en: "Magnetized Metal Shard" },
        image: "https://lh3.googleusercontent.com/xUwFpfz_BjZjjpNwxwwZjkS62TT5pehzRAjzBukN0cXpwg8sOSbXafCk29fHPEernFkD4p1PdTbr9UXVRsPz8cpMjWOoZAFvPr0dUf90IbKd=s0",
        images: ["https://lh3.googleusercontent.com/6sEJVHAjzGYst8Mi8DuWy2FQphOtn9nHlfd5PXyElZpW2ZacoPUSrkzjCRkf3DxAtLBaeNUyDNRu8KQanBG-PqsDcsFOoWZY2XjuO96YMPAh=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190120-053618.jpg"],
      },
      {
        number: 10,
        title: { ko: "B5", en: "B5" },
        location: { ko: "극장 지하 B1 에스컬레이터 위 나무상자 위", en: "Theater B1 — atop the crate above the escalator" },
        reward: { ko: "핏물 든 천", en: "Bloodstained Cloth" },
        image: "https://lh3.googleusercontent.com/GWdpqUL0I-UR22nx2roRRUM-XUGKnn-RVa_xS7DQBEMn-wmiw3p251f2QRaZiZow-HoM_FGegAuYWP_An-lqCaPAG7sF0qk4GYn7dP1E-XU=s0",
        images: ["https://lh3.googleusercontent.com/r0OSPyC357MDjMtM8B-E0bfNh8IQYbPxwydF50kU7xTq2zdYIFN3gwhTZ4WDBvWP3MhbqdcEfcBak8Uqx_oc5h6zgPM79rYYsCc21gJFDTHW=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-192610.jpg"],
      },
      {
        number: 11,
        title: { ko: "C1", en: "C1" },
        location: { ko: "카무로 중앙 주차장 102 기둥 부근 바닥", en: "Central Parking — floor near pillar 102" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
        image: "https://lh3.googleusercontent.com/i0rG3o-hX9G60rTreA3CtzBKlvIZ4KdG0ZvjHAB28pOYF5YivLscjr21TaFUYCQjmkTZjpkghvgEuz0vHsDytCLxEbJIPoVaXHAfgeNQ89QWaA=s0",
        images: ["https://lh3.googleusercontent.com/64h6tMcoH8J0fwJbk8bPiWxUdp06PZO4LsLq6El8d9kW8sdoit1pyXkjZuuGUQYd5crLlckj8qpt4enVkmPhJ3iWPdcryaGLisiEWDglwmf2=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190120-054308.jpg"],
      },
      {
        number: 12,
        title: { ko: "C2", en: "C2" },
        location: { ko: "카무로 지하상가 나카미치 거리 방면 출구 앞 바닥", en: "Underground mall — floor by the Nakamichi St exit" },
        reward: { ko: "강철 레가스", en: "Steel Greaves" },
        image: "https://lh3.googleusercontent.com/4e46AacBJqXMryl9lIWVPrAyYiHQ4KXd-bFaPm_1xhJ7inpMMqwgjkF5epbuAcEMw5l_nDRvXMWeP64hj-BFZ_UNvPXlQjyVTPlqp7C15cQ=s0",
        images: ["https://lh3.googleusercontent.com/4gjI_3ig4hyIA6qrkNgxBmiZWeRcF4hOg6THHy6GRJlOTa0yrefgls848DcivBh9eqjHjdTIFQFXvKx7mMqhxg1yYlpyol5OYdm_aQnMstMZGQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190120-054426.jpg"],
      },
      {
        number: 13,
        title: { ko: "C3", en: "C3" },
        location: { ko: "카무로초 서쪽 옥상 사이고 수련장 앞 LoveBrace 간판", en: "West rooftop — LoveBrace sign in front of Saejima's spot" },
        reward: { ko: "포켓 티슈", en: "Pocket Tissue" },
        image: "https://lh3.googleusercontent.com/RgEw7H1o_f_OBxLv84oEHLIUKr5nyEGG0cPWyJxLZKDplAL-8BnuMgYBfqKpE9DnXoty70W_GXMKknaHgvh_qoyjCP06s1AWilzXobQizPQl=s0",
        images: ["https://lh3.googleusercontent.com/lUiDhtI1t1YGG4s3Z8kkJkYaJgyOs37_f1NUT2eUGKnXN65VbPuWJR3xdsx9FE1QPwFZg0ZvU1AC5ezprETd9DXsvjiNrxb95dAK60U8tdo=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-192911.jpg"],
      },
      {
        number: 14,
        title: { ko: "C4", en: "C4" },
        location: { ko: "카무로 중앙 주차장 북서쪽 요금소 안", en: "Central Parking — inside the NW toll booth" },
        reward: { ko: "중력 변환 장치?", en: "Gravity Converter?" },
        image: "https://lh3.googleusercontent.com/qCd_uHKULTi9vtLz_X5yCIR9nwmV2FxnGj09q4nnyZQ1yZnas8RJR08diq9MPJkEWt2zPhioq1iB8XzjjhnSFsCMJjd6IuqTy5ANugGUnIEd=s0",
        images: ["https://lh3.googleusercontent.com/egULgQGfSaGtimLRC-7AFQbZTs5iII9RbZeXuGtzIVcRw8KeIvxYCmSIAe7_ey3MvUFg89SUs19WEph8efJUR6yXPwBIrQpqi1LJrR-z4SA=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-195102.jpg"],
      },
      {
        number: 15,
        title: { ko: "C5", en: "C5" },
        location: { ko: "카무로초 서쪽 옥상 분수 광장 계단 아래", en: "West rooftop — below the stairs to the fountain plaza" },
        reward: { ko: "WAT 사양 아머", en: "WAT-Spec Armor" },
        image: "https://lh3.googleusercontent.com/DUVqwCZQDYCFp5bwXg5Jx83f49P_omU0YjGDnspCnf9U27CSnMl1XtbEqESPW5Sk44YIip3gPo1PMqHVBSsYm48nLTMk8I5-qufPeDIUQhw=s0",
        images: ["https://lh3.googleusercontent.com/fL2tzvpKitcit52nKFHMjFdZzXEF4V0vZKurBTwBlIY9M6dUpj_El3b1kOUiOQb_L8KX0mesWxz7GVfI3Pjkl7eIFBdkqfVsbWgU0rhobt0dag=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-194633.jpg"],
      },
      {
        number: 16,
        title: { ko: "D1", en: "D1" },
        location: { ko: "카무로초 동쪽 옥상 핑크 거리 뒤에서 올라가 오른쪽 녹색 바닥", en: "East rooftop — green floor right after climbing from behind Pink St" },
        reward: { ko: "고대의 철강", en: "Ancient Steel" },
        image: "https://lh3.googleusercontent.com/Xdvk5JIg6fElEGDZEjuguVRDDSaSYwG2oZ8n12sm1oligI2leE-qTN1AtyPbs48Zv0mJznmjBd_KTPJQj9yLii_oLEWB9A7_RPiFEuT1IeJa=s0",
        images: ["https://lh3.googleusercontent.com/UQKEUIn6Ven9PM3EFxdHKyoHhrfpIN0dBm-w4e2wUkSC89qiH1mq61nErgthA5QNnDHHikipi6XqoS8dWesr6EDwFeRTa2FFasrWZJONRdp4YQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-191452.jpg"],
      },
      {
        number: 17,
        title: { ko: "D2", en: "D2" },
        location: { ko: "중앙 하수도 남쪽 하수 안", en: "Central sewer — in the south sewage" },
        reward: { ko: "고대의 철강", en: "Ancient Steel" },
        image: "https://lh3.googleusercontent.com/D_S5x8-tkKhikhZRlH_ZAXcTYvHp-1B40sCevC-dbvBn2b940tH30-gFWKQiKqLZQq5I-fNlbYWGuJDiwsy5H4PJXWa-cIBsxhj4TvazCA0n9g=s0",
        images: ["https://lh3.googleusercontent.com/a6weYcJWMRGAHWmZq4Bf3y8ECtuBzsb5vQnqPnCgpEBp27t5Tef72IDJzD6v_546hCDuvGWOA21QMyXJ9OrEM3LN2u_rV28z83xF651otcI=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-172319.jpg"],
      },
      {
        number: 18,
        title: { ko: "D3", en: "D3" },
        location: { ko: "카무로초 서쪽 옥상 분수 하단 물속", en: "West rooftop — in the water at the lower fountain" },
        reward: { ko: "사우스포 브레스", en: "Southpaw Bless" },
        image: "https://lh3.googleusercontent.com/tzy5sJJAk9Ju6Fe1P6ntaLvTMO8AZrkl9i568OO9Cngc1zwMWI_D5eZHfKwizkLVBlnab5KgWkRExYZzdxFlw3c8raA-xsVl8oxeylvWcVs=s0",
        images: ["https://lh3.googleusercontent.com/fU3R3j-5wIxssGYgNhpu5zn6uHjXjhuMP8C5nwS80-IQfUX8Jk8TpCGknJ4zUW1sXA9MYwq0RzABDDoNyDUHpVWfJuSPvUH2Ps4p1iebzPqN=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-194836.jpg"],
      },
      {
        number: 19,
        title: { ko: "D4", en: "D4" },
        location: { ko: "카무로 지하상가 CuezBAR 점내 당구대 아래", en: "Underground mall — under the CuezBAR pool table" },
        reward: { ko: "숀벤 산맥의 돌", en: "Shonben Mountain Stone" },
        image: "https://lh3.googleusercontent.com/Q3Y5n-qnpGBT6W8rewwUGx2hF9UQReiotXdsZ-8IQ0fXxESSag62sbi7EBzZIRPwDNXjT8G5Ti2Lt36_utcy39TvCKbIbmOouvcYgtt5pGY2Mg=s0",
        images: ["https://lh3.googleusercontent.com/o1iI0FEv92Z1jzcDr-8e3erEIhSSuuAdVkSdy4mRMwJ5WLo15D93FHsyoN9Smd6v2RBvQnjBI2nJn4xmNkTSEuDxWnP7tka2-jjpwML660GA=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-182546.jpg"],
      },
      {
        number: 20,
        title: { ko: "D5", en: "D5" },
        location: { ko: "카무로초 동쪽 옥상 DMM 간판 앞 난간", en: "East rooftop — railing in front of the DMM sign" },
        reward: { ko: "진주", en: "Pearl" },
        image: "https://lh3.googleusercontent.com/2wYUSyWAzyhP55JcgZcBN8yYKCcdRJfUdFRknhYDEFXmTWeUO6GsXmw2quM7l5dtXyNiTf8cNWZ6g1jkmSXTPoNOIimmqiCHBdDNuvUXkHPEbA=s0",
        images: ["https://lh3.googleusercontent.com/PMihvbX7Vi1KOTczTnBRqTW-2PlN8R5gkmQ2YtAGQIX4DTQaV7OB1G0mG894aMGXC9J6C2LYah9g9xXoksag3asB5S_FO15Fg0eNMVsvdjQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-201110.jpg"],
      },
      {
        number: 21,
        title: { ko: "E1", en: "E1" },
        location: { ko: "극장 지하 B1 IF7 방 입구 앞 바닥", en: "Theater B1 — floor at the IF7 room entrance" },
        reward: { ko: "버스트의 부적", en: "Burst Charm" },
        image: "https://lh3.googleusercontent.com/KuF1s1AsMJqUf7VrsBWEZEjGh9du0hN98P7Wpx3VomZQFw75Q8qX9W7J7B2ti5TOcik2cr_tpp9Nxzo_YVYEPMX8lzi7LdL7RYgLmLQq8Po=s0",
        images: ["https://lh3.googleusercontent.com/vRJ6ByLCCYwVgNfq65jl0ZgLjsLElznRyztYIYSgOySwMxryZCfEpAC5V46RrYS1pjiVGuhBXeJp0YtRl_ZDVfK4UYYV4Sd2qWcrXXUADeo=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-152623.jpg"],
      },
      {
        number: 22,
        title: { ko: "E2", en: "E2" },
        location: { ko: "카무로 중앙 주차장 천량 거리 출구 안내 근처 천장 배관 위 붉은 사각 부분", en: "Central Parking — atop the ceiling pipe (red square) near the Senryo exit sign" },
        reward: { ko: "카타요리사의 담배", en: "Katayori Cigarettes" },
        image: "https://lh3.googleusercontent.com/0ohtH7su4n2yA7aK403jWqDiX9n8vt9eTbbOgmLRZT28kd3VtYLM3gbg31523aMh_7HFYhLIr44ZP4EXXjI5mu6X91HMA16odZ-HbrXulF0-lw=s0",
        images: ["https://lh3.googleusercontent.com/gngUwbitgonY_Pp9JV6343tj3EBTb2shhzV8gMW_aUTiAtAt8OQ9-nnzTf753716_sI9Ax6shFEB7BZSlZYIhvj9DPq7F5SA82cFyXJnitcb=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-172826.jpg"],
      },
      {
        number: 23,
        title: { ko: "E3", en: "E3" },
        location: { ko: "카무로초 서쪽 옥상 니코니코 동화 간판 위", en: "West rooftop — atop the Niconico sign" },
        reward: { ko: "붉은 보석", en: "Red Gem" },
        image: "https://lh3.googleusercontent.com/5_GiCQ47RYhpmDuzFpfqs5Feu_LJEuKa4pv_FNa3x1YNa8mezqJQsjqoDAvu8PLZJWpgzUXRfdLLUvF6ztkRhPU8QUoHkoUNbM_TOKIS32Q=s0",
        images: ["https://lh3.googleusercontent.com/SNFsoGaNt8i3wq2I2C3fpEH-YdmK3U7JK02k6A6C-dzO1B7BZUGEqhN_R6XlaMmdMvjssoZSOfkZ0fN36YsvVEFWp379HiUaiYCz_xJQo_eB2w=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-193353.jpg"],
      },
      {
        number: 24,
        title: { ko: "E4", en: "E4" },
        location: { ko: "중앙 하수도 중앙 다리 북쪽 배관 위", en: "Central sewer — atop the pipe north of the central bridge" },
        reward: { ko: "히후미 껌", en: "Hifumi Gum" },
        image: "https://lh3.googleusercontent.com/f1837b5tCB2VRuLlHbop-aDs9JPgxeYq6d_wGYN0WUFDuJEOg3xyN377We-e9RErzvy6Ne7FujM9MqIWjDjNGRfIPsVSViZ4ruf_KDmTsnM=s0",
        images: ["https://lh3.googleusercontent.com/MnLOY1EoXXQM-597JPDRJxZijXPy2LWP1ePRN9ZE0m8-iDdDiSGcfGn0rI2GwgBZcTsUCMO-BmygmTTms1yezhuWsbraCszvGZKSlzuouJFG=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-204225.jpg"],
      },
      {
        number: 25,
        title: { ko: "E5", en: "E5" },
        location: { ko: "카무로초 동쪽 옥상 문 처마 위", en: "East rooftop — above the door eaves" },
        reward: { ko: "티타늄 드라이버", en: "Titanium Driver" },
        image: "https://lh3.googleusercontent.com/jRvVgd-ztxIkQF5DxFqZiPegoR0zeI4kidG0vXF8KZ07kyKw018TSG3L7V-zAiGZxR-UttF0o8fliQMr0Rb_kk6wlX9c4obJek9B9W0q_P0=s0",
        images: ["https://lh3.googleusercontent.com/SHdS-KoUt6kD0655GrMB2U_8VFTKzw5cMY6jEAammQBelBxa9ke_uU8LwtcMG0le5ygBofLxSCbXTMeFKS5Jirmfh8eI4DdY3Lt0Q9BRhQ649A=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-191130.jpg"],
      },
      {
        number: 26,
        title: { ko: "F1", en: "F1" },
        location: { ko: "카무로초 서쪽 옥상 급수 탱크 받침대 위", en: "West rooftop — atop the water-tank pedestal" },
        reward: { ko: "모노그램 백", en: "Monogram Bag" },
        image: "https://lh3.googleusercontent.com/wnNfSLKBBRpwRSwEVdIbavvAw7ONJdidqTPQ4935gbAm9a5WL9n5Enat9Sy_jtPZlh3FI4PFCjObbAVDQ2AvTunDzVyuSnhjpy1KHCB_Blc=s0",
        images: ["https://lh3.googleusercontent.com/S8UxO3L4wWIBRTeg1xNzV7GUlWDQ5uIzlChMexa2VcpIZXQxw0XwECk_mR9MSjcWWpzz64BdS0zUVadDWhZF78Sz8UaRbw6XEJvCiiwv1B7A=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190120-074433.jpg"],
      },
      {
        number: 27,
        title: { ko: "F2", en: "F2" },
        location: { ko: "극장 지하 B2 중앙 북쪽 막다른 곳 바닥", en: "Theater B2 — floor at the central-north dead end" },
        reward: { ko: "핏물 든 사라시", en: "Bloodstained Sarashi" },
        image: "https://lh3.googleusercontent.com/Zf26n9s2vGEKZ1Fpcw_QXmTfgA5PqYR8oDYC56HcAHQoYiTIbb3yxMzNzMJ2lHbkX1oHGS-eg8Zi2rogBNHRIPaiRgfuc0LQ0kXrgqmmOLxc=s0",
        images: ["https://lh3.googleusercontent.com/cIvYl2MjgEdAhMutID0o-y_tJZzuhANqNZOFh6HHSYbw6NRDTwoxNvu2AgUSODYWZNWRIB3K1aMrCc8daSex5_tjTCS4BC2z1ABKYZfs84X5=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-151757.jpg"],
      },
      {
        number: 28,
        title: { ko: "F3", en: "F3" },
        location: { ko: "극장 지하 B1 남쪽 자판기 위", en: "Theater B1 — atop the south vending machine" },
        reward: { ko: "BJ의 부적", en: "BJ Charm" },
        image: "https://lh3.googleusercontent.com/wDnuap-qbsVpCch8J_AyAe6aHR8y70r3E17xplyJp8teAN1d1wekvxSEKyfWjpEWWkkuKrHecHWaoXHmdB_Rd_IFODcDxuWASBH4fNYBaD4HJA=s0",
        images: ["https://lh3.googleusercontent.com/UVlqspud0UJmkUdCG4P4Wz5nk8uN5xuPDhZCr-V2biuneETChomsXT5x5lk2OFu9Z7Ihi4IQdyU9O5KWCrGyqxfqnjILmwVNAoIO9jMVTlk=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-152436.jpg"],
      },
      {
        number: 29,
        title: { ko: "F4", en: "F4" },
        location: { ko: "카무로초 동쪽 옥상 화분 앞", en: "East rooftop — in front of the planter" },
        reward: { ko: "앉아 한 방 패", en: "Sit-Down One-Shot Tile" },
        image: "https://lh3.googleusercontent.com/KPqOVzPNym1IcIHhaK4ARPeNmBoc6Hovx5LaXI1zXryKoe17GTlyN1GJtf-UIquctaZzXp89moITiRtNkAsTGuMBPJdPR2bIFpXtPc6-2EM=s0",
        images: ["https://lh3.googleusercontent.com/RYiO8pd39E6XoCTmyT-sX08-C6Qo3Nf6erOYLgW1iEsbe9tVtReQwOO0ZfKDDSUOgbOZ6ohkhEkETcm9O6WOad2iLQgo5mqSwRj6fyye81WM=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-195434.jpg"],
      },
      {
        number: 30,
        title: { ko: "F5", en: "F5" },
        location: { ko: "카무로초 동쪽 옥상 건축 현장 발판", en: "East rooftop — on the construction scaffolding" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
        image: "https://lh3.googleusercontent.com/zYn1C3LufrQS0q4Ld0vw9eYY3c6tgAXtUw9rRE2wtsJwiIXk4C6DehLo0h74NZqhwQCo3sc1TtcYzuJRmqq-JD_pjdeofNQgd5YAV6njr109=s0",
        images: ["https://lh3.googleusercontent.com/5HxZzYoJvZmuwDuGpogQBnyTt2vwoW4XTfuvAvxoEsTSIii_tYTdDu4yxG8kx2FKXacf7qPpkfIa596DzEt4AnKwCvfa_ddDDzbvsJSgvP2K=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-195744.jpg"],
      },
      {
        number: 31,
        title: { ko: "G1", en: "G1" },
        location: { ko: "카무로 중앙 주차장 111 기둥 옆 남색 왜건 아래", en: "Central Parking — under the navy wagon beside pillar 111" },
        reward: { ko: "금속 배트", en: "Metal Bat" },
        image: "https://lh3.googleusercontent.com/1UbqsJHcbYnniLuiRWCkMRUXYGSkgSR568Okvl-DuU6JJMMKPNWfIOntaYjB7EtXsb2vPJiI9QirUbdM5EoZ-hIr5h1thqyYh4c71kbulO3h=s0",
        images: ["https://lh3.googleusercontent.com/yL9uUHry10bOIifBV2ESZNvgM-3gd6UIy8Q4wQy1166GUPyLNq4BDXiZluykaG9A4sMzv-_BBeTNeokIXUx7TJh6pJN8kCySBGj_t0GYEeHK=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-173031.jpg"],
      },
      {
        number: 32,
        title: { ko: "G2", en: "G2" },
        location: { ko: "중앙 하수도 북동 통로 쓰레기봉투 앞 바닥", en: "Central sewer — floor by the trash bags, NE passage" },
        reward: { ko: "대자성 금속 조각", en: "Magnetized Metal Shard" },
        image: "https://lh3.googleusercontent.com/PXnGI-b1ul8RhHdxjSK2beN9Tli6_AxqOMG2efiOffCbRZjHMD0JLwOVLwJWUowzErQq9vwSf_RmRfAn4rOgc03ZQKtdJK_QuxL0SEzg5Lxe=s0",
        images: ["https://lh3.googleusercontent.com/yhN3921CHDinVrQagtB8TUUCEgtXn31Pfts48S12ZurIFy88xc8yQeADOs06ypXxxJdKlTCpptT5kiUzGXeqvqYR0DkG2izNBk4vZBnQNBE=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-171751.jpg"],
      },
      {
        number: 33,
        title: { ko: "G3", en: "G3" },
        location: { ko: "사이노카와라 지하 후쿠마덴 앞 기둥 부근 바닥", en: "Sai no Kawara underground — floor near the pillar before Fukumaden" },
        reward: { ko: "소형 모터", en: "Small Motor" },
        image: "https://lh3.googleusercontent.com/l8RrgxcriR6lUoAbAYFVyF7VvBKuPcZJmv_jpHAeLfZDXXOlkiPIezjj9WcsHL5TzO6wiPsS7yYbGtz6llFC9QAYGSO_9qL_PnhcYYMypu99VQ=s0",
        images: ["https://lh3.googleusercontent.com/qdWiJcdvCSn_f0yHrhE3p-Ao8o0YMxsMu_S1v7RuBPl3x4IFkLnp2iC21lB-6NcWGI1Upf2yf_JPnNs8P7RZR_J36hZ36OE4NIHbm5Cp-jpL=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-194407.jpg"],
      },
      {
        number: 34,
        title: { ko: "G4", en: "G4" },
        location: { ko: "중앙 하수도 센닌이 있는 곳 바닥", en: "Central sewer — floor where the Sennin is" },
        reward: { ko: "금 접시", en: "Gold Plate" },
        image: "https://lh3.googleusercontent.com/ld0hcXaJ8seOYOGJ3dQ8U8nSNFOUKfeyhr9YCIgLYIzT30JAet98EW0pzWXr2ULhFw4mt2O-1fDl7FWoYU99llcjrhjedW8UFVRMX5e_PQP2=s0",
        images: ["https://lh3.googleusercontent.com/MmGhQHsNjBSMUkAAiRtfu5grc7XW5Nvx6SFhXlcOozsjMF69NvR2pVw3gGEE0ITGmKgvQjfTfnNo7UERYTRrjYgCbptG-lYGBJbE3r3NO8NO=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-204510.jpg"],
      },
      {
        number: 35,
        title: { ko: "G5", en: "G5" },
        location: { ko: "카무로초 서쪽 옥상 건물을 잇는 다리 아래로 보이는 C-WORLD 파란 간판 위 (매우 보기 어려움)", en: "West rooftop — atop the blue C-WORLD sign under the connecting bridge (very hard to spot)" },
        reward: { ko: "수수께끼의 액체", en: "Mysterious Liquid" },
        image: "https://lh3.googleusercontent.com/0JgnxmQMEKlDoxWMpcC9avzMbnikcWLfENbEPxoKznczKeaf8o06jPW1pn0IUBommNL3TrXsBWIWXO5Ja41JbILKTZG9Ix5H-mJObnbdmi66=s0",
        images: ["https://lh3.googleusercontent.com/H1fQsXDn2dgW9iRokB0klVtR6nNLaZEjS735JDhr5XkMmWhxM1L_avYbr5OpTLK8hDuMqpvnEp1sVn7ya9vSF4Sz52yRiHZ_uZJbxjG37BOC=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-193650.jpg"],
      },
      {
        number: 36,
        title: { ko: "H1", en: "H1" },
        location: { ko: "카무로초 서쪽 옥상 바닥", en: "West rooftop — floor" },
        reward: { ko: "BLUE-FOX", en: "BLUE-FOX" },
        image: "https://lh3.googleusercontent.com/sT1T5PxLiOOVqjnTSXqX1CjQy5ZZNunplM9TU3-oN-NYBC21wSgP9zvpiq-foHE8XD3PhDzk2rr3uGmPaQKG_9v1h3rq69KpwX8UQFgcpxs=s0",
        images: ["https://lh3.googleusercontent.com/mUCi28dnGbErswz6khyKusthL8aP5BmQLxqj6rcJOsaq7aKbjWETNg6R5MH7KnJE7Mzqi3Yw_A-UmFSWlQZY8-dFbkQ_Dq-69Sa37Nl_yag=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-210554.jpg"],
      },
      {
        number: 37,
        title: { ko: "H2", en: "H2" },
        location: { ko: "카무로초 서쪽 옥상 바닥", en: "West rooftop — floor" },
        reward: { ko: "부적", en: "Charm" },
        image: "https://lh3.googleusercontent.com/K-5prejDeVm2v1Ye-SHdndGVN0Sk35-nt4BHpFa7AKl8S135vqh0w2V5_eqvzbnJEoqIP-ycGGER81SnWgnVGaZJ1xiyf2LGzZcrYp0KWQwV=s0",
        images: ["https://lh3.googleusercontent.com/UzcIrtgcfe3O-son45dKSlwwIyNplqCkm7Je2VobTENlRooXaI-8XjXDVf_2kg43NFIke56PvGu90qkFg2GRzVCIr5b2xN_6606EGkE02nqX=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-150621.jpg"],
      },
      {
        number: 38,
        title: { ko: "H3", en: "H3" },
        location: { ko: "카무로 중앙 주차장 중앙 통로 바닥", en: "Central Parking — central passage floor" },
        reward: { ko: "건틀릿", en: "Gauntlet" },
        image: "https://lh3.googleusercontent.com/omysnQo1-lYlfDX0iuQ2yevIlt60QpuXQhsNIKOxyoRHtNK9PbWN_FZH7nYiivmRXVpWcg9gCkwKDhZIlbUOBZ6yydd4_Sos-_HlNTQ3Iwc=s0",
        images: ["https://lh3.googleusercontent.com/5p8zoN-bdv_geFMkR27Z4uwG0ermj2XE-cD7D1x3qvoNsollWUv9DiOGwF4H1Kd7hPYqkyR_aRA8XTX-Ecqa87GqeXMzVV4DysT733JwT5RN=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190120-053923.jpg"],
      },
      {
        number: 39,
        title: { ko: "H4", en: "H4" },
        location: { ko: "북쪽 하수도 선글라스 낀 노숙자 머리 위 배관 위", en: "North sewer — atop the pipe above the sunglasses homeless man" },
        reward: { ko: "초고반발 수지", en: "Ultra-Rebound Resin" },
        image: "https://lh3.googleusercontent.com/5fMfODHw-eiQUXEKvuOdnnJ7mSq7SkppIB7XMD3DyqQYL10FAqTF_OHQyrxvIDV2frJmknld2P2alNl3hOCJU9Hq1tBIcrAoiksnvJ6AviSA=s0",
        images: ["https://lh3.googleusercontent.com/d3taFkXmfTLnlf2OTa29EZFr2PUU623BldwhZ1qCuIeP9_LMbBUuz6gufGt29Y629FqWSflJKdksoU_jz9CiaRKQJSeCPUgVHpMmYJAX5CDTiQ=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-213038.jpg"],
      },
      {
        number: 40,
        title: { ko: "H5", en: "H5" },
        location: { ko: "극장 지하 B3 변전실 형광등 위", en: "Theater B3 substation — atop the fluorescent light" },
        reward: { ko: "티타늄 코어 볼", en: "Titanium Core Ball" },
        image: "https://lh3.googleusercontent.com/2peXpGWyYIWaw8-JPjwcf6hI0WYnrOp8tlVc9M45yWluo8DzBFUsxG3ooU1XlTI50dQiYnlciCK8nDBKkPl14eY1D7LLbhObEyMzn7R8Ps29gg=s0",
        images: ["https://lh3.googleusercontent.com/0sNpI5D4750oe77f275JDP6j4WwM8C8KPhz_cAe7UD2j-o6bdr8GCBtldTrWLR2e4AiYCE59gknARtVLzRt3MQkXgFcskdkkk3pOfRiHjeE=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-212348.jpg"],
      },
      {
        number: 41,
        title: { ko: "I1", en: "I1" },
        location: { ko: "카무로초 동쪽 옥상 나카미치 거리 뒤 계단 옆 실외기 앞 바닥", en: "East rooftop — floor by the AC unit beside the Nakamichi-back stairs" },
        reward: { ko: "검은 보석", en: "Black Gem" },
        image: "https://lh3.googleusercontent.com/HL2YPjVFqo8WOZi9jJ3beENy-ZhHn3WuH24yuxBAd2ClaEF0AmycHyrCjWNnNaxOrDIc-8leto7fqzlps6ialnx-eG3uu_rGOqNQr8bh98WT2Q=s0",
        images: ["https://lh3.googleusercontent.com/F76voWvTHlxaRG05Yh3u94R1hMSOMNPVOlF704DxQEHING11wizclzJl4broSDbuOPVFoeidl5IVvRjMatGGukTdj35MuxwwIOcwOWUGDeuy=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-195646.jpg"],
      },
      {
        number: 42,
        title: { ko: "I2", en: "I2" },
        location: { ko: "카무로초 동쪽 옥상 무기점 남쪽 계단 아래 근처 바닥", en: "East rooftop — floor near the bottom of the stairs south of the weapon shop" },
        reward: { ko: "대자성 금속 조각", en: "Magnetized Metal Shard" },
        image: "https://lh3.googleusercontent.com/nstICt-pNhg3pOmgg084LdQ5xVJNzn5CiOWx-8naLCGFPmXMTcvYFT0wUL_y3TnIYnZCfdNzuKT28qJTiz4voKBm-E87zPyo0pVLsoTDrxAf=s0",
        images: ["https://lh3.googleusercontent.com/lKgQ_WVnCSNt6IhH7ywQ7x5mPy5y3RpbSssUrKOmM0JTWPI4Wc-AESJ-o4jSnCJT87rrqc8giO0cQnhb5Phb-5qN7_V4Xdz-RR4Hnh4il1wz=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-200117.jpg"],
      },
      {
        number: 43,
        title: { ko: "I3", en: "I3" },
        location: { ko: "극장 지하 B3 변전실 농구 골대", en: "Theater B3 substation — basketball hoop" },
        reward: { ko: "아이언", en: "Iron" },
        image: "https://lh3.googleusercontent.com/9OI2_eVprSImF4GsCposiIUowGgUYTzOHqvsvTR1Y8IeNsEDDIXQTdhcjcqIlX4D5WwLI-cj1ZBklG0m75DTzwOS6sNQVIZ_thBvp6bjt7eB=s0",
        images: ["https://lh3.googleusercontent.com/inEGJiTlT3-WGN_3xKUTZ2MpBuNKOGNO6U8o4HkMh0xqpvWspbUztTYF6SRKS5hS5ic07ZHqRpg30k3b5HR_MXn2qGHcgltr85xYTukiTK5GIA=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-212202.jpg"],
      },
      {
        number: 44,
        title: { ko: "I4", en: "I4" },
        location: { ko: "카무로초 서쪽 옥상 붉은 간판 뒤편 하부", en: "West rooftop — lower back of the red sign" },
        reward: { ko: "소형 모터", en: "Small Motor" },
        image: "https://lh3.googleusercontent.com/ArDU9AZdbKRZ6G5x-uBN7xuFZBZvxORtqxSioGqtuDb5qWujPunJ2fFIOCWo_0UiqpWDQXDvTi-wL1Oa9nERbNnZQgZTHPvbWF8HULKSOJ_4=s0",
        images: ["https://lh3.googleusercontent.com/HPBzuDMtXMY1uTG36m0UOXW3Z-CSetICE5swFGBqXoiFD6OtBLVPC6YMsiaADoB7Tmoh6Lxek6Wm4mJHGkB_je3vT-6UYuXNrBstZsG14fxi=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-210417.jpg"],
      },
      {
        number: 45,
        title: { ko: "I5", en: "I5" },
        location: { ko: "카무로초 서쪽 옥상 녹슨 계단 아래", en: "West rooftop — below the rusted stairs" },
        reward: { ko: "고확석", en: "High-Chance Stone" },
        image: "https://lh3.googleusercontent.com/sI2FbRb2OqrN82WG54D1gv-7sEN5yAMRfP-Y86kdEf6schjmHuiDhKoUIyKJcODZOunxnYm8Tf_12YB8v-1XAjXRDU7kGylA8iOK9wDh8Jfw=s0",
        images: ["https://lh3.googleusercontent.com/XinrbOTf6OHBuJH4uT3PqXM6-aSABz5mTJEC8CoF6BtZJCqVHPIFKzTu9IU-5bUIaBQP2iorEbEOuSfDe_yPWHd9kLM1BnhG4_prb10HwUY=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-210839.jpg"],
      },
      {
        number: 46,
        title: { ko: "J1", en: "J1" },
        location: { ko: "카무로 극장 통로(셔터 앞)", en: "Kamuro Theater — passage (in front of the shutter)" },
        reward: { ko: "RED-SHARK", en: "RED-SHARK" },
        image: "https://lh3.googleusercontent.com/uIfc8mvQuWbewwAFihDeilq9jeI8Xqkhb70M2Cre1ReswS5OSSuwGybUnNqUb8e4Sewy4OGxhchP2egbfbzVAH-BAYzAVbx5YLOKuEpMcNONjw=s0",
        images: ["https://lh3.googleusercontent.com/DLUeZocGW6QeAc6IF2z1ssJsMrjfAPl25PumhYJ69QKgzCc75ReWRUEmK0dj1pTZhAZvwPadKoHiuU-Qia-buArYl1baLCuutbMiJrw2dhwG=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-192050.jpg"],
      },
      {
        number: 47,
        title: { ko: "J2", en: "J2" },
        location: { ko: "북쪽 하수도 다리 아래", en: "North sewer — under the bridge" },
        reward: { ko: "중력 변환 장치?", en: "Gravity Converter?" },
        image: "https://lh3.googleusercontent.com/1FrwaHQ8wS5IcHnSE9P1ByXZAoYtnL8yWnJLt4Q5us69vGEvJPix-dQYwptDZXYF64FgWIYyGs_F8QroWxup5XdP276cGmrDodhbF8FYWhA=s0",
        images: ["https://lh3.googleusercontent.com/zmiNn_V0mM_Eujepu3n2FkXr2KWJ4RxImuVp6_n3su3hhVcPnQ-vb9ku9ADlUdP6Q5DiakcAl_tEiJ3p_DB1yZyeBprRHfEsa2YZP6waEBdp=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-160848.jpg"],
      },
      {
        number: 48,
        title: { ko: "J3", en: "J3" },
        location: { ko: "극장 지하 B1 부티크 키무라 앞 맥주 상자 안", en: "Theater B1 — in the beer crate in front of Boutique Kimura" },
        reward: { ko: "합성 폴리머", en: "Synthetic Polymer" },
        image: "https://lh3.googleusercontent.com/RlXgUZ2PXo0borNaLusafJjRGgJrFP5F5taWVTF0Yz4XMNmliJhI4YokbJ0M40qgze4eUE63kKHbLWoY73C3keFLUREaxlzho0R-aFFdic2p=s0",
        images: ["https://lh3.googleusercontent.com/04wRZ7OB8IC7hoq89K1Ecz6D52ff9IdVMUq_JqdlNPLBfTwpR6TPXkqCwnV1DeF6g4CL2q0F3XvQuMhDDtKw1sjpSZRthF3158JXaqd1u00=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-152205.jpg"],
      },
      {
        number: 49,
        title: { ko: "J4", en: "J4" },
        location: { ko: "카무로초 동쪽 옥상 나카미치 거리 계단 앞 실외기 위", en: "East rooftop — atop the AC unit before the Nakamichi St stairs" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
        image: "https://lh3.googleusercontent.com/W0I4wN6Atz_xJXEM0JE0ufJH3HX4z0T8jmwbAJb5HsFTrfEYC1b9ZtUcGD00TG_fgdrgNAHlwmX4bfV7IG2fMSixNQRSTJm1c_4n5mCAdRWV=s0",
        images: ["https://lh3.googleusercontent.com/JKxfwBhznHNRW6-kjkNXpPVfByvsaUFdxkkvwCrFv6gzTwKKKnV9n-ha4eGAW3udhibU_trzjxAlLyWCgN2O1Ip7gw64kNoP_ycZWlkAUoRV=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190119-195126.jpg"],
      },
      {
        number: 50,
        title: { ko: "J5", en: "J5" },
        location: { ko: "카무로초 동쪽 옥상 무기점 옆 통풍구 안", en: "East rooftop — in the vent beside the weapon shop" },
        reward: { ko: "다이아몬드", en: "Diamond" },
        image: "https://lh3.googleusercontent.com/SIWAConTpwnDVOFsT8ykGrmx_WS3j1Y99WwUzMICq9fMHXT7bW6hs9MnpslLBB4WDU50nnOIZiJWWVdMktaaRvkvHl5TDyjuIYfKooIK3BVz=s0",
        images: ["https://lh3.googleusercontent.com/G42VS_KosRIUolla0ztxfV-28Zkpoj8HdgjfQ6rc7hZAFYUDrfX4r0ZZm529EW23aPSyvakkp316iCwaCdPoYNtLn4gH_O4i-82d9Jv_Z6vXCg=s0", "https://www.hikarugennjinn.com/wp-content/uploads/2019/01/amarec20190121-200402.jpg"],
      },
        ],
      },
      ],
    }
  ],
};
