import type { CollectiblesData } from "./types";

export const yakuza0: CollectiblesData = {
  appId: 2988580,
  categories: [
    {
      slug: "mr-shakedown",
      title: { ko: "삥쟁이 격파", en: "Mr. Shakedown Encounters" },
      summary: {
        ko: "양 도시에서 등장하는 삥쟁이(미스터 셰이크다운)들을 격파하면 거액의 일시금이 들어옵니다. 부동산·카바레 시드 머니로 가장 효율적인 자금원입니다.",
        en: "Defeat the roaming Mr. Shakedowns in both cities for big lump-sum payouts — the most efficient seed money for the Real Estate and Cabaret mini-games.",
      },
    },
  {
    slug: "telephone-cards",
    title: { ko: "텔레폰 카드 90종 — 30명 × A·B·C", en: "Telephone Cards (90 total — 30 actresses × A/B/C)" },
    summary: { ko: "키류 편 카무로초 45장 + 마지마 편 소텐보리 45장. 한 명당 A·B·C 3종을 모두 수집해 컬렉터에게 보여주면 한 세트당 500만 엔을 받습니다. A→B→C 순서로 회수해야 표시되는 점에 주의하세요.", en: "Kiryu (Kamurocho) holds 45 cards, Majima (Sotenbori) holds 45. Each actress has A/B/C — bring all three to the collector for ¥5,000,000 per complete set. Cards must be collected in A→B→C order to appear." },
    tips: [
        { ko: "카드 워처를 장비하면 광나는 카드 위치가 미니맵에 떠 회수가 훨씬 수월합니다. 키류는 핑크 거리 뒤 컬렉터, 마지마는 소텐보리 동쪽 컬렉터에게 제출하세요.", en: "Equip the Card Watcher to mark shining cards on the minimap. Hand sets to Kiryu's collector behind Pink St. (Akimoto) or Majima's collector east of Sotenbori." },
        { ko: "세트 5장 보상 외에도 「절륜의 아키모토」 친구 호감도가 올라가며 추가 보상이 따라옵니다.", en: "Beyond the ¥5M payout, completing sets raises affinity with collector Akimoto for additional rewards." },
    ],
    source: [
      { label: "펑키게임 — 전화카드 (카무로쵸)", url: "https://funkygame.tistory.com/1804" },
      { label: "펑키게임 — 전화카드 (소텐보리)", url: "https://funkygame.tistory.com/1805" },
    ],
  },
  {
    slug: "real-estate-royale",
    title: { ko: "카무로초 머니 아일랜드 — 5구역 + 5억만장자 격파", en: "Kamurocho Money Island — 5 Districts + 5 Billionaires" },
    summary: { ko: "키류 편 부동산 모드. 카무로초 5구역(오락왕·전뇌왕·유흥왕·도박왕·예능왕) 부동산을 인수해 각 구역 매출 점유율 90% 이상을 달성하고 5억만장자를 차례로 격파하면 됩니다. 3장 이후 본격 진행 가능합니다.", en: "Kiryu's Real Estate Royale. Acquire properties across the five Kamurocho districts (Leisure King, Electronics King, Pleasure King, Gambling King, Media King), hit 90%+ market share per district, and defeat all five Billionaire bosses. Free play from Chapter 3." },
    tips: [
        { ko: "구역별 시장 점유율은 부동산을 한 곳씩 인수할 때마다 점진적으로 오릅니다. 시드 머니가 부족하면 삥쟁이를 격파해 거액을 확보하세요.", en: "Market share rises gradually as you buy properties. If short on seed money, defeat Mr. Shakedowns for lump-sum payouts." },
        { ko: "친구 단계 NPC 호감도를 끌어올리면 '매핑된' 점포가 추가 해금됩니다. 각 구역에 1~2곳씩 친구 전제 매물이 존재합니다.", en: "Raising Friendship affinity with key NPCs unlocks 'mapped' properties — 1-2 per district." },
        { ko: "최종 라이벌 금융왕은 5구역을 모두 장악하고 4억만장자를 격파한 뒤 메인 스토리 14장 이후에 도전 가능합니다.", en: "Final rival Finance King unlocks only after dominating all five districts + defeating the first 4 Billionaires, gated by Chapter 14 main story." },
    ],
    source: [
      { label: "펑키게임 — 머니 아일랜드 에어리어 공략", url: "https://funkygame.tistory.com/1818" },
      { label: "게임공략맨 — 神室町マネーアイランド", url: "https://dswiipspwikips3.jp/yakuza0/money-island.html" },
    ],
    groups: [
    {
      title: { ko: "5구역 — 점유율 이벤트 & 라이벌 보스", en: "5 Districts — Occupancy Events & Rival Bosses" },
      items: [
      {
        number: 1,
        title: { ko: "오락왕 구역 (불한당 스킬 해금)", en: "Leisure King District (Brawler skills unlock)" },
        location: { ko: "카무로초 남서부 — 시치후쿠 거리 일대", en: "Kamurocho SW — Shichifuku St. area" },
        body: { ko: "점유율 30%: 스기타 빌딩 앞 오락왕 부하×3 전투. 60%: 카라오케 스낵바 히로인에서 『JUDGEMENT-심판-』 80점 이상 승리 시 +10%, 패배 시 -10%. 90%: 세레나 뒤편에서 오락왕+부하×3 전투. 클리어 보너스: 불한당 스타일 봉쇄 스킬 해금, 매니저 오락왕·가드맨 타케시타 라쿠타 영입, 전뇌왕·유흥왕·도박왕 구역 개방.", en: "30%: fight Leisure King's men ×3 at Sugita Building. 60%: karaoke JUDGEMENT ≥80 pts → +10%, <80 → -10%. 90%: fight Leisure King+men×3 behind Serena. Clear: Brawler skills unlock, Manager Leisure King + Guard Takeshita Rakuta recruited, 3 new districts open." },
        reward: { ko: "불한당 스타일 봉쇄 스킬 해금 + 전뇌왕·유흥왕·도박왕 구역 개방", en: "Brawler style unlock + 3 districts open" },
      },
      {
        number: 2,
        title: { ko: "전뇌왕 구역 (러시 스킬 일부 해금)", en: "Electronics King District (Rush skills partial unlock)" },
        location: { ko: "카무로초 남중부 — 나카미치 거리 일대", en: "Kamurocho S-Center — Nakamichi St. area" },
        body: { ko: "점유율 30%: 비서와 대화 이벤트. 60%: HL 세가 나카미치점에서 부하×3 전투 후 아웃런 500만점 이상 승리 시 +10%, 미달 -10%. 90%: HL 세가 나카미치점에서 전뇌왕+부하×3 전투. 클리어 보너스: 러시 스타일 봉쇄 스킬 일부 해금, 매니저 전뇌왕·가드맨 메이덴 나미야 영입.", en: "30%: secretary talk event. 60%: fight ×3 at HL Sega Nakamichi, then Out Run score ≥5,000,000 → +10%, fail → -10%. 90%: fight Electronics King+men×3 at HL Sega. Clear: Rush skills partial unlock, Manager Electronics King + Guard Meiden Namiya recruited." },
        reward: { ko: "러시 스타일 봉쇄 스킬 일부 해금", en: "Rush style skills partial unlock" },
      },
      {
        number: 3,
        title: { ko: "유흥왕 구역 (파괴자 스킬 일부 해금)", en: "Pleasure King District (Beast skills partial unlock)" },
        location: { ko: "카무로초 — 핑크 거리·텔레폰 클럽 일대", en: "Kamurocho — Pink St. / Telephone Club area" },
        body: { ko: "점유율 30%: 비서와 대화 이벤트. 60%: 테루테루보야에서 미니게임 전화방 대결 — 3분 내 데이트 성공 시 +10%, 실패 -10%. 이후 유흥왕 부하×3 전투. 90%: 같은 장소에서 유흥왕+부하×3 전투. 클리어 보너스: 파괴자 스타일 봉쇄 스킬 일부 해금, 어드바이저 유흥왕·가드맨 재규어 영입.", en: "30%: secretary event. 60%: telephone club mini-game at Teruteru Boya — succeed date in 3 min → +10%, fail → -10%, then fight ×3. 90%: fight Pleasure King+men×3 at same spot. Clear: Beast skills partial unlock, Advisor Pleasure King + Guard Jaguar recruited." },
        reward: { ko: "파괴자 스타일 봉쇄 스킬 일부 해금", en: "Beast style partial unlock" },
      },
      {
        number: 4,
        title: { ko: "도박왕 구역 (러시 스킬 전체 해금)", en: "Gambling King District (Rush skills full unlock)" },
        location: { ko: "카무로초 — 극장 광장 일대", en: "Kamurocho — Theater Square area" },
        body: { ko: "6장부터 진행 가능. 점유율 30%: 비서와 대화 이벤트. 60%: 캣 파이트 미니게임 대결 — 과거 전적 높고 1st 배율 낮은 선수 유리. 승리 시 +10%, 패배 시 -10%. 90%: 도박왕+부하×4 전투. 클리어 보너스: 러시 스타일 모든 봉쇄 스킬 해금, 매니저 도박왕 영입, 예능왕 구역 개방.", en: "Available from Chapter 6. 30%: secretary event. 60%: Catfight mini-game — favor fighter with high past record + low 1st-place odds. Win → +10%, lose → -10%. 90%: fight Gambling King+men×4. Clear: Rush all skills unlock, Manager Gambling King, Media King district opens." },
        reward: { ko: "러시 스타일 모든 봉쇄 스킬 해금 + 예능왕 구역 개방", en: "Rush style full unlock + Media King district opens" },
      },
      {
        number: 5,
        title: { ko: "예능왕 구역 (파괴자 스킬 전체 해금)", en: "Media King District (Beast skills full unlock)" },
        location: { ko: "카무로초 — 호텔가·밀레니엄 타워 일대 (동부)", en: "Kamurocho — Hotel District / Millennium Tower area (east)" },
        body: { ko: "점유율 30%: 비서와 대화 이벤트. 60%: 댄스 미니게임 대결 — 예능왕 기준 5000~6000점, 90% 성공률 + 피버 2회 정도면 승리. 승리 +10%, 패배 -10%. 90%: 예능왕+부하×5 연전 후 금융왕 부하×2 연전. 클리어 보너스: 파괴자 스타일 모든 봉쇄 스킬 해금, 어드바이저 예능왕 영입. 이후 금융왕 결전.", en: "30%: secretary event. 60%: dance battle — Media King scores ~5,000-6,000; ~90% accuracy + 2 fever hits wins. 90%: fight Media King+men×5 then Finance King's men×2 back-to-back. Clear: Beast all skills unlock, Advisor Media King. Then Finance King fight." },
        reward: { ko: "파괴자 스타일 모든 봉쇄 스킬 해금", en: "Beast style full unlock" },
      },
      {
        number: 6,
        title: { ko: "금융왕 (최종 보스 — 도지마의 용 스타일 해금)", en: "Finance King (Final Boss — Dragon of Dojima unlock)" },
        location: { ko: "예능왕 구역 클리어 직후 — 사무실 복귀 후 이벤트", en: "Immediately after Media King clear — return to office" },
        body: { ko: "사무실로 돌아가면 이벤트 발동. 「OK다」 선택 후 금융왕 부하×2 → 금융왕 순으로 연전. 클리어 보너스: 도지마의 용 스타일 해금, 이미지 비디오 09 입수, 트로피. ※클리어 후 사무실 입구 옆을 조사하면 100억 지불로 키류 금 조각상 설치 가능 (효과 없음).", en: "Return to office triggers event. Choose 'OK' → fight Finance King's men×2 then Finance King. Clear: Dragon of Dojima style unlocked, Image Video 09 obtained, trophy. ※After clear: inspect office entrance to spend ¥10B on gold Kiryu statue (cosmetic only)." },
        reward: { ko: "도지마의 용 스타일 해금 + 이미지 비디오 09 + 트로피", en: "Dragon of Dojima style unlock + Image Video 09 + trophy" },
      },
      ],
    },
    {
      title: { ko: "오락왕 매물 (전체 S-매출: 6,378만 엔)", en: "Leisure King Properties (Total S-revenue: ¥63,780,000)" },
      mapImage: "/yakuza-0-real-estate/king-amusement-area.jpg",
      items: [
        {
          number: 1,
          title: { ko: "★ 파친코 뉴에덴", en: "★ Pachinko New Eden" },
          location: { ko: "오락 / 매입 1,840만", en: "Entertainment / Price ¥18,400,000" },
          body: { ko: "S-매출 1,380만. 구역 최고 수익 매물 중 하나. 우선 매입 추천.", en: "S-revenue ¥13,800,000. One of top earners — buy first." },
        },
        {
          number: 2,
          title: { ko: "★ 파친코 마루후쿠", en: "★ Pachinko Marufuku" },
          location: { ko: "오락 / 매입 1,840만", en: "Entertainment / Price ¥18,400,000" },
          body: { ko: "S-매출 1,380만. 뉴에덴과 동일 조건. 우선 매입 추천.", en: "S-revenue ¥13,800,000. Same conditions as New Eden — buy first." },
        },
        {
          number: 3,
          title: { ko: "카무로 러브 플라자", en: "Kamuro Love Plaza" },
          location: { ko: "유흥 / 매입 1,240만", en: "Adult / Price ¥12,400,000" },
          body: { ko: "S-매출 558만.", en: "S-revenue ¥5,580,000." },
        },
        {
          number: 4,
          title: { ko: "스키야키 무라나카", en: "Sukiyaki Muranaka" },
          location: { ko: "식당 / 매입 1,400만", en: "Restaurant / Price ¥14,000,000" },
          body: { ko: "S-매출 630만. 메인스토리 튜토리얼 중 자동 구입.", en: "S-revenue ¥6,300,000. Automatically purchased during main story tutorial." },
        },
        {
          number: 5,
          title: { ko: "뇨키뇨키 학원", en: "Nyoki-Nyoki Academy" },
          location: { ko: "유흥 / 매입 1,080만", en: "Adult / Price ¥10,800,000" },
          body: { ko: "S-매출 162만. 구역 최저가 매물.", en: "S-revenue ¥1,620,000. Cheapest in district." },
        },
        {
          number: 6,
          title: { ko: "러브러브 히메링고", en: "Love Love Hime-Ringo" },
          location: { ko: "유흥 / 매입 1,640만", en: "Adult / Price ¥16,400,000" },
          body: { ko: "S-매출 738만.", en: "S-revenue ¥7,380,000." },
        },
        {
          number: 7,
          title: { ko: "유한상사 하라지마 설계", en: "Harajima Design Co." },
          location: { ko: "기업 / 매입 1,320만", en: "Corporate / Price ¥13,200,000" },
          body: { ko: "S-매출 594만.", en: "S-revenue ¥5,940,000." },
        },
        {
          number: 8,
          title: { ko: "백합주 (디폴트 보유)", en: "Yurizake (Default-owned)" },
          location: { ko: "식당 / 매입 불필요", en: "Restaurant / No purchase" },
          body: { ko: "S-매출 156만. 구역 진입 시 자동 보유. 별도 구입 불필요.", en: "S-revenue ¥1,560,000. Owned automatically on district entry." },
        },
        {
          number: 9,
          title: { ko: "POPPO 텐카이치점 (서브스토리 조건)", en: "Poppo Tenkaichi (Substory condition)" },
          location: { ko: "상점 / 매입 불필요", en: "Shop / No purchase" },
          body: { ko: "S-매출 204만. 구매 불가 — 키류 서브스토리 51 절친 달성으로 무상 양도.", en: "S-revenue ¥2,040,000. Not purchasable — gifted via Kiryu Substory 51 friendship max." },
          prereq: { ko: "키류 서브스토리 51 절친 달성", en: "Kiryu Substory 51 friendship MAX" },
        },
        {
          number: 10,
          title: { ko: "스시긴 (서브스토리 조건)", en: "Sushi Gin (Substory condition)" },
          location: { ko: "식당 / 매입 불필요", en: "Restaurant / No purchase" },
          body: { ko: "S-매출 576만. 구매 불가 — 키류 서브스토리 53 절친 달성으로 무상 양도.", en: "S-revenue ¥5,760,000. Not purchasable — gifted via Kiryu Substory 53 friendship max." },
          prereq: { ko: "키류 서브스토리 53 절친 달성", en: "Kiryu Substory 53 friendship MAX" },
        },
      ],
    },
    {
      title: { ko: "전뇌왕 매물 (전체 S-매출: 8,072만 엔)", en: "Electronics King Properties (Total S-revenue: ¥80,720,000)" },
      mapImage: "/yakuza-0-real-estate/electronic-brain-area.jpg",
      items: [
        {
          number: 1,
          title: { ko: "쇼키치 카메라", en: "Shokichi Camera" },
          location: { ko: "상점 / 매입 6,240만", en: "Shop / Price ¥62,400,000" },
          body: { ko: "S-매출 936만.", en: "S-revenue ¥9,360,000." },
        },
        {
          number: 2,
          title: { ko: "★ 파친코 알로하", en: "★ Pachinko Aloha" },
          location: { ko: "오락 / 매입 7,520만", en: "Entertainment / Price ¥75,200,000" },
          body: { ko: "S-매출 1,880만. 우선 매입 추천.", en: "S-revenue ¥18,800,000. Buy first." },
        },
        {
          number: 3,
          title: { ko: "아사이 제3빌딩", en: "Asai Building No.3" },
          location: { ko: "기업 / 매입 5,120만", en: "Corporate / Price ¥51,200,000" },
          body: { ko: "S-매출 768만.", en: "S-revenue ¥7,680,000." },
        },
        {
          number: 4,
          title: { ko: "★ 파친코 쓰리세븐", en: "★ Pachinko Triple Seven" },
          location: { ko: "오락 / 매입 7,840만", en: "Entertainment / Price ¥78,400,000" },
          body: { ko: "S-매출 1,960만. 구역 최고 수익 매물. 우선 매입 추천.", en: "S-revenue ¥19,600,000. Top earner in district — buy first." },
        },
        {
          number: 5,
          title: { ko: "회전초밥 텐호스시", en: "Tenpo Sushi (Revolving)" },
          location: { ko: "식당 / 매입 5,120만", en: "Restaurant / Price ¥51,200,000" },
          body: { ko: "S-매출 256만. 매입 시 낚싯대 「바다 낚싯대」 입수.", en: "S-revenue ¥2,560,000. Purchasing awards the Sea Fishing Rod." },
          reward: { ko: "낚싯대 「바다 낚싯대」 입수", en: "Sea Fishing Rod obtained" },
        },
        {
          number: 6,
          title: { ko: "★ 러블리 버니", en: "★ Lovely Bunny" },
          location: { ko: "유흥 / 매입 5,600만", en: "Adult / Price ¥56,000,000" },
          body: { ko: "S-매출 1,400만. 우선 매입 추천.", en: "S-revenue ¥14,000,000. Buy first." },
        },
        {
          number: 7,
          title: { ko: "중화요리 북경", en: "Chinese Restaurant Peking" },
          location: { ko: "식당 / 매입 4,160만", en: "Restaurant / Price ¥41,600,000" },
          body: { ko: "S-매출 208만. 구역 최저가 매물.", en: "S-revenue ¥2,080,000. Cheapest in district." },
        },
        {
          number: 8,
          title: { ko: "AMUSEMENT GAME YOU", en: "Amusement Game You" },
          location: { ko: "오락 / 매입 5,920만", en: "Entertainment / Price ¥59,200,000" },
          body: { ko: "S-매출 296만.", en: "S-revenue ¥2,960,000." },
        },
        {
          number: 9,
          title: { ko: "도레미파 존 (디폴트 보유)", en: "DoReMiFa Zone (Default-owned)" },
          location: { ko: "오락 / 매입 불필요", en: "Entertainment / No purchase" },
          body: { ko: "S-매출 112만. 전뇌왕 구역 진입 시 자동 보유.", en: "S-revenue ¥1,120,000. Owned automatically on district entry." },
        },
        {
          number: 10,
          title: { ko: "HL 세가 나카미치점 (서브스토리 조건)", en: "HL Sega Nakamichi (Substory condition)" },
          location: { ko: "오락 / 매입 불필요", en: "Entertainment / No purchase" },
          body: { ko: "S-매출 256만. 구매 불가 — 키류 서브스토리 54 절친 달성으로 무상 양도. 60% 이벤트 장소이기도 함.", en: "S-revenue ¥2,560,000. Not purchasable — gifted via Kiryu Substory 54. Also the 60% event location." },
          prereq: { ko: "키류 서브스토리 54 절친 달성", en: "Kiryu Substory 54 friendship MAX" },
        },
      ],
    },
    {
      title: { ko: "유흥왕 매물 (전체 S-매출: 1억 8,632만 엔)", en: "Pleasure King Properties (Total S-revenue: ¥186,320,000)" },
      mapImage: "/yakuza-0-real-estate/king-customs-area.jpg",
      items: [
        {
          number: 1,
          title: { ko: "섹하라컵", en: "Sekuhara Cup" },
          location: { ko: "유흥 / 매입 1억 2,400만", en: "Adult / Price ¥124,000,000" },
          body: { ko: "S-매출 1,536만.", en: "S-revenue ¥15,360,000." },
        },
        {
          number: 2,
          title: { ko: "★ 카바레 발렌타인", en: "★ Cabaret Valentine" },
          location: { ko: "유흥 / 매입 1억 6,000만", en: "Adult / Price ¥160,000,000" },
          body: { ko: "S-매출 4,000만. 구역 최고 수익 매물. 우선 매입 추천.", en: "S-revenue ¥40,000,000. Top earner in district — buy first." },
        },
        {
          number: 3,
          title: { ko: "톤텐샵", en: "Tonten Shop" },
          location: { ko: "식당 / 매입 9,600만", en: "Restaurant / Price ¥96,000,000" },
          body: { ko: "S-매출 480만.", en: "S-revenue ¥4,800,000." },
        },
        {
          number: 4,
          title: { ko: "★ 아라비아 레코드", en: "★ Arabia Records" },
          location: { ko: "상점 / 매입 1억 5,680만", en: "Shop / Price ¥156,800,000" },
          body: { ko: "S-매출 2,352만. 우선 매입 추천.", en: "S-revenue ¥23,520,000. Buy first." },
        },
        {
          number: 5,
          title: { ko: "카무로 세계 극장", en: "Kamuro World Theater" },
          location: { ko: "오락 / 매입 1억 880만", en: "Entertainment / Price ¥108,800,000" },
          body: { ko: "S-매출 1,632만.", en: "S-revenue ¥16,320,000." },
        },
        {
          number: 6,
          title: { ko: "전화방 카르티에 라탱", en: "Telephone Club Quartier Latin" },
          location: { ko: "유흥 / 매입 8,960만", en: "Adult / Price ¥89,600,000" },
          body: { ko: "S-매출 1,344만. 구역 최저가 매물.", en: "S-revenue ¥13,440,000. Cheapest in district." },
        },
        {
          number: 7,
          title: { ko: "황안당 미술", en: "Koando Arts" },
          location: { ko: "상점 / 매입 1억 1,520만", en: "Shop / Price ¥115,200,000" },
          body: { ko: "S-매출 1,728만.", en: "S-revenue ¥17,280,000." },
        },
        {
          number: 8,
          title: { ko: "★ 노팬티 갈비 파라다이스", en: "★ No-Panties Ribs Paradise" },
          location: { ko: "유흥 / 매입 1억 2,480만", en: "Adult / Price ¥124,800,000" },
          body: { ko: "S-매출 3,120만. 우선 매입 추천.", en: "S-revenue ¥31,200,000. Buy first." },
        },
        {
          number: 9,
          title: { ko: "양식 모스카우", en: "Western Food Moskow" },
          location: { ko: "식당 / 매입 1억 240만", en: "Restaurant / Price ¥102,400,000" },
          body: { ko: "S-매출 512만.", en: "S-revenue ¥5,120,000." },
        },
        {
          number: 10,
          title: { ko: "유한상사 하야시 건축사무소 (디폴트 보유)", en: "Hayashi Architecture (Default-owned)" },
          location: { ko: "기업 / 매입 불필요", en: "Corporate / No purchase" },
          body: { ko: "S-매출 128만. 유흥왕 구역 진입 시 자동 보유.", en: "S-revenue ¥1,280,000. Owned automatically on district entry." },
        },
      ],
    },
    {
      title: { ko: "도박왕 매물 (전체 S-매출: 3억 5,424만 엔)", en: "Gambling King Properties (Total S-revenue: ¥354,240,000)" },
      mapImage: "/yakuza-0-real-estate/king-gambling-area.jpg",
      items: [
        {
          number: 1,
          title: { ko: "★ 파칭코 BIGSTAR", en: "★ Pachinko BIGSTAR" },
          location: { ko: "오락 / 매입 3억 2,640만", en: "Entertainment / Price ¥326,400,000" },
          body: { ko: "S-매출 8,160만. 구역 최고 수익 매물. 우선 매입 추천.", en: "S-revenue ¥81,600,000. Top earner — buy first." },
        },
        {
          number: 2,
          title: { ko: "카무로 스칼라좌 키네마 회관", en: "Kamuro La Scala Cinema Hall" },
          location: { ko: "오락 / 매입 2억 7,520만", en: "Entertainment / Price ¥275,200,000" },
          body: { ko: "S-매출 4,128만.", en: "S-revenue ¥41,280,000." },
        },
        {
          number: 3,
          title: { ko: "산와 레저 회관", en: "Sanwa Leisure Hall" },
          location: { ko: "기업 / 매입 2억 6,880만", en: "Corporate / Price ¥268,800,000" },
          body: { ko: "S-매출 4,032만.", en: "S-revenue ¥40,320,000." },
        },
        {
          number: 4,
          title: { ko: "뉴 몽마르트르", en: "New Montmartre" },
          location: { ko: "오락 / 매입 2억 6,240만", en: "Entertainment / Price ¥262,400,000" },
          body: { ko: "S-매출 3,936만.", en: "S-revenue ¥39,360,000." },
        },
        {
          number: 5,
          title: { ko: "★ 파칭코 뉴코스모스", en: "★ Pachinko New Cosmos" },
          location: { ko: "오락 / 매입 2억 7,520만", en: "Entertainment / Price ¥275,200,000" },
          body: { ko: "S-매출 5,600만. 우선 매입 추천.", en: "S-revenue ¥56,000,000. Buy first." },
        },
        {
          number: 6,
          title: { ko: "TOKYO 포푸리", en: "TOKYO Popuri" },
          location: { ko: "기업 / 매입 2억 7,520만", en: "Corporate / Price ¥275,200,000" },
          body: { ko: "S-매출 4,128만.", en: "S-revenue ¥41,280,000." },
        },
        {
          number: 7,
          title: { ko: "깁슨 홀", en: "Gibson Hall" },
          location: { ko: "기업 / 매입 3억 720만", en: "Corporate / Price ¥307,200,000" },
          body: { ko: "S-매출 4,608만.", en: "S-revenue ¥46,080,000." },
        },
        {
          number: 8,
          title: { ko: "NY 핫도그", en: "NY Hot Dog" },
          location: { ko: "식당 / 매입 2억 480만", en: "Restaurant / Price ¥204,800,000" },
          body: { ko: "S-매출 1,024만. 구역 최저가 매물.", en: "S-revenue ¥10,240,000. Cheapest in district." },
        },
        {
          number: 9,
          title: { ko: "카무로 소바 (디폴트 보유)", en: "Kamuro Soba (Default-owned)" },
          location: { ko: "식당 / 매입 불필요", en: "Restaurant / No purchase" },
          body: { ko: "S-매출 128만. 도박왕 구역 진입 시 자동 보유.", en: "S-revenue ¥1,280,000. Owned automatically on district entry." },
        },
        {
          number: 10,
          title: { ko: "마하볼 (서브스토리 조건)", en: "Mach Bowl (Substory condition)" },
          location: { ko: "오락 / 매입 불필요", en: "Entertainment / No purchase" },
          body: { ko: "S-매출 704만. 구매 불가 — 서브스토리 52 절친 달성으로 무상 양도. 60% 이벤트 캣 파이트 대결 장소.", en: "S-revenue ¥7,040,000. Not purchasable — gifted via Substory 52. Also the 60% Catfight event venue." },
          prereq: { ko: "서브스토리 52 절친 달성", en: "Substory 52 friendship MAX" },
        },
      ],
    },
    {
      title: { ko: "예능왕 매물 (전체 S-매출: 6억 7,904만 엔)", en: "Media King Properties (Total S-revenue: ¥679,040,000)" },
      mapImage: "/yakuza-0-real-estate/king-entertainment-area.jpg",
      items: [
        {
          number: 1,
          title: { ko: "★ Disco City Boy", en: "★ Disco City Boy" },
          location: { ko: "오락 / 매입 12억 2,880만", en: "Entertainment / Price ¥1,228,800,000" },
          body: { ko: "S-매출 6억 7,904만. 구역 전체 S-매출의 절대 다수를 차지. 우선 매입 추천.", en: "S-revenue ¥679,040,000. Dominates district revenue — buy first." },
        },
        {
          number: 2,
          title: { ko: "카무로탕", en: "Kamuro-to (Bath)" },
          location: { ko: "오락 / 매입 9억 7,280만", en: "Entertainment / Price ¥972,800,000" },
          body: { ko: "S-매출 2,432만.", en: "S-revenue ¥24,320,000." },
        },
        {
          number: 3,
          title: { ko: "★ 호텔 블루 라이트 카무로", en: "★ Hotel Blue Light Kamuro" },
          location: { ko: "기업 / 매입 9억 9,840만", en: "Corporate / Price ¥998,400,000" },
          body: { ko: "S-매출 1억 2,480만. 우선 매입 추천.", en: "S-revenue ¥124,800,000. Buy first." },
        },
        {
          number: 4,
          title: { ko: "호텔 머메이드", en: "Hotel Mermaid" },
          location: { ko: "기업 / 매입 9억 2,160만", en: "Corporate / Price ¥921,600,000" },
          body: { ko: "S-매출 6,912만.", en: "S-revenue ¥69,120,000." },
        },
        {
          number: 5,
          title: { ko: "광월극장", en: "Kogetsu Theater" },
          location: { ko: "오락 / 매입 7억 9,360만", en: "Entertainment / Price ¥793,600,000" },
          body: { ko: "S-매출 1,984만. 구역 최저가 매물.", en: "S-revenue ¥19,840,000. Cheapest in district." },
        },
        {
          number: 6,
          title: { ko: "★ 전화방 링링보이", en: "★ Telephone Club Rinrin-Boy" },
          location: { ko: "유흥 / 매입 9억 2,160만", en: "Adult / Price ¥921,600,000" },
          body: { ko: "S-매출 1억 1,520만. 우선 매입 추천.", en: "S-revenue ¥115,200,000. Buy first." },
        },
        {
          number: 7,
          title: { ko: "호텔 다이아몬드", en: "Hotel Diamond" },
          location: { ko: "기업 / 매입 9억 9,840만", en: "Corporate / Price ¥998,400,000" },
          body: { ko: "S-매출 7,488만.", en: "S-revenue ¥74,880,000." },
        },
        {
          number: 8,
          title: { ko: "호텔 화이트", en: "Hotel White" },
          location: { ko: "기업 / 매입 9억 2,160만", en: "Corporate / Price ¥921,600,000" },
          body: { ko: "S-매출 6,912만.", en: "S-revenue ¥69,120,000." },
        },
        {
          number: 9,
          title: { ko: "포켓 서킷 스타디움 (서브스토리 조건)", en: "Pocket Circuit Stadium (Substory condition)" },
          location: { ko: "오락 / 매입 불필요", en: "Entertainment / No purchase" },
          body: { ko: "S-매출 1,152만. 구매 불가 — 서브스토리 50 절친 달성으로 무상 양도.", en: "S-revenue ¥11,520,000. Not purchasable — gifted via Substory 50 friendship max." },
          prereq: { ko: "서브스토리 50 절친 달성", en: "Substory 50 friendship MAX" },
        },
        {
          number: 10,
          title: { ko: "토키와 식당 (디폴트 보유)", en: "Tokiwa Restaurant (Default-owned)" },
          location: { ko: "식당 / 매입 불필요", en: "Restaurant / No purchase" },
          body: { ko: "S-매출 1,664만. 예능왕 구역 진입 시 자동 보유.", en: "S-revenue ¥16,640,000. Owned automatically on district entry." },
        },
      ],
    },
    ],
  },
  {
    slug: "cabaret-club-czar",
    title: { ko: "소텐보리 물장사 아일랜드 — 5구역 + 플래티넘 캐스트 육성", en: "Sotenbori Cabaret Club Czar — 5 Districts + Platinum Hostess Training" },
    summary: { ko: "마지마 편 캬바쿠라 그랑프리 모드. 플레이어 가게 「클럽 선샤인」을 운영하며 소텐보리를 지배하는 「소텐보리 5스타」 라이벌 5점포(클럽 마즈·클럽 주피터·클럽 머큐리·클럽 비너스·클럽 문)를 차례로 격파합니다. 플래티넘 캐스트 6명(유키·사키·치카·아이·히비키·마나)을 영입해 능력치(섹시 / 뷰티 / 큐트 / 퍼니 4종 × X→△→○→◎ 4단계) MAX로 키웁니다. 캐스트별 특별 레슨의 정답 선택지 텍스트(예: 「분재…?」 / 「무조건 칭찬한다」)는 아래 레슨별 카드에서 전문으로 안내합니다.", en: "Majima's Cabaret Club Grand Prix. You run Club Sunshine and topple the Five Stars of Sotenbori — Club Mars, Club Jupiter, Club Mercury, Club Venus, and Club Moon. Recruit all 6 Platinum Hostesses (Yuki/Saki/Chika/Ai/Hibiki/Mana) and train them to MAX across the 4 stats (Sexy / Beauty / Cute / Funny — X→△→○→◎ tiers). Full Private Lesson dialog answers (e.g. \"Bonsai...?\" / \"Just praise her no matter what\") are listed verbatim in the per-cast lesson cards below." },
    tips: [
        { ko: "호스티스 능력치는 섹시 / 뷰티 / 큐트 / 퍼니 4종. 등급은 X / △ / ○ / ◎ 순으로 4단계입니다. 한 캐스트당 최대 3개 항목만 ◎까지 올릴 수 있으니, 캐스트별로 역할을 분담해 1개를 X로 두고 나머지 3개를 ◎로 특화하세요.", en: "Hostess stats split into Sexy / Beauty / Cute / Funny, ranked X → △ → ○ → ◎. Only 3 of 4 can hit ◎ per cast — specialize: lock one as X and push the other three to ◎ so roles don't overlap." },
        { ko: "특별 레슨(프라이빗 레슨)은 노래방·댄스·당구·다트 데이트로 진행됩니다. 호감도 + 데이트 승리로 레벨이 비약적으로 오릅니다. 데이트 선택지는 호스티스의 성격 유형에 맞춰 답하면 정답.", en: "Private Lessons use karaoke / dance / billiards / darts dates. Affinity + date wins drastically raise levels. Pick choices that match the hostess's personality type for the right answer." },
        { ko: "5스타 풀 제패 시 「지지 않는 태양」 업적이 트리거됩니다. 최종 라이벌 클럽 문 결전 전에 캐스트 능력치를 풀로 올려 두세요.", en: "Conquering all Five Stars triggers 'Walking On Sunshine'. Max out cast stats before the final Club Moon showdown." },
    ],
    source: { label: "용과 같이 시리즈/캬바쿠라 — 나무위키", url: "https://namu.wiki/w/%EC%9A%A9%EA%B3%BC%20%EA%B0%99%EC%9D%B4%20%EC%8B%9C%EB%A6%AC%EC%A6%88/%EC%BA%AC%EB%B0%94%EC%BF%A0%EB%9D%BC" },
    groups: [
    {
      title: { ko: "소텐보리 5스타 — 라이벌 클럽 제패", en: "Five Stars of Sotenbori — Rival Club Battles" },
      items: [
      {
        number: 1,
        title: { ko: "클럽 마즈 격파 (보스: 히노)", en: "Defeat Club Mars (Boss: Hino)" },
        location: { ko: "소텐보리 — 마즈 영역 (퍼플)", en: "Sotenbori — Mars Area (Purple)" },
        body: { ko: "5스타 입문전. 튜토리얼 직후 도전 가능. 일반 호스티스 라인업 + 트레이닝 1단계만 마쳐도 1위 매출 가능.", en: "Entry battle. Available right after the tutorial. Standard hostesses + basic training are enough for #1 sales." },
      },
      {
        number: 2,
        title: { ko: "클럽 주피터 격파 (보스: 키즈카)", en: "Defeat Club Jupiter (Boss: Kizuka)" },
        location: { ko: "소텐보리 — 주피터 영역 (그린)", en: "Sotenbori — Jupiter Area (Green)" },
        body: { ko: "Mars 클리어 후 도전. 첫 번째 플래티넘 캐스트 영입 가능 시점.", en: "After Mars. First Platinum Hostess becomes recruitable here." },
      },
      {
        number: 3,
        title: { ko: "클럽 머큐리 격파 (보스: 미즈무라)", en: "Defeat Club Mercury (Boss: Mizumura)" },
        location: { ko: "소텐보리 — 머큐리 영역 (블루)", en: "Sotenbori — Mercury Area (Blue)" },
        body: { ko: "능력치 ◎ 1개로는 불안정. 트레이닝 + 데이트 이벤트로 캐스트 1~2명을 핵심급으로 키워두세요.", en: "Single-◎ casts struggle here. Push 1-2 casts to core spec with training + date events." },
      },
      {
        number: 4,
        title: { ko: "클럽 비너스 격파 (보스: 카네하라)", en: "Defeat Club Venus (Boss: Kanehara)" },
        location: { ko: "소텐보리 — 비너스 영역 (레드)", en: "Sotenbori — Venus Area (Red)" },
        body: { ko: "VIP 손님 비중이 커집니다. 플래티넘 캐스트 4명 풀 영입 + 의상·헤어 풀 강화 후 도전.", en: "VIP customers dominate. Recruit all 4 Platinum Hostesses + max outfits + hair before challenging." },
      },
      {
        number: 5,
        title: { ko: "클럽 문 결승전 (보스: 츠키야마)", en: "Club Moon — Final (Boss: Tsukiyama)" },
        location: { ko: "소텐보리 — 문 영역 (골드) / 그랑프리 결승", en: "Sotenbori — Moon Area (Gold) / Grand Prix Final" },
        body: { ko: "최종 라이벌. 츠키야마는 5스타의 리더. 플래티넘 캐스트 4명을 능력치 MAX로 만들고 데이트 이벤트 풀 클리어 후 도전. 격파 시 「지지 않는 태양」 업적 + 클럽 선샤인 통합.", en: "Final rival — Tsukiyama leads the Five Stars. Hit MAX on all 4 Platinum Hostesses + clear date events. Win for 'Walking On Sunshine' achievement + Club Sunshine takes the throne." },
        reward: { ko: "「지지 않는 태양」 업적 + 마지마 부동산 외 시드 머니 확장", en: "'Walking On Sunshine' achievement + cabaret-side cash flow for Majima" },
      },
      ],
    },
    {
      title: { ko: "플래티넘 캐스트 육성 — 능력치 4종 / 데이트 시스템", en: "Platinum Hostess Training — 4 Stats / Date System" },
      items: [
      {
        number: 6,
        title: { ko: "섹시 라인", en: "Sexy line (X→△→○→◎)" },
        location: { ko: "드레스업 — 의상·헤어 변경", en: "Dress-Up — outfit + hair" },
        body: { ko: "노출도 높은 의상 + 헤어로 상승. 데이트 미니게임 중 「당구」 승리 시 추가 보너스.", en: "Boosted by exposed outfits + hairstyles. Win billiards dates for extra Sexy gains." },
      },
      {
        number: 7,
        title: { ko: "뷰티 라인", en: "Beauty line" },
        location: { ko: "드레스업 — 액세서리·화장", en: "Dress-Up — accessories + makeup" },
        body: { ko: "고급 액세서리 + 메이크업으로 상승. 「댄스」 데이트 승리 시 추가 보너스.", en: "High-end accessories + makeup. Win dance dates for extra Beauty gains." },
      },
      {
        number: 8,
        title: { ko: "큐트 라인", en: "Cute line" },
        location: { ko: "드레스업 — 캐주얼 의상", en: "Dress-Up — casual outfits" },
        body: { ko: "파스텔 톤·캐주얼 의상으로 상승. 「노래방」 데이트 승리 시 추가 보너스.", en: "Pastel / casual outfits. Win karaoke dates for extra Cute gains." },
      },
      {
        number: 9,
        title: { ko: "퍼니 라인", en: "Funny line" },
        location: { ko: "드레스업 — 개성적인 의상", en: "Dress-Up — quirky outfits" },
        body: { ko: "개성적인 의상 + 헤어. 「다트」 데이트 승리 시 추가 보너스.", en: "Quirky outfits + hair. Win darts dates for extra Funny gains." },
      },
      {
        number: 10,
        title: { ko: "특별 레슨 (프라이빗 레슨)", en: "Private Lesson" },
        location: { ko: "플래티넘 캐스트 — 호감도 + 데이트", en: "Platinum Hostess — affinity + date" },
        body: { ko: "호감도가 일정 단계 이상이면 특별 레슨 해금. 데이트 선택지는 캐릭터 성격에 맞춰 답해야 호감도가 크게 오릅니다.", en: "Affinity gates unlock Private Lessons. Match dialog choices to the cast's personality type for a big affinity spike." },
      },
      {
        number: 11,
        title: { ko: "캐스트 LV MAX → 다이아몬드 캐스트", en: "Cast LV MAX → Diamond Cast" },
        location: { ko: "플래티넘 캐스트 — 모든 능력치 + LV", en: "Platinum Hostess — all stats + LV" },
        body: { ko: "한 명의 캐스트를 LV MAX까지 키우면 「다이아몬드 캐스트」 업적 발동. 이후 다른 캐스트도 같이 키워 풀 라인업으로 결승전을 노리세요.", en: "Maxing one cast's LV unlocks 'You're Still Number One'. Continue maxing the rest for the final club battle." },
        reward: { ko: "「다이아몬드 캐스트」 업적", en: "'You're Still Number One' achievement" },
      },
      ],
    },

    {
      title: { ko: "플래티넘 캐스트 특별 레슨 — 6명 × 7회 정답 선택지(전문)", en: "Platinum Hostess Private Lessons — 6 × 7 Full-Text Choice Sheet" },
      items: [
      {
        number: 12,
        title: { ko: "유키 — 접객 연습 1회차", en: "Yuki — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「분재…?」 → 2) 「무조건 칭찬한다」 → 3) 「나이 든 손님에게 안성맞춤」 → 4) 「나도 남자라카이」", en: "Correct choices (in order): 1) \"Bonsai...?\" → 2) \"Just praise her no matter what\" → 3) \"Perfect for older customers\" → 4) \"I'm a guy too, y'know\"" },
      },
      {
        number: 13,
        title: { ko: "유키 — 접객 연습 2회차", en: "Yuki — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「왠지 알 것 같다」 → 2) 「다양한 여자가 있어서 좋다」 → 3) 「좋아하면 노력할 수 있지 않을까」 → 4) 「적어도 이름은 진짜로 해라, 거짓말쟁이」", en: "Correct choices (in order): 1) \"I kinda get it\" → 2) \"It's nice that there are all kinds of girls\" → 3) \"If you love it, you can push through, right?\" → 4) \"At least use your real first name, you little liar\"" },
      },
      {
        number: 14,
        title: { ko: "유키 — 접객 연습 3회차", en: "Yuki — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「가자미 지느러미살이네」 → 2) 「꼭 부탁하고 싶다」 → 3) 「손님을 전부 나라고 생각해라」 → 4) 「열심히 하고 있다고 본다」", en: "Correct choices (in order): 1) \"That's engawa, huh\" → 2) \"I'd love for you to do it\" → 3) \"Think of every customer as me\" → 4) \"I think you're working hard\"" },
      },
      {
        number: 15,
        title: { ko: "유키 — 접객 연습 4회차", en: "Yuki — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「분재」 → 2) 「기업이 보는 눈이 없다」 → 3) 「내가 빡세게 굴려주마!」 → 4) 「잠은 충분히 자라」", en: "Correct choices (in order): 1) \"Bonsai\" → 2) \"Those companies have no eye for talent\" → 3) \"I'll whip you into shape!\" → 4) \"Make sure you get plenty of sleep\"" },
      },
      {
        number: 16,
        title: { ko: "유키 — 동반 연습 — 노래방", en: "Yuki — Companion Practice — Karaoke" },
        location: { ko: "동반 연습 — 노래방", en: "Companion Practice — Karaoke" },
        body: { ko: "정답 경로: 「×3 샤인」에서 추임새를 넣는다 · 「24시간 신데렐라」를 부른다 둘 다 90점 이상이면 퍼펙트 레슨", en: "Correct path: Do the call-and-response on \"×3 Shine\" / Sing \"24-Hour Cinderella\" — score 90+ on both for a Perfect Lesson" },
      },
      {
        number: 17,
        title: { ko: "유키 — 동반 연습 — 디스코", en: "Yuki — Companion Practice — Disco" },
        location: { ko: "동반 연습 — 디스코", en: "Companion Practice — Disco" },
        body: { ko: "정답 경로: 「사랑의 디스코 퀸」으로 승부 Result★3이면 퍼펙트 레슨", en: "Correct path: Compete with \"Disco Queen of Love\" — get Result★3 for a Perfect Lesson" },
      },
      {
        number: 18,
        title: { ko: "유키 — 접객 연습 최종 회차", en: "Yuki — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「유키 많이 컸네」 → 2) 「언제든 기대 와도 된다」 → 3) 「사랑스러운 사람」 → 4) 「소, 소중히 해라」", en: "Correct choices (in order): 1) \"You've really grown, Yuki\" → 2) \"You can lean on me anytime\" → 3) \"Someone dear to me\" → 4) \"T-take good care of him\"" },
        reward: { ko: "서브스토리 No.69 「마지마의 부정」 발생", en: "Triggers Substory #69 \"Majima's Parental Heart\"" },
      },
      {
        number: 19,
        title: { ko: "아이 — 접객 연습 1회차", en: "Ai — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「다음에 같이 먹으러 가자!」 → 2) 「마사지를 받는다」 → 3) 「우리 가게에 와줘서 다행이다」 → 4) 「신경 쓰지 말고 편하게 가자」", en: "Correct choices (in order): 1) \"Let's go eat together next time!\" → 2) \"Have her give me a massage\" → 3) \"I'm glad you came to our place\" → 4) \"Don't worry about it, just take it easy\"" },
      },
      {
        number: 20,
        title: { ko: "아이 — 접객 연습 2회차", en: "Ai — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「연상의 남자가 봐도 매력적이다」 → 2) 「접객업이니까 어쩔 수 없다」 → 3) 「남자친구만 볼 수 있는 모습이네」 → 4) 「귀엽잖아」", en: "Correct choices (in order): 1) \"Even an older guy finds you charming\" → 2) \"It comes with the service job\" → 3) \"That's a side only your boyfriend gets to see\" → 4) \"That's cute, isn't it\"" },
      },
      {
        number: 21,
        title: { ko: "아이 — 동반 연습 — 디스코", en: "Ai — Companion Practice — Disco" },
        location: { ko: "동반 연습 — 디스코", en: "Companion Practice — Disco" },
        body: { ko: "정답 경로: 「Queen of the passion」으로 승부 Result★3이면 퍼펙트 레슨", en: "Correct path: Compete with \"Queen of the Passion\" — get Result★3 for a Perfect Lesson" },
      },
      {
        number: 22,
        title: { ko: "아이 — 접객 연습 3회차", en: "Ai — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「아이 같은 딸」 → 2) 「요리를 잘함」 → 3) 「태어나기 전」 → 4) 「그만두게 한다」", en: "Correct choices (in order): 1) \"A daughter like Ai\" → 2) \"Good at cooking\" → 3) \"Before she was born\" → 4) \"Make her quit\"" },
      },
      {
        number: 23,
        title: { ko: "아이 — 접객 연습 4회차", en: "Ai — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「앞으로 같이 힘내자!」 → 2) 「나도 힘을 받고 있다」 → 3) 「돈이 전부가 아니다」 → 4) 「난 데릴사위라도 상관없다」", en: "Correct choices (in order): 1) \"Let's keep working hard together!\" → 2) \"I get energy from you too\" → 3) \"Money isn't everything\" → 4) \"I don't mind marrying into your family\"" },
      },
      {
        number: 24,
        title: { ko: "아이 — 동반 연습 — 당구", en: "Ai — Companion Practice — Billiards" },
        location: { ko: "동반 연습 — 당구", en: "Companion Practice — Billiards" },
        body: { ko: "정답 경로: 나인볼로 아이와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play nine-ball against Ai — win for a Perfect Lesson" },
      },
      {
        number: 25,
        title: { ko: "아이 — 접객 연습 최종 회차", en: "Ai — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「선샤인에 어서 오세요」 → 2) 「용서할 수 없다!」 → 3) 「좋은 점이 너무 많은가?」 → 4) 「다음에 같이 갈까」 → 5) 간다라에 이미지 비디오 03 「우에하라 아이」 입고", en: "Correct choices (in order): 1) \"Welcome to Sunshine\" → 2) \"I can't let this slide!\" → 3) \"Too many good points, huh?\" → 4) \"Let's go together next time\" → 5) Image Video 03 \"Ai Uehara\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 03 해금", en: "Substory + Image Video 03 unlock" },
      },
      {
        number: 26,
        title: { ko: "사키 — 접객 연습 1회차", en: "Saki — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「멋진 취미네」 → 2) 「가라아게 너무 좋아」 → 3) 「좋은 엄마가 될 것 같다」 → 4) 「내가 처치하러 가줄까」", en: "Correct choices (in order): 1) \"That's a cool hobby\" → 2) \"I love karaage\" → 3) \"You'd make a great mom\" → 4) \"Want me to go take care of him?\"" },
      },
      {
        number: 27,
        title: { ko: "사키 — 접객 연습 2회차", en: "Saki — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「나는 남자다워 보이나?」 → 2) 「응석 부려보면 어떻노」 → 3) 「그 사람도 기뻤겠다」 → 4) 「괜찮지 않노」", en: "Correct choices (in order): 1) \"Do I seem manly?\" → 2) \"Why don't you try acting spoiled?\" → 3) \"He must've been happy\" → 4) \"That's fine, isn't it\"" },
      },
      {
        number: 28,
        title: { ko: "사키 — 동반 연습 — 디스코", en: "Saki — Companion Practice — Disco" },
        location: { ko: "동반 연습 — 디스코", en: "Companion Practice — Disco" },
        body: { ko: "정답 경로: 「I wanna take you home」으로 승부 Result★3이면 퍼펙트 레슨", en: "Correct path: Compete with \"I Wanna Take You Home\" — get Result★3 for a Perfect Lesson" },
      },
      {
        number: 29,
        title: { ko: "사키 — 접객 연습 3회차", en: "Saki — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「목표를 향해 달리는 집념」 → 2) 「연속 출근해주면 도움이 된다」 → 3) 「가라아게」 → 4) 「있다」", en: "Correct choices (in order): 1) \"Drive that runs toward a goal\" → 2) \"It'd help if you worked consecutive days\" → 3) \"Karaage\" → 4) \"There is\"" },
      },
      {
        number: 30,
        title: { ko: "사키 — 동반 연습 — 당구", en: "Saki — Companion Practice — Billiards" },
        location: { ko: "동반 연습 — 당구", en: "Companion Practice — Billiards" },
        body: { ko: "정답 경로: 나인볼로 사키와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play nine-ball against Saki — win for a Perfect Lesson" },
      },
      {
        number: 31,
        title: { ko: "사키 — 접객 연습 4회차", en: "Saki — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「형제자매가 많았으니까」 → 2) 「힘들면 말하그라」 → 3) 「섭섭하지만 응원한다카이」 → 4) 「무작정 한다고 되는 게 아니다」", en: "Correct choices (in order): 1) \"You had a lot of siblings, after all\" → 2) \"Tell me when it gets tough\" → 3) \"I'll miss ya, but I'm cheering for you\" → 4) \"You can't just charge in blindly\"" },
      },
      {
        number: 32,
        title: { ko: "사키 — 접객 연습 최종 회차", en: "Saki — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「여자아이니까 그렇지」 → 2) 「이걸로 공부에 집중할 수 있다」 → 3) 「다치면 큰일이다카이」 → 4) 「오빠… 라」 → 5) 간다라에 이미지 비디오 05 「하츠미 사키」 입고", en: "Correct choices (in order): 1) \"You are a girl, after all\" → 2) \"Now you can focus on your studies\" → 3) \"It'd be bad if you got hurt\" → 4) \"Big brother... huh\" → 5) Image Video 05 \"Saki Hatsumi\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 05 해금", en: "Substory + Image Video 05 unlock" },
      },
      {
        number: 33,
        title: { ko: "히비키 — 접객 연습 1회차", en: "Hibiki — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「때로는 엄격하게」 → 2) 「무리하면 안 된다」 → 3) 「어떤 만화를 좋아하노?」 → 4) 「무리할 필요는 없다」", en: "Correct choices (in order): 1) \"Sometimes strict\" → 2) \"Don't push yourself too hard\" → 3) \"What kind of manga do you like?\" → 4) \"You don't need to force it\"" },
      },
      {
        number: 34,
        title: { ko: "히비키 — 접객 연습 2회차", en: "Hibiki — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「좋은 생각이라고 본다」 → 2) 「히비키의 목소리가 좋다」 → 3) 「나도 응석 부리게 해다오」 → 4) 「그거 귀엽잖아!」", en: "Correct choices (in order): 1) \"I think that's a good idea\" → 2) \"I like Hibiki's voice\" → 3) \"Let me lean on you too\" → 4) \"That's cute!\"" },
      },
      {
        number: 35,
        title: { ko: "히비키 — 동반 연습 — 다트", en: "Hibiki — Companion Practice — Darts" },
        location: { ko: "동반 연습 — 다트", en: "Companion Practice — Darts" },
        body: { ko: "정답 경로: COUNT-UP으로 히비키와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play Count-Up against Hibiki — win for a Perfect Lesson" },
      },
      {
        number: 36,
        title: { ko: "히비키 — 접객 연습 3회차", en: "Hibiki — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「아이들에게 미움받음」 → 2) 「여자의 멋진 점」 → 3) 「연상이다」 → 4) 「그다지 활기차지 않은 아이도 좋다」", en: "Correct choices (in order): 1) \"Disliked by kids\" → 2) \"What's wonderful about girls\" → 3) \"Older women\" → 4) \"I also like girls who aren't so peppy\"" },
      },
      {
        number: 37,
        title: { ko: "히비키 — 동반 연습 — 노래방", en: "Hibiki — Companion Practice — Karaoke" },
        location: { ko: "동반 연습 — 노래방", en: "Companion Practice — Karaoke" },
        body: { ko: "정답 경로: 「Rouge of Love」에서 추임새를 넣는다 · 「24시간 신데렐라」를 부른다 둘 다 90점 이상이면 퍼펙트 레슨", en: "Correct path: Do the call-and-response on \"Rouge of Love\" / Sing \"24-Hour Cinderella\" — score 90+ on both for a Perfect Lesson" },
      },
      {
        number: 38,
        title: { ko: "히비키 — 접객 연습 4회차", en: "Hibiki — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「몸이 걱정이다」 → 2) 「언젠가 알게 될 날이 온다」 → 3) 「가게 일만으로도 벅차다…」 → 4) 「나도 놀아보고 싶다카이」", en: "Correct choices (in order): 1) \"I'm worried about your health\" → 2) \"Someday you'll understand\" → 3) \"The shop keeps me busy enough...\" → 4) \"I'd like to play too\"" },
      },
      {
        number: 39,
        title: { ko: "히비키 — 접객 연습 최종 회차", en: "Hibiki — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「너무 짊어지지 마라」 → 2) 「히비키는 행복하구나」 → 3) 「그릇이 큰 남자」 → 4) 「고맙다」 → 5) 간다라에 이미지 비디오 04 「오오츠키 히비키」 입고", en: "Correct choices (in order): 1) \"You're carrying too much\" → 2) \"You're a lucky girl, Hibiki\" → 3) \"A big-hearted man\" → 4) \"Thank you\" → 5) Image Video 04 \"Hibiki Ohtsuki\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 04 해금", en: "Substory + Image Video 04 unlock" },
      },
      {
        number: 40,
        title: { ko: "치카 — 접객 연습 1회차", en: "Chika — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「치카에게 딱이네」 → 2) 「조금쯤 달라야 재밌다」 → 3) 「인생은 돌아가는 길도 중요하다」 → 4) 「싫어도 미소는 지어야 한다」", en: "Correct choices (in order): 1) \"That suits Chika perfectly\" → 2) \"A bit of difference makes things fun\" → 3) \"Detours in life matter too\" → 4) \"You have to smile even when you don't feel like it\"" },
      },
      {
        number: 41,
        title: { ko: "치카 — 접객 연습 2회차", en: "Chika — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「나쁜 남자에게 속는 타입?」 → 2) 「나는 이해 못 하겠다」 → 3) 「상대에게 맞출 필요 없다」 → 4) 「길 잃는 건 잘하잖아?」", en: "Correct choices (in order): 1) \"The type to get tricked by a bad guy?\" → 2) \"I can't really understand that\" → 3) \"No need to match the other person\" → 4) \"You're good at getting lost, right?\"" },
      },
      {
        number: 42,
        title: { ko: "치카 — 접객 연습 3회차", en: "Chika — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「얌전하고 여성스러운 딸」 → 2) 「사려던 걸 깜빡하기도 하지」 → 3) 「결혼한 내 모습이 상상이 안 된다」 → 4) 「소중한 존재다카이」", en: "Correct choices (in order): 1) \"A graceful, ladylike daughter\" → 2) \"Sometimes forgets what she came to buy\" → 3) \"I can't picture myself married\" → 4) \"You're precious to me\"" },
      },
      {
        number: 43,
        title: { ko: "치카 — 동반 연습 — 당구", en: "Chika — Companion Practice — Billiards" },
        location: { ko: "동반 연습 — 당구", en: "Companion Practice — Billiards" },
        body: { ko: "정답 경로: 나인볼로 치카와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play nine-ball against Chika — win for a Perfect Lesson" },
      },
      {
        number: 44,
        title: { ko: "치카 — 접객 연습 4회차", en: "Chika — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「평소 모습이 더 좋다」 → 2) 「정열적이네」 → 3) 「어떤 가정을 꾸릴 거노?」 → 4) 「일에서도 좋은 만남은 있다」", en: "Correct choices (in order): 1) \"I prefer your usual self\" → 2) \"How passionate\" → 3) \"What kind of home would you build?\" → 4) \"You can find good people through work too\"" },
      },
      {
        number: 45,
        title: { ko: "치카 — 동반 연습 — 노래방", en: "Chika — Companion Practice — Karaoke" },
        location: { ko: "동반 연습 — 노래방", en: "Companion Practice — Karaoke" },
        body: { ko: "정답 경로: 「찰나의 인어공주」에서 추임새를 넣는다 · 「24시간 신데렐라」를 부른다 둘 다 90점 이상이면 퍼펙트 레슨", en: "Correct path: Do the call-and-response on \"Mermaid of a Moment\" / Sing \"24-Hour Cinderella\" — score 90+ on both for a Perfect Lesson" },
      },
      {
        number: 46,
        title: { ko: "치카 — 접객 연습 최종 회차", en: "Chika — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「나도 즐거우니까」 → 2) 「즐겁게 하는 게 최고다」 → 3) 「치카에게는 말이다」 → 4) 「다른 가게로 가지 말아다오!」 → 5) 간다라에 이미지 비디오 01 「아리무라 치카」 입고", en: "Correct choices (in order): 1) \"Because I'm having fun too\" → 2) \"Doing it with joy is the best\" → 3) \"For you, Chika...\" → 4) \"Don't go to another shop!\" → 5) Image Video 01 \"Chika Arimura\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 01 해금", en: "Substory + Image Video 01 unlock" },
      },
      {
        number: 47,
        title: { ko: "마나 — 접객 연습 1회차", en: "Mana — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「자신에게 보상을 줘야지」 → 2) 「마나랑 똑 닮았다」 → 3) 「거짓말쟁이라서 알아보는 걸지도」 → 4) 「휴지를 준비해둬야겠네」", en: "Correct choices (in order): 1) \"You've gotta reward yourself\" → 2) \"Looks just like Mana\" → 3) \"Maybe a liar can spot one\" → 4) \"Better grab some tissues\"" },
      },
      {
        number: 48,
        title: { ko: "마나 — 접객 연습 2회차", en: "Mana — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「진짜로 연애 경험이 없구나」 → 2) 「이상하지 않다」 → 3) 「할아버지들 상대로 하는 장사다」 → 4) 「알겠다」", en: "Correct choices (in order): 1) \"You really have no dating experience\" → 2) \"It's not weird\" → 3) \"It's a business catering to old men\" → 4) \"Got it\"" },
      },
      {
        number: 49,
        title: { ko: "마나 — 접객 연습 3회차", en: "Mana — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「마음에 드는 사람이라면」 → 2) 「나는 M이다」 → 3) 「언젠가 호되게 당한다」 → 4) 「무리하지 말고 병원 가라」", en: "Correct choices (in order): 1) \"If it's someone I'm into\" → 2) \"I'm an M\" → 3) \"You'll get burned someday\" → 4) \"Don't push it, go to the doctor\"" },
      },
      {
        number: 50,
        title: { ko: "마나 — 동반 연습 — 다트", en: "Mana — Companion Practice — Darts" },
        location: { ko: "동반 연습 — 다트", en: "Companion Practice — Darts" },
        body: { ko: "정답 경로: COUNT-UP으로 마나와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play Count-Up against Mana — win for a Perfect Lesson" },
      },
      {
        number: 51,
        title: { ko: "마나 — 접객 연습 4회차", en: "Mana — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「네 페이스대로 말해라」 → 2) 「알려줘서 고맙다카이」 → 3) 「자기 자신을 가꿔라」 → 4) 「성실한 면을 알게 됐다」", en: "Correct choices (in order): 1) \"Speak at your own pace\" → 2) \"Thanks for telling me\" → 3) \"Polish yourself up\" → 4) \"I got to see your serious side\"" },
      },
      {
        number: 52,
        title: { ko: "마나 — 동반 연습 — 디스코", en: "Mana — Companion Practice — Disco" },
        location: { ko: "동반 연습 — 디스코", en: "Companion Practice — Disco" },
        body: { ko: "정답 경로: 「I'm gonna make her mine」으로 승부 Result★3이면 퍼펙트 레슨", en: "Correct path: Compete with \"I'm Gonna Make Her Mine\" — get Result★3 for a Perfect Lesson" },
      },
      {
        number: 53,
        title: { ko: "마나 — 접객 연습 최종 회차", en: "Mana — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「마나만 있으면 무적이다」 → 2) 「정신적인 문제일지도 모른다」 → 3) 「살짝 질투했다」 → 4) 「모두가 소중하니까 그런 거다」 → 5) 간다라에 이미지 비디오 02 「사쿠라 마나」 입고", en: "Correct choices (in order): 1) \"With Mana around, I'm unstoppable\" → 2) \"Might be a mental thing\" → 3) \"I got a little jealous\" → 4) \"It's because everyone's important to me\" → 5) Image Video 02 \"Mana Sakura\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 02 해금", en: "Substory + Image Video 02 unlock" },
      },
      ],
    },
    ],
  },
  {
    slug: "video-clips",
    title: { ko: "비디오 — 간다라 비디오 가게 + 특별 클립 해금", en: "Video — Gandara Shop + Special Clip Unlocks" },
    summary: { ko: "용과 같이 0의 비디오 콘텐츠는 「간다라(ガンダーラ)」 비디오 가게에서 진행됩니다. 일반 이미지 비디오를 반복 시청하면 점원과의 호감도가 오르고, 특정 조건을 만족시키면 서브스토리 + 특별 클립이 해금됩니다. 30종 일괄 수집 시스템은 없으며, 핵심은 호감도 + 사이드 트리거입니다.", en: "Y0's video content lives at the Gandara (ガンダーラ) video shop. Watching standard image videos repeatedly raises affinity with the clerk; specific triggers unlock substories + special clips. There is no flat 30-clip checklist — what matters is affinity + side triggers." },
    tips: [
        { ko: "간다라 소텐보리점에서 처음 비디오를 보면 서브스토리가 자동 발생. 점원과의 절(絆) 게이지가 함께 오릅니다.", en: "First viewing at Sotenbori Gandara auto-triggers a substory + starts the clerk's bond gauge." },
        { ko: "천량 거리 북쪽 간다라에서 이미지 비디오 3회 시청 후 입장하면 서브스토리 「비디오 걸」 발생.", en: "Watch any image video 3 times at the Senryo St. North Gandara then re-enter to trigger substory 'Video Girl'." },
        { ko: "점원 절 게이지가 90 이상일 때 비디오 시청 → 오디세이 창고 앞 흰 옷 여성과 대화 → M스토어 쇼후쿠초점에서 「오뎅 모듬」 구매 → 여성에게 전달 → 「예의 비디오(例のビデオ)」 입수.", en: "Affinity 90+: watch a video → talk to the white-dressed woman in front of the Odyssey warehouse → buy 'Oden Assortment' at M-Store Shofukucho → give it to her → obtain the 'Special Video'." },
    ],
    source: { label: "龍が如く0 攻略 — ガンダーラ・ビデオ", url: "https://spwiki.net/ryuzero/" },
    items: [
      {
        number: 1,
        title: { ko: "간다라 소텐보리점 — 첫 비디오 + 서브스토리", en: "Gandara Sotenbori — First Video + Substory" },
        location: { ko: "소텐보리 — 동쪽 골목", en: "Sotenbori — east alley" },
        body: { ko: "마지마 편 장 진행 후 입장 가능. 첫 비디오 시청 시 서브스토리 자동 발생.", en: "Accessible during Majima chapters. First viewing auto-triggers the venue substory." },
      },
      {
        number: 2,
        title: { ko: "간다라 천량 거리 북점 — 「비디오 걸」 서브스토리", en: "Gandara Senryo North — 'Video Girl' substory" },
        location: { ko: "카무로초 — 천량 거리 북쪽", en: "Kamurocho — Senryo St. North" },
        body: { ko: "키류 편. 이미지 비디오를 3회 시청한 뒤 점내 재입장 시 서브스토리 시작.", en: "Kiryu side. Watch any image video 3 times, then re-enter the shop." },
      },
      {
        number: 3,
        title: { ko: "점원 호감도 → 90 도달 시 특수 이벤트", en: "Clerk Affinity 90 → Special Event" },
        location: { ko: "간다라 양 지점", en: "Either Gandara branch" },
        body: { ko: "같은 이미지 비디오 반복 시청으로도 호감도 상승. 호감도 90 이상에서 다음 시청 시 컷신 트리거.", en: "Repeated viewings (even the same video) raise affinity. At 90+, the next viewing triggers a cutscene." },
      },
      {
        number: 4,
        title: { ko: "오디세이 창고 앞 흰 옷 여성 대화", en: "White-Dressed Woman at Odyssey Warehouse" },
        location: { ko: "소텐보리 — 오디세이 창고", en: "Sotenbori — Odyssey warehouse" },
        body: { ko: "특수 이벤트 후 등장. 「오뎅 모듬」을 요청하니 M스토어 쇼후쿠초점에서 구매해 전달.", en: "Appears after the special event. Buy 'Oden Assortment' at M-Store Shofukucho and bring it." },
      },
      {
        number: 5,
        title: { ko: "예의 비디오 — 최종 보상", en: "Special Video — Final Reward" },
        location: { ko: "간다라 (예의 비디오로 재시청)", en: "Gandara (replay 'Special Video')" },
        body: { ko: "오뎅 전달 후 받는 「예의 비디오」를 가지고 간다라에서 시청. 컴플리트 리스트 + 사이드 보상 발생.", en: "After receiving the 'Special Video', return to Gandara to watch it — completes the side reward + Completion List entry." },
        reward: { ko: "컴플리트 리스트 항목 + 절륜 친구 라인 활성화", en: "Completion List entry + bond friendship line activated" },
      },
    ],
  },
  ],
};
