import type { CollectiblesData } from "./types";

export const yakuzaKiwami2: CollectiblesData = {
  appId: 3717340,
  categories: [
    {
      slug: "coin-lockers",
      title: { ko: "물품 보관함 — 양 도시 100개 열쇠와 보상", en: "Coin Lockers — All 100 Keys & Rewards (Both Cities)" },
      summary: {
        ko: "카무로초 50개 + 소텐보리 50개, 총 100개 코인로커 열쇠의 위치와 내용물을 정리했습니다. 보관함은 카무로초 타이헤이 거리·소텐보리 쇼후쿠초 서쪽에 있습니다. 지도의 번호가 카드 번호와 일치합니다.",
        en: "All 100 coin-locker keys (50 Kamurocho + 50 Sotenbori) with locations and contents. Map numbers match the card numbers.",
      },
      tips: [
        { ko: "거리·건물 바닥에서 반짝이는 곳을 조사하면 열쇠를 얻습니다. 「로커키 워처(E3)」를 입수하면 미니맵에 열쇠 위치가 표시됩니다.", en: "Investigate shining spots on the ground to get keys. The Locker Key Watcher (E3) marks keys on the minimap." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く極2 神室町のコインロッカー", url: "https://dswiipspwikips3.jp/yakuza-kiwami2/cheats-data/kamurocho-coin-locker-keys.html" },
      groups: [
      {
        title: { ko: "카무로초 — 50개 열쇠", en: "Kamurocho — 50 Keys" },
        mapImage: "https://dswiipspwikips3-images.jp/yakuza-kiwami2/kamurocho-coin-locker-keys.jpg",
        hotspots: {
          1: [85.4, 41.1], 2: [8.4, 60.7], 3: [94.1, 66.3], 4: [19.3, 76.9], 5: [58.6, 51.6], 6: [6.5, 18.6], 7: [21.5, 83.4], 8: [80.1, 35.5], 9: [51, 89.3], 10: [36.2, 74.7],
          11: [10.2, 18.6], 12: [50.5, 65.2], 13: [17.8, 57.3], 14: [12.1, 36.6], 15: [37.1, 44.7], 16: [13.4, 50.5], 17: [86.9, 65.9], 18: [35.7, 85.2], 19: [96.3, 26.6], 20: [50.5, 54],
          21: [50.1, 63.7], 22: [78.9, 48.1], 23: [28.6, 88.8], 24: [97.1, 61.3], 25: [87.7, 74], 26: [72.3, 89.1], 27: [57.7, 53.6], 28: [63.7, 75], 29: [75.5, 86.3], 30: [33.4, 31.7],
          31: [93.1, 72.1], 32: [24, 54.3], 33: [93.2, 89.2], 34: [35.1, 86], 35: [66.2, 81.6], 36: [44, 59.1], 37: [97.1, 37.6], 38: [77.8, 35.4], 39: [45.2, 22.1], 40: [91.3, 36.1],
          41: [42.2, 69.9], 42: [82.8, 27.3], 43: [58.9, 84.3], 44: [44.1, 53.3], 45: [51.8, 48.5], 46: [52.2, 81.6], 47: [67.8, 23.9], 48: [78, 73.6], 49: [50.4, 34.1], 50: [50.5, 39.8],
        },
        items: [
      {
        number: 1,
        title: { ko: "A1 · 1장", en: "A1 · Ch.1" },
        location: { ko: "막다른 곳에 열쇠가 떨어져 있다", en: "Key at the dead end" },
        reward: { ko: "잭나이프", en: "Switchblade" },
      },
      {
        number: 2,
        title: { ko: "A2 · 1장", en: "A2 · Ch.1" },
        location: { ko: "「극장 앞 광장 뒤」 도로에 열쇠가 떨어져 있다", en: "Key on the road behind Theater Square" },
        reward: { ko: "살충제", en: "Insecticide" },
      },
      {
        number: 3,
        title: { ko: "A3 · 1장", en: "A3 · Ch.1" },
        location: { ko: "쓰레기통 부근에 열쇠가 떨어져 있다", en: "Key near the trash bin" },
        reward: { ko: "스태미난 로열", en: "Staminan Royal" },
      },
      {
        number: 4,
        title: { ko: "A4 · 1장", en: "A4 · Ch.1" },
        location: { ko: "넷카페 간판 근처에 열쇠가 떨어져 있다", en: "Key near the net cafe sign" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 5,
        title: { ko: "A5 · 1장", en: "A5 · Ch.1" },
        location: { ko: "주차장 기둥 부근에 열쇠가 떨어져 있다", en: "Key near the parking pillar" },
        reward: { ko: "플래티넘 접시", en: "Platinum Plate" },
      },
      {
        number: 6,
        title: { ko: "B1 · 6장", en: "B1 · Ch.6" },
        location: { ko: "서브스토리 No.16 「비밀의 물건」 진행 중 입수", en: "From substory No.16 \"Secret Goods\"" },
        reward: { ko: "수상한 비디오", en: "Suspicious Video" },
      },
      {
        number: 7,
        title: { ko: "B2 · 1장", en: "B2 · Ch.1" },
        location: { ko: "「세레나 뒤」 쓰레기통 근처에 열쇠가 떨어져 있다", en: "Key near the trash bin behind Serena" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 8,
        title: { ko: "B3 · 1장", en: "B3 · Ch.1" },
        location: { ko: "건물 4층 창가 부근에 열쇠가 떨어져 있다", en: "Key by the 4th-floor window inside the building" },
        reward: { ko: "전국 사슬갑주", en: "Sengoku Chainmail" },
      },
      {
        number: 9,
        title: { ko: "B4 · 1장", en: "B4 · Ch.1" },
        location: { ko: "거리 도로에 열쇠가 떨어져 있다", en: "Key on the street road" },
        reward: { ko: "철 파이프", en: "Iron Pipe" },
      },
      {
        number: 10,
        title: { ko: "B5 · 1장", en: "B5 · Ch.1" },
        location: { ko: "「천하일 거리 뒤」 구석 바닥에 열쇠가 떨어져 있다", en: "Key in the corner behind Tenkaichi St" },
        reward: { ko: "100파운드 마이볼", en: "100-Pound My Ball" },
      },
      {
        number: 11,
        title: { ko: "C1 · 5장", en: "C1 · Ch.5" },
        location: { ko: "서브스토리 No.9 「메일로 일하기」 진행 중 입수", en: "From substory No.9 \"Work by Email\"" },
        reward: { ko: "녹색 상자", en: "Green Box" },
      },
      {
        number: 12,
        title: { ko: "C2 · 1장", en: "C2 · Ch.1" },
        location: { ko: "작은 지붕 기둥 밑동에 열쇠가 놓여 있다", en: "Key at the base of the small roof pillar" },
        reward: { ko: "스태미난 X", en: "Staminan X" },
      },
      {
        number: 13,
        title: { ko: "C3 · 1장", en: "C3 · Ch.1" },
        location: { ko: "간판 아래에 열쇠가 떨어져 있다", en: "Key under the sign" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 14,
        title: { ko: "C4 · 1장", en: "C4 · Ch.1" },
        location: { ko: "「아동 공원」 자판기 근처 바닥에 열쇠가 떨어져 있다", en: "Key by the children's park vending machine" },
        reward: { ko: "구리 접시", en: "Copper Plate" },
      },
      {
        number: 15,
        title: { ko: "C5 · 1장", en: "C5 · Ch.1" },
        location: { ko: "교통 표지판 근처 도로에 열쇠가 떨어져 있다", en: "Key on the road near the traffic sign" },
        reward: { ko: "램프 스탠드", en: "Lamp Stand" },
      },
      {
        number: 16,
        title: { ko: "D1 · 1장", en: "D1 · Ch.1" },
        location: { ko: "「뉴 텐포 시네마」 입구에 열쇠가 떨어져 있다", en: "Key at the New Tenpo Cinema entrance" },
        reward: { ko: "아라시의 양갱", en: "Arashi's Yokan" },
      },
      {
        number: 17,
        title: { ko: "D2 · 1장", en: "D2 · Ch.1" },
        location: { ko: "스쿠터 근처에 열쇠가 떨어져 있다", en: "Key near the scooter" },
        reward: { ko: "빠루", en: "Crowbar" },
      },
      {
        number: 18,
        title: { ko: "D3 · 1장", en: "D3 · Ch.1" },
        location: { ko: "「제3공원」 바닥에 열쇠가 떨어져 있다", en: "Key on the Third Park ground" },
        reward: { ko: "터프니스 라이트", en: "Toughness Light" },
      },
      {
        number: 19,
        title: { ko: "D4 · 5장", en: "D4 · Ch.5" },
        location: { ko: "카무로초 힐즈 건설 현장 구석 바닥에 열쇠가 떨어져 있다", en: "Key in the corner of the Kamurocho Hills site" },
        reward: { ko: "도싯핀즈", en: "Doshippins" },
      },
      {
        number: 20,
        title: { ko: "D5 · 8장", en: "D5 · Ch.8" },
        location: { ko: "밀레니엄 타워 1층 에스컬레이터 부근(서쪽). 메인 스토리 진행 후 진입 가능", en: "Millennium Tower 1F escalator (west); enter via story progress" },
        reward: { ko: "타우리너++", en: "Tauriner++" },
      },
      {
        number: 21,
        title: { ko: "E1 · 1장", en: "E1 · Ch.1" },
        location: { ko: "벤치 근처 바닥에 열쇠가 떨어져 있다", en: "Key on the floor near the bench" },
        reward: { ko: "근육의 서", en: "Tome of Muscle" },
      },
      {
        number: 22,
        title: { ko: "E2 · 1장", en: "E2 · Ch.1" },
        location: { ko: "「시치후쿠 파크」 간판 뒤에 열쇠가 떨어져 있다", en: "Key behind the Shichifuku Park sign" },
        reward: { ko: "샷건", en: "Shotgun" },
      },
      {
        number: 23,
        title: { ko: "E3 · 1장", en: "E3 · Ch.1" },
        location: { ko: "「천하일 거리」 도로에 열쇠가 떨어져 있다", en: "Key on Tenkaichi St road" },
        reward: { ko: "로커키 워처", en: "Locker Key Watcher" },
      },
      {
        number: 24,
        title: { ko: "E4 · 1장", en: "E4 · Ch.1" },
        location: { ko: "쓰레기통 부근에 열쇠가 떨어져 있다", en: "Key near the trash bin" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 25,
        title: { ko: "E5 · 1장", en: "E5 · Ch.1" },
        location: { ko: "자판기 뒤쪽에 열쇠가 떨어져 있다", en: "Key behind the vending machine" },
        reward: { ko: "톤파", en: "Tonfa" },
      },
      {
        number: 26,
        title: { ko: "F1 · 1장", en: "F1 · Ch.1" },
        location: { ko: "통로 모퉁이에 열쇠가 떨어져 있다", en: "Key at the passage corner" },
        reward: { ko: "플래티넘 접시", en: "Platinum Plate" },
      },
      {
        number: 27,
        title: { ko: "F2 · 8장", en: "F2 · Ch.8" },
        location: { ko: "밀레니엄 타워 1층 에스컬레이터 부근(동쪽). 메인 스토리 진행 후 진입 가능", en: "Millennium Tower 1F escalator (east); enter via story progress" },
        reward: { ko: "스태미난 로열", en: "Staminan Royal" },
      },
      {
        number: 28,
        title: { ko: "F3 · 1장", en: "F3 · Ch.1" },
        location: { ko: "가스통 부근에 열쇠가 떨어져 있다", en: "Key near the gas cylinder" },
        reward: { ko: "금 접시", en: "Gold Plate" },
      },
      {
        number: 29,
        title: { ko: "F4 · 1장", en: "F4 · Ch.1" },
        location: { ko: "쓰레기통 부근에 열쇠가 떨어져 있다", en: "Key near the trash bin" },
        reward: { ko: "유도봉", en: "Guide Baton" },
      },
      {
        number: 30,
        title: { ko: "F5 · 1장", en: "F5 · Ch.1" },
        location: { ko: "「요시다 배팅센터」 지붕에 열쇠가 떨어져 있다. 정면 반대편 동쪽 계단으로 지붕에 오를 수 있다", en: "Key on the Yoshida Batting Center roof; climb via the east stairs" },
        reward: { ko: "개조 다리미", en: "Modified Iron" },
      },
      {
        number: 31,
        title: { ko: "G1 · 1장", en: "G1 · Ch.1" },
        location: { ko: "택시 승차장 부근 도로에 열쇠가 떨어져 있다", en: "Key on the road near the taxi stand" },
        reward: { ko: "구리 접시", en: "Copper Plate" },
      },
      {
        number: 32,
        title: { ko: "G2 · 1장", en: "G2 · Ch.1" },
        location: { ko: "「극장 앞 광장」 바닥에 열쇠가 떨어져 있다", en: "Key on the Theater Square ground" },
        reward: { ko: "투박한 복대", en: "Rugged Belly Wrap" },
      },
      {
        number: 33,
        title: { ko: "G3 · 1장", en: "G3 · Ch.1" },
        location: { ko: "자전거 보관소에 열쇠가 떨어져 있다", en: "Key at the bicycle parking" },
        reward: { ko: "쇠몽둥이", en: "Iron Club" },
      },
      {
        number: 34,
        title: { ko: "G4 · 1장", en: "G4 · Ch.1" },
        location: { ko: "건물 1층 통로 안쪽 화장실 근처 바닥에 열쇠가 떨어져 있다", en: "Key by the 1F restroom inside the building" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 35,
        title: { ko: "G5 · 1장", en: "G5 · Ch.1" },
        location: { ko: "「무료 안내소」 바닥에 열쇠가 떨어져 있다", en: "Key on the info-center floor" },
        reward: { ko: "로열 조커", en: "Royal Joker" },
      },
      {
        number: 36,
        title: { ko: "H1 · 1장", en: "H1 · Ch.1" },
        location: { ko: "코인로커가 있는 곳 통로 안쪽에 열쇠가 떨어져 있다", en: "Key deep in the passage by the coin lockers" },
        reward: { ko: "스태미난 XX", en: "Staminan XX" },
      },
      {
        number: 37,
        title: { ko: "H2 · 1장", en: "H2 · Ch.1" },
        location: { ko: "노숙자 텐트 근처에 열쇠가 떨어져 있다", en: "Key near the homeless tent" },
        reward: { ko: "싸움 사라시", en: "Brawler's Sarashi" },
      },
      {
        number: 38,
        title: { ko: "H3 · 1장", en: "H3 · Ch.1" },
        location: { ko: "건물 계단 층계참(2/3)에 열쇠가 떨어져 있다", en: "Key on the stair landing (2/3)" },
        reward: { ko: "경쾌 벨트", en: "Light Belt" },
      },
      {
        number: 39,
        title: { ko: "H4 · 1장", en: "H4 · Ch.1" },
        location: { ko: "택시 승차장 근처 금속판 위에 열쇠가 떨어져 있다", en: "Key on the metal plate near the taxi stand" },
        reward: { ko: "터프니스 Z", en: "Toughness Z" },
      },
      {
        number: 40,
        title: { ko: "H5 · 1장", en: "H5 · Ch.1" },
        location: { ko: "화장실 안 세면대 바닥에 열쇠가 떨어져 있다", en: "Key on the restroom sink floor" },
        reward: { ko: "행운 화투", en: "Lucky Hanafuda" },
      },
      {
        number: 41,
        title: { ko: "I1 · 1장", en: "I1 · Ch.1" },
        location: { ko: "건물 안 바닥에 열쇠가 떨어져 있다", en: "Key on the floor inside the building" },
        reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" },
      },
      {
        number: 42,
        title: { ko: "I2 · 5장", en: "I2 · Ch.5" },
        location: { ko: "카무로초 힐즈 건설 현장 경트럭 근처에 열쇠가 떨어져 있다", en: "Key near the kei-truck at the Kamurocho Hills site" },
        reward: { ko: "BJ의 부적", en: "BJ Charm" },
      },
      {
        number: 43,
        title: { ko: "I3 · 1장", en: "I3 · Ch.1" },
        location: { ko: "거리 도로에 열쇠가 떨어져 있다", en: "Key on the street road" },
        reward: { ko: "식탁 소금", en: "Table Salt" },
      },
      {
        number: 44,
        title: { ko: "I4 · 1장", en: "I4 · Ch.1" },
        location: { ko: "피자 가게 근처 통로에 열쇠가 떨어져 있다", en: "Key in the passage near the pizza shop" },
        reward: { ko: "구리 접시", en: "Copper Plate" },
      },
      {
        number: 45,
        title: { ko: "I5 · 1장", en: "I5 · Ch.1" },
        location: { ko: "벤치 근처에 열쇠가 떨어져 있다", en: "Key near the bench" },
        reward: { ko: "절연체 셔츠", en: "Insulator Shirt" },
      },
      {
        number: 46,
        title: { ko: "J1 · 1장", en: "J1 · Ch.1" },
        location: { ko: "「무료 안내소」 바닥에 열쇠가 떨어져 있다", en: "Key on the info-center floor" },
        reward: { ko: "레더 브레스", en: "Leather Bracelet" },
      },
      {
        number: 47,
        title: { ko: "J2 · 5장", en: "J2 · Ch.5" },
        location: { ko: "카무로초 힐즈 건설 현장 구석 바닥에 열쇠가 떨어져 있다", en: "Key in the corner of the Kamurocho Hills site" },
        reward: { ko: "버스트의 부적", en: "Burst Charm" },
      },
      {
        number: 48,
        title: { ko: "J3 · 1장", en: "J3 · Ch.1" },
        location: { ko: "「타이헤이 거리 동쪽」 도로에 열쇠가 떨어져 있다", en: "Key on East Taihei Blvd road" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 49,
        title: { ko: "J4 · 4장", en: "J4 · Ch.4" },
        location: { ko: "서브스토리 No.22 「류구죠」 클리어 후 갈 수 있는 류구죠 3층 복도에 열쇠가 떨어져 있다", en: "Key in the Ryugujo 3F hall (after substory No.22)" },
        reward: { ko: "목발", en: "Crutch" },
      },
      {
        number: 50,
        title: { ko: "J5 · 1장", en: "J5 · Ch.1" },
        location: { ko: "「무료 안내소」 안 바닥에 열쇠가 떨어져 있다", en: "Key inside the info center" },
        reward: { ko: "매력의 서", en: "Tome of Charm" },
      },
        ],
      },
      {
        title: { ko: "소텐보리 — 50개 열쇠", en: "Sotenbori — 50 Keys" },
        mapImage: "https://dswiipspwikips3-images.jp/yakuza-kiwami2/soutenbori-coin-locker-keys.jpg",
        hotspots: {
          1: [28, 31.4], 2: [89.8, 47.7], 3: [81.1, 20.5], 4: [45.2, 73.5], 5: [4.1, 62.1], 6: [89.3, 34.5], 7: [57.4, 32.2], 8: [45.3, 30.5], 9: [41.1, 51.6], 10: [19.1, 62.3],
          11: [42.5, 84], 12: [13, 84.2], 13: [61.8, 48], 14: [48.6, 61.1], 15: [21, 65.1], 16: [68.1, 20.5], 17: [55, 36.7], 18: [22.4, 47.6], 19: [72.8, 43], 20: [44.3, 70.4],
          21: [85.1, 15.2], 22: [75.4, 35], 23: [33.4, 40.1], 24: [49.3, 49.6], 25: [56.7, 78.9], 26: [83.6, 36.2], 27: [61.5, 25.8], 28: [73.5, 39.6], 29: [30.1, 75.1], 30: [24.4, 94.1],
          31: [45.6, 40.5], 32: [22.3, 27.1], 33: [44.1, 20.3], 34: [36.8, 37.4], 35: [29.2, 39.8], 36: [16.6, 19.6], 37: [13.3, 61], 38: [52.7, 69.7], 39: [63.1, 41.7], 40: [28.8, 14.2],
          41: [22.3, 45.9], 42: [23.3, 96.7], 43: [58.9, 18.7], 44: [49.3, 28.9], 45: [30.9, 72.9], 46: [69.4, 29.1], 47: [26.6, 27.2], 48: [27.9, 47.6], 49: [86.7, 73.5], 50: [49.9, 51.8],
        },
        items: [
      {
        number: 1,
        title: { ko: "A1 · 2장", en: "A1 · Ch.2" },
        location: { ko: "「비사몬교」 아래 통로에 열쇠가 떨어져 있다", en: "Key in the passage under Bishamon Bridge" },
        reward: { ko: "스태미난 XX", en: "Staminan XX" },
      },
      {
        number: 2,
        title: { ko: "A2 · 2장", en: "A2 · Ch.2" },
        location: { ko: "택시 승차장 부근 바닥에 열쇠가 떨어져 있다", en: "Key near the taxi stand" },
        reward: { ko: "구리 접시", en: "Copper Plate" },
      },
      {
        number: 3,
        title: { ko: "A3 · 2장", en: "A3 · Ch.2" },
        location: { ko: "아래로 내려가는 에스컬레이터 부근에 열쇠가 떨어져 있다", en: "Key near the down escalator" },
        reward: { ko: "환상의 톤파", en: "Phantom Tonfa" },
      },
      {
        number: 4,
        title: { ko: "A4 · 2장", en: "A4 · Ch.2" },
        location: { ko: "건물 현관에 열쇠가 떨어져 있다", en: "Key at the building entrance" },
        reward: { ko: "펜치", en: "Pliers" },
      },
      {
        number: 5,
        title: { ko: "A5 · 2장", en: "A5 · Ch.2" },
        location: { ko: "통로 안쪽 막다른 바닥에 열쇠가 떨어져 있다", en: "Key at the dead-end floor inside the passage" },
        reward: { ko: "로열 조커", en: "Royal Joker" },
      },
      {
        number: 6,
        title: { ko: "B1 · 2장", en: "B1 · Ch.2" },
        location: { ko: "「이와하시 다리」 아래 통로에 열쇠가 떨어져 있다", en: "Key in the passage under Iwa Bridge" },
        reward: { ko: "구식 오토 권총", en: "Old Auto Pistol" },
      },
      {
        number: 7,
        title: { ko: "B2 · 2장", en: "B2 · Ch.2" },
        location: { ko: "「소텐보리 측도」 강가에 열쇠가 떨어져 있다", en: "Key along the river on Sotenbori Path" },
        reward: { ko: "아라시의 양갱", en: "Arashi's Yokan" },
      },
      {
        number: 8,
        title: { ko: "B3 · 2장", en: "B3 · Ch.2" },
        location: { ko: "「소텐보리 측도」 강가 벤치 근처에 열쇠가 떨어져 있다", en: "Key near the riverside bench, Sotenbori Path" },
        reward: { ko: "메탈 글러브", en: "Metal Glove" },
      },
      {
        number: 9,
        title: { ko: "B4 · 2장", en: "B4 · Ch.2" },
        location: { ko: "돈키호테 앞 도로에 열쇠가 떨어져 있다", en: "Key on the road in front of Don Quijote" },
        reward: { ko: "검은 띠", en: "Black Belt" },
      },
      {
        number: 10,
        title: { ko: "B5 · 2장", en: "B5 · Ch.2" },
        location: { ko: "건물 계단을 올라 가라오케 스낵 앞 층계참에 열쇠가 떨어져 있다", en: "Key on the landing in front of the karaoke snack" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 11,
        title: { ko: "C1 · 2장", en: "C1 · Ch.2" },
        location: { ko: "가게 앞 현관 아래에 열쇠가 떨어져 있다", en: "Key below the shop entrance" },
        reward: { ko: "은 접시", en: "Silver Plate" },
      },
      {
        number: 12,
        title: { ko: "C2 · 2장", en: "C2 · Ch.2" },
        location: { ko: "차 주차장에 열쇠가 떨어져 있다", en: "Key at the car park" },
        reward: { ko: "준민의 서", en: "Tome of Agility" },
      },
      {
        number: 13,
        title: { ko: "C3 · 2장", en: "C3 · Ch.2" },
        location: { ko: "건물 진입을 막는 폴 아래에 열쇠가 떨어져 있다", en: "Key under the pole blocking the building" },
        reward: { ko: "기교의 서", en: "Tome of Technique" },
      },
      {
        number: 14,
        title: { ko: "C4 · 2장", en: "C4 · Ch.2" },
        location: { ko: "도로에 열쇠가 떨어져 있다", en: "Key on the road" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 15,
        title: { ko: "C5 · 2장", en: "C5 · Ch.2" },
        location: { ko: "가게 앞 도로에 열쇠가 떨어져 있다", en: "Key on the road in front of the shop" },
        reward: { ko: "팔각봉", en: "Octagonal Staff" },
      },
      {
        number: 16,
        title: { ko: "D1 · 2장", en: "D1 · Ch.2" },
        location: { ko: "자전거 보관소에 열쇠가 떨어져 있다", en: "Key at the bicycle parking" },
        reward: { ko: "하라헤루 RX", en: "Harahel RX" },
      },
      {
        number: 17,
        title: { ko: "D2 · 2장", en: "D2 · Ch.2" },
        location: { ko: "「소텐보리 측도」 강가에 열쇠가 떨어져 있다", en: "Key along the river on Sotenbori Path" },
        reward: { ko: "대신 돌", en: "Decoy Stone" },
      },
      {
        number: 18,
        title: { ko: "D3 · 2장", en: "D3 · Ch.2" },
        location: { ko: "건물 내 계단을 오른 2층 실내에 열쇠가 떨어져 있다", en: "Key in the 2F room up the building stairs" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 19,
        title: { ko: "D4 · 2장", en: "D4 · Ch.2" },
        location: { ko: "계단 아래 건물 현관에 열쇠가 떨어져 있다", en: "Key at the building entrance below the stairs" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 20,
        title: { ko: "D5 · 2장", en: "D5 · Ch.2" },
        location: { ko: "건물 현관에 열쇠가 떨어져 있다", en: "Key at the building entrance" },
        reward: { ko: "경구", en: "Hardball" },
      },
      {
        number: 21,
        title: { ko: "E1 · 2장", en: "E1 · Ch.2" },
        location: { ko: "「맹렬초 가부키 마츠리」 간판 아래 입구에 열쇠가 떨어져 있다", en: "Key at the entrance under the Kabuki Festival sign" },
        reward: { ko: "스태미난 XX", en: "Staminan XX" },
      },
      {
        number: 22,
        title: { ko: "E2 · 2장", en: "E2 · Ch.2" },
        location: { ko: "「이와하시 다리」 중앙 바닥에 열쇠가 떨어져 있다", en: "Key on the center floor of Iwa Bridge" },
        reward: { ko: "하라헤루 하프", en: "Harahel Half" },
      },
      {
        number: 23,
        title: { ko: "E3 · 2장", en: "E3 · Ch.2" },
        location: { ko: "「소텐보리 측도」 블록 쪽에 열쇠가 떨어져 있다", en: "Key by the block on Sotenbori Path" },
        reward: { ko: "BJ의 부적", en: "BJ Charm" },
      },
      {
        number: 24,
        title: { ko: "E4 · 2장", en: "E4 · Ch.2" },
        location: { ko: "무료 안내소 간판 근처 도로에 열쇠가 떨어져 있다", en: "Key on the road near the info-center sign" },
        reward: { ko: "버스트의 부적", en: "Burst Charm" },
      },
      {
        number: 25,
        title: { ko: "E5 · 2장", en: "E5 · Ch.2" },
        location: { ko: "막다른 도로에 열쇠가 떨어져 있다", en: "Key on the dead-end road" },
        reward: { ko: "도싯핀즈", en: "Doshippins" },
      },
      {
        number: 26,
        title: { ko: "F1 · 2장", en: "F1 · Ch.2" },
        location: { ko: "「이와하시 다리」 아래 통로에 열쇠가 떨어져 있다", en: "Key in the passage under Iwa Bridge" },
        reward: { ko: "떡갈나무 목도", en: "Oak Bokken" },
      },
      {
        number: 27,
        title: { ko: "F2 · 2장", en: "F2 · Ch.2" },
        location: { ko: "올라가는 에스컬레이터 부근 바닥에 열쇠가 떨어져 있다", en: "Key near the up escalator" },
        reward: { ko: "우도", en: "Cleaver" },
      },
      {
        number: 28,
        title: { ko: "F3 · 2장", en: "F3 · Ch.2" },
        location: { ko: "「소텐보리 측도」로 내려가는 계단에 열쇠가 떨어져 있다", en: "Key on the stairs down to Sotenbori Path" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 29,
        title: { ko: "F4 · 2장", en: "F4 · Ch.2" },
        location: { ko: "건물 계단을 올라 4층(옥상) 골포스트에 열쇠가 떨어져 있다", en: "Key at the 4F (roof) goalpost" },
        reward: { ko: "전기포트", en: "Electric Kettle" },
      },
      {
        number: 30,
        title: { ko: "F5 · 2장", en: "F5 · Ch.2" },
        location: { ko: "카지노행 지하 계단을 내려간 곳에 열쇠가 떨어져 있다", en: "Key down the basement stairs toward the casino" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 31,
        title: { ko: "G1 · 2장", en: "G1 · Ch.2" },
        location: { ko: "「소텐보리 측도」 블록 쪽에 열쇠가 떨어져 있다", en: "Key by the block on Sotenbori Path" },
        reward: { ko: "금 접시", en: "Gold Plate" },
      },
      {
        number: 32,
        title: { ko: "G2 · 2장", en: "G2 · Ch.2" },
        location: { ko: "건물 내 남자 화장실에 열쇠가 떨어져 있다", en: "Key in the building men's restroom" },
        reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
      },
      {
        number: 33,
        title: { ko: "G3 · 2장", en: "G3 · Ch.2" },
        location: { ko: "벤치 아래에 열쇠가 떨어져 있다", en: "Key under the bench" },
        reward: { ko: "스태미난 로열", en: "Staminan Royal" },
      },
      {
        number: 34,
        title: { ko: "G4 · 2장", en: "G4 · Ch.2" },
        location: { ko: "비사몬교 선착장 아래에 열쇠가 떨어져 있다", en: "Key under the Bishamon Bridge dock" },
        reward: { ko: "터프니스 Z", en: "Toughness Z" },
      },
      {
        number: 35,
        title: { ko: "G5 · 2장", en: "G5 · Ch.2" },
        location: { ko: "계단 아래 블록 쪽에 열쇠가 떨어져 있다", en: "Key by the block below the stairs" },
        reward: { ko: "특수 경봉", en: "Special Baton" },
      },
      {
        number: 36,
        title: { ko: "H1 · 2장", en: "H1 · Ch.2" },
        location: { ko: "관엽식물 뒤편 바닥에 열쇠가 떨어져 있다", en: "Key on the floor behind the houseplant" },
        reward: { ko: "스태미난 Z", en: "Staminan Z" },
      },
      {
        number: 37,
        title: { ko: "H2 · 2장", en: "H2 · Ch.2" },
        location: { ko: "건물 안쪽으로 이어지는 통로에 열쇠가 떨어져 있다", en: "Key in the passage leading deeper into the building" },
        reward: { ko: "피녹 사슬갑주", en: "Bloodrust Chainmail" },
      },
      {
        number: 38,
        title: { ko: "H3 · 2장", en: "H3 · Ch.2" },
        location: { ko: "계단 아래 화단 근처에 열쇠가 떨어져 있다", en: "Key near the planter below the stairs" },
        reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
      },
      {
        number: 39,
        title: { ko: "H4 · 2장", en: "H4 · Ch.2" },
        location: { ko: "타코야키 가게 부근 바닥에 열쇠가 떨어져 있다", en: "Key near the takoyaki stand" },
        reward: { ko: "개조 버너", en: "Modified Burner" },
      },
      {
        number: 40,
        title: { ko: "H5 · 2장", en: "H5 · Ch.2" },
        location: { ko: "진입 금지 간판 근처 바닥에 열쇠가 떨어져 있다", en: "Key near the no-entry sign" },
        reward: { ko: "터프니스 ZZ", en: "Toughness ZZ" },
      },
      {
        number: 41,
        title: { ko: "I1 · 2장", en: "I1 · Ch.2" },
        location: { ko: "건물 내 계단 층계참에 열쇠가 떨어져 있다", en: "Key on the building stair landing" },
        reward: { ko: "스태미난 X", en: "Staminan X" },
      },
      {
        number: 42,
        title: { ko: "I2 · 2장", en: "I2 · Ch.2" },
        location: { ko: "카지노 앞 복도 골판지 부근에 열쇠가 떨어져 있다", en: "Key by the cardboard in the casino hallway" },
        reward: { ko: "청룡도", en: "Blue-Dragon Blade" },
      },
      {
        number: 43,
        title: { ko: "I3 · 2장", en: "I3 · Ch.2" },
        location: { ko: "「간코 스시」 가게 앞 바닥에 열쇠가 떨어져 있다", en: "Key in front of Ganko Sushi" },
        reward: { ko: "터프니스 라이트", en: "Toughness Light" },
      },
      {
        number: 44,
        title: { ko: "I4 · 2장", en: "I4 · Ch.2" },
        location: { ko: "「소텐보리 측도」 셔터 부근 바닥에 열쇠가 떨어져 있다", en: "Key by the shutter on Sotenbori Path" },
        reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" },
      },
      {
        number: 45,
        title: { ko: "I5 · 2장", en: "I5 · Ch.2" },
        location: { ko: "도박장행 복도에 열쇠가 떨어져 있다", en: "Key in the hall toward the gambling den" },
        reward: { ko: "행운 화투", en: "Lucky Hanafuda" },
      },
      {
        number: 46,
        title: { ko: "J1 · 2장", en: "J1 · Ch.2" },
        location: { ko: "계단 아래 거리에 열쇠가 떨어져 있다", en: "Key on the street below the stairs" },
        reward: { ko: "개조 화로", en: "Modified Stove" },
      },
      {
        number: 47,
        title: { ko: "J2 · 2장", en: "J2 · Ch.2" },
        location: { ko: "자판기 앞 테이블 아래에 열쇠가 떨어져 있다", en: "Key under the table in front of the vending machine" },
        reward: { ko: "군용 방탄조끼", en: "Military Bulletproof Vest" },
      },
      {
        number: 48,
        title: { ko: "J3 · 2장", en: "J3 · Ch.2" },
        location: { ko: "차 주차장에 열쇠가 떨어져 있다", en: "Key at the car park" },
        reward: { ko: "근성의 서", en: "Tome of Guts" },
      },
      {
        number: 49,
        title: { ko: "J4 · 10장", en: "J4 · Ch.10" },
        location: { ko: "서브스토리 No.47 「원한 대행」 클리어 보상으로 받는다", en: "Reward from clearing substory No.47" },
        reward: { ko: "플래티넘 접시", en: "Platinum Plate" },
      },
      {
        number: 50,
        title: { ko: "J5 · 2장", en: "J5 · Ch.2" },
        location: { ko: "건물 계단 근처에 열쇠가 떨어져 있다", en: "Key near the building stairs" },
        reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" },
      },
        ],
      },
      ],
    },
    {
      slug: "encounter-bosses",
      title: { ko: "인카운트 보스 — 카무로초 & 소텐보리 18인", en: "Encounter Bosses — All 18 Street Bosses (Both Cities)" },
      summary: {
        ko: "제5장 사야마에게 물품 전달 후 해금되는 인카운트 보스. 각 도시마다 야쿠자·양아치·불량배 계열로 3명씩 이어지는 보스 체인이 3개(총 9명)씩 존재합니다. 전원 격파 시 오의 「트리플 스웨이」를 습득할 수 있습니다.",
        en: "Street-encounter bosses, unlocked after delivering the item to Sayama in Chapter 5. Each city has three 3-boss chains (Yakuza / Delinquent / Thug lineage, 9 bosses total). Beating all of them unlocks the Triple Sway heat move.",
      },
      tips: [
        { ko: "각 계열 첫 보스는 해당 잡몹(야쿠자/양아치/불량배)을 5회 격파하면 메일로 인카운트 위치 안내를 받습니다.", en: "Beat the linked mob type (Yakuza/Delinquent/Thug) 5 times to get an email pointing to the first boss in each chain." },
        { ko: "체인의 다음 보스는 이전 보스 격파 후 같은 잡몹을 5회 더 격파해야 등장합니다.", en: "The next boss in a chain appears after beating the previous boss plus 5 more fights against the same mob type." },
      ],
      source: { label: "funkygame — 용과 같이 극 2 인카운트 보스", url: "https://funkygame.tistory.com/2026" },
      groups: [
        {
          title: { ko: "카무로초 — 9인", en: "Kamurocho — 9 Bosses" },
          items: [
            {
              number: 1,
              title: { ko: "매드 나카기리", en: "Mad Nakagiri" },
              location: { ko: "야쿠자 5회 격파 후 메일 수신", en: "Beat Yakuza mobs 5 times, then check email" },
              reward: { ko: "중식칼", en: "Chinese Cleaver" },
            },
            {
              number: 2,
              title: { ko: "파이어 카라사와", en: "Fire Karasawa" },
              location: { ko: "매드 나카기리 격파 + 야쿠자 5회 격파", en: "Beat Mad Nakagiri + 5 more Yakuza fights" },
              reward: { ko: "개조 모델건", en: "Modified Model Gun" },
            },
            {
              number: 3,
              title: { ko: "갓 겐조", en: "God Genzo" },
              location: { ko: "파이어 카라사와 격파 + 야쿠자 5회 격파", en: "Beat Fire Karasawa + 5 more Yakuza fights" },
              reward: { ko: "쇠망치, 마지마 건설 스카우트", en: "Sledgehammer, Majima Construction scout" },
            },
            {
              number: 4,
              title: { ko: "복서 후지키", en: "Boxer Fujiki" },
              location: { ko: "양아치 5회 격파 후 메일 수신", en: "Beat Delinquent mobs 5 times, then check email" },
              reward: { ko: "너클 더스터, 마지마 건설 스카우트", en: "Knuckle Duster, Majima Construction scout" },
            },
            {
              number: 5,
              title: { ko: "머슬 후지키", en: "Muscle Fujiki" },
              location: { ko: "복서 후지키 격파 + 양아치 5회 격파", en: "Beat Boxer Fujiki + 5 more Delinquent fights" },
              reward: { ko: "스턴 그레네이드, 마지마 건설 스카우트", en: "Stun Grenade, Majima Construction scout" },
            },
            {
              number: 6,
              title: { ko: "앰부쉬 쿠로사와", en: "Ambush Kurosawa" },
              location: { ko: "머슬 후지키 격파 + 양아치 5회 격파", en: "Beat Muscle Fujiki + 5 more Delinquent fights" },
              reward: { ko: "조장의 배트", en: "Foreman's Bat" },
            },
            {
              number: 7,
              title: { ko: "데들리 후쿠시마", en: "Deadly Fukushima" },
              location: { ko: "불량배 5회 격파 후 메일 수신", en: "Beat Thug mobs 5 times, then check email" },
              reward: { ko: "톱, 마지마 건설 스카우트", en: "Saw, Majima Construction scout" },
            },
            {
              number: 8,
              title: { ko: "편의점 사냥꾼 사이토", en: "Convenience Store Hunter Saito" },
              location: { ko: "데들리 후쿠시마 격파 + 불량배 5회 격파", en: "Beat Deadly Fukushima + 5 more Thug fights" },
              reward: { ko: "고압 전기충격기", en: "High-Voltage Stun Gun" },
            },
            {
              number: 9,
              title: { ko: "사무라이 가면", en: "Samurai Mask" },
              location: { ko: "편의점 사냥꾼 사이토 격파 + 불량배 5회 격파", en: "Beat Convenience Store Hunter Saito + 5 more Thug fights" },
              reward: { ko: "신수의 목도", en: "Divine Beast Bokken" },
            },
          ],
        },
        {
          title: { ko: "소텐보리 — 9인", en: "Sotenbori — 9 Bosses" },
          items: [
            {
              number: 1,
              title: { ko: "수수께끼의 암살자", en: "Mysterious Assassin" },
              location: { ko: "야쿠자 5회 격파 후 메일 수신", en: "Beat Yakuza mobs 5 times, then check email" },
              reward: { ko: "흑자수의 목도", en: "Black Embroidered Bokken" },
            },
            {
              number: 2,
              title: { ko: "피바람 츠치모토", en: "Blood-Rain Tsuchimoto" },
              location: { ko: "수수께끼의 암살자 격파 + 야쿠자 5회 격파", en: "Beat Mysterious Assassin + 5 more Yakuza fights" },
              reward: { ko: "섬광탄, 마지마 건설 스카우트", en: "Flashbang, Majima Construction scout" },
            },
            {
              number: 3,
              title: { ko: "금색의 가네모토", en: "Golden Kanemoto" },
              location: { ko: "피바람 츠치모토 격파 + 야쿠자 5회 격파", en: "Beat Blood-Rain Tsuchimoto + 5 more Yakuza fights" },
              reward: { ko: "닌자 단도", en: "Ninja Dagger" },
            },
            {
              number: 4,
              title: { ko: "위타천 나가부치", en: "Fleet-Footed Nagabuchi" },
              location: { ko: "양아치 5회 격파 후 메일 수신", en: "Beat Delinquent mobs 5 times, then check email" },
              reward: { ko: "긴 단도, 마지마 건설 스카우트", en: "Long Dagger, Majima Construction scout" },
            },
            {
              number: 5,
              title: { ko: "무기 사냥꾼 샤코", en: "Weapon Hunter Shako" },
              location: { ko: "위타천 나가부치 격파 + 양아치 5회 격파", en: "Beat Fleet-Footed Nagabuchi + 5 more Delinquent fights" },
              reward: { ko: "이름 없는 검", en: "Nameless Sword" },
            },
            {
              number: 6,
              title: { ko: "다리 파수꾼 우쿄", en: "Bridge Guardian Ukyo" },
              location: { ko: "무기 사냥꾼 샤코 격파 + 양아치 5회 격파", en: "Beat Weapon Hunter Shako + 5 more Delinquent fights" },
              reward: { ko: "쌍룡의 북채, 마지마 건설 스카우트", en: "Twin Dragon Drumsticks, Majima Construction scout" },
            },
            {
              number: 7,
              title: { ko: "강격의 나가사와", en: "Heavy-Strike Nagasawa" },
              location: { ko: "불량배 5회 격파 후 메일 수신", en: "Beat Thug mobs 5 times, then check email" },
              reward: { ko: "지렛대, 마지마 건설 스카우트", en: "Crowbar, Majima Construction scout" },
            },
            {
              number: 8,
              title: { ko: "파괴자 미네기시", en: "Destroyer Minegishi" },
              location: { ko: "강격의 나가사와 격파 + 불량배 5회 격파", en: "Beat Heavy-Strike Nagasawa + 5 more Thug fights" },
              reward: { ko: "더블 스타이커", en: "Double Stryker" },
            },
            {
              number: 9,
              title: { ko: "철권 사카이", en: "Iron Fist Sakai" },
              location: { ko: "파괴자 미네기시 격파 + 불량배 5회 격파", en: "Beat Destroyer Minegishi + 5 more Thug fights" },
              reward: { ko: "특제 특수 경찰봉", en: "Custom Special Baton" },
            },
          ],
        },
      ],
    },
    {
      slug: "videos",
      title: { ko: "비디오 마니아 — 본편 비디오 전부 시청", en: "Video Maniac — Watch Every Video" },
      summary: {
        ko: "비디오 가게에서 본편의 모든 비디오를 한 번씩 시청하면 「비디오 마니아」 업적 발동.",
        en: "Watch every video at the video store to unlock 'Video Maniac'.",
      },
    }
  ],
};
