import type { CollectiblesData } from "./types";

export const yakuza0: CollectiblesData = {
  appId: 2988580,
  categories: [
    {
      slug: "mr-shakedown",
      title: { ko: "삥쟁이 격파", en: "Mr. Shakedown Encounters" },
      summary: {
        ko: "양 도시에서 등장하는 삥쟁이(미스터 셰이크다운)들을 격파하면 거액의 일시금이 들어옵니다. 부동산·카바레 시드 머니로 가장 효율적인 자금원입니다.",
        en: "Defeat the roaming Mr. Shakedowns in both cities for big lump-sum payouts — the most efficient seed money for the Real Estate and Cabaret mini-games.",
      },
    },
  {
    slug: "telephone-cards",
    title: { ko: "텔레폰 카드 90종 — 30명 × A·B·C", en: "Telephone Cards (90 total — 30 actresses × A/B/C)" },
    summary: { ko: "키류 편 카무로초 45장 + 마지마 편 소텐보리 45장. 한 명당 A·B·C 3종을 모두 수집해 컬렉터에게 보여주면 한 세트당 500만 엔을 받습니다. A→B→C 순서로 회수해야 표시되는 점에 주의하세요.", en: "Kiryu (Kamurocho) holds 45 cards, Majima (Sotenbori) holds 45. Each actress has A/B/C — bring all three to the collector for ¥5,000,000 per complete set. Cards must be collected in A→B→C order to appear." },
    tips: [
        { ko: "카드 워처를 장비하면 광나는 카드 위치가 미니맵에 떠 회수가 훨씬 수월합니다. 키류는 핑크 거리 뒤 컬렉터, 마지마는 소텐보리 동쪽 컬렉터에게 제출하세요.", en: "Equip the Card Watcher to mark shining cards on the minimap. Hand sets to Kiryu's collector behind Pink St. (Akimoto) or Majima's collector east of Sotenbori." },
        { ko: "세트 5장 보상 외에도 「절륜의 아키모토」 친구 호감도가 올라가며 추가 보상이 따라옵니다.", en: "Beyond the ¥5M payout, completing sets raises affinity with collector Akimoto for additional rewards." },
    ],
    source: { label: "龍が如く0 最速攻略wiki — テレホンカード", url: "https://spwiki.net/ryuzero/wikis/109.html" },
    groups: [
    {
      title: { ko: "키류 / 카무로초 — 45장 (15명 × A·B·C)", en: "Kiryu / Kamurocho — 45 Cards (15 actresses × A/B/C)" },
      items: [
      {
        number: 1,
        title: { ko: "아리무라 치카 · 타입 A", en: "Chika Arimura · Type A" },
        location: { ko: "포케서 회장", en: "Pocket Circuit Stadium" },
      },
      {
        number: 2,
        title: { ko: "아리무라 치카 · 타입 B", en: "Chika Arimura · Type B" },
        location: { ko: "중도 거리, 후지소바 앞 철주 아래", en: "Nakamichi St., under the steel post in front of Fuji Soba" },
      },
      {
        number: 3,
        title: { ko: "아리무라 치카 · 타입 C", en: "Chika Arimura · Type C" },
        location: { ko: "챔피언 거리 북동쪽, 술집 '라쿠' 맞은편의 옥외기 옆", en: "Champion District NE, beside the AC unit across from Sakedokoro 'Raku'" },
      },
      {
        number: 4,
        title: { ko: "사토 하루키 · 타입 A", en: "Haruki Sato · Type A" },
        location: { ko: "카무로 시청가 동쪽", en: "Kamuro Shopping District east" },
      },
      {
        number: 5,
        title: { ko: "사토 하루키 · 타입 B", en: "Haruki Sato · Type B" },
        location: { ko: "후토, 남서쪽 타이어 보관소", en: "Wharf, SW tire yard" },
      },
      {
        number: 6,
        title: { ko: "사토 하루키 · 타입 C", en: "Haruki Sato · Type C" },
        location: { ko: "타이헤이 거리 서쪽 끝, 단보루 옆", en: "Taihei St. far west, beside the cardboard" },
      },
      {
        number: 7,
        title: { ko: "토모다 아야카 · 타입 A", en: "Ayaka Tomoda · Type A" },
        location: { ko: "핑크 거리 북쪽, 여신관 앞 철주 아래", en: "Pink St. north, under the steel post in front of Megamikan" },
      },
      {
        number: 8,
        title: { ko: "토모다 아야카 · 타입 B", en: "Ayaka Tomoda · Type B" },
        location: { ko: "마하볼 앞, 입구 왼쪽의 단보루", en: "In front of Mach Bowl, cardboard on the left of the entrance" },
      },
      {
        number: 9,
        title: { ko: "토모다 아야카 · 타입 C", en: "Ayaka Tomoda · Type C" },
        location: { ko: "후토, 북동쪽 컨테이너 뒤", en: "Wharf, behind the NE container" },
      },
      {
        number: 10,
        title: { ko: "미나토 리쿠 · 타입 A", en: "Riku Minato · Type A" },
        location: { ko: "천량 거리, 동쪽 세이브 포인트 앞", en: "Senryo St., just before the eastern save point" },
      },
      {
        number: 11,
        title: { ko: "미나토 리쿠 · 타입 B", en: "Riku Minato · Type B" },
        location: { ko: "호텔가, 호텔 아모레 입구", en: "Hotel District, entrance of HOTEL Amore" },
      },
      {
        number: 12,
        title: { ko: "미나토 리쿠 · 타입 C", en: "Riku Minato · Type C" },
        location: { ko: "핑크 거리 뒤편, 남쪽 카드 컬렉터 맞은편의 틈", en: "Pink St. backstreet, gap across from the card collector to the south" },
      },
      {
        number: 13,
        title: { ko: "시라이시 마리나 · 타입 A", en: "Marina Shiraishi · Type A" },
        location: { ko: "시치후쿠 거리, 전화박스 옆", en: "Shichifuku St., beside the phone booth" },
      },
      {
        number: 14,
        title: { ko: "시라이시 마리나 · 타입 B", en: "Marina Shiraishi · Type B" },
        location: { ko: "공원 앞 거리, 사우나 캡슐 묘조 앞", en: "Park Boulevard, in front of Sauna & Capsule Myoujou" },
      },
      {
        number: 15,
        title: { ko: "시라이시 마리나 · 타입 C", en: "Marina Shiraishi · Type C" },
        location: { ko: "호텔가, 북동쪽 요이도레 골목 옆 문", en: "Hotel District, gate next to Yoidore Alley in the NE" },
      },
      {
        number: 16,
        title: { ko: "미나미 리오나 · 타입 A", en: "Riona Minami · Type A" },
        location: { ko: "타이헤이 거리, 전화박스 앞 쓰레기장", en: "Taihei St., garbage area in front of the phone booth" },
      },
      {
        number: 17,
        title: { ko: "미나미 리오나 · 타입 B", en: "Riona Minami · Type B" },
        location: { ko: "로쿠란소, 안쪽 바닥", en: "Rokuran-so, back floor" },
      },
      {
        number: 18,
        title: { ko: "미나미 리오나 · 타입 C", en: "Riona Minami · Type C" },
        location: { ko: "공원 앞 거리, 동쪽 공원 안쪽 나무 밑동", en: "Park Boulevard, at the base of the tree at the back of the eastern park" },
      },
      {
        number: 19,
        title: { ko: "사쿠라이 아유 · 타입 A", en: "Ayu Sakurai · Type A" },
        location: { ko: "배팅 센터 내부, 게임 코너 안쪽 바닥", en: "Inside the Batting Center, floor at the back of the game corner" },
      },
      {
        number: 20,
        title: { ko: "사쿠라이 아유 · 타입 B", en: "Ayu Sakurai · Type B" },
        location: { ko: "시치후쿠 거리 동쪽, 세이브 포인트 뒤 건물 그늘", en: "Shichifuku St. east, building shadow behind the save point" },
      },
      {
        number: 21,
        title: { ko: "사쿠라이 아유 · 타입 C", en: "Ayu Sakurai · Type C" },
        location: { ko: "호텔가, 소바도코로 야마하치 남쪽 자동차 앞", en: "Hotel District, in front of the car south of Sobadokoro Yamahachi" },
      },
      {
        number: 22,
        title: { ko: "키타가와 에리카 · 타입 A", en: "Erika Kitagawa · Type A" },
        location: { ko: "아지트(슷폰 거리의 스기타 빌딩) 내부 입구", en: "Hideout (Sugita Building on Suppon St.), inner entrance" },
      },
      {
        number: 23,
        title: { ko: "키타가와 에리카 · 타입 B", en: "Erika Kitagawa · Type B" },
        location: { ko: "극장 앞 거리, 카무로소바 옆 자판기 앞", en: "Theater Avenue, in front of the vending machine next to Kamuro Soba" },
      },
      {
        number: 24,
        title: { ko: "키타가와 에리카 · 타입 C", en: "Erika Kitagawa · Type C" },
        location: { ko: "중도 거리 뒤편, 요로노타키 뒤 좁은 골목의 단보루 위", en: "Nakamichi St. backstreet, on the cardboard in the narrow alley behind Yoro no Taki" },
      },
      {
        number: 25,
        title: { ko: "카나에 루카 · 타입 A", en: "Ruka Kanae · Type A" },
        location: { ko: "빈센트 가게 안, 메뉴 간판이 있는 카운터 위", en: "Inside Vincent, on the counter with the menu sign" },
      },
      {
        number: 26,
        title: { ko: "카나에 루카 · 타입 B", en: "Ruka Kanae · Type B" },
        location: { ko: "시치후쿠 거리 서쪽, 전화박스 부근", en: "Shichifuku St. west, near the phone booth" },
      },
      {
        number: 27,
        title: { ko: "카나에 루카 · 타입 C", en: "Ruka Kanae · Type C" },
        location: { ko: "천량 거리, 카레숍 타블라의 벽 틈", en: "Senryo St., gap in the wall of Curry Shop Tabla" },
      },
      {
        number: 28,
        title: { ko: "오카자키 에미리 · 타입 A", en: "Emiri Okazaki · Type A" },
        location: { ko: "하이테크랜드 세가 극장 앞점 내부, 쓰레기통 앞", en: "Hi-Tech Land Sega Theater Square branch, in front of the trash can" },
      },
      {
        number: 29,
        title: { ko: "오카자키 에미리 · 타입 B", en: "Emiri Okazaki · Type B" },
        location: { ko: "아시아 거리, 북쪽 입구의 통로", en: "Asia St., passage at the north entrance" },
      },
      {
        number: 30,
        title: { ko: "오카자키 에미리 · 타입 C", en: "Emiri Okazaki · Type C" },
        location: { ko: "아시아 거리, 세이브 포인트 부근의 폴리 양동이", en: "Asia St., poly bucket near the save point" },
      },
      {
        number: 31,
        title: { ko: "아이바 레이카 · 타입 A", en: "Reika Aiba · Type A" },
        location: { ko: "챔피언 거리 남서쪽 좁은 골목", en: "Champion District SW narrow alley" },
      },
      {
        number: 32,
        title: { ko: "아이바 레이카 · 타입 B", en: "Reika Aiba · Type B" },
        location: { ko: "서공원 안, 중앙 통로 중앙의 파란 울타리(친치로린이 있는 통로)", en: "West Park, blue fence in the middle of the central path (the chinchirorin path)" },
      },
      {
        number: 33,
        title: { ko: "아이바 레이카 · 타입 C", en: "Reika Aiba · Type C" },
        location: { ko: "쇼와 거리, 세이브 박스 부근 지하 입구 부근", en: "Showa St., near the save box and the entrance to the underground" },
      },
      {
        number: 34,
        title: { ko: "마이카 · 타입 A", en: "Maika · Type A" },
        location: { ko: "마하볼, 가장 안쪽 여자 화장실 앞", en: "Mach Bowl, in front of the women's restroom in the back" },
      },
      {
        number: 35,
        title: { ko: "마이카 · 타입 B", en: "Maika · Type B" },
        location: { ko: "극장 앞 광장, 세이브 포인트 북쪽 쓰레기", en: "Theater Square, garbage north of the save point" },
      },
      {
        number: 36,
        title: { ko: "마이카 · 타입 C", en: "Maika · Type C" },
        location: { ko: "중도 거리 뒤편 신사, 동쪽 쓰레기 더미", en: "Shrine on Nakamichi St. backstreet, garbage on east side" },
      },
      {
        number: 37,
        title: { ko: "오토하 나나세 · 타입 A", en: "Nanase Otoha · Type A" },
        location: { ko: "핑크 거리 북쪽, 도쿄 요루시로", en: "Pink St. north, Tokyo Yorushiro" },
      },
      {
        number: 38,
        title: { ko: "오토하 나나세 · 타입 B", en: "Nanase Otoha · Type B" },
        location: { ko: "서공원 안, 서쪽 세이브 포인트 부근", en: "West Park, near the western save point" },
      },
      {
        number: 39,
        title: { ko: "오토하 나나세 · 타입 C", en: "Nanase Otoha · Type C" },
        location: { ko: "중도 거리 뒤편, 거의 중앙의 텔레쿠라와 라멘 테라니시 사이 철주 아래", en: "Nakamichi St. backstreet, under the steel post between the telekura and Ramen Teranishi near the middle" },
      },
      {
        number: 40,
        title: { ko: "아베노 미쿠 · 타입 A", en: "Miku Abeno · Type A" },
        location: { ko: "아텐시 가게 안", en: "Inside Atenshi" },
      },
      {
        number: 41,
        title: { ko: "아베노 미쿠 · 타입 B", en: "Miku Abeno · Type B" },
        location: { ko: "극장 앞 광장, 카무로 스칼라좌 키네마 회관 앞", en: "Theater Square, in front of Kamuro Scala-za Kinema Hall" },
      },
      {
        number: 42,
        title: { ko: "아베노 미쿠 · 타입 C", en: "Miku Abeno · Type C" },
        location: { ko: "핑크 거리 뒤편, 세이브 포인트 근처 건물 입구", en: "Pink St. backstreet, building entrance near the save point" },
      },
      {
        number: 43,
        title: { ko: "토오노 미호 · 타입 A", en: "Miho Tono · Type A" },
        location: { ko: "제3공원 벤치", en: "Third Park bench" },
      },
      {
        number: 44,
        title: { ko: "토오노 미호 · 타입 B", en: "Miho Tono · Type B" },
        location: { ko: "천량 거리 북쪽 간다라 남쪽, 테라카미 부동산 골목", en: "Senryo St. north, alley by Teragami Real Estate south of Gandhara" },
      },
      {
        number: 45,
        title: { ko: "토오노 미호 · 타입 C", en: "Miho Tono · Type C" },
        location: { ko: "카무로 시청가 남쪽, 아가헤이 옆 쓰레기 부근", en: "Kamuro Shopping District south, near the garbage beside Agahei" },
      },
      ],
    },
    {
      title: { ko: "마지마 / 소텐보리 — 45장 (15명 × A·B·C)", en: "Majima / Sotenbori — 45 Cards (15 actresses × A/B/C)" },
      items: [
      {
        number: 1,
        title: { ko: "사쿠라 마나 · 타입 A", en: "Mana Sakura · Type A" },
        location: { ko: "소텐보리 거리 서쪽, 세이브 포인트 옆 골목에 들어가 바로 오른쪽", en: "Sotenbori St. west, immediately on the right after entering the alley by the save point" },
      },
      {
        number: 2,
        title: { ko: "사쿠라 마나 · 타입 B", en: "Mana Sakura · Type B" },
        location: { ko: "이와하시 다리, 중앙 동쪽 움푹한 곳", en: "Iwahashi Bridge, recess on the central east side" },
      },
      {
        number: 3,
        title: { ko: "사쿠라 마나 · 타입 C", en: "Mana Sakura · Type C" },
        location: { ko: "쇼후쿠초, 아시타바 공원에서 나와 북쪽 오코노미야키 노보리 아래", en: "Shofukucho, north of Ashitaba Park exit, under the okonomiyaki banner" },
      },
      {
        number: 4,
        title: { ko: "우에하라 아이 · 타입 A", en: "Ai Uehara · Type A" },
        location: { ko: "소텐보리 거리 동쪽, 세이브 포인트 뒤", en: "Sotenbori St. east, behind the save point" },
      },
      {
        number: 5,
        title: { ko: "우에하라 아이 · 타입 B", en: "Ai Uehara · Type B" },
        location: { ko: "쇼후쿠초 남쪽 세이브 포인트에서 쇼후쿠초로 들어가 동쪽 넓은 통로 끝의 자전거 옆", en: "From the Shofukucho south save point into Shofukucho, beside the bicycle at the end of the wide east passage" },
      },
      {
        number: 6,
        title: { ko: "우에하라 아이 · 타입 C", en: "Ai Uehara · Type C" },
        location: { ko: "산즈노카와 강바닥(11장), 링을 정면으로 왼쪽 기둥 그늘", en: "Sanzu River bottom (Ch. 11), behind the left pillar facing the ring" },
      },
      {
        number: 7,
        title: { ko: "오오츠키 히비키 · 타입 A", en: "Hibiki Otsuki · Type A" },
        location: { ko: "쇼후쿠초 서쪽, 중간쯤 건물 뒤편으로 돌아 들어간 남서쪽 모퉁이", en: "Shofukucho west, SW corner around the back of the middle building" },
      },
      {
        number: 8,
        title: { ko: "오오츠키 히비키 · 타입 B", en: "Hibiki Otsuki · Type B" },
        location: { ko: "소텐보리 측도(남측) 중간쯤에서 쇼후쿠초로 빠지는 골목 쓰레기통 사이", en: "Between trash cans in the alley from the middle of Sotenbori Backstreet (south) to Shofukucho" },
      },
      {
        number: 9,
        title: { ko: "오오츠키 히비키 · 타입 C", en: "Hibiki Otsuki · Type C" },
        location: { ko: "쇼후쿠초 남쪽, 간다라 맞은편 화분 아래", en: "Shofukucho south, under the planter across from Gandhara" },
      },
      {
        number: 10,
        title: { ko: "하츠미 사키 · 타입 A", en: "Saki Hatsumi · Type A" },
        location: { ko: "카지노 가게 안, 들어가서 바로 왼편 화병 아래", en: "Inside the casino, under the vase on the immediate left" },
      },
      {
        number: 11,
        title: { ko: "하츠미 사키 · 타입 B", en: "Saki Hatsumi · Type B" },
        location: { ko: "쇼후쿠초 남쪽, 중간쯤 전봇대 밑동", en: "Shofukucho south, base of the utility pole in the middle" },
      },
      {
        number: 12,
        title: { ko: "하츠미 사키 · 타입 C", en: "Saki Hatsumi · Type C" },
        location: { ko: "비샤몬 다리 남쪽 노보리 깃발 아래", en: "Bishamon Bridge, under the banner on the south side" },
      },
      {
        number: 13,
        title: { ko: "아사쿠라 코토미 · 타입 A", en: "Kotomi Asakura · Type A" },
        location: { ko: "소텐보리 거리 동쪽, 세가 앞 쓰레기통 쪽 벤치 아래", en: "Sotenbori St. east, under the bench by the trash can in front of Sega" },
      },
      {
        number: 14,
        title: { ko: "아사쿠라 코토미 · 타입 B", en: "Kotomi Asakura · Type B" },
        location: { ko: "쇼후쿠초 서쪽, 중간쯤 뒤편으로 돌아 들어갈 수 있는 건물 정면 왼쪽", en: "Shofukucho west, front-left of the middle building you can walk around behind" },
      },
      {
        number: 15,
        title: { ko: "아사쿠라 코토미 · 타입 C", en: "Kotomi Asakura · Type C" },
        location: { ko: "마구타코 포장마차 구석", en: "Corner of the Magutako stall" },
      },
      {
        number: 16,
        title: { ko: "아이스 코코아 · 타입 A", en: "Kokoa Aisu · Type A" },
        location: { ko: "쇼후쿠초 서쪽, 세이브 포인트 맞은편 건물의 비상계단 아래", en: "Shofukucho west, under the emergency stairs of the building across from the save point" },
      },
      {
        number: 17,
        title: { ko: "아이스 코코아 · 타입 B", en: "Kokoa Aisu · Type B" },
        location: { ko: "호겐지 골목, 절 맞은편 후지이데라 간판 그늘", en: "Hogenji Alley, behind the Fujiidera sign across from the temple" },
      },
      {
        number: 18,
        title: { ko: "아이스 코코아 · 타입 C", en: "Kokoa Aisu · Type C" },
        location: { ko: "분자에몬 거리, 세이브 포인트 옆 우편함 옆", en: "Bunzaemon St., beside the postbox next to the save point" },
      },
      {
        number: 19,
        title: { ko: "하즈키 노조미 · 타입 A", en: "Nozomi Hazuki · Type A" },
        location: { ko: "마지마의 아파트 마당, 빨랫대 아래", en: "Majima's apartment yard, under the laundry pole" },
      },
      {
        number: 20,
        title: { ko: "하즈키 노조미 · 타입 B", en: "Nozomi Hazuki · Type B" },
        location: { ko: "아시타바 공원, 세이브 포인트 옆 맥주 케이스", en: "Ashitaba Park, beer case next to the save point" },
      },
      {
        number: 21,
        title: { ko: "하즈키 노조미 · 타입 C", en: "Nozomi Hazuki · Type C" },
        location: { ko: "소텐보리 거리 서쪽, 택시 승강장 전봇대", en: "Sotenbori St. west, utility pole at the taxi stand" },
      },
      {
        number: 22,
        title: { ko: "마키 쿄코 · 타입 A", en: "Kyoko Maki · Type A" },
        location: { ko: "가라오케 스낵 우타히메 안, 안쪽 화분의 그늘", en: "Karaoke Snack Utahime, behind the plant in the back" },
      },
      {
        number: 23,
        title: { ko: "마키 쿄코 · 타입 B", en: "Kyoko Maki · Type B" },
        location: { ko: "자쿠바라야, 입구 왼쪽 쓰레기장", en: "Jakubaraya, garbage dump on the left of the entrance" },
      },
      {
        number: 24,
        title: { ko: "마키 쿄코 · 타입 C", en: "Kyoko Maki · Type C" },
        location: { ko: "아시타바 공원 세이브 포인트에서 분자에몬 거리로 나간 모퉁이의 쓰레기 더미", en: "From the Ashitaba Park save point, garbage pile at the corner where you exit onto Bunzaemon St." },
      },
      {
        number: 25,
        title: { ko: "후루카와 이오리 · 타입 A", en: "Iori Furukawa · Type A" },
        location: { ko: "비샤몬 다리에서 소텐보리 측도 서쪽(북측)으로 내려가는 계단 층계참", en: "Stair landing going down from Bishamon Bridge to Sotenbori Backstreet West (north side)" },
      },
      {
        number: 26,
        title: { ko: "후루카와 이오리 · 타입 B", en: "Iori Furukawa · Type B" },
        location: { ko: "분자에몬 거리 모퉁이, 분자 극장 입구의 기둥", en: "Bunzaemon St. corner, pillar at the entrance of Bunza Theater" },
      },
      {
        number: 27,
        title: { ko: "후루카와 이오리 · 타입 C", en: "Iori Furukawa · Type C" },
        location: { ko: "호겐지 골목 중심부, 초밥집 간판 아래 맥주 케이스", en: "Hogenji Alley center, beer case under the sushi shop sign" },
      },
      {
        number: 28,
        title: { ko: "하네다 아이 · 타입 A", en: "Ai Haneda · Type A" },
        location: { ko: "소텐보리 거리, 세이브 포인트 뒤 가게 입구", en: "Sotenbori St., shop entrance behind the save point" },
      },
      {
        number: 29,
        title: { ko: "하네다 아이 · 타입 B", en: "Ai Haneda · Type B" },
        location: { ko: "소텐보리 측도 동쪽(남측), 푸른 간판 앞 바닥", en: "Sotenbori Backstreet East (south), the ground in front of the blue sign" },
      },
      {
        number: 30,
        title: { ko: "하네다 아이 · 타입 C", en: "Ai Haneda · Type C" },
        location: { ko: "세가 소텐보리점, 가게 안 들어가 오른편 재떨이", en: "Sega Sotenbori, ashtray on the right after entering" },
      },
      {
        number: 31,
        title: { ko: "미즈키 나오 · 타입 A", en: "Nao Mizuki · Type A" },
        location: { ko: "아시타바 공원 안, 북쪽 벤치 아래", en: "Inside Ashitaba Park, under the north bench" },
      },
      {
        number: 32,
        title: { ko: "미즈키 나오 · 타입 B", en: "Nao Mizuki · Type B" },
        location: { ko: "소텐보리 측도(북측)에서 소텐보리 거리로 빠지는 골목의 쓰레기 더미", en: "Garbage pile in the alley from Sotenbori Backstreet (north) to Sotenbori St." },
      },
      {
        number: 33,
        title: { ko: "미즈키 나오 · 타입 C", en: "Nao Mizuki · Type C" },
        location: { ko: "쇼후쿠초 서쪽, 세이브 포인트 북쪽 계단이 있는 건물 1층 안쪽", en: "Shofukucho west, back of the 1F of the building with stairs north of the save point" },
      },
      {
        number: 34,
        title: { ko: "나츠메 유키 · 타입 A", en: "Yuki Natsume · Type A" },
        location: { ko: "쇼후쿠초, 세이브 포인트 옆 쓰레기장", en: "Shofukucho, garbage dump beside the save point" },
      },
      {
        number: 35,
        title: { ko: "나츠메 유키 · 타입 B", en: "Yuki Natsume · Type B" },
        location: { ko: "소텐보리 측도 동쪽(북측), 돌출된 계단", en: "Sotenbori Backstreet East (north), the protruding stairs" },
      },
      {
        number: 36,
        title: { ko: "나츠메 유키 · 타입 C", en: "Yuki Natsume · Type C" },
        location: { ko: "비샤몬 다리를 건너 소텐보리 거리 서쪽 왼편 공중화장실 안", en: "Inside the public restroom on the left after crossing Bishamon Bridge to Sotenbori St. west" },
      },
      {
        number: 37,
        title: { ko: "이토 리나 · 타입 A", en: "Rina Ito · Type A" },
        location: { ko: "바 스테일 안, 당구대 아래", en: "Inside BAR Stijl, under the billiard table" },
      },
      {
        number: 38,
        title: { ko: "이토 리나 · 타입 B", en: "Rina Ito · Type B" },
        location: { ko: "카지노 가게 안, 오른쪽 안쪽 화장실로 보이는 문 앞", en: "Inside the casino, in front of the door that looks like a restroom in the back right" },
      },
      {
        number: 39,
        title: { ko: "이토 리나 · 타입 C", en: "Rina Ito · Type C" },
        location: { ko: "쇼후쿠초 서쪽, M 스토어 쇼후쿠초점 옆 단보루 더미 그늘", en: "Shofukucho west, behind the cardboard pile next to M Store Shofukucho branch" },
      },
      {
        number: 40,
        title: { ko: "하세가와 시즈쿠 · 타입 A", en: "Shizuku Hasegawa · Type A" },
        location: { ko: "자쿠바라야, 가게 안쪽 NPC 탁자 벽 옆", en: "Jakubaraya, by the wall at the NPC table in the back" },
      },
      {
        number: 41,
        title: { ko: "하세가와 시즈쿠 · 타입 B", en: "Shizuku Hasegawa · Type B" },
        location: { ko: "분자에몬 거리 모퉁이, 큰 건물(SFT 빌리지) 입구 왼쪽 화분 아래", en: "Bunzaemon St. corner, under the planter to the left of the big building's entrance (SFT VILLAGE)" },
      },
      {
        number: 42,
        title: { ko: "하세가와 시즈쿠 · 타입 C", en: "Shizuku Hasegawa · Type C" },
        location: { ko: "소텐보리 측도(남측), 통로 서쪽의 맨홀", en: "Sotenbori Backstreet (south), manhole on the west side of the path" },
      },
      {
        number: 43,
        title: { ko: "쿠리바야시 리리 · 타입 A", en: "Riri Kuribayashi · Type A" },
        location: { ko: "쇼후쿠초와 쇼후쿠초 동쪽의 경계, 빨간 차 앞", en: "Border of Shofukucho and Shofukucho East, in front of the red car" },
      },
      {
        number: 44,
        title: { ko: "쿠리바야시 리리 · 타입 B", en: "Riri Kuribayashi · Type B" },
        location: { ko: "쇼후쿠초 남쪽 세이브 포인트에서 쇼후쿠초로 들어가자마자 동쪽 통로 도중", en: "From the Shofukucho south save point into Shofukucho, midway down the east passage" },
      },
      {
        number: 45,
        title: { ko: "쿠리바야시 리리 · 타입 C", en: "Riri Kuribayashi · Type C" },
        location: { ko: "호겐지 골목, 쇼후쿠초 서쪽에서 들어가자마자의 맥주 통", en: "Hogenji Alley, beer barrel right after entering from Shofukucho west" },
      },
      ],
    },
    ],
  },
  {
    slug: "real-estate-royale",
    title: { ko: "카무로초 머니 아일랜드 — 5구역 + 5억만장자 격파", en: "Kamurocho Money Island — 5 Districts + 5 Billionaires" },
    summary: { ko: "키류 편 부동산 모드. 카무로초 5구역(레저 킹·일렉트로닉스 킹·플레저 킹·갬블링 킹·미디어 킹) 부동산을 인수해 각 구역 매출 점유율 90% 이상을 달성하고 5억만장자를 차례로 격파하면 됩니다. 3장 이후 본격 진행 가능합니다.", en: "Kiryu's Real Estate Royale. Acquire properties across the five Kamurocho districts (Leisure King, Electronics King, Pleasure King, Gambling King, Media King), hit 90%+ market share per district, and defeat all five Billionaire bosses. Free play from Chapter 3." },
    tips: [
        { ko: "구역별 시장 점유율은 부동산을 한 곳씩 인수할 때마다 점진적으로 오릅니다. 시드 머니가 부족하면 삥쟁이를 격파해 거액을 확보하세요.", en: "Market share rises gradually as you buy properties. If short on seed money, defeat Mr. Shakedowns for lump-sum payouts." },
        { ko: "친구 단계 NPC 호감도를 끌어올리면 '매핑된' 점포가 추가 해금됩니다. 각 구역에 1~2곳씩 친구 전제 매물이 존재합니다.", en: "Raising Friendship affinity with key NPCs unlocks 'mapped' properties — 1-2 per district." },
        { ko: "최종 라이벌 파이낸스 킹은 5구역을 모두 장악하고 4억만장자를 격파한 뒤 메인 스토리 14장 이후에 도전 가능합니다.", en: "Final rival Finance King unlocks only after dominating all five districts + defeating the first 4 Billionaires, gated by Chapter 14 main story." },
    ],
    source: { label: "龍が如く0 最速攻略wiki — 不動産", url: "https://spwiki.net/ryuzero/" },
    groups: [
    {
      title: { ko: "5구역 — 부동산 점유율 + 라이벌 보스", en: "5 Districts — Market Share + Boss" },
      items: [
      {
        number: 1,
        title: { ko: "레저 킹 구역", en: "Leisure King District" },
        location: { ko: "카무로초 — 시치후쿠 거리 일대 (북부)", en: "Kamurocho — Shichifuku St. area (north)" },
        body: { ko: "10곳 부동산을 인수해 점유율 90% 도달 후 레저 킹과 결전. 기본 부동산 외 친구 미호와 셰프의 호감도 조건으로 풀리는 매핑 매물 2곳 포함.", en: "Buy 10 properties to 90% share, then fight Leisure King. Includes 2 'mapped' properties gated on Friendship with Miho and Chef." },
        reward: { ko: "레저 킹 격파 보상: 시드 머니 + 다음 구역 해금", en: "Reward: seed money + next district unlock" },
      },
      {
        number: 2,
        title: { ko: "일렉트로닉스 킹 구역", en: "Electronics King District" },
        location: { ko: "카무로초 — 천량 거리·후지소바 일대 (중부)", en: "Kamurocho — Senryo St. / Fuji Soba area (center)" },
        body: { ko: "친구 루카의 우정 조건 + 일반 매물 9곳. 시장 점유율 90% 후 일렉트로닉스 킹과 결전. JCC 디스코 미니게임이 미션 흐름에 포함.", en: "Friend Luka condition + 9 standard properties. Hit 90% share then face Electronics King — JCC Disco minigame is woven into the arc." },
      },
      {
        number: 3,
        title: { ko: "플레저 킹 구역", en: "Pleasure King District" },
        location: { ko: "카무로초 — 핑크 거리·텔레폰 클럽 일대", en: "Kamurocho — Pink St. / Telephone Club area" },
        body: { ko: "텔레폰 클럽 콘텐츠 + 친구 9명 호감도와 연동. 점유율 90% 후 플레저 킹은 매장(아야카) 데이트 이벤트 클리어를 조건으로 합니다.", en: "Tied to Telephone Club + 9 friend affinities. Pleasure King fight gated by Ayaka date event after 90% share." },
      },
      {
        number: 4,
        title: { ko: "갬블링 킹 구역", en: "Gambling King District" },
        location: { ko: "카무로초 — 극장 광장·테아토르 일대 (남부)", en: "Kamurocho — Theater Square / Theater area (south)" },
        body: { ko: "친구 에미리(마하볼)와의 우정으로 매핑 매물 해금. 갬블링 킹은 JCC 일본 캣파이트 클럽 서브스토리 클리어 후 등장.", en: "Emiri (Mach Bowl) friendship unlocks mapped property. Gambling King appears after the JCC Japan Catfight Club side story clears." },
      },
      {
        number: 5,
        title: { ko: "미디어 킹 구역", en: "Media King District" },
        location: { ko: "카무로초 — 호텔가·밀레니엄 타워 일대 (동부)", en: "Kamurocho — Hotel District / Millennium Tower area (east)" },
        body: { ko: "친구 파이터(포켓 서킷)의 우정 + 일반 매물 9곳. 디스코 시티 보이 인수 시 「The Glamorous Life」 업적이 트리거됩니다.", en: "Fighter (Pocket Circuit) friendship + 9 properties. Buying Disco City Boy triggers the 'The Glamorous Life' achievement." },
      },
      {
        number: 6,
        title: { ko: "파이낸스 킹 (최종)", en: "Finance King (Final)" },
        location: { ko: "서브스토리 「We Built This City」 — 최종 라이벌", en: "Side story 'We Built This City' — final rival" },
        body: { ko: "5구역 점유율 풀 + 4억만장자 격파 + 14장 도달 후 결전. 격파 시 도지마의 용 스타일 해금 + 부동산 로열 컴플리트.", en: "After 5 districts dominated + 4 Billionaires beaten + Chapter 14, the final fight unlocks. Win to unlock Dragon of Dojima style + complete Real Estate Royale." },
        reward: { ko: "도지마의 용 스타일 해금 + 「We Built This City」 업적", en: "Dragon of Dojima style unlock + 'We Built This City' achievement" },
      },
      ],
    },
    {
      title: { ko: "레저 킹 매물 — 카무로초 남서부 (시치후쿠 거리)", en: "Leisure King Properties — Kamurocho Southwest (Shichifuku St.)" },
      mapImage: "https://lh3.googleusercontent.com/VNssO3bppCsYtXQsK4EJqlRXveUTtk2_3_Cf2JW99QAzENWtoS-sA9F7wWTTYdxzEow6lniBUjs3oNhWPEHiYJ_ibI9EGFDmNKjk2tadfwPO",
      items: [
        {
          number: 1,
          title: { ko: "유리자케 (시작 점포)", en: "Yurizake (Starting Property)" },
          location: { ko: "포포 마트 서쪽", en: "West of Poppo Mart" },
          body: { ko: "키류가 처음부터 소유하고 있는 점포. 별도 구입 불필요.", en: "Owned from the start — no purchase needed." },
        },
        {
          number: 2,
          title: { ko: "뇨키뇨키 학원", en: "Nyoki-Nyoki Academy" },
          location: { ko: "긴다코 남쪽", en: "South of Gindaco" },
          body: { ko: "인수 가격 ¥10,800,000 / 최대 수익 ¥1,620,000. 레저 킹 구역에서 가장 싼 매물 중 하나.", en: "Price ¥10,800,000 / Max revenue ¥1,620,000. One of the cheapest in Leisure King." },
        },
        {
          number: 3,
          title: { ko: "신키츠 헬스 플라자", en: "Kamuro Health Plaza" },
          location: { ko: "세레나 건너편", en: "Across from Serena" },
          body: { ko: "인수 가격 ¥12,400,000 / 최대 수익 ¥5,580,000.", en: "Price ¥12,400,000 / Max revenue ¥5,580,000." },
        },
        {
          number: 4,
          title: { ko: "하라시마 디자인", en: "Harashima Design" },
          location: { ko: "공원 3 동쪽", en: "East of Public Park 3" },
          body: { ko: "인수 가격 ¥13,200,000 / 최대 수익 ¥5,940,000.", en: "Price ¥13,200,000 / Max revenue ¥5,940,000." },
        },
        {
          number: 5,
          title: { ko: "스키야키 무라나카", en: "Sukiyaki Muranaka" },
          location: { ko: "세레나 북쪽", en: "North of Serena" },
          body: { ko: "인수 가격 ¥14,000,000 / 최대 수익 ¥6,300,000.", en: "Price ¥14,000,000 / Max revenue ¥6,300,000." },
        },
        {
          number: 6,
          title: { ko: "헬스 와일드 애플", en: "Health Wild Apple" },
          location: { ko: "스기타 빌딩 북쪽", en: "North of Sugita Building" },
          body: { ko: "인수 가격 ¥16,400,000 / 최대 수익 ¥7,380,000.", en: "Price ¥16,400,000 / Max revenue ¥7,380,000." },
        },
        {
          number: 7,
          title: { ko: "파칭코 뉴 에덴", en: "Pachinko New Eden" },
          location: { ko: "세레나 남쪽", en: "South of Serena" },
          body: { ko: "인수 가격 ¥18,400,000 / 최대 수익 ¥13,800,000. 레저 킹 구역 최고 수익 매물.", en: "Price ¥18,400,000 / Max revenue ¥13,800,000. Top earner in Leisure King." },
        },
        {
          number: 8,
          title: { ko: "파칭코 마루후쿠", en: "Pachinko Marufuku" },
          location: { ko: "포포 동쪽", en: "East of Poppo" },
          body: { ko: "인수 가격 ¥18,400,000 / 최대 수익 ¥13,800,000. 뉴 에덴과 더불어 구역 최고 수익급.", en: "Price ¥18,400,000 / Max revenue ¥13,800,000. Tied with New Eden for top earner." },
        },
        {
          number: 9,
          title: { ko: "포포 텐카이치 거리점 (친구 매핑)", en: "Poppo Tenkaichi St. (Friendship Mapped)" },
          location: { ko: "세레나 북쪽 — 텐카이치 거리", en: "North of Serena — Tenkaichi St." },
          body: { ko: "구매 불가 — 친구 NPC의 호감도를 풀까지 올리면 무상 양도.", en: "Not purchasable — gifted free when the friend NPC's affinity is maxed." },
          prereq: { ko: "포포 텐카이치 거리점 주인과의 친구 호감도 MAX", en: "Friendship MAX with the Poppo Tenkaichi St. owner" },
        },
        {
          number: 10,
          title: { ko: "스시 긴 (친구 매핑)", en: "Sushi Gin (Friendship Mapped)" },
          location: { ko: "남동부 — 텐카이치 거리 남쪽", en: "Southeast region — south of Tenkaichi St." },
          body: { ko: "구매 불가 — 스시 긴 셰프와의 친구 호감도를 풀까지 올리면 무상 양도. 최대 수익 ¥5,760,000.", en: "Not purchasable — gifted free when Sushi Gin chef's friendship is maxed. Max revenue ¥5,760,000." },
          prereq: { ko: "스시 긴 셰프와의 친구 호감도 MAX", en: "Friendship MAX with Sushi Gin chef" },
        },
      ],
    },
    {
      title: { ko: "일렉트로닉스 킹 매물 — 카무로초 남중부 (천량 거리·후지소바)", en: "Electronics King Properties — Kamurocho South-Center (Senryo St. / Fuji Soba)" },
      mapImage: "https://lh3.googleusercontent.com/9_J5UmgtGg49qdtVdE0hQ6SHsfYRG-yjm3S82Zy7vxLmM5skfpvYBGIVoRmOXjVyTwG1WDkGDi-6wFAfImNa68qmUpiBF9QlQG7w_eTMP-xD",
      items: [
        {
          number: 1,
          title: { ko: "도레미파 존 (시작 점포)", en: "DoReMiFa Zone (Starting Property)" },
          location: { ko: "HL 세가 남쪽", en: "South of HL SEGA" },
          body: { ko: "일렉트로닉스 킹 구역 진입 시 자동 보유.", en: "Owned automatically when this district unlocks." },
        },
        {
          number: 2,
          title: { ko: "베이징 차이니즈 이터리", en: "Beijing Chinese Eatery" },
          location: { ko: "후지소바 북쪽", en: "North of Fuji Soba" },
          body: { ko: "인수 가격 ¥41,600,000. 구역에서 가장 저렴.", en: "Price ¥41,600,000. Cheapest in the district." },
        },
        {
          number: 3,
          title: { ko: "아사이 빌딩 3호", en: "Asai Building No. 3" },
          location: { ko: "카페 알프스 북쪽", en: "North of Cafe Alps" },
          body: { ko: "인수 가격 ¥51,200,000.", en: "Price ¥51,200,000." },
        },
        {
          number: 4,
          title: { ko: "텐포 스시", en: "Tenpo Sushi" },
          location: { ko: "후지소바 남쪽", en: "South of Fuji Soba" },
          body: { ko: "인수 가격 ¥51,200,000.", en: "Price ¥51,200,000." },
        },
        {
          number: 5,
          title: { ko: "러블리 버니", en: "Lovely Bunny" },
          location: { ko: "스마일 버거 남쪽", en: "South of Smile Burger" },
          body: { ko: "인수 가격 ¥56,000,000.", en: "Price ¥56,000,000." },
        },
        {
          number: 6,
          title: { ko: "어뮤즈먼트 게임 유", en: "Amusement Game You" },
          location: { ko: "긴다코 동쪽", en: "East of Gindaco" },
          body: { ko: "인수 가격 ¥59,200,000.", en: "Price ¥59,200,000." },
        },
        {
          number: 7,
          title: { ko: "파칭코 알로하", en: "Pachinko Aloha" },
          location: { ko: "후지소바 건너편", en: "Across from Fuji Soba" },
          body: { ko: "인수 가격 ¥75,200,000.", en: "Price ¥75,200,000." },
        },
        {
          number: 8,
          title: { ko: "파칭코 777", en: "Pachinko 777" },
          location: { ko: "아사이 빌딩 북쪽", en: "North of Asai Building" },
          body: { ko: "인수 가격 ¥78,400,000. 구역 최고가 일반 매물.", en: "Price ¥78,400,000. Most expensive standard property." },
        },
        {
          number: 9,
          title: { ko: "쇼키치 카메라", en: "Shokichi Camera" },
          location: { ko: "후지소바 북쪽으로 두 블록", en: "Two buildings north of Fuji Soba" },
          body: { ko: "인수 가격 ¥82,400,000.", en: "Price ¥82,400,000." },
        },
        {
          number: 10,
          title: { ko: "HL 세가 나카미치 거리점 (친구 매핑)", en: "HL SEGA Nakamichi St. (Friendship Mapped)" },
          location: { ko: "요로노타키 북쪽 — 나카미치 거리", en: "North of Yoronotaki — Nakamichi St." },
          body: { ko: "구매 불가 — 게임센터 점원 루카와의 친구 호감도를 풀까지 올리면 무상 양도.", en: "Not purchasable — gifted when arcade clerk Luka's friendship is maxed." },
          prereq: { ko: "게임센터 점원 루카 친구 호감도 MAX", en: "Friendship MAX with arcade clerk Luka" },
        },
      ],
    },
    {
      title: { ko: "플레저 킹 매물 — 핑크 거리·텔레폰 클럽 일대", en: "Pleasure King Properties — Pink St. / Telephone Club Area" },
      mapImage: "https://lh3.googleusercontent.com/nIcf1dnAQOQDJH8JzKtpRZRbYxpds3--IFKwF6Emw05E7zYSwz2yJy8eXHi-p7SMEXHHEUwcYSWaRNUhwGV",
      items: [
        {
          number: 1,
          title: { ko: "하야시 건설 (시작 점포)", en: "Hayashi Construction (Starting Property)" },
          location: { ko: "텐고쿠켄 남쪽", en: "South of Tengokuken" },
          body: { ko: "플레저 킹 구역 진입 시 자동 보유.", en: "Owned automatically when this district unlocks." },
        },
        {
          number: 2,
          title: { ko: "콰르티에 라탱", en: "Quartier Latin" },
          location: { ko: "쇼와 거리 — 포포 북쪽", en: "Showa St. — north of Poppo" },
          body: { ko: "인수 가격 ¥89,600,000. 구역 최저가.", en: "Price ¥89,600,000. Cheapest in district." },
        },
        {
          number: 3,
          title: { ko: "톤텐샨", en: "Tontenshan" },
          location: { ko: "노팬티 BBQ 북동쪽", en: "Northeast of No-Panties BBQ" },
          body: { ko: "인수 가격 ¥96,000,000.", en: "Price ¥96,000,000." },
        },
        {
          number: 4,
          title: { ko: "섹슈얼 해러스먼트 캅", en: "Sexual Harassment Cop" },
          location: { ko: "아라비아 레코드 북쪽", en: "North of Arabia Records" },
          body: { ko: "인수 가격 ¥102,400,000.", en: "Price ¥102,400,000." },
        },
        {
          number: 5,
          title: { ko: "모스크바 양식당", en: "Moscow Western Cuisine" },
          location: { ko: "텔텔 보이즈 클럽 북쪽", en: "North of Teltel Boys Club" },
          body: { ko: "인수 가격 ¥102,400,000.", en: "Price ¥102,400,000." },
        },
        {
          number: 6,
          title: { ko: "카무로 월드 시어터", en: "Kamuro World Theater" },
          location: { ko: "캬바레 발렌타인 북쪽", en: "North of Cabaret Valentine" },
          body: { ko: "인수 가격 ¥108,800,000.", en: "Price ¥108,800,000." },
        },
        {
          number: 7,
          title: { ko: "오간도 아츠", en: "Ogando Arts" },
          location: { ko: "쇼텐 북동쪽", en: "Northeast of Shoten" },
          body: { ko: "인수 가격 ¥115,200,000.", en: "Price ¥115,200,000." },
        },
        {
          number: 8,
          title: { ko: "노팬티 BBQ", en: "No-Panties BBQ" },
          location: { ko: "카무로 월드 시어터 북쪽", en: "North of Kamuro World Theater" },
          body: { ko: "인수 가격 ¥124,800,000.", en: "Price ¥124,800,000." },
        },
        {
          number: 9,
          title: { ko: "아라비아 레코드", en: "Arabia Records" },
          location: { ko: "포포 오른쪽", en: "Right of Poppo" },
          body: { ko: "인수 가격 ¥158,800,000.", en: "Price ¥158,800,000." },
        },
        {
          number: 10,
          title: { ko: "캬바레 발렌타인", en: "Cabaret Valentine" },
          location: { ko: "포포 북쪽으로 두 블록", en: "Two buildings north of Poppo" },
          body: { ko: "인수 가격 ¥160,000,000. 구역 최고가.", en: "Price ¥160,000,000. Most expensive in district." },
        },
      ],
    },
    {
      title: { ko: "갬블링 킹 매물 — 극장 광장 일대 (북서중부)", en: "Gambling King Properties — Theater Square Area (Northwest-Center)" },
      mapImage: "https://lh3.googleusercontent.com/kje52WRy1qv7bSUgdzzP8qIcbq_PQUpuJEO6NBzryhabIcNfZpDyXq5UZKSJlwg2ZinGVJ49Kjl5a9KiXH__NyjQQQ_sjtppMp-X3ck1KM1Pmg",
      items: [
        {
          number: 1,
          title: { ko: "카무로 소바 (시작 점포)", en: "Kamuro Soba (Starting Property)" },
          location: { ko: "NY 핫도그 남쪽", en: "South of NY Hot Dog" },
          body: { ko: "갬블링 킹 구역 진입 시 자동 보유.", en: "Owned automatically when this district unlocks." },
        },
        {
          number: 2,
          title: { ko: "NY 핫도그", en: "NY Hot Dog" },
          location: { ko: "산와 레저 홀 동쪽", en: "East of Sanwa Leisure Hall" },
          body: { ko: "인수 가격 ¥204,800,000. 구역 최저가.", en: "Price ¥204,800,000. Cheapest in district." },
        },
        {
          number: 3,
          title: { ko: "파칭코 뉴 코스모스", en: "Pachinko New Cosmos" },
          location: { ko: "기브슨 홀 남서쪽", en: "Southwest of Gibson Hall" },
          body: { ko: "인수 가격 ¥224,000,000.", en: "Price ¥224,000,000." },
        },
        {
          number: 4,
          title: { ko: "뉴 몽마르트르", en: "New Montmartre" },
          location: { ko: "마하 볼 북쪽", en: "North of Mach Bowl" },
          body: { ko: "인수 가격 ¥262,400,000.", en: "Price ¥262,400,000." },
        },
        {
          number: 5,
          title: { ko: "산와 레저 홀", en: "Sanwa Leisure Hall" },
          location: { ko: "NY 핫도그 북서쪽", en: "Northwest of NY Hot Dog" },
          body: { ko: "인수 가격 ¥268,800,000.", en: "Price ¥268,800,000." },
        },
        {
          number: 6,
          title: { ko: "카무로 라 스칼라 시네마", en: "Kamuro La Scala Cinema" },
          location: { ko: "극장 광장 북서쪽", en: "Northwest of Theater Square" },
          body: { ko: "인수 가격 ¥275,200,000.", en: "Price ¥275,200,000." },
        },
        {
          number: 7,
          title: { ko: "도쿄 포푸리", en: "Tokyo Popuri" },
          location: { ko: "마하 볼 북쪽", en: "North of Mach Bowl" },
          body: { ko: "인수 가격 ¥275,200,000.", en: "Price ¥275,200,000." },
        },
        {
          number: 8,
          title: { ko: "기브슨 홀", en: "Gibson Hall" },
          location: { ko: "극장 광장 남서쪽", en: "Southwest of Theater Square" },
          body: { ko: "인수 가격 ¥307,200,000.", en: "Price ¥307,200,000." },
        },
        {
          number: 9,
          title: { ko: "파칭코 빅 스타", en: "Pachinko BIG STAR" },
          location: { ko: "카무로 소바 남서쪽", en: "Southwest of Kamuro Soba" },
          body: { ko: "인수 가격 ¥326,400,000. 구역 최고가 일반 매물.", en: "Price ¥326,400,000. Most expensive standard property." },
        },
        {
          number: 10,
          title: { ko: "마하 볼 (친구 매핑)", en: "Mach Bowl (Friendship Mapped)" },
          location: { ko: "기브슨 홀 서쪽", en: "West of Gibson Hall" },
          body: { ko: "구매 불가 — 볼링 직원 에미리와의 친구 호감도를 풀까지 올리면 무상 양도.", en: "Not purchasable — gifted when bowling employee Emiri's friendship is maxed." },
          prereq: { ko: "마하 볼 종업원 에미리 친구 호감도 MAX", en: "Friendship MAX with Mach Bowl employee Emiri" },
        },
      ],
    },
    {
      title: { ko: "미디어 킹 매물 — 호텔가·밀레니엄 타워 일대 (동부)", en: "Media King Properties — Hotel District / Millennium Tower Area (East)" },
      mapImage: "https://lh3.googleusercontent.com/3igYqe-TTLuuTH7aBxN8CsnHJbWyAPIU32r8ka1-wn68irJghiwVcL918YHQKkXku3fJxwZCjkPEdwWPX1J51u4FbnI6PE7I0shCoLTPbwJ1",
      items: [
        {
          number: 1,
          title: { ko: "도키와 식당 (시작 점포)", en: "Tokiwa Restaurant (Starting Property)" },
          location: { ko: "마하라자 서쪽", en: "West of Maharaja" },
          body: { ko: "미디어 킹 구역 진입 시 자동 보유.", en: "Owned automatically when this district unlocks." },
        },
        {
          number: 2,
          title: { ko: "코게츠 극장", en: "Kogetsu Theater" },
          location: { ko: "빈센트 동쪽", en: "East of Vincent" },
          body: { ko: "인수 가격 ¥793,600,000. 구역 최저가.", en: "Price ¥793,600,000. Cheapest in district." },
        },
        {
          number: 3,
          title: { ko: "호텔 머메이드", en: "Hotel Mermaid" },
          location: { ko: "요시다 배팅 센터 북동쪽", en: "Northeast of Yoshida Batting Center" },
          body: { ko: "인수 가격 ¥921,600,000.", en: "Price ¥921,600,000." },
        },
        {
          number: 4,
          title: { ko: "텔레쿠라 린린보", en: "Telekura Rinrin-bo" },
          location: { ko: "디스코 시티 보이 북서쪽", en: "Northwest of Disco City Boy" },
          body: { ko: "인수 가격 ¥921,600,000.", en: "Price ¥921,600,000." },
        },
        {
          number: 5,
          title: { ko: "호텔 화이트", en: "Hotel White" },
          location: { ko: "호텔 다이아몬드 팰리스 왼쪽", en: "Left of Hotel Diamond Palace" },
          body: { ko: "인수 가격 ¥921,600,000.", en: "Price ¥921,600,000." },
        },
        {
          number: 6,
          title: { ko: "카무로 온천", en: "Kamuro Hot Springs" },
          location: { ko: "호텔 블루 라이트 서쪽으로 두 블록", en: "Two buildings west of Hotel Blue Light" },
          body: { ko: "인수 가격 ¥972,800,000.", en: "Price ¥972,800,000." },
        },
        {
          number: 7,
          title: { ko: "호텔 블루 라이트", en: "Hotel Blue Light" },
          location: { ko: "빈센트 서쪽", en: "West of Vincent" },
          body: { ko: "인수 가격 ¥998,400,000.", en: "Price ¥998,400,000." },
        },
        {
          number: 8,
          title: { ko: "호텔 다이아몬드 팰리스", en: "Hotel Diamond Palace" },
          location: { ko: "요시다 배팅 센터 북쪽으로 두 블록", en: "Two buildings north of Yoshida Batting Center" },
          body: { ko: "인수 가격 ¥998,400,000.", en: "Price ¥998,400,000." },
        },
        {
          number: 9,
          title: { ko: "디스코 시티 보이", en: "Disco City Boy" },
          location: { ko: "칸라이 서쪽으로 두 블록", en: "Two buildings west of Kanrai" },
          body: { ko: "인수 가격 ¥1,228,800,000. 구역 최고가. 인수 시 「The Glamorous Life」 업적 트리거.", en: "Price ¥1,228,800,000. Most expensive in district. Buying triggers 'The Glamorous Life' achievement." },
          reward: { ko: "「The Glamorous Life」 업적", en: "'The Glamorous Life' achievement" },
        },
        {
          number: 10,
          title: { ko: "포켓 서킷 스타디움 (친구 매핑)", en: "Pocket Circuit Stadium (Friendship Mapped)" },
          location: { ko: "M 스토어 서쪽", en: "West of M Store" },
          body: { ko: "구매 불가 — 포켓 서킷 파이터와의 친구 호감도를 풀까지 올리면 무상 양도.", en: "Not purchasable — gifted when Pocket Circuit Fighter's friendship is maxed." },
          prereq: { ko: "포켓 서킷 파이터 친구 호감도 MAX", en: "Friendship MAX with Pocket Circuit Fighter" },
        },
      ],
    },
    ],
  },
  {
    slug: "cabaret-club-czar",
    title: { ko: "소텐보리 물장사 아일랜드 — 5구역 + 플래티넘 호스티스 육성", en: "Sotenbori Cabaret Royale — 5 Districts + Platinum Hostess Training" },
    summary: { ko: "마지마 편 캬바쿠라 그랑프리 모드. 플레이어 가게 「클럽 선샤인」을 운영하며 소텐보리를 지배하는 「소텐보리 5스타」 라이벌 5점포(클럽 마즈·클럽 주피터·클럽 머큐리·클럽 비너스·클럽 문)를 차례로 격파합니다. 플래티넘 캐스트 6명(유키·사키·치카·아이·히비키·마나)을 영입해 능력치(섹시 / 뷰티 / 큐트 / 퍼니 4종 × X→△→○→◎ 4단계) MAX로 키웁니다. 캐스트별 특별 레슨의 정답 선택지 텍스트(예: 「분재…?」 / 「무조건 칭찬한다」)는 아래 레슨별 카드에서 전문으로 안내합니다.", en: "Majima's Cabaret Club Grand Prix. You run Club Sunshine and topple the Five Stars of Sotenbori — Club Mars, Club Jupiter, Club Mercury, Club Venus, and Club Moon. Recruit all 6 Platinum Cast (Yuki/Saki/Chika/Ai/Hibiki/Mana) and train them to MAX across the 4 stats (Sexy / Beauty / Cute / Funny — X→△→○→◎ tiers). Full Private Lesson dialog answers (e.g. \"Bonsai...?\" / \"Just praise her no matter what\") are listed verbatim in the per-cast lesson cards below." },
    tips: [
        { ko: "호스티스 능력치는 섹시 / 뷰티 / 큐트 / 퍼니 4종. 등급은 X / △ / ○ / ◎ 순으로 4단계입니다. 한 캐스트당 최대 3개 항목만 ◎까지 올릴 수 있으니, 캐스트별로 역할을 분담해 1개를 X로 두고 나머지 3개를 ◎로 특화하세요.", en: "Hostess stats split into Sexy / Beauty / Cute / Funny, ranked X → △ → ○ → ◎. Only 3 of 4 can hit ◎ per cast — specialize: lock one as X and push the other three to ◎ so roles don't overlap." },
        { ko: "특별 레슨(프라이빗 레슨)은 노래방·댄스·당구·다트 데이트로 진행됩니다. 호감도 + 데이트 승리로 레벨이 비약적으로 오릅니다. 데이트 선택지는 호스티스의 성격 유형에 맞춰 답하면 정답.", en: "Private Lessons use karaoke / dance / billiards / darts dates. Affinity + date wins drastically raise levels. Pick choices that match the hostess's personality type for the right answer." },
        { ko: "5스타 풀 제패 시 「지지 않는 태양」 업적이 트리거됩니다. 최종 라이벌 클럽 문 결전 전에 캐스트 능력치를 풀로 올려 두세요.", en: "Conquering all Five Stars triggers 'Walking On Sunshine'. Max out cast stats before the final Club Moon showdown." },
    ],
    source: { label: "용과 같이 시리즈/캬바쿠라 — 나무위키", url: "https://namu.wiki/w/%EC%9A%A9%EA%B3%BC%20%EA%B0%99%EC%9D%B4%20%EC%8B%9C%EB%A6%AC%EC%A6%88/%EC%BA%AC%EB%B0%94%EC%BF%A0%EB%9D%BC" },
    groups: [
    {
      title: { ko: "소텐보리 5스타 — 라이벌 클럽 제패", en: "Five Stars of Sotenbori — Rival Club Battles" },
      items: [
      {
        number: 1,
        title: { ko: "클럽 마즈 격파 (보스: 히노)", en: "Defeat Club Mars (Boss: Hino)" },
        location: { ko: "소텐보리 — 마즈 영역 (퍼플)", en: "Sotenbori — Mars Area (Purple)" },
        body: { ko: "5스타 입문전. 튜토리얼 직후 도전 가능. 일반 호스티스 라인업 + 트레이닝 1단계만 마쳐도 1위 매출 가능.", en: "Entry battle. Available right after the tutorial. Standard hostesses + basic training are enough for #1 sales." },
      },
      {
        number: 2,
        title: { ko: "클럽 주피터 격파 (보스: 키즈카)", en: "Defeat Club Jupiter (Boss: Kizuka)" },
        location: { ko: "소텐보리 — 주피터 영역 (그린)", en: "Sotenbori — Jupiter Area (Green)" },
        body: { ko: "Mars 클리어 후 도전. 첫 번째 플래티넘 캐스트 영입 가능 시점.", en: "After Mars. First Platinum Cast becomes recruitable here." },
      },
      {
        number: 3,
        title: { ko: "클럽 머큐리 격파 (보스: 미즈무라)", en: "Defeat Club Mercury (Boss: Mizumura)" },
        location: { ko: "소텐보리 — 머큐리 영역 (블루)", en: "Sotenbori — Mercury Area (Blue)" },
        body: { ko: "능력치 ◎ 1개로는 불안정. 트레이닝 + 데이트 이벤트로 캐스트 1~2명을 핵심급으로 키워두세요.", en: "Single-◎ casts struggle here. Push 1-2 casts to core spec with training + date events." },
      },
      {
        number: 4,
        title: { ko: "클럽 비너스 격파 (보스: 카네하라)", en: "Defeat Club Venus (Boss: Kanehara)" },
        location: { ko: "소텐보리 — 비너스 영역 (레드)", en: "Sotenbori — Venus Area (Red)" },
        body: { ko: "VIP 손님 비중이 커집니다. 플래티넘 캐스트 4명 풀 영입 + 의상·헤어 풀 강화 후 도전.", en: "VIP customers dominate. Recruit all 4 Platinum Casts + max outfits + hair before challenging." },
      },
      {
        number: 5,
        title: { ko: "클럽 문 결승전 (보스: 츠키야마)", en: "Club Moon — Final (Boss: Tsukiyama)" },
        location: { ko: "소텐보리 — 문 영역 (골드) / 그랑프리 결승", en: "Sotenbori — Moon Area (Gold) / Grand Prix Final" },
        body: { ko: "최종 라이벌. 츠키야마는 5스타의 리더. 플래티넘 캐스트 4명을 능력치 MAX로 만들고 데이트 이벤트 풀 클리어 후 도전. 격파 시 「지지 않는 태양」 업적 + 클럽 선샤인 통합.", en: "Final rival — Tsukiyama leads the Five Stars. Hit MAX on all 4 Platinum Casts + clear date events. Win for 'Walking On Sunshine' achievement + Club Sunshine takes the throne." },
        reward: { ko: "「지지 않는 태양」 업적 + 마지마 부동산 외 시드 머니 확장", en: "'Walking On Sunshine' achievement + cabaret-side cash flow for Majima" },
      },
      ],
    },
    {
      title: { ko: "플래티넘 캐스트 육성 — 능력치 4종 / 데이트 시스템", en: "Platinum Cast Training — 4 Stats / Date System" },
      items: [
      {
        number: 6,
        title: { ko: "섹시 라인", en: "Sexy line (X→△→○→◎)" },
        location: { ko: "드레스업 — 의상·헤어 변경", en: "Dress-Up — outfit + hair" },
        body: { ko: "노출도 높은 의상 + 헤어로 상승. 데이트 미니게임 중 「당구」 승리 시 추가 보너스.", en: "Boosted by exposed outfits + hairstyles. Win billiards dates for extra Sexy gains." },
      },
      {
        number: 7,
        title: { ko: "뷰티 라인", en: "Beauty line" },
        location: { ko: "드레스업 — 액세서리·화장", en: "Dress-Up — accessories + makeup" },
        body: { ko: "고급 액세서리 + 메이크업으로 상승. 「댄스」 데이트 승리 시 추가 보너스.", en: "High-end accessories + makeup. Win dance dates for extra Beauty gains." },
      },
      {
        number: 8,
        title: { ko: "큐트 라인", en: "Cute line" },
        location: { ko: "드레스업 — 캐주얼 의상", en: "Dress-Up — casual outfits" },
        body: { ko: "파스텔 톤·캐주얼 의상으로 상승. 「노래방」 데이트 승리 시 추가 보너스.", en: "Pastel / casual outfits. Win karaoke dates for extra Cute gains." },
      },
      {
        number: 9,
        title: { ko: "퍼니 라인", en: "Funny line" },
        location: { ko: "드레스업 — 개성적인 의상", en: "Dress-Up — quirky outfits" },
        body: { ko: "개성적인 의상 + 헤어. 「다트」 데이트 승리 시 추가 보너스.", en: "Quirky outfits + hair. Win darts dates for extra Funny gains." },
      },
      {
        number: 10,
        title: { ko: "특별 레슨 (프라이빗 레슨)", en: "Private Lesson" },
        location: { ko: "플래티넘 캐스트 — 호감도 + 데이트", en: "Platinum Cast — affinity + date" },
        body: { ko: "호감도가 일정 단계 이상이면 특별 레슨 해금. 데이트 선택지는 캐릭터 성격에 맞춰 답해야 호감도가 크게 오릅니다.", en: "Affinity gates unlock Private Lessons. Match dialog choices to the cast's personality type for a big affinity spike." },
      },
      {
        number: 11,
        title: { ko: "캐스트 LV MAX → 다이아몬드 캐스트", en: "Cast LV MAX → Diamond Cast" },
        location: { ko: "플래티넘 캐스트 — 모든 능력치 + LV", en: "Platinum Cast — all stats + LV" },
        body: { ko: "한 명의 캐스트를 LV MAX까지 키우면 「다이아몬드 캐스트」 업적 발동. 이후 다른 캐스트도 같이 키워 풀 라인업으로 결승전을 노리세요.", en: "Maxing one cast's LV unlocks 'You're Still Number One'. Continue maxing the rest for the final club battle." },
        reward: { ko: "「다이아몬드 캐스트」 업적", en: "'You're Still Number One' achievement" },
      },
      ],
    },

    {
      title: { ko: "플래티넘 캐스트 특별 레슨 — 6명 × 7회 정답 선택지(전문)", en: "Platinum Cast Private Lessons — 6 × 7 Full-Text Choice Sheet" },
      items: [
      {
        number: 12,
        title: { ko: "유키 — 접객 연습 1회차", en: "Yuki — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「분재…?」 → 2) 「무조건 칭찬한다」 → 3) 「나이 든 손님에게 안성맞춤」 → 4) 「나도 남자라카이」", en: "Correct choices (in order): 1) \"Bonsai...?\" → 2) \"Just praise her no matter what\" → 3) \"Perfect for older customers\" → 4) \"I'm a guy too, y'know\"" },
      },
      {
        number: 13,
        title: { ko: "유키 — 접객 연습 2회차", en: "Yuki — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「왠지 알 것 같다」 → 2) 「다양한 여자가 있어서 좋다」 → 3) 「좋아하면 노력할 수 있지 않을까」 → 4) 「적어도 이름은 진짜로 해라, 거짓말쟁이」", en: "Correct choices (in order): 1) \"I kinda get it\" → 2) \"It's nice that there are all kinds of girls\" → 3) \"If you love it, you can push through, right?\" → 4) \"At least use your real first name, you little liar\"" },
      },
      {
        number: 14,
        title: { ko: "유키 — 접객 연습 3회차", en: "Yuki — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「가자미 지느러미살이네」 → 2) 「꼭 부탁하고 싶다」 → 3) 「손님을 전부 나라고 생각해라」 → 4) 「열심히 하고 있다고 본다」", en: "Correct choices (in order): 1) \"That's engawa, huh\" → 2) \"I'd love for you to do it\" → 3) \"Think of every customer as me\" → 4) \"I think you're working hard\"" },
      },
      {
        number: 15,
        title: { ko: "유키 — 접객 연습 4회차", en: "Yuki — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「분재」 → 2) 「기업이 보는 눈이 없다」 → 3) 「내가 빡세게 굴려주마!」 → 4) 「잠은 충분히 자라」", en: "Correct choices (in order): 1) \"Bonsai\" → 2) \"Those companies have no eye for talent\" → 3) \"I'll whip you into shape!\" → 4) \"Make sure you get plenty of sleep\"" },
      },
      {
        number: 16,
        title: { ko: "유키 — 동반 연습 — 노래방", en: "Yuki — Companion Practice — Karaoke" },
        location: { ko: "동반 연습 — 노래방", en: "Companion Practice — Karaoke" },
        body: { ko: "정답 경로: 「×3 샤인」에서 추임새를 넣는다 · 「24시간 신데렐라」를 부른다 둘 다 90점 이상이면 퍼펙트 레슨", en: "Correct path: Do the call-and-response on \"×3 Shine\" / Sing \"24-Hour Cinderella\" — score 90+ on both for a Perfect Lesson" },
      },
      {
        number: 17,
        title: { ko: "유키 — 동반 연습 — 디스코", en: "Yuki — Companion Practice — Disco" },
        location: { ko: "동반 연습 — 디스코", en: "Companion Practice — Disco" },
        body: { ko: "정답 경로: 「사랑의 디스코 퀸」으로 승부 Result★3이면 퍼펙트 레슨", en: "Correct path: Compete with \"Disco Queen of Love\" — get Result★3 for a Perfect Lesson" },
      },
      {
        number: 18,
        title: { ko: "유키 — 접객 연습 최종 회차", en: "Yuki — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「유키 많이 컸네」 → 2) 「언제든 기대 와도 된다」 → 3) 「사랑스러운 사람」 → 4) 「소, 소중히 해라」", en: "Correct choices (in order): 1) \"You've really grown, Yuki\" → 2) \"You can lean on me anytime\" → 3) \"Someone dear to me\" → 4) \"T-take good care of him\"" },
        reward: { ko: "서브스토리 No.69 「마지마의 부정」 발생", en: "Triggers Substory #69 \"Majima's Parental Heart\"" },
      },
      {
        number: 19,
        title: { ko: "아이 — 접객 연습 1회차", en: "Ai — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「다음에 같이 먹으러 가자!」 → 2) 「마사지를 받는다」 → 3) 「우리 가게에 와줘서 다행이다」 → 4) 「신경 쓰지 말고 편하게 가자」", en: "Correct choices (in order): 1) \"Let's go eat together next time!\" → 2) \"Have her give me a massage\" → 3) \"I'm glad you came to our place\" → 4) \"Don't worry about it, just take it easy\"" },
      },
      {
        number: 20,
        title: { ko: "아이 — 접객 연습 2회차", en: "Ai — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「연상의 남자가 봐도 매력적이다」 → 2) 「접객업이니까 어쩔 수 없다」 → 3) 「남자친구만 볼 수 있는 모습이네」 → 4) 「귀엽잖아」", en: "Correct choices (in order): 1) \"Even an older guy finds you charming\" → 2) \"It comes with the service job\" → 3) \"That's a side only your boyfriend gets to see\" → 4) \"That's cute, isn't it\"" },
      },
      {
        number: 21,
        title: { ko: "아이 — 동반 연습 — 디스코", en: "Ai — Companion Practice — Disco" },
        location: { ko: "동반 연습 — 디스코", en: "Companion Practice — Disco" },
        body: { ko: "정답 경로: 「Queen of the passion」으로 승부 Result★3이면 퍼펙트 레슨", en: "Correct path: Compete with \"Queen of the Passion\" — get Result★3 for a Perfect Lesson" },
      },
      {
        number: 22,
        title: { ko: "아이 — 접객 연습 3회차", en: "Ai — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「아이 같은 딸」 → 2) 「요리를 잘함」 → 3) 「태어나기 전」 → 4) 「그만두게 한다」", en: "Correct choices (in order): 1) \"A daughter like Ai\" → 2) \"Good at cooking\" → 3) \"Before she was born\" → 4) \"Make her quit\"" },
      },
      {
        number: 23,
        title: { ko: "아이 — 접객 연습 4회차", en: "Ai — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「앞으로 같이 힘내자!」 → 2) 「나도 힘을 받고 있다」 → 3) 「돈이 전부가 아니다」 → 4) 「난 데릴사위라도 상관없다」", en: "Correct choices (in order): 1) \"Let's keep working hard together!\" → 2) \"I get energy from you too\" → 3) \"Money isn't everything\" → 4) \"I don't mind marrying into your family\"" },
      },
      {
        number: 24,
        title: { ko: "아이 — 동반 연습 — 당구", en: "Ai — Companion Practice — Billiards" },
        location: { ko: "동반 연습 — 당구", en: "Companion Practice — Billiards" },
        body: { ko: "정답 경로: 나인볼로 아이와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play nine-ball against Ai — win for a Perfect Lesson" },
      },
      {
        number: 25,
        title: { ko: "아이 — 접객 연습 최종 회차", en: "Ai — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「선샤인에 어서 오세요」 → 2) 「용서할 수 없다!」 → 3) 「좋은 점이 너무 많은가?」 → 4) 「다음에 같이 갈까」 → 5) 간다라에 이미지 비디오 03 「우에하라 아이」 입고", en: "Correct choices (in order): 1) \"Welcome to Sunshine\" → 2) \"I can't let this slide!\" → 3) \"Too many good points, huh?\" → 4) \"Let's go together next time\" → 5) Image Video 03 \"Ai Uehara\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 03 해금", en: "Substory + Image Video 03 unlock" },
      },
      {
        number: 26,
        title: { ko: "사키 — 접객 연습 1회차", en: "Saki — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「멋진 취미네」 → 2) 「가라아게 너무 좋아」 → 3) 「좋은 엄마가 될 것 같다」 → 4) 「내가 처치하러 가줄까」", en: "Correct choices (in order): 1) \"That's a cool hobby\" → 2) \"I love karaage\" → 3) \"You'd make a great mom\" → 4) \"Want me to go take care of him?\"" },
      },
      {
        number: 27,
        title: { ko: "사키 — 접객 연습 2회차", en: "Saki — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「나는 남자다워 보이나?」 → 2) 「응석 부려보면 어떻노」 → 3) 「그 사람도 기뻤겠다」 → 4) 「괜찮지 않노」", en: "Correct choices (in order): 1) \"Do I seem manly?\" → 2) \"Why don't you try acting spoiled?\" → 3) \"He must've been happy\" → 4) \"That's fine, isn't it\"" },
      },
      {
        number: 28,
        title: { ko: "사키 — 동반 연습 — 디스코", en: "Saki — Companion Practice — Disco" },
        location: { ko: "동반 연습 — 디스코", en: "Companion Practice — Disco" },
        body: { ko: "정답 경로: 「I wanna take you home」으로 승부 Result★3이면 퍼펙트 레슨", en: "Correct path: Compete with \"I Wanna Take You Home\" — get Result★3 for a Perfect Lesson" },
      },
      {
        number: 29,
        title: { ko: "사키 — 접객 연습 3회차", en: "Saki — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「목표를 향해 달리는 집념」 → 2) 「연속 출근해주면 도움이 된다」 → 3) 「가라아게」 → 4) 「있다」", en: "Correct choices (in order): 1) \"Drive that runs toward a goal\" → 2) \"It'd help if you worked consecutive days\" → 3) \"Karaage\" → 4) \"There is\"" },
      },
      {
        number: 30,
        title: { ko: "사키 — 동반 연습 — 당구", en: "Saki — Companion Practice — Billiards" },
        location: { ko: "동반 연습 — 당구", en: "Companion Practice — Billiards" },
        body: { ko: "정답 경로: 나인볼로 사키와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play nine-ball against Saki — win for a Perfect Lesson" },
      },
      {
        number: 31,
        title: { ko: "사키 — 접객 연습 4회차", en: "Saki — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「형제자매가 많았으니까」 → 2) 「힘들면 말하그라」 → 3) 「섭섭하지만 응원한다카이」 → 4) 「무작정 한다고 되는 게 아니다」", en: "Correct choices (in order): 1) \"You had a lot of siblings, after all\" → 2) \"Tell me when it gets tough\" → 3) \"I'll miss ya, but I'm cheering for you\" → 4) \"You can't just charge in blindly\"" },
      },
      {
        number: 32,
        title: { ko: "사키 — 접객 연습 최종 회차", en: "Saki — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「여자아이니까 그렇지」 → 2) 「이걸로 공부에 집중할 수 있다」 → 3) 「다치면 큰일이다카이」 → 4) 「오빠… 라」 → 5) 간다라에 이미지 비디오 05 「하츠미 사키」 입고", en: "Correct choices (in order): 1) \"You are a girl, after all\" → 2) \"Now you can focus on your studies\" → 3) \"It'd be bad if you got hurt\" → 4) \"Big brother... huh\" → 5) Image Video 05 \"Saki Hatsumi\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 05 해금", en: "Substory + Image Video 05 unlock" },
      },
      {
        number: 33,
        title: { ko: "히비키 — 접객 연습 1회차", en: "Hibiki — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「때로는 엄격하게」 → 2) 「무리하면 안 된다」 → 3) 「어떤 만화를 좋아하노?」 → 4) 「무리할 필요는 없다」", en: "Correct choices (in order): 1) \"Sometimes strict\" → 2) \"Don't push yourself too hard\" → 3) \"What kind of manga do you like?\" → 4) \"You don't need to force it\"" },
      },
      {
        number: 34,
        title: { ko: "히비키 — 접객 연습 2회차", en: "Hibiki — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「좋은 생각이라고 본다」 → 2) 「히비키의 목소리가 좋다」 → 3) 「나도 응석 부리게 해다오」 → 4) 「그거 귀엽잖아!」", en: "Correct choices (in order): 1) \"I think that's a good idea\" → 2) \"I like Hibiki's voice\" → 3) \"Let me lean on you too\" → 4) \"That's cute!\"" },
      },
      {
        number: 35,
        title: { ko: "히비키 — 동반 연습 — 다트", en: "Hibiki — Companion Practice — Darts" },
        location: { ko: "동반 연습 — 다트", en: "Companion Practice — Darts" },
        body: { ko: "정답 경로: COUNT-UP으로 히비키와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play Count-Up against Hibiki — win for a Perfect Lesson" },
      },
      {
        number: 36,
        title: { ko: "히비키 — 접객 연습 3회차", en: "Hibiki — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「아이들에게 미움받음」 → 2) 「여자의 멋진 점」 → 3) 「연상이다」 → 4) 「그다지 활기차지 않은 아이도 좋다」", en: "Correct choices (in order): 1) \"Disliked by kids\" → 2) \"What's wonderful about girls\" → 3) \"Older women\" → 4) \"I also like girls who aren't so peppy\"" },
      },
      {
        number: 37,
        title: { ko: "히비키 — 동반 연습 — 노래방", en: "Hibiki — Companion Practice — Karaoke" },
        location: { ko: "동반 연습 — 노래방", en: "Companion Practice — Karaoke" },
        body: { ko: "정답 경로: 「Rouge of Love」에서 추임새를 넣는다 · 「24시간 신데렐라」를 부른다 둘 다 90점 이상이면 퍼펙트 레슨", en: "Correct path: Do the call-and-response on \"Rouge of Love\" / Sing \"24-Hour Cinderella\" — score 90+ on both for a Perfect Lesson" },
      },
      {
        number: 38,
        title: { ko: "히비키 — 접객 연습 4회차", en: "Hibiki — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「몸이 걱정이다」 → 2) 「언젠가 알게 될 날이 온다」 → 3) 「가게 일만으로도 벅차다…」 → 4) 「나도 놀아보고 싶다카이」", en: "Correct choices (in order): 1) \"I'm worried about your health\" → 2) \"Someday you'll understand\" → 3) \"The shop keeps me busy enough...\" → 4) \"I'd like to play too\"" },
      },
      {
        number: 39,
        title: { ko: "히비키 — 접객 연습 최종 회차", en: "Hibiki — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「너무 짊어지지 마라」 → 2) 「히비키는 행복하구나」 → 3) 「그릇이 큰 남자」 → 4) 「고맙다」 → 5) 간다라에 이미지 비디오 04 「오오츠키 히비키」 입고", en: "Correct choices (in order): 1) \"You're carrying too much\" → 2) \"You're a lucky girl, Hibiki\" → 3) \"A big-hearted man\" → 4) \"Thank you\" → 5) Image Video 04 \"Hibiki Ohtsuki\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 04 해금", en: "Substory + Image Video 04 unlock" },
      },
      {
        number: 40,
        title: { ko: "치카 — 접객 연습 1회차", en: "Chika — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「치카에게 딱이네」 → 2) 「조금쯤 달라야 재밌다」 → 3) 「인생은 돌아가는 길도 중요하다」 → 4) 「싫어도 미소는 지어야 한다」", en: "Correct choices (in order): 1) \"That suits Chika perfectly\" → 2) \"A bit of difference makes things fun\" → 3) \"Detours in life matter too\" → 4) \"You have to smile even when you don't feel like it\"" },
      },
      {
        number: 41,
        title: { ko: "치카 — 접객 연습 2회차", en: "Chika — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「나쁜 남자에게 속는 타입?」 → 2) 「나는 이해 못 하겠다」 → 3) 「상대에게 맞출 필요 없다」 → 4) 「길 잃는 건 잘하잖아?」", en: "Correct choices (in order): 1) \"The type to get tricked by a bad guy?\" → 2) \"I can't really understand that\" → 3) \"No need to match the other person\" → 4) \"You're good at getting lost, right?\"" },
      },
      {
        number: 42,
        title: { ko: "치카 — 접객 연습 3회차", en: "Chika — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「얌전하고 여성스러운 딸」 → 2) 「사려던 걸 깜빡하기도 하지」 → 3) 「결혼한 내 모습이 상상이 안 된다」 → 4) 「소중한 존재다카이」", en: "Correct choices (in order): 1) \"A graceful, ladylike daughter\" → 2) \"Sometimes forgets what she came to buy\" → 3) \"I can't picture myself married\" → 4) \"You're precious to me\"" },
      },
      {
        number: 43,
        title: { ko: "치카 — 동반 연습 — 당구", en: "Chika — Companion Practice — Billiards" },
        location: { ko: "동반 연습 — 당구", en: "Companion Practice — Billiards" },
        body: { ko: "정답 경로: 나인볼로 치카와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play nine-ball against Chika — win for a Perfect Lesson" },
      },
      {
        number: 44,
        title: { ko: "치카 — 접객 연습 4회차", en: "Chika — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「평소 모습이 더 좋다」 → 2) 「정열적이네」 → 3) 「어떤 가정을 꾸릴 거노?」 → 4) 「일에서도 좋은 만남은 있다」", en: "Correct choices (in order): 1) \"I prefer your usual self\" → 2) \"How passionate\" → 3) \"What kind of home would you build?\" → 4) \"You can find good people through work too\"" },
      },
      {
        number: 45,
        title: { ko: "치카 — 동반 연습 — 노래방", en: "Chika — Companion Practice — Karaoke" },
        location: { ko: "동반 연습 — 노래방", en: "Companion Practice — Karaoke" },
        body: { ko: "정답 경로: 「찰나의 인어공주」에서 추임새를 넣는다 · 「24시간 신데렐라」를 부른다 둘 다 90점 이상이면 퍼펙트 레슨", en: "Correct path: Do the call-and-response on \"Mermaid of a Moment\" / Sing \"24-Hour Cinderella\" — score 90+ on both for a Perfect Lesson" },
      },
      {
        number: 46,
        title: { ko: "치카 — 접객 연습 최종 회차", en: "Chika — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「나도 즐거우니까」 → 2) 「즐겁게 하는 게 최고다」 → 3) 「치카에게는 말이다」 → 4) 「다른 가게로 가지 말아다오!」 → 5) 간다라에 이미지 비디오 01 「아리무라 치카」 입고", en: "Correct choices (in order): 1) \"Because I'm having fun too\" → 2) \"Doing it with joy is the best\" → 3) \"For you, Chika...\" → 4) \"Don't go to another shop!\" → 5) Image Video 01 \"Chika Arimura\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 01 해금", en: "Substory + Image Video 01 unlock" },
      },
      {
        number: 47,
        title: { ko: "마나 — 접객 연습 1회차", en: "Mana — Customer Service Practice 1" },
        location: { ko: "접객 연습 1회차", en: "Customer Service Practice 1" },
        body: { ko: "정답 선택지(순서): 1) 「자신에게 보상을 줘야지」 → 2) 「마나랑 똑 닮았다」 → 3) 「거짓말쟁이라서 알아보는 걸지도」 → 4) 「휴지를 준비해둬야겠네」", en: "Correct choices (in order): 1) \"You've gotta reward yourself\" → 2) \"Looks just like Mana\" → 3) \"Maybe a liar can spot one\" → 4) \"Better grab some tissues\"" },
      },
      {
        number: 48,
        title: { ko: "마나 — 접객 연습 2회차", en: "Mana — Customer Service Practice 2" },
        location: { ko: "접객 연습 2회차", en: "Customer Service Practice 2" },
        body: { ko: "정답 선택지(순서): 1) 「진짜로 연애 경험이 없구나」 → 2) 「이상하지 않다」 → 3) 「할아버지들 상대로 하는 장사다」 → 4) 「알겠다」", en: "Correct choices (in order): 1) \"You really have no dating experience\" → 2) \"It's not weird\" → 3) \"It's a business catering to old men\" → 4) \"Got it\"" },
      },
      {
        number: 49,
        title: { ko: "마나 — 접객 연습 3회차", en: "Mana — Customer Service Practice 3" },
        location: { ko: "접객 연습 3회차", en: "Customer Service Practice 3" },
        body: { ko: "정답 선택지(순서): 1) 「마음에 드는 사람이라면」 → 2) 「나는 M이다」 → 3) 「언젠가 호되게 당한다」 → 4) 「무리하지 말고 병원 가라」", en: "Correct choices (in order): 1) \"If it's someone I'm into\" → 2) \"I'm an M\" → 3) \"You'll get burned someday\" → 4) \"Don't push it, go to the doctor\"" },
      },
      {
        number: 50,
        title: { ko: "마나 — 동반 연습 — 다트", en: "Mana — Companion Practice — Darts" },
        location: { ko: "동반 연습 — 다트", en: "Companion Practice — Darts" },
        body: { ko: "정답 경로: COUNT-UP으로 마나와 승부 승리하면 퍼펙트 레슨", en: "Correct path: Play Count-Up against Mana — win for a Perfect Lesson" },
      },
      {
        number: 51,
        title: { ko: "마나 — 접객 연습 4회차", en: "Mana — Customer Service Practice 4" },
        location: { ko: "접객 연습 4회차", en: "Customer Service Practice 4" },
        body: { ko: "정답 선택지(순서): 1) 「네 페이스대로 말해라」 → 2) 「알려줘서 고맙다카이」 → 3) 「자기 자신을 가꿔라」 → 4) 「성실한 면을 알게 됐다」", en: "Correct choices (in order): 1) \"Speak at your own pace\" → 2) \"Thanks for telling me\" → 3) \"Polish yourself up\" → 4) \"I got to see your serious side\"" },
      },
      {
        number: 52,
        title: { ko: "마나 — 동반 연습 — 디스코", en: "Mana — Companion Practice — Disco" },
        location: { ko: "동반 연습 — 디스코", en: "Companion Practice — Disco" },
        body: { ko: "정답 경로: 「I'm gonna make her mine」으로 승부 Result★3이면 퍼펙트 레슨", en: "Correct path: Compete with \"I'm Gonna Make Her Mine\" — get Result★3 for a Perfect Lesson" },
      },
      {
        number: 53,
        title: { ko: "마나 — 접객 연습 최종 회차", en: "Mana — Customer Service Practice (Final)" },
        location: { ko: "접객 연습 최종 회차", en: "Customer Service Practice (Final)" },
        body: { ko: "정답 선택지(순서): 1) 「마나만 있으면 무적이다」 → 2) 「정신적인 문제일지도 모른다」 → 3) 「살짝 질투했다」 → 4) 「모두가 소중하니까 그런 거다」 → 5) 간다라에 이미지 비디오 02 「사쿠라 마나」 입고", en: "Correct choices (in order): 1) \"With Mana around, I'm unstoppable\" → 2) \"Might be a mental thing\" → 3) \"I got a little jealous\" → 4) \"It's because everyone's important to me\" → 5) Image Video 02 \"Mana Sakura\" arrives at Gandhara" },
        reward: { ko: "서브스토리 + 이미지 비디오 02 해금", en: "Substory + Image Video 02 unlock" },
      },
      ],
    },
    ],
  },
  {
    slug: "video-clips",
    title: { ko: "비디오 — 간다라 비디오 가게 + 특별 클립 해금", en: "Video — Gandara Shop + Special Clip Unlocks" },
    summary: { ko: "용과 같이 0의 비디오 콘텐츠는 「간다라(ガンダーラ)」 비디오 가게에서 진행됩니다. 일반 이미지 비디오를 반복 시청하면 점원과의 호감도가 오르고, 특정 조건을 만족시키면 서브스토리 + 특별 클립이 해금됩니다. 30종 일괄 수집 시스템은 없으며, 핵심은 호감도 + 사이드 트리거입니다.", en: "Y0's video content lives at the Gandara (ガンダーラ) video shop. Watching standard image videos repeatedly raises affinity with the clerk; specific triggers unlock substories + special clips. There is no flat 30-clip checklist — what matters is affinity + side triggers." },
    tips: [
        { ko: "간다라 소텐보리점에서 처음 비디오를 보면 서브스토리가 자동 발생. 점원과의 절(絆) 게이지가 함께 오릅니다.", en: "First viewing at Sotenbori Gandara auto-triggers a substory + starts the clerk's bond gauge." },
        { ko: "천량 거리 북쪽 간다라에서 이미지 비디오 3회 시청 후 입장하면 서브스토리 「비디오 걸」 발생.", en: "Watch any image video 3 times at the Senryo St. North Gandara then re-enter to trigger substory 'Video Girl'." },
        { ko: "점원 절 게이지가 90 이상일 때 비디오 시청 → 오디세이 창고 앞 흰 옷 여성과 대화 → M스토어 쇼후쿠초점에서 「오뎅 모듬」 구매 → 여성에게 전달 → 「예의 비디오(例のビデオ)」 입수.", en: "Affinity 90+: watch a video → talk to the white-dressed woman in front of the Odyssey warehouse → buy 'Oden Assortment' at M-Store Shofukucho → give it to her → obtain the 'Special Video'." },
    ],
    source: { label: "龍が如く0 攻略 — ガンダーラ・ビデオ", url: "https://spwiki.net/ryuzero/" },
    items: [
      {
        number: 1,
        title: { ko: "간다라 소텐보리점 — 첫 비디오 + 서브스토리", en: "Gandara Sotenbori — First Video + Substory" },
        location: { ko: "소텐보리 — 동쪽 골목", en: "Sotenbori — east alley" },
        body: { ko: "마지마 편 장 진행 후 입장 가능. 첫 비디오 시청 시 서브스토리 자동 발생.", en: "Accessible during Majima chapters. First viewing auto-triggers the venue substory." },
      },
      {
        number: 2,
        title: { ko: "간다라 천량 거리 북점 — 「비디오 걸」 서브스토리", en: "Gandara Senryo North — 'Video Girl' substory" },
        location: { ko: "카무로초 — 천량 거리 북쪽", en: "Kamurocho — Senryo St. North" },
        body: { ko: "키류 편. 이미지 비디오를 3회 시청한 뒤 점내 재입장 시 서브스토리 시작.", en: "Kiryu side. Watch any image video 3 times, then re-enter the shop." },
      },
      {
        number: 3,
        title: { ko: "점원 호감도 → 90 도달 시 특수 이벤트", en: "Clerk Affinity 90 → Special Event" },
        location: { ko: "간다라 양 지점", en: "Either Gandara branch" },
        body: { ko: "같은 이미지 비디오 반복 시청으로도 호감도 상승. 호감도 90 이상에서 다음 시청 시 컷신 트리거.", en: "Repeated viewings (even the same video) raise affinity. At 90+, the next viewing triggers a cutscene." },
      },
      {
        number: 4,
        title: { ko: "오디세이 창고 앞 흰 옷 여성 대화", en: "White-Dressed Woman at Odyssey Warehouse" },
        location: { ko: "소텐보리 — 오디세이 창고", en: "Sotenbori — Odyssey warehouse" },
        body: { ko: "특수 이벤트 후 등장. 「오뎅 모듬」을 요청하니 M스토어 쇼후쿠초점에서 구매해 전달.", en: "Appears after the special event. Buy 'Oden Assortment' at M-Store Shofukucho and bring it." },
      },
      {
        number: 5,
        title: { ko: "예의 비디오 — 최종 보상", en: "Special Video — Final Reward" },
        location: { ko: "간다라 (예의 비디오로 재시청)", en: "Gandara (replay 'Special Video')" },
        body: { ko: "오뎅 전달 후 받는 「예의 비디오」를 가지고 간다라에서 시청. 컴플리트 리스트 + 사이드 보상 발생.", en: "After receiving the 'Special Video', return to Gandara to watch it — completes the side reward + Completion List entry." },
        reward: { ko: "컴플리트 리스트 항목 + 절륜 친구 라인 활성화", en: "Completion List entry + bond friendship line activated" },
      },
    ],
  },
  ],
};
