import type { CollectiblesData } from "./types";

export const yakuzaKiwami: CollectiblesData = {
  appId: 3717330,
  categories: [
    {
      slug: "coin-lockers",
      title: { ko: "물품 보관함 — 카무로초 50개 열쇠와 보상", en: "Coin Lockers — Kamurocho's 50 Keys & Rewards" },
      summary: {
        ko: "카무로초에 흩어진 코인로커 열쇠 50개의 위치와 내용물을 정리했습니다. 보관함은 타이헤이 거리에 있습니다. 지도의 번호가 카드 번호와 일치합니다.",
        en: "All 50 Kamurocho coin-locker keys with locations and contents. The lockers sit on Taihei Blvd. Map numbers match the card numbers.",
      },
      tips: [
        { ko: "거리·건물 바닥에서 반짝이는 곳을 조사하면 열쇠를 얻습니다. 대부분 4장부터 회수 가능합니다.", en: "Investigate shining spots on the ground for keys. Most become available from Chapter 4." },
      ],
      source: { label: "ゲーム攻略マン — 龍が如く極 コインロッカーの鍵", url: "https://dswiipspwikips3.jp/yakuza-kiwami/cheats-data/coin-locker-key.html" },
      groups: [
        {
          title: { ko: "카무로초 — 50개 열쇠", en: "Kamurocho — 50 Keys" },
          mapImage: "https://dswiipspwikips3-images.jp/yakuza-kiwami/map-coin-locker-key.jpg",
          hotspots: {
            1: [28.0, 84.2], 2: [35.4, 98.7], 3: [82.4, 80.2], 4: [79.3, 56.2], 5: [17.6, 60.3], 6: [46.0, 70.9], 7: [15.2, 75.1], 8: [81.8, 69.4], 9: [12.2, 58.3], 10: [21.4, 19.3],
            12: [64.0, 68.9], 13: [28.3, 63.5], 14: [87.7, 68.8], 15: [37.4, 58.0], 16: [43.2, 76.0], 17: [66.4, 47.7], 18: [34.7, 45.4], 19: [60.6, 81.4], 20: [76.0, 97.7], 21: [21.7, 88.0],
            22: [65.5, 97.5], 23: [95.4, 58.6], 24: [28.3, 34.1], 25: [76.6, 88.4], 26: [48.0, 55.3], 27: [60.0, 88.1], 28: [11.1, 50.5], 29: [59.4, 93.3], 30: [59.4, 76.2], 31: [28.4, 53.2],
            32: [56.4, 43.6], 33: [40.7, 92.6], 34: [9.3, 65.8], 35: [35.3, 82.0], 36: [36.5, 87.1], 37: [19.9, 61.3], 38: [91.6, 94.8], 39: [66.3, 62.3], 40: [79.9, 52.0], 41: [55.8, 96.6],
            42: [19.6, 82.6], 44: [74.2, 18.2], 45: [85.9, 52.4], 46: [67.2, 78.6], 47: [7.5, 50.5], 48: [54.1, 69.5], 49: [44.7, 68.4],
          },
          items: [
        {
          number: 1,
          title: { ko: "A1 · 2장", en: "A1 · Ch.2" },
          location: { ko: "POPPO 천하일 거리점 앞 도로에 떨어져 있다", en: "On the road in front of POPPO Tenkaichi" },
          reward: { ko: "중세 은화", en: "Medieval Silver Coin" },
        },
        {
          number: 2,
          title: { ko: "A2 · 4장", en: "A2 · Ch.4" },
          location: { ko: "쇼와 거리 서쪽 인도의 파일론 2개 사이에 떨어져 있다", en: "Between two pylons on the West Showa St sidewalk" },
          reward: { ko: "불상", en: "Buddha Statue" },
        },
        {
          number: 3,
          title: { ko: "A3 · 4장", en: "A3 · Ch.4" },
          location: { ko: "천량 거리 자판기 아래 도로에 떨어져 있다", en: "Under the Senryo Ave vending machine" },
          reward: { ko: "공룡 화석", en: "Dinosaur Fossil" },
        },
        {
          number: 4,
          title: { ko: "A4 · 4장", en: "A4 · Ch.4" },
          location: { ko: "시치후쿠 파크 자판기 아래에 떨어져 있다", en: "Under the Shichifuku Park vending machine" },
          reward: { ko: "토우", en: "Clay Figure" },
        },
        {
          number: 5,
          title: { ko: "A5 · 4장", en: "A5 · Ch.4" },
          location: { ko: "데보라 댄스홀 1층 방 구석에 떨어져 있다", en: "In the corner of the Debolah dance hall 1F" },
          reward: { ko: "운석 조각", en: "Meteorite Fragment" },
        },
        {
          number: 6,
          title: { ko: "B1 · 4장", en: "B1 · Ch.4" },
          location: { ko: "타이헤이 거리 코인로커 옆에 떨어져 있다", en: "Beside the Taihei Blvd coin lockers" },
          reward: { ko: "대신 돌", en: "Decoy Stone" },
        },
        {
          number: 7,
          title: { ko: "B2 · 2장", en: "B2 · Ch.2" },
          location: { ko: "타이헤이 거리 서쪽 건물 모서리 도로에 떨어져 있다", en: "On the road at the West Taihei building corner" },
          reward: { ko: "너클", en: "Brass Knuckles" },
        },
        {
          number: 8,
          title: { ko: "B3 · 4장", en: "B3 · Ch.4" },
          location: { ko: "천량 거리 북쪽 도로에 떨어져 있다", en: "On the road north of Senryo Ave" },
          reward: { ko: "스카치 위스키", en: "Scotch Whisky" },
        },
        {
          number: 9,
          title: { ko: "B4 · 4장", en: "B4 · Ch.4" },
          location: { ko: "극장 앞 광장 인도 기둥 아래에 떨어져 있다", en: "Under the pillar on the Theater Square sidewalk" },
          reward: { ko: "핀조로의 패", en: "Pinzoro Tile" },
        },
        {
          number: 10,
          title: { ko: "B5 · 5장", en: "B5 · Ch.5" },
          location: { ko: "사이노카와라 지하 환락가 바닥에 떨어져 있다", en: "On the floor of the Sai no Kawara underground" },
          reward: { ko: "중세 회화", en: "Medieval Painting" },
        },
        {
          number: 11,
          title: { ko: "C1 · 5장", en: "C1 · Ch.5" },
          location: { ko: "서브스토리 42에서 입수", en: "From substory 42" },
          reward: { ko: "도스", en: "Dosu (Dagger)" },
        },
        {
          number: 12,
          title: { ko: "C2 · 4장", en: "C2 · Ch.4" },
          location: { ko: "밀레니엄 타워 동쪽 거리 바이크 근처 도로에 떨어져 있다", en: "On the road near the bike, Millennium Tower East St" },
          reward: { ko: "도스", en: "Dosu (Dagger)" },
        },
        {
          number: 13,
          title: { ko: "C3 · 2장", en: "C3 · Ch.2" },
          location: { ko: "극장 앞 광장 노란 세로 간판 두 기둥 아래에 떨어져 있다", en: "Under the two pillars of the yellow Theater Sq sign" },
          reward: { ko: "히후미 껌", en: "Hifumi Gum" },
        },
        {
          number: 14,
          title: { ko: "C4 · 4장", en: "C4 · Ch.4" },
          location: { ko: "챔피언 거리 건물 사이 좁은 통로에 떨어져 있다", en: "In the narrow passage between Champion District buildings" },
          reward: { ko: "아라시의 양갱", en: "Arashi's Yokan" },
        },
        {
          number: 15,
          title: { ko: "C5 · 2장", en: "C5 · Ch.2" },
          location: { ko: "극장 앞 거리 계단을 내려간 자판기 아래에 떨어져 있다", en: "Under the vending machine down the Theater Ave stairs" },
          reward: { ko: "스태미난 스파크", en: "Staminan Spark" },
        },
        {
          number: 16,
          title: { ko: "D1 · 4장", en: "D1 · Ch.4" },
          location: { ko: "나카미치 거리 모서리 인도에 떨어져 있다", en: "On the Nakamichi St corner sidewalk" },
          reward: { ko: "사라시", en: "Sarashi" },
        },
        {
          number: 17,
          title: { ko: "D2 · 4장", en: "D2 · Ch.4" },
          location: { ko: "공원 앞 거리 인도에 떨어져 있다", en: "On the Park Blvd sidewalk" },
          reward: { ko: "핏물 든 사라시", en: "Bloodstained Sarashi" },
        },
        {
          number: 18,
          title: { ko: "D3 · 4장", en: "D3 · Ch.4" },
          location: { ko: "요시다 배팅센터 아케이드 기기 쪽 바닥", en: "Floor by the arcade machines, Yoshida Batting Center" },
          reward: { ko: "싸움 사라시", en: "Brawler's Sarashi" },
        },
        {
          number: 19,
          title: { ko: "D4 · 4장", en: "D4 · Ch.4" },
          location: { ko: "나카미치 거리 뒤 바닥에 떨어져 있다", en: "On the ground behind Nakamichi St" },
          reward: { ko: "메탈 재킷", en: "Metal Jacket" },
        },
        {
          number: 20,
          title: { ko: "D5 · 4장", en: "D5 · Ch.4" },
          location: { ko: "쇼텐에 들어가 안쪽 바닥에 떨어져 있다", en: "On the back floor inside Shoten" },
          reward: { ko: "스프링 암", en: "Spring Arm" },
        },
        {
          number: 21,
          title: { ko: "E1 · 2장", en: "E1 · Ch.2" },
          location: { ko: "세레나 뒤 계단을 오른 문 아래에 떨어져 있다", en: "Under the door up the stairs behind Serena" },
          reward: { ko: "신사 우산", en: "Gentleman's Umbrella" },
        },
        {
          number: 22,
          title: { ko: "E2 · 4장", en: "E2 · Ch.4" },
          location: { ko: "핑크 거리 도로에 떨어져 있다", en: "On the Pink St road" },
          reward: { ko: "타우리너 맥시멈", en: "Tauriner Maximum" },
        },
        {
          number: 23,
          title: { ko: "E3 · 4장", en: "E3 · Ch.4" },
          location: { ko: "시치후쿠 거리 동쪽 자전거 근처 인도에 떨어져 있다", en: "On the sidewalk near the bike, East Shichifuku St" },
          reward: { ko: "숀벤 산맥의 돌", en: "Shonben Mountain Stone" },
        },
        {
          number: 24,
          title: { ko: "E4 · 4장", en: "E4 · Ch.4" },
          location: { ko: "호텔가 구석 도로에 떨어져 있다", en: "On the road in the Hotel District corner" },
          reward: { ko: "쵸고로의 염주", en: "Chogoro Beads" },
        },
        {
          number: 25,
          title: { ko: "E5 · 4장", en: "E5 · Ch.4" },
          location: { ko: "핑크 거리 뒤 좁은 통로 바닥에 떨어져 있다", en: "On the floor of the narrow passage behind Pink St" },
          reward: { ko: "쿨 스트라이커", en: "Cool Striker" },
        },
        {
          number: 26,
          title: { ko: "F1 · 4장", en: "F1 · Ch.4" },
          location: { ko: "시치후쿠 거리 크리스마스 트리 근처 도로에 떨어져 있다", en: "On the road near the Shichifuku St Christmas tree" },
          reward: { ko: "골드 슬래퍼", en: "Gold Slapper" },
        },
        {
          number: 27,
          title: { ko: "F2 · 4장", en: "F2 · Ch.4" },
          location: { ko: "나카미치 거리 뒤 모서리 도로에 떨어져 있다", en: "On the corner road behind Nakamichi St" },
          reward: { ko: "리페어 키트", en: "Repair Kit" },
        },
        {
          number: 28,
          title: { ko: "F3 · 4장", en: "F3 · Ch.4" },
          location: { ko: "아동 공원 식수대 아래에 떨어져 있다", en: "Under the children's park water fountain" },
          reward: { ko: "카타요리사의 담배", en: "Katayori Cigarettes" },
        },
        {
          number: 29,
          title: { ko: "F4 · 4장", en: "F4 · Ch.4" },
          location: { ko: "록란소 카운터 옆 바닥에 떨어져 있다", en: "On the floor beside the Rokuranso counter" },
          reward: { ko: "BANKER 말", en: "BANKER Piece" },
        },
        {
          number: 30,
          title: { ko: "F5 · 4장", en: "F5 · Ch.4" },
          location: { ko: "아카우시마루 타이헤이 거리점 안쪽 자리 바닥 (열쇠가 안 보이는 위치)", en: "Floor of the back seat in Akaushimaru (key is hidden)" },
          reward: { ko: "터프니스 인피니티", en: "Toughness Infinity" },
        },
        {
          number: 31,
          title: { ko: "G1 · 4장", en: "G1 · Ch.4" },
          location: { ko: "시치후쿠 거리 서쪽 도로에 떨어져 있다", en: "On the West Shichifuku St road" },
          reward: { ko: "슬래퍼", en: "Slapper" },
        },
        {
          number: 32,
          title: { ko: "G2 · 4장", en: "G2 · Ch.4" },
          location: { ko: "공원 앞 거리 모서리 도로에 떨어져 있다", en: "On the Park Blvd corner road" },
          reward: { ko: "PLAYER 말", en: "PLAYER Piece" },
        },
        {
          number: 33,
          title: { ko: "G3 · 4장", en: "G3 · Ch.4" },
          location: { ko: "킷사 알프스 안쪽 카운터 앞 바닥에 떨어져 있다", en: "On the floor before the back counter of Cafe Alps" },
          reward: { ko: "BJ의 부적", en: "BJ Charm" },
        },
        {
          number: 34,
          title: { ko: "G4 · 4장", en: "G4 · Ch.4" },
          location: { ko: "마하 볼 남자 화장실 입구 바닥에 떨어져 있다", en: "On the floor at the Mach Bowl men's room entrance" },
          reward: { ko: "버스트의 부적", en: "Burst Charm" },
        },
        {
          number: 35,
          title: { ko: "G5 · 4장", en: "G5 · Ch.4" },
          location: { ko: "천하일 거리 뒷골목 쌓인 골판지 근처 바닥에 떨어져 있다", en: "Near the stacked cardboard in the Tenkaichi back alley" },
          reward: { ko: "버티기 돌", en: "Footing Stone" },
        },
        {
          number: 36,
          title: { ko: "H1 · 4장", en: "H1 · Ch.4" },
          location: { ko: "제3공원 놀이기구 아래에 떨어져 있다", en: "Under the Third Park playground equipment" },
          reward: { ko: "스턴건", en: "Stun Gun" },
        },
        {
          number: 37,
          title: { ko: "H2 · 2장", en: "H2 · Ch.2" },
          location: { ko: "극장 앞 광장 「카무로 유니버설 시어터」 간판 아래 도로에 떨어져 있다", en: "Under the Kamuro Universal Theater sign, Theater Square" },
          reward: { ko: "검은 보석", en: "Black Gem" },
        },
        {
          number: 38,
          title: { ko: "H3 · 4장", en: "H3 · Ch.4" },
          location: { ko: "천량 거리 세이브 포인트 근처 도로에 떨어져 있다", en: "On the road near the Senryo Ave save point" },
          reward: { ko: "로열 조커", en: "Royal Joker" },
        },
        {
          number: 39,
          title: { ko: "H4 · 4장", en: "H4 · Ch.4" },
          location: { ko: "핑크 거리 북쪽 빔 근처 도로에 떨어져 있다", en: "On the road near Beam, north Pink St" },
          reward: { ko: "행운 화투", en: "Lucky Hanafuda" },
        },
        {
          number: 40,
          title: { ko: "H5 · 4장", en: "H5 · Ch.4" },
          location: { ko: "빈센트의 방 구석 바닥에 떨어져 있다", en: "On the floor in the corner of Vincent's room" },
          reward: { ko: "루비 접시", en: "Ruby Plate" },
        },
        {
          number: 41,
          title: { ko: "I1 · 4장", en: "I1 · Ch.4" },
          location: { ko: "나카미치 거리 뒤 공터에 떨어져 있다", en: "In the vacant lot behind Nakamichi St" },
          reward: { ko: "무의 보석", en: "Void Gem" },
        },
        {
          number: 42,
          title: { ko: "I2 · 2장", en: "I2 · Ch.2" },
          location: { ko: "슷폰 거리 자전거 근처 도로에 떨어져 있다", en: "On the road near the bike on Suppon St" },
          reward: { ko: "짜고치기 패", en: "Loaded Tile" },
        },
        {
          number: 43,
          title: { ko: "I3 · 4장", en: "I3 · Ch.4" },
          location: { ko: "서브스토리 23에서 입수", en: "From substory 23" },
          reward: { ko: "개조 모델건", en: "Modified Model Gun" },
        },
        {
          number: 44,
          title: { ko: "I4 · 5장", en: "I4 · Ch.5" },
          location: { ko: "사이노카와라(서공원) 파란 철책 쪽에 떨어져 있다", en: "By the blue fence in Sai no Kawara (West Park)" },
          reward: { ko: "대리석 진주", en: "Marble Pearl" },
        },
        {
          number: 45,
          title: { ko: "I5 · 4장", en: "I5 · Ch.4" },
          location: { ko: "공원 앞 거리 뒤 막다른 곳에 떨어져 있다", en: "At the dead end behind Park Blvd" },
          reward: { ko: "도싯핀즈", en: "Doshippins" },
        },
        {
          number: 46,
          title: { ko: "J1 · 4장", en: "J1 · Ch.4" },
          location: { ko: "타이헤이 거리 동쪽 고토부키 약국 근처 도로에 떨어져 있다", en: "On the road near Kotobuki Pharmacy, East Taihei Blvd" },
          reward: { ko: "금속 배트", en: "Metal Bat" },
        },
        {
          number: 47,
          title: { ko: "J2 · 4장", en: "J2 · Ch.4" },
          location: { ko: "포케서 스타디움 테이블 아래쯤에 떨어져 있다", en: "Around under the table at Pocket Circuit Stadium" },
          reward: { ko: "메탈 핀", en: "Metal Fin" },
        },
        {
          number: 48,
          title: { ko: "J3 · 4장", en: "J3 · Ch.4" },
          location: { ko: "밀레니엄 타워 앞뜰 화단 근처 경사 바닥에 떨어져 있다", en: "On the slope near the Millennium Tower front-garden planter" },
          reward: { ko: "항복 말", en: "Surrender Piece" },
        },
        {
          number: 49,
          title: { ko: "J4 · 7장", en: "J4 · Ch.7" },
          location: { ko: "도박장 복도 맨 안쪽 바닥에 떨어져 있다", en: "On the floor at the back of the gambling den hall" },
          reward: { ko: "다이아몬드 접시", en: "Diamond Plate" },
        },
        {
          number: 50,
          title: { ko: "J5 · 6장", en: "J5 · Ch.6" },
          location: { ko: "서브스토리 43에서 입수", en: "From substory 43" },
          reward: { ko: "카리스마의 사진", en: "Charisma Photo" },
        },
          ],
        },
      ],
    },
  ],
};
